)F Function - The CORE command allows the display of various
  parts of storage.  All addressing is based on your address
  space, so only nucleus, LPA, CSA, SQA, LSQA, and your currently
  allocated private areas may be displayed.
)X SYNTAX - CORE
)O OPERANDS -
))ADDRESS    - Location to be displayed (256 bytes at a time).
))PFKS       - PFK 7      - Backup 256 bytes.
               PFK 8      - Forward 256 bytes.
               PFK 9      - Redisplay the same area again.
               PA1 (ATTN) - Terminate.
