         TITLE ' IEAVADFM - USER FORMAT CSECT                          *
                        '
IEAVADFM CSECT ,                                                   0001
@PROLOG  DS    0H                                                  0002
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
        DC    XL4'00000000'
*   END IEAVADFM;                                                  0003
@EL00001 DS    0H                                                  0003
@EF00001 DS    0H                                                  0003
@ER00001 BR    @14                                                 0003
@DATA    DS    0H
@DATD    DSECT
         DS    0F
IEAVADFM CSECT
         DS    0F
@DATD    DSECT
         DS    0D
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
IEAVADFM CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
         DS    0D
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
@ENDDATA EQU   *
         END   IEAVADFM,(C'PLS0034',0701,77005)
