         TITLE '**********  ICKVA01:  OBTAIN VOLUME AUTHORIZATION  *****
               *********'
        MACRO
        GETMAIN &R,&LV=
        L     REG15,0(REG1)           GDTTBL ADDRESS
        L     REG15,GDTPRL(REG15)     PROL ROUTINE ADDRESS
        CNOP  2,4                     BOUNDARY ALIGNMENT
        LA    REG14,*+14              RETURN ADDRESS
        BALR  REG1,REG15              LINKAGE TO PROL ROUTINE
        DC    A(MODID)                MODULE ID ADDRESS
        DC    A(@SIZDATD)             AUTOMATIC STORAGE SIZE ADDRESS
        MEND
ICKVA01  CSECT ,                                                   0002
@MAINENT DS    0H                                                  0002
         USING *,@15                                               0002
         B     @PROLOG                                             0002
         DC    AL1(16)                                             0002
         DC    C'ICKVA01   78.192'                                 0002
         DROP  @15
@PROLOG  STM   @14,@12,12(@13)                                     0002
         BALR  @12,0                                               0002
@PSTART  DS    0H                                                  0002
         USING @PSTART,@12                                         0002
         L     @00,@SIZDATD                                        0002
         GETMAIN  R,LV=(0)
         LR    @11,@01                                             0002
         USING @DATD,@11                                           0002
         ST    @13,@SA00001+4                                      0002
         LM    @00,@01,20(@13)                                     0002
         ST    @11,8(,@13)                                         0002
         LR    @13,@11                                             0002
         XC    @ZTEMPS(@ZLEN),@ZTEMPS
         MVC   @PC00001(12),0(@01)                                 0002
*                                                                  0176
         EJECT
*/*****  B E G I N    E X E C U T I O N  *****************************/
*                                                                  0177
*    IF GDTDBG = NULLPTR                                           0177
*      THEN;                                                       0177
         L     @10,@PC00001                                        0177
         L     @10,GDTDBG(,@10)                                    0177
         LTR   @10,@10                                             0177
         BZ    @RT00177                                            0177
*      ELSE                                                        0179
*        CALL ICKDB010 (GDTTBL, 'VA00');                           0179
*                                                                  0179
*                                                                  0179
         L     @10,@PC00001                                        0179
         ST    @10,@AL00001                                        0179
         LA    @15,@CC00515                                        0179
         ST    @15,@AL00001+4                                      0179
         MVI   @AL00001+4,X'80'                                    0179
         L     @15,GDTDBG(,@10)                                    0179
         LA    @01,@AL00001                                        0179
         BALR  @14,@15                                             0179
*/*  ESTABLISH UPRINT ARGUMENT LIST                                  */
*    PRTHDR = 'DARGLIST';                                          0180
@RT00177 MVC   PRTHDR(8),@CC00516                                  0180
*    DDSTRU = ADDR(PRTARGS);                                       0181
         LA    @10,PRTARGS                                         0181
         ST    @10,DDSTRU                                          0181
*    PRTARGS = ''B;                                                0182
         XC    PRTARGS(20),PRTARGS                                 0182
*    DARGSMOD = MSGMODZ;                                           0183
         MVC   DARGSMOD(3,@10),@CC00482                            0183
*/*  INDICATE SUCCESSFUL COMPLETION INITIALLY                        */
*    CONDCODE = SUCCEEDS;                                          0184
         L     @10,@PC00001+8                                      0184
         SLR   @15,@15                                             0184
         ST    @15,CONDCODE(,@10)                                  0184
*/*  OBTAIN THE FLAG WHICH INDICATES IF VOLUME IS BEING PROCESSED    */
*/*   OFF-LINE OR ON-LINE (UDEVINFO)                                 */
*    CALL ICKDVIN0 (GDTTBL                                         0185
*             ,VOLIB                                               0185
*             ,VOLSTATE                                            0185
*             ,POOLID                                              0185
*             ,VLNPTR                                              0185
*             ,VLNLEN                                              0185
*             ,RETCODE);                                           0185
         L     @10,@PC00001                                        0185
         ST    @10,@AL00001                                        0185
         L     @15,@PC00001+4                                      0185
         ST    @15,@AL00001+4                                      0185
         LA    @15,@CF00040                                        0185
         ST    @15,@AL00001+8                                      0185
         LA    @15,POOLID                                          0185
         ST    @15,@AL00001+12                                     0185
         LA    @15,VLNPTR                                          0185
         ST    @15,@AL00001+16                                     0185
         LA    @15,VLNLEN                                          0185
         ST    @15,@AL00001+20                                     0185
         LA    @15,RETCODE                                         0185
         ST    @15,@AL00001+24                                     0185
         L     @15,GDTDIN(,@10)                                    0185
         LA    @01,@AL00001                                        0185
         BALR  @14,@15                                             0185
*/*  IF THE VOLUME IS BEING PROCESSED OFF-LINE                       */
*    IF LINEFLAG = OFFLINE                                         0186
*/*    THEN                                                          */
*      THEN DO;                                                    0186
*                                                                  0186
         L     @10,VLNPTR                                          0186
         TM    LINEFLAG(@10),B'10000000'                           0186
         BNZ   @RF00186                                            0186
*        REPLY = 'X';                                              0188
         MVI   REPLY,C'X'                                          0188
*/*      DO-WHILE PROPER REPLY IS NOT OBTAINED                       */
*        DO WHILE (REPLY ^= 'T') & (REPLY ^= 'U');                 0189
*                                                                  0189
         B     @DE00189                                            0189
@DL00189 DS    0H                                                  0190
*/*        ISSUE MESSAGE TO ACQUIRE PERMISSION TO PROCESS VOLUME     */
*/*         (UWTO)                                                   */
*          CALL ICKDVIN0 (GDTTBL                                   0190
*                   ,VOLIB                                         0190
*                   ,VOLCUU                                        0190
*                   ,POOLID                                        0190
*                   ,VLNPTR                                        0190
*                   ,VLNLEN                                        0190
*                   ,RETCODE);                                     0190
         L     @10,@PC00001                                        0190
         ST    @10,@AL00001                                        0190
         L     @15,@PC00001+4                                      0190
         ST    @15,@AL00001+4                                      0190
         LA    @15,@CF00112                                        0190
         ST    @15,@AL00001+8                                      0190
         LA    @15,POOLID                                          0190
         ST    @15,@AL00001+12                                     0190
         LA    @15,VLNPTR                                          0190
         ST    @15,@AL00001+16                                     0190
         LA    @15,VLNLEN                                          0190
         ST    @15,@AL00001+20                                     0190
         LA    @15,RETCODE                                         0190
         ST    @15,@AL00001+24                                     0190
         L     @15,GDTDIN(,@10)                                    0190
         LA    @01,@AL00001                                        0190
         BALR  @14,@15                                             0190
*          PERMIT = PERMITM;                                       0191
         MVC   PERMIT(52),@CC00498                                 0191
*          PERMITB = DEVADDR;                                      0192
         MVI   PERMITB+3,C' '                                      0192
         L     @10,VLNPTR                                          0192
         MVC   PERMITB(3),DEVADDR(@10)                             0192
*          CALL ICKSAWO0  (GDTTBL                                  0193
*                ,PERMILEN                                         0193
*                ,ADDR (PERMIT)                                    0193
*                ,NOROUT                                           0193
*                ,NODESC                                           0193
*                ,REPLYLEN                                         0193
*                ,ADDR (REPLY));                                   0193
         MVC   @AL00001+4(20),@AL00193                             0193
         L     @10,@PC00001                                        0193
         ST    @10,@AL00001                                        0193
         LA    @15,PERMIT                                          0193
         ST    @15,@AFTEMPS                                        0193
         LA    @15,@AFTEMPS                                        0193
         ST    @15,@AL00001+8                                      0193
         LA    @15,REPLY                                           0193
         ST    @15,@AFTEMPS+4                                      0193
         LA    @15,@AFTEMPS+4                                      0193
         ST    @15,@AL00001+24                                     0193
         MVI   @AL00001+24,X'80'                                   0193
         L     @15,GDTWTO(,@10)                                    0193
         LA    @01,@AL00001                                        0193
         BALR  @14,@15                                             0193
*/*        IF PERMISSION NOT GRANTED                                 */
*          IF REPLY = 'T'                                          0194
*/*          THEN                                                    */
*            THEN DO;                                              0194
*                                                                  0194
         CLI   REPLY,C'T'                                          0194
         BNE   @RF00194                                            0194
*/*            ISSUE MESSAGE ABOUT TERMINATION (MSGTERM) (UPRINT)    */
*              DARGSENT = MSGTERM;                                 0196
         L     @10,DDSTRU                                          0196
         MVI   DARGSENT(@10),X'31'                                 0196
*              CALL ICKTPPR0 (GDTTBL                               0197
*                     ,PRTFILE                                     0197
*                     ,DDSTRU);                                    0197
         L     @10,@PC00001                                        0197
         ST    @10,@AL00001                                        0197
         LA    @15,@CF00090                                        0197
         ST    @15,@AL00001+4                                      0197
         LA    @15,DDSTRU                                          0197
         ST    @15,@AL00001+8                                      0197
         MVI   @AL00001+8,X'80'                                    0197
         L     @15,GDTPRT(,@10)                                    0197
         LA    @01,@AL00001                                        0197
         BALR  @14,@15                                             0197
*/*            INDICATE UNSUCCESSFUL COMPLETION                      */
*              CONDCODE = FAILS;                                   0198
         L     @10,@PC00001+8                                      0198
         MVC   CONDCODE(4,@10),@CF00161                            0198
*/*            END-THEN                                              */
*              END;                                                0199
*/*      END-WHILE                                                   */
*        END;                                                      0200
@RF00194 DS    0H                                                  0200
@DE00189 CLI   REPLY,C'T'                                          0200
         BE    @DC00189                                            0200
         CLI   REPLY,C'U'                                          0200
         BNE   @DL00189                                            0200
@DC00189 DS    0H                                                  0201
*/*      END-THEN (VOLUME BEING PROCESSED OFF-LINE)                  */
*        END;                                                      0201
*/*  END-PROCEDURE OBTAIN_VOLUME_AUTHORIZATION                       */
*    IF GDTDBG = NULLPTR                                           0202
*      THEN;                                                       0202
@RF00186 L     @10,@PC00001                                        0202
         L     @10,GDTDBG(,@10)                                    0202
         LTR   @10,@10                                             0202
         BZ    @RT00202                                            0202
*      ELSE                                                        0204
*        CALL ICKDB010 (GDTTBL                                     0204
*          ,'VA99');                                               0204
         L     @10,@PC00001                                        0204
         ST    @10,@AL00001                                        0204
         LA    @15,@CC00522                                        0204
         ST    @15,@AL00001+4                                      0204
         MVI   @AL00001+4,X'80'                                    0204
         L     @15,GDTDBG(,@10)                                    0204
         LA    @01,@AL00001                                        0204
         BALR  @14,@15                                             0204
*    CALL ICKSAFP0 (GDTTBL                                         0205
*           ,POOLID);                                              0205
@RT00202 L     @10,@PC00001                                        0205
         ST    @10,@AL00001                                        0205
         LA    @15,POOLID                                          0205
         ST    @15,@AL00001+4                                      0205
         MVI   @AL00001+4,X'80'                                    0205
         L     @15,GDTFPL(,@10)                                    0205
         LA    @01,@AL00001                                        0205
         BALR  @14,@15                                             0205
*    CALL ICKSAEP0(GDTTBL,MODID);                                  0206
*                                                                  0206
*                                                                  0206
         L     @10,@PC00001                                        0206
         ST    @10,@AL00001                                        0206
         LA    @15,MODID                                           0206
         ST    @15,@AL00001+4                                      0206
         MVI   @AL00001+4,X'80'                                    0206
         L     @15,GDTEPL(,@10)                                    0206
         LA    @01,@AL00001                                        0206
         BALR  @14,@15                                             0206
*    END ICKVA01                                                   0207
*/* THE FOLLOWING INCLUDE STATEMENTS WERE FOUND IN THIS PROGRAM.      *
*/*%INCLUDE SYSLIB  (DMSDF01 )                                        *
*/*%INCLUDE SYSLIB  (DMSDF00 )                                        *
*/*@INCLUDE SYSLIB  (DMSDF02 )                                        *
*;                                                                 0207
@DATA    DS    0H
         DS    0F
@AL00193 DC    A(PERMILEN)             LIST WITH   5 ARGUMENT(S)
         DS    F
         DC    A(NOROUT)
         DC    A(NODESC)
         DC    A(REPLYLEN)
@DATD    DSECT
         DS    0F
@SA00001 DS    18F
@PC00001 DS    3F
@AL00001 DS    7A
@AFTEMPS DS    2F
@ZTEMPS  DS    C
@ZTEMPND EQU   *
@ZLEN    EQU   @ZTEMPND-@ZTEMPS
ICKVA01  CSECT
         DS    0F
@CF00090 DC    F'0'
@CF00161 DC    F'1'
@CF00112 DC    F'2'
@CF00040 DC    F'4'
@DATD    DSECT
         DS    0D
LISTSCAN DS    A
IOCSPTR  DS    A
OPNPTR   DS    A
DDSTRU   DS    A
FSADDR   DS    A
DMPINDEX DS    A
VLNPTR   DS    A
VLNLEN   DS    F
RETCODE  DS    F
I        DS    F
LISTPTR  DS    A
VOLTYPE  DS    F
SETRC    DS    H
TESTRC   DS    H
LISTLN   DS    FL1
         DS    CL3
PRTSTR   DS    CL28
         ORG   PRTSTR
PRTHDR   DS    CL8
PRTARGS  DS    CL20
         ORG   PRTSTR+28
PERMIT   DS    CL52
         ORG   PERMIT
PERMITA  DS    CL32
PERMITB  DS    CL4
PERMITC  DS    CL16
         ORG   PERMIT+52
REPLY    DS    CL1
VOLNAME  DS    CL3
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
ICKVA01  CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
         DS    0D
PERMILEN DC    AL2(52)
NOROUT   DC    AL2(0)
NODESC   DC    AL2(0)
REPLYLEN DC    AL1(1)
@CC00498 DC    C'ICK003D REPLY U TO PURGE VOLUME XXX CONTENTS, ELSE T'
@CC00516 DC    C'DARGLIST'
@CC00515 DC    C'VA00'
@CC00522 DC    C'VA99'
@CC00482 DC    C'EF0'
MODID    DC    CL4'VA01'
POOLID   DC    CL4'VA01'
PTCHVA01 DS    CL256
         ORG   PTCHVA01
@NM00018 DC    256X'00'
         ORG   PTCHVA01+256
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
REG12    EQU   @12
REG0     EQU   @00
REG1     EQU   @01
REG10    EQU   @10
REG11    EQU   @11
REG13    EQU   @13
REG14    EQU   @14
REG15    EQU   @15
REG2     EQU   @02
REG3     EQU   @03
REG4     EQU   @04
REG5     EQU   @05
REG6     EQU   @06
REG7     EQU   @07
REG8     EQU   @08
REG9     EQU   @09
RTNREG   EQU   @15
ICKSAEP0 EQU   0
ICKSAFP0 EQU   0
ICKSAWO0 EQU   0
TRACE1   EQU   0
OLDERID1 EQU   TRACE1
TRACE2   EQU   0
STAEPARM EQU   0
STAEPFX  EQU   STAEPARM
IOCSTR   EQU   0
IOCDSO   EQU   IOCSTR+13
IOCRFM   EQU   IOCSTR+14
IOCMAC   EQU   IOCSTR+15
IOCMSG   EQU   IOCSTR+16
OPNAGL   EQU   0
OPNOPT   EQU   OPNAGL
OPNRFM   EQU   OPNAGL+1
OPNTYP   EQU   OPNAGL+2
OPNMOD   EQU   OPNAGL+3
UVOLLIST EQU   0
UVOLENT  EQU   UVOLLIST+2
ICKDVIN0 EQU   0
ICKTPPR0 EQU   0
DARGLIST EQU   0
DARGSTID EQU   DARGLIST+8
DARGSMOD EQU   DARGSTID
DARGSENT EQU   DARGSTID+3
DARGARY  EQU   DARGLIST+20
DARGINS  EQU   DARGARY
DARGINL  EQU   DARGARY+2
FMTLIST  EQU   0
FMTFLGS  EQU   FMTLIST
FMTSPF   EQU   FMTLIST+2
FMTRFNO  EQU   FMTSPF
FMTILEN  EQU   FMTRFNO
FMTIOFF  EQU   FMTLIST+4
FMTTRBC  EQU   FMTIOFF
FMTSTO   EQU   FMTTRBC
FMTOCOL  EQU   FMTLIST+6
FMTCNVF  EQU   FMTLIST+10
ICKDB010 EQU   0
DMPITM   EQU   0
DMPARY   EQU   0
LINEFLAG EQU   0
DEVADDR  EQU   0
DMPTRM   EQU   0
ICKDVCL0 EQU   0
ICKDVON0 EQU   0
ICKDVOP0 EQU   0
ICKIOCL0 EQU   0
ICKIOGT0 EQU   0
ICKIOIT0 EQU   0
ICKIOOP0 EQU   0
ICKIOPT0 EQU   0
ICKIOTM0 EQU   0
ICKSACL0 EQU   0
ICKSADE0 EQU   0
ICKSAFS0 EQU   0
ICKSAGP0 EQU   0
ICKSAGS0 EQU   0
ICKSALD0 EQU   0
ICKSAPR0 EQU   0
ICKSASC0 EQU   0
ICKSASN0 EQU   0
ICKSAST0 EQU   0
ICKSATI0 EQU   0
ICKSAVC0 EQU   0
ICKTPEA0 EQU   0
ICKTPES0 EQU   0
ICKTPRE0 EQU   0
ICKTPRS0 EQU   0
LISTTEST EQU   0
NEWERID1 EQU   5
NEWERID2 EQU   5
GDTTBL   EQU   0
GDTTR1   EQU   GDTTBL+8
GDTTR2   EQU   GDTTBL+12
GDTDIN   EQU   GDTTBL+44
GDTDOP   EQU   GDTTBL+48
GDTDBG   EQU   GDTTBL+52
GDTDVO   EQU   GDTTBL+56
GDTPRT   EQU   GDTTBL+60
GDTESS   EQU   GDTTBL+64
GDTESA   EQU   GDTTBL+68
GDTRST   EQU   GDTTBL+72
GDTRES   EQU   GDTTBL+76
GDTCAL   EQU   GDTTBL+80
GDTGSP   EQU   GDTTBL+84
GDTFSP   EQU   GDTTBL+88
GDTGPL   EQU   GDTTBL+92
GDTFPL   EQU   GDTTBL+96
GDTLOD   EQU   GDTTBL+100
GDTDEL   EQU   GDTTBL+104
GDTPRL   EQU   GDTTBL+108
GDTEPL   EQU   GDTTBL+112
GDTTIM   EQU   GDTTBL+116
GDTIIO   EQU   GDTTBL+120
GDTTIO   EQU   GDTTBL+124
GDTOPN   EQU   GDTTBL+136
GDTCLS   EQU   GDTTBL+140
GDTGET   EQU   GDTTBL+144
GDTPUT   EQU   GDTTBL+148
GDTSNP   EQU   GDTTBL+160
GDTWTO   EQU   GDTTBL+168
GDTSCR   EQU   GDTTBL+172
GDTVCK   EQU   GDTTBL+176
GDTDVC   EQU   GDTTBL+180
GDTSTE   EQU   GDTTBL+188
VOLIB    EQU   0
CONDCODE EQU   0
         AGO   .@UNREFD                START UNREFERENCED COMPONENTS
GDTCVR   EQU   GDTTBL+184
GDTSPR   EQU   GDTTBL+164
GDTABH   EQU   GDTTBL+156
GDTABT   EQU   GDTTBL+152
GDTTOH   EQU   GDTTBL+132
GDTRIP   EQU   GDTTBL+128
GDTDVH   EQU   GDTTBL+40
GDTIOH   EQU   GDTTBL+36
GDTSAH   EQU   GDTTBL+32
GDTTPH   EQU   GDTTBL+28
GDTRIH   EQU   GDTTBL+24
GDTSTH   EQU   GDTTBL+20
GDTDBH   EQU   GDTTBL+16
GDTPRM   EQU   GDTTBL+4
GDTHDR   EQU   GDTTBL
@NM00017 EQU   DMPARY+15
DMPARYTP EQU   DMPARY+14
DMPARYEX EQU   DMPARY+12
DMPARYIC EQU   DMPARY+10
DMPARYSZ EQU   DMPARY+8
DMPARYNM EQU   DMPARY
@NM00016 EQU   DMPITM+15
DMPITMTP EQU   DMPITM+14
DMPITMLN EQU   DMPITM+12
DMPITMPT EQU   DMPITM+8
DMPITMNM EQU   DMPITM
@NM00015 EQU   FMTCNVF+1
FMTBS    EQU   FMTCNVF+1
FMTSS    EQU   FMTCNVF+1
FMTAL    EQU   FMTCNVF+1
FMTZS    EQU   FMTCNVF+1
@NM00014 EQU   FMTCNVF
FMTPU    EQU   FMTCNVF
FMTBD    EQU   FMTCNVF
FMTBHD   EQU   FMTCNVF
FMTBHA   EQU   FMTCNVF
FMTBH    EQU   FMTCNVF
FMTOLEN  EQU   FMTLIST+8
FMTRIO   EQU   FMTOCOL
FMTSPT   EQU   FMTSTO
FMTSTL   EQU   FMTILEN
@NM00013 EQU   FMTFLGS+1
FMTHDF   EQU   FMTFLGS
FMTDFF   EQU   FMTFLGS
FMTSTF   EQU   FMTFLGS
FMTREPF  EQU   FMTFLGS
FMTBDF   EQU   FMTFLGS
FMTIDF   EQU   FMTFLGS
FMTSCF   EQU   FMTFLGS
FMTEOLF  EQU   FMTFLGS
DARGDTM  EQU   DARGARY+4
DARGPCT  EQU   DARGINL
DARGREP  EQU   DARGINS
@NM00012 EQU   DARGLIST+19
DARGIND  EQU   DARGLIST+18
DARGRETL EQU   DARGLIST+16
DARGCNT  EQU   DARGLIST+14
DARGILP  EQU   DARGLIST+12
DARGRETP EQU   DARGLIST+4
DARGDBP  EQU   DARGLIST
UVOLVOL  EQU   UVOLENT+4
UVOLDEV  EQU   UVOLENT
UVOLCNT  EQU   UVOLLIST
OPNRSVD  EQU   OPNAGL+28
OPNVOL   EQU   OPNAGL+24
OPNBLK   EQU   OPNAGL+20
OPNREC   EQU   OPNAGL+16
OPNDSN   EQU   OPNAGL+12
OPNDDN   EQU   OPNAGL+8
OPNIOC   EQU   OPNAGL+4
@NM00011 EQU   OPNMOD
OPNMODRC EQU   OPNMOD
OPNMODAC EQU   OPNMOD
@NM00010 EQU   OPNTYP
OPNTYPSO EQU   OPNTYP
OPNTYPSI EQU   OPNTYP
@NM00009 EQU   OPNRFM
OPNRFMBK EQU   OPNRFM
OPNRFMSF EQU   OPNRFM
OPNRFMUN EQU   OPNRFM
OPNRFMVR EQU   OPNRFM
OPNRFMFX EQU   OPNRFM
@NM00008 EQU   OPNOPT
OPNOPTJM EQU   OPNOPT
OPNOPTKS EQU   OPNOPT
OPNOPTBK EQU   OPNOPT
OPNOPTUP EQU   OPNOPT
OPNOPTOT EQU   OPNOPT
OPNOPTIN EQU   OPNOPT
IOCEXT   EQU   IOCSTR+36
IOCRRN   EQU   IOCSTR+32
@NM00007 EQU   IOCSTR+30
IOCPNM   EQU   IOCSTR+28
IOCCBP   EQU   IOCSTR+24
IOCDSN   EQU   IOCSTR+20
@NM00006 EQU   IOCSTR+17
@NM00005 EQU   IOCMSG
IOCMSGOP EQU   IOCMSG
IOCMACPA EQU   IOCMAC
@NM00004 EQU   IOCMAC
IOCMACBK EQU   IOCMAC
IOCMACUP EQU   IOCMAC
IOCMACOT EQU   IOCMAC
IOCMACIN EQU   IOCMAC
@NM00003 EQU   IOCRFM
IOCRFMBK EQU   IOCRFM
IOCRFMSF EQU   IOCRFM
IOCRFMUN EQU   IOCRFM
IOCRFMVR EQU   IOCRFM
IOCRFMFX EQU   IOCRFM
@NM00002 EQU   IOCDSO
IOCDSOPS EQU   IOCDSO
IOCKYL   EQU   IOCSTR+12
IOCTRN   EQU   IOCSTR+8
IOCDLN   EQU   IOCSTR+4
IOCDAD   EQU   IOCSTR
STAEWORK EQU   STAEPARM+32
STARPTR  EQU   STAEPFX+28
STASPTR  EQU   STAEPFX+24
STALEN   EQU   STAEPFX+20
STAID    EQU   STAEPFX+16
STAEPA   EQU   STAEPFX+12
STAGDT   EQU   STAEPFX+8
STABPTR  EQU   STAEPFX+4
STAFPTR  EQU   STAEPFX
NEWID2   EQU   TRACE2+95
OLDERID2 EQU   TRACE2
NEWID1   EQU   TRACE1+95
CALLID   EQU   OLDERID1+90
@NM00001 EQU   OLDERID1
.@UNREFD ANOP                          END UNREFERENCED COMPONENTS
@ENDDATA EQU   *
         END   ICKVA01,(C'PLS1819',0701,78192)
