**************************************************************
*                                                            *
* NAME: BSPLIN01                                             *
*                                                            *
* TYPE: ASSEMBLER SOURCE                                     *
*                                                            *
* DESC: VTAM LOGON INTERPRET TABLE                           *
*                                                            *
**************************************************************
BSPLIN01 INTAB
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Tso'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='tso'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='TSO'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Logon'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='logon'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='LOGON'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='IBMUSER'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='ibmuser'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Ibmuser'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Herc01'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='herc01'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='HERC01'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Herc02'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='herc02'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='HERC02'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Herc03'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='herc03'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='HERC03'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='Herc04'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='herc04'
         LOGCHAR APPLID=(APPLICID,TSO),SEQNCE='HERC04'
         ENDINTAB
         END
