PROGRAM ACKERMANN(OUTPUT) ;
CONST NLIM = 6 ;   MLIM = 6 ;   (* LIMITS OF FUNCTION DOMAIN *)
TYPE  SHRTINT = 0..20 ;
VAR   N, M : SHRTINT ;

FUNCTION ACK(N, M : INTEGER ): INTEGER ;
   BEGIN
   IF M = 0 THEN ACK := N+1
   ELSE
      IF N = 0 THEN  ACK := ACK(1, M-1)
      ELSE   ACK := ACK( ACK(N-1,M) ,  M-1) ;
   END (*ACK*) ;

BEGIN
WRITE(OUTPUT, '      ') ;
FOR N := 0 TO NLIM DO WRITE(OUTPUT, '   ', N:4, '    ') ;
WRITELN(OUTPUT) ;   WRITELN(OUTPUT) ;
FOR M := 0 TO MLIM DO
   BEGIN    WRITELN(OUTPUT) ;   WRITE(M:5, ')') ;
   FOR N := 0 TO NLIM DO  WRITE( ACK(N,M):12 ) ;
   WRITELN( OUTPUT)
   END ;
END .
