//***FILE 409 contains the card image members associated with the   *
//*           MXI package from Rob Scott, of Scott Enterprise       *
//*           Consultancy, Ltd. in England.  The MXI package is     *
//*           a type of system monitor that can run under ISPF,     *
//*           in batch, or it can be invoked under REXX.            *
//*                                                                 *
//*                For up to date information please see the        *
//*                SEC website : www.secltd.co.uk                   *
//*                                                                 *
//*                Any problems, comments or suggestions            *
//*                please e-mail : info@secltd.co.uk                *
//*                                                                 *
//* --------------------------------------------------------------- *
//*                                                                 *
//*  Version 2.2a   enhancements                                    *
//*                                                                 *
//*  (1) Ability to issue operator commands                         *
//*  (2) Ability to change the swappability of any address          *
//*      space                                                      *
//*  (3) Addition of the JOB() and ASID() keywords to the TCB       *
//*      and CDE commands (ie they now work x-memory).              *
//*  (4) Addition of a security table for authorized commands       *
//*      (required if (1) and (2) exist!).                          *
//*  (5) Ability to list online channel paths                       *
//*                                                                 *
//* --------------------------------------------------------------- *
//*                                                                 *
//*  MXI (MVS eXtended Information) is an ISPF-based application    *
//*  that enables the MVS Systems Programmer to display important   *
//*  configuration information about the active MVS system.         *
//*                                                                 *
//*  Although primarily used online, MXI can be run in batch and    *
//*  also has a REXX interface.                                     *
//*                                                                 *
//*  Most of the displays can be filtered using ISPF-like masking   *
//*  characters and many display fields are 'point-and-shoot'.      *
//*                                                                 *
//*  MXI can display information about the following aspects of     *
//*  the MVS system:                                                *
//*                                                                 *
//*       APF, Linklist and LPA Datasets                            *
//*       Active Address Spaces                                     *
//*       ASID Usage                                                *
//*       Master and User Catalogs                                  *
//*       Common Storage Usage by Address Space                     *
//*       Common Storage Subpool Usage                              *
//*       Orphaned Common Storage                                   *
//*       CPU and LPAR Information                                  *
//*       CA-1 Configuration                                        *
//*       Coupling Facility Information                             *
//*       Online DASD and TAPE Volumes                              *
//*       Dynamic and Other System Exits                            *
//*       Enqueue Requests and Contention                           *
//*       GRS Resource Name Lists                                   *
//*       HSM Request Queues                                        *
//*       IPL and LOAD Information                                  *
//*       Link Pack Directory Modules                               *
//*       Nucleus Modules                                           *
//*       Memory Displays Including DSECT Mapping                   *
//*       MPF List Entries                                          *
//*       Page and SMF Datasets                                     *
//*       PARMLIB Statements and System Symbols                     *
//*       PPT Entries                                               *
//*       Real and Auxiliary Storage Usage by Address Space         *
//*       SMS Configuration and Modules                             *
//*       SMS Data, Management and Storage Classes                  *
//*       System Name/Token Entries                                 *
//*       Subsystems                                                *
//*       SVC Entries Including ESR Tables                          *
//*       Sysplex Information                                       *
//*       XCF Members and Structures                                *
//*       VTAM Major Nodes                                          *
//*                                                                 *
//*                       Software Pre-requisites :                 *
//*                       MVS/ESA Version 5  or                     *
//*                       OS/390                                    *
//*                       ISPF Version 3.5 or later                 *
//*                       JES2 Version 5 and above                  *
//*                                                                 *
//*                       Source Code Supplied : NO                 *
//*                       Size 304K                                 *
//*                                                                 *
//*     Scott Enterprise Consultancy Ltd.                           *
//*     Tel: +44 (0)181 408 3556                                    *
//*                                                                 *
//*      Index of Members in this dataset                           *
//*      --------------------------------                           *
//*      $$INDEX        This member                                 *
//*      $GUIDE         Short user guide                            *
//*      $INSTALL       Instructions on how to install MXI from     *
//*                     this dataset and the load library           *
//*                     (supplied in File 410)                      *
//*      $INSTJCL       Allocate runtime datasets and copy          *
//*                     members from this dataset into them.        *
//*      $LIBDEF        Example REXX exec to invoke MXI using       *
//*                     LIBDEFs.                                    *
//*      $MXIXPT        Instructions on how to code the MXI         *
//*                     exception rules.                            *
//*      $README        Version and release notes                   *
//*      $SUPPORT       Trouble shooting guide and where to         *
//*                     report problems.                            *
//*      $TECHSPC       Technical overview                          *
//*      $XPTASM        Sample JCL to Assemble and link the MXI     *
//*                     exception rules                             *
//*      MXICMDS        Commands table                              *
//*      MXIRULE        Macro used to generate exception rules      *
//*      MXIXPT00       Sample exception rules table                *
//*      MXIH*          Help panels                                 *
//*      MXIPANEL       Main Panel                                  *
//*      MXIPANE2       Alternate panel                             *
//*      MXIOPTS        Screen options panel                        *
//*      MXIOPTL        MXI settings panel                          *
//*                                                                 *
//*  -------------------------------------------------------------  *
//*                                                                 *
//*    Version and Release Notes :                                  *
//*                                                                 *
//*   2.2a                                                          *
//*     o  Added an internal security table to control              *
//*        authorized commands.                                     *
//*     o  Added the JOB() and ASID() keywords to the CDE           *
//*        command to get JPAQ and TCB loaded modules of other      *
//*        address spaces                                           *
//*     o  Added the JOB() and ASID() keywords to the TCB           *
//*        command to get the TCB structure of other address        *
//*        spaces                                                   *
//*     o  Added the CHP command to list channel path information.  *
//*     o  Added the MAKE command to change address space           *
//*        swapability.                                             *
//*     o  Added the / command to issue operator commands.          *
//*     o  Added the ONLY(JPAQ) keyword to the CDE command.         *
//*     o  The TYPE=DASD and TYPE=TASK exception rules now          *
//*        support the use of pattern masks for volsers and         *
//*        jobnames.                                                *
//*     o  The PRT command will use USERID if the TSO prefix is     *
//*        null.                                                    *
//*     o  Added the OMVS and RTLS statements to the PARM           *
//*        command.                                                 *
//*     o  Fixed the TAPE command storage creep problem.            *
//*     o  Fixed the SGRP command storage problem.                  *
//*                                                                 *
//*   2.1e                                                          *
//*     o  Added the AGRP command to display SMS aggregate          *
//*        groups.                                                  *
//*     o  Added the UCB command to show the actual UCB             *
//*        addresses of all devices.                                *
//*     o  Added the CDE command to show the JPAQ and TCB           *
//*        loaded modules.                                          *
//*     o  Added the ONLY() and NOT() keywords to the DASD          *
//*        command.                                                 *
//*     o  Added subsystem version information (via SSI-54) to      *
//*        the SSI command.                                         *
//*     o  Added support for JES3.                                  *
//*     o  Added the UCB map to the MEM command.                    *
//*     o  Changed the SGRP command to show all volumes             *
//*        defined to the SMS storage group when the more           *
//*        detailed display is shown.                               *
//*     o  Changed the TAPE command to accept unit address          *
//*        masking.                                                 *
//*     o  Changed the SVC command to accept masking.               *
//*     o  Removed the authorized version of the CAT command.       *
//*     o  The command parsing routines have been changed so        *
//*        that all commands that accept keywords do NOT have       *
//*        to have the positional mask specified.                   *
//*     o  Added SMS Status to the DASD display for a single        *
//*        volume.                                                  *
//*     o  Improved authority checking when running under ISPF      *
//*        or REXX.                                                 *
//*                                                                 *
//*   2.1d                                                          *
//*     o Added the SORTXA and SORTXD commands to sort hex          *
//*       values                                                    *
//*     o Added the JOB() and ASID() keywords to the DDNS           *
//*       command to get allocated datasets for other address       *
//*       spaces                                                    *
//*     o Added the TCB command                                     *
//*     o Added the USP command                                     *
//*     o Renamed the SMF command to SMFD                           *
//*     o Added new SMF command                                     *
//*     o Added the A=asid form of the DA command                   *
//*     o Added the MAP command                                     *
//*     o The SRCH command now presents a summary of matched        *
//*       member(s) instead of each member                          *
//*     o The EDT command can now cope with more than 8000          *
//*       devices per unit name                                     *
//*     o Show allocated jobnames and device types on the EDT       *
//*       command                                                   *
//*     o Toggle ISPF 'Tab to point and shoot' setting              *
//*     o Re-worked the HELP dialog                                 *
//*     o MXIREXX now defaults to inlude screen headings            *
//*       (titles)                                                  *
//*     o Added the 'NOTITLES' special parm to MXIREXX              *
//*     o MXIREXX now correctly sets return codes                   *
//*     o Cater for null commands in MXIREXX (was giving 0C4        *
//*       abends)                                                   *
//*     o Fixed 0C6 abends when invalid input given to the SVC      *
//*       or MEM comamnds                                           *
//*                                                                 *
//*   2.1c                                                          *
//*     o Added the EXC command                                     *
//*     o Added CPU% and SIO on the DA display                      *
//*     o ENQC command now displays both enqueue conflicts and      *
//*       RESERVEs at the same time                                 *
//*     o MPF command now recognises SUP(ALL) entries               *
//*     o Allow SRCH command to be issued on the PARM display       *
//*     o Adjust alignment in the CVT mapping for MEM @CVT          *
//*       MAP(CVT)                                                  *
//*     o Allow NORMAL attribute to be assigned to                  *
//*       point-and-shoot fields                                    *
//*     o Place 'Row n of n' message on ALL scrollable panels       *
//*     o Assign a console key of MXI to E-MCS consoles and         *
//*       ensure MigID is released                                  *
//*     o Disallow LPAR info collection under VM                    *
//*     o Enhance RMF Diag204 validation                            *
//*     o Add support for 62-line screens                           *
//*                                                                 *
//*   2.1b                                                          *
//*     o Added the DA command                                      *
//*     o Added the RS command                                      *
//*     o Added the UIC command                                     *
//*     o Added the SGRP() keyword to the DASD command              *
//*     o Added EXCP counts to the DDNS command                     *
//*     o Enhancements to the DASD command displays                 *
//*     o Enhancements to the TAPE comamnd displays                 *
//*     o Show PARMLIB dsnames/vols/status with the PARM            *
//*       command                                                   *
//*     o MXI now remembers current line in scrollable list         *
//*       when screen refreshed                                     *
//*     o MXI now keeps the sort order when screen refreshed        *
//*                                                                 *
//*   2.1a                                                          *
//*     o Added the LLSU command                                    *
//*     o Added the LLS command                                     *
//*     o Added the CS command                                      *
//*     o Added the CSR command                                     *
//*     o Added the DCLS command                                    *
//*     o Added the CA1 command                                     *
//*     o Added the CAX keyword to the CAT command                  *
//*     o Added the LLS keyword to the LINK command                 *
//*     o Added APF fields for LINK and LPA command output          *
//*     o Volser now displayed for LINK and LPA when DSCB           *
//*       is OFF                                                    *
//*     o Added support for parm to be passed via ISPF SELECT       *
//*       PGM(MXI)                                                  *
//*     o Fixed panel size for MXIHMSC2                             *
//*     o Added the MXICMDS ISPF table to ensure PASSTHRU for       *
//*       MXI commands                                              *
//*                                                                 *
