      DOUBLE PRECISION MNAME,MPASS
      DATA MNAME,MPASS,POINT/'DEMO    ','DEMO    ',0.0/
      DEFINE FILE 3(50,2400,L,IV)
      DO 1 I=1,50
      WRITE(3'I)MNAME,POINT,MPASS
      MPASS=-1
1     CONTINUE
      STOP
      END
