TJHE     TITLE 'IGTJHE - 3838 SUBSYS ALLOC ERR INFO RETURN.            *
                        '
IGTJHE   CSECT ,                                                01S0001
@MAINENT DS    0H                                               01S0001
         USING *,@15                                            01S0001
         B     @PROLOG                                          01S0001
         DC    AL1(16)                                          01S0001
         DC    C'IGTJHE    77.092'                              01S0001
         DROP  @15
@PROLOG  STM   @14,@12,12(@13)                                  01S0001
         BALR  @07,0                                            01S0001
@PSTART  DS    0H                                               01S0001
         USING @PSTART,@07                                      01S0001
         L     @00,@SIZDATD                                     01S0001
         IGTYGSV  R,LV=(0)
         LR    @06,@01                                          01S0001
         USING @DATD,@06                                        01S0001
         ST    @13,@SA00001+4                                   01S0001
         LM    @00,@01,20(@13)                                  01S0001
         ST    @06,8(,@13)                                      01S0001
         LR    @13,@06                                          01S0001
*   SSDDRPTR=R0P;                   /* POINTER TO ALLOC REQUEST BLK  */
         LR    SSDDRPTR,R0P                                     01S0044
*   RFY                                                         01S0045
*    (R0P) UNRSTD;                  /* FREE IT UP NOW                */
*   RFY                                                         01S0046
*     SSAGARBK BASED(SSDDRPTR);     /* BASE FOR REQUEST BLOCK        */
*   IF RETN(ERRINDX)=SSAGGPER THEN  /* IF THIS IS A GROUP LEVEL ERROR*/
         LA    @15,8                                            01S0047
         LR    @14,ERRINDX                                      01S0047
         SLA   @14,2                                            01S0047
         C     @15,RETN-4(@14)                                  01S0047
         BNE   @RF00047                                         01S0047
*     IF SSOBRETN^=SSAGGPER THEN    /* IF A GROUP LEVEL ERROR HAS NOT*/
         L     @14,SSOBPTR(,ALLCWAPT)                           01S0048
         C     @15,SSOBRETN(,@14)                               01S0048
         BE    @RF00048                                         01S0048
*       DO;                         /* PREVIOUSLY BEEN REPORTED THEN */
*         SSOBRETN=SSAGGPER;        /* SSOBRETN INDICATES GRP LVL ERR*/
         ST    @15,SSOBRETN(,@14)                               01S0050
*         SSAGGPEC=ERRCODE(ERRINDX);/* SET ERROR REASON CODE-GRPLEVEL*/
         L     @15,SSOBINDV(,@14)                               01S0051
         LR    @14,ERRINDX                                      01S0051
         ALR   @14,@14                                          01S0051
         LH    @00,ERRCODE-2(@14)                               01S0051
         STH   @00,SSAGGPEC(,@15)                               01S0051
*         SSAGGPIC=INFOCODE(ERRINDX);/* INFORMATION CODE FOR ERROR   */
         LH    @00,INFOCODE-2(@14)                              01S0052
         STH   @00,SSAGGPIC(,@15)                               01S0052
*         IF SSAGSMSG=BON THEN      /* IF CALLER EXPECTS MSGS TO BE  */
         TM    SSAGSMSG(@15),B'01000000'                        01S0053
         BNO   @RF00053                                         01S0053
*           DO;                     /* PROVIDED THEN PROVIDE         */
*             SSAGGMGL=ERRMSGL(ERRINDX);/* LENGTH OF MESSAGE TEXT AND*/
         L     @15,SSAGGMGP(,@15)                               01S0055
         LH    @00,ERRMSGL-2(@14)                               01S0055
         STH   @00,SSAGGMGL(,@15)                               01S0055
*             SSAGGMSG(1:SSAGGMGL)=ERRMSGT(ERRINDX,1:SSAGGMGL);/* MSG
*                                      TEXT                          */
         BCTR  @00,0                                            01S0056
         LR    @14,ERRINDX                                      01S0056
         MH    @14,@CH00148                                     01S0056
         LA    @11,ERRMSGT-110(@14)                             01S0056
         LR    @14,@00                                          01S0056
         EX    @14,@SM00856                                     01S0056
*             SSAGGMSG(9:12)=APCTSSID;/* FILL IN SUBSYS ID           */
         MVC   SSAGGMSG+8(4,@15),APCTSSID(APCTPTR)              01S0057
*           END;                                                01S0058
*       END;                                                    01S0059
@RF00053 DS    0H                                               01S0060
*   IF RETN(ERRINDX)=SSAGDDER THEN  /* IF THIS IS A DD/TEXT UNIT-    */
@RF00048 DS    0H                                               01S0060
@RF00047 LA    @15,4                                            01S0060
         LR    @14,ERRINDX                                      01S0060
         SLA   @14,2                                            01S0060
         C     @15,RETN-4(@14)                                  01S0060
         BNE   @RF00060                                         01S0060
*     IF SSAGRBEC=0 THEN            /* RELATED ERROR AND THE FIRST   */
         SLR   @14,@14                                          01S0061
         CH    @14,SSAGRBEC(,SSDDRPTR)                          01S0061
         BNE   @RF00061                                         01S0061
*       DO;                         /* FOR THIS REQUEST THEN DO      */
*         IF SSOBRETN=0 THEN        /* SET SSOBRETN IF FIRST ERROR   */
         L     @11,SSOBPTR(,ALLCWAPT)                           01S0063
         C     @14,SSOBRETN(,@11)                               01S0063
         BNE   @RF00063                                         01S0063
*           SSOBRETN=SSAGDDER;      /* TO INDICATE DD LEVEL ERROR    */
         ST    @15,SSOBRETN(,@11)                               01S0064
*         SSAGRBEC=ERRCODE(ERRINDX);/* ERROR REASON CODE FOR PROBLEM */
@RF00063 LR    @15,ERRINDX                                      01S0065
         ALR   @15,@15                                          01S0065
         LH    @00,ERRCODE-2(@15)                               01S0065
         STH   @00,SSAGRBEC(,SSDDRPTR)                          01S0065
*         SSAGRBIC=INFOCODE(ERRINDX);/* INFORMATION CODE FOR PROBLEM */
         LH    @00,INFOCODE-2(@15)                              01S0066
         STH   @00,SSAGRBIC(,SSDDRPTR)                          01S0066
*         IF SSAGSMSG=BON THEN      /* IF ERROR MESSAGES HAVE BEEN   */
         L     @14,SSOBPTR(,ALLCWAPT)                           01S0067
         L     @14,SSOBINDV(,@14)                               01S0067
         TM    SSAGSMSG(@14),B'01000000'                        01S0067
         BNO   @RF00067                                         01S0067
*           DO;                     /* REQUESTED THEN PROVIDE        */
*             SSAGDMGL=ERRMSGL(ERRINDX);/* LENGTH OF MESSAGE TEXT AND*/
         L     @14,SSAGDMGP(,SSDDRPTR)                          01S0069
         LH    @00,ERRMSGL-2(@15)                               01S0069
         STH   @00,SSAGDMGL(,@14)                               01S0069
*             SSAGDMSG(1:SSAGDMGL)=ERRMSGT(ERRINDX,1:SSAGDMGL);/* MSG
*                                      TEXT                          */
         BCTR  @00,0                                            01S0070
         LR    @15,ERRINDX                                      01S0070
         MH    @15,@CH00148                                     01S0070
         LA    @11,ERRMSGT-110(@15)                             01S0070
         LR    @15,@00                                          01S0070
         EX    @15,@SM00858                                     01S0070
*             SSAGDMSG(9:12)=APCTSSID;/* FILL IN SUBSYS ID           */
         MVC   SSAGDMSG+8(4,@14),APCTSSID(APCTPTR)              01S0071
*           END;                                                01S0072
*       END;                                                    01S0073
*   RETURN;                         /* IGTXEPLG                      */
@EL00001 L     @13,4(,@13)                                      01S0074
@EF00001 L     @00,@SIZDATD                                     01S0074
         LR    @01,@06                                          01S0074
         IGTYFSV  R,LV=(0),A=(1)
@ER00001 LM    @14,@12,12(@13)                                  01S0074
         BR    @14                                              01S0074
*                                                               01S0075
*   /*****************************************************************/
*   /*                                                               */
*   /* SYSTEM DECLARES                                               */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0075
*   DECLARE                         /* COMMON VARIABLES              */
*     I256C CHAR(256) BASED,                                    01S0075
*     I031F FIXED(31) BASED,                                    01S0075
*     I031P PTR(31) BASED,                                      01S0075
*     I015F FIXED(15) BASED,                                    01S0075
*     I015P PTR(15) BASED,                                      01S0075
*     I008P PTR(8) BASED,                                       01S0075
*     I001C CHAR(1) BASED;                                      01S0075
*                                                               01S0076
*/*   MODULE PATCH AREA                                              */
*                                                               01S0076
*   DCL                                                         01S0076
*     APPATCH CHAR(*) INT STATIC LOCAL GEND;                    01S0076
*   GENERATE DATA DEFS(APPATCH);                                01S0077
*                                                               01S0078
*   /*****************************************************************/
*   /*                                                               */
*   /* GENERAL REGISTER DECLARES                                     */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0078
*   DCL                                                         01S0078
*     R0F FIXED(31) REG(0),                                     01S0078
*     R0P PTR(24) REG(0),                                       01S0078
*     R0RSTD PTR(31) REG(0),                                    01S0078
*     R1F FIXED(31) REG(1),                                     01S0078
*     R1P PTR(24) REG(1),                                       01S0078
*     R1RSTD PTR(31) REG(1),                                    01S0078
*     R2F FIXED(31) REG(2),                                     01S0078
*     R2P PTR(24) REG(2),                                       01S0078
*     R2RSTD PTR(31) REG(2),                                    01S0078
*     R3F FIXED(31) REG(3),                                     01S0078
*     R3P PTR(24) REG(3),                                       01S0078
*     R3RSTD PTR(31) REG(3),                                    01S0078
*     R4F FIXED(31) REG(4),                                     01S0078
*     R4P PTR(24) REG(4),                                       01S0078
*     R4RSTD PTR(31) REG(4),                                    01S0078
*     R5F FIXED(31) REG(5),                                     01S0078
*     R5P PTR(24) REG(5),                                       01S0078
*     R5RSTD PTR(31) REG(5),                                    01S0078
*     R6F FIXED(31) REG(6),                                     01S0078
*     R6P PTR(24) REG(6),                                       01S0078
*     R6RSTD PTR(31) REG(6),                                    01S0078
*     R7F FIXED(31) REG(7),                                     01S0078
*     R7P PTR(24) REG(7),                                       01S0078
*     R7RSTD PTR(31) REG(7),                                    01S0078
*     R8F FIXED(31) REG(8),                                     01S0078
*     R8P PTR(24) REG(8),                                       01S0078
*     R8RSTD PTR(31) REG(8),                                    01S0078
*     R9F FIXED(31) REG(9),                                     01S0078
*     R9P PTR(24) REG(9),                                       01S0078
*     R9RSTD PTR(31) REG(9),                                    01S0078
*     R10F FIXED(31) REG(10),                                   01S0078
*     R10P PTR(24) REG(10),                                     01S0078
*     R10RSTD PTR(31) REG(10),                                  01S0078
*     R11F FIXED(31) REG(11),                                   01S0078
*     R11P PTR(24) REG(11),                                     01S0078
*     R11RSTD PTR(31) REG(11),                                  01S0078
*     R12F FIXED(31) REG(12),                                   01S0078
*     R12P PTR(24) REG(12),                                     01S0078
*     R12RSTD PTR(31) REG(12),                                  01S0078
*     R13F FIXED(31) REG(13),                                   01S0078
*     R13P PTR(24) REG(13),                                     01S0078
*     R13RSTD PTR(31) REG(13),                                  01S0078
*     R14F FIXED(31) REG(14),                                   01S0078
*     R14P PTR(24) REG(14),                                     01S0078
*     R14RSTD PTR(31) REG(14),                                  01S0078
*     R15F FIXED(31) REG(15),                                   01S0078
*     R15P PTR(24) REG(15),                                     01S0078
*     R15RSTD PTR(31) REG(15),                                  01S0078
*                                                               01S0078
*     /***************************************************************/
*     /*                                                             */
*     /* VPSS CONTROL BLOCK POINTER DECLARES                         */
*     /*                                                             */
*     /***************************************************************/
*                                                               01S0078
*     APSMPTR PTR(24) REG(01),      /* STORAGE MANAGEMENT BLOCK 01S0078
*                                      (SUGGESTED POINTER)           */
*     APSCPTR PTR(24) REG(01),      /* STORAGE MANAGEMENT CONTROL
*                                      WORD (SUGGESTED POINTER)      */
*     APINPTR PTR(24) REG(01),      /* USER'S INPUT PARAMETER LIST
*                                      (SUGGESTED POINTER)           */
*/*                                                                  */
*                                                               01S0078
*     APDATA PTR(24) REG(06),       /* ADDRESS OF DYNAMIC DATA  01S0078
*                                      WORKAREA (DATAREG)            */
*     APCODE PTR(24) REG(07),       /* PROGRAM CODE BASE REGISTER
*                                      (CODEREG)                     */
*     APDEBPTR PTR(24) REG(08),     /* VPSS DEB (SUGGESTED POINTER)  */
*     APNPPTR PTR(24) REG(08),      /* SUBSYSTEM INITIALIZATION 01S0078
*                                      WORKAREA BLOCK (ONLY USED BY
*                                      SUBSYSTEM INITIALIZATION)     */
*     APRLPTR PTR(24) REG(08),      /* VPSS ACB REQUEST LIST    01S0078
*                                      (SUGGESTED POINTER)           */
*     APCIPTR PTR(24) REG(08),      /* 3838 CONTROL TABLE (SUGGESTED
*                                      POINTER)                      */
*     APCWPTR PTR(24) REG(08),      /* CALL INTERFACE WORKAREA  01S0078
*                                      (SUGGESTED POINTER)           */
*     APERPTR PTR(24) REG(08),      /* ERP/IO APPENDAGE WORKAREA
*                                      (SUGGESTED POINTER)           */
*     APACBPTR PTR(24) REG(09),     /* VPSS ACB (SUGGESTED POINTER)  */
*     APCQPTR PTR(24) REG(09),      /* COMMAND QUEUE ELEMENT    01S0078
*                                      (SUGGESTED POINTER)           */
*     APOTPTR PTR(24) REG(09),      /* OPTION TABLE (SUGGESTED  01S0078
*                                      POINTER)                      */
*     APIOPTR PTR(24) REG(10),      /* I/O ELEMENT (SUGGESTED   01S0078
*                                      POINTER)                      */
*     APEXLPTR PTR(24) REG(10),     /* VPSS EXLST (SUGGESTED POINTER)*/
*     APUBPTR PTR(24) REG(10),      /* UNIT BLOCK (SUGGESTED POINTER)*/
*     APAXPTR PTR(24) REG(10),      /* VPSS ACB EXTENSION (SUGGESTED
*                                      POINTER)                      */
*     APCPPTR PTR(24) REG(10),      /* VPSS CALL PROCESSING     01S0078
*                                      INDICATORS (SUGGESTED POINTER)*/
*     APOCPTR PTR(24) REG(10),      /* VPSS OPEN/CLOSE SUBSYSTEM
*                                      WORKAREA (REQUIRED POINTER)   */
*     APATPTR PTR(24) REG(11),      /* VPSS ACB TABLE (SUGGESTED
*                                      POINTER)                      */
*     APLBPTR PTR(24) REG(11),      /* LABEL RESOLUTION TABLE   01S0078
*                                      (SUGGESTED POINTER)           */
*     APUTPTR PTR(24) REG(11),      /* USER TABLE (SUGGESTED POINTER)*/
*     APDSPTR PTR(24) REG(11),      /* VPSS DATASET ENTRY (SUGGESTED
*                                      POINTER)                      */
*     APXLPTR PTR(24) REG(11),      /* TRANSLATION TABLE (SUGGESTED
*                                      POINTER)                      */
*     APDXPTR PTR(24) REG(11),      /* VPSS DEB EXTENSION (SUGGESTED
*                                      POINTER)                      */
*     APCTPTR PTR(24) REG(12) RSTD, /* CONTROL TABLE (REQUIRED  01S0078
*                                      POINTER)                      */
*     APSVPTR PTR(24) REG(13) RSTD, /* OS/VPSS SAVEAREA/WORKAREA
*                                      (REQUIRED POINTER)            */
*     APRETURN PTR(24) REG(14),     /* RETURN ADDRESS FOR SUBROUTINE
*                                      LINKAGE                       */
*     APENTRY PTR(24) REG(15),      /* SUBROUTINE ENTRY POINT LINKAGE*/
*     APRCODE PTR(24) REG(15);      /* CONTAINS SUBROUTINE RETURN
*                                      CODE                          */
*                                                               01S0079
*   /*****************************************************************/
*   /*                                                               */
*   /* USER REGISTER DECLARES                                        */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0079
*   DCL                                                         01S0079
*     ALLCWAPT PTR(24) REG(04) RSTD;/* POINTER FOR ALLCWA            */
*   DCL                                                         01S0080
*     ERRINDX FIXED(31) REG(01) RSTD;/* INDX TO ERR RTN ARRAYS       */
*   END IGTJHE                                                  01S0081
*                                                               01S0081
*/* THE FOLLOWING INCLUDE STATEMENTS WERE FOUND IN THIS PROGRAM.     */
*/*%INCLUDE SYSLIB  (IGTXAPAW)                                       */
*/*%INCLUDE SYSLIB  (IGTXSYSI)                                       */
*/*%INCLUDE SYSLIB  (IGTXSYSI)                                       */
*/*%INCLUDE SYSLIB  (IGTXSYSI)                                       */
*/*%INCLUDE SYSLIB  (IGTXSYSI)                                       */
*/*%INCLUDE SYSLIB  (IGTJHM  )                                       */
*/*%INCLUDE SYSLIB  (IGTXAPCT)                                       */
*/*%INCLUDE SYSLIB  (IGTXAPSV)                                       */
*/*%INCLUDE SYSLIB  (IGTXAPCV)                                       */
*/*%INCLUDE SYSLIB  (IEFJSSOB)                                       */
*/*%INCLUDE SYSLIB  (IEFSSARB)                                       */
*                                                               01S0081
*       ;                                                       01S0081
         B     @EL00001                                         01S0081
@DATA    DS    0H
@CH00148 DC    H'110'
@SM00856 MVC   SSAGGMSG(0,@15),0(@11)
@SM00858 MVC   SSAGDMSG(0,@14),0(@11)
@DATD    DSECT
         DS    0F
@SA00001 DS    20F
IGTJHE   CSECT
         DS    0F
@DATD    DSECT
         DS    0D
IGTJHE   CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
         DS    0D
RETN     DC    F'4'
         DC    F'4'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'4'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'4'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
         DC    F'8'
ERRCODE  DC    H'16'
         DC    H'16'
         DC    H'4'
         DC    H'4'
         DC    H'24'
         DC    H'24'
         DC    H'16'
         DC    H'20'
         DC    H'20'
         DC    H'20'
         DC    H'20'
         DC    H'8'
         DC    H'20'
         DC    H'20'
         DC    H'8'
         DC    H'24'
         DC    H'20'
         DC    H'20'
         DC    H'16'
         DC    H'16'
INFOCODE DC    XL2'0040'
         DC    XL2'0044'
         DC    XL2'0040'
         DC    XL2'0044'
         DC    XL2'0040'
         DC    XL2'0044'
         DC    XL2'0048'
         DC    XL2'005C'
         DC    XL2'0040'
         DC    XL2'0044'
         DC    XL2'0048'
         DC    XL2'0044'
         DC    XL2'004C'
         DC    XL2'0050'
         DC    XL2'004C'
         DC    XL2'004C'
         DC    XL2'0054'
         DC    XL2'0058'
         DC    XL2'004C'
         DC    XL2'0050'
ERRMSGT  DC    CL110'IGT456I .... SUBLIST NOT PERMITTED FOR SUBSYS KEYWC
               ORD'
         DC    CL110'IGT457I .... 3838 SUBSYSTEM ALLOCATION REQUIRES SYC
               STEM CREATED SSWA'
         DC    CL110'IGT480I .... SUBSYS ALLOCATION UNABLE TO ESTABLISHC
                ESTAE ENVIRONMENT'
         DC    CL110'IGT481I .... INSUFFICIENT STORAGE TO PERFORM SUBSYC
               STEM ALLOCATION'
         DC    CL110'IGT482I .... SUBSYSTEM MONITOR SERIALIZATION PREVEC
               NTS ALLOCATION'
         DC    CL110'IGT483I .... SUBSYSTEM ALLOCATION ERROR'
         DC    CL110'IGT484I .... REGION REQUESTED WAS LARGER THAN LARGC
               EST AVAILABLE IN PRESENT CONFIGURATION'
         DC    CL110'IGT485I .... SUBSYSTEM RESOURCE REQUEST DENIED BY C
               INSTALLATION EXIT'
         DC    CL110'IGT490I .... JOB CANCELED WHILE SERIALIZED IN SUBSC
               YS ALLOCATON'
         DC    CL110'IGT491I .... JOB CANCELED WHILE WAITING TO ATTEMPTC
                SUBSYS ALLOCATON'
         DC    CL110'IGT492I .... JOB CANCELED WAITING TO INITIATE SUBSC
               YSTEM MONITOR'
         DC    CL110'IGT493I .... SUBSYSTEM MONITOR NOT ACTIVE AND REQUC
               EST NOT ALLOWED TOWAIT'
         DC    CL110'IGT494I .... JOB CANCELED WAITING FOR SUBSYSTEM MOC
               NITOR TO BECOME ACTIVE'
         DC    CL110'IGT495I .... JOB CANCELED.SUBSYSTEM MONITOR NOT REC
               ADY.'
         DC    CL110'IGT499I .... SUBSYSTEM RESOURCES NOT AVAILABLE'
         DC    CL110'IGT486I .... SUBSYSTEM ALLOCATION ERROR.'
         DC    CL110'IGT496I .... JOB CANCELED WAITING FOR SUBSYSTEM REC
               SOURCES TO BECOME AVAILABLE'
         DC    CL110'IGT498I .... JOB CANCELED IN ALLOCATION RECOVERY'
         DC    CL110'IGT478I .... JOB REQUESTED MORE PORTS THAN ARE AVAC
               ILABLE IN PRESENT CONFIGURATION'
         DC    CL110'IGT479I .... JOBS TOTAL BULK STORAGE REQUIREMENT EC
               XCEEDS MAXIMUM AVAILABLE IN PRESENT CONFIGURATION'
ERRMSGL  DC    H'53'
         DC    H'67'
         DC    H'68'
         DC    H'65'
         DC    H'64'
         DC    H'39'
         DC    H'88'
         DC    H'67'
         DC    H'62'
         DC    H'67'
         DC    H'63'
         DC    H'72'
         DC    H'72'
         DC    H'54'
         DC    H'46'
         DC    H'40'
         DC    H'77'
         DC    H'48'
         DC    H'81'
         DC    H'99'
IGTJHE   CSECT
*                                /* GENERATE PATCH
         IGTXZAP ,                 GENERATE PATCH AREA
@DATD    DSECT
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
IGTJHE   CSECT
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
SSDDRPTR EQU   @05
APDATA   EQU   @06
APCODE   EQU   @07
ALLCWAPT EQU   @04
APCTPTR  EQU   @12
APSVPTR  EQU   @13
R0P      EQU   @00
ERRINDX  EQU   @01
APACBPTR EQU   @09
APATPTR  EQU   @11
APAXPTR  EQU   @10
APCIPTR  EQU   @08
APCPPTR  EQU   @10
APCQPTR  EQU   @09
APCWPTR  EQU   @08
APDEBPTR EQU   @08
APDSPTR  EQU   @11
APDXPTR  EQU   @11
APENTRY  EQU   @15
APERPTR  EQU   @08
APEXLPTR EQU   @10
APINPTR  EQU   @01
APIOPTR  EQU   @10
APLBPTR  EQU   @11
APNPPTR  EQU   @08
APOCPTR  EQU   @10
APOTPTR  EQU   @09
APRCODE  EQU   @15
APRETURN EQU   @14
APRLPTR  EQU   @08
APSCPTR  EQU   @01
APSMPTR  EQU   @01
APUBPTR  EQU   @10
APUTPTR  EQU   @11
APXLPTR  EQU   @11
R0F      EQU   @00
R0RSTD   EQU   @00
R1F      EQU   @01
R1P      EQU   @01
R1RSTD   EQU   @01
R10F     EQU   @10
R10P     EQU   @10
R10RSTD  EQU   @10
R11F     EQU   @11
R11P     EQU   @11
R11RSTD  EQU   @11
R12F     EQU   @12
R12P     EQU   @12
R12RSTD  EQU   @12
R13F     EQU   @13
R13P     EQU   @13
R13RSTD  EQU   @13
R14F     EQU   @14
R14P     EQU   @14
R14RSTD  EQU   @14
R15F     EQU   @15
R15P     EQU   @15
R15RSTD  EQU   @15
R2F      EQU   @02
R2P      EQU   @02
R2RSTD   EQU   @02
R3F      EQU   @03
R3P      EQU   @03
R3RSTD   EQU   @03
R4F      EQU   @04
R4P      EQU   @04
R4RSTD   EQU   @04
R5F      EQU   @05
R5P      EQU   @05
R5RSTD   EQU   @05
R6F      EQU   @06
R6P      EQU   @06
R6RSTD   EQU   @06
R7F      EQU   @07
R7P      EQU   @07
R7RSTD   EQU   @07
R8F      EQU   @08
R8P      EQU   @08
R8RSTD   EQU   @08
R9F      EQU   @09
R9P      EQU   @09
R9RSTD   EQU   @09
SSARBPTR EQU   0
APAW     EQU   0
SSOBPTR  EQU   APAW
ALLSTAT  EQU   APAW+8
ALLSTAT0 EQU   ALLSTAT
ALLSTAT1 EQU   ALLSTAT+1
ALLSTAT2 EQU   ALLSTAT+2
ALLSTAT3 EQU   ALLSTAT+3
ALLRSRCE EQU   APAW+12
EXITINFO EQU   APAW+48
EXITINF0 EQU   EXITINFO
EXITINF1 EQU   EXITINFO+1
APCT     EQU   0
APCTENQM EQU   APCT+12
APCTSSID EQU   APCTENQM+4
APCTSMIN EQU   APCT+32
APCTSMAD EQU   APCT+36
APCTZ@@@ EQU   APCT+40
APCTU@@@ EQU   APCT+440
APCTBR14 EQU   APCT+840
APCTERRS EQU   APCT+876
@NM00020 EQU   APCT+936
APCTSTAT EQU   @NM00020
APCTPRSW EQU   @NM00020+1
APCTAPCQ EQU   APCT+944
APCTCQAQ EQU   APCT+952
APCTZ@@1 EQU   APCT+1120
APSV     EQU   0
APSVREGS EQU   APSV+12
SSOB     EQU   0
SSOBRETN EQU   SSOB+12
SSOBINDV EQU   SSOB+16
SSAG     EQU   0
SSAGEHDR EQU   SSAG
SSAGFLGS EQU   SSAGEHDR+2
SSAGSMSG EQU   SSAGFLGS
SSAGGPEC EQU   SSAGEHDR+4
SSAGGPIC EQU   SSAGEHDR+6
SSAGGMGP EQU   SSAGEHDR+24
SSAGARBK EQU   0
SSAGRBEC EQU   SSAGARBK+4
SSAGRBIC EQU   SSAGARBK+6
SSAGDMGP EQU   SSAGARBK+56
SSAGDMBK EQU   0
SSAGDMGL EQU   SSAGDMBK
SSAGDMSG EQU   SSAGDMBK+2
SSAGGMBK EQU   0
SSAGGMGL EQU   SSAGGMBK
SSAGGMSG EQU   SSAGGMBK+2
APCVZDAL EQU   0
APCVZDAP EQU   0
APCVZDBK EQU   0
APCVZDDA EQU   0
APCVZDDQ EQU   0
APCVZDEQ EQU   0
APCVZDID EQU   0
APCVZDIO EQU   0
APCVZDIP EQU   0
APCVZDMD EQU   0
APCVZDMM EQU   0
APCVZDQR EQU   0
APCVZDRI EQU   0
APCVZDUA EQU   0
APCVZDUL EQU   0
APCVZDWI EQU   0
APCVZDWT EQU   0
APCVZDX1 EQU   0
APCVZDX2 EQU   0
APCVZDX3 EQU   0
APCVZDX4 EQU   0
APCVZD10 EQU   0
APCVZD20 EQU   0
APCVZD4E EQU   0
APCVZD40 EQU   0
APCVZD41 EQU   0
APCVZD42 EQU   0
APCVZD43 EQU   0
APCVZD44 EQU   0
APCVZD45 EQU   0
APCVZD46 EQU   0
APCVZD47 EQU   0
APCVZD48 EQU   0
APCVZD49 EQU   0
APCVZD60 EQU   0
APCVZD80 EQU   0
APCVZD81 EQU   0
APCVZD82 EQU   0
APCVZD83 EQU   0
APCVZJAA EQU   0
APCVZJAD EQU   0
APCVZJAG EQU   0
APCVZJAJ EQU   0
APCVZJAM EQU   0
APCVZJAP EQU   0
APCVZJAX EQU   0
APCVZJAY EQU   0
APCVZJBA EQU   0
APCVZJBD EQU   0
APCVZJBG EQU   0
APCVZJBJ EQU   0
APCVZJBM EQU   0
APCVZJDA EQU   0
APCVZJDD EQU   0
APCVZJDG EQU   0
APCVZJDJ EQU   0
APCVZJDM EQU   0
APCVZJHC EQU   0
APCVZJHE EQU   0
APCVZJHF EQU   0
APCVZJHO EQU   0
APCVZJHQ EQU   0
APCVZJHR EQU   0
APCVZJHT EQU   0
APCVZJHW EQU   0
APCVZJH0 EQU   0
APCVZJH6 EQU   0
APCVZJI0 EQU   0
APCVZJI3 EQU   0
APCVZJJ0 EQU   0
APCVZKAA EQU   0
APCVZKBA EQU   0
APCVZKBB EQU   0
APCVZKBC EQU   0
APCVZKBD EQU   0
APCVZKBE EQU   0
APCVZKBF EQU   0
APCVZKCA EQU   0
APCVZKDA EQU   0
APCVZKGA EQU   0
APCVZKGB EQU   0
APCVZKGC EQU   0
APCVZKGD EQU   0
APCVZLCA EQU   0
APCVZLCB EQU   0
APCVZMBA EQU   0
APCVZMBD EQU   0
APCVZMBG EQU   0
APCVZMBH EQU   0
APCVZMBK EQU   0
APCVZMBM EQU   0
APCVZMIB EQU   0
APCVZMIC EQU   0
APCVZMIF EQU   0
APCVZMJB EQU   0
APCVZMJC EQU   0
APCVZMJH EQU   0
APCVZMJI EQU   0
APCVZMMA EQU   0
APCVZUAA EQU   0
APCVZUAB EQU   0
APCVZUAC EQU   0
APCVZUAD EQU   0
APCVZUAE EQU   0
APCVZUAF EQU   0
APCVZUAG EQU   0
APCVZUBB EQU   0
APCVZUFA EQU   0
APCVZUHA EQU   0
APCVZUHB EQU   0
APCVZUJA EQU   0
APCVZUKA EQU   0
APCV1CMD EQU   0
APCV1JAA EQU   0
APCV1JBJ EQU   0
APCV1JHC EQU   0
APCV1JHL EQU   0
APCV1JHT EQU   0
APCV1MAB EQU   0
APCV1MBD EQU   0
APCV2JHC EQU   0
APCV2JHL EQU   0
APCV2MBD EQU   0
I001C    EQU   0
I008P    EQU   0
I015F    EQU   0
I015P    EQU   0
I031F    EQU   0
I031P    EQU   0
I256C    EQU   0
APCTZ    EQU   APCTZ@@@
APCTZUAA EQU   APCTZ
APCTZUAB EQU   APCTZ+4
APCTZUAC EQU   APCTZ+8
APCTZUAD EQU   APCTZ+12
APCTZUAE EQU   APCTZ+16
APCTZUBB EQU   APCTZ+24
APCTZD10 EQU   APCTZ+28
APCTZD20 EQU   APCTZ+32
APCTZD40 EQU   APCTZ+36
APCTZD41 EQU   APCTZ+40
APCTZD42 EQU   APCTZ+44
APCTZD43 EQU   APCTZ+48
APCTZD44 EQU   APCTZ+52
APCTZD45 EQU   APCTZ+56
APCTZD46 EQU   APCTZ+60
APCTZD47 EQU   APCTZ+64
APCTZD48 EQU   APCTZ+68
APCTZD49 EQU   APCTZ+72
APCTZD60 EQU   APCTZ+76
APCTZD80 EQU   APCTZ+80
APCTZD4E EQU   APCTZ+84
APCTZMBA EQU   APCTZ+88
APCTZMBD EQU   APCTZ+92
APCTZMBG EQU   APCTZ+96
APCTZDX1 EQU   APCTZ+104
APCTZDX2 EQU   APCTZ+108
APCTZDX3 EQU   APCTZ+112
APCTZDX4 EQU   APCTZ+116
APCTZMBH EQU   APCTZ+120
APCTZMBK EQU   APCTZ+124
APCTZMBM EQU   APCTZ+128
APCTZMJB EQU   APCTZ+132
APCTZMJC EQU   APCTZ+136
APCTZMJH EQU   APCTZ+140
APCTZMMA EQU   APCTZ+144
APCTZDMD EQU   APCTZ+148
APCTZD81 EQU   APCTZ+152
APCTZDID EQU   APCTZ+156
APCTZDRI EQU   APCTZ+160
APCTZMJI EQU   APCTZ+164
APCTZDWT EQU   APCTZ+168
APCTZDMM EQU   APCTZ+172
APCTZDAL EQU   APCTZ+176
APCTZDBK EQU   APCTZ+180
APCTZDIP EQU   APCTZ+184
APCTZDDA EQU   APCTZ+188
APCTZDUL EQU   APCTZ+192
APCTZDEQ EQU   APCTZ+196
APCTZDDQ EQU   APCTZ+200
APCTZDUA EQU   APCTZ+204
APCTZUAF EQU   APCTZ+208
APCTZUAG EQU   APCTZ+212
APCTZDIO EQU   APCTZ+216
APCTZUHA EQU   APCTZ+220
APCTZUHB EQU   APCTZ+224
APCTZJAA EQU   APCTZ+232
APCTZJAD EQU   APCTZ+236
APCTZJAG EQU   APCTZ+240
APCTZJAJ EQU   APCTZ+244
APCTZJAM EQU   APCTZ+248
APCTZJAP EQU   APCTZ+252
APCTZJAY EQU   APCTZ+256
APCTZUFA EQU   APCTZ+260
APCTZUJA EQU   APCTZ+264
APCTZDAP EQU   APCTZ+268
APCTZKAA EQU   APCTZ+272
APCTZD82 EQU   APCTZ+276
APCTZMIB EQU   APCTZ+280
APCTZMIC EQU   APCTZ+284
APCTZD83 EQU   APCTZ+288
APCTZMIF EQU   APCTZ+296
APCTZJH0 EQU   APCTZ+300
APCTZJI0 EQU   APCTZ+304
APCTZJI3 EQU   APCTZ+308
APCTZJJ0 EQU   APCTZ+312
APCTZJBA EQU   APCTZ+316
APCTZJBD EQU   APCTZ+320
APCTZJBG EQU   APCTZ+324
APCTZJBJ EQU   APCTZ+328
APCTZJBM EQU   APCTZ+332
APCTZKCA EQU   APCTZ+340
APCTZKDA EQU   APCTZ+344
APCTZJDA EQU   APCTZ+356
APCTZJDJ EQU   APCTZ+360
APCTZJH6 EQU   APCTZ+364
APCTZJHO EQU   APCTZ+368
APCTZJHF EQU   APCTZ+372
APCTZJHE EQU   APCTZ+376
APCTZDQR EQU   APCTZ+380
APCTZJHR EQU   APCTZ+384
APCTZJHT EQU   APCTZ+388
APCTZJHW EQU   APCTZ+392
APCTZ1   EQU   APCTZ@@1
APCTZKBA EQU   APCTZ1
APCTZKBC EQU   APCTZ1+4
APCTZKBB EQU   APCTZ1+8
APCTZJHC EQU   APCTZ1+20
APCTZJHQ EQU   APCTZ1+24
APCTZKBD EQU   APCTZ1+28
APCTZKBE EQU   APCTZ1+40
APCTZUKA EQU   APCTZ1+56
APCTZKBF EQU   APCTZ1+60
APCTZJDD EQU   APCTZ1+64
APCTZJDG EQU   APCTZ1+68
APCTZJDM EQU   APCTZ1+72
APCTZLCA EQU   APCTZ1+76
APCTZLCB EQU   APCTZ1+80
APCTZDWI EQU   APCTZ1+84
APCTZJAX EQU   APCTZ1+88
APCTZKGA EQU   APCTZ1+92
APCTZKGB EQU   APCTZ1+96
APCTZKGC EQU   APCTZ1+100
APCTZKGD EQU   APCTZ1+104
APCTU    EQU   APCTU@@@
APCT1MAB EQU   APCTU
APCT1MBD EQU   APCTU+4
APCT2MBD EQU   APCTU+8
APCT1CMD EQU   APCTU+12
APCT1JAA EQU   APCTU+20
APCT1JHC EQU   APCTU+24
APCT2JHC EQU   APCTU+28
APCT1JHT EQU   APCTU+32
APCT1JHL EQU   APCTU+36
APCT2JHL EQU   APCTU+40
APCT1JBJ EQU   APCTU+44
ALLCWA   EQU   APAW
         AGO   .@UNREFD                START UNREFERENCED COMPONENTS
@NM00052 EQU   APCTU+48
APCT1MBM EQU   APCTU+16
@NM00051 EQU   APCTZ1+108
@NM00050 EQU   APCTZ1+52
@NM00049 EQU   APCTZ1+48
@NM00048 EQU   APCTZ1+44
@NM00047 EQU   APCTZ1+36
@NM00046 EQU   APCTZ1+32
@NM00045 EQU   APCTZ1+16
@NM00044 EQU   APCTZ1+12
@NM00043 EQU   APCTZ+396
@NM00042 EQU   APCTZ+352
@NM00041 EQU   APCTZ+348
@NM00040 EQU   APCTZ+336
@NM00039 EQU   APCTZ+292
APCTZJFA EQU   APCTZ+228
APCTZMBR EQU   APCTZ+100
@NM00038 EQU   APCTZ+20
SSAGSSCM EQU   SSAGARBK+52
SSAGSSWA EQU   SSAGARBK+48
SSAGJFCB EQU   SSAGARBK+44
SSAGSSNM EQU   SSAGARBK+40
SSAGADSP EQU   SSAGARBK+36
SSAGUNIT EQU   SSAGARBK+32
SSAGSOUT EQU   SSAGARBK+28
SSAGDUMY EQU   SSAGARBK+24
SSAGDISP EQU   SSAGARBK+20
SSAGDDNM EQU   SSAGARBK+16
SSAGNRBP EQU   SSAGARBK+12
@NM00055 EQU   SSAGARBK+10
SSAGDMLN EQU   SSAGARBK+8
SSAGRBFL EQU   SSAGARBK+2
SSAGRBLN EQU   SSAGARBK
SSAGGMLN EQU   SSAGEHDR+20
SSAGJBNM EQU   SSAGEHDR+16
SSAGCNCL EQU   SSAGEHDR+12
SSAGARBP EQU   SSAGEHDR+8
@NM00054 EQU   SSAGFLGS
SSAGWAIT EQU   SSAGFLGS
SSAGLEN  EQU   SSAGEHDR
SSOBSSIB EQU   SSOB+8
SSOBFUNC EQU   SSOB+6
SSOBLEN  EQU   SSOB+4
SSOBID   EQU   SSOB
APSVWORK EQU   APSV+80
@NM00053 EQU   APSV+80
APSVFREE EQU   APSV+76
APSVAPSM EQU   APSV+72
APSVRG12 EQU   APSVREGS+56
APSVRG11 EQU   APSVREGS+52
APSVRG10 EQU   APSVREGS+48
APSVRG9  EQU   APSVREGS+44
APSVRG8  EQU   APSVREGS+40
APSVRG7  EQU   APSVREGS+36
APSVRG6  EQU   APSVREGS+32
APSVRG5  EQU   APSVREGS+28
APSVRG4  EQU   APSVREGS+24
APSVRG3  EQU   APSVREGS+20
APSVRG2  EQU   APSVREGS+16
APSVRG1  EQU   APSVREGS+12
APSVRG0  EQU   APSVREGS+8
APSVRG15 EQU   APSVREGS+4
APSVRG14 EQU   APSVREGS
APSVNEXT EQU   APSV+8
APSVPREV EQU   APSV+4
APSVAPSC EQU   APSV
@NM00037 EQU   APCT+1556
APCTSVCT EQU   APCT+1552
APCTDAVT EQU   APCT+1548
APCTLOGL EQU   APCT+1544
@NM00036 EQU   APCT+1540
APCTDMPU EQU   APCT+1536
APCTDMPM EQU   APCT+1532
APCTNDMP EQU   APCT+1530
APCTASID EQU   APCT+1528
APCTLGPG EQU   APCT+1526
APCTLGLN EQU   APCT+1524
APCTAPVU EQU   APCT+1520
APCTABR  EQU   APCT+1116
APCTACTR EQU   APCT+1112
APCTLOGD EQU   APCT+1108
APCTDCLD EQU   APCT+1104
APCTIOAP EQU   APCT+1100
@NM00035 EQU   APCT+1080
@NM00034 EQU   APCT+1078
APCTKCAX EQU   APCT+1076
APCTABND EQU   APCT+1072
@NM00033 EQU   APCT+1068
APCTAPIO EQU   APCT+1064
APCTCSCT EQU   APCT+1060
APCTSTDF EQU   APCT+1056
APCTSTMX EQU   APCT+1052
APCTRGMX EQU   APCT+1048
APCTSIZE EQU   APCT+1046
APCTCTUB EQU   APCT+1045
APCTMFID EQU   APCT+1044
APCTMFSZ EQU   APCT+1040
APCTCRTN EQU   APCT+1036
APCTAPCP EQU   APCT+1032
APCTAMNA EQU   APCT+1028
APCTEMNA EQU   APCT+1024
APCTAALP EQU   APCT+1020
APCTEALP EQU   APCT+1016
@NM00032 EQU   APCT+1012
@NM00031 EQU   APCT+1008
@NM00030 EQU   APCT+1004
APCTEIPL EQU   APCT+1000
@NM00029 EQU   APCT+996
@NM00028 EQU   APCT+992
@NM00027 EQU   APCT+988
@NM00026 EQU   APCT+984
@NM00025 EQU   APCT+980
APCTECPW EQU   APCT+976
APCTEULD EQU   APCT+972
APCTECPT EQU   APCT+968
APCTEALC EQU   APCT+964
APCTECBL EQU   APCT+960
APCTECIT EQU   APCT+956
APCTCQAF EQU   APCTCQAQ
APCTCQL  EQU   APCTAPCQ+4
APCTCQF  EQU   APCTAPCQ
APCTCQLK EQU   APCT+940
@NM00024 EQU   @NM00020+2
@NM00023 EQU   APCTPRSW
APCTAPST EQU   APCTPRSW
@NM00022 EQU   APCTPRSW
@NM00021 EQU   APCTSTAT
APCTWARM EQU   APCTSTAT
APCTTERM EQU   APCTSTAT
APCTHALT EQU   APCTSTAT
APCTQSCE EQU   APCTSTAT
APCTSTRT EQU   APCTSTAT
APCTACT  EQU   APCTSTAT
@NM00019 EQU   APCT+935
APCTSOUT EQU   APCT+934
APCTDAID EQU   APCT+933
APCTSV34 EQU   APCT+932
APCTMJOB EQU   APCT+928
APCTTCB  EQU   APCT+924
APCTASCB EQU   APCT+920
APCTDCNW EQU   APCT+918
APCTDCNR EQU   APCT+916
@NM00018 EQU   APCT+912
@NM00017 EQU   APCT+908
@NM00016 EQU   APCT+904
@NM00015 EQU   APCT+900
@NM00014 EQU   APCTERRS+22
APCTERTJ EQU   APCTERRS+20
APCTERTD EQU   APCTERRS+18
APCTERTC EQU   APCTERRS+16
APCTERTB EQU   APCTERRS+14
APCTERTA EQU   APCTERRS+12
APCTERT9 EQU   APCTERRS+10
APCTERT3 EQU   APCTERRS+8
APCTERT2 EQU   APCTERRS+6
APCTERT1 EQU   APCTERRS+4
APCTERT0 EQU   APCTERRS+2
APCTERTT EQU   APCTERRS
APCTDSAP EQU   APCT+872
APCTISUB EQU   APCT+868
APCTUBAP EQU   APCT+864
APCTAPDS EQU   APCT+860
APCTUBIC EQU   APCT+856
APCTUBIS EQU   APCT+852
APCTAPUB EQU   APCT+848
APCTUBLK EQU   APCT+844
APCTBR1A EQU   APCTBR14+2
@NM00013 EQU   APCTBR14
APCTSMSZ EQU   APCTSMAD+2
@NM00012 EQU   APCTSMAD+1
@NM00011 EQU   APCTSMAD
APCTSMIS EQU   APCTSMIN+2
@NM00010 EQU   APCTSMIN+1
APCTSMSP EQU   APCTSMIN
@NM00009 EQU   APCT+30
APCTLINE EQU   APCT+28
APCTLBSZ EQU   APCT+24
APCTREG  EQU   APCT+20
@NM00008 EQU   APCTENQM
APCTSSVT EQU   APCT+8
APCTUSER EQU   APCT+4
APCTID   EQU   APCT
@NM00007 EQU   APAW+68
LASTARB  EQU   APAW+64
ALLMSGID EQU   APAW+60
BSRTOT   EQU   APAW+56
NUMIER   EQU   APAW+54
NPNTOT   EQU   APAW+52
EXITINF3 EQU   EXITINFO+3
EXITINF2 EQU   EXITINFO+2
@NM00006 EQU   EXITINF1
EXITHOLD EQU   EXITINF1
EXITCANC EQU   EXITINF1
EXITCOMM EQU   EXITINF1
EXITREJ  EQU   EXITINF1
@NM00005 EQU   EXITINF0
EXITRCON EQU   EXITINF0
EXITENRQ EQU   EXITINF0
EXITALOK EQU   EXITINF0
EXITIMPS EQU   EXITINF0
EXITIMPP EQU   EXITINF0
@NM00004 EQU   APAW+46
BSAVAIL  EQU   APAW+44
BSUNLD   EQU   APAW+42
USCAVAIL EQU   APAW+40
USCUNLD  EQU   APAW+38
NUMNTSAT EQU   APAW+36
NUMALREQ EQU   APAW+32
ACNCLECB EQU   APAW+28
ALLOCNTR EQU   APAW+24
@NM00003 EQU   APAW+21
ALLENQRC EQU   APAW+20
INITTCB  EQU   APAW+16
ALLCWAIT EQU   ALLRSRCE
ALLSTART EQU   ALLRSRCE
ALLAPUB  EQU   ALLRSRCE
ALLALL   EQU   ALLRSRCE
ALLSER   EQU   ALLRSRCE
@NM00002 EQU   ALLSTAT3
ALLQUE2  EQU   ALLSTAT2
ALLERRN2 EQU   ALLSTAT2
ALLMLWTO EQU   ALLSTAT2
ALLRES   EQU   ALLSTAT2
ALLQRMV  EQU   ALLSTAT2
ALLQADD  EQU   ALLSTAT2
ALLQUE   EQU   ALLSTAT2
ALLDYN   EQU   ALLSTAT2
@NM00001 EQU   ALLSTAT1
ALLMARK  EQU   ALLSTAT1
ALLINST  EQU   ALLSTAT1
ALLHOLD  EQU   ALLSTAT1
ALLNLAA  EQU   ALLSTAT1
ALLAPDS  EQU   ALLSTAT0
ALLERREN EQU   ALLSTAT0
ALLRQVAL EQU   ALLSTAT0
ALLMONWT EQU   ALLSTAT0
ALLJCLOK EQU   ALLSTAT0
ALLMONUP EQU   ALLSTAT0
ALLWAIT  EQU   ALLSTAT0
ALLFAIL  EQU   ALLSTAT0
FIRSTARB EQU   APAW+4
.@UNREFD ANOP                          END UNREFERENCED COMPONENTS
@RF00061 EQU   @EL00001
@RF00060 EQU   @EL00001
@RF00067 EQU   @EL00001
@ENDDATA EQU   *
         END   IGTJHE,(C'PLS2109',0701,77092)
