 /*************************************************************
 *                                                                     *
 *                           SMFDEFT                                   *
 *                                                                     *
 **************************************************************
 *                                                                     *
 *                           TSO SMF RECORD DEFINITIONS                C
 *                                                                     *
 *************************************************************/
         DCL 1 SMFTHDR BASED (SMFPTR) UNALIGNED,
              2 SMFTRES1 CHAR(1),
              2 TSOTYPE BIT(8),
                   /* TYPE
                   30 - START TSO
                   31 - TIOC INITIALIZATION
                   32 - DRIVER
                   33 - DRIVER MODIFY
                   34 - TSO STEP TERMINATION
                   35 - TSO LOGOFF
                   38 - INITIAL TSO CONFIGURATION
                   40 - DYNAMIC DD
                   41 - MODIFY TSO
                   42 - STOP TSO
                   */
              2 SMFTWTME BIN FIXED(31,0),
                   /* TIME AT WHICH RECORD WAS WRITTEN - .01 SECS */
              2 SMFTWDTE DEC FIXED(7,0),
                   /* DATE, IN JULIAN FORM ON WHICH RECORD WAS
                   WRITTEN - 00YYDDDC */
              2 SMFTID CHAR(2),
                   /* SYSTEM IDENTIFICATION. */
              2 SMFTMDL CHAR(2);
                   /* SYSTEM MODEL IDENTIFIER. */
                   /*************************
                   *
                   * TYPE 34 TSO SMF RECORD DEFINITION
                   *
                   ****************************/
         DCL 1 SMFT34 BASED (SMFPTR) UNALIGNED,
              2 FILL CHAR(14),
                   /* PAD FOR STANDARD RECORD HEADER */
              2 USERID CHAR(8),
                   /* USER IDENTIFICATION */
              2 LOGTME FIXED BIN(31,0),
                   /* LOGON TIME IN .01 SECS */
              2 LOGDTE DEC FIXED(7,0),
                   /* LOGN DATE IN JULIAN - 00YYDDDC */
              2 USER CHAR(8),
                   /* RESERVED FOR USER */
              2 STEPNO BIT(8),
                   /* STEP NUMBER IN SESSION */
              2 OCCTME FIXED BIN(31,0),
                   /* RESERVED */
              2 TPUTCNT FIXED BIN(31,0),
                   /* LINE-OUT COUNT, NUMBER OF TPUTS ISSUED. */
              2 TGETCNT FIXED BIN(31,0),
                   /* LINE-IN COUNT, NUMBER OF TGETS SATISFIED. */
              2 COMPLCODE FIXED BIN(15,0),
                   /* JOB COMPLETION CODE */
              2 PRTY BIT(8),
                   /* LOGN PRIORITY */
              2 TMPNAME CHAR(8),
                   /* TERMINAL MONITOR PROGRAM NAME */
              2 STEPNAME CHAR(8),
                   /* STEP NAME (PROCEDURE) */
              2 REGSIZE FIXED BIN(15,0),
                   /* SIZE OF REGION (1K BLOCKS) */
              2 SMFT34RES3 CHAR(2),
                   /* RESERVED */
              2 REGUSED FIXED BIN(15,0),
                   /* MAIN STORAGE USED (1K BLOCKS) */
              2 SMFT34RES3A CHAR(6),
                   /* RESERVED */
              2 PKF BIT(8),
                   /* STORAGE PROTECT KEY - XXXX0000 */
              2 SMFT34RES4 CHAR(3),
                   /* RESERVED */
              2 ALLOCTME FIXED BIN(31,0),
                   /* DEVICE ALLOCATION TIME IN HUNDREDTHS
                   OF A SECOND. */
              2 LOADTME FIXED BIN(31,0),
                   /* PROBLEM PROGRAM LOAD TIME OF DAY
                   IN HUNDREDTHS OF A SECOND. */
              2 SMFT34RES5 CHAR(8),
                   /* RESERVED. */
              2 DEVLEN BIT(16),
                   /* CONTAINS THE LENGTH OF THE FOLLOWING ARRAY OF
                   DEVICE FIELDS, PLUS 2 FOR THE LNGTH OF DEVLEN
                   ITSELF. */
              2 DEVARRAY (1000),
               3 DEVDESCR,
                4 DEVCLASS BIT (8),
                   /* COPIED FROM UCBTYP+2 IN UCB */
                4 DEVTYPE BIT (8),
                   /* COPIED FROM UCBTYP+3 IN UCB */
                4 CHANNEL BIT (8),
                   /* COPIED FROM LOW-ORDER THREE BITS OF UCB CHA
                   FIELD AT UCB+4 */
                4 DEVADDR BIT (8),
                   /* COPIED FROM UCBUA AT UCB+5 */
               3 ACCESSCNT BIT (32);
                   /* NOTE THAT THE UPPER BOUND OF THE ABOVE ARRAY IS
                   VARIABLE AND IS NOT ACTUALLY FIXED AT 1000.
                   CONSEQUENTLY, DATA FOLLOWING THE ARRAY IN THE
                   ACTUAL RECORD HAS BEEN DEFINED AS A SEPARATE
                   LEVEL 1 BASED VARIABLE.  IN ORDER TO ASSIGN THE
                   PROPER ADDRESS TO T34PTR, OVERLAY DEFINE IT AS
                   A FIXED BINARY DATA VARIABLE, AND, AFTER
                   ASSIGNING THE ADDRESS DEVLEN TO T34PTR, ADD THE
                   VALUE IN DEVLEN TO IT. */
         DCL 1 MORET34 BASED (T34PTR) UNALIGNED,
              2 LEN1 BIT (8),
                   /* LENGTH OF REST OF RECORD, EXCLUDING THIS
                   FIELD. */
              2 SCPUTME BIT (24),
                   /* STEP CPU TIME IN .01 SECS */
              2 LEN2 BIT (8),
                   /* NUMBER OF ACCOUNTING FIELDS THAT FOLLOW.  EACH
                   ENTRY FOR AN ACCOUNTING FIELD CONTAINS THE
                   LENGTH OF THE FIELD (1 BYTE, BINARY), FOLLOWED
                   BY THE FIELD (EBCDIC).  AN OMITTED FIELD IS
                   REPRESENTED BY A LENGTH INDICATOR OF 0. */
              2 SACCTFLDS,
                   3 SACCTLEN BIT (8),
                   3 SACCTFLD CHAR(144);
                   /*************************
                   *
                   * TYPE 35 TSO SMF RECORD DEFINITION
                   *
                   ****************************/
         DCL 1 SMFT35 BASED (SMFPTR) UNALIGNED,
              2 FILL CHAR(14),
                   /* PAD FOR STANDARD RECORD HEADER */
              2 USERID CHAR(8),
                   /* USER IDENTIFICATION */
              2 LOGTME FIXED BIN(31,0),
                   /* LOGON TIME IN .01 SECS */
              2 LOGDTE DEC FIXED(7,0),
                   /* LOGN DATE IN JULIAN - 00YYDDDC */
              2 USER CHAR(8),
                   /* RESERVED FOR USER */
              2 NOSTEPS BIT(8),
                   /* NUMBER OF STEPS IN SESSION */
              2 SMFT35RES2 CHAR(4),
                   /* RESERVED */
              2 TPUTCNT FIXED BIN(31,0),
                   /* LINE-OUT COUNT, NUMBER OF TPUTS ISSUED. */
              2 TGETCNT FIXED BIN(31,0),
                   /* LINE-IN COUNT, NUMBER OF TGETS SATISFIED. */
              2 COMPLCODE FIXED BIN(15,0),
                   /* JOB COMPLETION CODE */
              2 PRTY BIT(8),
                   /* LOGN PRIORITY */
              2 ENQTME FIXED BIN(31,0),
                   /* LOGN ENQUEUE TIME OF DAY IN .01 SECS */
              2 ENQDTE DEC FIXED(7,0),
                   /* LOGN ENQUEUE DATE IN JULIAN - 00YYDDDC */
              2 TERMFLG BIT(8),
                   /* TERMINATION INDICATORS
                   XX.. .X.X RESERVED
                   ..1. .... CANCELED AT EXIT IEJUJI
                   ...1 .... CANCELED AT EXIT IEJUSI
                   .... 1... CANCELED AT EXIT IEFACTRT
                   .... ..1. ABEND
                   */
              2 SYSOUT BIT(40),
                   /* SYSOUT CLASSES USED BY THE PROGRAM AND MESSAGES*/
                   /* BYTE -0       1       2       3       4        */
                   /* BIT  -0123456701234567012345670123456701234567
                   /* CLASS-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789     */
              2 SMFT35RES3 CHAR(4),
                   /* RESERVED */
              2 PKF BIT(8),
                   /* STORAGE PROTECT KEY - XXXX0000 */
              2 SMFT35RES4 CHAR(19),
                   /* RESERVED */
              2 SMFT35LEN BIT(8),
                   /* LENGTH OF REST OF RECORD (NEXT 4 FIELDS) */
              2 SMFT35RES5 CHAR(20),
                   /* RESERVED (BLANKS) */
              2 SESSIONTME BIT(24),
                   /* SESSION CPU TIME IN .01 SECS */
              2 TACCTLEN BIT(8),
                   /* NUMBER OF ACCOUNTING FIELDS. */
              2 TACCTFLD CHAR(144);
                   /* ACCOUNTING FIELDS. */
