         MACRO
         SETSTAT   &NAME,&COND
         GBLC      &FNAME(255),&FSTATUS(255)
         GBLA      &FNUM(255),&IND1
         LCLA      &SUM,&J
&FNAME(&IND1) SETC '&NAME'
&SUM     SETA      1
&J       SETA     1
         AIF       ('&NAME' NE 'ALL').S1
&J       SETA      &IND1
         AGO       .S2
.LOOP    ANOP
&SUM     SETA      &SUM+&FNUM(&J)
&J       SETA      &J+1
.S1      AIF       ('&FNAME(&SUM)' NE '&NAME').LOOP
         AIF       ('&FSTATUS(&SUM)' EQ '&COND').END
&J       SETA      &SUM+&FNUM(&J)
         AIF       ('&FSTATUS(&SUM)' EQ 'DISK').S2
         MNOTE ' THE STATUS OF &FNAME(&SUM) CANNOT BE SET TO &COND'
         MEXIT
.S2      ANOP
&FSTATUS(&SUM) SETC '&COND'
&SUM     SETA      &SUM+1
         AIF       (&SUM LT &J).S2
.END     MEND
