//* ********************************************************
//* *  INSTALL THE 'LISTAX'   TSO COMMAND                  *
//* *  NOTE: MODULE IS NOT REENTRANT                       *
//* ********************************************************
//LISTAX   EXEC ASMHCL,COND=(0,NE),
//         PARM.ASM='OBJECT,NODECK,TERM,ALIGN,NOLIST',
//         PARM.LKED='LIST,MAP'
//SYSTERM  DD SYSOUT=*
//SYSIN    DD DSN=SHARE.TSOSRC(LISTAX),DISP=SHR
//LKED.SYSLMOD DD DSN=SYS1.SHARE.LOAD,DISP=SHR,SPACE=,UNIT=
//LKED.SYSIN DD *
 NAME LISTAX(R)
/*
