         TITLE 'IKJEFF08 - GEN JOB CARD ROUTINE                        *
                       '
IKJEFF08 CSECT ,                                                   0001
@MAINENT DS    0H                                                  0001
         USING *,@15                                               0001
         B     @PROLOG                                             0001
         DC    AL1(16)                                             0001
         DC    C'IKJEFF08  73.293'                                 0001
         DROP  @15
@PROLOG  STM   @14,@12,12(@13)                                     0001
         BALR  @12,0                                               0001
@PSTART  DS    0H                                                  0001
         USING @PSTART,@12                                         0001
         L     @00,@SIZDATD                                        0001
         GETMAIN R,LV=(0)
         LR    @11,@01                                             0001
         USING @DATD,@11                                           0001
         ST    @13,@SA00001+4                                      0001
         LM    @00,@01,20(@13)                                     0001
         ST    @11,8(,@13)                                         0001
         LR    @13,@11                                             0001
         MVC   @PC00001(20),0(@01)                                 0001
DUMMYLBL DS    0H                                                  0003
*                                                                  0033
*   /*****************************************************************/
*   /*                                                               */
*   /* END OF IKJEFFMT MAPPING MACRO                                 */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0034
*                                                                  0034
*   /*****************************************************************/
*   /*                                                               */
*   /* INITIALIZATION BEFORE GENERATE JOB STATEMENT                  */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0034
*   HTPTR=ADDR(HIST);               /* USE LOCAL POINTER TO HISTORY
*                                      TABLE                         */
         L     HTPTR,@PC00001                                      0034
*   INGEN=INGEN+1;                  /* INDICATE IN IKJEFF08          */
         LA    @10,1                                               0035
         SLR   @04,@04                                             0035
         IC    @04,INGEN(,HTPTR)                                   0035
         AR    @10,@04                                             0035
         STC   @10,INGEN(,HTPTR)                                   0035
*   HOLD=STMTPTR;                   /* HOLD THE POINTER TO THE     0036
*                                      ORIGINAL INPUT CARD TO ONE  0036
*                                      SIDE WHILE THE GENERATED CARD
*                                      IS BUILT AND PROCESSED        */
         L     @10,@PC00001+4                                      0036
         L     HOLD,STMTPTR(,@10)                                  0036
*   PASS=PCONTAB;                   /* SAVE CONTROL TABLE POINTER TO
*                                      PASS TO IKJEFF06              */
         L     @10,@PC00001+12                                     0037
         L     @10,PCONTAB(,@10)                                   0037
         ST    @10,PASS                                            0037
*   CURRJCL=PRIORJCL;                                              0038
         MVC   CURRJCL(4,HTPTR),PRIORJCL(HTPTR)                    0038
*   CT=7;                           /* SET THE COUNTER FOR 7 LOOPS TO
*                                      CLEAR AND GENERATE A JOB CARD
*                                      AND CONTINUATIONS -- NOTE THAT
*                                      6 CARDS MAY BE BUILT; THEN THE
*                                      ORIGINAL NON-JOB STATEMENT IS
*                                      PROCESSED                     */
         LA    CT,7                                                0039
*   GO TO BLANK;                    /* INITIALIZE THE FIRST CARD     */
*                                                                  0040
         B     BLANK                                               0040
*   /*****************************************************************/
*   /*                                                               */
*   /* LOOP TO GENERATE JOB CARD AND CONTINUATIONS                   */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0041
*COUNT:                                                            0041
*   IF CT=0 THEN                    /* IF THE LOOP COUNTER IS DOWN TO
*                                      ZERO, THEN RE-PROCESS THE   0041
*                                      ORIGINAL NON-JOB            0041
*                                      STATEMENT--HAVE ALREADY     0041
*                                      HANDLED JOB CARDS IN THE LOOP */
COUNT    LTR   CT,CT                                               0041
         BNZ   @RF00041                                            0041
*     DO;                                                          0042
*       STMTPTR=HOLD;               /* RESTORE THE ORIGINAL CARD     */
         L     @10,@PC00001+4                                      0043
         ST    HOLD,STMTPTR(,@10)                                  0043
*       CALL IKJEFF06(PASS);        /* IKJEFF06 IS JCL CARD        0044
*                                      CONTROLLER                    */
         LA    @10,PASS                                            0044
         ST    @10,@AL00001                                        0044
         L     @15,@CV00065                                        0044
         LA    @01,@AL00001                                        0044
         BALR  @14,@15                                             0044
*       INGEN=INGEN-1;                                             0045
         SLR   @10,@10                                             0045
         IC    @10,INGEN(,HTPTR)                                   0045
         BCTR  @10,0                                               0045
         STC   @10,INGEN(,HTPTR)                                   0045
*       RETURN;                     /* RETURN TO WHOEVER CALLED '08  */
@EL00001 L     @13,4(,@13)                                         0046
@EF00001 L     @00,@SIZDATD                                        0046
         LR    @01,@11                                             0046
         FREEMAIN R,LV=(0),A=(1)
@ER00001 LM    @14,@12,12(@13)                                     0046
         BR    @14                                                 0046
*     END;                                                         0047
*                                                                  0048
*   /*****************************************************************/
*   /*                                                               */
*   /* FIRST CARD HAS JOBNAME AND ACCOUNTING INFORMATION             */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0048
*   IF CT=6 THEN                                                   0048
@RF00041 CH    CT,@CH00122                                         0048
         BNE   @RF00048                                            0048
*     DO;                           /* PREPARE FOR THE FIRST CARD -- */
*       CARD(3:10)=USERID;          /* JOBNAME=USERID                */
         L     @10,@PC00001+8                                      0050
         MVC   CARD+2(8),USERID(@10)                               0050
*       CARD(13:15)='JOB';          /* TWO BLANKS BEFORE 'JOB'       */
         MVC   CARD+12(3),@CC00257                                 0051
*       IF HTACCNTL^=0 THEN         /* INSERT USER'S ACCOUNTING    0052
*                                      INFORMATION IF HAVE ANY       */
         SLR   @10,@10                                             0052
         LH    @04,HTACCNTL(,HTPTR)                                0052
         CR    @04,@10                                             0052
         BE    @RF00052                                            0052
*         DO;                                                      0053
*           IF HTACNTC1=0 THEN      /* SIMPLE CASE IF ALL THE ACCOUNT
*                                      INFO FITS ON ONE CARD         */
         CH    @10,HTACNTC1(,HTPTR)                                0054
         BNE   @RF00054                                            0054
*             KOL=HTACCNTL;         /* GET LENGTH OF INFO            */
         ST    @04,KOL                                             0055
*           ELSE                    /* ACCOUNTING INFO WON'T ALL FIT
*                                      ON THE FIRST CARD             */
*             KOL=HTACNTC1;         /* FILL CARD (EXCEPT COMMA)      */
         B     @RC00054                                            0056
@RF00054 LH    @10,HTACNTC1(,HTPTR)                                0056
         ST    @10,KOL                                             0056
*           IF KOL>HTC1MAX THEN     /* ERROR EXIT IF ACCOUNT INFO  0057
*                                      WON'T FIT ON GENERATED JOB  0057
*                                      CARD                          */
@RC00054 CLC   KOL(4),@CF00200                                     0057
         BNH   @RF00057                                            0057
*             DO;                                                  0058
*               CALL ACNTIBAD;      /* ISSUE ERROR MSG AND TURN QUIT
*                                      BIT ON                        */
         BAL   @14,ACNTIBAD                                        0059
*               KOL=HTC1MAX;        /* CONTINUE UNTIL CALL IKJEFF06  */
         MVC   KOL(4),@CF00200                                     0060
*             END;                                                 0061
*           KOL=KOL+OPRNDCOL;       /* LAST COLUMN FOR MOVE =LENGTH +
*                                      (BEGINCOL-1)                  */
@RF00057 LA    @10,16                                              0062
         A     @10,KOL                                             0062
         ST    @10,KOL                                             0062
*           CARD(17:KOL)=HTACCNTI;  /* PUT USER'S ACCOUNT INFORMATION
*                                      ON THE JOB CARD               */
         SH    @10,@CH00060                                        0063
         L     @04,HTACCNTP(,HTPTR)                                0063
         EX    @10,@SM00287                                        0063
*         END;                      /* END OF INSERTING              */
*       ELSE                        /* IF NO ACCOUNTING INFO         */
*         KOL=OPRNDCOL;             /* WILL PUT COMMA IN 17          */
         B     @RC00052                                            0065
@RF00052 MVC   KOL(4),@CF00069                                     0065
*     END;                                                         0066
*                                                                  0066
@RC00052 DS    0H                                                  0067
*   /*****************************************************************/
*   /*                                                               */
*   /* SECOND CARD HAS CONTINUATION OF ACCOUNTING INFORMATION        */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0067
*   IF CT=5 THEN                                                   0067
@RF00048 CH    CT,@CH00259                                         0067
         BNE   @RF00067                                            0067
*     DO;                                                          0068
*       IF HTACNTC1=0 THEN          /* IF DON'T NEED TO CONTINUE   0069
*                                      ACCOUNTING INFO ONTO THIS CARD*/
         SLR   @10,@10                                             0069
         CH    @10,HTACNTC1(,HTPTR)                                0069
         BE    @RT00069                                            0069
*         GO TO SKIP;               /* DON'T PUT OUT THIS CARD       */
*       IF HTACNTC2=0 THEN          /* ACCOUNT INFO WILL FIT ON THIS
*                                      CARD                          */
         CH    @10,HTACNTC2(,HTPTR)                                0071
         BNE   @RF00071                                            0071
*         KOL=HTACCNTL;             /* GET END COL OF INSERT         */
         LH    @10,HTACCNTL(,HTPTR)                                0072
         ST    @10,KOL                                             0072
*       ELSE                        /* ACCOUNT INFO WILL BE CONTINUED*/
*         KOL=HTACNTC2;             /* GET END COL OF INSERT SECTION */
         B     @RC00071                                            0073
@RF00071 LH    @10,HTACNTC2(,HTPTR)                                0073
         ST    @10,KOL                                             0073
*       KOL=(KOL-HTACNTC1)+2;       /* LAST COLUMN FOR MOVE        0074
*                                      =LENGTH(COL-1) + (BEGINCOL-1) */
@RC00071 L     @10,KOL                                             0074
         SH    @10,HTACNTC1(,HTPTR)                                0074
         AH    @10,@CH00110                                        0074
         ST    @10,KOL                                             0074
*       IF KOL>CARDMAX THEN         /* ERROR EXIT IF ACCOUNT INFO  0075
*                                      WON'T FIT ON JOB CARD         */
         CH    @10,@CH00067                                        0075
         BNH   @RF00075                                            0075
*         DO;                                                      0076
*           CALL ACNTIBAD;          /* ISSUE ERROR MSG AND TURN QUIT
*                                      BIT ON                        */
         BAL   @14,ACNTIBAD                                        0077
*           KOL=CARDMAX;            /* CONTINUE UNTIL CALL IKJEFF06  */
         MVC   KOL(4),@CF00067                                     0078
*         END;                                                     0079
*       ACNTIPTR=ADDR(HTACCNTI)+HTACNTC1+1;/* POINTER TO FIRST COL OF
*                                      INSERT SECTION                */
@RF00075 LH    ACNTIPTR,HTACNTC1(,HTPTR)                           0080
         A     ACNTIPTR,HTACCNTP(,HTPTR)                           0080
         AH    ACNTIPTR,@CH00106                                   0080
*       CARD(4:KOL)=ACNTINST;       /* PUT CONTINUATION OF ACCOUNTING
*                                      INFORMATION ON CARD (NOTE SKIP
*                                      OVER COMMA IN HTACCNTI)       */
         L     @10,KOL                                             0081
         SH    @10,@CH00094                                        0081
         EX    @10,@SM00289                                        0081
*     END;                                                         0082
*                                                                  0082
*   /*****************************************************************/
*   /*                                                               */
*   /* THIRD CARD HAS CONTINUATION OF ACCOUNTING INFORMATION         */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0083
*   IF CT=4 THEN                                                   0083
@RF00067 CH    CT,@CH00094                                         0083
         BNE   @RF00083                                            0083
*     DO;                                                          0084
*       IF HTACNTC2=0 THEN          /* IF DON'T NEED TO CONTINUE   0085
*                                      ACCOUNTING INFO ONTO THIS CARD*/
         LH    @10,HTACNTC2(,HTPTR)                                0085
         LTR   @10,@10                                             0085
         BZ    @RT00085                                            0085
*         GO TO SKIP;               /* DON'T PUT OUT THIS CARD       */
*       KOL=(HTACCNTL-HTACNTC2)+2;  /* LAST COLUMN FOR MOVE        0087
*                                      =LENGTH(COL-1) + (BEGINCOL-1) */
         LCR   @10,@10                                             0087
         AH    @10,HTACCNTL(,HTPTR)                                0087
         AH    @10,@CH00110                                        0087
         ST    @10,KOL                                             0087
*       IF KOL>CARDMAX THEN         /* ERROR EXIT IF ACCOUNT INFO  0088
*                                      WON'T FIT ON JOB CARD         */
         CH    @10,@CH00067                                        0088
         BNH   @RF00088                                            0088
*         DO;                                                      0089
*           CALL ACNTIBAD;          /* ISSUE ERROR MSG AND TURN QUIT
*                                      BIT ON                        */
         BAL   @14,ACNTIBAD                                        0090
*           KOL=CARDMAX;            /* CONTINUE UNTIL CALL IKJEFF06  */
         MVC   KOL(4),@CF00067                                     0091
*         END;                                                     0092
*       ACNTIPTR=ADDR(HTACCNTI)+HTACNTC2+1;/* POINTER TO FIRST COL OF
*                                      INSERT SECTION                */
@RF00088 LH    ACNTIPTR,HTACNTC2(,HTPTR)                           0093
         A     ACNTIPTR,HTACCNTP(,HTPTR)                           0093
         AH    ACNTIPTR,@CH00106                                   0093
*       CARD(4:KOL)=ACNTINST;       /* PUT CONTINUATION OF ACCOUNTING
*                                      INFORMATION ON CARD (NOTE SKIP
*                                      OVER COMMA IN HTACCNTI)       */
         L     @10,KOL                                             0094
         SH    @10,@CH00094                                        0094
         EX    @10,@SM00289                                        0094
*     END;                                                         0095
*                                                                  0096
*   /*****************************************************************/
*   /*                                                               */
*   /* NEXT CARD HAS PROGRAMMER NAME=USERID                          */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0096
*   IF CT=3 THEN                                                   0096
@RF00083 CH    CT,@CH00061                                         0096
         BNE   @RF00096                                            0096
*     DO;                           /* FILL IN THIS CARD             */
*       CARD(OPRNDCOL:23)=USERID;   /* USE USERID AS PGMR NAME       */
         L     @10,@PC00001+8                                      0098
         MVC   CARD+15(8),USERID(@10)                              0098
*       CARD(31:53)='GENERATED JOB STATEMENT';                     0099
         MVC   CARD+30(23),@CC00263                                0099
*       KOL=OPRNDCOL;                                              0100
         MVC   KOL(4),@CF00069                                     0100
*     END;                                                         0101
*                                                                  0101
*   /*****************************************************************/
*   /*                                                               */
*   /* NEXT CARD HAS NOTIFY=USERID                                   */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0102
*   IF CT=2 THEN                    /* FILL IN THIRD CARD            */
@RF00096 CH    CT,@CH00110                                         0102
         BNE   @RF00102                                            0102
*     DO;                                                          0103
*       IF NONOTIFY='1'B THEN       /* ADD 'NOTIFY=' UNLESS NONO WAS
*                                      SPECIFIED -- IN THAT CASE THIS
*                                      CARD IS SIMPLY SKIPPED        */
         TM    NONOTIFY(HTPTR),B'00010000'                         0104
         BO    @RT00104                                            0104
*         GO TO SKIP;               /* NONOTIFY WAS SPECIFIED        */
*       CARD(OPRNDCOL:22)='NOTIFY=';                               0106
         MVC   CARD+15(7),@CC00267                                 0106
*       CARD(23:30)=USERID;                                        0107
         L     @10,@PC00001+8                                      0107
         MVC   CARD+22(8),USERID(@10)                              0107
*       KOL=23;                                                    0108
         MVC   KOL(4),@CF00261                                     0108
*     END;                                                         0109
*                                                                  0109
*   /*****************************************************************/
*   /*                                                               */
*   /* LAST CARD HAS MSGLEVEL=(1,1)                                  */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0110
*   IF CT=1 THEN                                                   0110
@RF00102 CH    CT,@CH00106                                         0110
         BNE   @RF00110                                            0110
*     DO;                           /* PUT 'MSGLEVEL=' ON THE LAST 0111
*                                      CARD AND GO STRAIGHT TO HAVE
*                                      IT PROCESSED WITHOUT ADDING A
*                                      CONTINUATION COMMA            */
*       CARD(OPRNDCOL:29)='MSGLEVEL=(1,1)';                        0112
         MVC   CARD+15(14),@CC00270                                0112
*       GO TO PROCESS;              /* WILL CALL PROCESSING RTN      */
         B     PROCESS                                             0113
*     END;                                                         0114
*                                                                  0115
*   /*****************************************************************/
*   /*                                                               */
*   /* PUT COMMA AFTER OPERAND FIELD ON CARD                         */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0115
*COMMA:                             /* PUT A COMMA AT THE NEXT BLANK
*                                      ON THE CARD BEING BUILT       */
*   KOL=KOL+1;                                                     0115
@RF00110 DS    0H                                                  0115
COMMA    LA    @10,1                                               0115
         A     @10,KOL                                             0115
         ST    @10,KOL                                             0115
*   IF CARD(KOL)^=' ' THEN          /* IF NOT BLANK,                 */
         LA    @04,CARD-1(@10)                                     0116
         CLI   0(@04),C' '                                         0116
         BNE   @RT00116                                            0116
*     GO TO COMMA;                  /* KEEP LOOKING                  */
*   CARD(KOL)=',';                                                 0118
*                                                                  0118
         LA    @04,CARD-1(@10)                                     0118
         MVI   0(@04),C','                                         0118
*   /*****************************************************************/
*   /*                                                               */
*   /* CALL OTHER SUBMIT ROUTINE TO PROCESS THIS CARD                */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0119
*PROCESS:                           /* NOW CALL THE CONTROL ROUTINE
*                                      TO PROCESS THE GENERATED CARD */
*   STMTPTR=ADDR(CARD);                                            0119
PROCESS  L     @10,@PC00001+4                                      0119
         LA    @04,CARD                                            0119
         ST    @04,STMTPTR(,@10)                                   0119
*   CALL IKJEFF06(PASS);            /* 06 WILL GET CARD SUBMITTED    */
*                                                                  0120
         LA    @10,PASS                                            0120
         ST    @10,@AL00001                                        0120
         L     @15,@CV00065                                        0120
         LA    @01,@AL00001                                        0120
         BALR  @14,@15                                             0120
*   /*****************************************************************/
*   /*                                                               */
*   /* SUBROUTINE TO BLANK AND INITIALIZE THE NEXT CARD              */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0121
*BLANK:                             /* BLANK OUT THE WORKING AREA  0121
*                                      WHERE GENERATED CARDS ARE   0121
*                                      BUILT - ADD A SLASH-SLASH - 0121
*                                      AND DECREMENT THE LOOP COUNTER*/
*   CARD=' ';                                                      0121
BLANK    MVI   CARD+1,C' '                                         0121
         MVC   CARD+2(78),CARD+1                                   0121
         MVI   CARD,C' '                                           0121
*   CARD(1:2)='//';                                                0122
*                                                                  0122
         MVC   CARD(2),@CC00279                                    0122
*   /*****************************************************************/
*   /*                                                               */
*   /* SUBROUTINE TO SKIP TO NEXT CARD IN LOOP                       */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0123
*SKIP:                              /* SKIP OVER A CONTINUATION CARD */
*   CT=CT-1;                                                       0123
SKIP     BCTR  CT,0                                                0123
*   GO TO COUNT;                    /* GO TO TOP OF LOOP TO GEN CARDS*/
         B     COUNT                                               0124
*                                                                  0125
*   /*****************************************************************/
*   /*                                                               */
*   /* ACNTIBAD INTERNAL PROCEDURE - ISSUES ERROR MESSAGE AND TURNS  */
*   /* SUBMIT QUIT SWITCH ON (TELLS IKJEFF06 NOT TO CONTINUE)        */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0125
*ACNTIBAD:                                                         0125
*   PROC;                                                          0125
ACNTIBAD STM   @14,@12,@SA00002                                    0125
*   QUIT='1'B;                      /* TURN SUBMIT QUIT SWITCH ON    */
         OI    QUIT(HTPTR),B'10000000'                             0126
*   MSGID='04B';                    /* 'ACCOUNT INFO WON'T FIT ON JOB
*                                      CARD' ERROR MESSAGE           */
         L     @10,@PC00001+16                                     0127
         L     @10,MSGPTR(,@10)                                    0127
         MVI   MSGID+3(@10),C' '                                   0127
         MVC   MSGID(3,@10),@CC00284                               0127
*   L1=LENGTH(CTCMDNM);             /* INSERT COMMAND NAME INTO MSG  */
         MVI   L1(@10),X'08'                                       0128
*   VAR1=ADDR(CTCMDNM);                                            0129
         L     @02,@PC00001+12                                     0129
         L     @02,CONLIST(,@02)                                   0129
         LA    @02,CTCMDNM(,@02)                                   0129
         STCM  @02,7,VAR1(@10)                                     0129
*   RFY                                                            0130
*     R1 RSTD;                                                     0130
*   R1=ADDR(MSGTABLE);              /* POINT TO IKJEFF02'S PARAM LIST*/
         LR    R1,@10                                              0131
*   CALL IKJEFF02;                  /* CALL MESSAGE ISSUER MODULE    */
         L     @15,MSGRTN(,@10)                                    0132
         BALR  @14,@15                                             0132
*   RFY                                                            0133
*     R1 UNRSTD;                                                   0133
*   END ACNTIBAD;                                                  0134
@EL00002 DS    0H                                                  0134
@EF00002 DS    0H                                                  0134
@ER00002 LM    @14,@12,@SA00002                                    0134
         BR    @14                                                 0134
*                                                                  0135
*/*IKJEFF08:    CHART                                                */
*/*HEADER                                                          0135
*/*IKJEFF08                    GENJOB ROUTINE                        */
*/*E ENTER FROM CALLER                                               */
*/*P INCREMENT THE 'IN GENJOB' CTR                                   */
*/*P HOLD ASIDE THE ORIGINAL INPUT CARD                              */
*/*P SET CTR TO SEVEN                                                */
*/*N THIS CTR COUNTS JCL CARDS--6 GENERATED,1 ORIGINAL CARD          */
*/*BLANK: P INITIALIZE FIRST AND SECOND COLS OF NEWLY FORMED CARD WITH
*/* //                                                               */
*/*P SUBTRACT ONE FROM CTR                                           */
*/*COUNT: D (YES,,NO,%H2) IS THE CTR 0                               */
*/*P REPROCESS THE ORIGINAL CARD                                     */
*/*S IKJEFF06: CALL IKJEFF06 CONTROL RTN                             */
*/*P DECREMENT THE 'IN GENJOB' CTR                                   */
*/*R END IKJEFF08-RETURN TO CALLER                                   */
*/*%H2: P IF THE CTR IS 6 PLACE USERID, VERB JOB, AND ACCOUNT INFO 0135
*/*ON CARD                                                           */
*/*P IF THE CTR IS 3 PLACE USERID AS PGMR NAME                       */
*/*D (YES,,NO,%D4) IS THE CTR 2                                      */
*/*D (NO,,YES,BLANK) IS NONOTIFY SPECIFIED                           */
*/*N WHEN NONOTIFY IS SPECIFIED, ONLY THREE NEW JCL CARDS ARE GENERATED
*/*                                                                  */
*/*P (,%D4) PLACE NOTIFY ON THE CARD                                 */
*/*%D4: D (YES,,NO,COMMA) IS THE CTR 1                               */
*/*P PLACE MSGLEVEL=1 (1,1) ON LAST CARD                             */
*/*PROCESS: S (,BLANK) IKJEFF06: CALL IKJEFF06 CONTROL RTN           */
*/*COMMA: P (,PROCESS) FIND LAST NONBLANK CHAR & PLACE COMMA FOR CONT
*/*                                                                  */
*/*IKJEFF08:  END                                                    */
*                                                                  0135
*   END IKJEFF08                                                   0135
*                                                                  0135
*/* THE FOLLOWING INCLUDE STATEMENTS WERE FOUND IN THIS PROGRAM.     */
*/*%INCLUDE SYSLIB  (IKJEFFCT)                                       */
*/*%INCLUDE SYSLIB  (IKJEFFHT)                                       */
*/*%INCLUDE SYSLIB  (IKJEFFMT)                                       */
*                                                                  0135
*       ;                                                          0135
         B     @EL00001                                            0135
@DATA    DS    0H
@CH00106 DC    H'1'
@CH00110 DC    H'2'
@CH00061 DC    H'3'
@CH00094 DC    H'4'
@CH00259 DC    H'5'
@CH00122 DC    H'6'
@CH00060 DC    H'17'
@SM00287 MVC   CARD+16(0),HTACCNTI(@04)
@SM00289 MVC   CARD+3(0),ACNTINST(ACNTIPTR)
@DATD    DSECT
         DS    0F
@SA00001 DS    18F
@PC00001 DS    5F
@SA00002 DS    15F
@AL00001 DS    1A
IKJEFF08 CSECT
         DS    0F
@CF00069 DC    F'16'
@CF00261 DC    F'23'
@CF00200 DC    F'54'
@CF00067 DC    F'70'
@CH00067 EQU   @CF00067+2
@DATD    DSECT
         DS    0D
KOL      DS    A
PASS     DS    F
TEMPHOLD DS    A
CARD     DS    CL80
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
IKJEFF08 CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
@CV00065 DC    V(IKJEFF06)
         DS    0D
@CC00279 DC    C'//'
@CC00257 DC    C'JOB'
@CC00284 DC    C'04B'
@CC00267 DC    C'NOTIFY='
@CC00270 DC    C'MSGLEVEL=(1,1)'
@CC00263 DC    C'GENERATED JOB STATEMENT'
PATCH    DS    CL51
         ORG   PATCH
PTCHINIT DC    17CL3'ZAP'
         ORG   PATCH+51
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
HTPTR    EQU   @03
ACNTIPTR EQU   @04
CT       EQU   @02
HOLD     EQU   @05
R1       EQU   @01
ACNTINST EQU   0
IKJEFF02 EQU   0
CONTAB   EQU   0
CTCMDNM  EQU   CONTAB+76
HISTORY  EQU   0
WHATMOD  EQU   HISTORY+12
INGEN    EQU   WHATMOD+2
JCLSWITS EQU   HISTORY+16
PRIORJCL EQU   JCLSWITS
PVERB    EQU   PRIORJCL
PDTYPE   EQU   PRIORJCL+2
PMISC    EQU   PRIORJCL+3
CURRJCL  EQU   JCLSWITS+4
CVERB    EQU   CURRJCL
CDTYPE   EQU   CURRJCL+2
CMISC    EQU   CURRJCL+3
STATICSW EQU   HISTORY+24
GENL     EQU   STATICSW
QUIT     EQU   GENL
NONOTIFY EQU   GENL
TAKEXITS EQU   STATICSW+1
CODEFLD  EQU   STATICSW+3
DLMONJCL EQU   HISTORY+32
HTSWITCH EQU   HISTORY+34
HTACCNTP EQU   HISTORY+40
HTACCNTL EQU   HISTORY+44
HTACNTC1 EQU   HISTORY+46
HTACNTC2 EQU   HISTORY+48
HTACCNTI EQU   0
MSGTABLE EQU   0
TMCTPTR  EQU   MSGTABLE+4
ECBPTR   EQU   MSGTABLE+8
@NM00011 EQU   MSGTABLE+12
SW       EQU   MSGTABLE+20
RETMSG   EQU   MSGTABLE+21
SW2      EQU   MSGTABLE+24
MSGID    EQU   MSGTABLE+40
MTINSRTS EQU   MSGTABLE+44
L1       EQU   MTINSRTS
VAR1     EQU   MTINSRTS+1
L2       EQU   MTINSRTS+4
L3       EQU   MTINSRTS+8
L4       EQU   MTINSRTS+12
MSGRTN   EQU   MSGTABLE+60
RET      EQU   0
MSGECB   EQU   0
MSGTMCT  EQU   0
HIST     EQU   0
STMTPTR  EQU   0
USERID   EQU   0
PCONTAB  EQU   0
MSGPTR   EQU   0
CONLIST  EQU   PCONTAB
         AGO   .@UNREFD                START UNREFERENCED COMPONENTS
RETCHAR  EQU   RET+2
RETSIZE  EQU   RET
VAR4     EQU   MTINSRTS+13
HIGHL4   EQU   L4
VAR3     EQU   MTINSRTS+9
HIGHL3   EQU   L3
VAR2     EQU   MTINSRTS+5
HIGHL2   EQU   L2
HIGHL1   EQU   L1
@NM00015 EQU   MSGTABLE+36
@NM00014 EQU   MSGTABLE+32
MTOLDPTR EQU   MSGTABLE+28
@NM00013 EQU   MSGTABLE+25
@NM00012 EQU   SW2
MTDOMSW  EQU   SW2
MT2OLDSW EQU   SW2
MTNHEXSW EQU   SW
MTWTPSW  EQU   SW
MTJOBISW EQU   SW
MTKEY1SW EQU   SW
MTHEXSW  EQU   SW
MTWTOSW  EQU   SW
MTPUTLSW EQU   SW
MTNOIDSW EQU   SW
MSGCSECT EQU   MSGTABLE+16
MTHIGH   EQU   @NM00011
MTCPPL   EQU   TMCTPTR
LISTPTR  EQU   MSGTABLE
@NM00010 EQU   HISTORY+50
@NM00009 EQU   HISTORY+36
@NM00008 EQU   HISTORY+35
@NM00007 EQU   HTSWITCH
HTDLMSW  EQU   HTSWITCH
HTDLM    EQU   DLMONJCL
@NM00006 EQU   HISTORY+28
HTCODE   EQU   CODEFLD
OPOFF    EQU   STATICSW+2
@NM00005 EQU   TAKEXITS
COMNTX   EQU   TAKEXITS
JESX     EQU   TAKEXITS
NULLX    EQU   TAKEXITS
CMDX     EQU   TAKEXITS
DDX      EQU   TAKEXITS
EXECX    EQU   TAKEXITS
JOBX     EQU   TAKEXITS
FIRST    EQU   GENL
FLUSH    EQU   GENL
CDLMFND  EQU   CMISC
CNOTHING EQU   CMISC
CCOMCON  EQU   CMISC
CVERBCOP EQU   CMISC
CNAME    EQU   CMISC
CCONERR  EQU   CMISC
COPCONEX EQU   CMISC
CCONEX   EQU   CMISC
CDDDATA  EQU   CDTYPE
CDDAST   EQU   CDTYPE
@NM00004 EQU   CVERB+1
@NM00003 EQU   CVERB+1
CJES     EQU   CVERB+1
CCOMMENT EQU   CVERB
CCOMMAND EQU   CVERB
CDD      EQU   CVERB
CEXEC    EQU   CVERB
CJOB     EQU   CVERB
CNULL    EQU   CVERB
CDATA    EQU   CVERB
CDELIM   EQU   CVERB
PDLMFND  EQU   PMISC
PNOTHING EQU   PMISC
PCOMCON  EQU   PMISC
PVERBCOP EQU   PMISC
PNAME    EQU   PMISC
PCONERR  EQU   PMISC
POPCONEX EQU   PMISC
PCONEX   EQU   PMISC
PDDDATA  EQU   PDTYPE
PDDAST   EQU   PDTYPE
@NM00002 EQU   PVERB+1
@NM00001 EQU   PVERB+1
PJES     EQU   PVERB+1
PCOMMENT EQU   PVERB
PCOMMAND EQU   PVERB
PDD      EQU   PVERB
PEXEC    EQU   PVERB
PJOB     EQU   PVERB
PNULL    EQU   PVERB
PDATA    EQU   PVERB
PDELIM   EQU   PVERB
INOINIT  EQU   WHATMOD+3
INCOMPIN EQU   WHATMOD+3
INMSG    EQU   WHATMOD+3
INDAIRIN EQU   WHATMOD+3
INWRMGR  EQU   WHATMOD+3
INEXIT   EQU   WHATMOD+3
INIDENT  EQU   WHATMOD+3
INREAD   EQU   WHATMOD+3
INPROMPT EQU   WHATMOD+1
INCONTRL EQU   WHATMOD
SUBTAB   EQU   HISTORY
CTACBPT  EQU   CONTAB+72
CTRPLPT  EQU   CONTAB+68
INITSAVE EQU   CONTAB+64
COMECBPT EQU   CONTAB+60
DDPTR    EQU   CONTAB+56
EXITAD   EQU   CONTAB+52
EXWORD   EQU   CONTAB+48
TMCTPT   EQU   CONTAB+44
USERIDPT EQU   CONTAB+40
MSGLISPT EQU   CONTAB+36
JOBNAMPT EQU   CONTAB+32
CTNDSNPT EQU   CONTAB+28
HISTPT   EQU   CONTAB+24
CLOSERPT EQU   CONTAB+20
STMTPT   EQU   CONTAB+16
CONTABPT EQU   CONTAB+12
TABID    EQU   CONTAB
.@UNREFD ANOP                          END UNREFERENCED COMPONENTS
@RT00069 EQU   SKIP
@RT00085 EQU   SKIP
@RT00104 EQU   SKIP
@RT00116 EQU   COMMA
@PB00002 EQU   @EL00001
@ENDDATA EQU   *
         END   IKJEFF08,(C'PL/S-II',0502,73293)
