         TITLE '**********  ICKBM01:  BUILD PACK MAP  ******************
               *********'
        MACRO
        GETMAIN &R,&LV=
        L     REG15,0(REG1)           GDTTBL ADDRESS
        L     REG15,GDTPRL(REG15)     PROL ROUTINE ADDRESS
        CNOP  2,4                     BOUNDARY ALIGNMENT
        LA    REG14,*+14              RETURN ADDRESS
        BALR  REG1,REG15              LINKAGE TO PROL ROUTINE
        DC    A(MODID)                MODULE ID ADDRESS
        DC    A(@SIZDATD)             AUTOMATIC STORAGE SIZE ADDRESS
        MEND
ICKBM01  CSECT ,                                                   0002
@MAINENT DS    0H                                                  0002
         USING *,@15                                               0002
         B     @PROLOG                                             0002
         DC    AL1(16)                                             0002
         DC    C'ICKBM01   78.192'                                 0002
         DROP  @15
@PROLOG  STM   @14,@12,12(@13)                                     0002
         BALR  @12,0                                               0002
@PSTART  DS    0H                                                  0002
         USING @PSTART,@12                                         0002
         L     @00,@SIZDATD                                        0002
         GETMAIN  R,LV=(0)
         LR    @11,@01                                             0002
         USING @DATD,@11                                           0002
         ST    @13,@SA00001+4                                      0002
         LM    @00,@01,20(@13)                                     0002
         ST    @11,8(,@13)                                         0002
         LR    @13,@11                                             0002
         XC    @ZTEMPS(@ZLEN),@ZTEMPS
         MVC   @PC00001(36),0(@01)                                 0002
*                                                                  0177
         EJECT
*                                                                  0178
*/*****  B E G I N    E X E C U T I O N  *****************************/
*                                                                  0178
*    IF GDTDBG = NULLPTR                                           0178
*      THEN;                                                       0178
         L     @10,@PC00001                                        0178
         L     @10,GDTDBG(,@10)                                    0178
         LTR   @10,@10                                             0178
         BZ    @RT00178                                            0178
*      ELSE                                                        0180
*        CALL ICKDB010(GDTTBL                                      0180
*         ,'BM00');                                                0180
*                                                                  0180
*                                                                  0180
         L     @10,@PC00001                                        0180
         ST    @10,@AL00001                                        0180
         LA    @15,@CC00501                                        0180
         ST    @15,@AL00001+4                                      0180
         MVI   @AL00001+4,X'80'                                    0180
         L     @15,GDTDBG(,@10)                                    0180
         LA    @01,@AL00001                                        0180
         BALR  @14,@15                                             0180
*    CONDCODE = SUCCESS;                                           0181
*                                                                  0181
@RT00178 L     @10,@PC00001+32                                     0181
         SLR   @03,@03                                             0181
         ST    @03,CONDCODE(,@10)                                  0181
*/*  INITIALIZE UPRINT ARGUMENT LIST                                 */
*    PRTHDR = 'DARGLIST';                                          0182
         MVC   PRTHDR(8),@CC00520                                  0182
*    PRTARGS = ''B;                                                0183
         XC    PRTARGS(20),PRTARGS                                 0183
*    DDSTRU = ADDR(PRTARGS);                                       0184
         LA    @10,PRTARGS                                         0184
         ST    @10,DDSTRU                                          0184
*    DARGSMOD = EFMSGS;                                            0185
*                                                                  0185
         MVC   DARGSMOD(3,@10),EFMSGS                              0185
*/*  OBTAIN SPACE FOR MAP-DATUM ENTRY (UGPOOL)                       */
*    CALL ICKSAGP0(GDTTBL                                          0186
*          ,ENTRYSZ                                                0186
*          ,ENTRYPTR                                               0186
*          ,MAPID                                                  0186
*          ,SETZERO);                                              0186
*                                                                  0186
         MVC   @AL00001+4(16),@AL00186                             0186
         L     @10,@PC00001                                        0186
         ST    @10,@AL00001                                        0186
         LA    @03,ENTRYPTR                                        0186
         ST    @03,@AL00001+8                                      0186
         L     @15,GDTGPL(,@10)                                    0186
         LA    @01,@AL00001                                        0186
         BALR  @14,@15                                             0186
*/*  IF NO SPACE AVAILABLE                                           */
*    RESPECIFY RTNREG RSTD;                                        0187
*    TESTRC = RTNREG;                                              0188
         LR    TESTRC,RTNREG                                       0188
*    RESPECIFY RTNREG UNRSTD;                                      0189
*    IF TESTRC ^= 0                                                0190
*                                                                  0190
*                                                                  0190
*/*    THEN                                                          */
*      THEN DO;                                                    0190
*                                                                  0190
*                                                                  0190
         LTR   TESTRC,TESTRC                                       0190
         BZ    @RF00190                                            0190
*/*      PRINT MESSAGE: NO STORAGE AVAILABLE FOR MAP-DATUM (UPRINT)  */
*        DARGSENT = MSGNOSTG;                                      0192
         L     @10,DDSTRU                                          0192
         MVI   DARGSENT(@10),X'12'                                 0192
*        CALL ICKTPPR0(GDTTBL                                      0193
*              ,PRTFILE                                            0193
*              ,DDSTRU);                                           0193
*                                                                  0193
         L     @10,@PC00001                                        0193
         ST    @10,@AL00001                                        0193
         LA    @15,@CF00102                                        0193
         ST    @15,@AL00001+4                                      0193
         LA    @15,DDSTRU                                          0193
         ST    @15,@AL00001+8                                      0193
         MVI   @AL00001+8,X'80'                                    0193
         L     @15,GDTPRT(,@10)                                    0193
         LA    @01,@AL00001                                        0193
         BALR  @14,@15                                             0193
*/*      SET ERROR CODE (CONDCODE=1)                                 */
*        CONDCODE = NOSPACE;                                       0194
*                                                                  0194
         L     @10,@PC00001+32                                     0194
         MVC   CONDCODE(4,@10),@CF00173                            0194
*/*      END-THEN                                                    */
*        END;                                                      0195
*                                                                  0195
*/*    ELSE                                                          */
*      ELSE                                                        0196
*        SPACEOK: DO;                                              0196
*                                                                  0196
*                                                                  0196
         B     @RC00190                                            0196
@RF00190 DS    0H                                                  0196
SPACEOK  DS    0H                                                  0197
*/*      MOVE SUPPLIED INFORMATION TO THE MAP-DATUM ENTRY            */
*        MAPTRK = TRACK;                                           0197
         L     @10,ENTRYPTR                                        0197
         L     @15,@PC00001+8                                      0197
         MVC   MAPTRK(4,@10),TRACK(@15)                            0197
*        MAPLINK = LINK;                                           0198
         L     @15,@PC00001+12                                     0198
         MVC   MAPLINK(4,@10),LINK(@15)                            0198
*        IF TRKTYPE = ALTRNATE                                     0199
*          THEN DO;    MAPFALT = ON; END;                          0199
         L     @15,@PC00001+16                                     0199
         TM    TRKTYPE(@15),B'10000000'                            0199
         BNZ   @RF00199                                            0199
         OI    MAPFALT(@10),B'10000000'                            0201
*        IF DFTFLAG = ON                                           0203
*          THEN DO;    MAPFDEF = ON; END;                          0203
@RF00199 L     @10,@PC00001+20                                     0203
         TM    DFTFLAG(@10),B'10000000'                            0203
         BNO   @RF00203                                            0203
         L     @10,ENTRYPTR                                        0205
         OI    MAPFDEF(@10),B'01000000'                            0205
*        IF CHKFLAG = ON                                           0207
*          THEN DO;    MAPFCHK = ON; END;                          0207
@RF00203 L     @10,@PC00001+24                                     0207
         TM    CHKFLAG(@10),B'10000000'                            0207
         BNO   @RF00207                                            0207
         L     @10,ENTRYPTR                                        0209
         OI    MAPFCHK(@10),B'00100000'                            0209
*        IF UNRFLAG = ON                                           0211
*          THEN DO;    MAPFUNR = ON; END;                          0211
*                                                                  0211
@RF00207 L     @10,@PC00001+28                                     0211
         TM    UNRFLAG(@10),B'10000000'                            0211
         BNO   @RF00211                                            0211
         L     @10,ENTRYPTR                                        0213
         OI    MAPFUNR(@10),B'00010000'                            0213
*/*      IF THIS IS FIRST ENTRY FOR CURRENT VOLIB (UDEVINFO)         */
*        CALL ICKDVIN0(GDTTBL                                      0215
*                ,VOLIB                                            0215
*                ,VOLAMAPF                                         0215
*                ,POOLID                                           0215
*                ,INFOPTR                                          0215
*                ,INFOLEN                                          0215
*                ,RETCODE);                                        0215
@RF00211 L     @10,@PC00001                                        0215
         ST    @10,@AL00001                                        0215
         L     @15,@PC00001+4                                      0215
         ST    @15,@AL00001+4                                      0215
         LA    @15,@CF00263                                        0215
         ST    @15,@AL00001+8                                      0215
         LA    @15,POOLID                                          0215
         ST    @15,@AL00001+12                                     0215
         LA    @15,INFOPTR                                         0215
         ST    @15,@AL00001+16                                     0215
         LA    @15,INFOLEN                                         0215
         ST    @15,@AL00001+20                                     0215
         LA    @15,RETCODE                                         0215
         ST    @15,@AL00001+24                                     0215
         L     @15,GDTDIN(,@10)                                    0215
         LA    @01,@AL00001                                        0215
         BALR  @14,@15                                             0215
*        IF FIRSTPTR = NULLPTR                                     0216
*                                                                  0216
*/*        THEN LINK FROM ANCHOR (UDEVINFO)                          */
*          THEN DO;                                                0216
*                                                                  0216
         L     @10,INFOPTR                                         0216
         L     @10,FIRSTPTR(,@10)                                  0216
         LTR   @10,@10                                             0216
         BNZ   @RF00216                                            0216
*            INFOPTR = ADDR(ENTRYPTR);                             0218
         LA    @10,ENTRYPTR                                        0218
         ST    @10,INFOPTR                                         0218
*            CALL ICKDVIN0(GDTTBL                                  0219
*                    ,VOLIB                                        0219
*                    ,VOLSMAPF                                     0219
*                    ,POOLID                                       0219
*                    ,INFOPTR                                      0219
*                    ,INFOLEN                                      0219
*                    ,RETCODE);                                    0219
         L     @10,@PC00001                                        0219
         ST    @10,@AL00001                                        0219
         L     @15,@PC00001+4                                      0219
         ST    @15,@AL00001+4                                      0219
         LA    @15,@CF00330                                        0219
         ST    @15,@AL00001+8                                      0219
         LA    @15,POOLID                                          0219
         ST    @15,@AL00001+12                                     0219
         LA    @15,INFOPTR                                         0219
         ST    @15,@AL00001+16                                     0219
         LA    @15,INFOLEN                                         0219
         ST    @15,@AL00001+20                                     0219
         LA    @15,RETCODE                                         0219
         ST    @15,@AL00001+24                                     0219
         L     @15,GDTDIN(,@10)                                    0219
         LA    @01,@AL00001                                        0219
         BALR  @14,@15                                             0219
*            END;                                                  0220
*                                                                  0220
*/*        ELSE LINK FROM END OF CHAIN (UDEVINFO)                    */
*          ELSE DO;                                                0221
*                                                                  0221
         B     @RC00216                                            0221
@RF00216 DS    0H                                                  0222
*            CALL ICKDVIN0(GDTTBL                                  0222
*                    ,VOLIB                                        0222
*                    ,VOLAMAPL                                     0222
*                    ,POOLID                                       0222
*                    ,INFOPTR                                      0222
*                    ,INFOLEN                                      0222
*                    ,RETCODE);                                    0222
         L     @10,@PC00001                                        0222
         ST    @10,@AL00001                                        0222
         L     @15,@PC00001+4                                      0222
         ST    @15,@AL00001+4                                      0222
         LA    @15,@CF00127                                        0222
         ST    @15,@AL00001+8                                      0222
         LA    @15,POOLID                                          0222
         ST    @15,@AL00001+12                                     0222
         LA    @15,INFOPTR                                         0222
         ST    @15,@AL00001+16                                     0222
         LA    @15,INFOLEN                                         0222
         ST    @15,@AL00001+20                                     0222
         LA    @15,RETCODE                                         0222
         ST    @15,@AL00001+24                                     0222
         L     @15,GDTDIN(,@10)                                    0222
         LA    @01,@AL00001                                        0222
         BALR  @14,@15                                             0222
*            LASTPTR->MAPNEXT = ENTRYPTR;                          0223
         L     @10,INFOPTR                                         0223
         L     @10,LASTPTR(,@10)                                   0223
         MVC   MAPNEXT(4,@10),ENTRYPTR                             0223
*/*          END-ELSE                                                */
*            END;                                                  0224
*                                                                  0224
*/*        ESTABLISH MAP-DATUM ENTRY AS CURRENT LAST ENTRY           */
*                                                                  0225
*          INFOPTR = ADDR(ENTRYPTR);                               0225
@RC00216 LA    @10,ENTRYPTR                                        0225
         ST    @10,INFOPTR                                         0225
*          CALL ICKDVIN0(GDTTBL                                    0226
*                  ,VOLIB                                          0226
*                  ,VOLSMAPL                                       0226
*                  ,POOLID                                         0226
*                  ,INFOPTR                                        0226
*                  ,INFOLEN                                        0226
*                  ,RETCODE);                                      0226
*                                                                  0226
         L     @10,@PC00001                                        0226
         ST    @10,@AL00001                                        0226
         L     @15,@PC00001+4                                      0226
         ST    @15,@AL00001+4                                      0226
         LA    @15,@CF00333                                        0226
         ST    @15,@AL00001+8                                      0226
         LA    @15,POOLID                                          0226
         ST    @15,@AL00001+12                                     0226
         LA    @15,INFOPTR                                         0226
         ST    @15,@AL00001+16                                     0226
         LA    @15,INFOLEN                                         0226
         ST    @15,@AL00001+20                                     0226
         LA    @15,RETCODE                                         0226
         ST    @15,@AL00001+24                                     0226
         L     @15,GDTDIN(,@10)                                    0226
         LA    @01,@AL00001                                        0226
         BALR  @14,@15                                             0226
*/*      END-ELSE                                                    */
*        END SPACEOK;                                              0227
*                                                                  0227
*/*  FREE ALL TEMPORARY POOL AREAS                                   */
*    CALL ICKSAFP0(GDTTBL                                          0228
*          ,POOLID                                                 0228
*          ,ALL);                                                  0228
*                                                                  0228
@RC00190 MVC   @AL00001+4(8),@AL00228                              0228
         L     @10,@PC00001                                        0228
         ST    @10,@AL00001                                        0228
         L     @15,GDTFPL(,@10)                                    0228
         LA    @01,@AL00001                                        0228
         BALR  @14,@15                                             0228
*/*  END-PROCEDURE BUILD_PACK_MAP                                    */
*                                                                  0229
*    IF GDTDBG = NULLPTR                                           0229
*      THEN;                                                       0229
         L     @10,@PC00001                                        0229
         L     @10,GDTDBG(,@10)                                    0229
         LTR   @10,@10                                             0229
         BZ    @RT00229                                            0229
*      ELSE                                                        0231
*        CALL ICKDB010(GDTTBL                                      0231
*         ,'BM99');                                                0231
         L     @10,@PC00001                                        0231
         ST    @10,@AL00001                                        0231
         LA    @15,@CC00525                                        0231
         ST    @15,@AL00001+4                                      0231
         MVI   @AL00001+4,X'80'                                    0231
         L     @15,GDTDBG(,@10)                                    0231
         LA    @01,@AL00001                                        0231
         BALR  @14,@15                                             0231
*    CALL ICKSAEP0(GDTTBL,MODID);                                  0232
*                                                                  0232
*                                                                  0232
*                                                                  0232
@RT00229 L     @10,@PC00001                                        0232
         ST    @10,@AL00001                                        0232
         LA    @15,MODID                                           0232
         ST    @15,@AL00001+4                                      0232
         MVI   @AL00001+4,X'80'                                    0232
         L     @15,GDTEPL(,@10)                                    0232
         LA    @01,@AL00001                                        0232
         BALR  @14,@15                                             0232
*    END ICKBM01                                                   0233
*/* THE FOLLOWING INCLUDE STATEMENTS WERE FOUND IN THIS PROGRAM.      *
*/*%INCLUDE SYSLIB  (DMSDF01 )                                        *
*/*%INCLUDE SYSLIB  (DMSDF00 )                                        *
*/*@INCLUDE SYSLIB  (DMSDF02 )                                        *
*;                                                                 0233
@DATA    DS    0H
         DS    0F
@AL00186 DC    A(ENTRYSZ)              LIST WITH   4 ARGUMENT(S)
         DS    F
         DC    A(MAPID)
         DC    AL1(X'80')
         DC    AL3(@CC00153)
@AL00228 DC    A(POOLID)               LIST WITH   2 ARGUMENT(S)
         DC    AL1(X'80')
         DC    AL3(@CC00145)
@DATD    DSECT
         DS    0F
@SA00001 DS    18F
@PC00001 DS    9F
@AL00001 DS    7A
@ZTEMPS  DS    C
@ZTEMPND EQU   *
@ZLEN    EQU   @ZTEMPND-@ZTEMPS
ICKBM01  CSECT
         DS    0F
@CF00102 DC    F'0'
@CF00173 DC    F'1'
@CF00263 DC    F'5'
@CF00127 DC    F'6'
@CF00330 DC    F'105'
@CF00333 DC    F'106'
@DATD    DSECT
         DS    0D
LISTSCAN DS    A
IOCSPTR  DS    A
OPNPTR   DS    A
DDSTRU   DS    A
FSADDR   DS    A
DMPINDEX DS    A
ENTRYPTR DS    A
INFOPTR  DS    A
INFOLEN  DS    F
RETCODE  DS    F
LISTPTR  DS    A
SETRC    DS    H
LISTLN   DS    FL1
         DS    CL1
PRTLIST  DS    CL28
         ORG   PRTLIST
PRTHDR   DS    CL8
PRTARGS  DS    CL20
         ORG   PRTLIST+28
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
ICKBM01  CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
         DS    0D
ENTRYSZ  DC    AL4(16)
@CC00520 DC    C'DARGLIST'
@CC00153 DC    C'ZERO'
@CC00501 DC    C'BM00'
@CC00525 DC    C'BM99'
@CC00145 DC    C'ALL'
MODID    DC    CL4'BM01'
MAPID    DC    CL4'PP00'
POOLID   DC    CL4'BM00'
EFMSGS   DC    CL3'EF0'
PTCHBM01 DS    CL256
         ORG   PTCHBM01
@NM00018 DC    256X'00'
         ORG   PTCHBM01+256
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
TESTRC   EQU   @02
REG12    EQU   @12
RTNREG   EQU   @15
REG0     EQU   @00
REG1     EQU   @01
REG10    EQU   @10
REG11    EQU   @11
REG13    EQU   @13
REG14    EQU   @14
REG15    EQU   @15
REG2     EQU   @02
REG3     EQU   @03
REG4     EQU   @04
REG5     EQU   @05
REG6     EQU   @06
REG7     EQU   @07
REG8     EQU   @08
REG9     EQU   @09
ICKSAEP0 EQU   0
ICKSAGP0 EQU   0
ICKSAFP0 EQU   0
TRACE1   EQU   0
OLDERID1 EQU   TRACE1
TRACE2   EQU   0
STAEPARM EQU   0
STAEPFX  EQU   STAEPARM
IOCSTR   EQU   0
IOCDSO   EQU   IOCSTR+13
IOCRFM   EQU   IOCSTR+14
IOCMAC   EQU   IOCSTR+15
IOCMSG   EQU   IOCSTR+16
OPNAGL   EQU   0
OPNOPT   EQU   OPNAGL
OPNRFM   EQU   OPNAGL+1
OPNTYP   EQU   OPNAGL+2
OPNMOD   EQU   OPNAGL+3
UVOLLIST EQU   0
UVOLENT  EQU   UVOLLIST+2
ICKDVIN0 EQU   0
ICKTPPR0 EQU   0
DARGLIST EQU   0
DARGSTID EQU   DARGLIST+8
DARGSMOD EQU   DARGSTID
DARGSENT EQU   DARGSTID+3
DARGARY  EQU   DARGLIST+20
DARGINS  EQU   DARGARY
DARGINL  EQU   DARGARY+2
FMTLIST  EQU   0
FMTFLGS  EQU   FMTLIST
FMTSPF   EQU   FMTLIST+2
FMTRFNO  EQU   FMTSPF
FMTILEN  EQU   FMTRFNO
FMTIOFF  EQU   FMTLIST+4
FMTTRBC  EQU   FMTIOFF
FMTSTO   EQU   FMTTRBC
FMTOCOL  EQU   FMTLIST+6
FMTCNVF  EQU   FMTLIST+10
ICKDB010 EQU   0
DMPITM   EQU   0
DMPARY   EQU   0
MAPDATA  EQU   0
MAPTRK   EQU   MAPDATA
MAPLINK  EQU   MAPDATA+4
MAPFLGS  EQU   MAPDATA+8
MAPFALT  EQU   MAPFLGS
MAPFDEF  EQU   MAPFLGS
MAPFCHK  EQU   MAPFLGS
MAPFUNR  EQU   MAPFLGS
MAPNEXT  EQU   MAPDATA+12
FIRSTPTR EQU   0
LASTPTR  EQU   0
DMPTRM   EQU   0
ICKDVCL0 EQU   0
ICKDVON0 EQU   0
ICKDVOP0 EQU   0
ICKIOCL0 EQU   0
ICKIOGT0 EQU   0
ICKIOIT0 EQU   0
ICKIOOP0 EQU   0
ICKIOPT0 EQU   0
ICKIOTM0 EQU   0
ICKSACL0 EQU   0
ICKSADE0 EQU   0
ICKSAFS0 EQU   0
ICKSAGS0 EQU   0
ICKSALD0 EQU   0
ICKSAPR0 EQU   0
ICKSASC0 EQU   0
ICKSASN0 EQU   0
ICKSAST0 EQU   0
ICKSATI0 EQU   0
ICKSAVC0 EQU   0
ICKSAWO0 EQU   0
ICKTPEA0 EQU   0
ICKTPES0 EQU   0
ICKTPRE0 EQU   0
ICKTPRS0 EQU   0
LISTTEST EQU   0
NEWERID1 EQU   5
NEWERID2 EQU   5
GDTTBL   EQU   0
GDTTR1   EQU   GDTTBL+8
GDTTR2   EQU   GDTTBL+12
GDTDIN   EQU   GDTTBL+44
GDTDOP   EQU   GDTTBL+48
GDTDBG   EQU   GDTTBL+52
GDTDVO   EQU   GDTTBL+56
GDTPRT   EQU   GDTTBL+60
GDTESS   EQU   GDTTBL+64
GDTESA   EQU   GDTTBL+68
GDTRST   EQU   GDTTBL+72
GDTRES   EQU   GDTTBL+76
GDTCAL   EQU   GDTTBL+80
GDTGSP   EQU   GDTTBL+84
GDTFSP   EQU   GDTTBL+88
GDTGPL   EQU   GDTTBL+92
GDTFPL   EQU   GDTTBL+96
GDTLOD   EQU   GDTTBL+100
GDTDEL   EQU   GDTTBL+104
GDTPRL   EQU   GDTTBL+108
GDTEPL   EQU   GDTTBL+112
GDTTIM   EQU   GDTTBL+116
GDTIIO   EQU   GDTTBL+120
GDTTIO   EQU   GDTTBL+124
GDTOPN   EQU   GDTTBL+136
GDTCLS   EQU   GDTTBL+140
GDTGET   EQU   GDTTBL+144
GDTPUT   EQU   GDTTBL+148
GDTSNP   EQU   GDTTBL+160
GDTWTO   EQU   GDTTBL+168
GDTSCR   EQU   GDTTBL+172
GDTVCK   EQU   GDTTBL+176
GDTDVC   EQU   GDTTBL+180
GDTSTE   EQU   GDTTBL+188
VOLIB    EQU   0
TRACK    EQU   0
LINK     EQU   0
TRKTYPE  EQU   0
DFTFLAG  EQU   0
CHKFLAG  EQU   0
UNRFLAG  EQU   0
CONDCODE EQU   0
         AGO   .@UNREFD                START UNREFERENCED COMPONENTS
GDTCVR   EQU   GDTTBL+184
GDTSPR   EQU   GDTTBL+164
GDTABH   EQU   GDTTBL+156
GDTABT   EQU   GDTTBL+152
GDTTOH   EQU   GDTTBL+132
GDTRIP   EQU   GDTTBL+128
GDTDVH   EQU   GDTTBL+40
GDTIOH   EQU   GDTTBL+36
GDTSAH   EQU   GDTTBL+32
GDTTPH   EQU   GDTTBL+28
GDTRIH   EQU   GDTTBL+24
GDTSTH   EQU   GDTTBL+20
GDTDBH   EQU   GDTTBL+16
GDTPRM   EQU   GDTTBL+4
GDTHDR   EQU   GDTTBL
@NM00017 EQU   DMPARY+15
DMPARYTP EQU   DMPARY+14
DMPARYEX EQU   DMPARY+12
DMPARYIC EQU   DMPARY+10
DMPARYSZ EQU   DMPARY+8
DMPARYNM EQU   DMPARY
@NM00016 EQU   DMPITM+15
DMPITMTP EQU   DMPITM+14
DMPITMLN EQU   DMPITM+12
DMPITMPT EQU   DMPITM+8
DMPITMNM EQU   DMPITM
@NM00015 EQU   FMTCNVF+1
FMTBS    EQU   FMTCNVF+1
FMTSS    EQU   FMTCNVF+1
FMTAL    EQU   FMTCNVF+1
FMTZS    EQU   FMTCNVF+1
@NM00014 EQU   FMTCNVF
FMTPU    EQU   FMTCNVF
FMTBD    EQU   FMTCNVF
FMTBHD   EQU   FMTCNVF
FMTBHA   EQU   FMTCNVF
FMTBH    EQU   FMTCNVF
FMTOLEN  EQU   FMTLIST+8
FMTRIO   EQU   FMTOCOL
FMTSPT   EQU   FMTSTO
FMTSTL   EQU   FMTILEN
@NM00013 EQU   FMTFLGS+1
FMTHDF   EQU   FMTFLGS
FMTDFF   EQU   FMTFLGS
FMTSTF   EQU   FMTFLGS
FMTREPF  EQU   FMTFLGS
FMTBDF   EQU   FMTFLGS
FMTIDF   EQU   FMTFLGS
FMTSCF   EQU   FMTFLGS
FMTEOLF  EQU   FMTFLGS
DARGDTM  EQU   DARGARY+4
DARGPCT  EQU   DARGINL
DARGREP  EQU   DARGINS
@NM00012 EQU   DARGLIST+19
DARGIND  EQU   DARGLIST+18
DARGRETL EQU   DARGLIST+16
DARGCNT  EQU   DARGLIST+14
DARGILP  EQU   DARGLIST+12
DARGRETP EQU   DARGLIST+4
DARGDBP  EQU   DARGLIST
UVOLVOL  EQU   UVOLENT+4
UVOLDEV  EQU   UVOLENT
UVOLCNT  EQU   UVOLLIST
OPNRSVD  EQU   OPNAGL+28
OPNVOL   EQU   OPNAGL+24
OPNBLK   EQU   OPNAGL+20
OPNREC   EQU   OPNAGL+16
OPNDSN   EQU   OPNAGL+12
OPNDDN   EQU   OPNAGL+8
OPNIOC   EQU   OPNAGL+4
@NM00011 EQU   OPNMOD
OPNMODRC EQU   OPNMOD
OPNMODAC EQU   OPNMOD
@NM00010 EQU   OPNTYP
OPNTYPSO EQU   OPNTYP
OPNTYPSI EQU   OPNTYP
@NM00009 EQU   OPNRFM
OPNRFMBK EQU   OPNRFM
OPNRFMSF EQU   OPNRFM
OPNRFMUN EQU   OPNRFM
OPNRFMVR EQU   OPNRFM
OPNRFMFX EQU   OPNRFM
@NM00008 EQU   OPNOPT
OPNOPTJM EQU   OPNOPT
OPNOPTKS EQU   OPNOPT
OPNOPTBK EQU   OPNOPT
OPNOPTUP EQU   OPNOPT
OPNOPTOT EQU   OPNOPT
OPNOPTIN EQU   OPNOPT
IOCEXT   EQU   IOCSTR+36
IOCRRN   EQU   IOCSTR+32
@NM00007 EQU   IOCSTR+30
IOCPNM   EQU   IOCSTR+28
IOCCBP   EQU   IOCSTR+24
IOCDSN   EQU   IOCSTR+20
@NM00006 EQU   IOCSTR+17
@NM00005 EQU   IOCMSG
IOCMSGOP EQU   IOCMSG
IOCMACPA EQU   IOCMAC
@NM00004 EQU   IOCMAC
IOCMACBK EQU   IOCMAC
IOCMACUP EQU   IOCMAC
IOCMACOT EQU   IOCMAC
IOCMACIN EQU   IOCMAC
@NM00003 EQU   IOCRFM
IOCRFMBK EQU   IOCRFM
IOCRFMSF EQU   IOCRFM
IOCRFMUN EQU   IOCRFM
IOCRFMVR EQU   IOCRFM
IOCRFMFX EQU   IOCRFM
@NM00002 EQU   IOCDSO
IOCDSOPS EQU   IOCDSO
IOCKYL   EQU   IOCSTR+12
IOCTRN   EQU   IOCSTR+8
IOCDLN   EQU   IOCSTR+4
IOCDAD   EQU   IOCSTR
STAEWORK EQU   STAEPARM+32
STARPTR  EQU   STAEPFX+28
STASPTR  EQU   STAEPFX+24
STALEN   EQU   STAEPFX+20
STAID    EQU   STAEPFX+16
STAEPA   EQU   STAEPFX+12
STAGDT   EQU   STAEPFX+8
STABPTR  EQU   STAEPFX+4
STAFPTR  EQU   STAEPFX
NEWID2   EQU   TRACE2+95
OLDERID2 EQU   TRACE2
NEWID1   EQU   TRACE1+95
CALLID   EQU   OLDERID1+90
@NM00001 EQU   OLDERID1
.@UNREFD ANOP                          END UNREFERENCED COMPONENTS
@ENDDATA EQU   *
         END   ICKBM01,(C'PLS1701',0701,78192)
