%TUTORIAL -------- PANVALET DATASET HARDCOPY OR BROWSE -----------------
%     PANVALET MENU OPTION P.P - PRINT   +   %NEXT SELECTION==>_OPT
+
+     Panvalet  gives  you the ability to browse or print a dataset.
+     You  can  route  this  to a local or remote printer.  You only
+     have  to  know the Panvalet dataset name and which printer you
+     would  like  to  see  the  hardcopy on.
+
+        Enter  in  the  Panvalet  dataset  name.   Use  Menu P.D to
+     determine the name if you can't remember it. Make sure that it
+     is followed by your Panvalet User Number.
+        If  you  would  only like to browse the dataset, enter in a
+     "B"  after the Access Type field. Use your scroll keys to look
+     at  the  dataset and PF3 to end Browse.  Note: extremely large
+     datasets may be too large to look at with the Browse function,
+     or  to  print  out with this menu.  Also: VSBASIC, TEXT, LIST,
+     and  CLIST TSO datasets will not print out correctly with this
+     menu.   Retrieve  them  with  menu P.R (Panvalet Retrieve) and
+     then  use  menu 3.6 to print them out.  Enter in an "H" or "D"
+     to  obtain  a  hardcopy  of  the  dataset,  depending  on your
+     location and printer type.
+
+        Enter  in  an  "F"  for  "print  class" if you would like a
+     microfiche of the output.
)PROC
  &UP=P0HELP
)END
