*        %GOTO PLSMSK;                  /* BILINGUAL HEADER
         MACRO
         TMSKD
         SPACE
.* CHANGE ACTIVITY AS FOLLOWS:
.*A-000000-999999                                              @Y17XANU
IEDMSK   DSECT
*
*        OPERATOR CONTROL TCHNG MASK DSECT
*
MSKNUM   DS    H .                 NUMBER OF MASKS
MSKMASK  DS    0XL2 .              PROTECTION MASK
MSK1     DS    XL1 .                    MASK BYTE 1
MSKBYTE1 EQU   X'FF' .                   USED TO CHECK IF BYTES 4-7
*                                        OF TTE ARE PROTECTED
MSKCNT   EQU   X'80' .                   CHECK TO ALLOW TLIST COUNT
*                                        MODIFICATION
MSKLIST  EQU   X'40' .                   CHECK TO ALLOW TLIST ENTRIES
*                                        MODIFICATION
*        EQU   X'20'-X'01' .             RESERVED
MSK2     DS    XL1 .                    MASK BYTE 2
MSKBYTE2 EQU   X'F0' .                   USED TO CHECK IF BYTES 8-F
*                                        OF TTE ARE PROTECTED
*        EQU   X'80'-X'10' .             RESERVED
MSKOPT   EQU   X'08' .                   USED TO CHECK IF OPTION
*                                        FIELDS ARE PROTECTED
*                                        (MSKBYTE2)
MSKDVDP  EQU   X'04' .                   USED TO CHECK IF DEVICE
*                                        DEPENDENT FIELDS ARE PROTECTED
*        EQU   X'02'-X'01' .             RESERVED
*
*        THIS DSECT CONSISTS OF 9 MASKS, REPRESENTING 9 TTE TYPES,
*        IN THE FOLLOWING ORDER:
*
*              1 - 270X TERMINAL (DIAL, NON DIAL, LOG)
*              2 - 3705 BSC/SS TERMINAL
*              3 - PU
*              4 - LU
*              5 - SSCP
*              6 - NCP
*              7 - 3705 LINE
*              8 - LIST
*              9 - TPROCESS
*
MSKLEN   EQU   *-MSKMASK .              LENGTH OF MASK ENTRY
         MEND
*        */
*%PLSMSK: ;
*DECLARE 1 IEDMSK BDY(WORD) BASED(IEDMSKP),
*/*                                                                  */
*/*      OPERATOR CONTROL TCHNG MASK DSECT                           */
*/*                                                                  */
*   2 MSKNUM FIXED(15),                 /* NUMBER OF MASKS           */
*   2 MSKMASK CHAR(2),                  /* PROTECTION MASK           */
*    3 MSK1 CHAR(1),                    /* MASK BYTE 1               */
*     4 MSKCNT BIT(1),                   /* CHECK TO ALLOW TLIST COUNT
*                                           MODIFICATION             */
*     4 MSKLIST BIT(1),                  /* CHECK TO ALLOW TLIST
*                                           ENTRIES MODIFICATION     */
*     4 *       BIT(6),                  /* RESERVED                 */
*    3 MSK2 CHAR(1),                    /* MASK BYTE 2               */
*     4 *       BIT(4),                  /* RESERVED                 */
*     4 MSKOPT  BIT(1),                  /* USED TO CHECK IF OPTION
*                                           FIELDS ARE PROTECTED
*                                           (MSKBYTE2)               */
*     4 MSKDVDP BIT(1),                  /* USED TO CHECK IF DEVICE
*                                           DEPENDENT FIELDS ARE
*                                           PROTECTED                */
*     4 *       BIT(2);                  /* RESERVED                 */
*
* %MSKLEN='LENGTH(MSKMASK)';            /* LENGTH OF MASK ENTRY      */
*
*/*                                                                  */
*/*      CONSTANTS (MSK1)                                            */
*/*                                                                  */
*DCL MSKBYTE1 BIT(8) CONSTANT('FF'X);   /* USED TO CHECK IF BYTES 4-7
*                                          OF TTE ARE PROTECTED      */
*/*                                                                  */
*/*      CONSTANTS (MSK2)                                            */
*/*                                                                  */
*DCL MSKBYTE2 BIT(8) CONSTANT('F0'X);   /* USED TO CHECK IF BYTES 8-F
*                                          OF TTE ARE PROTECTED      */
*/*      THIS DSECT CONSISTS OF 9 MASKS, REPRESENTING 9 TTE TYPES,   */
*/*      IN THE FOLLOWING ORDER:                                     */
*/*                                                                  */
*/*            1 - 270X TERMINAL (DIAL, NON DIAL, LOG)               */
*/*            2 - 3705 BSC/SS TERMINAL                              */
*/*            3 - PU                                                */
*/*            4 - LU                                                */
*/*            5 - SSCP                                              */
*/*            6 - NCP                                               */
*/*            7 - 3705 LINE                                         */
*/*            8 - LIST                                              */
*/*            9 - TPROCESS                                          */
*/*                                                                  */
