         TITLE '***** IDCTSCT0 - COPYT STATIC TEXT ****'
* /* START OF SPECIFICATIONS****
*01* PROCESSOR = ASSEMBLER
**** END OF SPECIFICATIONS ***/
************************************************************   @Z40LB65
*                                                          *   @Z40LB65
* MODULE NAME -   IDCTSCT0                                 *   @Z40LB65
*                                                          *   @Z40LB65
*                                                          *   @Z40LB65
* DESCRIPTIVE NAME - STATIC TEXT MODULE FOR THE COPYT      *   @Z40LB65
*         FUNCTION                                         *   @Z40LB65
*                                                          *   @Z40LB65
*                                                          *   @Z40LB65
* COPYRIGHT - NONE                                         *   @Z40LB65
*                                                          *   @Z40LB65
* STATUS - RELEASE 0  LEVEL 0                              *   @Z40LB65
*                                                          *   @Z40LB65
* FUNCTION - CONTAINS NO EXECTABLE CODE, ONLY STATIC TEXT  *   @Z40LB65
*        ENTRIES FOR THE FUNCTION COPYT                    *   @Z40LB65
*        THIS MODULE IS LOADED BY IDCTP05 WHEN A STATIC    *   @Z40LB65
*        TEXT REQUEST IS MADE.                             *   @Z40LB65
*                                                          *   @Z40LB65
* NOTES - NONE                                             *   @Z40LB65
*                                                          *   @Z40LB65
*        DEPENDENCIES - NONE                               *   @Z40LB65
*        RESTRICTIONS - NONE                               *   @Z40LB65
*        REGISTER CONVENTIONS - NA                         *   @Z40LB65
*        PATCH AREA - NA                                   *   @Z40LB65
*                                                          *   @Z40LB65
* MODULE TYPE - TABLES                                     *   @Z40LB65
*                                                          *   @Z40LB65
*        PROCESSOR - ASSEMBLER                             *   @Z40LB65
*        MODULE SIZE - 100                                 *   @Z40LB65
*        ATTRIBUTES - READ-ONLY                            *   @Z40LB65
*                                                          *   @Z40LB65
* ENTRY POINT - NA                                         *   @Z40LB65
*                                                          *   @Z40LB65
* EXIT NORMAL - NA                                         *   @Z40LB65
*                                                          *   @Z40LB65
* EXIT ERROR - NA                                          *   @Z40LB65
*                                                          *   @Z40LB65
* EXTERNAL REFERENCES - NA                                 *   @Z40LB65
*                                                          *   @Z40LB65
* TABLES - NA                                              *   @Z40LB65
*                                                          *   @Z40LB65
* MACROS - NA                                              *   @Z40LB65
*                                                          *   @Z40LB65
* CHANGE ACTIVITY - NONE                                   *   @Z40LB65
*                                                          *   @Z40LB65
************************************************************   @Z40LB65
         EJECT                                                 @Z40LB65
************************************************************   @Z40LB65
*                                                          *   @Z40LB65
* THIS MODULE IS THE FIRST MODULE OF STATIC TEXT REQUIRED  *   @Z40LB65
* BY THE COPYT FSR                                         *   @Z40LB65
*                                                          *   @Z40LB65
************************************************************   @Z40LB65
*                                                              @Z40LB65
IDCTSCT0 CSECT                                                 @Z40LB65
*                                                              @Z40LB65
INDEX    DC    Y((INDEXEND-INDEX1)/2)  COUNT OF ENTRIES        @Z40LB65
INDEX1   DC    Y(TXT1-INDEX)           MSG IDC31160I           @Z40LB65
INDEXEND DS    0H                                              @Z40LB65
         EJECT                                                 @Z40LB65
**********************************************************     @Z40LB65
*                                                        *     @Z40LB65
* IDC31160I TOSTAGINGDRIVE SSID SPECIFIED IS NOT         *     @Z40LB65
*           A VALID MSC TABLES SSID                      *     @Z40LB65
*                                                        *     @Z40LB65
**********************************************************     @Z40LB65
         SPACE 3                                               @Z40LB65
TXT1     DC    Y(TXT1B-TXT1A)          ENTRY LENGTH            @Z40LB65
         DC    X'8000'                 MESSAGE FLAG            @Z40LB65
         SPACE 1                                               @Z40LB65
* SPACING CONTROL SUB-STRUCTURE                                @Z40LB65
TXT1A    DC    X'4000'                 SPACE CONTROL FLAG      @Z40LB65
         DC    H'2'                    SPACING FACTOR          @Z40LB65
         DC    C'R '                   SPACING TYPE            @Z40LB65
         SPACE 1                                               @Z40LB65
* STATIC TEXT SUB-STRUCTURE                                    @Z40LB65
         DC    X'8400'                 STATIC TEXT FLAG        @Z40LB65
         DC    Y(STE11B-STE11A)        TEXT LENGTH             @Z40LB65
         DC    Y(STE11A-TXT1A)         TEXT OFFSET             @Z40LB65
         DC    H'1'                    PRINT COLUMN            @Z40LB65
         DC    Y(STE11B-STE11A)        PRINT FIELD LENGTH      @Z40LB65
         DC    H'0'                    CONVERSION FLAGS        @Z40LB65
         SPACE 1                                               @Z40LB65
* STATIC TEXT ENTRY                                            @Z40LB65
STE11A   DC    C'IDC31160I TOSTAGINGDRIVE SSID SPECIFIED IS NOT '
         DC    C'A VALID MSC TABLES SSID'                      @Z40LB65
STE11B   EQU   *                                               @Z40LB65
TXT1B    EQU   *                                               @Z40LB65
         END   IDCTSCT0                                        @Z40LB65
