//*********************************************************************
//*                                                                   *
//*      ERSTELLT            DATUM = 01.12.77    AUTOR = ZESCHICK     *
//*                                                                   *
//*      ZWECK               RUECKLADEN DES BEST. KK                  *
//*                                                                   *
//*      SYMBOL-PARAMETER                                             *
//*                          CYLKK   = PRIME-ANGABE FUER KK-BEST.     *
//*                          PLATTE2 = PLATTE FUER KK-BEST.           *
//*                          SITAG   = DATUM DES SICHERUNGSTAGES      *
//*                          TOUR    = NR. DER TOUR                   *
//*                                                                   *
//*********************************************************************
//*                                                                   *
//INDLKPLA PROC  CYLKK=125
//*                                                                   *
//KKS    EXEC  PGM=IEFBR14
//DDKK     DD  DSN=KK.BEST.T&TOUR,
//             UNIT=DISK,VOL=SER=&PLATTE2,DISP=(OLD,DELETE)
//*
//KKL    EXEC  PGM=KGALX01
//STEPLIB  DD  DSN=KGALX01,UNIT=DISK,VOL=SER=SYSRES,DISP=SHR
//SYSPRINT DD  SYSOUT=A
//AUSG     DD  SYSOUT=A
//SNAP     DD  SYSOUT=A
//SPIE     DD  SYSOUT=A
//SALBEST  DD  DSN=KK.BEST&SITAG..T&TOUR,
//             LABEL=(4,SL),DISP=OLD
//DALBEST  DD  DSN=KK.BEST.T&TOUR.(INDEX),
//             UNIT=DISK,VOL=SER=&PLATTE2,DISP=(,KEEP),
//             SPACE=(CYL,2,,CONTIG),
//             DCB=(RECFM=FB,LRECL=106,BLKSIZE=3074,CYLOFL=1,
//             DSORG=IS,OPTCD=ILRWY,RKP=1,KEYLEN=08,BUFNO=5)
//         DD  DSN=KK.BEST.T&TOUR.(PRIME),
//             UNIT=DISK,VOL=SER=&PLATTE2,DISP=(,KEEP),
//             SPACE=(CYL,&CYLKK,,CONTIG),
//             DCB=(RECFM=FB,LRECL=106,BLKSIZE=3074,CYLOFL=1,
//             DSORG=IS,OPTCD=ILRWY,RKP=1,KEYLEN=08,BUFNO=5)
//         DD  DSN=KK.BEST.T&TOUR.(OVFLOW),
//             UNIT=DISK,VOL=SER=&PLATTE2,DISP=(,KEEP),
//             SPACE=(CYL,2,,CONTIG),
//             DCB=(RECFM=FB,LRECL=106,BLKSIZE=3074,CYLOFL=1,
//             DSORG=IS,OPTCD=ILRWY,RKP=1,KEYLEN=08,BUFNO=5)
/*
