%TUTORIAL --------------  IBM PC File Transfer Program  --------------T
%OPTION ===>_ZCMD

                            Options for SEND command

%APPEND+ Allows you to add a personal computer file to the end of a data
         a dataset to the end of a personal computer file.  APPEND may n
         specified for members of a partitioned data set.

%BLKSIZE(n)+ When you are%sending+a file, BLKSIZE specifies the block si
             the host dataset (n is the number of bytes in a data block)
             is omitted, BLKSIZE is assumed to be the same as LRECL for
             datasets.  If you are adding to, or replacing a dataset, BL
             the same as that of the existing dataset.

 (More on next panel - press%Enter+to continue)
)PROC
 &ZCONT = VPCT016
 &ZUP   = VPCT000
)END
