         MACRO
         HSYSTBL
         SPACE 1
***********************************************************************
*                                                                     *
*                HUGHES AIRCRAFT SYSTEM CONTROL TABLE                 *
*                                                                     *
*  THIS DSECT DESCRIBES THE SYSTEM CONTROL TABLE HEADER.              *
*  THE ACCOUNTING TABLE IS POINTED TO BY "UVTSYSTB" IN THE HACUVT.    *
*                                                                     *
*  CREATED:    04/15/84                                               *
*                                                                     *
*  UPDATES:                                                           *
*    00/00/00 LDW  (NONE)                                             *
*                                                                     *
***********************************************************************
         SPACE 1
HSYSTBL  DSECT
HSYSTBID DC    CL8'HSYSTBL '            ID (NAME OF THIS LOAD MODULE)
HSYSSPLN DS    0F                       SUBPOOL AND LENGTH
HSYSSP   DC    AL1(241)                 SUBPOOL (CSA, USER KEY, PAGE-
*                                          ABLE, NOT FETCH PROTECTED,
*                                          EXPLICITLY ASSIGNED & FREED)
HSYSLEN  DS    AL3                      LENGTH OF WHOLE MODULE
         DS    H                        LENGTH OF FIXED SECTION
         DS    H                        OFFSET TO SEGMENT DESCRIPTIONS
         DS    F                        SPARE
HSYSDONE DS    F                        # OF USERS FINISHED WITH TABLE
*  DATE AND TIME TABLE WAS LOADED, IN "TIME DEC" MACRO FORM
HSYSDATE DS    F                        DATE THIS TABLE LOADED
HSYSTIME DS    F                        TIME THIS TABLE LOADED
         DS    8A                       SPARE
HSYSNSEG DS    A                        NUMBER OF SEGMENTS
HSYSFEND EQU   *                        END OF FIXED SECTION
         SPACE 2
*---  SEGMENT OFFSETS GO HERE
*HSYS?SEG DS   A                        OFFSET TO ? SEGMENT
         SPACE 2
*  FORMAT OF ? SEGMENTS
HSYSTABS DSECT
HSYSEGOF DS    A                        OFFSET TO LAST ENTRY
HSYSEGLN DS    Y                        LENGTH OF EACH ENTRY
HSYSEGNM DS    Y                        NUMBER OF ENTRIES
HSYSENT1 EQU   *                        FIRST ENTRY
         SPACE 2
         MEND
