*          DATA SET AM002600   AT LEVEL 012 AS OF 07/18/77
         MACRO
&NAME    SUBEXIT &RC=0,&RENT=NO,&RWALNG=0,&SP=0
         GBLB  &RENTOPT
.*             MACRO-ID. 'SUBEXIT'.
.*             AUTHOR.   DON HIGGINS.
.*             DATE WRITTEN.  07/28/70.
.*             REMARKS.  THIS MACRO GENERATES THE CODE TO RESTORE
.*                       REGISTERS AND RETURN FROM A CSECT.  A RETURN
.*                       CODE OF ZERO IS RETURNED UNLESS A DIFFERENT
.*                       CODE IS SPECIFIED USING THE KEY WORD RC=.
.*             REV1 11/14/74 ADD REENTRANT OPTION. SEE SUBENTRY.
.*             REV2 12/09/74 ADD REG OPTION FOR RC OPERAND.
.*             REV3 02/10/76 DSH - ADD SUBPOOL OPTION
         AIF   ('&RC'(1,1) EQ '(').RCREG
         LA    15,&RC
         AGO   .CHKRENT
.RCREG   ANOP
         LR    15,&RC
.CHKRENT ANOP
         AIF   (&RENTOPT EQ 0).NORENT
&NAME    L     13,4(,13)
         STM   15,1,16(13)
         L     1,8(,13)
         LA    15,8
         SLR   1,15
         L     0,4(,1)
         FREEMAIN R,LV=(0),A=(1)
         LM    14,12,12(13)
         BR    14
         MEXIT
.NORENT  ANOP
&NAME    L     13,4(,13)
         L     14,12(,13)
         LM    2,12,28(13)
         BR    14
         MEND
