1


                   *  An Introduction to Dialog Manager  *










            DIRECT ANY QUESTIONS TO DEVELOPMENT TECHNICAL SUPPORT
                8 South / x5719, 5745, 5969, 6786, 4226, 5232
1Introduction to Dialog Manager                                       Pa


                                                                    CONT
+                                                                   ____





   General Overview and Description  . . . . . . . . . . . . . . . . . .

   Features of a Dialog Manager  . . . . . . . . . . . . . . . . . . . .

   Components of a Dialog Manager  . . . . . . . . . . . . . . . . . . .

   ISPF/PDF  DDNAMES . . . . . . . . . . . . . . . . . . . . . . . . . .

   CLISTS and Programs . . . . . . . . . . . . . . . . . . . . . . . . .

   ISPF/PDF Variables  . . . . . . . . . . . . . . . . . . . . . . . . .

   ISPF Variable Search Order  . . . . . . . . . . . . . . . . . . . . .

   ISPF Panels . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   ISPF Skeletons Overview . . . . . . . . . . . . . . . . . . . . . . .

   ISPF Skeletons  . . . . . . . . . . . . . . . . . . . . . . . . . . .

   ISPF Tables . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   ISPF Messages . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   Accessing the test Dialogs for class  . . . . . . . . . . . . . . . .

   Steps for Developing an ISPF DIALOG . . . . . . . . . . . . . . . . .

   Example Dialog Specs  . . . . . . . . . . . . . . . . . . . . . . . .

   Example Dialog Flowchart  . . . . . . . . . . . . . . . . . . . . . .

   Document the flow of the Function . . . . . . . . . . . . . . . . . .

   Example List of Components  . . . . . . . . . . . . . . . . . . . . .
1Introduction to Dialog Manager                                      Pag


   Creating a DISPLAY Panel  . . . . . . . . . . . . . . . . . . . . . .

   Example Screen Image  . . . . . . . . . . . . . . . . . . . . . . . .

   Attribute Section . . . . . . . . . . . . . . . . . . . . . . . . . .

   Body Section  . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   Example BODY Layout of Screen . . . . . . . . . . . . . . . . . . . .

   ISPF System Variables . . . . . . . . . . . . . . . . . . . . . . . .

   INITIALIZATION Section  . . . . . . . . . . . . . . . . . . . . . . .

   PROCEDURE Section . . . . . . . . . . . . . . . . . . . . . . . . . .

   Dynamic Message Generation  . . . . . . . . . . . . . . . . . . . . .

   Example Image Solution  . . . . . . . . . . . . . . . . . . . . . . .

   Example Screen Solution . . . . . . . . . . . . . . . . . . . . . . .

   File Tailoring  . . . . . . . . . . . . . . . . . . . . . . . . . . .

   File Tailoring Example  . . . . . . . . . . . . . . . . . . . . . . .

   Invoking ISPF Services from a CLIST . . . . . . . . . . . . . . . . .

   Invoking the CONTROL Service  . . . . . . . . . . . . . . . . . . . .

   Invoking the DISPLAY Service  . . . . . . . . . . . . . . . . . . . .

   Invoking FILE TAILORING Services  . . . . . . . . . . . . . . . . . .

   Opening the FILE TAILORING file (FTOPEN)  . . . . . . . . . . . . . .

   Generating the FILE TAILORING file (FTINCL) . . . . . . . . . . . . .

   Closing the FILE TAILORING file (FTCLOSE) . . . . . . . . . . . . . .

   The ISPF Test Facility (PDF OPTION 7) . . . . . . . . . . . . . . . .
1Introduction to Dialog Manager                                     Page


   Coding an Example CLIST . . . . . . . . . . . . . . . . . . . . . . .

   Coding a Menu Panel . . . . . . . . . . . . . . . . . . . . . . . . .

   Coding a Tutorial Panel . . . . . . . . . . . . . . . . . . . . . . .

   ISPF Tables . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

   Example Table Display CLIST . . . . . . . . . . . . . . . . . . . . .
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                    General Overview and Description
 ×
 ×______________________________________________________________________





 ø  Dialog

    A Discussion or Communication between 2 or more




 ø  Manager

    One who controls and directs




 ø  Dialog Manager

    Controls Communication / Interaction
    Between User and Processor

    A structured technique used to transfer data
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                      Features of a Dialog Manager
 ×
 ×______________________________________________________________________

    Feature                           Dialog Component
+   _______                           ______ _________




    ø  Formatted Displays               - Panels




    ø  General Edits                    - Panels




    ø  Generates Data                   - Skeletons




    ø  Organizes Data                   - Tables




    ø  Display of tables                - Tables




    ø  Diagnostic / Error messages      - Messages
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                     Components of a Dialog Manager
 ×
 ×______________________________________________________________________




 ø  CLISTS



 ø  Programs



 ø  Variables



 ø  Panels



 ø  Skeletons



 ø  Tables



 ø  Messages
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×
 ×  ISPF/PDF  DDNAMES
 ×
 ×
 ×
 ×       ~ISPPLIB    -     Panel Libraries
 ×
 ×
 ×
 ×       ~ISPSLIB    -     Skeleton Library (input)
 ×
 ×
 ×
 ×        ISPFILE    -     Skeleton Library (output)
 ×
 ×
 ×
 ×       ~ISPLLIB    -     ISPF Program Libraries
 ×
 ×
 ×
 ×       ~ISPTLIB    -     Table Library (input)
 ×
 ×
 ×
 ×        ISPTABL    -     Table Library (output)
 ×
 ×
 ×
 ×        ISPMLIB    -     Message Library
 ×
 ×
 ×
 ×       ~ISPPROF    -     User Profile Library
 ×
 ×
 ×______________________________________________________________________

      ~  these files are required by ISPF at all times.
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                           CLISTS and Programs
 ×
 ×______________________________________________________________________




 ø  Function

    Controls the flow of a dialog




 ø  Pros of using a DIALOG PROGRAM


    1.  Execution speed is excellent.

    2.  Edits and Calculations are coded very easily.

    3.  Almost all high-level languages are supported.




 ø  Pros of using a DIALOG CLIST


    1.  Easy to write quick short CLISTs.

    2.  Short CLISTS are easy to maintain.

    3.  Immediate test and execution - no compile step.
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                           ISPF/PDF Variables
 ×
 ×______________________________________________________________________



 ø  Definition


    A character string that may vary in length, referred to by a symbol.




 ø  Variable Pools


    A "Variable Pool" is a set/collection of variables.

    Variable Pools are maintained by ISPF.

    Variables are maintained by Dialog Manager Services.
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                     ISPF/PDF Variables (continued)
 ×
 ×______________________________________________________________________




                                    ×

           Session 1                ×                  Session 2

  Function 1       Function 2       ×      Function 1             Functi

 %__________^     %___________^     ×     %____________^
 %_____________^ ×          ×     ×           ×           ×            ×
 ×             × ×  Func    ×     ×  Func     ×     ×     ×  Func      ×
 ×   Func      × ×          ×     ×           ×           ×            ×
 ×             × >__________<     >___________<     ×     >____________<
 >_____________<

 %____________________________^     ×
 %___________________________________^ ×                            ×
 ×                                   × ×       S h a r e d          ×
 ×        S  h  a  r  e  d           × ×                            ×
 ×                                   × >____________________________<
 >___________________________________<

 %______________________________________________________________________
 ___^ ×
 × ×                P   r   o   f   i   l   e
 × ×
 ×
 >______________________________________________________________________
 ___<
1Introduction to Dialog Manager                                       Pa


 _______________________________________________________________________
 ×
 ×
 ×                     ISPF/PDF Variables (continued)
 ×
 ×______________________________________________________________________







 ø  Function Pool


    ~ Variables are associated with a single ISPF Function.

    ~ An ISPF Function is a single CLIST, Program or Menu panel.

    ~ ISPF does not initialize a users Function Pool with any variables.

    A Function Pool is not reusable.  ~ The function pool is always dele
    at the end of the function.




 ø  SHARED Pool

    ~ Variables are shared across functions in a single ISPF session.

    ~ When a user first enters ISPF, a Shared Pool is created.

    ~ A different Shared Pool is maintained for both parts of a split
    screen.

    ~ A Shared Pool is deleted when the user exits its split screen.

    ~ Once a variable is in the Shared Pool, you are unable to delete it
1Introduction to Dialog Manager                                       Pa



    ____________________________________________________________________
    ×
    ×
    ×                  ISPF/PDF Variables (continued)
    ×
    ×___________________________________________________________________



 ø  PROFILE Pool


    ~ Variables are associated with a given user.

    ~ The Profile Pool is maintained across ISPF sessions.

    ~ The Profile Pool is never deleted by ISPF.

    ~ Once a variable is in the Profile Pool, you are unable to delete i
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                       ISPF Variable Search Order
 ×
 ×______________________________________________________________________





 ø  Description

    ISPF Services search the variable pools for access to variables.



    The Search Order is:



       1.  Function Pool

       2.  Shared Pool

       3.  Profile Pool



 ø  Functionality

    When a variable is found, it is always maintained in the Function Po

    A variable found in the SHARED or PROFILE pool is copied/created in
    Function Pool.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                               ISPF Panels
 ×
 ×______________________________________________________________________



 ø  Description

    A predefined display image.
    A formatted layout of a screen image.



 ø  Types of ISPF panels


    There are four types:


     1.  Selection or Menu Panels

     2.  Data Entry Panels

     3.  Data Display Panels

     4.  Tutorial Panels


     For the different types of panels, there are different rules and
     considerations.
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×                      ISPF Panels (continued)
    ×
    ×___________________________________________________________________



 ø  Components of a Panel



    Attribute Section - Describes field characteristics


    Body Section      - Defines the screen layout


    Model Section     - Optional image used for table displays


    Init Section      - Describes any initialization code


    Proc Section      - Identifies any Procedural code to be executed
                        This includes edits, assignment statements...
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         ISPF Skeletons Overview
 ×
 ×______________________________________________________________________


             %________________________________________________^
             ×                                                ×
             ×          I S P F     S K E L E T O N           ×
             ×                                                ×
             ×             D E F I N I T I O N S              ×
             ×                                                ×
             ×          (Input to ISPF/PDF Services)          ×
             >________________________________________________<

                                    ×

                                    ×
                     %________________________________^
                     ×                                ×
                     ×          I  S  P  F            ×
                     ×                                ×
                     ×      S  E  R  V  I  C  E  S    ×
                     ×                                ×
                     >________________________________<

                                    ×

                                    ×

             %________________________________________________^
             ×                                                ×
             ×          I S P F     S K E L E T O N           ×
             ×                                                ×
             ×   F I L E   T A I L O R I N G   O U T P U T    ×
             ×                                                ×
             ×         (Output from ISPF/PDF Services)        ×
             >________________________________________________<
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                             ISPF Skeletons
 ×
 ×______________________________________________________________________



 ø  Description

    A generalized representation of data.

    Data may optionally be customized by a DIALOG.



 ø  Functionality of File Tailoring Services


    ~  Symbolic substitution

    ~  Conditional symbolic substitution

    ~  Conditional generation of data

    ~  Variable assignment statements

    ~  Tabbing data

    ~  Imbedding other Skeletons

    ~  Table Processing

    ~  Commenting

    ~  Very similar to JCL Cataloged Procedures...

    ~  Dynamic allocation of output files...
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×                    ISPF Skeletons (continued)
    ×
    ×___________________________________________________________________



 ø  Restrictions

    All skeletons must be in a skeleton library.

    Under ISPF/PDF Release 1 - LRECL of File Tailoring output must be 80
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                               ISPF Tables
 ×
 ×______________________________________________________________________



 ø  Description

    A set of occurring data items

    Similar to an occurring COBOL level.




 ø  Benefits and Features


    ~  Supports Keyed or non-keyed access

    ~  Optional extension variables

    ~  Table Services allows simple display

    ~  Skeleton Services allows simple extraction

    ~  Allows a table to be saved across sessions and users




 ø  Restrictions

    Tables are maintained in core (Region Size)

    Clist services have a lot of overhead
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                              ISPF Messages
 ×
 ×______________________________________________________________________



 ø  Description

    A comment providing special information for a user.


 ø  Uses...

    Alerts a user to errors

    Notifies a user of completion status

    Provides a mini-tutorial service

    Used for logging messages to ISPF log.




 ø  CNA Modifications

    Messages of all types have been greatly improved at CNA.

    You will learn these techniques this week.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                  Accessing the test Dialogs for class
 ×
 ×______________________________________________________________________



 ø  Use LOGON PROC "DIALOG"

    Override Logon Proc when logging on

    When typing in your account number add PR(DIALOG)



 ø  Option 10 under ISPF
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                   Steps for Developing an ISPF DIALOG
 ×
 ×______________________________________________________________________



   1.  List all requirements


   2.  Document the Flow of the Dialog

       Dialog flow (Menu Panels to CLIST, Programs...)

       Function flow (Clist and Programs)


   3.  List all Dialog Components


   4.  Create Panels, Skeletons, Tables, Messages...


   5.  Code CLIST or PROGRAM


   6.  Testing, Implementation and further Documentation
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                          Example Dialog Specs
 ×
 ×______________________________________________________________________



 ø  Scope

    A Dialog to do Background COBOL Compiles from Panvalet


 ø  Requirements...


    1.  Default Panvalet Library to Library found on P.2

    2.  Member name should be remembered from session to session

    3.  Compiler output should optionally be routed to SYSOUT

    4.  Compiler output should optionally be routed to TSDA

    5.  Optional CPYSTAMP (Pipe Processor)

    6.  Compile parms should be remembered and modifiable

    7.  Copy Libraries should be generated before default ones

    8.  Copy Libraries should be remembered across sessions

    9.  Optional Link routine should be available

    10. Systerm should always be routed to MSGCLASS

    11. Job cards should be maintained by menu panel

    12. Enable the user to submit one or more compiles with a job
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                        Example Dialog Flowchart
 ×
 ×______________________________________________________________________



                         %___________________^
                         ×                   ×
                         ×   Menu Panel for  ×
                         ×   Pan Background  ×
                         ×                   ×
                         >_________Ö_________<
                                   ×
         %____________Ö____________+___________Ö___________Ö___________^
        1×           2×           3×          4×          5×          6×
    %____$___^   %____$____^  %____$____^ %____$____^ %____$____^
 %____$____^
    × CLIST  ×   × CLIST   ×  × CLIST   × × CLIST   × × CLIST   × × CLIS
 ×
    × BCOMP1 ×   × BCOMP2  ×  × BCOMP3  × × BCOMP4  × × BCOMP5  × × BCOM
 ×
    ×        ×   ×         ×  ×         × ×         × ×         × ×
 ×
    >________<   >_________<  >_________< >_________< >_________<
 >_________<

  All Clists are stored in TESTE.LIFE.SPF.CLIST
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                    Document the flow of the Function
 ×
 ×______________________________________________________________________



   1.  Initialization

       Test for Debugging mode (will set CONLIST SYMLIST etc...)
       Set ISPF ERROR mode to RETURN
       Do any variable initialization neccessary


   2.  Display the Panel


   3.  Process Panel Return Code

       When Return Code = 8, PF3 was hit
       When Return Code = 0, the enter key was hit


   4.  Edit for valid Panvalet file

       Allocate CNAPANDD to Panvalet file
       If not found, set-up error message and go to display panel


   5.  Verify all COPY Libraries exist


   6.  PAN LIST member DD(CNAPANDD)

       Verify Member exists on PAN library
       If not, issue error message, go to display panel
1Introduction to Dialog Manager                                      Pag



       _________________________________________________________________
       ×
       ×
       ×         Document the flow of the Function (continued)
       ×
       ×________________________________________________________________




   7.  Convert all DSNAMES to JCL Syntax (use MODEL)

       Fully qualified without quotes - unlike ISPF naming conventions.


   8.  Generate JCL


   9.  Use the CNAJCL interface for submitting JCL

       If return code is 4 - loop to step 2
       If return code is not 4 - exit CLIST
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                       Example List of Components
 ×
 ×______________________________________________________________________



 ø  Panels
    1.  COBOL Compile Panel
        User will specify what library and member to COMPILE
        Name = 'TESTE.LIFE.SPF.PANELS(BPANCOBx)'
                                     where x is your group number

 ø  Skeletons

    1.  Skeleton with Job cards in them (IBM supplied ISRJSJC)

    2.  Skeleton with COMPILE JCL
        Name = 'TESTE.LIFE.SPF.SKELETON(CNAPCBx)'
                                     where x is your group number

    3.  Skeleton with LINK JCL
        A CLIST will take care of this.

 ø  Messages
    None - Dynamic message generation will be used.

 ø  Tables
    None

 ø  CLISTS
    1.  Clist to "drive" the Background Compile function
        Name = 'TESTE.LIFE.SPF.CLIST(BCOMPx)'
                                     where x is your group number

 ø  Programs
    None
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                        Creating a DISPLAY Panel
 ×
 ×______________________________________________________________________




 ø  Components

    ~ Attribute Section
       Defines the charactersitics of all fields


    ~ Body Section
       Defines the image (layout) of the panel


    ~ Initialization Section
       Contains all houskeeping code (conversions etc..)


    ~ Procedure Section
       Contains all edits, procedural assignments, internal variable
       manipulation...
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                          Example Screen Image
 ×
 ×______________________________________________________________________

 ---------------------------  DATA SET UTILITY  ------------------------
 OPTION  ===>

    A - Allocate new data set                 C - Catalog data set
    R - Rename entire data set                U - Uncatalog data set
    D - Delete entire data set
    blank - Display data set information

 ISPF LIBRARY:
    PROJECT ===> TESTE
    LIBRARY ===> LIFE
    TYPE    ===> DIVPLIB2

 OTHER PARTITIONED OR SEQUENTIAL DATA SET:
    DATA SET NAME  ===>
    VOLUME SERIAL  ===>          (If not cataloged, required for option

 DATA SET PASSWORD ===>          (If password protected)
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                            Attribute Section
 ×
 ×______________________________________________________________________




 ø  Syntax

    )ATTR        - must begin in column 1.

    )ATTR (abc)  - may be used to override defaults.

           a     = Text field, high intensity  (default = %)
           b     = Text field, low intensity   (defualt = +)
           c     = Input field, high intensity (defualt = _)



 ø  Attribute Section Definition

         char        Keyword(value)      Keyword(value) ....

    where "char"    = any 1 byte field delimiter

    Keyword         = any valid keyword (full list follows)

    "value"         = the appropriate value for the keyword
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                Attribute Section (continued)
        ×
        ×_______________________________________________________________




 ø  KEYWORDS...


    1.  TYPE (TEXT × INPUT × OUTPUT)

        specifies the type of field this character represents:

        TEXT    represents fixed data (literal) that is to be displayed

        INPUT   represents a variable whos data is displayed and modifia

        OUTPUT  represents a variable whos data is display only


    2.  INTENS (HIGH × LOW × NON)

        Specifies the intensity (brightness) used for this type of field

        HIGH    represents a bright intensity field

        LOW     represents a normal intensity field

        NON     represents a non-display field (valid only for input)
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                Attribute Section (continued)
        ×
        ×_______________________________________________________________




    3.  CAPS (ON × OFF)

        Specifies whether upper-case translation should occur:

        ON      designates all data should be set to uppercase

        OFF     designates all data should be left as typed


    4.  JUST (LEFT × RIGHT × ASIS)

        Specifies how the contents of the field should be justified:

        LEFT    Left justify all data

        RIGHT   Right justify all data

        ASIS    No justification should occur


    5.  PAD (NULLS × char)

        Specifies the "pad" character used for input/output fields:

        NULLS   represents that low-values (nulls) be used

        char    is any character enclosed in single quotes be used
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                Attribute Section (continued)
        ×
        ×_______________________________________________________________




    6.  SKIP (ON × OFF)

        Specifies whether the autoskip attribute be used:

        ON      The cursor should skip to the next input field

        OFF     The cursor will not skip - the keyboard will lock.


    7.  ATTN (ON × OFF)

        Not applicable at CNA


 ø  Defaults

     %  TYPE(TEXT) INTENS(HIGH)

     +  TYPE(TEXT) INTENS(LOW)

     _  TYPE(INPUT) INTENS(HIGH)
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                              Body Section
 ×
 ×______________________________________________________________________




 ø  Creating the Panel Image

    Using the Attributes defined in the ATTRIBUTE Section

    Define literals, input and output fields



 ø  Standards...

    ‘  IBM Conventions...

    ‘  Consistency...

    ‘  Standardization...

    ‘  The PROFESSIONAL Touch



 ø  On the following pages are exerpts from the ISPF manual...
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                      Example BODY Layout of Screen
 ×
 ×______________________________________________________________________

 )BODY
 %----------------------------  DATA SET UTILITY
 ---------------------------- %OPTION  ===>_ZCMD
 + %
 %   A+- Allocate new data set                %C+- Catalog data set
 %   R+- Rename entire data set               %U+- Uncatalog data set
 %   D+- Delete entire data set
 %   blank+- Display data set information
 +
 +ISPF LIBRARY:
 +   PROJECT%===>_PROJECT +
 +   LIBRARY%===>_LIBRARY +
 +   TYPE   %===>_TYPE    +
 +
 +OTHER PARTITIONED OR SEQUENTIAL DATA SET:
 +   DATA SET NAME %===>_DSN
 + +   VOLUME SERIAL %===>_VOL   +  (If not cataloged, required for opti
 "C") +
 +DATA SET PASSWORD%===>^PSWD    +(If password protected)
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                          ISPF System Variables
 ×
 ×______________________________________________________________________




 1.  ZUSER     - User Id

 2.  ZPREFIX    - TSO user prefix

 3.  ZLOGON     - Stepname of TSO LOGON procedure

 4.  ZTIME      - Time of day (formatted hh:mm)

 5.  ZDATE      - Current date (format yy/mm/dd)

 6.  ZJDATE     - Day of year date (format yy.ddd)

 7.  ZDAY       - Day of month (2 characters)

 8.  ZMONTH     - Month of the year (2 characters)

 9.  ZYEAR      - Year (2 characters)

 10. ZTEMPF     - Name of temporary file for file tailoring output

 11. ZAPPLID    - Application Identifier

 12. Z          - Null Variable

 13. ZTERM      - Terminal Type

 14. ZKEYS      - Number of Pfkeys

 15. ZPFxx      - Setting for PF keys

 16. ZERRMSG    - Error message id
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                    ISPF System Variables (Continued)
 ×
 ×______________________________________________________________________




 17. ZERRSM     - Short Error Message text

 18. ZERRLM     - Long Error Message text

 19. ZERRHM     - Name of help panel associated with error message

 20. ZVERB      - Command verb after a command table (SETVERB) action

 21. ZTDTOP     - Current top row upon return from table display

 22. ZSCBR      - Scroll amount for the BROWSE service

 23. ZSCED      - Scroll amount for the EDIT service

 24. ZSCML      - Scroll amount for Member Lists

 25. ZUP        - Name of Parent Panel (tutorial)

 26. ZCONT      - Name of next continuation panel (tutorial)

 27. ZIND       - Yes specifies an index page (tutorial)

 28. ZHTOP      - Name of top panel (tutorial)

 29. ZHINDEX    - Name of first Index Panel (tutorial)

 30. ZCMD       - Command Input field

 31. ZSEL       - Command selected by menu panels

 32. ZPARENT    - Parent menu name (in explicit chain mode only)
1Introduction to Dialog Manager                                      Pag


 33. ZPRIM      - Yes specifies panel is a primary option panel
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         INITIALIZATION Section
 ×
 ×______________________________________________________________________




 ø  Syntax

    )INIT        - must begin in column 1.

    Nothing else may be found on the line.



 ø  Assignment Statements...

    variable = value


    1.  &A = ' '      will set the variable A to null

    2.  &A = &Z       will set the variable A to null

    3.  &COUNT = 5    will set the variable COUNT to 5

    4.  &DSN = '''SYS1.MACLIB'''
        will set variable DSN to 'SYS1.MACLIB'

    5.  &BB = &C      will set BB to the contents of variable C
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×              INITIALIZATION Section (Continued)
        ×
        ×_______________________________________________________________




 ø  TRUNC (variable,value)


    "value"    can be a numeric value

               will truncate the "value" amount of bytes


    "value"    can be a one-byte character

               will truncate at that character

               character must be enclosed in quotes




    1.  &A = TRUNC (&XYZ,3)

        will set the variable A to the first 3 bytes represented by vari
        XYZ.

        If XYZ is less than 4 bytes, variables A and XYZ will be identic
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×              INITIALIZATION Section (Continued)
        ×
        ×_______________________________________________________________




 ø  TRANS (variable  value,value ... MSG=value)


    "value,value"  will translate from first value to second value

                   unlimited amount of value,value pairs


    "MSG=value"    is optional and will display a message if no value fo



    1.  &A = TRANS (&XYZ NO,N,YES,Y,*,&Z)

    2.  &A = TRANS (TRUNC ( &ABC,1) N,NO,Y,YES,MSG=ERR1)
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×              INITIALIZATION Section (Continued)
        ×
        ×_______________________________________________________________




 ø  IF ( variable operator value,value...)


    "operator"     may be "=" or "^=" only

    "value"        may be any value or variable



    1.  IF (&ZUSER = 'C1307','C5708','C7836')
           &ABC = X

    2.  IF (&ZUSER ^= 'C1307','C5708','C7836')
           &ABC = Y



 ø  Special Variables


    .CURSOR = field

    .HELP = panel

    .RESP = ENTER or END

    .ZVARS = '(variable,variable)'

    .TRAIL represents the remainder of a TRUNC

    .MSG = message
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                            PROCEDURE Section
 ×
 ×______________________________________________________________________




 ø  Syntax

    )PROC        - must begin in column 1.

    Nothing else may be found on the line.



 ø  All statements found in INIT are valid in PROC


 ø  VER (variable, NONBLANK, keyword,value... MSG=value)


    "variable"    represents the variable you wish to edit

    "NONBLANK"    is optional and says the variable must not be null

                  NONBLANK may be abbreviated as NB


    "keyword"     represents a valid edit keyword
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                PROCEDURE Section (Continued)
        ×
        ×_______________________________________________________________




    1.  PICT - the variable must conform to a picture

        VER (&SSN,NB,PICT,NNN-NN-NNNN)

        will verify that &SSN is not blank and is entered as a valid Soc
        Security Number.


    2.  ALPHA


        VER (&ABC,ALPHA)

        Will ensure that if &ABC is entered, is contains only alpha
        characters

    3.  NUM

        VER (&ABC,NONBLANK,NUM,MSG=ABC001)

        Ensures that &ABC is entered and is numeric. If not, message ABC
        will be displayed.

    4.  HEX

        Verifies the variable is all valid hexadecimal digits.

    5.  BIT

        Verifies the variable is all "0"s and "1"s.
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                PROCEDURE Section (Continued)
        ×
        ×_______________________________________________________________




    6.  NAME

        Verifies the variable is in valid member name syntax.

    7.  DSNAME

        Verifies the variable is in valid Dataset Name syntax.

    8.  RANGE

        Verifies the variable is within a range of the values that follo

        VER (&NUM,RANGE,1,1300)

    9.  LIST

        Verifies the variable is one of the following values in the list

        VER (&OPT,LIST,A,B,C,D,E,F)



 ø  VPUT name-list pool-name

    name-list      is the list of variables enclosed in parends.

    pool-name      is ASIS, SHARED or PROFILE
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                       Dynamic Message Generation
 ×
 ×______________________________________________________________________




 ø  Components of a message

    24 byte error message in top left corner

    78 byte error message shown on the third line of the display



 ø  Special Message Names

    DTS001  thru  DTS049

    Displays variables UMSG1  thru  UMSG49 in the 24 byte area

    Displays variables LMSG1  thru  LMSG49 in the 78 byte area



 ø  SPF Processing of Error Messages

    If the 24 byte message is = spaces - ignore - display 78 byte one.

    If the 78 byte message is = spaces - ignore - display the tutorial.



 ø  Directing Error Message to a specific tutorial panel

    DTS050 thru DTS069 directs the PF1 key (HELP key) to a specific tuto
    panel.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         Example Image Solution
 ×
 ×______________________________________________________________________






   ---------------------------  EDIT - ENTRY PANEL
 --------------------------
   COMMAND ===>

   ISPF LIBRARY:
      PROJECT ===> TESTE
      LIBRARY ===> LIFE.SPF  ===>           ===>           ===>
      TYPE    ===> CLIST
      MEMBER  ===>                 (Blank for member selection list)

   OTHER PARTITIONED OR SEQUENTIAL DATA SET:
      DATA SET NAME  ===>
      VOLUME SERIAL  ===>          (If not cataloged)

   DATA SET PASSWORD ===>          (If password protected)

   PROFILE NAME      ===>          (Blank defaults to data set type)
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         Example Screen Solution
 ×
 ×______________________________________________________________________






 )ATTR
   ^ TYPE(INPUT) INTENS(NON)
 )BODY
 %-------------------------  EDIT - ENTRY PANEL
 ----------------------------- %COMMAND ===>_ZCMD
 + %
 +ISPF LIBRARY:
 +   PROJECT%===>_PROJECT +
 +   LIBRARY%===>_LIBRARY % ===>_LIB2    % ===>_LIB3    % ===>_LIB4    +
 +   TYPE   %===>_TYPE    +
 +   MEMBER %===>_MEMBER  +       (Blank for member selection list)
 +
 +OTHER PARTITIONED OR SEQUENTIAL DATA SET:
 +   DATA SET NAME %===>_DSN
 +   VOLUME SERIAL %===>_VOL   +  (If not cataloged)
 +
 +DATA SET PASSWORD%===>^PASSWD  +(If password protected)
 +
 +PROFILE NAME     %===>_Z       +(Blank defaults to data set type)
 )INIT
    .HELP = ISR20000
    .ZVARS = '(EDPR)'
 )PROC
  IF (&ZCMD ^= &Z)
     .MSG = ZCMD001

  IF (&DSN = &Z)
     VER (&PROJECT,NB,NAME,MSG=DTS001)
     VER (&LIBRARY,NB,NAME,MSG=DTS002)
     VER (&LIB2,NAME,MSG=DTS002)
1Introduction to Dialog Manager                                      Pag


     VER (&LIB3,NAME,MSG=DTS002)
     VER (&LIB4,NAME,MSG=DTS002)
     VER (&TYPE,NAME,MSG=DTS003)

  VER (&DSN,DSNAME)
  VER (&VOL,NAME,MSG=DTS004)
  &VOL = TRUNC (&VOL,6)
  &TRAIL = .TRAIL
  IF (&TRAIL ^= &Z)
      .MSG = DTS004

  &UMSG1 = 'INVALID PROJECT NAME'
  &LMSG1 = 'EXPECTED VALID PROJECT NAME TO BUILD THE EDIT DSNAME WITH'
  &UMSG2 = 'INVALID LIBRARY NAME'
  &LMSG2 = 'EXPECTED A VALID LIBRARY NAME TO BUILD THE EDIT DSNAME WITH'
  &UMSG3 = 'INVALID TYPE SPECIFIED'
  &LMSG3 = 'EXPECTED A VALID TYPE TO BUILD THE EDIT DSNAME WITH'
  &UMSG4 = 'INVALID VOLSER'
  &LMSG4 = 'EXPECTED A VOLSER NOT GREATER THAN 6 BYTES LONG'
  VPUT (EDPR) PROFILE
 )END
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                             File Tailoring
 ×
 ×______________________________________________________________________




 ø  JCL is maintained in the "skeleton library"



 ø  JCL or Data of any kind may be generated



 ø  All ampersands are treated as variables and are subsituted at File
    Tailoring time.



 ø  Double ampersands generate as a single ampersand.



 ø  Data may not expand beyond column 80.



 ø  Blank lines are not generated.
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                  File Tailoring (Continued)
        ×
        ×_______________________________________________________________




 ø  The Skeleton may contain the following commands:

    Note:      All commands start in column 1.

    1.  )SEL      relational-expression
        )ENDSEL


        By surrounding part of the skeleton with the above commands, the
        skeleton will be conditionally generated.


        If the relational expression is true, the skeleton is generated.


        )SEL &SW = 0

        data...

        )ENDSEL



    2.  )SET     variable = value or expression


        Will assign a variable a value during the file tailoring.


        )SET SW = 1
1Introduction to Dialog Manager                                      Pag



        ________________________________________________________________
        ×
        ×
        ×                  File Tailoring (Continued)
        ×
        ×_______________________________________________________________




    3.  )CM    comments


        Allows imbedding of comments in the skeleton.

        These lines will not be generated by the File Tailoring Services



    4.  )TB   tab columns

        Used to set the Tab Columns.

        Default is one setting at column 80.
        The exclamation mark (!) is the default tab character.



    5.  )IM   skeleton name NT OPT

        Used to include other skeletons.

        Optional keywords NT will not File Tailor.
1Introduction to Dialog Manager                                      Pag



             ___________________________________________________________
             ×
             ×
             ×               File Tailoring (Continued)
             ×
             ×__________________________________________________________




    6.  )DEFAULT   abcdefg

        Used to set the default characters used by the File Tailoring
        Service.

        Defaults are:
                 a     )  represents the character used to denote FT
             command.
                 b     &  denotes a variable
                 c     ?  denotes a FT continuation
                 d     !  used to tab
                 e     <  denotes the left side of a conditional value
                 f     ×  represents the "or" sign of a conditional valu
                 g     >  represents the right side of a conditional val
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         File Tailoring Example
 ×
 ×______________________________________________________________________

 )SEL &FRSTTIME = Y && &JOB1 ^= &Z
 &JOB1
 )ENDSEL
 )SEL &FRSTTIME = Y && &JOB2 ^= &Z
 &JOB2
 )ENDSEL
 )SEL &FRSTTIME = Y && &JOB3 ^= &Z
 &JOB3
 )ENDSEL
 )SEL &FRSTTIME = Y && &JOB4 ^= &Z
 &JOB4
 )ENDSEL
 //*****************************************************************
 //**
 //**       THIS IS THE LIBRARY CROSS REFERENCE FUNCTION
 //**
 //*****************************************************************
 //XREFLIBS  EXEC PGM=ZCNAJ3,PARM=&PGMOPT
 //STEPLIB     DD DSN=SYS1.SPF.CNALOAD,DISP=SHR
 //SORTLIB     DD DSN=SYS1.SORTLIB,DISP=SHR
 //SORTMSGS    DD  SYSOUT=&WTR
 //SYSPRINT    DD  SYSOUT=&WTR
 //SYSUDUMP    DD  SYSOUT=&WTR
 //REPORT      DD  SYSOUT=&WTR,DCB=BLKSIZE=1330,COPIES=&COP
 //SYSIN       DD  *
 ++PRINT 0-UP
 //SYSPUNCH    DD  UNIT=SYSDA,SPACE=(CYL,(1,1)),
 //             DCB=(RECFM=FB,BLKSIZE=800,LRECL=80)
 //WKFILE01    DD  UNIT=SYSDA,SPACE=(CYL,(2,2)),DISP=(MOD,DELETE)
 //SORTWK01    DD  UNIT=SYSDA,SPACE=(CYL,(6),,CONTIG)
 //SORTWK02    DD  UNIT=SYSDA,SPACE=(CYL,(6),,CONTIG)
 //SORTWK03    DD  UNIT=SYSDA,SPACE=(CYL,(6),,CONTIG)
 //SORTWK04    DD  UNIT=SYSDA,SPACE=(CYL,(6),,CONTIG)
 //SORTWK05    DD  UNIT=SYSDA,SPACE=(CYL,(6),,CONTIG)
 //CONTROL     DD DUMMY,DCB=(RECFM=F,BLKSIZE=80,LRECL=80)
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                   File Tailoring Example (Continued)
 ×
 ×______________________________________________________________________




 )SEL    &LIB1 = Y
 //&LIT1.LIB&CG1.1  DD DSN=&DSN1,DISP=SHR
 )ENDSEL
 )SEL    &LIB2 = Y
 //&LIT2.LIB&CG2.2  DD DSN=&DSN2,DISP=SHR
 )ENDSEL
 )SEL    &LIB3 = Y
 //&LIT3.LIB&CG3.3  DD DSN=&DSN3,DISP=SHR
 )ENDSEL
 )SEL  &LIB4 = Y
 //&LIT4.LIB&CG4.4  DD DSN=&DSN4,DISP=SHR
 )ENDSEL
 )SEL  &LIB5 = Y
 //&LIT5.LIB&CG5.5  DD DSN=&DSN5,DISP=SHR
 )ENDSEL
 )SEL  &LIB6 = Y
 //&LIT6.LIB&CG6.6  DD DSN=&DSN6,DISP=SHR
 )ENDSEL
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                   Invoking ISPF Services from a CLIST
 ×
 ×______________________________________________________________________




 ø  SYNTAX

    ISPEXEC   service-name  parameters



    ISPEXEC       must be coded as shown.

    service-name  is the appropriate service you wish to invoke.

    parameters    are any valid parms associated with the service.



 ø  Notes about ISPF Services

    ~ All Variables in a CLIST are implicit.

    ~ If ISPEXEC is issued from outside ISPF, LASTCC = 12.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                      Invoking the CONTROL Service
 ×
 ×______________________________________________________________________




 ø  SYNTAX

    ISPEXEC   CONTROL   type    mode



    ISPEXEC       must be coded as shown.

    CONTROL       is the service-name and should be coded as shown.

    type          should be a valid CONTROL type as found in the ISPF
                  manual.

    mode          should be a valid "mode" for the "type" selected.



 ø  Setting Error Modes


    ISPEXEC CONTROL ERRORS CANCEL

    or

    ISPEXEC CONTROL ERRORS RETURN


    Tells SPF to handle or ignore return codes greater than 12.
    Only affects ISPEXEC Services.
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×               Invoking the CONTROL Service (continued)
    ×
    ×___________________________________________________________________




 ø  Setting DISPLAY Refresh mode


    ISPEXEC CONTROL DISPLAY REFRESH


    Will send the entire screen image when the next panel is displayed.

    Automatically set by entering Line Mode.



 ø  Setting DISPLAY Line Mode


    ISPEXEC CONTROL DISPLAY LINE START(number)


    Tells SPF to enter Line Mode and will place cursor at line "number".

    Number "0" will place cursor at end of panel.



 ø  Setting DISPLAY LOCK


    ISPEXEC CONTROL DISPLAY LOCK


    Tells SPF not to free the keyboard when the next screen is displayed
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×               Invoking the CONTROL Service (continued)
    ×
    ×___________________________________________________________________




 ø  Setting DISPLAY SAVE / RESTORE


    ISPEXEC CONTROL DISPLAY SAVE

    or

    ISPEXEC CONTROL DISPLAY RESTORE


    Saves or restores the current environments control blocks.



 ø  Setting NONDISPL mode


    ISPEXEC CONTROL NONDISPL ENTER

    or

    ISPEXEC CONTROL NONDISPL END


    When the next display of a screen is issued, do not display the scre
    Simulate the ENTER or END key being hit.
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×               Invoking the CONTROL Service (continued)
    ×
    ×___________________________________________________________________




 ø  Setting SPLIT mode


    ISPEXEC CONTROL SPLIT ENABLE

    or

    ISPEXEC CONTROL SPLIT DISABLE


    Enable or Disable the SPLIT Screen function.
    If Split Screen is already entered, set bad Return Code.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                      Invoking the DISPLAY Service
 ×
 ×______________________________________________________________________




 ø  SYNTAX

    ISPEXEC DISPLAY PANEL(panel) MSG(message) CURSOR(field)


    ISPEXEC        must be coded as shown

    DISPLAY        must be coded as shown

    PANEL(panel)   is optional.
                   Code the panel name to be displayed.

    MSG(message)   is optional.
                   Code a Message id if one is to be displayed.

    CURSOR(field)  is optional.
                   Code a Variable name for the cursor to be placed at.



 ø  Return Codes

    0    Normal completion.
    8    User hit PF3 or his END key.
    12   The panel, message or cursor field could not be found.
    16   Truncation or Translation error in storing defined variables.
    20   Severe Error Occurred.
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×             Invoking the DISPLAY Service (continued)
    ×
    ×___________________________________________________________________




 ø  Special Notes

    Leaving the Panel blank will redisplay the current panel.

    Leaving Message blank will issue no message.

    Leaving Cursor blank will have normal cursor placement execute.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                    Invoking FILE TAILORING Services
 ×
 ×______________________________________________________________________




 ø  Description

    File Tailoring Services will generate data found in the skeleton
    library.

    A regular Open, Write and Close file logic must be invoked.



 ø  Opening a the FTS file

    Use the ISPEXEC FTOPEN service



 ø  Generating (writing) the FTS file

    Use the ISPEXEC FTINCL service



 ø  Closing the FTS file

    Use the ISPEXEC FTCLOSE service
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                Opening the FILE TAILORING file (FTOPEN)
 ×
 ×______________________________________________________________________




 ø  Syntax

    ISPEXEC   FTOPEN  TEMP


    ISPEXEC        must be coded as shown

    FTOPEN         must be coded as shown

    TEMP           is optional.
                   If coded, it must be coded as shown.



 ø  Description

    Open a File Tailoring Output file.

    TEMP  keyword says the file is a temporary one.
    ISPF will dynamically allocate a file for you.

    The files fully qualified name without quotes is found in the shared
    pool as variable ZTEMPF.

    If TEMP is not used, the output file must be allocated by a user to
    DDNAME ISPFILE.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×               Generating the FILE TAILORING file (FTINCL)
 ×
 ×______________________________________________________________________




 ø  Syntax

    ISPEXEC   FTINCL  skel-name   NOFT


    ISPEXEC        must be coded as shown

    FTINCL         must be coded as shown

    skel-name      should be a valid skeleton name.

    NOFT           is optional.
                   If coded it must be coded as shown.
                   It tells the File Tailoring not to process the skelet



 ø  Description

    Include into the File Tailoring Output file the named skeleton.

    NOFT  keyword says not to do any variable subsitution or processing
    the ) control cards.

    An FTOPEN must have been executed successfully.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                Closing the FILE TAILORING file (FTCLOSE)
 ×
 ×______________________________________________________________________




 ø  Syntax

    ISPEXEC   FTCLOSE


    ISPEXEC        must be coded as shown

    FTCLOSE        must be coded as shown



 ø  Description

    Closes the File Tailoring output file so you may submit JCL or proce
    the data generated.

    There are other parameters on the FTCLOSE not covered here.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                  The ISPF Test Facility (PDF OPTION 7)
 ×
 ×______________________________________________________________________




 ø  Describing the what a "TEST" environment is...

    When ISPF get a panel from ISPPLIB...

    ~  It normally will do a BLDL and reuse the BLDL for the panel.

    ~  After updating the panel description, the BLDL is still pointing
       the old version.

    ~  PA1 or the ATTN key hit twice returns you to the Primary Option M



 In a TEST mode...

    ~  ISPF does a fresh BLDL every time a panel is displayed...

    ~  PA1 or the ATTN key will exit ISPF immediately.



 ø  Invoking the "TEST" mode...

    PDF TEST
    PDF TESTX
    PDF TRACE
    PDF TRACEX

    Enter Option 7 while in ISPF.
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×                The ISPF Test Facility (continued)
    ×
    ×___________________________________________________________________




 ø  Using Option 7

    Option 7.1    -    will test a "function"

    Option 7.2    -    will test/display a data entry panel

    Option 7.3    -    display/update variables in all pools

    Option 7.4    -    allows a user to maintain ISPF tables

    Option 7.5    -    browses a users ISPF LOG.

    Option 7.6    -    allows the user to type any ISPEXEC commands

    Option 7.7    -    allows the user to trace variables/functions

    Option 7.8    -    allows the user to set breakpoints

    Option 7.T    _    is a full tutorial on the above functions
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         Coding an Example CLIST
 ×
 ×______________________________________________________________________




 ø The following is an example CLIST

    /******************************************************************
    /*     DETERMINE IF WE ARE RUNNING IN DEBUG MODE                  *
    /*     AND SET CONTROL ACCORDINGLY                                *
    /******************************************************************
             CONTROL NOFLUSH NOMSG
             ISPEXEC VGET SPFDBUG PROFILE
             IF &LASTCC ^= 0 THEN SET &SPFDBUG = N
             IF &SPFDBUG = Y THEN CONTROL LIST MSG SYMLIST CONLIST
             ELSE CONTROL NOLIST NOMSG NOSYMLIST NOCONLIST
    /******************************************************************
    /*               INITIALIZATION                                   *
    /******************************************************************
             SET MESSAGE =
             SET CURSOR =
             SET PANEL = EDSAMPLE
    /******************************************************************
    /*               MAIN CLIST LOGIC                                 *
    /******************************************************************
    LOOP:    +
             ISPEXEC DISPLAY PANEL(&PANEL) MSG(&MESSAGE) CURSOR(&CURSOR)
    /******************************************************************
    /*             REINITIALIZATION                                   *
    /******************************************************************
             SET MESSAGE =
             SET CURSOR =
             SET PANEL = EDSAMPLE
    /******************************************************************
    /*       DO THE SCOPE OF THE CLIST WORK                           *
    /******************************************************************
              .
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×                Coding an Example Clist (continued)
    ×
    ×___________________________________________________________________




              .
              .
              IF error occurred THEN DO
                  SET UMSG1 = &STR(short message)
                  SET LMSG1 = &STR(long message)
                  SET MESSAGE = &STR(DTS001)
        optional  SET PANEL =
                  SET CURSOR = field name in error
                  GOTO LOOP
                  END
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                           Coding a Menu Panel
 ×
 ×______________________________________________________________________




 ø  Special Considerations for coding a Menu Panel

    Use standard Model under ISPF/PDF EDIT to begin



 ø  The PROC Section

    &ZSEL = TRANS ( TRUNC (&ZCMD,'.')
                   value, ' string '
                   value, ' string '
                     ' ',' '
                     '*','?'  )


    value      is the value the user enters

    string     is a valid string to follow the ISPEXEC SELECT command
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                         Coding a Tutorial Panel
 ×
 ×______________________________________________________________________




 ø  The PROC Section may be the same as a Menu Panel


    To set up a "menu" of help panels.

    The "string" value that &ZSEL is assigned must be a panel name.

    If the panel name is preceded by a "*", the panel will not be
    automatically selected by ISPF services (when the user hits enter wi
    nothing else.



 ø  &ZCONT parameter

    Used to specify a panel which is a continuation of the current one.



 ø  &ZUP parameter

    Connects a panel to an upper level panel.

    Used only when this panel is displayed before the upper level panel.
    If the upper panel is displayed first, ISPF will remember.



 ø  Testing the tutorial service

    ISPEXEC SELECT PGM(ISPTUTOR) PARM(panel name)
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                               ISPF Tables
 ×
 ×______________________________________________________________________




 ø  Overview


    Tables consists of rows (records) of data

    Rows consists of variables (fields) of data

    _____________Ö_____________________Ö___________________________^
                 ×  &NAME              ×  &ADDRESS                 ×
    _____________+_____________________+___________________________@
    Row number 1 ×  Bob Zimmerman      ×  1234 State Street        ×
    _____________+_____________________+___________________________@
    Row number 2 ×  Bruce Lomar        ×  1236 Wabash Street       ×
    _____________$_____________________$___________________________<



 ø  ISPF Table Services


    ô  Creates a table

    ô  Opens a table previously closed

    ô  Saves a table (permanent tables)

    ô  Closes a table with or without saving it

    ô  Deletes tables
1Introduction to Dialog Manager                                      Pag



       _________________________________________________________________
       ×
       ×
       ×                    ISPF Tables (continued)
       ×
       ×________________________________________________________________




 ø  ISPF Tables Services for rows of the table


    ô  A row can have unlimited amount of variables (fields)

    ô  The data the row represents is limited to 32k

    ô  Pointing to row "x" will fill the variables of the table with the
       data of that row.

    ô  Any single row can be "extended" with extra variables pertinent t
       that row.



    ø  ISPF Tables Services for columns of a table


       ô  You may scan a table for a specific value(s) in a given
       variable(s).



 ø  Temporary tables  vs.  Permanent Tables

    Permanent tables are saved on DISK (ISPTABL) and may be opened from
    (ISPTLIB).

    Temporary tables exist only in storage and are deleted from storage.

    Permanent tables may be shared across users (for read only).
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×                      ISPF Tables (continued)
    ×
    ×___________________________________________________________________




 ø  Keyed  vs.  non-Keyed tables

    Any row variable(s) can be designated as the key to the table.

    Duplicate keys are not allowed.

    In ISPF RELEASE 2, keyed tables are maintained in key sequence.

    Rows of a keyed table may be accessed directly by a key.



 ø  Displaying the data of a table

    Any single row can be displayed/updated by a data entry panel.

    Display of 2 or more rows requires a special TABLE DISPLAY panel.

    On the Table Display panel, you may select which variables of the ro
    should be displayed.

    Table Display panels do not support )PROC section.
    This is only Release 1.
    This only applies to the table variables.

    The display is maintained by ISPF (Scrollable).
1Introduction to Dialog Manager                                      Pag



    ____________________________________________________________________
    ×
    ×
    ×                      ISPF Tables (continued)
    ×
    ×___________________________________________________________________




 ø  LIMITATIONS

    There is no SORT Facility in release 1 to SORT the tables.

    Permanent tables should be limited in size because of overhead.
1Introduction to Dialog Manager                                      Pag


 _______________________________________________________________________
 ×
 ×
 ×                       Example Table Display CLIST
 ×
 ×______________________________________________________________________

 PROC 0
 /******************************************************************
 /*     DETERMINE IF WE ARE RUNNING IN DEBUG MODE                  *
 /*     AND SET CONTROL ACCORDINGLY                                *
 /******************************************************************
          CONTROL NOFLUSH NOMSG
          ISPEXEC VGET SPFDBUG PROFILE
          IF &LASTCC ^= 0 THEN SET &SPFDBUG = N
          IF &SPFDBUG = Y THEN CONTROL LIST MSG SYMLIST CONLIST
          ELSE CONTROL NOLIST NOMSG NOSYMLIST NOCONLIST
 /******************************************************************
 /*       MAIN CLIST LOGIC
 /*       OPEN TABLE THAT CONTAINS DOCUMENTS
 /******************************************************************
          SET MSG =
          SET CURSOR =
          SET PANEL = DTSDOCS
          SET CSRROW =
          SET ZTDTOP = 1
          SET LERROR =
          ISPEXEC CONTROL ERRORS RETURN
          ISPEXEC TBOPEN DTSDOCS NOWRITE
          SET LCC = &LASTCC
          IF &LCC ^= 0 AND &LCC ^= 12 THEN +
              DO
              ISPEXEC CONTROL DISPLAY LINE START(0)
              WRITE SEVERE ERROR OCCURRED PROCESSING DOCUMENT TABLE
              WRITE OPEN FAILED
              WRITE NOTIFY DEVELOPMENT TECHNICAL SUPPORT (X5719)
              EXIT CODE(&LCC)
              END

 /******************************************************************
 /*       THIS THE CODE THAT LOOPS THRU TABLE PROCESSING
 /******************************************************************
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




 LOOP:    +
          IF &LERROR = OR &LERROR = &CSRROW OR &LERROR = 0 THEN
          ELSE +
              DO
              ISPEXEC TBTOP DTSDOCS
              SET LCC = &LASTCC
              ISPEXEC TBSKIP DTSDOCS NUMBER(&LERROR)
              SET LCC = &LASTCC
              SET LSEL =
              ISPEXEC TBPUT DTSDOCS
              SET LCC = &LASTCC
              END

          ISPEXEC TBTOP DTSDOCS
          SET LCC = &LASTCC
          ISPEXEC TBSKIP DTSDOCS NUMBER(&ZTDTOP)
          SET LCC = &LASTCC

          ISPEXEC TBDISPL DTSDOCS PANEL(&PANEL)   +
                                  MSG(&MSG)       +
                                  CURSOR(&CURSOR) +
                                  CSRROW(&CSRROW)
          SET PCC = &LASTCC
          IF &PCC > 8 THEN +
              DO
              ISPEXEC CONTROL DISPLAY LINE START(0)
              WRITE SEVERE ERROR OCCURRED PROCESSING DOCUMENT SCREEN
              WRITE TBDISPL OF SCREEN FAILED
              WRITE NOTIFY DEVELOPMENT TECHNICAL SUPPORT (X5719)
              EXIT CODE(&LCC)
              END
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




          IF &MSG = THEN SET LERROR =
          ELSE SET LERROR = &CSRROW
          SET MSG =
          SET CURSOR =
          SET PANEL = DTSDOCS
          SET CSRROW =
          IF &STR(&PCMD) = RES THEN SET PCMD = RESET

          ISPEXEC TBQUERY DTSDOCS POSITION(CRP)
          SET LCC = &LASTCC
          IF &CRP = 0 THEN GOTO PRIM
          SET LSEL = &STR(&LSEL)
          IF &STR(&PCMD) = RESET THEN SET LSEL =

 /******************************************************************
 /*       LINE COMMAND EQUAL TO SPACES
 /******************************************************************
          IF &STR(&LSEL) = THEN +
              DO
              GOTO NEXTLC
              END

 /******************************************************************
 /*       LINE COMMAND EQUAL TO "S" OR "P" TO SUBMIT JOB TO PRINT
 /******************************************************************
          IF &STR(&LSEL) = S OR &STR(&LSEL) = P THEN +
              DO
              IF &LENGTH(&JCL) < 9 THEN +
                  ISPEXEC SELECT PANEL(&JCL)
              ELSE +
                  DO
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




                  SET TEMP = &CRP - &ZTDTOP
                  SET TEMP = &TEMP + 12
                  IF &TEMP > 22 THEN SET &TEMP = 22
                  ISPEXEC CONTROL DISPLAY LINE START(&TEMP)
                  CONTROL MSG PROMPT
                  SUB &JCL
                  IF &SPFDBUG ^= Y THEN CONTROL NOMSG NOPROMPT
                  END
              SET LSEL =
              GOTO NEXTLC
              END

 /******************************************************************
 /*       LINE COMMAND EQUAL TO "B"
 /******************************************************************
          IF &STR(&LSEL) = B THEN +
              DO
              IF &STR(&BRDSNAME) = THEN +
                  DO
                  SET UMSG1 = &STR(NO BROWSEABLE DOCUMENT)
                  SET LMSG1 = &STR(THERE IS NO DOCUMENT AVAILABLE +
                  FOR INTERACTIVE BROWSE)
                  SET MSG = &STR(DTS001)
                  SET CURSOR = LSEL
                  SET CSRROW = &CRP
                  END
              ELSE +
                  DO
                  SET BRTITLE = &STR(&DOC - &DESC)
                  ISPEXEC BROWSE DATASET(&BRDSNAME)
                  SET LCC = &LASTCC
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




                  SET BRTITLE =
                  IF &LCC ^= 0 THEN +
                      DO
                      SET UMSG1 = &STR(BROWSE ERROR OCCURRED)
                      SET LMSG1 = &STR(TRIED TO BROWSE &DOC AND +
                      BROWSE RETURN NON-ZERO RETURN CODE)
                      SET MSG = &STR(DTS001)
                      SET CURSOR = LSEL
                      SET CSRROW = &CRP
                      END
                  ELSE SET LSEL =
                  END
              GOTO NEXTLC
              END

 /******************************************************************
 /*       INVALID LINE COMMAND
 /******************************************************************
          SET UMSG1 = &STR(INVALID LINE COMMAND)
          SET LMSG1 = &STR(THE ONLY VALID LINE COMMANDS ARE 'S', 'P' +
          AND 'B')
          SET MSG = &STR(DTS001)
          SET CURSOR = LSEL
          SET CSRROW = &CRP

 /******************************************************************
 /*       CHECK FOR MORE LINE COMMANDS
 /******************************************************************
 NEXTLC:  +
          ISPEXEC TBPUT DTSDOCS
          SET LCC = &LASTCC
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




          IF &MSG = THEN +
              DO
              IF &PCC = 4 OR &PCC = 8 THEN +
                  DO
                  SET PANEL =
                  GOTO LOOP
                  END
              END
          ELSE +
              DO
              GOTO LOOP
              END

 /******************************************************************
 /*       PRIMARY COMMAND AREA
 /******************************************************************
 PRIM:    +
          IF &PCC = 8 AND &LERROR =  THEN +
              DO
              ISPEXEC TBEND DTSDOCS
              SET LCC = &LASTCC
              EXIT CODE(&LASTCC)
              END

          IF &STR(&PCMD) = THEN GOTO LOOP
          IF &STR(&PCMD) = RESET THEN +
              DO
              SET PCMD =
              GOTO LOOP
              END
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




          IF &STR(&PCMD) = PRINT THEN +
              DO
              ALLOC F(ISPFILE) SYSOUT(P) +
                  LRECL(80) BLKSIZE(80) DSORG(PS) RECFM(F A) REUSE
              SET LCC = &LASTCC
              ISPEXEC FTOPEN
              SET LCC = &LASTCC
              ISPEXEC FTINCL DTSDOCS
              SET LCC = &LASTCC
              ISPEXEC FTCLOSE
              SET LCC = &LASTCC
              FREE F(ISPFILE)
              SET PCMD =
              SET UMSG1 = &STR(LIST OF DOCS PRINTED)
              SET LMSG1 = &STR(THE ENTIRE LISTING OF DOCUEMNTS SHOWN +
              HERE HAS BEEN PRINTED)
              SET MSG = &STR(DTS001)
              GOTO LOOP
              END

          SET SYSDVAL = &STR(&PCMD)
          READDVAL COMMAND PARMS EXTRA

          IF &STR(&EXTRA) ^= THEN +
              DO
              SET UMSG1 = &STR(TOO MANY PARAMETERS)
              SET LMSG1 = &STR(YOU HAVE ENTERED TOO MANY PARAMETER FOR +
              THIS FUNCTION)
              SET MSG = &STR(DTS001)
              GOTO LOOP
              END
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




          IF &STR(&PARMS) = THEN +
              DO
              SET UMSG1 = &STR(EXPECTED A PARAMETER)
              SET LMSG1 = &STR(THE LOCATE COMMAND EXPECTS A PARAMETER +
              TO SEARCH ON)
              SET MSG = &STR(DTS001)
              GOTO LOOP
              END

          IF &STR(&COMMAND) = L OR &STR(&COMMAND) = LOC THEN +
              DO
              ISPEXEC TBTOP DTSDOCS
              SET LCC = &LASTCC
              SET DOC = &STR(&PARMS)&STR(*)
              ISPEXEC TBSCAN DTSDOCS ARGLIST(DOC)
              SET LCC = &LASTCC
              IF &LCC = 8 THEN +
                  DO
                  SET UMSG1 = &STR(PREFIX NOT FOUND)
                  SET LMSG1 = &STR(NO DOCUMENTS BEGIN WITH &PARMS)
                  SET MSG = &STR(DTS001)
                  GOTO LOOP
                  END
              ISPEXEC TBQUERY DTSDOCS POSITION(ZTDTOP)
              SET PCMD =
              GOTO LOOP
              END

          SET UMSG1 = &STR(INVALID COMMAND)
          SET LMSG1 = &STR(THE COMMAND ENTERED IS NOT VALID FOR THIS +
          FUNCTION)
1Introduction to Dialog Manager                                      Pag



 _______________________________________________________________________
 ×
 ×
 ×                 Example Table Display Clist (continued)
 ×
 ×______________________________________________________________________




          SET MSG = &STR(DTS001)
          GOTO LOOP
1Introduction to Dialog Manager                                      Pag









































 SCLIB
 DMCLASS
