         TITLE 'IGCFQ10D - COPY/REPLACE DEVICE SESSION INFO.           *
                        '
IGCFQ10D CSECT ,                                                01S0001
@PROLOG  BALR  @12,0                                            01S0001
@PSTART  DS    0H                                               01S0001
         USING @PSTART,@12                                      01S0001
*                                   /*
IGCFQ10D IEDHJN AFTERHJN,HJN
*                                                               01S0462
*   /*****************************************************************/
*   /*                                                               */
*   /* INITIALIZATION                                                */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0462
*   ROPCAVT=RPARM;                  /* SET POINTER TO OP. CTL. AVT   */
         LR    ROPCAVT,RPARM                                    01S0462
*   ROPCE=OPCCOPCE;                 /* SET POINTER TO CURRENT OPCE   */
         L     ROPCE,OPCCOPCE(,ROPCAVT)                         01S0463
*   RAVT=OPCAVTPT;                  /* SET POINTER TO TCAM AVT       */
         L     RAVT,OPCAVTPT(,ROPCAVT)                          01S0464
*   RSAVE=ADDR(OPCSAVE);            /* SET POINTER TO SAVE AREA      */
         LA    RSAVE,OPCSAVE(,ROPCAVT)                          01S0465
*   RWRKAREA=OPCWORK;               /* OP. CTL. WORKAREA BASE - USED
*                                      FOR TEMPORARY STORAGE         */
*                                                               01S0466
         L     RWRKAREA,OPCWORK(,ROPCAVT)                       01S0466
*   /*****************************************************************/
*   /*                                                               */
*   /* BASE COMPILER GENERATED DSECT (CREATED BY REENTRANT OPTION)   */
*   /* FOR TEMPORARY STORAGE ON WORK AREA BASE.                      */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0467
*   GEN REFS(RWRKAREA);                                         01S0467
*                        /*
         USING @DATD,RWRKAREA    */
*   FLAGS=''B;                      /* INIT FLAGS FIELD              */
*                                                               01S0468
         MVI   FLAGS,X'00'                                      01S0468
*   /*****************************************************************/
*   /*                                                               */
*   /* CALCULATE 50% OF TCAM'S LINE UNITS                            */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0469
*   HALFUNIT=AVTNOLBF;              /* # OF TCAM'S LINE UNITS        */
         LH    @14,AVTNOLBF(,RAVT)                              01S0469
         STH   @14,HALFUNIT                                     01S0469
*   SRL(HALFUNIT,1);                /* DIVIDE BY TWO FOR 50%         */
*                                                               01S0470
         SRL   @14,1                                            01S0470
         STH   @14,HALFUNIT                                     01S0470
*   /*****************************************************************/
*   /*                                                               */
*   /* OBTAIN ADDR. OF NEG. PREFIX OF ORIG. OPCE                     */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0471
*   ORGNOPCE=OCPTRSAV-LENGTH(IEDQOPCN);/* OBTAIN THE ADDR. OF THE
*                                      START OF THE NEG. PREFIX IN
*                                      THE ORIG. OPCE                */
         L     ORGNOPCE,OCPTRSAV(,ROPCE)                        01S0471
         SH    ORGNOPCE,@CH00045                                01S0471
*                                                               01S0472
*   /*****************************************************************/
*   /*                                                               */
*   /* MAIN PROCDURE                                                 */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0472
*   IF OCREDRVE=ON THEN             /* IF THIS IS A REDRIVE OPCE     */
*                                                               01S0472
         TM    OCREDRVE(ROPCE),B'00010000'                      01S0472
         BNO   @RF00472                                         01S0472
*     /***************************************************************/
*     /*                                                             */
*     /* THIS IS A REDRIVE OPCE WITH ATTACHED UNITS.                 */
*     /*                                                             */
*     /***************************************************************/
*                                                               01S0473
*     CALL REDRIVE;                                             01S0473
         BAL   @14,REDRIVE                                      01S0473
*   ELSE                                                        01S0474
*     DO;                                                       01S0474
*                                                               01S0474
         B     @RC00472                                         01S0474
@RF00472 DS    0H                                               01S0475
*       /*************************************************************/
*       /*                                                           */
*       /* THIS IS A RESPONSE OPCE OR A REQUEST FROM IGCFL10D.       */
*       /*                                                           */
*       /*************************************************************/
*                                                               01S0475
*       ORGNOPCE->OCRESPCT=ORGNOPCE->OCRESPCT-1;/* DECREMENT RSP. CT.*/
         SLR   @14,@14                                          01S0475
         ICM   @14,3,OCRESPCT(ORGNOPCE)                         01S0475
         BCTR  @14,0                                            01S0475
         STH   @14,OCRESPCT(,ORGNOPCE)                          01S0475
*                                                               02S0476
*       /*************************************************************/
*       /*                                                           */
*       /* ---------- THIS SEGMENT PROCESSES RESPONSES --------      */
*       /*                                                           */
*       /*************************************************************/
*                                                               02S0476
*       IF OCSWITCH=OCRPLDSI THEN   /* IF REPLACE RESPONSE           */
         CLI   OCSWITCH(ROPCE),X'E4'                            02S0476
         BNE   @RF00476                                         02S0476
*         FREUTFLG=ON;              /* SET FLAG TO FREE UNITS        */
         OI    FREUTFLG,B'10000000'                             02S0477
*       ELSE                                                    02S0478
*         IF OCSWITCH=OCOPYDSI THEN /* IF COPY RESPONSE              */
         B     @RC00476                                         02S0478
@RF00476 CLI   OCSWITCH(ROPCE),X'E3'                            02S0478
         BNE   @RF00478                                         02S0478
*           DO;                                                 02S0479
*                                                               02S0479
*             /*******************************************************/
*             /*                                                     */
*             /* DETERMINE IF REPLACE SHOULD BE DONE.                */
*             /*                                                     */
*             /*******************************************************/
*                                                               02S0480
*                                                               03S0480
*             /*******************************************************/
*             /*                                                     */
*             /* --- THIS SEGMENT PROCESSES "COPY DEVICE SESSION     */
*             /* INFO." RESPONSES                                    */
*             /*                                                     */
*             /*******************************************************/
*                                                               03S0480
*             RFY                                               03S0480
*               IEDDSI1 BASED(ADDR(PRUDATA)+LENGTH(IEDBDU));    03S0480
*             RFY                                               03S0481
*               IEDQTRM BASED(RPARM);                           03S0481
*             IF BDUSYRSP=GOODRSP THEN/* IF GOOD RESPONSE ON COPY    */
         L     @14,OCUNIT(,ROPCE)                               03S0482
         CLI   BDUSYRSP+12(@14),X'60'                           03S0482
         BNE   @RF00482                                         03S0482
*               DO;                                             03S0483
*                 RPARM=OCTRMTBL;   /* OBTAIN TTE .....              */
         SLR   RPARM,RPARM                                      03S0484
         ICM   RPARM,3,OCTRMTBL(ROPCE)                          03S0484
*                 CALL IEDQTNT;     /* .... ADDR.                    */
         L     @15,AVTRNMPT(,RAVT)                              03S0485
         BALR  @14,@15                                          03S0485
*                 RZERO=TRMDDIGA;   /* OBTAIN ADDR. .....            */
         LH    RZERO,@CH01535                                   03S0486
*                 CALL IEDQTL;      /* .... OF DEVICE DEPENDENT FIELD*/
         L     @15,AVTDDFT(,RAVT)                               03S0487
         BALR  @14,@15                                          03S0487
*                 DEVDPADR=RTNCODE; /* ADDR. OF DIAL DIGITS FIELD    */
         LR    DEVDPADR,RTNCODE                                 03S0488
*                                                               04S0489
*                 /***************************************************/
*                 /*                                                 */
*                 /* ------ PLACE RU DIAL DATA IN CONTIGUOUS STORAGE */
*                 /* IN OP. CTL. WORK AREA. SAVE POINTERS TO THE UNIT*/
*                 /* ADDR. AND STARTING ADDR. OF DIAL DATA IN RU FOR */
*                 /* MOVE BACK.-------                               */
*                 /*                                                 */
*                 /***************************************************/
*                                                               04S0489
*                 RFY                                           04S0489
*                   IEDDSI1 BASED(PLMVSD);/* BASE ON PARM LIST SOURCE
*                                      DATA                          */
*                 RFY                                           04S0490
*                   IEDDSI2 BASED(PLMVSD);/* ADDR.                   */
*                 RFY                                           04S0491
*                   IEDDSI3 BASED(PLMVSD);                      04S0491
*                 RFY                                           04S0492
*                   IEDDSI4 BASED(PLMVSD);                      04S0492
*                                                               04S0492
*                 /***************************************************/
*                 /*                                                 */
*                 /* INIT. PARM. LIST FOR IEDMVBFR. THIS ROUTINE IS  */
*                 /* USED TO FIND ADDR. OF DIAL DATA BY MOVING BYTES */
*                 /* INTO THEMSELVES THUS MOVING POINTER.            */
*                 /*                                                 */
*                 /***************************************************/
*                                                               04S0493
*                 IEDPLMV=''B;      /* CLEAR PARM. LIST AREA         */
         LA    @14,PARMLSP                                      04S0493
         XC    IEDPLMV(24,@14),IEDPLMV(@14)                     04S0493
*                 PLMVSU=OCUNIT;    /* SOURCE UNIT ADDR.             */
         L     @05,OCUNIT(,ROPCE)                               04S0494
         ST    @05,PLMVSU(,@14)                                 04S0494
*                 PLMVTU=OCUNIT;    /* TARGET UNIT ADDR.             */
         ST    @05,PLMVTU(,@14)                                 04S0495
*                 PLMVSD=ADDR(PRUDATA)+LENGTH(IEDBDU);/* SOURCE DATA
*                                      ADDR.                         */
         LA    @05,PRUDATA(,@05)                                04S0496
         AH    @05,@CH00071                                     04S0496
         ST    @05,PLMVSD(,@14)                                 04S0496
*                 PLMVTD=ADDR(PRUDATA)+LENGTH(IEDBDU);/* TARGET DATA
*                                      ADDR.                         */
         ST    @05,PLMVTD(,@14)                                 04S0497
*                 PLMVLNTH=DSIPOLNM+LENGTH(IEDDSI1);/* NUMBER OF
*                                      POLLING CHARACTERS            */
*                                                               04S0498
         LA    @07,4                                            04S0498
         SLR   @06,@06                                          04S0498
         IC    @06,DSIPOLNM(,@05)                               04S0498
         ALR   @07,@06                                          04S0498
         STH   @07,PLMVLNTH(,@14)                               04S0498
*                 /***************************************************/
*                 /*                                                 */
*                 /* LOCATE START OF ADDR. CHARS. FIELD              */
*                 /*                                                 */
*                 /***************************************************/
*                                                               04S0499
*                 RPARM=ADDR(PARMLSP);/* ADDR. OF PARM LIST  @YM05982*/
         LR    RPARM,@14                                        04S0499
*                 CALL IEDMVBFR;                                04S0500
         L     @05,AVTSAVTP(,RAVT)                              04S0500
         L     @15,SAVTMVBF(,@05)                               04S0500
         BALR  @14,@15                                          04S0500
*                 PLMVLNTH=DSIADRNM+LENGTH(IEDDSI2);/* NUMBER OF
*                                      ADDRESSING CHARACTERS         */
*                                                               04S0501
         LA    @14,PARMLSP                                      04S0501
         L     @05,PLMVSD(,@14)                                 04S0501
         LA    @07,1                                            04S0501
         SLR   @06,@06                                          04S0501
         IC    @06,DSIADRNM(,@05)                               04S0501
         ALR   @07,@06                                          04S0501
         STH   @07,PLMVLNTH(,@14)                               04S0501
*                 /***************************************************/
*                 /*                                                 */
*                 /* LOCATE INPUT IDENTIFIER FIELD.                  */
*                 /*                                                 */
*                 /***************************************************/
*                                                               04S0502
*                 CALL IEDMVBFR;                                04S0502
*                                                               04S0502
         L     @05,AVTSAVTP(,RAVT)                              04S0502
         L     @15,SAVTMVBF(,@05)                               04S0502
         BALR  @14,@15                                          04S0502
*                 /***************************************************/
*                 /*                                                 */
*                 /* IF INPUT ID IS 0 REMAINING FIELDS IN IEDDSI3 ARE*/
*                 /* NOT PRESENT                                     */
*                 /*                                                 */
*                 /***************************************************/
*                                                               04S0503
*                 IF DSINPTID='00'X THEN/* IF 0                      */
         LA    @14,PARMLSP                                      04S0503
         L     @14,PLMVSD(,@14)                                 04S0503
         CLI   DSINPTID(@14),X'00'                              04S0503
         BNE   @RF00503                                         04S0503
*                   FREUTFLG=ON;    /* THEN SET FLAG         @YM07670*/
         OI    FREUTFLG,B'10000000'                             04S0504
*                 ELSE                                          04S0505
*                   DO;             /*                       @YM07430*/
         B     @RC00503                                         04S0505
@RF00503 DS    0H                                               04S0506
*                     PLMVLNTH=LENGTH(IEDDSI3);/* MOVE LENGTH OF
*                                      IEDDSI3                       */
*                                                               04S0506
         LA    @14,PARMLSP                                      04S0506
         MVC   PLMVLNTH(2,@14),@CH00331                         04S0506
*                     /***********************************************/
*                     /*                                             */
*                     /* LOCATE BEGINNING OF DIAL DATA FIELDS        */
*                     /*                                             */
*                     /***********************************************/
*                                                               04S0507
*                     CALL IEDMVBFR;                            04S0507
*                                                               04S0507
         L     @05,AVTSAVTP(,RAVT)                              04S0507
         L     @15,SAVTMVBF(,@05)                               04S0507
         BALR  @14,@15                                          04S0507
*                     /***********************************************/
*                     /*                                             */
*                     /* SAVE POINTERS FOR UNIT AND START OF DIAL    */
*                     /* DATA                                        */
*                     /*                                             */
*                     /***********************************************/
*                                                               04S0508
*                     UNITSAVE=PLMVTU;                          04S0508
         LA    @14,PARMLSP                                      04S0508
         MVC   UNITSAVE(4),PLMVTU(@14)                          04S0508
*                     DATASAVE=PLMVTD;                          04S0509
*                                                               04S0509
         MVC   DATASAVE(4),PLMVTD(@14)                          04S0509
*                     /***********************************************/
*                     /*                                             */
*                     /* MOVE DIAL DATA INTO CONTIGUOUS STORAGE IN   */
*                     /* WORK AREA.                                  */
*                     /*                                             */
*                     /***********************************************/
*                                                               04S0510
*                     PLMVTU=ADDR(DIALDATA);/* ADDR. IN WRK AREA     */
         LA    @05,DIALSP                                       04S0510
         ST    @05,PLMVTU(,@14)                                 04S0510
*                     PLMVTD=ADDR(DIALDATA);/* ADDR. IN WRK AREA     */
         ST    @05,PLMVTD(,@14)                                 04S0511
*                     PLMVTCTG=ON;  /* FLAG FOR CONTIGUOUS TARGET    */
         OI    PLMVTCTG(@14),B'00100000'                        04S0512
*                     PLMVLNTH=DSIDLCNT+LENCTFLD;/* LENGTH OF DIAL
*                                      DATA                          */
         L     @05,PLMVSD(,@14)                                 04S0513
         LA    @07,1                                            04S0513
         SLR   @06,@06                                          04S0513
         IC    @06,DSIDLCNT(,@05)                               04S0513
         ALR   @07,@06                                          04S0513
         STH   @07,PLMVLNTH(,@14)                               04S0513
*                     CALL IEDMVBFR;                            04S0514
         L     @05,AVTSAVTP(,RAVT)                              04S0514
         L     @15,SAVTMVBF(,@05)                               04S0514
         BALR  @14,@15                                          04S0514
*                     RFY                                       04S0515
*                       IEDDSI1 BASED(ADDR(PRUDATA)+LENGTH(IEDBDU));
*                                   /* RESET BASE FOR START OF DATA
*                                      RECORD                        */
*                   END;            /*                       @YM07430*/
*                                   /* ... WORK AREA FOR EASY   03S0517
*                                      HANDLING ADDR. OF DIAL FIELD
*                                      IN RU PLACED IN RUDIALAD      */
*                 IF FREUTFLG=OFF THEN/*                     @YM07670*/
@RC00503 TM    FREUTFLG,B'10000000'                             03S0517
         BNZ   @RF00517                                         03S0517
*                   DO;             /*                       @YM07430*/
*                     IF TTEDIALN>MAXIMUM THEN/* IF TTE DIAL DATA >
*                                      MAX. ALLOWED                  */
         LA    @14,DIALSP                                       03S0519
         CLC   TTEDIALN(1,DEVDPADR),MAXIMUM(@14)                03S0519
         BNH   @RF00519                                         03S0519
*                       FREUTFLG=ON;/* SET TO FREE OPCE AND RU       */
         OI    FREUTFLG,B'10000000'                             03S0520
*                     ELSE                                      03S0521
*                                                               03S0521
*                       /*********************************************/
*                       /*                                           */
*                       /* REPLACE CAN BE DONE IF DIAL DIGITS DO NOT */
*                       /* MATCH.                                    */
*                       /*                                           */
*                       /*********************************************/
*                                                               03S0521
*                       IF TTEDIALN=ACTUAL THEN/* IF NUMBER OF TTE
*                                      DIAL DIGITS IS SAME AS NO. OF
*                                      RU DIGITS                     */
         B     @RC00519                                         03S0521
@RF00519 LA    @14,DIALSP                                       03S0521
         CLC   TTEDIALN(1,DEVDPADR),ACTUAL(@14)                 03S0521
         BNE   @RF00521                                         03S0521
*                         DO;       /* CONVERT NCP'S DIGITS TO BINARY
*                                      AND COMPARE WITH TCAM'S  03S0522
*                                                            @YM06517*/
*                           DIGITS(1:1)=DIGITS(1:1)&CLEARHI;/*  03S0523
*                                      CONVERT FIRST BYTE    @YM06517*/
         NI    DIGITS(@14),X'0F'                                03S0523
*                           IF ACTUAL>1 THEN/* IF MORE THAN 1 DIGIT
*                                                            @YM06875*/
         CLI   ACTUAL(@14),1                                    03S0524
         BNH   @RF00524                                         03S0524
*                             MVZ(DIGITS(2:ACTUAL),DIGITS(1:ACTUAL-1));
         LA    @05,DIALSP                                       03S0525
         SLR   @07,@07                                          03S0525
         IC    @07,ACTUAL(,@05)                                 03S0525
         BCTR  @07,0                                            03S0525
         BCTR  @07,0                                            03S0525
         EX    @07,@SB01711                                     03S0525
*                                   /* CONVERT REST OF DIGITS   03S0526
*                                                            @YM06517*/
*                           ELSE                                03S0526
*                             ;     /*                       @YM06875*/
@RF00524 DS    0H                                               03S0527
*                           IF TTEDIALD(1:TTEDIALN)=DIGITS(1:TTEDIALN)
*                             THEN  /* IF MATCH                      */
         LA    @14,DIALSP                                       03S0527
         SLR   @05,@05                                          03S0527
         IC    @05,TTEDIALN(,DEVDPADR)                          03S0527
         BCTR  @05,0                                            03S0527
         EX    @05,@SC01713                                     03S0527
         BNE   @RF00527                                         03S0527
*                             FREUTFLG=ON;/* REPLACE DOES NOT NEED TO
*                                      BE DONE - FREE OPCE AND RU    */
         OI    FREUTFLG,B'10000000'                             03S0528
*                           ELSE                                03S0529
*                             BLRPLFLG=ON;/* SET FLAG TO BUILD  03S0529
*                                      REPLACE                       */
         B     @RC00527                                         03S0529
@RF00527 OI    BLRPLFLG,B'01000000'                             03S0529
*                         END;      /*                       @YM06517*/
*                       ELSE                                    03S0531
*                         DO;                                   03S0531
         B     @RC00521                                         03S0531
@RF00521 DS    0H                                               03S0532
*                           RFY                                 03S0532
*                             RTNCODE UNRSTD;                   03S0532
*                           RFY                                 03S0533
*                             IEDPRUQD BASED(UNITSAVE);         03S0533
*                           RFY                                 03S0534
*                             TICFLD BASED(ADDR(PRUTIC));       03S0534
*                                                               03S0534
*                           /*****************************************/
*                           /*                                       */
*                           /* IF THE NUMBER OF DIAL DIGITS IN THE   */
*                           /* TTE IS TOO LARGE FOR CURRENT RU, GET  */
*                           /* ANOTHER UNIT.                         */
*                           /*                                       */
*                           /*****************************************/
*                                                               03S0535
*                           IF TIC^=VALTIC THEN/* IF START OF DIAL
*                                      DATA IS IN THE LAST UNIT      */
         L     @05,UNITSAVE                                     03S0535
         TM    TIC+8(@05),B'00000011'                           03S0535
         BZ    @RF00535                                         03S0535
*                             IF(DATASAVE-UNITSAVE)+(COUNT+1)+(TTEDIALN
*                                 -ACTUAL)>(AVTKEYLE+12) THEN/* IS
*                                      ANOTHER UNIT NEEDED           */
         LCR   @05,@05                                          03S0536
         AL    @05,DATASAVE                                     03S0536
         LA    @15,1                                            03S0536
         LA    @14,DIALSP                                       03S0536
         SLR   @07,@07                                          03S0536
         IC    @07,COUNT(,@14)                                  03S0536
         ALR   @07,@15                                          03S0536
         ALR   @05,@07                                          03S0536
         SLR   @07,@07                                          03S0536
         IC    @07,TTEDIALN(,DEVDPADR)                          03S0536
         SLR   @06,@06                                          03S0536
         IC    @06,ACTUAL(,@14)                                 03S0536
         SLR   @07,@06                                          03S0536
         ALR   @05,@07                                          03S0536
         LA    @14,12                                           03S0536
         AH    @14,AVTKEYLE(,RAVT)                              03S0536
         CR    @05,@14                                          03S0536
         BNH   @RF00536                                         03S0536
*                               DO;                             03S0537
*                                 RPARM=1;/* GET ANOTHER ....        */
         LR    RPARM,@15                                        03S0538
*                                 CALL ALLOCBUF;/* .... UNIT         */
         L     @15,OPCGETBF(,ROPCAVT)                           03S0539
         BALR  @14,@15                                          03S0539
*                                 PRUNUNIT=RPARM;/* SET TIC FIELD OF
*                                      LAST UNIT TO POINT TO NEW UNIT*/
         L     @05,UNITSAVE                                     03S0540
         STCM  RPARM,7,PRUNUNIT(@05)                            03S0540
*                               END;                            03S0541
*                             ELSE                              03S0542
*                               ;                               03S0542
@RF00536 DS    0H                                               03S0543
*                           ELSE                                03S0543
*                             ;                                 03S0543
@RF00535 DS    0H                                               03S0544
*                           RFY                                 03S0544
*                             TICFLD BASED;                     03S0544
*                           RFY                                 03S0545
*                             IEDPRUQD BASED(OCUNIT);           03S0545
*                                                               03S0545
*                           /*****************************************/
*                           /*                                       */
*                           /* RESET COUNT FIELDS FOR PACKED RU AND  */
*                           /* GO BUILD REPLACE DSI                  */
*                           /*                                       */
*                           /*****************************************/
*                                                               03S0546
*                           PRUDATCT=PRUDATCT+(TTEDIALN-ACTUAL);/*
*                                      DATA COUNT IN PACKED RU       */
         L     @05,OCUNIT(,ROPCE)                               03S0546
         LA    @15,DIALSP                                       03S0546
         SLR   @14,@14                                          03S0546
         IC    @14,TTEDIALN(,DEVDPADR)                          03S0546
         SLR   @07,@07                                          03S0546
         IC    @07,ACTUAL(,@15)                                 03S0546
         SLR   @14,@07                                          03S0546
         LH    @07,PRUDATCT(,@05)                               03S0546
         ALR   @07,@14                                          03S0546
         STH   @07,PRUDATCT(,@05)                               03S0546
*                           DSITOTNM=DSITOTNM+(TTEDIALN-ACTUAL);/*
*                                      COUNT IN DATA RECORD          */
         LA    @05,PRUDATA(,@05)                                03S0547
         AH    @05,@CH00071                                     03S0547
         SLR   @07,@07                                          03S0547
         IC    @07,DSITOTNM(,@05)                               03S0547
         ALR   @07,@14                                          03S0547
         STC   @07,DSITOTNM(,@05)                               03S0547
*                           COUNT=COUNT+(TTEDIALN-ACTUAL);/* DIAL
*                                      DATA COUNT FIELD IN WRK AREA  */
         SLR   @05,@05                                          03S0548
         IC    @05,COUNT(,@15)                                  03S0548
         ALR   @14,@05                                          03S0548
         STC   @14,COUNT(,@15)                                  03S0548
*                           BLRPLFLG=ON;/* SET FLAG TO BUILD REPLACE */
         OI    BLRPLFLG,B'01000000'                             03S0549
*                           RFY                                 03S0550
*                             RTNCODE RSTD;                     03S0550
*                         END;                                  03S0551
*                   END;            /*                       @YM07430*/
*                 ELSE                                          03S0553
*                   ;               /*                       @YM07430*/
@RF00517 DS    0H                                               03S0554
*               END;                                            03S0554
*             ELSE                                              03S0555
*               FREUTFLG=ON;        /* FREE OPCE AND RU              */
         B     @RC00482                                         03S0555
@RF00482 OI    FREUTFLG,B'10000000'                             03S0555
*             IF BLRPLFLG=ON THEN   /* IF FLAG INDICATING REPLACE TO
*                                      BE BUILT                      */
@RC00482 TM    BLRPLFLG,B'01000000'                             03S0556
         BNO   @RF00556                                         03S0556
*               DO;                                             03S0557
*                                                               04S0558
*                 /***************************************************/
*                 /*                                                 */
*                 /* --- THIS SEGMENT BUILDS REPLACE DEV. SESSION    */
*                 /* INFO. OPCE- PACKED RU PAIRS ----                */
*                 /*                                                 */
*                 /***************************************************/
*                                                               04S0558
*                 TRMTBLSV=OCTRMTBL;/* SAVE OCTRMTBL                 */
         SLR   TRMTBLSV,TRMTBLSV                                04S0558
         ICM   TRMTBLSV,3,OCTRMTBL(ROPCE)                       04S0558
*                 PTRSAVSV=OCPTRSAV;/* SAVE                          */
         L     @14,OCPTRSAV(,ROPCE)                             04S0559
         ST    @14,PTRSAVSV                                     04S0559
*                 UNITSV=OCUNIT;    /* SAVE                          */
         L     @07,OCUNIT(,ROPCE)                               04S0560
         ST    @07,UNITSV                                       04S0560
*                 IEDQOPCN=''B;     /* CLEAR NEG. PREFIX             */
         LA    @05,8                                            04S0561
         LR    @14,ROPCE                                        04S0561
         SLR   @14,@05                                          04S0561
         XC    IEDQOPCN(8,@14),IEDQOPCN(@14)                    04S0561
*                 IEDQOPCE=''B;     /* CLEAR OPCE                    */
         XC    IEDQOPCE(56,ROPCE),IEDQOPCE(ROPCE)               04S0562
*                 OCTRMTBL=TRMTBLSV;/* RESOURCE TTCIN                */
         STH   TRMTBLSV,OCTRMTBL(,ROPCE)                        04S0563
*                 OCPTRSAV=PTRSAVSV;/* POINTER TO ORIG OPCE          */
         L     @14,PTRSAVSV                                     04S0564
         ST    @14,OCPTRSAV(,ROPCE)                             04S0564
*                 OCUNIT=UNITSV;    /* POINTER TO ATTACHED PACKED RU */
         ST    @07,OCUNIT(,ROPCE)                               04S0565
*                 OCSWITCH=OCRPLDSI;/* REPLACE CMND.                 */
         MVI   OCSWITCH(ROPCE),X'E4'                            04S0566
*                 OCELMPRI=PRIMEDFG;                            04S0567
         MVI   OCELMPRI(ROPCE),X'DF'                            04S0567
*                 OCPRIFLG=OPR02;                               04S0568
         MVI   OCPRIFLG(ROPCE),X'08'                            04S0568
*                 OCWTG=THISMOD;    /* SET TO RETURN TO THIS MODULE  */
         MVC   OCWTG(2,ROPCE),THISMOD                           04S0569
*                 OCACTREQ=ON;      /* SET FOR ACTIVATE REQUEST      */
         OI    OCACTREQ(ROPCE),B'00001000'                      04S0570
*                 PRUTTCIN=OCTRMTBL;/* COPY DEVICE TTCIN     @YM06512*/
         SLR   @14,@14                                          04S0571
         ICM   @14,3,OCTRMTBL(ROPCE)                            04S0571
         STH   @14,PRUTTCIN(,@07)                               04S0571
*                 PRURHTH(1:3)=TRHFID0;/* SET FID0 RH FLAGS          */
         LCR   @05,@05                                          04S0572
         ALR   @05,@07                                          04S0572
         MVC   PRURHTH(3,@05),@CB01378                          04S0572
*                 PRURHTH(4:4)=TTH0BYT0;/* SET FID0 TH FLAGS         */
         MVI   PRURHTH+3(@05),X'0C'                             04S0573
*                 BDUMODIF=CD0CRDSI;/* BDU MODIFIER FOR "REPLACE"    */
         AH    @07,@CH00239                                     04S0574
         MVI   BDUMODIF(@07),X'22'                              04S0574
*                 BDUFNFLG=''B;     /* CLEAR FUNCTION FLAGS          */
         MVI   BDUFNFLG(@07),X'00'                              04S0575
*                 BDUHEADR=ON;      /* SET HEADER FLAG       @YM06147*/
         OI    BDUHEADR(@07),B'01000000'                        04S0576
*                 BDUBDUFG=''B;     /* CLEAR BDU FLAGS               */
         MVI   BDUBDUFG(@07),X'00'                              04S0577
*                 BDUSYRSP=''B;     /* CLEAR SYSTEM RESPONSE         */
         MVI   BDUSYRSP(@07),X'00'                              04S0578
*                 BDUEXRSP=''B;     /* CLEAR EXTENDED RESPONSE       */
         MVI   BDUEXRSP(@07),X'00'                              04S0579
*                 TTEDIALR(1:TTEDIALN+1)=TTEDIAL(1:TTEDIALN+1);/*
*                                      MOVE DIAL DIGITS AND LENGTH
*                                      INTO WORK AREA                */
         LA    @14,DIALSP                                       04S0580
         SLR   @05,@05                                          04S0580
         IC    @05,TTEDIALN(,DEVDPADR)                          04S0580
         EX    @05,@SM01717                                     04S0580
*                 DIGITS(1:1)=DIGITS(1:1)×SETHI;/* CONVERT DIGIT TO
*                                      EBCDIC                @YM06517*/
         OI    DIGITS(@14),X'F0'                                04S0581
*                 IF ACTUAL>1 THEN  /* IF MORE THAN 1 DIGIT  @YM06875*/
         CLI   ACTUAL(@14),1                                    04S0582
         BNH   @RF00582                                         04S0582
*                   MVZ(DIGITS(2:ACTUAL),DIGITS(1:ACTUAL-1));/* 04S0583
*                                      CONVERT REST TO EBCDIC @YM6517*/
         LA    @09,DIALSP                                       04S0583
         SLR   @05,@05                                          04S0583
         IC    @05,ACTUAL(,@09)                                 04S0583
         BCTR  @05,0                                            04S0583
         BCTR  @05,0                                            04S0583
         EX    @05,@SB01711                                     04S0583
*                 ELSE                                          04S0584
*                   ;               /*                       @YM06875*/
@RF00582 DS    0H                                               04S0585
*                 IEDPLMV=''B;      /* CLEAR IEDMVBFR PARM. LIST     */
         LA    @14,PARMLSP                                      04S0585
         XC    IEDPLMV(24,@14),IEDPLMV(@14)                     04S0585
*                 PLMVTU=UNITSAVE;  /* UNIT WHERE RU DIAL DATA STARTS*/
         MVC   PLMVTU(4,@14),UNITSAVE                           04S0586
*                 PLMVTD=DATASAVE;  /* ADDR. OF DIAL DATA IN RU      */
         MVC   PLMVTD(4,@14),DATASAVE                           04S0587
*                 PLMVSU=ADDR(DIALDATA);/* ADDR. OF DIAL DATA IN WRK
*                                      AREA                          */
         LA    @09,DIALSP                                       04S0588
         ST    @09,PLMVSU(,@14)                                 04S0588
*                 PLMVSD=ADDR(DIALDATA);/* DUPLICATE                 */
         ST    @09,PLMVSD(,@14)                                 04S0589
*                 PLMVLNTH=COUNT+1; /* NO. BYTES TO MOVE             */
         LA    @05,1                                            04S0590
         SLR   @07,@07                                          04S0590
         IC    @07,COUNT(,@09)                                  04S0590
         ALR   @05,@07                                          04S0590
         STH   @05,PLMVLNTH(,@14)                               04S0590
*                 PLMVSCTG=ON;      /* 'SOURCE CONTIGUOUS' FLAG      */
         OI    PLMVSCTG(@14),B'01000000'                        04S0591
*                 RPARM=ADDR(PARMLSP);/* ADDR OF PARM LIST   @YM05982*/
         LR    RPARM,@14                                        04S0592
*                 CALL IEDMVBFR;    /* MOVE NEW DIAL DATA INTO RU    */
         L     @09,AVTSAVTP(,RAVT)                              04S0593
         L     @15,SAVTMVBF(,@09)                               04S0593
         BALR  @14,@15                                          04S0593
*                 ORGNOPCE->OCRESPCT=ORGNOPCE->OCRESPCT+1;/* UPDATE
*                                      RESPONSE COUNT                */
         LA    @14,1                                            04S0594
         SLR   @09,@09                                          04S0594
         ICM   @09,3,OCRESPCT(ORGNOPCE)                         04S0594
         ALR   @14,@09                                          04S0594
         STH   @14,OCRESPCT(,ORGNOPCE)                          04S0594
*                 OPCMODID=RUDSPMOD;/* SET TO XCTL TO RU DISPATCHER  */
         MVC   OPCMODID(2,ROPCAVT),RUDSPMOD                     04S0595
*               END;                                            03S0596
*             RFY                                               03S0597
*               IEDDSI1 BASED;                                  03S0597
@RF00556 DS    0H                                               03S0598
*           END;                                                02S0598
*         ELSE                                                  02S0599
*           ;                       /* A REQUEST FROM IGCFL10D, NO
*                                      RESPONSE PROCESSING NEEDED, NO
*                                      ATTACHED UNIT TO FREE.        */
@RF00478 DS    0H                                               02S0600
*       IF FREUTFLG=ON THEN         /* IF UNITS ARE TO BE FREED      */
@RC00476 TM    FREUTFLG,B'10000000'                             02S0600
         BNO   @RF00600                                         02S0600
*         IF ORGNOPCE->OCRESPCT=0 THEN/* IF END OF STEP              */
         ICM   @14,3,OCRESPCT(ORGNOPCE)                         02S0601
         BNZ   @RF00601                                         02S0601
*           DO;                                                 02S0602
*                                                               02S0602
*             /*******************************************************/
*             /*                                                     */
*             /* FREE ONLY ATTACHED RU KEEPING THE OPCE TO INITIATE  */
*             /* NEXT STEP IN PROCESSING.                            */
*             /*                                                     */
*             /*******************************************************/
*                                                               02S0603
*             RZERO=1;              /* DECREMENT OPCADGOT BY 1 ....  */
         LA    RZERO,1                                          02S0603
*             CALL DECRCT;          /* .... AND PRIME R/D ELEMENT    */
         L     @15,OPCDECR(,ROPCAVT)                            02S0604
         BALR  @14,@15                                          02S0604
*             RPARM=OCUNIT;         /* GO FREE ....                  */
         L     RPARM,OCUNIT(,ROPCE)                             02S0605
*             CALL FREEBUFF;        /* .... ATTACHED RU              */
         L     @15,OPCFREBF(,ROPCAVT)                           02S0606
         BALR  @14,@15                                          02S0606
*             OCUNIT=PRUINTIC;      /* SET INVALID TIC IN OPCE       */
         MVC   OCUNIT(4,ROPCE),@CF01345                         02S0607
*           END;                                                02S0608
*         ELSE                                                  02S0609
*           DO;                                                 02S0609
*                                                               02S0609
         B     @RC00601                                         02S0609
@RF00601 DS    0H                                               02S0610
*             /*******************************************************/
*             /*                                                     */
*             /* FREE BOTH OPCE AND RU SINCE NO "REPLACE" MUST BE    */
*             /* DONE.                                               */
*             /*                                                     */
*             /*******************************************************/
*                                                               02S0610
*             RZERO=2;              /* DECREMENT OPCADGOT BY 2 ....  */
         LA    RZERO,2                                          02S0610
*             CALL DECRCT;          /* .... AND PRIME R/D ELEMENT    */
         L     @15,OPCDECR(,ROPCAVT)                            02S0611
         BALR  @14,@15                                          02S0611
*             RPARM=ROPCE;          /* FREE OPCE AND ....            */
         LR    RPARM,ROPCE                                      02S0612
*             CALL FREEBUFF;        /* .... ATTACHED RU              */
         L     @15,OPCFREBF(,ROPCAVT)                           02S0613
         BALR  @14,@15                                          02S0613
*             OPCMODID=CNTLMOD;     /* SET TO XCTL TO CONTROL MOD.   */
         MVC   OPCMODID(2,ROPCAVT),CNTLMOD                      02S0614
*           END;                                                02S0615
*       ELSE                                                    02S0616
*         ;                                                     02S0616
@RF00600 DS    0H                                               02S0617
*       DO WHILE(ORGNOPCE->OCRESPCT=0);/* IF THE RESPONSE COUNT IS 0
*                                      INDICATING THAT NEXT STEP
*                                      SHOULD BE DONE                */
*                                                               01S0617
@RC00600 B     @DE00617                                         01S0617
@DL00617 DS    0H                                               01S0618
*         /***********************************************************/
*         /*                                                         */
*         /* DETERMINE WHAT TO DO NEXT                               */
*         /*                                                         */
*         /***********************************************************/
*                                                               01S0618
*                                                               02S0618
*         /***********************************************************/
*         /*                                                         */
*         /* --------- THIS SEGMENT CHECKS THE NEXT STEP TO BE DONE  */
*         /* -----                                                   */
*         /*                                                         */
*         /***********************************************************/
*                                                               02S0618
*         IF OCSWITCH=OCOPYDSI×OCSWITCH=OCRPLDSI THEN/* IF CURRENT
*                                      OPCE IS FOR COPY/REPLACE 02S0618
*                                      DEVICE SESSION INFORMATION    */
         CLI   OCSWITCH(ROPCE),X'E3'                            02S0618
         BE    @RT00618                                         02S0618
         CLI   OCSWITCH(ROPCE),X'E4'                            02S0618
         BNE   @RF00618                                         02S0618
@RT00618 DS    0H                                               02S0619
*           DO;                                                 02S0619
*                                                               02S0619
*             /*******************************************************/
*             /*                                                     */
*             /* DIAL DIGIT PROCESSING COMPLETE FOR ALL AUTOCALL     */
*             /* RESOURCES UNDER THE NCP, SET TO XCTL TO IGCFJ10D TO */
*             /* START ACTLINK PROCESSING.                           */
*             /*                                                     */
*             /*******************************************************/
*                                                               02S0620
*             OCSWITCH=OCACTLK;     /* SET COMMAND AS ACTLINK        */
         MVI   OCSWITCH(ROPCE),X'50'                            02S0620
*             OPCMODID=RPNCPMOD;    /* SET TO XCTL                   */
         MVC   OPCMODID(2,ROPCAVT),RPNCPMOD                     02S0621
*             ORGNOPCE->OCRESPCT=1; /* SET RESPONSE COUNT            */
         MVC   OCRESPCT(2,ORGNOPCE),@CH00060                    02S0622
*             OCREDRVE=OFF;         /* RESET REDRIVE FLAG            */
         NI    OCREDRVE(ROPCE),B'11101111'                      02S0623
*           END;                                                02S0624
*         ELSE                                                  02S0625
*           DO;                                                 02S0625
*                                                               02S0625
         B     @RC00618                                         02S0625
@RF00618 DS    0H                                               02S0626
*             /*******************************************************/
*             /*                                                     */
*             /* CHECK IF ANY DIAL BSC-SS TERMS WITH AUTODIAL        */
*             /* SPECIFIED. REFORMAT CURRENT OPCE INTO REDRIVE OPCE  */
*             /* FOR COPY DSI                                        */
*             /*                                                     */
*             /*******************************************************/
*                                                               02S0626
*                                                               03S0626
*             /*******************************************************/
*             /*                                                     */
*             /* ------ THIS SEGMENT REFORMATS AN OPCE INTO A REDRIVE*/
*             /* OPCE---                                             */
*             /*                                                     */
*             /*******************************************************/
*                                                               03S0626
*             RFY                                               03S0626
*               IEDSATD BASED(ENTRYPTR);/* SAT BASE FOR LOOP         */
*             RFY                                               03S0627
*               IEDRVTD BASED(SATRNRVT);/* BASE FOR RVT              */
*             OCREDRVE=ON;          /* SET FLAG                      */
         OI    OCREDRVE(ROPCE),B'00010000'                      03S0628
*             OCBUFNED=''B;         /* INIT. BUFFER UNITS NEEDED     */
         SLR   @14,@14                                          03S0629
         STH   @14,OCBUFNED(,ROPCE)                             03S0629
*             OCBUFGOT=''B;         /* INIT. BUFFER UNITS GOT        */
         STH   @14,OCBUFGOT(,ROPCE)                             03S0630
*             OCSWITCH=OCOPYDSI;    /* COPY DEV. SESSION INFO. CODE  */
*                                                               03S0631
         MVI   OCSWITCH(ROPCE),X'E3'                            03S0631
*             /*******************************************************/
*             /*                                                     */
*             /* LOOP THROUGH SAT UNTIL CORRECT RVT FOUND            */
*             /*                                                     */
*             /*******************************************************/
*                                                               03S0632
*             ENTRYPTR=SAVTSAT;     /* ADDR. OF SAT - FIRST ENTRY    */
         L     @14,AVTSAVTP(,RAVT)                              03S0632
         MVC   ENTRYPTR(4),SAVTSAT(@14)                         03S0632
*             DO UNTIL(FDRVTFLG=ON);                            03S0633
@DL00633 DS    0H                                               03S0634
*               IF SATRNRVT^=0 THEN /* IF THIS SUBAREA ACTIVE   03S0634
*                                                            @YM05702*/
         L     @14,ENTRYPTR                                     03S0634
         L     @14,SATRNRVT(,@14)                               03S0634
         LTR   @14,@14                                          03S0634
         BZ    @RF00634                                         03S0634
*                 IF RVTINDEX=OCPTRSAV->OCTRMTBL THEN/* IF THIS IS
*                                      CORRECT RVT                   */
         L     @09,OCPTRSAV(,ROPCE)                             03S0635
         SLR   @05,@05                                          03S0635
         ICM   @05,3,OCTRMTBL(@09)                              03S0635
         CH    @05,RVTINDEX(,@14)                               03S0635
         BNE   @RF00635                                         03S0635
*                   FDRVTFLG=ON;    /* SET FLAG TO GET OUT OF LOOP   */
         OI    FDRVTFLG,B'00100000'                             03S0636
*                 ELSE                                          03S0637
*                   ENTRYPTR=ENTRYPTR+LENGTH(IEDSATD);/* UPDATE PTR.
*                                      TO NEXT SAT ENTRY             */
         B     @RC00635                                         03S0637
@RF00635 LA    @14,8                                            03S0637
         AL    @14,ENTRYPTR                                     03S0637
         ST    @14,ENTRYPTR                                     03S0637
*               ELSE                /*                       @YM05702*/
*                 ENTRYPTR=ENTRYPTR+LENGTH(IEDSATD);/* UPDATE PTR. TO
*                                      NEXT SAT ENTRY        @YM06014*/
         B     @RC00634                                         03S0638
@RF00634 LA    @14,8                                            03S0638
         AL    @14,ENTRYPTR                                     03S0638
         ST    @14,ENTRYPTR                                     03S0638
*             END;                                              03S0639
@RC00634 DS    0H                                               03S0639
@DE00633 TM    FDRVTFLG,B'00100000'                             03S0639
         BNO   @DL00633                                         03S0639
*             ENTRYCT=RVTNUM-1;     /* NO. OF RVT ENTRIES - NCP ENTRY*/
         L     @14,ENTRYPTR                                     03S0640
         L     @14,SATRNRVT(,@14)                               03S0640
         LH    @09,RVTNUM(,@14)                                 03S0640
         BCTR  @09,0                                            03S0640
         STH   @09,ENTRYCT                                      03S0640
*             ENTRYRVT=SATRNRVT+LENGTH(RVTINDEX);/* SET PTR. IN R/D
*                                      OPCE TO SECOND ENTRY IN THE
*                                      RVT                           */
         AH    @14,@CH00131                                     03S0641
         ST    @14,ENTRYRVT(,ROPCE)                             03S0641
*             RFY                                               03S0642
*               IEDSATD BASED;                                  03S0642
*             RFY                                               03S0643
*               IEDRVTD BASED(ENTRYRVT);                        03S0643
*             ENTRYPTR=ENTRYRVT;    /* POINT TO SECOND ENTRY         */
         ST    @14,ENTRYPTR                                     02S0644
*             DO WHILE(ENTRYCT^=0); /* SET TO LOOP THROUGH RVT       */
         B     @DE00645                                         02S0645
@DL00645 DS    0H                                               02S0646
*               RFY                                             02S0646
*                 IEDRVTD BASED(ENTRYPTR);/* BASE FOR DURATION OF
*                                      LOOP                          */
*               RFY                                             02S0647
*                 IEDQTRM BASED(RPARM);/* BASE FOR DURATION OF LOOP  */
*               IF RVTINDEX^=0 THEN /* IF VALID INDEX                */
         L     @14,ENTRYPTR                                     02S0648
         LH    @14,RVTINDEX(,@14)                               02S0648
         LTR   @14,@14                                          02S0648
         BZ    @RF00648                                         02S0648
*                 DO;                                           02S0649
*                   RPARM=RVTINDEX; /* OBTAIN TTE ....               */
         LR    RPARM,@14                                        02S0650
*                   CALL IEDQTNT;   /* .... ADDR. OF RESOURCE        */
         L     @15,AVTRNMPT(,RAVT)                              02S0651
         BALR  @14,@15                                          02S0651
*                   IF TRMTYPE=TRMPSNA THEN/* IF PRE-SNA 3705   02S0652
*                                      TERMINAL                      */
*                                                               02S0652
         LR    @14,RPARM                                        02S0652
         SH    @14,@CH01700                                     02S0652
         CLI   TRMTYPE(@14),X'4F'                               02S0652
         BNE   @RF00652                                         02S0652
*                     /***********************************************/
*                     /*                                             */
*                     /* GO SEE IF AUTOCALL WITH VALID DIAL DIGITS   */
*                     /* SPECIFIED                                   */
*                     /*                                             */
*                     /***********************************************/
*                                                               02S0653
*                                                               03S0653
*                     /***********************************************/
*                     /*                                             */
*                     /* ---- THIS SEGMENT CHECKS IF COPY DSI CMND IS*/
*                     /* NEEDED FOR THIS TERM. -----                 */
*                     /*                                             */
*                     /***********************************************/
*                                                               03S0653
*                     IF TRMAUTOC=ON&TRMDDIG=ON THEN/* IF AUTOCALL
*                                      WITH DIAL DIGITS              */
         TM    TRMAUTOC(@14),B'00100000'                        03S0653
         BNO   @RF00653                                         03S0653
         TM    TRMDDIG(RPARM),B'01000000'                       03S0653
         BNO   @RF00653                                         03S0653
*                       DO;                                     03S0654
*                         RZERO=TRMDDIGA;/* CODE FOR IEDQTL          */
         LH    RZERO,@CH01535                                   03S0655
*                         CALL IEDQTL;/* GET ADDR. OF DIAL DIGITS
*                                      FIELD                         */
         L     @15,AVTDDFT(,RAVT)                               03S0656
         BALR  @14,@15                                          03S0656
*                         DEVDPADR=RTNCODE;/* SAVE ADDR.             */
         LR    DEVDPADR,RTNCODE                                 03S0657
*                         IF TTEDIALN=LENCTFLD&TTEDIALD(1:1)='0F'X THEN
         CLI   TTEDIALN(DEVDPADR),1                             03S0658
         BNE   @RF00658                                         03S0658
         CLI   TTEDIALD(DEVDPADR),X'0F'                         03S0658
         BE    @RT00658                                         03S0658
*                           ;       /* IF INVALID DIAL DATA THEN DO
*                                      NOTHING                       */
*                         ELSE                                  03S0660
*                           DO;                                 03S0660
@RF00658 DS    0H                                               03S0661
*                             ORGNOPCE->OCRESPCT=ORGNOPCE->OCRESPCT+1;
         LA    @14,1                                            03S0661
         SLR   @09,@09                                          03S0661
         ICM   @09,3,OCRESPCT(ORGNOPCE)                         03S0661
         ALR   @14,@09                                          03S0661
         STH   @14,OCRESPCT(,ORGNOPCE)                          03S0661
*                                   /* INCREMENT RESP. COUNT         */
*                             OCBUFNED=OCBUFNED+2;/* UPDATE UNITS
*                                      NEEDED BY 2                   */
         LA    @14,2                                            03S0662
         SLR   @09,@09                                          03S0662
         ICM   @09,3,OCBUFNED(ROPCE)                            03S0662
         ALR   @14,@09                                          03S0662
         STH   @14,OCBUFNED(,ROPCE)                             03S0662
*                           END;                                03S0663
*                       END;                                    03S0664
*                     ELSE                                      03S0665
*                       ;                                       03S0665
@RF00653 DS    0H                                               03S0666
*                   ELSE                                        02S0666
*                     ;                                         02S0666
@RF00652 DS    0H                                               02S0667
*                 END;                                          02S0667
*               ELSE                                            02S0668
*                 ;                                             02S0668
@RF00648 DS    0H                                               02S0669
*               ENTRYCT=ENTRYCT-1;  /* DECREMENT LOOP CTR.           */
@RC00648 LH    @14,ENTRYCT                                      02S0669
         BCTR  @14,0                                            02S0669
         STH   @14,ENTRYCT                                      02S0669
*               ENTRYPTR=ENTRYPTR+LENGTH(RVTINDEX);/* OBTAIN NEXT RVT
*                                      ENTRY                         */
         LA    @14,2                                            02S0670
         AL    @14,ENTRYPTR                                     02S0670
         ST    @14,ENTRYPTR                                     02S0670
*               RFY                                             02S0671
*                 IEDQTRM BASED(RTRM);/* RESTORE BASE                */
*               RFY                                             02S0672
*                 IEDRVTD BASED(ENTRYRVT);/* RESET BASE              */
*             END;                                              02S0673
@DE00645 ICM   @14,3,ENTRYCT                                    02S0673
         BNZ   @DL00645                                         02S0673
*           END;                                                02S0674
*       END;                                                    01S0675
@RC00618 DS    0H                                               01S0675
@DE00617 ICM   @14,3,OCRESPCT(ORGNOPCE)                         01S0675
         BZ    @DL00617                                         01S0675
*       IF OCREDRVE=ON THEN         /* IF CHKSTEP CREATED REDRIVE
*                                      OPCE                          */
         TM    OCREDRVE(ROPCE),B'00010000'                      01S0676
         BNO   @RF00676                                         01S0676
*         DO;                                                   01S0677
*                                                               01S0677
*           /*********************************************************/
*           /*                                                       */
*           /* A REDRIVE OPCE HAS BEEN CREATED FOR COPY DEVICE       */
*           /* SESSION INFORMATION COMMANDS. OBTAIN AS MANY UNITS AS */
*           /* ALLOWABLE UP TO THE NUMBER OF UNITS NEEDED TO SEND OUT*/
*           /* ALL COMMANDS AND THEN ENTER REDRIVE PROCESSING WHICH  */
*           /* BUILDS COPY DEVICE SESSION INFORMATION OPCE- PACKED RU*/
*           /* PAIRS FOR EACH RESOURCE.                              */
*           /*                                                       */
*           /*********************************************************/
*                                                               01S0678
*                                                               02S0678
*           /*********************************************************/
*           /*                                                       */
*           /* OBTAIN AS MANY BUFFER UNITS AS THE OPCE NEEDS UP TO   */
*           /* 50% OF TCAM'S UNITS. CHAIN THEM OFF OCUNIT FIELD OF   */
*           /* THE OPCE.                                             */
*           /*                                                       */
*           /*********************************************************/
*                                                               02S0678
*           UNITPTR=ROPCE;          /* SET TO POINT TO R/D OPCE      */
         LR    UNITPTR,ROPCE                                    02S0678
*           IF OPCADGOT+OCBUFNED>HALFUNIT THEN/* IF TOTAL OF UNITS
*                                      A/D HAS AND UNITS NEEDED 02S0679
*                                      EXCEEDS THE 50% LEVEL         */
         LH    @14,HALFUNIT                                     02S0679
         SLR   @11,@11                                          02S0679
         ICM   @11,3,OPCADGOT(ROPCAVT)                          02S0679
         SLR   @09,@09                                          02S0679
         ICM   @09,3,OCBUFNED(ROPCE)                            02S0679
         ALR   @09,@11                                          02S0679
         CR    @09,@14                                          02S0679
         BNH   @RF00679                                         02S0679
*             UNITSGET=HALFUNIT-OPCADGOT;/* GET UNITS UP TO 50% LEVEL*/
         SLR   @14,@11                                          02S0680
         STH   @14,UNITSGET                                     02S0680
*           ELSE                                                02S0681
*             UNITSGET=OCBUFNED;    /* GET AS MANY UNITS AS NEEDED   */
         B     @RC00679                                         02S0681
@RF00679 MVC   UNITSGET(2),OCBUFNED(ROPCE)                      02S0681
*           DO WHILE(UNITSGET^=0);  /* GO TO ALLOCBUF AS MANY TIMES
*                                      AS NECESSAY TO OBTAIN UNITS   */
@RC00679 B     @DE00682                                         02S0682
@DL00682 DS    0H                                               02S0683
*             IF UNITSGET>MAXUNTGT THEN/* IF FK IS TO GET MORE THAN
*                                      THE # OF UNITS ALLOCBUF CAN
*                                      GIVE PER CALL                 */
         LA    @14,255                                          02S0683
         CH    @14,UNITSGET                                     02S0683
         BNL   @RF00683                                         02S0683
*               RPARM=MAXUNTGT;     /* GET THE MAXIMUM               */
         LR    RPARM,@14                                        02S0684
*             ELSE                                              02S0685
*               RPARM=UNITSGET;     /* GET # TO GET                  */
         B     @RC00683                                         02S0685
@RF00683 LH    RPARM,UNITSGET                                   02S0685
*             CALL ALLOCBUF;        /* GET BUFFER UNITS              */
*                                                               02S0686
@RC00683 L     @15,OPCGETBF(,ROPCAVT)                           02S0686
         BALR  @14,@15                                          02S0686
*             /*******************************************************/
*             /*                                                     */
*             /* LINK UNITS JUST GOTTEN OFF OF OCLINK AT END OF      */
*             /* CURRENT CHAIN OF BUFFERS                            */
*             /*                                                     */
*             /*******************************************************/
*                                                               02S0687
*             RFY                                               02S0687
*               IEDQOPCE BASED(UNITPTR);                        02S0687
*             RFY                                               02S0688
*               TICFLD BASED(ADDR(OCUNIT));                     02S0688
*             DO WHILE(TIC=VALTIC); /* LOOP TO FIND END OF CURRENT
*                                      CHAIN                         */
         B     @DE00689                                         02S0689
@DL00689 DS    0H                                               02S0690
*               UNITPTR=OCUNIT;     /* POINT TO NEXT UNIT            */
         L     UNITPTR,OCUNIT(,UNITPTR)                         02S0690
*             END;                                              02S0691
@DE00689 TM    TIC+8(UNITPTR),B'00000011'                       02S0691
         BZ    @DL00689                                         02S0691
*             OCUNIT=RPARM;         /* POINT TO UNITS JUST GOTTEN    */
         ST    RPARM,OCUNIT(,UNITPTR)                           02S0692
*             RFY                                               02S0693
*               TICFLD BASED;                                   02S0693
*             RFY                                               02S0694
*               IEDQOPCE BASED(ROPCE);                          02S0694
*             UNITSGET=UNITSGET-RZERO;/* UPDATE # OF UNITS TO GET    */
         LH    @14,UNITSGET                                     02S0695
         SLR   @14,RZERO                                        02S0695
         STH   @14,UNITSGET                                     02S0695
*             OCBUFNED=OCBUFNED-RZERO;/* UPDATE # OF UNITS OPCE NEEDS*/
         SLR   @14,@14                                          02S0696
         ICM   @14,3,OCBUFNED(ROPCE)                            02S0696
         SLR   @14,RZERO                                        02S0696
         STH   @14,OCBUFNED(,ROPCE)                             02S0696
*             OCBUFGOT=OCBUFGOT+RZERO;/* UPDATE # OF UNITS OPCE HAS  */
         SLR   @14,@14                                          02S0697
         ICM   @14,3,OCBUFGOT(ROPCE)                            02S0697
         ALR   @14,RZERO                                        02S0697
         STH   @14,OCBUFGOT(,ROPCE)                             02S0697
*             OPCADGOT=OPCADGOT+RZERO;/* UPDATE OPCADGOT             */
         SLR   @14,@14                                          02S0698
         ICM   @14,3,OPCADGOT(ROPCAVT)                          02S0698
         ALR   @14,RZERO                                        02S0698
         STH   @14,OPCADGOT(,ROPCAVT)                           02S0698
*           END;                                                02S0699
@DE00682 ICM   @14,3,UNITSGET                                   02S0699
         BNZ   @DL00682                                         02S0699
*           CALL REDRIVE;                                       01S0700
         BAL   @14,REDRIVE                                      01S0700
*         END;                                                  01S0701
*       ELSE                                                    01S0702
*         ;                         /* EITHER OPCE IS A ACTLINK 01S0702
*                                      REQUEST OPCE OR IS A REPLACE
*                                      DSI COMMAND OPCE. IN EITHER
*                                      CASE, EXIT.                   */
@RF00676 DS    0H                                               01S0703
*     END;                                                      01S0703
*                                                               01S0703
*   /*****************************************************************/
*   /*                                                               */
*   /* EXIT CODE                                                     */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0704
*   IF OPCMODID=CNTLMOD THEN        /* IF XCTL IS TO IGC0010D        */
@RC00472 CLC   OPCMODID(2,ROPCAVT),CNTLMOD                      01S0704
         BNE   @RF00704                                         01S0704
*     RZERO=''B;                    /* CLEAR                         */
         SLR   RZERO,RZERO                                      01S0705
*   RPARM=ROPCAVT;                                              01S0706
@RF00704 LR    RPARM,ROPCAVT                                    01S0706
*   GEN REFS(ROPCAVT,OPCXCTL) EXIT;                             01S0707
*                                                               01S0707
         XCTL  SF=(E,OPCXCTL(ROPCAVT))
*   /*****************************************************************/
*   /*                                                               */
*   /* END OF MAIN PROCEDURE                                         */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0708
*                                                               01S0708
*/********************************************************************/
*/*              REDRIVE SUBROUTINE                                  */
*/********************************************************************/
*/*                                                                  */
*/* THIS ROUTINE PERFORMS THE REDRIVE PROCESSING:                    */
*/* 1. THE RVT IS SCANNED STARTING WITH THE ENTRY ADDR. (ENTRYRVT)   */
*/*    CONTAINED IN OCMODNME OF THE REDRIVE OPCE. ON THE FIRST PASS, */
*/*    THIS IS SET UP WITH THE 2ND ENTRY IN THE RVT.                 */
*/* 2. USING RVTINDEX, THE TTE IS OBTAINED AND THE TERMINAL IS       */
*/*    VERIFIED AS A BSC-SS DIAL TERM. WITH AUTOCALL SPECIFIED.      */
*/* 3. IF SO, A COPY DEVICE SESSION INFORMATION OPCE IS BUILT IN     */
*/*    THE UNIT POINTED TO BY OCUNIT OF THE REDRIVE OPCE. THE NEXT   */
*/*    UNIT HAS A PACKED RU BUILT IN IT. OCUNIT OF THE REDRIVE OPCE  */
*/*    IS SET TO THE UNIT FOLLOWING THE SECOND UNIT.                 */
*/* 4. THE OPCE=RU PAIR JUST BUILT IS PUT INTO THE CHAIN FOR THE     */
*/*    POST TO AVTOPCOB.                                             */
*/* 5. IF THERE ARE 2 OR MORE UNITS LEFT, THE RVT SCAN IS CONTINED   */
*/*    AND STEPS 2-4 REPEATED.                                       */
*/*                                                                  */
*/********************************************************************/
*                                                               01S0708
*REDRIVE:                                                       01S0708
*   PROC OPTIONS(RETREG,SAVE(14));                              01S0708
REDRIVE  ST    @14,@SA00002                                     01S0708
*   IF OCBUFGOT>=2 THEN             /* IF TWO OR MORE UNITS ATTACHED */
         CLC   OCBUFGOT(2,ROPCE),@CH00131                       01S0709
         BL    @RF00709                                         01S0709
*     DO;                                                       01S0710
*                                                               01S0710
*       /*************************************************************/
*       /*                                                           */
*       /* THERE ARE ENOUGH UNITS                                    */
*       /*                                                           */
*       /*************************************************************/
*                                                               01S0711
*       OPCAQWD1=OCUNIT;            /* SET FIRST WORD OF AQCTL PARM.
*                                      LIST TO POINT TO FIRST UNIT   */
         MVC   OPCAQWD1(4,ROPCAVT),OCUNIT(ROPCE)                01S0711
*       DO WHILE(OCBUFGOT>=2);      /* LOOP WHILE ENOUGH UNITS REMAIN*/
         B     @DE00712                                         01S0712
@DL00712 DS    0H                                               01S0713
*         RFY                                                   01S0713
*           IEDQOPCE BASED(UNITPTR);/* REDEFINE BASE FOR LOOP        */
*         UNITPTR=ROPCE->OCUNIT;    /* POINT TO FIRST UNIT           */
         L     UNITPTR,OCUNIT(,ROPCE)                           01S0714
*         ROPCE->OCUNIT=OCUNIT->OCUNIT;/* SET OCUNIT OF REDRIVE TO
*                                      POINT TO UNIT FOLLOWING UNIT
*                                      FOLLOWING UNIT POINTED TO BY
*                                      UNITPTR                       */
         L     @14,OCUNIT(,UNITPTR)                             01S0715
         L     @11,OCUNIT(,@14)                                 01S0715
         ST    @11,OCUNIT(,ROPCE)                               01S0715
*         OCELEM=ROPCE->OCUNIT;     /* MOVE LINK FOR POST TO AVTOPCOB*/
         ST    @11,OCELEM(,UNITPTR)                             01S0716
*         PRUTIC=PRUINTIC;          /* SET TIC FIELD OF RU INVALID   */
*                                                               01S0717
         MVC   PRUTIC(4,@14),@CB01345                           01S0717
*         /***********************************************************/
*         /*                                                         */
*         /* SET COMMON FIELDS IN OPCE                               */
*         /*                                                         */
*         /***********************************************************/
*                                                               01S0718
*         OCPTRSAV=ROPCE->OCPTRSAV; /* SET ADDR. OF ORIG. OPCE       */
         MVC   OCPTRSAV(4,UNITPTR),OCPTRSAV(ROPCE)              01S0718
*         OCSWITCH=OCOPYDSI;        /* SET COMMAND CODE              */
         MVI   OCSWITCH(UNITPTR),X'E3'                          01S0719
*         OCLINK=ADDR(AVTOPCOB);    /* SET QCB ADDR.                 */
         LA    @14,AVTOPCOB(,RAVT)                              01S0720
         ST    @14,OCLINK(,UNITPTR)                             01S0720
*         OCELMPRI=PRIMEDFG;        /* SET UP POST PRIORITY          */
         MVI   OCELMPRI(UNITPTR),X'DF'                          01S0721
*         OCPRIFLG=OPR02;           /* SET TO ROUTE TO RU DISPATCHER */
         MVI   OCPRIFLG(UNITPTR),X'08'                          01S0722
*         OCWTG=THISMOD;            /* SET TO RETURN TO THIS MOD.    */
         MVC   OCWTG(2,UNITPTR),THISMOD                         01S0723
*         OCACTREQ=ON;              /* ACTIVATE REQUEST              */
         OI    OCACTREQ(UNITPTR),B'00001000'                    01S0724
*         OPCAQWD2=UNITPTR;         /* 'END OF CHAIN' ADDR. IN AQCTL
*                                      PARM. LIST                    */
*                                                               01S0725
         ST    UNITPTR,OPCAQWD2(,ROPCAVT)                       01S0725
*         /***********************************************************/
*         /*                                                         */
*         /* SCAN RVT UNTIL THE TTE OF A DIAL TERM. WITH AUTOCALL AND*/
*         /* VALID DIAL DIGITS IS FOUND. FINISH BUILDING OPCE AND    */
*         /* PACKED RU.                                              */
*         /*                                                         */
*         /***********************************************************/
*                                                               01S0726
*                                                               02S0726
*         /***********************************************************/
*         /*                                                         */
*         /* ------- THIS SEGMENT BUILDS "COPY DEVICE SESSION        */
*         /* INFORMATION" OPCE- PACKED RU PAIRS. -----               */
*         /*                                                         */
*         /***********************************************************/
*                                                               02S0726
*         RFY                                                   02S0726
*           IEDQTRM BASED(RPARM);   /* SET TTE BASE                  */
*         RFY                                                   02S0727
*           IEDQOPCE BASED(ROPCE);  /* SET BASE AS REDRIVE OPCE      */
*         DO UNTIL(BUILTFLG=ON);    /* DO UNTIL CMND. BUILT          */
*                                                               02S0728
@DL00728 DS    0H                                               02S0729
*           /*********************************************************/
*           /*                                                       */
*           /* OBTAIN NEXT RVT ENTRY ADDR. FROM REDRIVE OPCE AND SET */
*           /* OCTRMTBL OF OPCE BEING BUILT TO TTCIN CONTAINED IN RVT*/
*           /* ENTRY.                                                */
*           /*                                                       */
*           /*********************************************************/
*                                                               02S0729
*           UNITPTR->OCTRMTBL=RVTINDEX;/* SET TTCIN FOR OPCE BEING
*                                      BUILT                         */
         L     @14,ENTRYRVT(,ROPCE)                             02S0729
         LH    @11,RVTINDEX(,@14)                               02S0729
         STH   @11,OCTRMTBL(,UNITPTR)                           02S0729
*           ENTRYRVT=ENTRYRVT+LENGTH(RVTINDEX);/* UPDATE RVT ENTRY
*                                      PTR. IN R/D OPCE TO POINT TO
*                                      NEXT ENTRY                    */
         AH    @14,@CH00131                                     02S0730
         ST    @14,ENTRYRVT(,ROPCE)                             02S0730
*           RPARM=UNITPTR->OCTRMTBL;/* OBTAIN ADDR. OF ....          */
         LR    RPARM,@11                                        02S0731
*           CALL IEDQTNT;           /* .... TTE                      */
         L     @15,AVTRNMPT(,RAVT)                              02S0732
         BALR  @14,@15                                          02S0732
*           IF TRMTYPE=TRMPSNA&TRMAUTOC=ON&TRMDDIG=ON THEN/* IF 02S0733
*                                      PRE-SNA TERM. WITH AUTOCALL
*                                      AND DIAL DIGITS               */
         LR    @14,RPARM                                        02S0733
         SH    @14,@CH01700                                     02S0733
         CLI   TRMTYPE(@14),X'4F'                               02S0733
         BNE   @RF00733                                         02S0733
         TM    TRMAUTOC(@14),B'00100000'                        02S0733
         BNO   @RF00733                                         02S0733
         TM    TRMDDIG(RPARM),B'01000000'                       02S0733
         BNO   @RF00733                                         02S0733
*             DO;                                               02S0734
*                                                               02S0734
*               /*****************************************************/
*               /*                                                   */
*               /* BUILD COPY DEVICE SESSION INFO. CMND. IF THIS     */
*               /* TERMINAL HAS VALID DIAL DIGITS.                   */
*               /*                                                   */
*               /*****************************************************/
*                                                               02S0735
*               RZERO=TRMDDIGA;     /* OBTAIN ADDR. OF ....          */
         LH    RZERO,@CH01535                                   02S0735
*               CALL IEDQTL;        /* .... DEVICE DEPENDENT FIELD   */
         L     @15,AVTDDFT(,RAVT)                               02S0736
         BALR  @14,@15                                          02S0736
*               DEVDPADR=RTNCODE;   /* COPY ADDR. OF FIELD           */
         LR    DEVDPADR,RTNCODE                                 02S0737
*               IF TTEDIALN=1&TTEDIALD(1:1)='0F'X THEN/* IF INVALID  */
         CLI   TTEDIALN(DEVDPADR),1                             02S0738
         BNE   @RF00738                                         02S0738
         CLI   TTEDIALD(DEVDPADR),X'0F'                         02S0738
         BNE   @RF00738                                         02S0738
*                 BUILTFLG=OFF;     /* CMND. NOT BUILT FOR THIS TERM.
*                                      - CHECK NEXT RVT ENTRY        */
         NI    BUILTFLG,B'11101111'                             02S0739
*               ELSE                                            02S0740
*                 DO;                                           02S0740
*                                                               02S0740
         B     @RC00738                                         02S0740
@RF00738 DS    0H                                               02S0741
*                   /*************************************************/
*                   /*                                               */
*                   /* BUILD PACKED RU                               */
*                   /*                                               */
*                   /*************************************************/
*                                                               02S0741
*                   RFY                                         02S0741
*                     IEDQOPCE BASED(UNITPTR);/* RESET BASE AS OPCE
*                                      BEING BUILT                   */
*                   PRUTTCIN=OCTRMTBL;/* SET RESOURCE TTCIN          */
         L     @14,OCUNIT(,UNITPTR)                             02S0742
         MVC   PRUTTCIN(2,@14),OCTRMTBL(UNITPTR)                02S0742
*                   PRUDATCT=LENGTH(IEDBDU);/* DATA LENGTH IS BDU
*                                      LENGTH                        */
         MVC   PRUDATCT(2,@14),@CH00071                         02S0743
*                   BDUCMND=CD0CTRL;/* CONTROL BDU                   */
         LA    @11,12                                           02S0744
         ALR   @11,@14                                          02S0744
         MVI   BDUCMND(@11),X'08'                               02S0744
*                   BDUMODIF=CD0CCDSI;/* COPY DSI MODIFIER           */
         MVI   BDUMODIF(@11),X'21'                              02S0745
*                   BDUHEADR=ON;    /* TURN ON HEADER FLAG   @YM06147*/
         OI    BDUHEADR(@11),B'01000000'                        02S0746
*                   PRURHTH(1:3)=TRHFID0;/* SET FID0 RH FLAGS        */
         SH    @14,@CH00045                                     02S0747
         MVC   PRURHTH(3,@14),@CB01378                          02S0747
*                   PRURHTH(4:4)=TTH0BYT0;/* SET FID0 TH FLAGS       */
         MVI   PRURHTH+3(@14),X'0C'                             02S0748
*                   BUILTFLG=ON;    /* RU BUILT, RETURN TO REDRIVE   */
         OI    BUILTFLG,B'00010000'                             02S0749
*                 END;                                          02S0750
*             END;                                              02S0751
*           ELSE                                                02S0752
*             BUILTFLG=OFF;         /* CMND. NOT BUILT FOR THIS TERM.
*                                      - CHECK NEXT RVT ENTRY        */
         B     @RC00733                                         02S0752
@RF00733 NI    BUILTFLG,B'11101111'                             02S0752
*         END;                                                  02S0753
@RC00733 DS    0H                                               02S0753
@DE00728 TM    BUILTFLG,B'00010000'                             02S0753
         BNO   @DL00728                                         02S0753
*         RFY                                                   02S0754
*           IEDQTRM BASED(RTRM);    /* RESET BASE FOR TTE            */
*         ROPCE->OCBUFGOT=ROPCE->OCBUFGOT-2;/* DECREMENT # UNITS GOT */
         SLR   @14,@14                                          01S0755
         ICM   @14,3,OCBUFGOT(ROPCE)                            01S0755
         BCTR  @14,0                                            01S0755
         BCTR  @14,0                                            01S0755
         STH   @14,OCBUFGOT(,ROPCE)                             01S0755
*         RFY                                                   01S0756
*           IEDQOPCE BASED(ROPCE);  /* RESET BASE AS REDRIVE OPCE    */
*       END;                                                    01S0757
*                                                               01S0757
@DE00712 CLC   OCBUFGOT(2,ROPCE),@CH00131                       01S0757
         BNL   @DL00712                                         01S0757
*       /*************************************************************/
*       /*                                                           */
*       /* POST OPCE'S TO AVTOPCOB                                   */
*       /*                                                           */
*       /*************************************************************/
*                                                               01S0758
*       OPCAQREQ=CHAINFLG;          /* FINISH BUILDING PARM. LIST BY
*                                      SETTING FLAG FOR CHAIN POST   */
         MVI   OPCAQREQ(ROPCAVT),X'B4'                          01S0758
*       RPARM=ADDR(OPCAQCTL);       /* SET REG 1 TO POINT TO PARM.
*                                      LIST                          */
         LA    RPARM,OPCAQCTL(,ROPCAVT)                         01S0759
*       SVC(102);                   /* POST IT                       */
         SVC   102                                              01S0760
*     END;                          /* END OF REDRIVE PROCESSING     */
*   ELSE                                                        01S0762
*     ;                             /* NOT ENOUGH UNITS, DON'T DO
*                                      REDRIVE                       */
*                                                               01S0762
@RF00709 DS    0H                                               01S0763
*   /*****************************************************************/
*   /*                                                               */
*   /* IF STILL MORE OPCE - RU'S TO BUILD, PLACE REDRIVE ELEMENT BACK*/
*   /* ON WAIT CHAIN                                                 */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0763
*   IF OCBUFNED=0 THEN              /* IF PROCESSING DONE            */
         ICM   @14,3,OCBUFNED(ROPCE)                            01S0763
         BNZ   @RF00763                                         01S0763
*     DO;                                                       01S0764
*       RPARM=ROPCE;                /* FREE REDRIVE ....             */
         LR    RPARM,ROPCE                                      01S0765
*       CALL FREEBUFF;              /* .... OPCE                     */
         L     @15,OPCFREBF(,ROPCAVT)                           01S0766
         BALR  @14,@15                                          01S0766
*       RZERO=1;                    /* DECREMENT OPCADGOT AND ....   */
         LA    RZERO,1                                          01S0767
*       CALL DECRCT;                /* .... INITIATE REDRIVE    01S0768
*                                      PROCESSING FOR ANOTHER REDRIVE
*                                      OPCE                          */
         L     @15,OPCDECR(,ROPCAVT)                            01S0768
         BALR  @14,@15                                          01S0768
*     END;                                                      01S0769
*   ELSE                            /* PROCESSING NOT FINISHED       */
*     DO;                                                       01S0770
         B     @RC00763                                         01S0770
@RF00763 DS    0H                                               01S0771
*       OCWTG=THISMOD;              /* SET TO RETURN                 */
         MVC   OCWTG(2,ROPCE),THISMOD                           01S0771
*       OCLINK=OPCBUFWT;            /* PLACE REDRIVE OPCE ....       */
         MVC   OCLINK(4,ROPCE),OPCBUFWT(ROPCAVT)                01S0772
*       OPCBUFWT=ROPCE;             /* .... BACK ON WAIT CHAIN       */
         ST    ROPCE,OPCBUFWT(,ROPCAVT)                         01S0773
*     END;                                                      01S0774
*                                                               01S0774
*   /*****************************************************************/
*   /*                                                               */
*   /* SET TO XCTL TO THE CONTROL MOD. - IGC0010D                    */
*   /*                                                               */
*   /*****************************************************************/
*                                                               01S0775
*   OPCMODID=CNTLMOD;                                           01S0775
@RC00763 MVC   OPCMODID(2,ROPCAVT),CNTLMOD                      01S0775
*   END REDRIVE;                                                01S0776
@EL00002 DS    0H                                               01S0776
@EF00002 DS    0H                                               01S0776
@ER00002 L     @14,@SA00002                                     01S0776
         BR    @14                                              01S0776
*   END IGCFQ10D                                                01S0777
*                                                               01S0777
*/* THE FOLLOWING INCLUDE STATEMENTS WERE FOUND IN THIS PROGRAM.     */
*/*%INCLUDE SYSLIB  (TAVTD   )                                       */
*/*%INCLUDE SYSLIB  (TBDUD   )                                       */
*/*%INCLUDE SYSLIB  (TCD0D   )                                       */
*/*%INCLUDE SYSLIB  (TDSID   )                                       */
*/*%INCLUDE SYSLIB  (TOPCAVTD)                                       */
*/*%INCLUDE SYSLIB  (TOPCED  )                                       */
*/*%INCLUDE SYSLIB  (TOPRED  )                                       */
*/*%INCLUDE SYSLIB  (TPLMVD  )                                       */
*/*%INCLUDE SYSLIB  (TPRIOR  )                                       */
*/*%INCLUDE SYSLIB  (TPRUD   )                                       */
*/*%INCLUDE SYSLIB  (TRHD    )                                       */
*/*%INCLUDE SYSLIB  (TRVTD   )                                       */
*/*%INCLUDE SYSLIB  (TSATD   )                                       */
*/*%INCLUDE SYSLIB  (TTHD    )                                       */
*/*%INCLUDE SYSLIB  (TTRMD   )                                       */
*/*%INCLUDE SYSUT5  (RSPPROC )                                       */
*/*%INCLUDE SYSUT5  (CPYDSIR )                                       */
*/*%INCLUDE SYSUT5  (GETDIAL )                                       */
*/*%INCLUDE SYSUT5  (BLDREPL )                                       */
*/*%INCLUDE SYSUT5  (CHKSTEP )                                       */
*/*%INCLUDE SYSUT5  (REFORMAT)                                       */
*/*%INCLUDE SYSUT5  (CPYDSICK)                                       */
*/*%INCLUDE SYSUT5  (GETBUFUT)                                       */
*/*%INCLUDE SYSUT5  (BLDOPCE )                                       */
*                                                               01S0777
*       ;                                                       01S0777
@DATA    DS    0H
@CH00060 DC    H'1'
@CH00131 DC    H'2'
@CH00331 DC    H'4'
@CH00071 DC    H'6'
@CH00045 DC    H'8'
@CH00239 DC    H'12'
@CH01700 DC    H'14'
@CH01535 DC    XL2'4000'
@SB01711 MVZ   DIGITS+1(0,@14),DIGITS(@14)
@SC01713 CLC   TTEDIALD(0,DEVDPADR),DIGITS(@14)
@SM01717 MVC   TTEDIALR(0,@14),TTEDIAL(DEVDPADR)
@DATD    DSECT
         DS    0F
@SA00002 DS    1F
IGCFQ10D CSECT
         DS    0F
@CF01345 DC    XL4'08000002'
@DATD    DSECT
         DS    0D
ENTRYPTR DS    A
DATASAVE DS    A
UNITSAVE DS    A
PTRSAVSV DS    A
UNITSV   DS    A
UNITSGET DS    H
HALFUNIT DS    H
DIALSP   DS    CL35
         DS    CL1
PARMLSP  DS    CL24
FLAGS    DS    BL1
         ORG   FLAGS
FREUTFLG DS    BL1
BLRPLFLG EQU   FLAGS+0
FDRVTFLG EQU   FLAGS+0
BUILTFLG EQU   FLAGS+0
         ORG   FLAGS+1
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
IGCFQ10D CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
         DS    0D
@CB01345 DC    X'08000002'
@CB01378 DC    X'0B8000'
CNTLMOD  DC    CL2'00'
RPNCPMOD DC    CL2'FJ'
RUDSPMOD DC    CL2'02'
THISMOD  DC    CL2'FQ'
         DS    CL1
ADPATCH  DC    XL100'0'
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
TRMTBLSV EQU   @06
UNITPTR  EQU   @06
ORGNOPCE EQU   @11
DEVDPADR EQU   @09
IEDQAPTR EQU   @04
ROPCAVT  EQU   @02
ROPCE    EQU   @03
IEDPLMVP EQU   @10
IEDQTPTR EQU   @08
RZERO    EQU   @00
RPARM    EQU   @01
RAVT     EQU   @04
RTRM     EQU   @08
RWRKAREA EQU   @10
RSAVE    EQU   @13
RRET     EQU   @14
RBRNCH   EQU   @15
RTNCODE  EQU   @15
RCL14SAV EQU   @11
IEDQAVTD EQU   0
AVTSAVEX EQU   IEDQAVTD+288
@NM00003 EQU   IEDQAVTD+388
AVTCKFLG EQU   @NM00003
AVTBASE  EQU   IEDQAVTD+412
AVTPKF   EQU   AVTBASE
AVTRNMPT EQU   IEDQAVTD+424
AVTNOLBF EQU   IEDQAVTD+454
AVTOSECB EQU   IEDQAVTD+492
AVTECB1  EQU   AVTOSECB
AVTHG02  EQU   IEDQAVTD+528
AVTDISP  EQU   IEDQAVTD+552
AVTHD    EQU   IEDQAVTD+556
AVTSCOPT EQU   AVTHD
AVTSAVTP EQU   IEDQAVTD+612
AVTSAVTF EQU   AVTSAVTP
AVTCKPEL EQU   IEDQAVTD+652
AVTCKRMV EQU   AVTCKPEL
AVTCKELF EQU   IEDQAVTD+680
AVTCKBYT EQU   IEDQAVTD+691
AVTHG01  EQU   IEDQAVTD+692
AVTCKLNK EQU   IEDQAVTD+696
AVTCRELE EQU   IEDQAVTD+708
AVTCCELE EQU   AVTCRELE
AVTCLRHI EQU   IEDQAVTD+716
AVTADBUF EQU   IEDQAVTD+720
AVTSYSER EQU   IEDQAVTD+728
AVTCKPQB EQU   IEDQAVTD+804
AVTCKPTB EQU   AVTCKPQB
AVTCKPEC EQU   AVTCKPQB+4
AVTCKPCC EQU   AVTCKPEC
AVTOPCQB EQU   IEDQAVTD+816
AVTOPCOB EQU   AVTOPCQB
AVTOPCEC EQU   AVTOPCQB+4
AVTOPCCC EQU   AVTOPCEC
AVTOLTQB EQU   IEDQAVTD+828
AVTCWFL1 EQU   IEDQAVTD+924
AVTCWFL2 EQU   IEDQAVTD+925
AVTSUBT  EQU   IEDQAVTD+948
AVTIOTR  EQU   IEDQAVTD+949
AVTKEYLE EQU   IEDQAVTD+1032
AVTBIT1  EQU   IEDQAVTD+1050
AVTBIT2  EQU   IEDQAVTD+1051
AVTBIT3  EQU   IEDQAVTD+1052
AVTDDFT  EQU   IEDQAVTD+1064
AVTBIT4  EQU   IEDQAVTD+1136
@NM00085 EQU   IEDQAVTD+1232
IEDNSVTD EQU   0
SAVTDIAG EQU   IEDNSVTD
SAVTDIAF EQU   SAVTDIAG
SAVTSAT  EQU   IEDNSVTD+80
SAVTLUSQ EQU   IEDNSVTD+88
SAVTMVBF EQU   IEDNSVTD+160
SAVTTCPU EQU   IEDNSVTD+238
SAVTZELM EQU   IEDNSVTD+270
SAVTRDRV EQU   IEDNSVTD+284
SAVTCKQB EQU   IEDNSVTD+300
SAVTCKTB EQU   SAVTCKQB
SAVTCKEC EQU   SAVTCKQB+4
SAVTCKCC EQU   SAVTCKEC
IEDBDU   EQU   0
BDUCMND  EQU   IEDBDU
BDUMODIF EQU   IEDBDU+1
BDUFNFLG EQU   IEDBDU+2
BDUHEADR EQU   BDUFNFLG
BDUBDUFG EQU   IEDBDU+3
BDURSP   EQU   IEDBDU+4
BDUSYRSP EQU   BDURSP
BDUEXRSP EQU   BDURSP+1
BDUEND   EQU   IEDBDU+6
IEDDSI1  EQU   0
DSITOTNM EQU   IEDDSI1
DSIPOLL  EQU   IEDDSI1+3
DSIPOLNM EQU   DSIPOLL
IEDDSI2  EQU   0
DSIADRNM EQU   IEDDSI2
IEDDSI3  EQU   0
DSINPTID EQU   IEDDSI3
IEDDSI4  EQU   0
DSIDIAL  EQU   IEDDSI4
DSIDLCNT EQU   DSIDIAL
IEDQOPCD EQU   0
OPCAVTPT EQU   IEDQOPCD+8
OPCCOPCE EQU   IEDQOPCD+12
OPCPGCK  EQU   IEDQOPCD+40
OPCSAVE  EQU   IEDQOPCD+56
OPCWORK  EQU   IEDQOPCD+140
OPCAQCTL EQU   IEDQOPCD+180
OPCXCTL  EQU   IEDQOPCD+204
OPCLDNME EQU   IEDQOPCD+212
OPCMODID EQU   OPCLDNME+3
OPCGETBF EQU   IEDQOPCD+276
OPCFREBF EQU   IEDQOPCD+280
OPCSPEC  EQU   IEDQOPCD+300
OPCADGOT EQU   IEDQOPCD+318
OPCBUFWT EQU   IEDQOPCD+348
OPCDECR  EQU   IEDQOPCD+352
OPCPWCOB EQU   IEDQOPCD+368
OPCPWQCB EQU   OPCPWCOB
OPCPWECB EQU   OPCPWCOB+4
IEDQOPCE EQU   0
OCLINK   EQU   IEDQOPCE
OCELEM   EQU   IEDQOPCE+4
OCELMPRI EQU   OCELEM
OCUNIT   EQU   IEDQOPCE+8
OCRUDEST EQU   OCUNIT
OCCKPKEY EQU   OCRUDEST
OCSCAN   EQU   OCCKPKEY
OCOPTCDE EQU   IEDQOPCE+12
OCPRIFLG EQU   OCOPTCDE
OCSWITCH EQU   IEDQOPCE+13
OCFLAG   EQU   IEDQOPCE+14
@NM00122 EQU   IEDQOPCE+16
OCDEST   EQU   @NM00122
OCREQVAL EQU   OCDEST+1
OCTRMTBL EQU   IEDQOPCE+20
OCLINENO EQU   IEDQOPCE+22
OCTIOT   EQU   OCLINENO
OCTRUNIT EQU   IEDQOPCE+24
OCRSID   EQU   OCTRUNIT
OCALSTAT EQU   OCRSID
OCREDRVE EQU   OCALSTAT
OCACTREQ EQU   OCALSTAT
OCPARM   EQU   IEDQOPCE+28
OCWTG    EQU   IEDQOPCE+30
OCBACKUP EQU   IEDQOPCE+32
OCBUFNED EQU   OCBACKUP
OCBUFGOT EQU   OCBACKUP+2
OCMODNME EQU   IEDQOPCE+40
OCIPLWA  EQU   OCMODNME
OCPTRSAV EQU   OCMODNME+4
OCCKDATA EQU   IEDQOPCE+48
OCRSTGTM EQU   OCCKDATA
IEDQOPCN EQU   0
OCLDNME  EQU   IEDQOPCN
OCLINTTE EQU   OCLDNME
OCRESPCT EQU   OCLINTTE
OCREQFLG EQU   OCLINTTE+2
OCPREFLG EQU   OCLINTTE+3
IEDOPRED EQU   0
OPRESAVE EQU   IEDOPRED+8
OPREFLG3 EQU   IEDOPRED+14
IEDPLMV  EQU   0
PLMVTU   EQU   IEDPLMV
PLMVTD   EQU   IEDPLMV+4
PLMVSU   EQU   IEDPLMV+8
PLMVSD   EQU   IEDPLMV+12
PLMVLNTH EQU   IEDPLMV+16
PLMVFLG1 EQU   IEDPLMV+18
PLMVSCTG EQU   PLMVFLG1
PLMVTCTG EQU   PLMVFLG1
IEDPRUQD EQU   0
PRUTTCIN EQU   IEDPRUQD
PRUDATCT EQU   IEDPRUQD+2
PRUTIC   EQU   IEDPRUQD+8
PRUNUNIT EQU   PRUTIC+1
PRUDATA  EQU   IEDPRUQD+12
IEDPRUND EQU   0
PRURHTH  EQU   IEDPRUND
PRURH    EQU   PRURHTH
PRURHFG0 EQU   PRURH
PRURHFG1 EQU   PRURH+1
PRURHFG2 EQU   PRURH+2
PRUTH    EQU   PRURHTH+3
PRUFIDN  EQU   PRUTH
IEDRH    EQU   0
TRHBYTE0 EQU   IEDRH
TRHBYTE1 EQU   IEDRH+1
TRHBYTE2 EQU   IEDRH+2
IEDRVTD  EQU   0
RVTNUM   EQU   IEDRVTD
RVTINDEX EQU   IEDRVTD+2
IEDSATD  EQU   0
SATRNRVT EQU   IEDSATD+4
IEDTH    EQU   0
TTHBYTE0 EQU   IEDTH
TTHSNF   EQU   IEDTH+6
TTHTAG   EQU   TTHSNF
TTHTAG1  EQU   TTHTAG
IEDQTRM  EQU   0
TRMSTATE EQU   IEDQTRM
TRMLOG   EQU   TRMSTATE
TRMINSEQ EQU   IEDQTRM+4
TLISTCNT EQU   TRMINSEQ
TRMOUTSQ EQU   IEDQTRM+6
TLISTEN  EQU   TRMOUTSQ
TRMDSORG EQU   TLISTEN
TRMALTD  EQU   IEDQTRM+8
TRMDEVFL EQU   IEDQTRM+10
TRMDDIG  EQU   TRMDEVFL
TRMSTAT  EQU   IEDQTRM+12
IEDNTRM  EQU   0
TRMBYTE4 EQU   IEDNTRM
TRMBYTE3 EQU   IEDNTRM+1
TRMBYTE2 EQU   IEDNTRM+2
TRMINPG  EQU   TRMBYTE2
TRMBYTE1 EQU   IEDNTRM+3
TRMSCPRQ EQU   TRMBYTE1
TRMAUTOC EQU   TRMBYTE1
TRMBYTE0 EQU   IEDNTRM+6
TRMSIBPT EQU   IEDNTRM+7
TRMTYPE  EQU   IEDNTRM+11
TTEDIAL  EQU   0
TTEDIALN EQU   TTEDIAL
TTEDIALD EQU   TTEDIAL+1
DIALDATA EQU   0
COUNT    EQU   DIALDATA
MAXIMUM  EQU   DIALDATA+1
TTEDIALR EQU   DIALDATA+2
ACTUAL   EQU   TTEDIALR
DIGITS   EQU   TTEDIALR+1
TICFLD   EQU   0
TIC      EQU   TICFLD+3
ALLOCBUF EQU   0
FREEBUFF EQU   0
IEDQTNT  EQU   0
IEDQTL   EQU   0
DECRCT   EQU   0
IEDMVBFR EQU   0
PROGRTNE EQU   0
RDSI1    EQU   PLMVSD
RDSI2    EQU   PLMVSD
RDSI3    EQU   PLMVSD
RDSI4    EQU   PLMVSD
OPCAQWD  EQU   OPCAQCTL
OPCAQWD1 EQU   OPCAQWD
OPCAQREQ EQU   OPCAQWD1
OPCAQWD2 EQU   OPCAQWD+4
OPCAQWD3 EQU   OPCAQWD+8
OCCKPKY1 EQU   OCCKPKEY
OCCKPTYP EQU   OCCKPKY1
OCICACTN EQU   OCMODNME
OCICDADR EQU   OCICACTN
OCICSW   EQU   OCICDADR+3
IEDPRUQP EQU   OCUNIT
ENTRYRVT EQU   OCMODNME
IEDQRVTP EQU   ENTRYRVT
IEDQSATP EQU   ENTRYPTR
TRMPRE1  EQU   TRMBYTE4
TRMNCP1  EQU   TRMBYTE4
TRMPRE   EQU   TRMBYTE3
TRMNCP   EQU   TRMBYTE3
TRMPU    EQU   TRMBYTE3
TRMLU    EQU   TRMBYTE3
TRMLINK  EQU   TRMBYTE3
ENTRYCT  EQU   UNITSGET
BDUTEXT  EQU   BDUEND
OCCIB    EQU   OCREQVAL
TRMOPT   EQU   IEDQTRM+20
         AGO   .@UNREFD                START UNREFERENCED COMPONENTS
@NM00160 EQU   TRMLINK
TRMLSTAT EQU   TRMLINK
TRMLINT  EQU   TRMLINK
TRMEPMOD EQU   TRMLINK
TRMLULOG EQU   TRMLU
TRMINERR EQU   TRMLU
TRMLUREQ EQU   TRMLU
TRMSESRQ EQU   TRMLU
TRMTDIFF EQU   TRMLU
TRMLUTM  EQU   TRMLU
TRMLUIT  EQU   TRMLU
TRMAUTO  EQU   TRMLU
TRMPCONT EQU   TRMPU
@NM00159 EQU   TRMPU
TRMNCONT EQU   TRMNCP
TRMQUCKN EQU   TRMNCP
TRMSLOWN EQU   TRMNCP
TRMSYGEN EQU   TRMNCP
TRMNCPCL EQU   TRMNCP
TRMIPLDM EQU   TRMNCP
TRMINOUT EQU   TRMPRE
TRMRDOUT EQU   TRMPRE
TRMNLOUT EQU   TRMPRE
TRMWROUT EQU   TRMPRE
TRMASNXI EQU   TRMPRE
TRMSTMM  EQU   TRMPRE
TRMCMODE EQU   TRMPRE
TRMSTPND EQU   TRMPRE
@NM00158 EQU   TRMNCP1
TRMINOP  EQU   TRMNCP1
TRMLYNCH EQU   TRMPRE1
TRMSPOUT EQU   TRMPRE1
TRMERLCK EQU   TRMPRE1
TRMQNPL  EQU   TRMPRE1
TRMSPACT EQU   TRMPRE1
TRMOCNI  EQU   TRMPRE1
TRMSESSN EQU   TRMPRE1
TRMCONT  EQU   TRMPRE1
OCICINAC EQU   OCICSW
@NM00128 EQU   OCICSW
OCICATST EQU   OCICDADR+1
OCICTYPE EQU   OCICDADR
@NM00127 EQU   OCCKPKY1
OCCKPENV EQU   OCCKPKY1
OCCKPRST EQU   OCCKPTYP
OCCKPNCP EQU   OCCKPTYP
OCCKPINC EQU   OCCKPTYP
OPCAQLST EQU   OPCAQWD3+1
OPCAQRQ3 EQU   OPCAQWD3
OPCAQSEC EQU   OPCAQWD2+1
OPCAQRQ2 EQU   OPCAQWD2
OPCAQFST EQU   OPCAQWD1+1
@NM00161 EQU   TICFLD
TRMSUBST EQU   IEDNTRM+12
TRMRLMCT EQU   IEDNTRM+10
TRMCOHTG EQU   TRMSIBPT+1
TRMGPCNT EQU   TRMSIBPT
TRMBUFRD EQU   TRMBYTE0
TRMSNA   EQU   TRMBYTE0
TRMGP    EQU   TRMBYTE0
TRMDIAL  EQU   TRMBYTE0
@NM00157 EQU   TRMBYTE0
TRMOUTPT EQU   TRMBYTE0
TRMINPUT EQU   TRMBYTE0
TRMUDEF  EQU   TRMBYTE0
TRMCOHRT EQU   IEDNTRM+4
TRMSTOTE EQU   TRMBYTE1
TRMCKPRN EQU   TRMBYTE1
TRMTSATN EQU   TRMBYTE1
TRMTRACE EQU   TRMBYTE1
TRMSWBCK EQU   TRMBYTE1
TRMINPTP EQU   TRMBYTE1
TRMWTNEG EQU   TRMSCPRQ
TRMWRBRK EQU   TRMBYTE2
TRMNOSND EQU   TRMBYTE2
TRMPREP  EQU   TRMBYTE2
TRMGPACT EQU   TRMBYTE2
TRMANDL  EQU   TRMBYTE2
TRMCLOSN EQU   TRMINPG
TRMREMB  EQU   TRMBYTE2
TRMRSACT EQU   TRMBYTE2
TRMOPTBL EQU   IEDQTRM+18
TRMOPNO  EQU   IEDQTRM+17
TRMCHCIN EQU   IEDQTRM+16
TRMSENSE EQU   TRMSTAT+3
TRMTEMPR EQU   TRMSTAT+2
TRMSIO   EQU   TRMSTAT
@NM00156 EQU   TRMDEVFL+1
TRMTPIN  EQU   TRMDEVFL+1
TRMNCPI  EQU   TRMDEVFL+1
TRMRNTRM EQU   TRMDEVFL+1
@NM00155 EQU   TRMDEVFL+1
TRMLMD   EQU   TRMDEVFL+1
TRMCONC  EQU   TRMDEVFL+1
TRMTSOB  EQU   TRMDEVFL
TRMBFDY  EQU   TRMDEVFL
TRMTBLK  EQU   TRMDEVFL
TRMSBLK  EQU   TRMDEVFL
TRMBLKS  EQU   TRMDEVFL
TRMADDC  EQU   TRMDEVFL
TRMBUFS  EQU   TRMDEVFL
TRMPRILK EQU   TRMALTD
TRMLGB   EQU   TRMDSORG
TRMUTERM EQU   TLISTCNT
TRMDESTQ EQU   IEDQTRM+1
TRMSCNYN EQU   TRMSTATE
TRMOPTFN EQU   TRMSTATE
TRMHELDN EQU   TRMSTATE
TRMACPTN EQU   TRMSTATE
TRMPREF  EQU   TRMSTATE
TRMPROC  EQU   TRMLOG
TRMLIST  EQU   TRMLOG
TRMLINE  EQU   TRMSTATE
TTHDCF   EQU   IEDTH+8
TTHTAG2  EQU   TTHTAG+1
@NM00154 EQU   TTHTAG1
TTHTAGS  EQU   TTHTAG1
TTHOAF   EQU   IEDTH+4
TTHDAF   EQU   IEDTH+2
TTHBYTE1 EQU   IEDTH+1
TTHEFI   EQU   TTHBYTE0
@NM00153 EQU   TTHBYTE0
TTHEBIU  EQU   TTHBYTE0
TTHBBIU  EQU   TTHBYTE0
TTHFTYPE EQU   TTHBYTE0
SATRNLCB EQU   IEDSATD
@NM00152 EQU   TRHBYTE2
@NM00151 EQU   TRHBYTE2
@NM00150 EQU   TRHBYTE2
TRHCSI   EQU   TRHBYTE2
@NM00149 EQU   TRHBYTE2
TRHCDI   EQU   TRHBYTE2
TRHEB    EQU   TRHBYTE2
TRHBB    EQU   TRHBYTE2
TRHPI    EQU   TRHBYTE1
@NM00148 EQU   TRHBYTE1
@NM00147 EQU   TRHBYTE1
@NM00146 EQU   TRHBYTE1
TRHER    EQU   TRHBYTE1
TRHDR2   EQU   TRHBYTE1
@NM00145 EQU   TRHBYTE1
TRHDR1   EQU   TRHBYTE1
TRHEC    EQU   TRHBYTE0
TRHBC    EQU   TRHBYTE0
TRHSDI   EQU   TRHBYTE0
TRHFI    EQU   TRHBYTE0
@NM00144 EQU   TRHBYTE0
TRHRUCAT EQU   TRHBYTE0
TRHTYPE  EQU   TRHBYTE0
@NM00143 EQU   IEDPRUND+4
PRUTHEFI EQU   PRUFIDN
PRUTHUSS EQU   PRUFIDN
PRUTHEIU EQU   PRUFIDN
PRUTHBIU EQU   PRUFIDN
PRUTHTYE EQU   PRUFIDN
@NM00142 EQU   PRURHFG2
PRURHCSI EQU   PRURHFG2
@NM00141 EQU   PRURHFG2
PRURHCDI EQU   PRURHFG2
PRURHEB  EQU   PRURHFG2
PRURHBB  EQU   PRURHFG2
PRURHPI  EQU   PRURHFG1
@NM00140 EQU   PRURHFG1
PRURHER  EQU   PRURHFG1
PRURHDR2 EQU   PRURHFG1
@NM00139 EQU   PRURHFG1
PRURHDR1 EQU   PRURHFG1
PRURHEC  EQU   PRURHFG0
PRURHBC  EQU   PRURHFG0
PRURHSDI EQU   PRURHFG0
PRURHFI  EQU   PRURHFG0
@NM00138 EQU   PRURHFG0
PRURUCAT EQU   PRURHFG0
PRURHTYP EQU   PRURHFG0
@NM00137 EQU   PRUTIC
@NM00136 EQU   IEDPRUQD+4
PLMVUNCA EQU   IEDPLMV+20
PLMVFLG2 EQU   IEDPLMV+19
@NM00135 EQU   PLMVFLG1
PLMVUNCF EQU   PLMVFLG1
@NM00134 EQU   OPREFLG3
OPREATCH EQU   OPREFLG3
@NM00133 EQU   OPREFLG3
OPREFLG2 EQU   IEDOPRED+13
OPREFLG1 EQU   IEDOPRED+12
OPRETIC  EQU   OPRESAVE
OPRELINK EQU   IEDOPRED+5
OPREPRI  EQU   IEDOPRED+4
OPREQCB  EQU   IEDOPRED+1
OPREKEY  EQU   IEDOPRED
@NM00132 EQU   OCLDNME+4
@NM00131 EQU   OCPREFLG
OCTOTEP  EQU   OCPREFLG
OCREPOST EQU   OCPREFLG
OCRSPSNT EQU   OCPREFLG
OCBFREQ  EQU   OCPREFLG
OCIDLE   EQU   OCREQFLG
OCFORCE  EQU   OCREQFLG
OCDCARD  EQU   OCREQFLG
OCPARTAL EQU   OCREQFLG
OCADNCP  EQU   OCREQFLG
@NM00130 EQU   OCREQFLG
@NM00129 EQU   OCREQFLG
OCFLUSHZ EQU   OCREQFLG
OCCKPTWA EQU   OCCKDATA+4
@NM00126 EQU   OCRSTGTM+2
OCCKDAT2 EQU   OCRSTGTM+1
OCCKDAT1 EQU   OCRSTGTM
OCPUADR  EQU   OCIPLWA+2
OCWTGSAV EQU   OCIPLWA
OCDVRDCT EQU   OCBACKUP+6
OCNCP    EQU   OCBACKUP+4
OCRESNUM EQU   OCPARM
OCSEQ    EQU   OCTRUNIT+2
@NM00125 EQU   OCRSID+1
OCNONE   EQU   OCALSTAT
OCSOME   EQU   OCALSTAT
OCALLFLG EQU   OCALSTAT
OCSEQIND EQU   OCALSTAT
@NM00124 EQU   OCALSTAT
OCRENTRD EQU   OCALSTAT
OCWTGB   EQU   OCTIOT
@NM00123 EQU   @NM00122+2
OCCONID  EQU   OCDEST
OCRLN    EQU   IEDQOPCE+15
OCRESP   EQU   OCFLAG
OCATTACH EQU   OCFLAG
OCSSCP   EQU   OCFLAG
OCOUTPUT EQU   OCFLAG
OCLINE   EQU   OCFLAG
OCMPP    EQU   OCFLAG
OCTOTE   EQU   OCFLAG
OCCONSOL EQU   OCFLAG
@NM00121 EQU   OCSWITCH
OCQUCKN  EQU   OCSWITCH
@NM00120 EQU   OCRUDEST+1
@NM00119 EQU   OCSCAN
OCNOTUCB EQU   OCSCAN
OCNONAME EQU   OCSCAN
OCALLRLN EQU   OCSCAN
OCDDNAME EQU   OCSCAN
OCDDNRLN EQU   OCSCAN
OCADDR   EQU   OCSCAN
OCELMPTR EQU   OCELEM+1
OPCBOTTM EQU   IEDQOPCD+1184
@NM00118 EQU   IEDQOPCD+1100
@NM00117 EQU   IEDQOPCD+948
@NM00116 EQU   IEDQOPCD+940
@NM00115 EQU   IEDQOPCD+380
@NM00114 EQU   OPCPWCOB+9
@NM00113 EQU   OPCPWCOB+8
@NM00112 EQU   OPCPWECB+1
OPCPWCCC EQU   OPCPWECB
OPCPWCHN EQU   OPCPWQCB+1
OPCPWVTO EQU   OPCPWQCB
OPCWAITV EQU   IEDQOPCD+364
OPCTOTCK EQU   IEDQOPCD+360
OPCAPXTL EQU   IEDQOPCD+356
OPCWRKSP EQU   IEDQOPCD+320
OPCRQCNT EQU   IEDQOPCD+316
OPPOLSTP EQU   IEDQOPCD+312
OPCCKCIB EQU   IEDQOPCD+308
OPCEND   EQU   IEDQOPCD+307
OPCSTCBS EQU   IEDQOPCD+306
OPCHNEND EQU   IEDQOPCD+302
OPCOQSW  EQU   IEDQOPCD+301
@NM00111 EQU   OPCSPEC
@NM00110 EQU   OPCSPEC
@NM00109 EQU   OPCSPEC
@NM00108 EQU   OPCSPEC
OPCFRMCA EQU   OPCSPEC
OPCRSTRT EQU   OPCSPEC
OPCPART  EQU   OPCSPEC
OPCALTD  EQU   OPCSPEC
OPCBFEND EQU   IEDQOPCD+296
OPCBFIRS EQU   IEDQOPCD+292
OPCAVBUF EQU   IEDQOPCD+290
OPCIPLCT EQU   IEDQOPCD+289
OPCCLNTS EQU   IEDQOPCD+288
OPCHA8   EQU   IEDQOPCD+286
OPCBFREQ EQU   IEDQOPCD+284
OPCNEXT  EQU   IEDQOPCD+272
OPCFMDFC EQU   IEDQOPCD+268
OPCSCNC  EQU   IEDQOPCD+264
OPCHORTG EQU   IEDQOPCD+260
OPCHORT  EQU   IEDQOPCD+256
OPCCKPTL EQU   IEDQOPCD+252
OPCCKPTF EQU   IEDQOPCD+248
OPCWAITA EQU   IEDQOPCD+244
OPCWAITR EQU   IEDQOPCD+240
OPCWAITP EQU   IEDQOPCD+236
OPCWAITO EQU   IEDQOPCD+232
OPCWAITN EQU   IEDQOPCD+228
OPCWAITL EQU   IEDQOPCD+224
OPCWAITC EQU   IEDQOPCD+220
@NM00107 EQU   OPCLDNME+5
@NM00106 EQU   OPCLDNME
OPCWAIT  EQU   IEDQOPCD+192
OPCCKERB EQU   IEDQOPCD+164
OPCBFERB EQU   IEDQOPCD+148
OPCFLAG2 EQU   IEDQOPCD+147
OPCFLAG1 EQU   IEDQOPCD+146
OPCWRKSZ EQU   IEDQOPCD+144
OPCRSAVE EQU   IEDQOPCD+132
OPCQCBAD EQU   IEDQOPCD+128
OPCTRMWA EQU   IEDQOPCD+52
OPCPSTWT EQU   IEDQOPCD+48
OPCTNTEA EQU   IEDQOPCD+44
OPCLCB   EQU   IEDQOPCD+36
@NM00105 EQU   IEDQOPCD+32
OPCIPLAD EQU   IEDQOPCD+28
OPCTOFLK EQU   IEDQOPCD+24
OPCOPTLK EQU   IEDQOPCD+20
OPCDCBLK EQU   IEDQOPCD+16
OPCDOUBL EQU   IEDQOPCD
DSIDLDIG EQU   DSIDIAL+3
DSISLACT EQU   DSIDIAL+2
DSIDLMAX EQU   DSIDIAL+1
DSIMODID EQU   IEDDSI3+3
DSISEQNO EQU   IEDDSI3+1
DSIADDR  EQU   IEDDSI2+1
DSIPOLCH EQU   DSIPOLL+1
DSINETAD EQU   IEDDSI1+1
BDUXGRPH EQU   BDUEXRSP
BDUXFINL EQU   BDUEXRSP
BDUXINIT EQU   BDUEXRSP
BDURESP  EQU   BDUSYRSP
BDUPHASE EQU   BDUSYRSP
BDUERROR EQU   BDUSYRSP
BDUXERLK EQU   BDUBDUFG
BDUALTAK EQU   BDUFNFLG
BDUNEGAK EQU   BDUFNFLG
BDUPOSAK EQU   BDUFNFLG
BDUTPTX  EQU   BDUFNFLG
BDUFRSTB EQU   BDUFNFLG
BDULEADG EQU   BDUFNFLG
BDUSTHDR EQU   BDUFNFLG
SAVTBITN EQU   IEDNSVTD+312
@NM00104 EQU   SAVTCKQB+8
@NM00103 EQU   SAVTCKEC+1
@NM00102 EQU   SAVTCKCC
SAVTCKPO EQU   SAVTCKCC
SAVTCKWA EQU   SAVTCKCC
SAVTCKCH EQU   SAVTCKTB+1
SAVTCKVT EQU   SAVTCKTB
@NM00101 EQU   IEDNSVTD+297
SAVTRDFG EQU   SAVTRDRV+12
@NM00100 EQU   SAVTRDRV+5
SAVTRDPY EQU   SAVTRDRV+4
SAVTRDQB EQU   SAVTRDRV+1
SAVTRDKY EQU   SAVTRDRV
SAVTNID  EQU   IEDNSVTD+280
SAVTDVAS EQU   IEDNSVTD+276
SAVTPLSZ EQU   IEDNSVTD+274
@NM00099 EQU   IEDNSVTD+273
SAVTSUBL EQU   IEDNSVTD+272
@NM00098 EQU   SAVTZELM+1
SAVTSUBM EQU   SAVTZELM
SAVTMHDX EQU   IEDNSVTD+268
SAVTNAT1 EQU   IEDNSVTD+266
SAVTSH20 EQU   IEDNSVTD+264
SAVTLCBS EQU   IEDNSVTD+260
SAVTRNMP EQU   IEDNSVTD+256
SAVTTNTX EQU   IEDNSVTD+252
SAVTNAX  EQU   IEDNSVTD+248
SAVTSUBV EQU   IEDNSVTD+247
SAVTSUBA EQU   IEDNSVTD+246
SAVTSIBC EQU   IEDNSVTD+244
SAVTBSM  EQU   IEDNSVTD+240
SAVTSCPT EQU   SAVTTCPU
SAVTRQTG EQU   IEDNSVTD+236
SAVTRQCH EQU   IEDNSVTD+232
SAVTMAND EQU   IEDNSVTD+228
SAVTSPLN EQU   IEDNSVTD+224
SAVTNADL EQU   IEDNSVTD+222
SAVTNATL EQU   IEDNSVTD+220
SAVTMHTB EQU   IEDNSVTD+216
SAVTSSMH EQU   IEDNSVTD+212
SAVTQRS  EQU   IEDNSVTD+208
SAVTRQIN EQU   IEDNSVTD+204
SAVTDFCO EQU   IEDNSVTD+200
SAVTSAO  EQU   IEDNSVTD+196
SAVTSARI EQU   IEDNSVTD+192
SAVTSAC  EQU   IEDNSVTD+188
SAVTSAI  EQU   IEDNSVTD+184
SAVTCSCI EQU   IEDNSVTD+180
SAVTSSRP EQU   IEDNSVTD+176
SAVTSSRQ EQU   IEDNSVTD+172
SAVTSCLU EQU   IEDNSVTD+168
SAVTXTRQ EQU   IEDNSVTD+164
@NM00097 EQU   IEDNSVTD+148
SAVTIPCQ EQU   IEDNSVTD+144
@NM00096 EQU   IEDNSVTD+136
SAVTXFMI EQU   IEDNSVTD+132
@NM00095 EQU   IEDNSVTD+124
SAVTXFMO EQU   IEDNSVTD+120
@NM00094 EQU   IEDNSVTD+116
SAVTSSSR EQU   IEDNSVTD+112
SAVTSCPQ EQU   IEDNSVTD+108
SAVTSLCB EQU   IEDNSVTD+104
SAVTLUSR EQU   IEDNSVTD+100
@NM00093 EQU   SAVTLUSQ+8
SAVTLUSP EQU   SAVTLUSQ+4
SAVTLUSB EQU   SAVTLUSQ
@NM00092 EQU   IEDNSVTD+84
SAVTNAT  EQU   IEDNSVTD+76
SAVTCLUP EQU   IEDNSVTD+72
SAVTPIUT EQU   IEDNSVTD+68
SAVTRNTA EQU   IEDNSVTD+64
SAVTDNIR EQU   IEDNSVTD+60
SAVTCNIR EQU   IEDNSVTD+56
SAVTFLDH EQU   IEDNSVTD+52
SAVTSRTN EQU   IEDNSVTD+48
SAVTSREQ EQU   IEDNSVTD+44
SAVTFAIL EQU   IEDNSVTD+42
SAVTSUSE EQU   IEDNSVTD+40
SAVTSIB  EQU   IEDNSVTD+36
SAVTPRTN EQU   IEDNSVTD+32
@NM00091 EQU   IEDNSVTD+28
SAVTWH20 EQU   IEDNSVTD+26
SAVTPWT  EQU   IEDNSVTD+24
SAVTPRTQ EQU   IEDNSVTD+20
SAVTPREQ EQU   IEDNSVTD+16
SAVTPH20 EQU   IEDNSVTD+14
SAVTPUSE EQU   IEDNSVTD+12
SAVTPLCB EQU   IEDNSVTD+8
SAVTPOOL EQU   IEDNSVTD+4
SAVTPRMT EQU   SAVTDIAF
SAVTVIRT EQU   SAVTDIAF
AVTCPBNO EQU   IEDQAVTD+1244
AVTHRESS EQU   IEDQAVTD+1243
@NM00090 EQU   IEDQAVTD+1242
@NM00089 EQU   IEDQAVTD+1241
@NM00088 EQU   IEDQAVTD+1240
@NM00087 EQU   IEDQAVTD+1237
@NM00086 EQU   IEDQAVTD+1236
AVTHRESE EQU   @NM00085
AVTRADDR EQU   IEDQAVTD+1228
AVTNADDR EQU   IEDQAVTD+1224
AVTHRESN EQU   IEDQAVTD+1220
AVTVOLRN EQU   IEDQAVTD+1216
AVTTOTNN EQU   IEDQAVTD+1212
AVTTRCYN EQU   IEDQAVTD+1208
AVTRCTRN EQU   IEDQAVTD+1204
AVTNOVON EQU   IEDQAVTD+1200
AVTADEBN EQU   IEDQAVTD+1196
AVTVOLRR EQU   IEDQAVTD+1192
AVTTOTNR EQU   IEDQAVTD+1188
AVTTRCYR EQU   IEDQAVTD+1184
AVTRCTRR EQU   IEDQAVTD+1180
AVTNOVOR EQU   IEDQAVTD+1176
AVTADEBR EQU   IEDQAVTD+1172
AVTLODPT EQU   IEDQAVTD+1168
AVTIOBN  EQU   IEDQAVTD+1164
AVTIOBR  EQU   IEDQAVTD+1160
AVTCPBPT EQU   IEDQAVTD+1156
AVTFCPB  EQU   IEDQAVTD+1152
@NM00084 EQU   IEDQAVTD+1148
AVTINCPQ EQU   IEDQAVTD+1144
@NM00083 EQU   IEDQAVTD+1140
@NM00082 EQU   IEDQAVTD+1137
@NM00081 EQU   AVTBIT4
@NM00080 EQU   AVTBIT4
@NM00079 EQU   AVTBIT4
@NM00078 EQU   AVTBIT4
@NM00077 EQU   AVTBIT4
@NM00076 EQU   AVTBIT4
@NM00075 EQU   AVTBIT4
AVTRUFTN EQU   AVTBIT4
@NM00074 EQU   IEDQAVTD+1132
AVTNOBFQ EQU   IEDQAVTD+1128
@NM00073 EQU   IEDQAVTD+1124
AVTDKENQ EQU   IEDQAVTD+1120
@NM00072 EQU   IEDQAVTD+1116
AVTDKAPQ EQU   IEDQAVTD+1112
AVTCOPY  EQU   IEDQAVTD+1108
AVTIA    EQU   IEDQAVTD+1104
AVTFL    EQU   IEDQAVTD+1100
@NM00071 EQU   IEDQAVTD+1096
AVTNCPBQ EQU   IEDQAVTD+1092
AVTTOTNC EQU   IEDQAVTD+1088
AVTCMAX  EQU   IEDQAVTD+1084
AVTCMIN  EQU   IEDQAVTD+1080
AVTHM02  EQU   IEDQAVTD+1076
AVTOPCIN EQU   IEDQAVTD+1074
AVTDCTLN EQU   IEDQAVTD+1072
AVTOPMSK EQU   IEDQAVTD+1068
AVTSTEAL EQU   IEDQAVTD+1060
AVTOPTN  EQU   IEDQAVTD+1056
AVTDSKCT EQU   IEDQAVTD+1054
AVTCKRST EQU   IEDQAVTD+1053
AVTSTAN  EQU   AVTBIT3
AVTSTACN EQU   AVTBIT3
AVTSTAIN EQU   AVTBIT3
AVTSTAYN EQU   AVTBIT3
AVTOLTBN EQU   AVTBIT3
AVTTSAB  EQU   AVTBIT3
AVTRFULN EQU   AVTBIT3
AVTRECVN EQU   AVTBIT3
@NM00070 EQU   AVTBIT2
@NM00069 EQU   AVTBIT2
AVTOPEIN EQU   AVTBIT2
AVTSTRTN EQU   AVTBIT2
AVTTOPOL EQU   AVTBIT2
AVTCOPYN EQU   AVTBIT2
AVTREUSN EQU   AVTBIT2
AVTEXTSC EQU   AVTBIT2
AVTDISKN EQU   AVTBIT1
AVTQUCKN EQU   AVTBIT1
AVTCLOSN EQU   AVTBIT1
AVTREADN EQU   AVTBIT1
AVTDLAYN EQU   AVTBIT1
AVTAQTAN EQU   AVTBIT1
AVTTSON  EQU   AVTBIT1
AVTAPLKN EQU   AVTBIT1
AVTDUMBR EQU   IEDQAVTD+1048
AVTDLQX  EQU   IEDQAVTD+1046
AVTINTLV EQU   IEDQAVTD+1044
AVTSMCNT EQU   IEDQAVTD+1042
AVTAVFCT EQU   IEDQAVTD+1040
AVTOPCON EQU   IEDQAVTD+1038
AVTOPCNT EQU   IEDQAVTD+1036
AVTLNCNT EQU   IEDQAVTD+1034
AVTHA16  EQU   IEDQAVTD+1030
AVTHA7   EQU   IEDQAVTD+1028
AVTHA4   EQU   IEDQAVTD+1026
AVTHA3   EQU   IEDQAVTD+1024
AVTHA2   EQU   IEDQAVTD+1022
AVTGETMS EQU   IEDQAVTD+1021
@NM00068 EQU   IEDQAVTD+1020
AVTGETMD EQU   IEDQAVTD+1016
AVTGETMN EQU   IEDQAVTD+1012
AVTCWTOT EQU   IEDQAVTD+1008
AVTCWINT EQU   IEDQAVTD+956
AVTDTRAP EQU   IEDQAVTD+952
@NM00067 EQU   IEDQAVTD+950
@NM00066 EQU   AVTIOTR
AVTIOTRH EQU   AVTIOTR
AVTIOTRE EQU   AVTIOTR
@NM00065 EQU   AVTSUBT
AVTSUBPT EQU   AVTSUBT
AVTSUBON EQU   AVTSUBT
AVTAFE30 EQU   IEDQAVTD+944
AVTAFE20 EQU   IEDQAVTD+940
AVTAFE10 EQU   IEDQAVTD+936
AVTCWEC2 EQU   IEDQAVTD+932
AVTCWPM2 EQU   IEDQAVTD+928
AVTCWTS2 EQU   IEDQAVTD+927
AVTCWTS1 EQU   IEDQAVTD+926
AVTCWCLD EQU   AVTCWFL2
AVTCWRAP EQU   AVTCWFL2
@NM00064 EQU   AVTCWFL2
@NM00063 EQU   AVTCWFL2
@NM00062 EQU   AVTCWFL2
@NM00061 EQU   AVTCWFL2
@NM00060 EQU   AVTCWFL2
AVTCWACT EQU   AVTCWFL2
@NM00059 EQU   AVTCWFL1
@NM00058 EQU   AVTCWFL1
@NM00057 EQU   AVTCWFL1
@NM00056 EQU   AVTCWFL1
@NM00055 EQU   AVTCWFL1
@NM00054 EQU   AVTCWFL1
@NM00053 EQU   AVTCWFL1
AVTCOMWN EQU   AVTCWFL1
AVTCWEC1 EQU   IEDQAVTD+920
AVTCWPM1 EQU   IEDQAVTD+916
AVTCAREA EQU   IEDQAVTD+912
AVTFZERO EQU   IEDQAVTD+908
AVTCADDR EQU   IEDQAVTD+904
AVTCOREC EQU   IEDQAVTD+900
@NM00052 EQU   IEDQAVTD+892
AVTCPBCB EQU   IEDQAVTD+888
@NM00051 EQU   IEDQAVTD+880
AVTDSIOB EQU   IEDQAVTD+876
@NM00050 EQU   IEDQAVTD+868
AVTCPRMB EQU   IEDQAVTD+864
@NM00049 EQU   IEDQAVTD+856
AVTCLOSB EQU   IEDQAVTD+852
@NM00048 EQU   IEDQAVTD+844
AVTACTIB EQU   IEDQAVTD+840
@NM00047 EQU   IEDQAVTD+836
AVTOLTEB EQU   IEDQAVTD+832
AVTOLTCH EQU   AVTOLTQB+1
AVTOLTVT EQU   AVTOLTQB
@NM00046 EQU   AVTOPCQB+8
@NM00045 EQU   AVTOPCEC+1
@NM00044 EQU   AVTOPCCC
AVTOPCPO EQU   AVTOPCCC
AVTOPCWA EQU   AVTOPCCC
AVTOPCCH EQU   AVTOPCOB+1
AVTOPCVT EQU   AVTOPCOB
@NM00043 EQU   AVTCKPQB+9
AVTCKPTS EQU   AVTCKPQB+8
@NM00042 EQU   AVTCKPEC+1
@NM00041 EQU   AVTCKPCC
AVTCKPPO EQU   AVTCKPCC
AVTCKPWA EQU   AVTCKPCC
AVTCKPCH EQU   AVTCKPTB+1
AVTCKPVT EQU   AVTCKPTB
@NM00040 EQU   IEDQAVTD+796
AVTBFRTB EQU   IEDQAVTD+792
@NM00039 EQU   IEDQAVTD+784
AVTBFREB EQU   IEDQAVTD+780
AVTTIMQ  EQU   IEDQAVTD+776
@NM00038 EQU   IEDQAVTD+772
AVTIMQPS EQU   IEDQAVTD+768
AVTINOUT EQU   IEDQAVTD+766
AVTREFTM EQU   IEDQAVTD+764
@NM00037 EQU   IEDQAVTD+752
AVTDELYB EQU   IEDQAVTD+748
AVTOCQPT EQU   IEDQAVTD+744
AVTTSOPT EQU   IEDQAVTD+740
AVTSUPPT EQU   IEDQAVTD+736
AVTCBQCB EQU   IEDQAVTD+732
AVTMSGS  EQU   IEDQAVTD+729
@NM00036 EQU   AVTSYSER
@NM00035 EQU   AVTSYSER
@NM00034 EQU   AVTSYSER
@NM00033 EQU   AVTSYSER
@NM00032 EQU   AVTSYSER
@NM00031 EQU   AVTSYSER
AVTCMAXN EQU   AVTSYSER
AVTCMINN EQU   AVTSYSER
AVT2260L EQU   IEDQAVTD+724
AVTABEPL EQU   AVTADBUF
AVTHFF   EQU   AVTCLRHI+2
@NM00030 EQU   AVTCLRHI
AVTCCLNK EQU   AVTCRELE+5
AVTCCPRI EQU   AVTCRELE+4
AVTCCQCB EQU   AVTCCELE+1
AVTCCKEY EQU   AVTCCELE
AVTDELAD EQU   IEDQAVTD+704
AVTDELEM EQU   IEDQAVTD+700
AVTBSX   EQU   AVTCKLNK
AVTOPETR EQU   AVTHG01
@NM00029 EQU   AVTCKBYT
AVTCKONQ EQU   AVTCKBYT
@NM00028 EQU   AVTCKBYT
@NM00027 EQU   AVTCKBYT
@NM00026 EQU   AVTCKBYT
@NM00025 EQU   AVTCKBYT
@NM00024 EQU   AVTCKBYT
@NM00023 EQU   AVTCKBYT
AVTOPERT EQU   IEDQAVTD+690
AVTOPXCL EQU   IEDQAVTD+688
AVTOPERL EQU   IEDQAVTD+687
@NM00022 EQU   IEDQAVTD+686
AVTCKTIM EQU   IEDQAVTD+684
AVTCKELV EQU   IEDQAVTD+682
AVTCPRCD EQU   IEDQAVTD+681
AVTWARMN EQU   AVTCKELF
AVTCRTLN EQU   AVTCKELF
AVTCPIPN EQU   AVTCKELF
AVTCCLCN EQU   AVTCKELF
AVTCINCN EQU   AVTCKELF
@NM00021 EQU   AVTCKELF
AVTCMCPN EQU   AVTCKELF
AVTCRDYN EQU   AVTCKELF
AVTCKQAD EQU   IEDQAVTD+677
AVTSCBSZ EQU   IEDQAVTD+676
@NM00020 EQU   IEDQAVTD+672
AVTCKELE EQU   IEDQAVTD+668
@NM00019 EQU   AVTCKPEL+8
AVTCKRLK EQU   AVTCKPEL+5
AVTCKRPR EQU   AVTCKPEL+4
AVTCKRMQ EQU   AVTCKRMV+1
AVTCKRKY EQU   AVTCKRMV
AVTHK    EQU   IEDQAVTD+648
AVTHI    EQU   IEDQAVTD+644
AVTIOT   EQU   IEDQAVTD+640
AVTNX    EQU   IEDQAVTD+636
AVTTONE  EQU   IEDQAVTD+632
AVTA3TL  EQU   IEDQAVTD+628
AVTDMECB EQU   IEDQAVTD+624
AVTABEND EQU   IEDQAVTD+618
AVTPLCBN EQU   IEDQAVTD+616
@NM00018 EQU   AVTSAVTP+1
@NM00017 EQU   AVTSAVTF
AVTSNA   EQU   AVTSAVTF
AVTONSNA EQU   AVTSAVTF
AVTVTMCP EQU   AVTSAVTF
@NM00016 EQU   IEDQAVTD+608
AVTCMBSS EQU   IEDQAVTD+604
AVTRCV   EQU   IEDQAVTD+600
AVTSEND  EQU   IEDQAVTD+596
AVTCSCH  EQU   IEDQAVTD+592
AVTQ1    EQU   IEDQAVTD+588
AVTE7    EQU   IEDQAVTD+584
AVTHB    EQU   IEDQAVTD+580
AVTR1    EQU   IEDQAVTD+576
AVTBZ    EQU   IEDQAVTD+572
AVTEZ    EQU   IEDQAVTD+568
AVTEC    EQU   IEDQAVTD+564
AVTEW    EQU   IEDQAVTD+560
AVTNDIAL EQU   AVTSCOPT
AVTN2741 EQU   AVTSCOPT
AVTCONCO EQU   AVTSCOPT
AVTCONC  EQU   AVTSCOPT
AVTCMBUF EQU   AVTSCOPT
AVTAPDMP EQU   AVTSCOPT
@NM00015 EQU   AVTSCOPT
AVTHA    EQU   AVTDISP
AVTEA    EQU   IEDQAVTD+548
AVTAX    EQU   IEDQAVTD+544
AVTA3    EQU   IEDQAVTD+540
AVTGD    EQU   IEDQAVTD+536
AVTAL    EQU   IEDQAVTD+532
AVTOLTST EQU   AVTHG02
AVTE8    EQU   IEDQAVTD+524
AVTUI    EQU   IEDQAVTD+520
AVTCOMPT EQU   IEDQAVTD+516
AVTCRSRF EQU   IEDQAVTD+512
@NM00014 EQU   IEDQAVTD+508
AVTKA02  EQU   IEDQAVTD+504
AVTOPTPT EQU   IEDQAVTD+500
AVTPCBPT EQU   IEDQAVTD+496
@NM00013 EQU   AVTECB1
AVTCOMP  EQU   AVTECB1
@NM00012 EQU   AVTECB1
AVTOPECA EQU   IEDQAVTD+488
AVTOLECA EQU   IEDQAVTD+484
AVTCKECA EQU   IEDQAVTD+480
AVTCWECA EQU   IEDQAVTD+476
AVTCWTCB EQU   IEDQAVTD+472
AVTOLTCB EQU   IEDQAVTD+468
AVTOCTCB EQU   IEDQAVTD+464
AVTCKTCB EQU   IEDQAVTD+460
AVTAS    EQU   IEDQAVTD+456
AVTNCKPR EQU   IEDQAVTD+453
AVTCIB   EQU   IEDQAVTD+452
AVTSPLPT EQU   IEDQAVTD+448
AVTMVBFR EQU   IEDQAVTD+444
AVTSBTA  EQU   IEDQAVTD+440
AVTRARTN EQU   IEDQAVTD+436
AVTBSCAN EQU   IEDQAVTD+432
AVTRDYA  EQU   IEDQAVTD+428
AVTDISTR EQU   IEDQAVTD+420
AVTPARM3 EQU   IEDQAVTD+416
@NM00011 EQU   AVTPKF
@NM00010 EQU   AVTPKF
@NM00009 EQU   AVTPKF
AVTFTCHF EQU   AVTPKF
@NM00008 EQU   AVTPKF
@NM00007 EQU   AVTPKF
@NM00006 EQU   AVTPKF
@NM00005 EQU   AVTPKF
AVTPARM  EQU   IEDQAVTD+408
AVTEXS2A EQU   IEDQAVTD+402
AVTEXA2S EQU   IEDQAVTD+396
AVTOCGET EQU   IEDQAVTD+392
AVTCKAVT EQU   @NM00003+1
@NM00004 EQU   AVTCKFLG
AVTCKHLT EQU   AVTCKFLG
AVTCKREQ EQU   AVTCKFLG
AVTCKENV EQU   AVTCKFLG
AVTCKNAC EQU   AVTCKFLG
AVTCKTAC EQU   AVTCKFLG
@NM00002 EQU   IEDQAVTD+384
AVTREADD EQU   IEDQAVTD+380
AVTREADY EQU   IEDQAVTD+376
AVTRACE  EQU   IEDQAVTD+372
AVTTCB   EQU   IEDQAVTD+368
AVTPASWD EQU   IEDQAVTD+360
AVTCTLCH EQU   IEDQAVTD+352
AVTDOUBL EQU   IEDQAVTD+344
AVTDOUBX EQU   IEDQAVTD+336
AVTDPARM EQU   IEDQAVTD+332
AVTCSTCS EQU   IEDQAVTD+328
AVTDLQ   EQU   AVTSAVEX+32
@NM00001 EQU   AVTSAVEX
AVTSAVE4 EQU   IEDQAVTD+216
AVTSAVE3 EQU   IEDQAVTD+144
AVTSAVE2 EQU   IEDQAVTD+72
AVTSAVE1 EQU   IEDQAVTD
.@UNREFD ANOP                          END UNREFERENCED COMPONENTS
@RC00517 EQU   @RC00482
@RC00601 EQU   @RC00600
@RC00635 EQU   @RC00634
@RC00652 EQU   @RC00648
@RC00738 EQU   @RC00733
@RC00521 EQU   @RC00517
@RC00519 EQU   @RC00517
@RC00653 EQU   @RC00652
@RC00527 EQU   @RC00521
@RT00658 EQU   @RC00653
@ENDDATA EQU   *
         END   IGCFQ10D,(C'PLS1746',0701,77112)
