         TITLE 'AMAPTF01 - PTF APPLICATION FUNCTION SERVICE PROGRAM'
*    GENERATE (EJECT);
         EJECT
*
* AMAPTF01:
*    PROC;
         LCLA  &T,&SPN                                            0002
.@001    ANOP                                                     0002
AMAPTF01 CSECT ,                                                  0002
         STM   @E,@C,12(@D)                                       0002
         BALR  @B,0                                               0002
@PSTART  DS    0H                                                 0002
         USING @PSTART+00000,@B                                   0002
         ST    @D,@SAV001+4                                       0002
         LA    @F,@SAV001                                         0002
         ST    @F,8(0,@D)                                         0002
         LR    @D,@F                                              0002
*    DECLARE
*          AMASPUT2 LABEL;
*    DECLARE
*          AMARDOBJ LABEL GENERATED;
*    DECLARE
*          SYSUTDCB LABEL GENERATED;
*    DECLARE
*          AMACLOSE LABEL GENERATED;
*    DECLARE
*          AMAIDCHK LABEL;           /* S21016                        *
*    DECLARE
*          AMAIDBL LABEL;            /* S21016                        *
*    DECLARE
*          OPENREG REGISTER(3) PTR(31); /* DCB ADDRESS REGISTER       *
*    DECLARE
*          OPENBIT BIT(1) INIT('0'B); /* FIRST TIME ENTRY FLAG        *
*    DECLARE
*          RETCODE REGISTER(15);
*    DECLARE
*          LSTPTR REGISTER(1) PTR(31); /* PARAMETER LIST REGISTER     *
*    DECLARE
*          LSTPTRSV REGISTER(5) PTR(31); /* PARAMETER LIST POINTER
*                                       M3990                         *
*    DECLARE
*          I REGISTER(6) PTR(31);    /* COLUMN COUNTER S21995         *
*    RESTRICT (LSTPTR,OPENREG,LSTPTRSV,I); /* S21995                  *
*    DECLARE
*          1 PRMLST BASED(LSTPTRSV), /* PTFLE PARAMETER LIST M3990    *
*            2 BRFIELD PTR(8),       /* INDEX FOR FUNCTIONAL BRANCH   *
*            2 IDENTCON PTR(8),      /* IDENTIFY CONT. SWITCH M0861   *
*            2 RETCDE PTR(8),        /* RETURN CODE SAVE AREA   A48711*
*            2 COMSW PTR(8),         /* SWITCHES                Y01045*
*            2 MODSTORE PTR(31),     /* ADDRESS OF MATCHED MOD NAME   *
*            2 OVTABADR PTR(31),     /* ADDRESS OF OVERLAY TABLE      *
*            2 PTF01 PTR(31),        /* ENTRY POINT OF AMAPTF01       *
*            2 PTF02 PTR(31),        /* ENTRY POINT OF AMAPTF02       *
*            2 PCHAREA PTR(31),      /* STAGE 1 INPUT BUFFER          *
*            2 MODAREA PTR(31),      /* CONTROL STMNT INPUT BUFFER    *
*            2 OUTFDCB PTR(31),      /* ADDR OF OUTFDCB               *
*            2 SYNADEXT PTR(31),     /* ADDR OF AMAPTFLE SYNAD RTN    *
*            2 MSGAREA PTR(31),      /* ADDR OF ERROR MESSAGE BUFFER  *
*            2 PRINTDCB PTR(31),     /* ADDR OF PRINTDCB IN AMAPTFLE  *
*            2 SELNAME PTR(31),      /* ADDR OF SYSTEM MODULE NAME    *
*                                    /* ON THE SELECT STATEMENT       *
*            2 SSISAVE PTR(31),      /* ADDR OF MATCHED MODULE        *
*                                    /* IN MODULE NAME TABLE          *
*            2 MESSAGE2 PTR(31),     /* ADDR OF MESSAGE WRITE RTN     *
*            2 MODTBL PTR(31),       /* ADDR OF MODULE NAME TABLE     *
*            2 SSITABLE PTR(31),     /* ADDR OF SSI TABLE             *
*            2 PARMPTR PTR(31),      /* ADDR OF EXEC PARM FIELD       *
*            2 FILCLOSE PTR(31);     /* ADDR OF FILCLOSE RTN          *
*    DECLARE
*          AMAPTF02 ENTRY BASED(PTF02);
*    DECLARE
*          DDMSGOUT CHAR(4) INIT('OUTF'); /* OUTF DDNAME              *
*    DECLARE
*          DDMSG CHAR(6) INIT('SYSUT2'); /* SYSUT2 DDNAME             *
*    DECLARE
*          DDSYSL CHAR(7) INIT('SYSLMOD'); /* SYSLMOD DDNAME M4012    *
*    DECLARE
*          MODSTRBF CHAR(8) BASED(MODSTORE); /* MODULE NAME SAVE      *
*                                    /* FOR TABLE COMPARE             *
*    DECLARE
*          NAMMATCH PTR(8) INIT(0);  /* MODULE NAME MATCH FOR SYSUT2  *
*
* /********************************************************************
* /* THE FOLLOWING IS A BRANCH TABLE CONSISTING OF SIX SUBROUTINE     *
* /* ADDRESSES.  ONE OF THESE ADDRESSES INDEXED BY BRFIELD CAUSES     *
* /* ENTRY INTO THAT SUBROUTINE.                                      *
*
*    DECLARE
*          BRTABLE(6) PTR(31)
*                INIT(ADDR(AMAOPEN),ADDR(AMASPOBJ),
*          ADDR(AMALINK),ADDR(AMACLOSE),ADDR(AMASPS),
*          ADDR(AMALEPRM));           /*                        Y01045*
*    DECLARE
*          MSGBUF CHAR(121);         /* A MESSAGE BUFFER              *
*    DECLARE
*          UT2OUT CHAR(80);          /* INPUT BUFFER FOR SYSUT2       *
*    DECLARE
*          DUMFIELD CHAR(80) BASED(MODAREA); /* MODAREA BUFF IN PTFLE *
*    DECLARE
*          TTRZ CHAR(4) INIT(' ') BDY(WORD); /* NOTE ADDRESS          *
*    DECLARE
*          ENDPARM CHAR(1);          /* END OF EXEC CARD PARAMETERS
*                                       M4011                         *
*    DECLARE
*          BLDLFLD CHAR(72) BDY(HWORD) INIT(' '); /* BLDL PARAMETER
*                                       LIST                          *
*                                    /* FOR PTF02 AND OPT LIST FOR
*                                       L.E. M3999                    *
*    DECLARE
*          PTF02ADR PTR(31);         /* ADDR OF AMAPTF02              *
*
* /********************************************************************
* /*    THE FOLLOWING IS A NAME CARD THAT AMAPTF01 MUST GENERATE      *
* /*    TO BUILD A SYSLIN DATA SET FOR A MODULE THAT WAS              *
* /*    ORIGINALLY COPIED INTO THE SYSTEM AT SYSGEN TIME.             *
*
*    DECLARE
*          1 NAMECARD,
*            2 NME CHAR(10) INIT('     NAME '),
*            2 MDN CHAR(11);         /* MODULE NAME WILL BE MOVED IN
*                                       M4000                         *
*    DECLARE
*          REP CHAR(3) INIT('(R)');  /* M4000                         *
*    DECLARE
*          NEWNAME CHAR(1) INIT('00'X); /* MODULE NAME SWITCH M4014   *
*    DECLARE
*          IDFOUND CHAR(1) INIT('80'X); /* IDENTIFY FOUND SW S21016   *
*    DECLARE
*          1 ALIASCD,                /* ALIAS CARD FOR M4014          *
*            2 * CHAR(7) INIT(' ALIAS '), /* COPIED AT SYSGEN M4014   *
*            2 ALIASNM CHAR(8);      /* WITH ALIASES M4014            *
*    DECLARE
*          1 SSICARD,
*            2 SETSSI CHAR(12) INIT('     SETSSI '),
*            2 SSIINFO CHAR(8);      /* SETSSI CARD FOR COPIED MODULES*
*    DECLARE
*          SELBUF CHAR(8) BASED(SELNAME); /* MOD NAME ON SELECT
*                                       STATEMNT                      *
*    DECLARE
*          1 PRMFIELD BASED(PARMPTR),
*            2 PARMLEN PTR(16),      /* LENGTH OF PARAMETER LIST      *
*            2 PARM CHAR(100);       /* TEXT OF PARAMETER             *
*    DECLARE
*          LKEDNAME CHAR(8) INIT(' '); /* NAME OF LINKAGE EDITOR      *
*
* /********************************************************************
* /*    THE FOLLOWING IS MESSAGE AMA005I                              *
* /********************************************************************
*
*    DECLARE
*          AMA005I CHAR(54) INIT
*          ('AMA005I  INVALID PARAMETER SPECIFIED ON EXEC STATEMENT');
*
* /********************************************************************
* /*    THE FOLLOWING IS MESSAGE AMA006I                              *
* /********************************************************************
*
*    DECLARE
*          1 AMA006I,
*            2 * CHAR(21) INIT('AMA006I  LOAD MODULE '),
*            2 CCCCCCCC CHAR(8),     /* MOD NAME                      *
*            2 * CHAR(24) INIT(' NOT UPDATED WITH PTF - '),
*            2 NN CHAR(2);           /* REASON CODE                   *
*
* /********************************************************************
* /*    THE FOLLOWING MESSAGE IS AMA007I                              *
* /********************************************************************
*
*    DECLARE
*          1 AMA007I,
*            2 * CHAR(21) INIT('AMA007I  LOAD MODULE '),
*            2 LLLLLLLL CHAR(8),     /* MOD NAME                      *
*            2 * CHAR(31) INIT(' UPDATED WITH PTF - NEW SSI IS '), /*
*                                       M3999                         *
*            2 SSI CHAR(8);          /* NEW SSI                       *
*
* /********************************************************************
* /*    THE FOLLOWING MESSAGE IS AMA010I                              *
* /********************************************************************
*
*    DECLARE
*          1 AMA010I,                /* S21016                        *
*            2 * CHAR(29) INIT('AMA010I  AMAPTFLE TERMINATED,'), /*
*                                       S21016                        *
*            2 * CHAR(33) INIT(' AN IDENTIFY STATEMENT IS MISSING');
*                                       /* S21016                     *
* /*                                                            S21016*
*
* /********************************************************************
* /*    THE FOLLOWING MESSAGE IS AMA013I                              *
* /********************************************************************
*
*    DECLARE
*          1 AMA013I,                /* S21016                        *
*            2 * CHAR(26) INIT('AMA013I  THE FOLLOWING IS '), /*
*                                       S21016                        *
*            2 * CHAR(32) INIT('IDENTIFY INFORMATION FOR MODULE '), /*
*                                       S21016                        *
*            2 AMA013NM CHAR(8) INIT('        '); /* S21016           *
* /*                                                            S21016*
*
* /********************************************************************
* /*    THE FOLLOWING MESSAGE IS AMA016I                        Y01045*
* /********************************************************************
*
*    DECLARE
*          1 AMA016I,             /*                            Y01045*
*            2 * CHAR(29) INIT('AMA016I  AMAPTFLE TERMINATED,'),
*                                 /*                            Y01045*
*            2 * CHAR(32) INIT(' PARMLIB DD STATEMENT IS MISSING');
*                                /*                             Y01045*
* /*    DIFF IS THE DIFFERENCE BETWEEN THE BEGINNING ADDRESS OF THE   *
* /*    MODULE NAME TABLE AND AN ADDRESS OF A NAME IN THE TABLE       *
*    DECLARE
*          DIFF FIXED(31);
* /*    QUOTIENT IS DIFF DIVIDED BY 9                                 *
*    DECLARE
*          QUOTIENT FIXED(31);
* /*    THE ADDFACTR IS THE QUOTIENT MULTIPLIED BY 8.  WHEN ADDFACTR  *
* /*    IS ADDED TO SSITABLE, THE RESULTANT WILL BE A POINTER TO AN   *
* /*    ENTRY IN THE SSI TABLE FOR THE UPDATED MODULE.                *
*    DECLARE
*          ADDFACTR FIXED(31);
*    DECLARE
*          CORRSSI PTR(31);          /* POINTS TO SSI FOR NEW MOD     *
*    DECLARE
*          SSIDATA CHAR(8) BASED(CORRSSI); /* SSI FOR NEW MODULE      *
*    DECLARE
*          RETCDSAV FIXED(31);       /* SAVE FOR L.E. RET CODE        *
*    DECLARE
*          1 DDNMELST BDY (HWORD),   /* DDNAME PARM LIST FOR          *
*            2 * PTR(16) INIT(64),   /* LINKAGE EDITOR                *
*            2 * CHAR(8) INIT('OUTF    '),
*            2 * CHAR(8) INIT('0000000000000000'X),
*            2 * CHAR(8) INIT('SYSLMOD '),
*            2 * CHAR(8) INIT('0000000000000000'X),
*            2 * CHAR(8) INIT('0000000000000000'X),
*            2 * CHAR(8) INIT('SYSPRINT'),
*            2 * CHAR(8) INIT('0000000000000000'X),
*            2 * CHAR(8) INIT('SYSUT1  ');
*    DECLARE
*          PARMCONT BIT(1) INIT('0'B); /* USED TO INDICATE THAT       *
*                                    /* PARM IS CONTINUED             *
*    DECLARE
*          PCHBUFFR CHAR(80) BASED(PCHAREA); /* STAGE 1 INPUT BUFFER  *
*    DECLARE
*          PRMNUMBR PTR(16) INIT('0000'X); /* NUMBER OF L.E. PARMS    *
*    DECLARE
*          PARMEQUL CHAR(5) INIT('PARM='); /* USED FOR SEARCH OF      *
*                                    /* PARM KEYWORD ON EXEC          *
*                                    /* STATEMENT                     *
*    DECLARE
*          B PTR(16);                /* INDEX INTO BLDLFLD            *
*    DECLARE
*          DSSDNME CHAR(8) INIT('PARMLIB ');  /* DDNAME FOR DSS Y01045*
*    DECLARE
*          DEVDATA CHAR(8) BDY(WORD);  /* DATA AREA FOR DEVTYPE       *
*                                    /* MACRO                   Y01045*
*    DECLARE
*          PATCH(50) CHAR(2) BDY(HWORD) INIT((50)'0000'X);
*                                    /*  PATCH AREA             Y01983*
*
*    GENERATE;
IHADCB   DCBD
AMAPTF01 CSECT
         DS    0H
*    LSTPTRSV = LSTPTR;              /* SAVE ADDR OF PARM LIST M3990  *
         LR    @5,@1                                              0062
*    GO TO BRTABLE(BRFIELD);         /* BRANCH TO SUBROUTINE    A46805*
         SR    @2,@2                                              0063
         IC    @2,0(0,@5)                                         0063
         SLA   @2,2                                               0063
         L     @F,BRTABLE-4(@2)                                   0063
         BCR   15,@F                                              0063
* AMAOPEN:
*    IF OPENBIT = '1'B               /* IS IT FIRST ENTRY TO PTF01?   *
*          THEN
AMAOPEN  TM    OPENBIT,B'10000000'                                0064
*      GO TO AMASPUT2;               /* NO - SPOOL CARD         A46805*
         BC    01,AMASPUT2                                        0065
*    OPENBIT='1'B;                   /* SET FIRST ENTRY               *
         OI    OPENBIT,B'10000000'                                0066
*                                    /* TO PTF01 M4004                *
*    GENERATE;
OPENFLG  EQU   X'10'
         OPEN (SYSUTDCB,(OUTPUT))     OPEN WORKFILE DCB           M4005
         LA    OPENREG,SYSUTDCB
         USING IHADCB,OPENREG
         TM    DCBOFLGS,OPENFLG    DID DCB OPEN
         BZ    AMADDMSG            NO-WRITE ERROR MESSAGE
         DS    0H
*    IF PARMLEN > 8                  /* IS PARM IN ERROR?             *
*          THEN
         LA    @F,8                                               0068
         L     @2,64(0,@5)         
         MVC   @TEMP2+2(2),0(@2)                                  0068
         C     @F,@TEMP2                                          0068
*      GO TO AMA0001;                /* YES-WRITE ERROR MSG           *
         BC    04,AMA0001                                         0069
*    BLDLFLD(1) = '0000'X;           /* INDICATE TO PTF02             *
         MVC   BLDLFLD(1),@X2                                     0070
*                                    /* THAT BLDL IS FOR              *
*                                    /* LINKAGE EDITOR                *
*    BLDLFLD(5:PARMLEN+4) = PARM;    /* PUT NAME IN BLDL LIST M4003   *
         LA    @E,2(0,@2)                                         0071
         LA    @4,4                                               0071
         MVC   @TEMP2+2(2),0(@2)                                  0071
         A     @4,@TEMP2                                          0071
         SH    @4,@D1                                             0071
         LA    @A,BLDLFLD+4                                       0071
         EX    @4,@MVC                                            0071
*    LSTPTR = ADDR(BLDLFLD);         /* POINT TO BLDL LIST M3990      *
         LA    @1,BLDLFLD                                         0072
*    CALL AMAPTF02;                  /* GO TO PTF02                   *
         L     @4,16(0,@5)         
         LR    @F,@4                                              0073
         BALR  @E,@F                                              0073
*    IF BLDLFLD(1:2) = '0000'X       /* WAS BLDL O.K.?                *
*          THEN
         CLC   BLDLFLD(2),@X2                                     0074
         BC    07,@9FF                                            0074
*      DO;
* /*    IF THE BLDL WAS NOT GOOD, THEN INITIALIZE THE MESSAGE         *
* /*    BUFFER WITH THE ERROR MESSAGE AND GO TO AMAERMSG TO WRITE     *
* /*    THE ERROR MESSAGE.  UPON RETURN FROM AMAERMSG, RETURN TO      *
* /*    FILCLOSE IN AMAPTFLE TO CLOSE ALL DCBS.                       *
*
* AMA0001:
*        MSGBUF = ' ';
AMA0001  MVI   MSGBUF,C' '                                        0076
         MVC   MSGBUF+1(120),MSGBUF                               0076
*        MSGBUF(1:54) = AMA005I;
         MVC   MSGBUF(54),AMA005I                                 0077
*        RETCDE='10'X;                /*SET UP 16 RETURN CODE   A48711*
         MVI   2(@5),X'10'                                        0078
*
* AMACALL:
*        CALL AMAERMSG;
AMACALL  L     @F,@V1              ADDRESS OF AMAERMSG            0079
         BALR  @E,@F                                              0079
*        BRFIELD='00'X;              /* ZERO BRFIELD            Y01045*
         MVI   0(@5),X'00'                                        0080
*        RETURN TO FILCLOSE;
         L     @D,4(0,@D)                                         0081
         L     @E,68(0,@5)                                        0081
         LM    @F,@C,16(@D)                                       0081
         BCR   15,@E                                              0081
*      END;
*    ELSE
*      DO;
*        IF BLDLFLD(1) = 'FF'X       /* SYSLMOD OPEN FAIL M4012       *
*              THEN
@9FF     CLI   BLDLFLD,X'FF'                                      0084
*          GO TO AMADDSYS;           /* YES-GO WRITE ERROR MESSAGE    *
         BC    08,AMADDSYS                                        0085
* /*    IF THE BLDL AND OPEN WERE GOOD, THEN SAVE THE LINKAGE         *
* /*    EDITOR NAME AND SPOOL FIRST CONTROL STATEMENT.                *
*        LKEDNAME(1:PARMLEN) = PARM;
         L     @2,64(0,@5)         
         LA    @E,2(0,@2)                                         0086
         MVC   @TEMP2+2(2),0(@2)                                  0086
         L     @4,@TEMP2                                          0086
         BCTR  @4,0                                               0086
         LA    @A,LKEDNAME                                        0086
         EX    @4,@MVC                                            0086
*      END;
*
* /********************************************************************
* /*    AMASPUT2 IS A SUBROUTINE THAT IS USED FOR SPOOLING ALL CONTROL*
* /*    STATEMENTS TO THE SYSUT2 WORK FILE.  THIS ROUTINE IS ENTERED  *
* /*    WHEN AMAPTFLE IS READING THE CONTROL STATEMENTS.              *
* /********************************************************************
*
*
* AMASPUT2:
*    UT2OUT = DUMFIELD;              /* MOVE STMNT IN UT2OUT          *
@9FE     EQU   *                                                  0088
AMASPUT2 L     @2,24(0,@5)         
         MVC   UT2OUT(80),0(@2)                                   0088
*    OPENREG = ADDR(SYSUTDCB);       /* SET OPENREG TO SYSUTDCB ADDR  *
         LA    @3,SYSUTDCB                                        0089
*    GENERATE;
         WRITE SYSUDECB,SF,(OPENREG),UT2OUT
         CHECK SYSUDECB
         DS    0H
*    IF DUMFIELD(1) = '02'X          /* IS THIS AN OBJECT STMNT M4014 *
*          THEN
         CLI   0(@2),X'02'                                        0091
         BC    07,@9FD                                            0091
*      NEWNAME = '00'X;              /* YES-TURN OFF MODULE NAME SW   *
         MVI   NEWNAME,X'00'                                      0092
         BC    15,@9FC                                            0093
*    ELSE
*      DO;                           /* M4014                         *
*        IF DUMFIELD(1) = ' '        /* IS IDENTIFY CARD S21016       *
*              THEN
@9FD     L     @2,24(0,@5)         
         CLI   0(@2),C' '                                         0094
         BC    07,@9FB                                            0094
*          DO;                       /* S21016                        *
*            IDFOUND = '80'X;        /* SET IDENT FOUND SW            *
         MVI   IDFOUND,X'80'                                      0096
*            IDENTCON = '00'X;       /* RESET SW M0861                *
         MVI   1(@5),X'00'                                        0097
*            IF DUMFIELD(72) ^= ' '  /* IDENT CONTIN M0861            *
*                  THEN
         L     @2,24(0,@5)         
         CLI   71(@2),C' '                                        0098
         BC    08,@9FA                                            0098
*              IDENTCON = '08'X;     /* SET IDENT CONT SW             *
         MVI   1(@5),X'08'                                        0099
*                                    /* M0861                         *
*            GO TO AMARET1;          /* RETURN TO AMAPTFLE            *
         BC    15,AMARET1                                         0100
*          END;                      /* S21016                        *
*        IF NEWNAME = '00'X          /* MODULE NAME SWITCH SET M4014  *
*              THEN
@9FB     CLI   NEWNAME,X'00'                                      0102
         BC    07,@9F9                                            0102
*          DO;                       /* S21016                        *
*            IF IDFOUND = '80'X      /* IDENT FOUND SW SET            *
*                  THEN
         CLI   IDFOUND,X'80'                                      0104
         BC    07,@9F8                                            0104
*              DO;                   /* S21016                        *
*                IDFOUND = '00'X;    /* RESET IDENTIFY SW             *
         MVI   IDFOUND,X'00'                                      0106
*                NEWNAME = '80'X;    /* SET SWITCH M4014              *
         MVI   NEWNAME,X'80'                                      0107
*              END;                  /* S21016                        *
*            ELSE
*              GO TO AMANOID;        /* WRITE MSG S21016              *
*          END;                      /* S21016                        *
         BC    15,@9F6                                            0111
*        ELSE
*          DUMFIELD(1) = '02'X;      /* INDICATE NAME NOT TO BE M4014 *
@9F9     L     @2,24(0,@5)         
         MVI   0(@2),X'02'                                        0111
*                                    /* PUT IN MODULE NAME TABLE      *
*      END;                          /* M4014                         *
*    GO TO AMARET1;                  /* RETURN TO AMAPTFLE            *
         BC    15,AMARET1                                         0113
*
* /********************************************************************
* /********************************************************************
* /*    AMASPS IS ENTERED FORM PART 2(IEBCOPY) OF AMAPTFLE.           *
* /*    BRFIELD IS SET TO ZERO SO THAT AFTER THE OBJ IS SPOOLED TO    *
* /*    THE OUTF (SYSLIN) DATA SET, A NAME CARD IS GENERATED AND A    *
* /*    LINK IS MADE TO THE LINKAGE EDITOR.                           *
* /********************************************************************
*
*
* AMASPS:
*    BRFIELD = '00'X;                /* ENTERED FROM IEBCOPY          *
AMASPS   MVI   0(@5),X'00'                                        0114
*
* /********************************************************************
* /********************************************************************
* /*    AMASPOBJ IS ENTERED FROM PART 1(IEWL) OF AMAPTFLE.            *
* /*    THIS SUBROUTINE READS THE OBJ FOR THE APPROPRIATE MODULE      *
* /*    FROM THE SYSUT2 WORK FILE AND SPOOLS IT TO THE OUTF(SYSLIN)   *
* /*    DATA SET.                                                     *
* /********************************************************************
*
*
* AMASPOBJ:
*    NEWNAME = '00'X;                /* TURN OFF MODULE NAME SW M4014 *
AMASPOBJ MVI   NEWNAME,X'00'                                      0115
*    IDFOUND = '00'X;                /* S21016                        *
         MVI   IDFOUND,X'00'                                      0116
*    IF TTRZ(1) = ' ' THEN
         CLI   TTRZ,C' '                                          0117
         BC    07,@9F5                                            0117
*      DO;                           /* M4005                         *
*        GENERATE;
         CLOSE (SYSUTDCB)                                         M4005
         OPEN  (SYSUTDCB,(INPUT))                                 M4005
         READ  SYSTDECB,SF,SYSUTDCB,UT2OUT                        M4005
         CHECK SYSTDECB                                           M4005
         NOTE  SYSUTDCB                                           M4005
         ST    LSTPTR,TTRZ                                        M4005
         DS    0H
*        GO TO CHKNAME;              /* M4005                         *
         BC    15,CHKNAME                                         0120
*      END;
*    GENERATE;
@9F5     EQU   *                                                  0122
         POINT SYSUTDCB,TTRZ     LOCATE BEGINNING OF WORK FILE    M4005
AMARDOBJ READ SYSRDECB,SF,SYSUTDCB,UT2OUT
         CHECK SYSRDECB                                           M4004
         DS    0H
*
* CHKNAME:
*    IF NAMMATCH = 1 THEN            /* HAS APPROPRIATE OBJ BEEN
*                                       FOUND?                        *
CHKNAME  CLI   NAMMATCH,1                                         0123
*      GO TO AMACKOBJ;               /* YES-CHECK FOR OBJ CARD M4005  *
         BC    08,AMACKOBJ                                        0124
*    ELSE
* /*    IF THE APPROPRIATE OBJ HAS NOT BEEN LOCATED, THEN ATTEMPT TO  *
* /*    LOCATE IT BY CHECKING THE STATEMENT READ FROM SYSUT2 TO THE   *
* /*    MODULE NAME IN THE MODSTRBF BUFFER.                           *
*      IF UT2OUT(1:8) ^= MODSTRBF THEN
         L     @2,4(0,@5)          
         CLC   UT2OUT(8),0(@2)                                    0125
*        GO TO AMARDOBJ;             /* NO MATCH- READ ANOTHER RECORD *
         BC    07,AMARDOBJ                                        0126
*      ELSE
*        DO;
*          NAMMATCH = 1;             /* MATCH-INDICATE A MATCH        *
         MVI   NAMMATCH,1                                         0128
*          NEWNAME = '80'X;          /* SET MODULE NAME SWITCH M4014  *
         MVI   NEWNAME,X'80'                                      0129
*          GO TO AMARDOBJ;           /* AND READ ANOTHER OBJ RECORD   *
         BC    15,AMARDOBJ                                        0130
*        END;
*
* AMACKOBJ:
*    IF UT2OUT(1) = '02'X            /* IS THE RECORD OBJECT STMNT?   *
*          THEN
AMACKOBJ CLI   UT2OUT,X'02'                                       0132
         BC    07,@9F4                                            0132
*      DO;
*        NEWNAME = '00'X;            /* TURN OFF MODULE NAME SW M4014 *
         MVI   NEWNAME,X'00'                                      0134
*
* OUTFWTE:
*        OPENREG = OUTFDCB;          /* YES-GET THE OUTFDCB ADDRESS
*                                       M4014                         *
OUTFWTE  L     @3,28(0,@5)                                        0135
*        GENERATE;
         WRITE OUTFDECB,SF,(OPENREG),UT2OUT
         CHECK OUTFDECB
         DS    0H
*        GO TO AMARDOBJ;             /* READ ANOTHER SYSUT2 RECORD    *
         BC    15,AMARDOBJ                                        0137
*      END;
*    ELSE
*      IF NEWNAME = '80'X            /* MODULE NAME ALREADY           *
*                                    /* READ IN M4014                 *
*            THEN
@9F4     CLI   NEWNAME,X'80'                                      0139
         BC    07,@9F2                                            0139
*        DO;                         /* YES-BUILD ALIAS CARDS         *
*          IF BRFIELD ^= '00'X       /* MODULE COPIED AT M4014        *
*                                    /* SYSGEN (BRFIELD=0)            *
*                THEN
         CLI   0(@5),X'00'                                        0141
*            GO TO AMARDOBJ;         /* NO-IGNORE ALIAS M4014         *
         BC    07,AMARDOBJ                                        0142
*          ALIASNM = UT2OUT(1:8);    /* MOVE ALIAS NAME M4014         *
         MVC   ALIASCD+7(8),UT2OUT                                0143
*                                    /* TO ALIAS CARD M4014           *
*          UT2OUT = ' ';             /* BLANK OUTPUT BUFFER           *
         MVI   UT2OUT,C' '                                        0144
         MVC   UT2OUT+1(79),UT2OUT                                0144
*          UT2OUT(1:15) = ALIASCD;   /* MOVE ALIAS CARD TO            *
         MVC   UT2OUT(15),ALIASCD                                 0145
*                                    /* OUTPUT BUFFER M4014           *
*          GO TO OUTFWTE;            /* WRITE ALIAS CARD M4014        *
         BC    15,OUTFWTE                                         0146
*        END;                        /* M4014                         *
*    IF UT2OUT(1) = ' '              /* IDENTIFY CARD S21016          *
*          THEN
@9F2     EQU   *                                                  0148
@9F3     CLI   UT2OUT,C' '                                        0148
         BC    07,@9F1                                            0148
*      DO;                           /* YES-SET IDENTIFY FOUND S21016 *
*        IDFOUND = '80'X;            /* SWITCH S21016                 *
         MVI   IDFOUND,X'80'                                      0150
*        GO TO OUTFWTE;              /* WRITE IDENTIFY CARD S21016    *
         BC    15,OUTFWTE                                         0151
*      END;                          /* S21016                        *
*
* /********************************************************************
* /*    AMAEODAD IS ENTERED UPON EOF OR WHEN THE OBJ HAS BEEN SPOOLED *
* /********************************************************************
*
*
* AMAEODAD:
*    NAMMATCH = 0;                   /* RESET NAME FOUND SWITCH M4000 *
@9F1     EQU   *                                                  0153
AMAEODAD MVI   NAMMATCH,0                                         0153
*    IF IDFOUND = '00'X              /* IDENTIFY CARD MISSING S21016  *
*          THEN
         CLI   IDFOUND,X'00'                                      0154
*      GO TO AMANOID;                /* YES-WRITE MESSAGE S21016      *
         BC    08,AMANOID                                         0155
*    IDFOUND = '00'X;                /* TURN OFF IDENTIFY FOUND SWITCH*
         MVI   IDFOUND,X'00'                                      0156
*    SSIINFO = '0';                  /* NO SETSSI CARD NEEDED M4000   *
         MVI   SSICARD+12,C'0'                                    0157
         MVI   SSICARD+13,C' '                                    0157
         MVC   SSICARD+14(6),SSICARD+13                           0157
*    IF BRFIELD ^= 0 THEN            /* DOES A NAME STMNT HAVE TO BE  *
         CLI   0(@5),0                                            0158
*                                    /* WRITTEN BECAUSE OF ENTRY FROM *
*                                    /* PART 2(IEBCOPY) OF AMAPTFLE?  *
*                                    /* M4000                         *
*      GO TO AMARET2;                /* NO-RETURN TO AMAPTFLE         *
         BC    07,AMARET2                                         0159
*    UT2OUT = ' ';                   /* YES-CLEAR THE BUFFER M4003    *
         MVI   UT2OUT,C' '                                        0160
         MVC   UT2OUT+1(79),UT2OUT                                0160
*    MDN = ' ';                      /* BLANK MOD NAME BUFFER M4003   *
         MVI   NAMECARD+10,C' '                                   0161
         MVC   NAMECARD+11(10),NAMECARD+10                        0161
*    DO I = 1 TO 8;                  /* MOVE MODULE NAME INTO BUFFER  *
         LA    @6,1                                               0162
*      IF SELBUF(I) = ',' × SELBUF(I) = ')' × SELBUF(I) = ' ' THEN
@DO9F0   LR    @2,@6                                              0163
         L     @4,44(0,@5)         
         LA    @A,0(@2,@4)                                        0163
         BCTR  @A,0                                               0163
         CLI   0(@A),C','                                         0163
         BC    08,@9EC                                            0163
         CLI   0(@A),C')'                                         0163
         BC    08,@9EB                                            0163
         CLI   0(@A),C' '                                         0163
         BC    07,@9EA                                            0163
*        GO TO MOVEREP;              /* REACHED END OF NAME M4011     *
         BC    08,MOVEREP                                         0164
*      MDN(I) = SELBUF(I);           /* MOVE CHAR TO BUFFER           *
@9EA     LR    @2,@6                                              0165
         L     @4,44(0,@5)         
         LA    @E,0(@2,@4)                                        0165
         BCTR  @E,0                                               0165
         LA    @A,NAMECARD+9(@2)                                  0165
         MVC   0(1,@A),0(@E)                                      0165
*    END;                            /* M4003                         *
*
* MOVEREP:
*    MDN(I:I+2) = REP;               /* MOVE (R) TO NAME CARD         *
         AH    @6,@D2                                             0166
@DO9EF   CH    @6,@D3                                             0166
         BC    12,@DO9F0                                          0166
MOVEREP  LR    @2,@6                                              0167
         LA    @A,NAMECARD+9(@2)                                  0167
         MVC   0(3,@A),REP                                        0167
*    SSIINFO = ' ';                  /* BLANK SETSSI FIELD M4000      *
         MVI   SSICARD+12,C' '                                    0168
         MVC   SSICARD+13(7),SSICARD+12                           0168
*    GO TO SSIGEN;                   /* GET SSI INFORMATION M4000     *
         BC    15,SSIGEN                                          0169
*
* MOVESSI:
*    SSIINFO = SSIDATA;              /* MOVE SSI TO SETSSI CARD       *
MOVESSI  L     @2,CORRSSI                                         0170
         MVC   SSICARD+12(8),0(@2)                                0170
*    UT2OUT = SSICARD;               /* MOVE CARD TO BUFFER M4000     *
         MVC   UT2OUT(20),SSICARD                                 0171
         MVI   UT2OUT+20,C' '                                     0171
         MVC   UT2OUT+21(59),UT2OUT+20                            0171
*    OPENREG = OUTFDCB;              /* M4000                         *
         L     @3,28(0,@5)                                        0172
*    GENERATE;
         WRITE OUTFSSI,SF,(OPENREG),UT2OUT   WRITE SETSSI CARD    M4000
         CHECK OUTFSSI                                            M4000
         DS    0H
*    UT2OUT = ' ';
         MVI   UT2OUT,C' '                                        0174
         MVC   UT2OUT+1(79),UT2OUT                                0174
*    UT2OUT = NAMECARD;              /* MOVE NAME CARD INTO BUFFER    *
         MVC   UT2OUT(21),NAMECARD                                0175
         MVI   UT2OUT+21,C' '                                     0175
         MVC   UT2OUT+22(58),UT2OUT+21                            0175
*    OPENREG = OUTFDCB;              /* GET THE OUTFDCB ADDRESS       *
         L     @3,28(0,@5)                                        0176
*    GENERATE;
                   WRITE OUTFNAME,SF,(OPENREG),UT2OUT
                   CHECK OUTFNAME
         DS    0H
*
* /********************************************************************
* /*    THE AMALINK SUBROUTINE IS ENTERED WHEN A LINK TO THE          *
* /*    LINKAGE EDITOR IS REQUIRED TO LINKEDIT A MODULE FOR THE PTF.  *
* /*    IF AMALINK IS ENTERED TO LINKEDIT A MODULE THAT WAS COPIED    *
* /*    INTO THE SYSTEM AT SYSGEN, THEN A BRANCH IS MADE TO AMAPTF02  *
* /*    TO RETRIEVE THE LINKEDIT ATTRIBUTES OF THE MODULE BEFORE THE  *
* /*    LINKEDIT IS DONE.  OTHERWISE, THE ATTRIBUTES HAVE ALREADY BEEN*
* /*    RETRIEVED FROM THE EXEC STATEMENT AND NO BRANCH TO AMAPTF02   *
* /*    IS DONE.  IN EITHER CASE, THE OVERLAY RECORD TABLE IN         *
* /*    AMAPTFLE IS FREED SO THAT THE LINKAGE EDITOR CAN BE BROUGHT   *
* /*    INTO CORE.  ALSO BEFORE THE LINK IS DONE, THE OUTFDCB IS      *
* /*    CLOSED BECAUSE THE LINKAGE EDITOR WILL RE-OPEN IT AS THE      *
* /*    SYSLIN DATA SET.  UPON RETURN FROM THE EDITOR, THE OUTFDCB IS *
* /*    RE-OPENED AND TESTED FOR A SUCCESSFUL OPEN.  LINKAGE EDITOR   *
* /*    RETURN CODES ARE CHECKED, AND A DISPOSITION MESSAGE IS ISSUED.*
* /*    A RETURN IS MADE TO AMAPTFLE.                                 *
* /********************************************************************
*
*
* AMALINK:
*    IF BRFIELD = 0                  /* NAME MATCH ON SELECT STMNT?
*                                       M4000                         *
*          THEN
AMALINK  CLI   0(@5),0                                            0178
         BC    07,@9E9                                            0178
*      DO;
*        BLDLFLD = ' ';              /* YES-CLEAR PTF02'S PARM LIST   *
         MVI   BLDLFLD,C' '                                       0180
         MVC   BLDLFLD+1(71),BLDLFLD                              0180
*        BLDLFLD(5:5+I-2) = MDN;               /* MOVE IN NAME        *
         LA    @E,NAMECARD+10                                     0181
         LH    @2,@D4                                             0181
         AR    @2,@6                                              0181
         AH    @2,@D1                                             0181
         SH    @2,@D1                                             0181
         LA    @A,BLDLFLD+4                                       0181
         EX    @2,@MVC                                            0181
*                                    /* M4003                         *
*        GO TO AMATABAD;             /* GO FREE OVERLAY TABLE         *
         BC    15,AMATABAD                                        0182
*      END;
*    CCCCCCCC = MODSTRBF;            /* NO-MOVE MOD NAME INTO MESSAGE *
@9E9     L     @2,4(0,@5)          
         MVC   AMA006I+21(8),0(@2)                                0184
*    GO TO AMANOBLD;                 /* NO BLDL NEEDED M4003          *
         BC    15,AMANOBLD                                        0185
*
* /********************************************************************
* /*    YES - AMAPTF02 IS NEEDED BECAUSE MODULE WAS ORIGINALLY COPIED *
* /*    INTO THE SYSTEM.  MOVE MODULE NAME INTO DISPOSITION MESSAGE   *
* /*    AND THEN GO TO AMAPTF02 TO RETRIEVE LINKEDIT ATTRIBUTES.      *
* /********************************************************************
*
*
* AMATABAD:
*    CCCCCCCC = BLDLFLD(5:12);              /* MOVE NAME M4000        *
AMATABAD MVC   AMA006I+21(8),BLDLFLD+4                            0186
*    LSTPTR = ADDR(BLDLFLD);         /* GET ADDR OF PTF02'S PARM LIST *
         LA    @1,BLDLFLD                                         0187
*    CALL AMAPTF02;                  /* GO TO AMAPTF02                *
         L     @2,16(0,@5)         
         LR    @F,@2                                              0188
         BALR  @E,@F                                              0188
*    MSGBUF = ' ';                   /* CLEAR MESSAGE BUFFER          *
         MVI   MSGBUF,C' '                                        0189
         MVC   MSGBUF+1(120),MSGBUF                               0189
*    IF BLDLFLD(1:2) = '0000'X ×     /* BLDL SUCCESSFUL?              *
*          BLDLFLD(1:2) = '0001'X THEN
         CLC   BLDLFLD(2),@X2                                     0190
         BC    08,@9E8                                            0190
         CLC   BLDLFLD(2),@X12                                    0190
         BC    07,@9E7                                            0190
*      GO TO AMA6IB;                 /* NO-GO WRITE ERROR MESSAGE     *
         BC    08,AMA6IB                                          0191
*    IF BLDLFLD(1) = 'FF'X           /* SYSLMOD OPEN FAIL M4012       *
*          THEN
@9E7     CLI   BLDLFLD,X'FF'                                      0192
*      GO TO AMADDSYS;               /* YES-GO WRITE ERROR MESSAGE    *
         BC    08,AMADDSYS                                        0193
*
* AMANOBLD:
*    OPENREG = OUTFDCB;              /* GET OUTFDCB ADDRESS           *
AMANOBLD L     @3,28(0,@5)                                        0194
*    GENERATE;
         CLOSE ((OPENREG),)          CLOSE THE OUTFDCB
         DS    0H
*
* /********************************************************************
* /*    CHECK IF UPDATING THE NUCLEUS                           Y01045*
* /********************************************************************
*
*    IF COMSW = '80'X THEN           /* UPDATING THE NUCLEUS    Y01045*
         CLI   3(@5),X'80'                                        0196
         BC    07,@9E6                                            0196
*      DO;                           /* YES                     Y01045*
*        GENERATE;
        DEVTYPE   DSSDNME,DEVDATA    PARMLIB DD PRESENT          Y01045
         DS    0H
*        IF RETCODE ^= 0 THEN        /* RETURN CODE ZERO        Y01045*
         LTR   @F,@F                                              0199
         BC    08,@9E5                                            0199
*          DO;                       /* NO - DD STATEMENT MISSING     *
*                                    /*                         Y01045*
*            MSGBUF=AMA016I;         /* MOVE MSG TO BUFFER      Y01045*
         MVC   MSGBUF(61),AMA016I                                 0201
         MVI   MSGBUF+61,C' '                                     0201
         MVC   MSGBUF+62(59),MSGBUF+61                            0201
*            RETCDE='10'X;           /* SET RETURN CODE         Y01045*
         MVI   2(@5),X'10'                                        0202
*            GOTO AMACALL;           /* WRITE MESSAGE AND       Y01045*
         BC    15,AMACALL                                         0203
*                                    /* RETURN TO FILCLOSE      Y01045*
*          END;                      /* END DO GROUP            Y01045*
*        END;                        /* END CHECK FOR NUCLEUS   Y01045*
@9E5     EQU   *                                                  0205
*                                    /* UPDATE                  Y01045*
*
*    LSTPTR = OVTABADR;              /* GET OVERLAY TABLE ADDRESS
*                                       M4000                         *
@9E6     L     @1,8(0,@5)                                         0206
*    GENERATE;
         FREEMAIN  R,LV=26800,A=(LSTPTR)  FREE THE OVERLAY TABLE S21016
         LINK  EPLOC=LKEDNAME,PARAM=(BLDLFLD,DDNMELST),VL=1
         DS    0H
*    RETCDSAV = RETCODE;             /* SAVE L.E. RETURN CODE         *
         ST    @F,RETCDSAV                                        0208
*    OPENREG = ADDR(OVTABADR);       /* GET OVERLAY TABLE ADDR M4000  *
         LA    @3,8(0,@5)                                         0209
*
* /********************************************************************
* /*    GETMAIN TO RE-INITIALIZE THE OVERLAY TABLE IN AMAPTFLE        *
* /********************************************************************
*
*    GENERATE(GETMAIN EU,LV=26800,A=(OPENREG)); /* S21016             *
         GETMAIN EU,LV=26800,A=(OPENREG)
         DS    0H
*
* /********************************************************************
*
*    RETCODE = RETCDSAV;             /* RESTORE RETURN CODE      M0867*
         L     @F,RETCDSAV                                        0211
*    IF RETCODE = 12×RETCODE = 16 THEN       /* SUCCESSFUL L.E.? M0867*
         CH    @F,@D5                                             0212
         BC    08,@9E4                                            0212
         CH    @F,@D6                                             0212
         BC    07,@9E3                                            0212
*      GO TO AMA6II;                 /* NO-GO WRITE ERROR MSG    M0867*
         BC    08,AMA6II                                          0213
*    OPENREG = OUTFDCB;              /* GET OUTFDCB ADDRESS           *
@9E3     L     @3,28(0,@5)                                        0214
*
* /********************************************************************
* /*    RE-OPEN THE OUTFDCB TO BUILD ANOTHER SYSLIN DATA SET IF NEEDED*
* /********************************************************************
*
*    GENERATE (OPEN ((OPENREG),INPUT)); /*                     S21016 *
         OPEN ((OPENREG),INPUT)
         DS    0H
*
* /********************************************************************
*
*    OPENREG = OUTFDCB;              /* GET THE OUTFDCB ADDR          *
         L     @3,28(0,@5)                                        0216
*    GENERATE;
         USING IHADCB,OPENREG
         TM    DCBOFLGS,OPENFLG      DCB OPEN OKAY?
         BZ    AMADDOUT              NO-GO WRITE ERROR MESSAGE
         DS    0H
*    LLLLLLLL = CCCCCCCC;            /* MOVE MODULE NAME INTO         *
         MVC   AMA007I+21(8),AMA006I+21                           0218
*                                    /* DISPOSITION MESSAGE           *
*
* /********************************************************************
* /*    LOCATE THE SSI IN THE SSI TABLE FOR INCLUSION IN MESSAGE      *
* /********************************************************************
*
*
* SSIGEN:
*    DIFF = SSISAVE - MODTBL;        /* FIND NAME DISPLACEMENT        *
SSIGEN   L     @F,56(0,@5)                                        0219
         LCR   @F,@F                                              0219
         A     @F,48(0,@5)                                        0219
         ST    @F,DIFF                                            0219
*                                    /* IN MOD NAME TABLE M4000       *
*    QUOTIENT = DIFF/10;             /* DIVIDE BY ENTRY LNGTH YA00891 *
         LR    @E,@F                                              0220
         SRDA  @E,32                                              0220
         LA    @0,10                                              0220
         DR    @E,@0                                              0220
         ST    @F,QUOTIENT                                        0220
*    ADDFACTR = QUOTIENT * 8;        /* MULTIPLY BY SSI ENTRY         *
         SLA   @F,3                                               0221
         ST    @F,ADDFACTR                                        0221
*                                    /* LENGTH TO LOCATE THE          *
*                                    /* MODULE'S SSI IN TABLE         *
*    CORRSSI = SSITABLE + ADDFACTR;  /* GET SSI ADDRESS               *
         A     @F,60(0,@5)                                        0222
         ST    @F,CORRSSI                                         0222
*    SSI = SSIDATA;                  /* MOVE SSI INTO MSG             *
         LR    @2,@F                                              0223
         MVC   AMA007I+60(8),0(@2)                                0223
*    IF SSIINFO = '        ' THEN
         CLC   SSICARD+12(8),@C13                                 0224
*      GO TO MOVESSI;                /* NEED SETSSI CARD              *
         BC    08,MOVESSI                                         0225
*    MSGBUF = AMA007I;               /* MOVE MSG INTO BUFFER          *
         MVC   MSGBUF(68),AMA007I                                 0226
         MVI   MSGBUF+68,C' '                                     0226
         MVC   MSGBUF+69(52),MSGBUF+68                            0226
*    CALL AMAERMSG;                  /* WRITE MESSAGE S21016          *
         L     @F,@V1              ADDRESS OF AMAERMSG            0227
         BALR  @E,@F                                              0227
*
* /********************************************************************
*
*    AMA013NM = LLLLLLLL;            /* MOVE MODULE NAME TO MSG       *
         MVC   AMA013I+58(8),AMA007I+21                           0228
*                                    /* S21016                        *
*    MSGBUF = AMA013I;               /* MOVE MSG INTO BUFFER          *
         MVC   MSGBUF(66),AMA013I                                 0229
         MVI   MSGBUF+66,C' '                                     0229
         MVC   MSGBUF+67(54),MSGBUF+66                            0229
*                                    /* S21016                        *
*    CALL AMAERMSG;                  /* WRITE MESSAGE S21016          *
         L     @F,@V1              ADDRESS OF AMAERMSG            0230
         BALR  @E,@F                                              0230
*
* PREPRD:
*    OPENREG = OUTFDCB;              /* S21016                        *
PREPRD   L     @3,28(0,@5)                                        0231
*    GENERATE;                       /* S21016                        *
         READ  OUTFDECA,SF,(OPENREG),UT2OUT  READ IDENTIFY CARDS S21016
         CHECK OUTFDECA                                          S21016
         DS    0H
*    IF UT2OUT(1) ^= ' '             /* CONTROL CARD S21016           *
*          THEN
         CLI   UT2OUT,C' '                                        0233
*      GO TO PREPRD;                 /* NO-GET NEXT CARD S21016       *
         BC    07,PREPRD                                          0234
*    I = 1;                          /* INITIALIZE COUNT S21016       *
         LA    @6,1                                               0235
*    IF IDENTCON = '08'X THEN
         CLI   1(@5),X'08'                                        0236
         BC    07,@9E2                                            0236
*      DO;                           /* CONTINUATION S21016           *
*        IDENTCON = '00'X;           /* YES-TURN OFF SW S21016        *
         MVI   1(@5),X'00'                                        0238
*        GO TO AMAIDST;              /* WRITE INFO S21016             *
         BC    15,AMAIDST                                         0239
*      END;                          /*                        S21016 *
*    OPENREG = ADDR(AMAIDCHK);       /* SET RETURN ADDR        S21016 *
@9E2     LA    @3,AMAIDCHK                                        0241
*    GO TO CHKSPACE;                 /* FIND OPERAND           S21016 *
         BC    15,CHKSPACE                                        0242
*
* AMAIDCHK:                          /*                        S21016 *
*    IF UT2OUT(I:I+3) = 'NAME'       /* NAME CARD              S21016 *
*          THEN
AMAIDCHK LR    @2,@6                                              0243
         LA    @A,UT2OUT-1(@2)                                    0243
         CLC   0(4,@A),@C14                                       0243
*      GO TO OUTFEOF;                /* YES-EXIT               S21016 *
         BC    08,OUTFEOF                                         0244
*    IF UT2OUT(I:I+7) ^= 'IDENTIFY'  /* IDENTIFY CARD          S21016 *
*          THEN
         CLC   0(8,@A),@C15                                       0245
*      GO TO PREPRD;                 /* NO-READ NEW CARD       S21016 *
         BC    07,PREPRD                                          0246
*
* AMAIDST:
*    OPENREG = ADDR(AMAIDBL);        /* SET RETURN ADDR        S21016 *
AMAIDST  LA    @3,AMAIDBL                                         0247
*    IF UT2OUT(72) ^= ' '            /* CONTINUATION            M0861 *
*          THEN
         CLI   UT2OUT+71,C' '                                     0248
         BC    08,@9E1                                            0248
*      IDENTCON = '08'X;             /* YES-INDICATE SO         M0861 *
         MVI   1(@5),X'08'                                        0249
*    GO TO CHKSPACE;                 /* FIND IDR INFO          S21016 *
         BC    15,CHKSPACE                                        0250
*
* AMAIDBL:
*    MSGBUF = ' ';                   /* BLANK BUFFER           S21016 *
AMAIDBL  MVI   MSGBUF,C' '                                        0251
         MVC   MSGBUF+1(120),MSGBUF                               0251
*    MSGBUF(20:82) = UT2OUT(I:72);   /* MOVE TO BUFFER         S21016 *
         LA    @2,72                                              0252
         LR    @4,@6                                              0252
         SR    @2,@4                                              0252
         LA    @E,UT2OUT-1(@4)                                    0252
         LA    @A,MSGBUF+19                                       0252
         MVI   0(@A),C' '                                         0252
         MVC   1(062,@A),0(@A)                                    0252
         EX    @2,@MVC                                            0252
*    CALL AMAERMSG;                  /* IDENTIFY INFO          S21016 *
         L     @F,@V1              ADDRESS OF AMAERMSG            0253
         BALR  @E,@F                                              0253
*    GO TO PREPRD;                   /* READ NEXT CARD         S21016 *
         BC    15,PREPRD                                          0254
*
* OUTFEOF:
*    OPENREG = OUTFDCB;              /*                        S21016 *
OUTFEOF  L     @3,28(0,@5)                                        0255
*    GENERATE (CLOSE ((OPENREG)));   /*                        S21016 *
         CLOSE ((OPENREG))
         DS    0H
* OPENOUTF:                          /*                         M0867 *
*    OPENREG = OUTFDCB;              /*                        S21016 *
OPENOUTF L     @3,28(0,@5)                                        0257
*    GENERATE (OPEN ((OPENREG),OUTPUT)); /* OPEN OUTF          S21016 *
         OPEN ((OPENREG),OUTPUT)
         DS    0H
*    OPENREG = OUTFDCB;              /* GET THE OUTFDCB ADDR   S21016 *
         L     @3,28(0,@5)                                        0259
*    GENERATE;
         USING IHADCB,OPENREG                                    S21016
         TM    DCBOFLGS,OPENFLG      DCB OPEN OKAY?              S21016
         BZ    AMADDOUT              NO-GO WRITE ERROR MESSAGE   S21016
         DS    0H
*    GO TO AMARET2;                  /* RETURN TO AMAPTFLE            *
         BC    15,AMARET2                                         0261
*
* CHKSPACE:
*    DO I = I TO 71;                 /* GET NEXT OPERAND       S21016 *
*      IF UT2OUT(I) = ' '            /* REACHED NON BLANK      S21016 *
*            THEN
@DO9E0   LR    @2,@6                                              0263
         LA    @A,UT2OUT-1(@2)                                    0263
         CLI   0(@A),C' '                                         0263
*        GO TO CHKSP2;               /* NO CONTINUE TO SCAN    S21016 *
         BC    08,CHKSP2                                          0264
*    END;
*
* CHKSP2:
*    DO I = I TO 71;
         AH    @6,@D2                                             0265
@DO9DF   CH    @6,@D7                                             0265
         BC    12,@DO9E0                                          0265
         BC    15,@DO9DB                                          0266
*      IF UT2OUT(I) ^= ' '           /* REACHED NON BLANK      S21016 *
*            THEN
@DO9DC   LR    @2,@6                                              0267
         LA    @A,UT2OUT-1(@2)                                    0267
         CLI   0(@A),C' '                                         0267
         BC    08,@9D8                                            0267
*        GENERATE;
         BR    3                       RETURN TO CALLER          S21016
         DS    0H
*    END;                            /*                        S21016 *
*
* /********************************************************************
* /********************************************************************
* /*    AMALEPRM IS A SUBROUTINE THAT IS USED TO RETRIEVE THE         *
* /*    LINKEDIT ATTRIBUTES OF THE MODULE FROM THE EXEC STATEMENT     *
* /*    IF THE MODULE WAS LINKEDITED INTO THE SYSTEM AT SYSGEN TIME.  *
* /********************************************************************
*
*
* AMALEPRM:
*    I = 3;                          /* SET INDEX PAST SLASHES        *
@9D8     AH    @6,@D2                                             0269
@DO9DB   CH    @6,@D7                                             0269
         BC    12,@DO9DC                                          0269
AMALEPRM LA    @6,3                                               0270
*    IF PARMCONT = '1'B THEN         /* CONTINUATION STATEMENT?       *
         TM    PARMCONT,B'10000000'                               0271
*      GO TO AMABLANK;               /* YES-FIND FIRST KEYWORD        *
         BC    01,AMABLANK                                        0272
*    PRMNUMBR = 0;                   /* RESET LKED PARM LENGTH  M4003 *
         SR    @F,@F                                              0273
         STH   @F,PRMNUMBR                                        0273
*
* AMACOLCK:
*    IF I >= 72 THEN                 /* SCAN COMPLETE                 *
AMACOLCK CH    @6,@D8                                             0274
*
* AMACONT:
*      GO TO AMARET2;                /* YES-RETURN TO AMAPTFLE        *
         BC    11,AMARET2                                         0275
*
* AMABLANK:
*    IF PCHBUFFR(I) = ' '            /* KEYWORD FOUND?                *
*          THEN
@9D7     EQU   *                                                  0276
AMABLANK LR    @2,@6                                              0276
         L     @4,20(0,@5)         
         LA    @A,0(@2,@4)                                        0276
         BCTR  @A,0                                               0276
         CLI   0(@A),C' '                                         0276
         BC    07,@9D6                                            0276
*      DO;                           /* YES                           *
*
* AMABUMPI:
*        I = I+1;                    /* BUMP INDEX INTO BUFFER        *
AMABUMPI AH    @6,@D2                                             0278
*        GO TO AMACOLCK;             /* CHECK FOR END OF STMNT        *
         BC    15,AMACOLCK                                        0279
*      END;
*    ELSE                            /* NO                            *
*      IF PARMCONT = '1'B THEN       /* A CONTINUAION STMNT?          *
@9D6     TM    PARMCONT,B'10000000'                               0281
*        GO TO AMAPRM2;              /* YES-CONSTRUCT PARM LIST       *
         BC    01,AMAPRM2                                         0282
*      ELSE
* /*    NO - THEN CHECK TO SEE IF PARMS HAVE BEEN FOUND               *
*        IF PCHBUFFR(I:I+4) = PARMEQUL THEN /* FOUND?                 *
         LR    @2,@6                                              0283
         L     @4,20(0,@5)         
         LA    @A,0(@2,@4)                                        0283
         BCTR  @A,0                                               0283
         CLC   0(5,@A),PARMEQUL                                   0283
*          GO TO AMAMVPRM;           /* YES-SET UP PARM LIST          *
*        ELSE
*          GO TO AMABUMPI;           /* NO-CHECK NEXT CHAR            *
         BC    07,AMABUMPI                                        0285
*
* AMAMVPRM:
*    ENDPARM = '7D'X;                /* SET PARM END TO '       M4011 *
@9D5     EQU   *                                                  0286
AMAMVPRM MVI   ENDPARM,X'7D'                                      0286
*    IF PCHBUFFR(I+5) = '('          /* IF PARM BEGIN IS        M4011 *
*          THEN
         LA    @2,5                                               0287
         AR    @2,@6                                              0287
         L     @4,20(0,@5)         
         LA    @A,0(@2,@4)                                        0287
         BCTR  @A,0                                               0287
         CLI   0(@A),C'('                                         0287
         BC    07,@9D4                                            0287
*      ENDPARM = ')';                /* (,SET END TO )          M4011 *
         MVI   ENDPARM,C')'                                       0288
*    I = I+6;                        /* BUMP PAST 'PARM='             *
@9D4     AH    @6,@D9                                             0289
*    IF I >= 72                      /* AT END OF STMNT?              *
*          THEN
         CH    @6,@D8                                             0290
         BC    04,@9D3                                            0290
*      DO;                           /* YES                           *
*        PARMCONT = '1'B;            /* INDICATE CONTINUATION         *
         OI    PARMCONT,B'10000000'                               0292
*        GO TO AMARET2;              /* RETURN TO AMAPTFLE            *
         BC    15,AMARET2                                         0293
*      END;
*
* AMAPRM1:
*    B = 3;                          /* INDEX INTO BLDLFLD            *
@9D3     EQU   *                                                  0295
AMAPRM1  LA    @F,3                                               0295
         STH   @F,B                                               0295
*
* /********************************************************************
* /*    MOVE THE PARAMETERS, ONE CHARACTER AT A TIME, INTO BLDLFLD    *
* /********************************************************************
*
*
* AMAPRM2:
*    BLDLFLD(B) = PCHBUFFR(I);       /* MOVE A CHARACTER              *
AMAPRM2  LR    @2,@6                                              0296
         L     @4,20(0,@5)         
         LA    @E,0(@2,@4)                                        0296
         BCTR  @E,0                                               0296
         MVC   @TEMP2+2(2),B                                      0296
         L     @7,@TEMP2                                          0296
         LA    @A,BLDLFLD-1(@7)                                   0296
         MVC   0(1,@A),0(@E)                                      0296
*    B = B+1;                        /* BUMP BLDLFLD INDEX            *
         LA    @F,1                                               0297
         MVC   @TEMP2+2(2),B                                      0297
         A     @F,@TEMP2                                          0297
         STH   @F,B                                               0297
*    I = I+1;                        /* BUMP PCHBUFFR INDEX           *
         AH    @6,@D2                                             0298
*    PRMNUMBR = PRMNUMBR+1;          /* BUMP NUMBER OF PARMS          *
         LA    @F,1                                               0299
         MVC   @TEMP2+2(2),PRMNUMBR                               0299
         A     @F,@TEMP2                                          0299
         STH   @F,PRMNUMBR                                        0299
*    IF I >= 72                      /* END OF STATEMENT?             *
*          THEN
         CH    @6,@D8                                             0300
         BC    04,@9D2                                            0300
*      DO;                           /* YES                           *
*        PARMCONT = '1'B;            /* INDICATE PARM CONTINUED       *
         OI    PARMCONT,B'10000000'                               0302
*        GO TO AMARET2;              /* RETURN TO AMAPTFLE            *
         BC    15,AMARET2                                         0303
*      END;
*    ELSE
*      IF PCHBUFFR(I) = ENDPARM      /* END OF PARAMETERS M4011       *
*            THEN
@9D2     LR    @2,@6                                              0305
         L     @4,20(0,@5)         
         LA    @A,0(@2,@4)                                        0305
         BCTR  @A,0                                               0305
         CLC   0(1,@A),ENDPARM                                    0305
         BC    07,@9D0                                            0305
*        DO;                         /* YES                           *
*          B = 0;                    /* RE-INIT BLDLFLD INDEX         *
         SR    @F,@F                                              0307
         STH   @F,B                                               0307
*          PARMCONT = '0'B;          /* SET NO CONTINUATION           *
         NI    PARMCONT,B'01111111'                               0308
*          BLDLFLD(1:2) = PRMNUMBR;  /* MOVE PARM LENGTH              *
         MVC   BLDLFLD(2),PRMNUMBR                                0309
*                                    /*                         M4003 *
*          GO TO AMARET2;            /* RETURN TO AMAPTFLE            *
         BC    15,AMARET2                                         0310
*        END;
*      ELSE                          /* NOT END OF PARMS              *
*        GO TO AMAPRM2;              /* MOVE ANOTHER PARM             *
*
* /********************************************************************
* /********************************************************************
* /*    AMACLOSE IS ENTERED FROM AMAPTFLE WHEN ALL OF THE DCBS        *
* /*    MUST BE CLOSED BEFORE TERMINATION.                            *
* /********************************************************************
*
*    GENERATE;
@9CF     EQU   *                                                  0313
@9D1     EQU   *                                                  0313
AMACLOSE  CLOSE (SYSUTDCB)    CLOSE THE SYSUTDCB
         DS    0H
*    GO TO AMARET2;                  /* RETURN TO AMAPTFLE            *
         BC    15,AMARET2                                         0314
*
* /********************************************************************
* /********************************************************************
* /********************************************************************
* /*    SET UP FOR MESSAGE AMA0006I                                   *
* /********************************************************************
*
*
* AMA6IB:
*    NN = '01';                      /* SET UNSUCCESSFUL              *
AMA6IB   MVC   AMA006I+53(2),@C19                                 0315
*                                    /* BLDL CODE IN MSG              *
*    GO TO AMAMV6I;                  /* MOVE REMAINDER OF MSG         *
         BC    15,AMAMV6I                                         0316
*
* AMA6II:
*    NN = '02';                      /* SET UNSUCCESSFUL              *
AMA6II   MVC   AMA006I+53(2),@C20                                 0317
*                                    /* L.E. CODE IN MSG              *
*
* AMAMV6I:
*    MSGBUF = AMA006I;               /* MOVE MSG INTO BUFFER          *
AMAMV6I  MVC   MSGBUF(55),AMA006I                                 0318
         MVI   MSGBUF+55,C' '                                     0318
         MVC   MSGBUF+56(65),MSGBUF+55                            0318
*    IF RETCDE < '08'X THEN          /* CODE < 8                A48711*
         CLI   2(@5),X'08'                                        0319
         BC    10,@9CE                                            0319
*      RETCDE='08'X;                 /* YES. CHANGE TO 8        A48711*
         MVI   2(@5),X'08'                                        0320
*    CALL AMAERMSG;                  /* WRITE MESSAGE                 *
@9CE     L     @F,@V1              ADDRESS OF AMAERMSG            0321
         BALR  @E,@F                                              0321
*    IF NN = '02' THEN               /*BAD LINK EDIT             M0867*
         CLC   AMA006I+53(2),@C20                                 0322
*      GO TO OPENOUTF;               /*YES-OPEN OUTF             M0867*
         BC    08,OPENOUTF                                        0323
*    OPENREG=OUTFDCB;                /* GET DCB ADDRESS         A53522*
         L     @3,28(0,@5)                                        0324
*    GENERATE;                       /* POSITION DATA SET       A53522*
        CLOSE   ((OPENREG),REREAD),TYPE=T
         DS    0H
*    GO TO AMARET2;                  /* RETURN TO AMAPTFLE            *
         BC    15,AMARET2                                         0326
*
* AMANOID:                           /* NO IDENTIFY CARD       S21016 *
*    MSGBUF = AMA010I;               /* MOVE MSG TO BUFF       S21016 *
AMANOID  MVC   MSGBUF(62),AMA010I                                 0327
         MVI   MSGBUF+62,C' '                                     0327
         MVC   MSGBUF+63(58),MSGBUF+62                            0327
*    RETCDE='10'X;                   /* SET 16 RETURN CODE      A48711*
         MVI   2(@5),X'10'                                        0328
*    GO TO AMACALL;                  /* WRITE MESSAGE AND             *
         BC    15,AMACALL                                         0329
*                                    /* RETURN TO FILCLOSE            *
*
* /********************************************************************
* /********************************************************************
* /*    AMASYNAD IS THE SYNAD IN CASE OF AN I/O ERROR.                *
* /*    RETURN IS TO THE SYNADAF ROUTINE IN AMAPTFLE                  *
* /********************************************************************
*
*
* AMASYNAD:
*    GENERATE;                       /*                         M4013 *
AMASYNAD EQU   *                                                  0330
         L     13,4(0,13)                                         M4013
         L     14,32(0,5)                                         M4013
         LM    2,12,28(13)        DO NOT RESTORE REGISTERS 0 OR 1 M4013
         BCR   15,14                                              M4013
         DS    0H
*
* /********************************************************************
* /********************************************************************
*
*    RESPECIFY DUMFIELD BASED(MSGAREA);
*
* /********************************************************************
* /*    AMADDMSG INITIALIZES THE ERROR MESSAGE FOR AN                 *
* /*    UNSUCCESSFUL OPEN OF THE DCBS.                                *
* /********************************************************************
*
*
* AMADDSYS:
*    DUMFIELD(41:47) = DDSYSL;       /* MOVE IN DDNAME          M4012 *
AMADDSYS L     @2,36(0,@5)         
         MVC   40(7,@2),DDSYSL                                    0332
*    GO TO AMADDRET;                 /* RETURN TO AMAPTFLE            *
         BC    15,AMADDRET                                        0333
*
* AMADDMSG:
*    DUMFIELD(41:46) = DDMSG;        /* MOVE IN DDNAME                *
AMADDMSG L     @2,36(0,@5)         
         MVC   40(6,@2),DDMSG                                     0334
*    GO TO AMADDRET;                 /* RETURN TO AMAPTFLE      M4000 *
         BC    15,AMADDRET                                        0335
*
* AMADDOUT:
*    DUMFIELD(41:44) = DDMSGOUT;      /* MOVE IN DDNAME               *
AMADDOUT L     @2,36(0,@5)         
         MVC   40(4,@2),DDMSGOUT                                  0336
*
* AMADDRET:
*    RETURN TO MESSAGE2;             /* RETURN TO AMAPTFLE            *
AMADDRET L     @D,4(0,@D)                                         0337
         L     @E,52(0,@5)                                        0337
         LM    @F,@C,16(@D)                                       0337
         BCR   15,@E                                              0337
*                                    /* TO WRITE ERROR MESSAGE        *
*
* AMARET2:
*    BRFIELD = 0;                    /* CLEAR BRANCH TAB INDEX        *
AMARET2  MVI   0(@5),0                                            0338
*
* AMARET1:
*    RETURN;                         /* RETURN TO AMAPTFLE            *
         BC    15,@EL01                                           0339
*
* /********************************************************************
* /********************************************************************
* /*    AMAERMSG IS AN INTERNAL SUBROUTINE THAT IS CALLED TO          *
* /*    WRITE MESSAGES.                                               *
* /********************************************************************
*
*
* AMAERMSG:
*    PROC;
@EL01    L     @D,4(0,@D)                                         0340
         LM    @E,@C,12(@D)                                       0340
         BCR   15,@E                                              0340
AMAERMSG STM   @E,@C,12(@D)                                       0340
         ST    @D,@SAV002+4                                       0340
         LA    @F,@SAV002                                         0340
         ST    @F,8(0,@D)                                         0340
         LR    @D,@F                                              0340
*    OPENREG = PRINTDCB;             /* GET DCB ADDRESS               *
         L     @3,40(0,@5)                                        0341
*    GENERATE;
           WRITE ERRDECB,SF,(OPENREG),MSGBUF   WRITE THE MESSAGE
           CHECK ERRDECB
         DS    0H
*    RETURN;                         /* RETURN TO MSG CALLER          *
         BC    15,@EL01                                           0343
*
* /********************************************************************
* /********************************************************************
*
*    GENERATE;
SYSUTDCB   DCB DDNAME=SYSUT2,DSORG=PS,MACRF=(RP,W),LRECL=80,BLKSIZE=80,C
               SYNAD=AMASYNAD,EODAD=AMAEODAD,RECFM=F              M4005
         DS    0H
*
* /********************************************************************
*
*    END AMAERMSG;
         BC    15,@EL01                                           0345
*    END AMAPTF01;
@DATA1   EQU   *
@0       EQU   00                  EQUATES FOR REGISTERS 0-15
@1       EQU   01
@2       EQU   02
@3       EQU   03
@4       EQU   04
@5       EQU   05
@6       EQU   06
@7       EQU   07
@8       EQU   08
@9       EQU   09
@A       EQU   10
@B       EQU   11
@C       EQU   12
@D       EQU   13
@E       EQU   14
@F       EQU   15
@D1      DC    H'5'
@D2      DC    H'1'
@D3      DC    H'8'
@D4      DC    H'-2'
@D5      DC    H'12'
@D6      DC    H'16'
@D7      DC    H'71'
@D8      DC    H'72'
@D9      DC    H'6'
@MVC     MVC   0(1,@A),0(@E)
@V1      DC    A(AMAERMSG)
         DS    0F
@C13     DC    C'        '
@C14     DC    C'NAME'
@C15     DC    C'IDENTIFY'
@X2      DC    X'0000'
@X12     DC    X'0001'
@C19     DC    C'01'
@C20     DC    C'02'
         DS    0D
@DATA    EQU   *
@SAV001  EQU   @DATA+00000000      72 BYTE(S) ON WORD
OPENREG  EQU   00000003            FULLWORD POINTER REGISTER
         ORG   @DATA+00000072
OPENBIT  EQU   *                   1 BIT(S) ON BYTE
         DC    B'00000000'
RETCODE  EQU   00000015            FULLWORD INTEGER REGISTER
LSTPTR   EQU   00000001            FULLWORD POINTER REGISTER
LSTPTRSV EQU   00000005            FULLWORD POINTER REGISTER
I        EQU   00000006            FULLWORD POINTER REGISTER
PRMLST   EQU   00000000            72 BYTE(S) ON WORD
BRFIELD  EQU   PRMLST+00000000     1  BYTE  POINTER
IDENTCON EQU   PRMLST+00000001     1  BYTE  POINTER
RETCDE   EQU   PRMLST+00000002     1  BYTE  POINTER
COMSW    EQU   PRMLST+00000003     1  BYTE  POINTER
MODSTORE EQU   PRMLST+00000004     FULLWORD POINTER
OVTABADR EQU   PRMLST+00000008     FULLWORD POINTER
PTF01    EQU   PRMLST+00000012     FULLWORD POINTER
PTF02    EQU   PRMLST+00000016     FULLWORD POINTER
PCHAREA  EQU   PRMLST+00000020     FULLWORD POINTER
MODAREA  EQU   PRMLST+00000024     FULLWORD POINTER
OUTFDCB  EQU   PRMLST+00000028     FULLWORD POINTER
SYNADEXT EQU   PRMLST+00000032     FULLWORD POINTER
MSGAREA  EQU   PRMLST+00000036     FULLWORD POINTER
PRINTDCB EQU   PRMLST+00000040     FULLWORD POINTER
SELNAME  EQU   PRMLST+00000044     FULLWORD POINTER
SSISAVE  EQU   PRMLST+00000048     FULLWORD POINTER
MESSAGE2 EQU   PRMLST+00000052     FULLWORD POINTER
MODTBL   EQU   PRMLST+00000056     FULLWORD POINTER
SSITABLE EQU   PRMLST+00000060     FULLWORD POINTER
PARMPTR  EQU   PRMLST+00000064     FULLWORD POINTER
FILCLOSE EQU   PRMLST+00000068     FULLWORD POINTER
DDMSGOUT EQU   *                   4 BYTE(S)
         DC    C'OUTF'
DDMSG    EQU   *                   6 BYTE(S)
         DC    C'SYSUT2'
DDSYSL   EQU   *                   7 BYTE(S)
         DC    C'SYSLMOD'
MODSTRBF EQU   00000000            8 BYTE(S)
NAMMATCH EQU   *                   1  BYTE  POINTER
         DC    AL1(0)
         ORG   @DATA+00000092
BRTABLE  EQU   *                   6*FULLWORD POINTER
         DC    AL4(AMAOPEN)
         DC    AL4(AMASPOBJ)
         DC    AL4(AMALINK)
         DC    AL4(AMACLOSE)
         DC    AL4(AMASPS)
         DC    AL4(AMALEPRM)
MSGBUF   EQU   @DATA+00000116      121 BYTE(S)
UT2OUT   EQU   @DATA+00000237      80 BYTE(S)
DUMFIELD EQU   00000000            80 BYTE(S)
         ORG   @DATA+00000320
TTRZ     EQU   *                   4 BYTE(S) ON WORD
         DC    C' '
         DC    00003C' '
ENDPARM  EQU   @DATA+00000324      1 BYTE(S)
         ORG   @DATA+00000326
BLDLFLD  EQU   *                   72 BYTE(S) ON HWORD
         DC    C' '
         DC    00071C' '
PTF02ADR EQU   @DATA+00000400      FULLWORD POINTER
NAMECARD EQU   @DATA+00000404      21 BYTE(S) ON WORD
         ORG   NAMECARD+00000000
NME      EQU   *                   10 BYTE(S)
         DC    C'     NAME '
MDN      EQU   NAMECARD+00000010   11 BYTE(S)
         ORG   @DATA+00000425
REP      EQU   *                   3 BYTE(S)
         DC    C'(R)'
NEWNAME  EQU   *                   1 BYTE(S)
         DC    X'00'
IDFOUND  EQU   *                   1 BYTE(S)
         DC    X'80'
ALIASCD  EQU   @DATA+00000432      15 BYTE(S) ON WORD
         ORG   ALIASCD+00000000
A00000   EQU   *                   7 BYTE(S)
         DC    C' ALIAS '
ALIASNM  EQU   ALIASCD+00000007    8 BYTE(S)
SSICARD  EQU   @DATA+00000448      20 BYTE(S) ON WORD
         ORG   SSICARD+00000000
SETSSI   EQU   *                   12 BYTE(S)
         DC    C'     SETSSI '
SSIINFO  EQU   SSICARD+00000012    8 BYTE(S)
SELBUF   EQU   00000000            8 BYTE(S)
PRMFIELD EQU   00000000            102 BYTE(S) ON WORD
PARMLEN  EQU   PRMFIELD+00000000   HALFWORD POINTER
PARM     EQU   PRMFIELD+00000002   100 BYTE(S)
         ORG   @DATA+00000468
LKEDNAME EQU   *                   8 BYTE(S)
         DC    C' '
         DC    00007C' '
AMA005I  EQU   *                   54 BYTE(S)
         DC    C'AMA005I  INVALID PARAMETER SPECIFIED ON EX'
         DC    C'EC STATEMENT'
AMA006I  EQU   @DATA+00000532      55 BYTE(S) ON WORD
         ORG   AMA006I+00000000
A00001   EQU   *                   21 BYTE(S)
         DC    C'AMA006I  LOAD MODULE '
CCCCCCCC EQU   AMA006I+00000021    8 BYTE(S)
         ORG   AMA006I+00000029
A00002   EQU   *                   24 BYTE(S)
         DC    C' NOT UPDATED WITH PTF - '
NN       EQU   AMA006I+00000053    2 BYTE(S)
AMA007I  EQU   @DATA+00000588      68 BYTE(S) ON WORD
         ORG   AMA007I+00000000
A00003   EQU   *                   21 BYTE(S)
         DC    C'AMA007I  LOAD MODULE '
LLLLLLLL EQU   AMA007I+00000021    8 BYTE(S)
         ORG   AMA007I+00000029
A00004   EQU   *                   31 BYTE(S)
         DC    C' UPDATED WITH PTF - NEW SSI IS '
SSI      EQU   AMA007I+00000060    8 BYTE(S)
AMA010I  EQU   @DATA+00000656      62 BYTE(S) ON WORD
         ORG   AMA010I+00000000
A00005   EQU   *                   29 BYTE(S)
         DC    C'AMA010I  AMAPTFLE TERMINATED,'
A00006   EQU   *                   33 BYTE(S)
         DC    C' AN IDENTIFY STATEMENT IS MISSING'
AMA013I  EQU   @DATA+00000720      66 BYTE(S) ON WORD
         ORG   AMA013I+00000000
A00007   EQU   *                   26 BYTE(S)
         DC    C'AMA013I  THE FOLLOWING IS '
A00008   EQU   *                   32 BYTE(S)
         DC    C'IDENTIFY INFORMATION FOR MODULE '
AMA013NM EQU   *                   8 BYTE(S)
         DC    C'        '
AMA016I  EQU   @DATA+00000788      61 BYTE(S) ON WORD
         ORG   AMA016I+00000000
A00009   EQU   *                   29 BYTE(S)
         DC    C'AMA016I  AMAPTFLE TERMINATED,'
A00010   EQU   *                   32 BYTE(S)
         DC    C' PARMLIB DD STATEMENT IS MISSING'
DIFF     EQU   @DATA+00000852      FULLWORD INTEGER
QUOTIENT EQU   @DATA+00000856      FULLWORD INTEGER
ADDFACTR EQU   @DATA+00000860      FULLWORD INTEGER
CORRSSI  EQU   @DATA+00000864      FULLWORD POINTER
SSIDATA  EQU   00000000            8 BYTE(S)
RETCDSAV EQU   @DATA+00000868      FULLWORD INTEGER
DDNMELST EQU   @DATA+00000872      66 BYTE(S) ON HWORD
         ORG   DDNMELST+00000000
A00011   EQU   *                   HALFWORD POINTER
         DC    AL2(64)
A00012   EQU   *                   8 BYTE(S)
         DC    C'OUTF    '
A00013   EQU   *                   8 BYTE(S)
         DC    X'0000000000000000'
A00014   EQU   *                   8 BYTE(S)
         DC    C'SYSLMOD '
A00015   EQU   *                   8 BYTE(S)
         DC    X'0000000000000000'
A00016   EQU   *                   8 BYTE(S)
         DC    X'0000000000000000'
A00017   EQU   *                   8 BYTE(S)
         DC    C'SYSPRINT'
A00018   EQU   *                   8 BYTE(S)
         DC    X'0000000000000000'
A00019   EQU   *                   8 BYTE(S)
         DC    C'SYSUT1  '
PARMCONT EQU   *                   1 BIT(S) ON BYTE
         DC    B'00000000'
PCHBUFFR EQU   00000000            80 BYTE(S)
         ORG   @DATA+00000940
PRMNUMBR EQU   *                   HALFWORD POINTER
         DC    XL2'0000'
PARMEQUL EQU   *                   5 BYTE(S)
         DC    C'PARM='
B        EQU   @DATA+00000948      HALFWORD POINTER
         ORG   @DATA+00000950
DSSDNME  EQU   *                   8 BYTE(S)
         DC    C'PARMLIB '
DEVDATA  EQU   @DATA+00000960      8 BYTE(S) ON WORD
         ORG   @DATA+00000968
PATCH    EQU   *                   50*2 BYTE(S) ON HWORD
         DC    00050X'0000'
@SAV002  EQU   @DATA+00001068      72 BYTE(S) ON WORD
         ORG   @DATA
         DS    00001140C
@TEMPS   DS    0F
@TEMP2   DC    F'0'
@DATEND  EQU   *
@9F8     EQU   AMANOID
@9EC     EQU   MOVEREP
@9EB     EQU   MOVEREP
@9E8     EQU   AMA6IB
@9E4     EQU   AMA6II
CHKSPACE EQU   @DO9DF
CHKSP2   EQU   @DO9DB
AMACONT  EQU   AMARET2
@9D0     EQU   AMAPRM2
AMARET1  EQU   @EL01
@EL02    EQU   @EL01
@9FA     EQU   AMARET1
@9FC     EQU   AMARET1
@9F6     EQU   AMARET1
@9E1     EQU   CHKSPACE
@9F7     EQU   @9F6
         END   AMAPTF01
