#!/bin/bash
#**********************************************************************
#***                                                                ***
#*** Script:  set_daemon_mode                                       ***
#***                                                                ***
#*** Purpose: Activate daemon mode (TK4- unattended operations)     ***
#***                                                                ***
#*** Updated: 2013/11/26                                            ***
#***                                                                ***
#**********************************************************************
echo "DAEMON">mode
echo "Hercules daemon mode activated for unattended operations (mvs.bat)"
read -p "Press any key to continue..."
