#!/bin/bash
#**********************************************************************
#***                                                                ***
#*** Script:  set_console_mode                                      ***
#***                                                                ***
#*** Purpose: Activate console mode (TK4- unattended operations)    ***
#***                                                                ***
#*** Updated: 2013/11/26                                            ***
#***                                                                ***
#**********************************************************************
echo "CONSOLE">mode
echo "Hercules console mode activated for unattended operations (mvs.bat)"
read -p "Press any key to continue..."
