//*------------------------------------------------------------------*
//*       INSTALLATION OF THE MVS VERSION OF 'DISKMAP'               *
//*------------------------------------------------------------------*
//  EXEC  ASMHCL,PARM.LKED='AC=1,LIST,LET,MAP,XREF',SYSOUT='*'
//ASM.SYSLIB DD  DISP=SHR,DSN=SYS1.MACLIB
//          DD  DISP=SHR,DSN=SYS1.AMODGEN,UNIT=3330-1,VOL=SER=DLIBL1
//SYSIN    DD DSN=ASMI99U.MI110.SOURCE(XDISKMAP),DISP=SHR
//LKED.SYSLMOD  DD  DISP=SHR,DSN=SYS1.LINKLOAD(XDISKMAP)
