*        FULLSAVE
         MACRO
&NAME    FULLSAVE &BASEREG=12,&LV=,&SP=,&RENT=YES,&AREA=,&IDENT=*
         LCLA  &LCLA
         LCLC  &C(9),&LVA,&SPA
         AIF   ('&RENT' NE 'NO').TESTYES
         AIF   (T'&LV NE 'O').MNOTE
         AIF   (T'&SP EQ 'O').SAVE
.MNOTE   MNOTE 8,'IF RENT=NO, NEITHER LV NOR SP MAY BE SPECIFIED'
         MEXIT
.TESTYES AIF   ('&RENT' EQ 'YES' OR '&RENT' EQ 'SPECIAL').ISRENT
         MNOTE 8,'IF RENT PARAMETER IS SPECIFIED, IT MUST HAVE THE VALUX
               E ''YES'', ''NO'', OR ''SPECIAL''.'
         MEXIT
.ISRENT  AIF   (T'&LV NE 'O').TSTSP
&LVA     SETC  '72'
.TSTSP   AIF   (T'&SP NE 'O').SAVE
&SPA     SETC  '0'
.SAVE    ANOP
         AIF   (N'&BASEREG LT 10).GENBASE
         MNOTE 8,'TOO MANY BASE REGISTERS SPECIFIED. MAXIMUM PERMITTED X
               IS 9.'
         MEXIT
.GENBASE ANOP
&LCLA    SETA  &LCLA+1
&C(&LCLA) SETC ','
         AIF   (&LCLA LT N'&BASEREG).GENBASE
         DS    0H   ALIGN FOR FOLLOWING USING STATEMENT
 USING *&C(1)&BASEREG(1)&C(2)&BASEREG(2)&C(3)&BASEREG(3)&C(4)&BASEREG(4X
               )&C(5)&BASEREG(5)&C(6)&BASEREG(6)&C(7)&BASEREG(7)&C(8)&BX
               ASEREG(8)&C(9)&BASEREG(9) ESTABLISH ADDRESSABILITY
*              SAVE CALLER'S REGISTERS
&NAME    SAVE  (14,12),T,&IDENT
         LR    &BASEREG(1),15 LOAD BASE REGISTER FROM INITIAL ENTRY REGX
               ISTER
         AIF   ('&RENT' EQ 'NO').NOTRENT
*              GETMAIN FOR NEW SAVEAREA
         AIF   ('&RENT' EQ 'SPECIAL').SPECIAL
         GETMAIN    R,LV=&LV.&LVA,SP=&SP.&SPA
         AGO   .STORE13
.SPECIAL GETCORE    R,LV=&LV.&LVA,SP=&SP.&SPA
         AGO   .STORE13
.NOTRENT AIF   (T'&AREA EQ 'O').DS18F
         B     LOAD&SYSNDX    SPACE OVER SAVEAREA ADCON
         DC    A(&AREA)  SAVEAREA POINTER
LOAD&SYSNDX L  1,*-4  GET ADDRESS OF NEW SAVEAREA
         AGO   .STORE13
.DS18F   B     LOAD&SYSNDX    SPACE OVER NEW SAVEAREA
         DS    18F  NEW SAVEAREA
LOAD&SYSNDX LA 1,*-72    GET ADDRESS OF NEW SAVEAREA
.STORE13 ST    13,4(1)   STORE OLD SAVEAREA ADDRESS IN NEW SAVEAREA
         ST    1,8(13)   STORE NEW SAVEAREA ADDRESS IN OLD SAVEAREA
         LR    0,1  TEMPORARILY MOVE NEW SAVEAREA ADDRESS TO REG 0
         LR    1,13 MOVE OLD SAVEAREA ADDRESS TO REG 1
         LR    13,0 MOVE NEW SAVEAREA ADDRESS TO REG 13
         AIF   (N'&BASEREG EQ 1).AIFAREA
&LCLA    SETA  1
         LA    &BASEREG(N'&BASEREG),4095 SET INCREMENT FOR ADDITIONAL BX
               ASE REGISTERS
.BASELA  LA    &BASEREG(&LCLA+1),1(&BASEREG(&LCLA),&BASEREG(N'&BASEREG)X
               ) SET NEXT BASE REGISTER
&LCLA    SETA  &LCLA+1
         AIF   (&LCLA LT N'&BASEREG).BASELA
.AIFAREA AIF   ('&AREA' EQ '').LM
         USING &AREA,13  MAKE NEW SAVEAREA ADDRESSABLE
.LM      LM    0,1,20(1) RESTORE REGISTERS 0 AND 1 FROM OLD SAVEAREA
         MEND
*        TRANSFERRED FROM HAMMER   - 09/16/70
*
