         MACRO
&NAME    FULLRTRN   &LV=,&SP=,&RC=0,&RENT=YES
         LCLC  &LVA,&SPA
         AIF   ('&RENT' EQ 'YES' OR '&RENT' EQ 'SPECIAL').ISRENT
         AIF   ('&RENT' EQ 'NO').NOTRENT
         MNOTE 8,'IF RENT PARAMETER IS SPECIFIED, IT MUST HAVE THE VALUX
               E ''YES'', ''NO'', OR ''SPECIAL''.'
         MEXIT
.NOTRENT AIF   (T'&LV EQ 'O').TSTSP
.LVSPMSG MNOTE 8,'IF RENT=NO, NEITHER LV NOR SP MAY BE SPECIFIED'
         MEXIT
.TSTSP   AIF   (T'&SP NE 'O').LVSPMSG
&NAME    L     13,4(13)  GET CALLER'S SAVEAREA ADDRESS
         AGO   .RETURN
.ISRENT  AIF   (T'&SP NE 'O').TSTLV
&SPA     SETC  '0'
.TSTLV   AIF   (T'&LV    NE 'O').GENER
&LVA     SETC  '72'
         AGO   .LR
.GENER   AIF   ('&LV' NE '0').LR
&NAME    SR    1,1 ZERO REGISTER TO INDICATE ENTIRE SUBPOOL BEING FREED
         AGO   .LOAD13
.LR      ANOP
&NAME    LR    1,13 LOAD CURRENT SAVEAREA ADDRESS IN REG 1
.LOAD13  L     13,4(13)  GET CALLER'S SAVEAREA ADDRESS
*              EXECUTE FREEMAIN MACRO
         AIF   ('&RENT' EQ 'SPECIAL').SPECIAL
         FREEMAIN R,LV=&LV.&LVA,SP=&SP.&SPA,A=(1)
         AGO   .RETURN
.SPECIAL FREECORE   R,LV=&LV.&LVA,SP=&SP.&SPA,A=(1)
.RETURN  ANOP
*              RETURN TO CALLER
         RETURN (14,12),T,RC=&RC
         MEND
