.cm SCRIPT REFERENCE OPTIONS
.ur .if '&UPDATE' ne '' and '&UPDATE' gt '771208';.th .ef
.in
.us Options:
.sr options=%
.sp
.sr refcard = N
.go NOTCARD
.lb SCRIPTCD
.sr refcard = Y
.lb NOTCARD
.ur .if &refcard eq N .th .do begin
The options control formatting of output and the mechanical processes
of the output device.
Options may be delimited by blanks
and keyword operands may be delimited on the left with an
equal sign or the operand surrounded by parentheses.
.do end
Capital letters indicate minimum shortforms.
Underscores indicate default values.
.sp
.ur .if &refcard eq N .th .do begin;.cp begin
ADjust / N_O_A_D_j_u_s_t_ / ADjust=<0_×n>
.in +4
Causes all the output to be printed up to fifty columns from the left
print margin.
ADJUST by itself defaults to thirty columns, but ADJUST= may specify
from zero to fifty columns.
.in -4;.cp end;.do end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
CEntre / N_O_C_E_n_t_r_e_ / CEntre=<0_×n>
.br
CENTEr / N_O_C_E_N_T_E_r_ / CENTEr=<0_×n>
.in +4
Alternate forms of ADJUST, for compatability
with former versions of SCRIPT.
.in -4;.cp end;.do end
.sp;.cp begin
COntinue / N_O_C_O_n_t_i_n_u_e_ / COntinue=<0_×n>
.in +4
Specifies the number of errors which are to be allowed before processing
is terminated.
The value of "n" may range from 0 to 32767;
NOCO is the same as CO=0, and
CO is the same as CO=32767.
.in -4
.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
DEBUG / N_O_D_E_B_U_G_
.br
S_P_I_E_  / NOSPIE
.in +4
This is a debugging tool for the person maintaining the SCRIPT program.
It prevents a program interrupt exit from
being set, thus preventing a SCRW999T diagnostic from occurring.
.in -4;.cp end;.do end
.sp;.cp begin
FIle / N_O_F_I_l_e_
.in +4
When used in combination with the TERMINAL option, this causes
output to be written to the usual offline file but in a format
suitable for an online terminal.
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
F_O_r_m_a_t_t_e_d_ / UNformatted
.in +4
The specified file is printed along with all control lines.
No other processing takes place.
.in -4;.cp end;.do end
.sp;.cp begin
FNSize=<2_0_0_×n>
.in +4
Specifies the maximum number of output lines (from 1 to 32767)
that may be outstanding in a Keep or Footnote at any one time.
.in -4;.cp end
.sp;.cp begin
HSFSover=<9_×n>
.in +4
Specifies the maximum number of top and bottom titles that
may be defined.
See the .TT control word for a description of how these
titles are shared.
The numeric operand may range from 2 to 19.
.in -4;.cp end
.sp;.cp begin
LINenumber=<0_×n> / LEGalnumber=<0_×n>
.in +4
LIN= causes the current output line number within the
page to be displayed if the output line is non-blank and that portion of
the output line starting at column
"n" (ranging from 1 to 125) is otherwise blank.
LEG= numbers only non-blank lines in the text area.
LIN= and LEG= are mutually exclusive.
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
L_O_C_A_L_ / GLOBAL
.in +4
Causes the parameter variables "&0", "&1", etc.
to be entered in a dictionary local to the file being
called or to be entered in the global dictionary.
.in -4;.cp end;.do end
.sp;.cp begin
MArk / N_O_M_A_r_k_
.in +4
Marks the beginning of each line of the original input by
underscoring the first character of each record.
.in -4;.cp end
.sp;.cp begin
NUmber / N_O_N_U_m_b_e_r_ / NUmber=<0_×n>
.in +4
Displays the number of the record in the input file being processed
when the current output line was printed.
The value of "n" (from 1 to 100) defines the starting column in the outp
line where this information is to appear, if those columns
would otherwise be blank.  NONU is the same as NU=0.
NU is the same as NU=1 with an ADjust of 30.
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
OFfline or PRinter
.in +4
Causes the output to be edited and formatted for the off-line printer.
.in -4;.cp end;.do end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
ONline or TErminal
.in +4
Causes output lines to be formatted for an online terminal.
This option is mutually exclusive of the PRinter option.
.in -4;.cp end;.do end
.sp;.cp begin
PAge=<1_×m<:n>>
.in +4
Input is processed but output is not produced until the start of
page "m".
If a second number "n" is specified, processing and output will terminat
after page "n" has been produced.
.ur .if &refcard eq N .th .do begin
The PAGE= option may be useful for restart purposes (i.e. PAGE=5)
or for checking single pages of output (i.e. PA=5:5).
.do end
.in -4;.cp end
.sp;.cp begin
PASses=<1_×n>
.in +4
Causes SCRIPT to make "n-1" complete
passes through the input file,
performing all indicated formatting but not producing
any output.  A last pass is then made, during which output is produced.
The value of "n" may range from 1 to 10.
.ur .if &refcard eq N .th .do begin
This option is useful for processing a file which uses reference
variables defined later in the input.
.do end
.in -4;.cp end
.sp;.cp begin
PRinter or OFfline
.in +4
Causes the output to be edited and formatted for the off-line printer.
.ur .if &refcard eq N .th .do begin
It is recommended that PRinter be
used when proof-reading the output.
.do end
.in -4;.cp end
.sp;.cp begin
PROFile / N_O_P_R_O_F_i_l_e_
.in +4
Causes an imbed (.IM) of a file called PROFILE
automatically at the start of each pass.
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
TWOPass or 2Pass / O_N_E_P_a_s_s_ or 1Pass
.in +4
The TWOPASS option is a shortform for PASSES=2.  The ONEPASS option
is a shortform for PASSES=1.
.in -4;.cp end;.do end
.sp;.cp begin
QUiet / N_O_Q_U_i_e_t_
.in +4
If TErminal is in effect, QUiet
causes the SCRIPT version identification line to be suppressed.
.in -4;.cp end
.sp;.cp begin
RMSize=<2_0_0_×n>
.in +4
Specifies the maximum number of input records (from 1 to 32767)
that may be included
in any single remote (see .RM) definition.
.in -4;.cp end
.sp;.cp begin
SCREen / N_O_S_C_R_E_e_n_
.in +4
Specifies that the output device is a SCREEN or CRT device.
It is effective only for TErminal output.
SCREEN is set as the default if the output device is
known to be a CRT.  The effect is to print overstruck output
on one or more consecutive lines instead of using "backspace and undersc
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
SEQColumn=<2_4_0_×n>
.in +4
Specifies the first of eight contiguous columns (from 1 to 240)
where the input
record sequence number may be found for variable-length input files.
SEQ=0 means that no sequence numbers are present.
If "n" is greater than the length of
a record, then the last eight columns are presumed to contain
the sequence number for that record.
.in -4;.cp end;.do end
.sp;.cp begin
S_I_X_ / EIGHT
.in +4
The SIX option defines the initial Page Length for six
lines per inch on an eleven inch page
and line three set to the first normal print line on the page.
The EIGHT option defines the initial Page Length for eight
lines per inch on an eleven inch page
and line four set to the first normal print line on the page.
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
SRLength=<1_5_0_×n>
.in +4
Specifies the maximum length of character-string operands for
reference variables; "n" may range
from 4 to 240.
.in -4;.cp end;.do end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
STATistics / N_O_S_T_A_T_i_s_t_i_c_s_
.in +4
Causes various and sundry statistics information to be printed
on the SYSTERM data set.
.in -4;.cp end;.do end
.sp;.cp begin
STop / N_O_S_T_o_p_
.in +4
Causes a pause at the bottom of each page when producing online output.
This pause allows the user to insert the next page.
The pause is terminated by a carriage return.
.in -4;.cp end
.sp;.cp begin
TABLeft=<0_×1>
.in +4
Controls the operation of a Left Tab.
A "0" value makes Left Tabs work like a typewriter,
with the character following a tab being placed
in the column specified.
A "1" value makes the character following a Left Tab
go immediately after the column specified.
See the Tab control word (.TB).
.in -4;.cp end
.sp;.cp begin
TErminal or ONline
.in +4
Causes output lines to be formatted for an online terminal.
This option is mutually exclusive of the PRinter option.
.in -4;.cp end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
UPcase / N_O_U_P_c_a_s_e_
.br
TRanslate / N_O_T_R_a_n_s_l_a_t_e_
.in +4
Causes character translation using a translate table that contains
as default lower to upper case mapping.  Other
types of translation may be specified with the .TR control word.
.in -4;.cp end;.do end
.ur .if &refcard eq N .th .do begin;.sp;.cp begin
U_P_P_e_r_ / NOUPPer
.in +4
The UPPER option causes all SET REFERENCE symbols to be converted
to upper case before symbol table lookups.
.in -4;.cp end;.do end
.sp;.cp begin
W_A_i_t_ / NOwait
.in +4
Causes output to begin immediately without waiting for the first page
to be positioned by the user.
This option has no effect when producing off-line output.
.in -4;.cp end
.sp;.cp begin
&name=string OR +name=string
.in +4
At the beginning of the first pass, a ".SR
line will be executed for each such option in the options list.
See the ".SR" control word for operand format rules.  This
is useful for setting switch values externally to the SCRIPT input.
.in -4;.cp end
.sp;.cp begin
The following options maybe used to set initial and default values
for the corresponding control words:
.sp
.in +8
.fo no
.ur .bx &sysin +18 +22
     Parameter      Minimum   Maximum
.bx
  ADjust=<0_×n>         0        50
  BMargin=<6_×n>        0        33
  DArk=<1_×n>           1        10
  FMargin=<1_×n>        0        33
  HMargin=<1_×n>        0        33
  LLength=<6_0_×n>      10       144
  PLength=<6_6_×n>      10       176
  TMargin=<6_×n>        0        33
.bx off
.fo yes
.cp end
.in
.pa
.cm End of OPTIONS
