         TITLE '***** IDCTSRL0 - REPLACEC STATIC TEXT *****' @Y30LB32
************************************************************ @Y30LB32
*                                                          * @Y30LB32
* MODULE NAME - IDCTSRL0                                   * @Y30LB32
*                                                          * @Y30LB32
*                                                          * @Y30LB32
* DESCRIPTIVE NAME - STATIC TEXT MODULE FOR THE            * @Y30LB32
*                    REPLACEC FUNCTION                     * @Y30LB32
*                                                          * @Y30LB32
* COPYRIGHT - NONE                                         * @Y30LB32
*                                                          * @Y30LB32
* STATUS - RELEASE 0  LEVEL 0                              * @Y30LB32
*                                                          * @Y30LB32
* FUNCTION - CONTAINS NO EXECTABLE CODE, ONLY STATIC TEXT  * @Y30LB32
*        ENTRIES FOR THE REPLACEC FUNCTION                 * @Y30LB32
*        THIS MODULE IS LOADED BY IDCTP05 WHEN A STATIC    * @Y30LB32
*        TEXT REQUEST IS MADE.                             * @Y30LB32
*                                                          * @Y30LB32
* NOTES - NONE                                             * @Y30LB32
*                                                          * @Y30LB32
*        DEPENDENCIES - NONE                               * @Y30LB32
*        RESTRICTIONS - NONE                               * @Y30LB32
*        REGISTER CONVENTIONS - NA                         * @Y30LB32
*        PATCH AREA - NA                                   * @Y30LB32
*                                                          * @Y30LB32
* MODULE TYPE - TABLES                                     * @Y30LB32
*                                                          * @Y30LB32
*        PROCESSOR - ASSEMBLER                             * @Y30LB32
*        MODULE SIZE - 299                                 * @Y30LB32
*        ATTRIBUTES - READ-ONLY                            * @Y30LB32
*                                                          * @Y30LB32
* ENTRY POINT - NA                                         * @Y30LB32
*                                                          * @Y30LB32
* EXIT NORMAL - NA                                         * @Y30LB32
*                                                          * @Y30LB32
* EXIT ERROR - NA                                          * @Y30LB32
*                                                          * @Y30LB32
* EXTERNAL REFERENCES - NA                                 * @Y30LB32
*                                                          * @Y30LB32
* TABLES - NA                                              * @Y30LB32
*                                                          * @Y30LB32
* MACROS - NA                                              * @Y30LB32
*                                                          * @Y30LB32
* CHANGE ACTIVITY - NONE                                   * @Y30LB32
* CHANGE 01 03/19/75 - FCR 351 MODIFICATION - IDC791E      * @ZM30741
*                                                          * @Y30LB32
************************************************************ @Y30LB32
         EJECT                                               @Y30LB32
************************************************************ @Y30LB32
*                                                          * @Y30LB32
* THIS MODULE IS THE FIRST MODULE OF STATIC TEXT REQUIRED  * @Y30LB32
* BY THE REPLACEC FUNCTION                                 * @Y30LB32
*                                                          * @Y30LB32
************************************************************ @Y30LB32
*                                                            @Y30LB32
IDCTSRL0 CSECT                                               @Y30LB32
*                                                            @Y30LB32
INDEX    DC    Y((INDEXEND-INDEX1)/2)  COUNT OF ENTRIES      @Y30LB32
INDEX1   DC    Y(TXT1-INDEX)           MSG IDC0790I          @Y30LB32
INDEX2   DC    Y(TXT2-INDEX)           MSG IDC791E           @Y30LB32
INDEXEND DS    0H                                            @Y30LB32
         EJECT                                               @Y30LB32
**********************************************************   @Y30LB32
*                                                        *   @Y30LB32
* IDC0790I CARTRIDGE (CSN) REPLACED BY CARTRIDGE (CSN)   *   @Y30LB32
*                                                        *   @Y30LB32
**********************************************************   @Y30LB32
         SPACE 3                                             @Y30LB32
TXT1     DC    Y(TXT1B-TXT1A)          ENTRY LENGTH          @Y30LB32
         DC    X'8000'                 MESSAGE FLAG          @Y30LB32
         SPACE 1                                             @Y30LB32
* SPACING CONTROL SUB-STRUCTURE                              @Y30LB32
TXT1A    DC    X'4000'                 SPACE CONTROL FLAG    @Y30LB32
         DC    H'2'                    SPACING FACTOR        @Y30LB32
         DC    C'R '                   SPACING TYPE          @Y30LB32
         SPACE 1                                             @Y30LB32
* STATIC TEXT SUB-STRUCTURE                                  @Y30LB32
         DC    X'0400'                 STATIC TEXT FLAG      @Y30LB32
         DC    Y(STE11B-STE11A)        TEXT LENGTH           @Y30LB32
         DC    Y(STE11A-TXT1A)         TEXT OFFSET           @Y30LB32
         DC    H'1'                    PRINT COLUMN          @Y30LB32
         DC    Y(STE11B-STE11A)        PRINT FIELD LENGTH    @Y30LB32
         DC    H'0'                    CONVERSION FLAGS      @Y30LB32
         SPACE 1                                             @Y30LB32
* BLOCK DATA SUB-STRUCTURE                                   @Y30LB32
         DC    X'1000'                                       @Y30LB32
         DC    H'12,00,20,12,00'       LNG,OFST,PC,          @Y30LB32
*                                      LNG,FLG               @Y30LB32
         SPACE 1                                             @Y30LB32
* STATIC TEXT SUB-STRUCTURE                                  @Y30LB32
         DC    X'0400'                 STATIC TEXT FLAG      @Y30LB32
         DC    Y(STE12B-STE12A)        TEXT LENGTH           @Y30LB32
         DC    Y(STE12A-TXT1A)         TEXT OFFSET           @Y30LB32
         DC    H'33'                   PRINT COLUMN          @Y30LB32
         DC    Y(STE12B-STE12A)        PRINT FIELD LENGTH    @Y30LB32
         DC    X'0000'                 CONVERSION FLAGS      @Y30LB32
         SPACE 1                                             @Y30LB32
* INSERT DATA SUB-STRUCTURE                                  @Y30LB32
         DC    X'A000'                                       @Y30LB32
         DC    H'01,00,55,12,00'       LNG,OFST,PC,          @Y30LB32
*                                      LNG,FLG               @Y30LB32
         SPACE 1                                             @Y30LB32
* STATIC TEXT ENTRIES                                        @Y30LB32
STE11A   DC    C'IDC0790I CARTRIDGE'                         @Y30LB32
STE11B   EQU   *                                             @Y30LB32
STE12A   DC    C'REPLACED BY CARTRIDGE'                      @Y30LB32
STE12B   EQU   *                                             @Y30LB32
TXT1B    EQU   *                                             @Y30LB32
         EJECT                                               @Y30LB32
**********************************************************   @Y30LB32
*                                                        *   @Y30LB32
* IDC791E REPLACED CARTRIDGE (CSN) EJECTED; (JJJ) (SSS)  *   @Y30LB32
*                                                        *   @Y30LB32
**********************************************************   @Y30LB32
         SPACE 3                                             @Y30LB32
TXT2     DC    Y(TXT2B-TXT2A)          ENTRY LENGTH          @Y30LB32
         DC    X'8000'                 MESSAGE FLAG          @Y30LB32
         SPACE 1                                             @Y30LB32
* SPACING CONTROL SUB-STRUCTURE                              @Y30LB32
TXT2A    DC    X'4000'                 SPACE CONTROL FLAG    @Y30LB32
         DC    H'2'                    SPACING FACTOR        @Y30LB32
         DC    C'R '                   SPACING TYPE          @Y30LB32
         SPACE 1                                             @Y30LB32
* STATIC TEXT SUB-STRUCTURE                                  @Y30LB32
         DC    X'0400'                 STATIC TEXT FLAG      @Y30LB32
         DC    Y(STE21B-STE21A)        TEXT LENGTH           @Y30LB32
         DC    Y(STE21A-TXT2A)         TEXT OFFSET           @Y30LB32
         DC    H'1'                    PRINT COLUMN          @Y30LB32
         DC    Y(STE21B-STE21A)        PRINT FIELD LENGTH    @Y30LB32
         DC    H'0'                    CONVERSION FLAGS      @Y30LB32
         SPACE 1                                             @Y30LB32
* INSERT DATA SUB-STRUCTURE                                  @ZM30741
         DC    X'2000'                                       @ZM30741
         DC    H'03,00,28,12'          LNG,OFST,PC,LNG       @ZM30741
         DC    H'0000'                 CONVERSION FLAGS      @ZM30741
         SPACE 1                                             @Y30LB32
* INSERT DATA SUB-STRUCTURE                                  @Y30LB32
         DC    X'2000'                                       @Y30LB32
         DC    H'01,00,51,08'          LNG,OFST,PC,LNG       @ZM30741
         DC    X'0000'                 CONVERSION FLGS       @Y30LB32
         SPACE 1                                             @Y30LB32
* INSERT DATA SUB-STRUCTURE                                  @Y30LB32
         DC    X'A000'                                       @Y30LB32
         DC    H'02,00,60,08'          LNG,OFST,PC,LNG       @ZM30741
         DC    X'0000'                 CONVERSION FLGS       @ZM30741
         SPACE 1                                             @Y30LB32
* STATIC TEXT ENTRIES                                        @Y30LB32
STE21A   DC    C'IDC791E REPLACED CARTRIDGE UNIDENTIFIED '   @ZM30741
         DC    C'EJECTED;'                                   @ZM30741
STE21B   EQU   *                                             @ZM30741
TXT2B    EQU   *                                             @Y30LB32
         END
