 /******START OF SPECIFICATIONS***************************************/
 /*                                                                  */
 /*  MODULE-NAME = IEEMBOCB                                          */
 /*                                                                  */
 /*  DESCRIPTIVE-NAME = OPTION CONTROL BLOCK                         */
 /*                                                                  */
 /*  FUNCTION = THIS MACRO MAPS THE DIFFERENT TYPES OF             */
 /*             OPTION CONTROL BLOCKS WHICH ARE THE INTERNAL         */
 /*             REPRESENTATION OF THE OPTIONS SPECIFIED.             */
 /*             IT ALSO MAPS THE OCB BUFFER POOL                     */
 /*                                                                  */
 /*  NOTES = SEE BELOW                                               */
 /*                                                                  */
 /*  MODULE-TYPE = PLS MAPPING MACRO                                 */
 /*                                                                  */
 /*  CHANGE-ACTIVITY = NONE                                          */
 /*                                                                  */
 /*     A000000-999999                                       @G741PLS*/
 /*  JBB1226 CHANGES - ADD OCBCHNG FLAG                      @G383P26*/
 /******END OF SPECIFICATIONS*****************************************/
 DCL 1 IEEMBOCB BASED BDY(WORD),   /* COMMON TO ALL OPTIONS      */
           2 OCBNEXT PTR(31),     /* NEXT OCB ON CHAIN          */
           2 OCBOPTNE PTR(31),    /* ADDRESS OF OPTAB ENTRY     */
           2 OCBADDR PTR(31),     /* ADDRESS OF SUBOPTION OCB'S */
           2 OCBFLAGS BIT(32),    /* CHARACTERISTICS           */
               4 OCBNOXF BIT(1),  /* NOXXX OPTION SPECIFIED    */
               4 OCBSRCF BIT(16), /* FLAGS INDICATE INPUT SOURCE */
                 5 OCBMEMBF BIT(1), /* ACCEPTED FROM MEMBER  */
                 5 OCBREPLF BIT(1), /* ACCEPTED FROM REPLY   */
                 5 OCBDFTSF BIT(1), /* DEFAULT USED          */
                 5 OCBCONF BIT(1),  /* CHANGED DUE TO
                                       CONFLICTING OPTIONS       */
                 5 OCBSYSNF BIT(1), /* ACCEPTED FROM SYSIN
                                     (DUMP PROCESSOR ONLY)     */
               4 OCBCHNG BIT(1);    /* OPTION MODIFIED     @G383P26*/

 DCL 1 OCBSYSID BASED(ADDR(IEEMBOCB))BDY(WORD),/* SYSID OPTION       */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD), /* COMMON SECTION */
       8 OCBSYSTM CHAR(4),          /* SYSTEM ID */
       8 OCBCPUID(2) CHAR(6);      /* CPU SERIAL NUMBERS */

 DCL 1 OCBDATE BASED(ADDR(IEEMBOCB))BDY(WORD),/* DATE OPTION         */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION         */
       8 OCBPSDAT CHAR(4),            /* START DATE (PACKED)         */
       8 OCBPEDAT CHAR(4),            /* END DATE (PACKED)           */
       8 OCBCHDAT CHAR(11),           /* CHARACTER VALUES            */
         9 OCBSDATE CHAR(5),          /* START DATE (CHARS)          */
         9 OCBDDLM CHAR(1),           /* COMMA IN HERE               */
         9 OCBEDATE CHAR(5);          /* END DATE (CHARS)            */

 DCL 1 OCBTOD BASED(ADDR(IEEMBOCB))BDY(WORD), /* TOD OPTION          */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION         */
       8 OCBPTOD CHAR(4),            /* START TOD  (PACKED)         */
       8 OCBCTOD CHAR(6);            /* CHARACTER VALUE             */
 DCL 1 OCBGROUP BASED(ADDR(IEEMBOCB))BDY(WORD),/* GROUP OCB */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION */
       8 OCBGRPNM CHAR(8);            /* GROUP NAME */
 DCL 1 OCBEXITS BASED(ADDR(IEEMBOCB))BDY(WORD),/* EXITS OCB */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION */
       8 OCBEXITN CHAR(8);            /* EXIT NAME */
 DCL 1 OCBXXDD BASED(ADDR(IEEMBOCB))BDY(WORD),/* DDNAME OCB */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION */
       8 OCBDDNAM CHAR(8);            /* DDNAME    */
 DCL 1 OCBSSID BASED(ADDR(IEEMBOCB))BDY(WORD),/* SSID OCB */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION */
       8 OCBSSNM CHAR(4);            /* SSID    */
 DCL 1 OCB2DEC  BASED(ADDR(IEEMBOCB))BDY(WORD),/* 2 DIGIT DECIMAL */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION */
       8 OCBBINVL FIXED(31),          /* BINARY VALUE */
       8 OCBCHVAL CHAR(2);           /* PRINTABLE VALUE */
 DCL 1 OCBBUFNO BASED(ADDR(IEEMBOCB))BDY(WORD),/* BUFNUM OCB */
       8 * CHAR(LENGTH(IEEMBOCB))BDY(WORD),/* COMMON SECTION */
       8 OCBBVAL1 FIXED(31),         /* BINARY FIRST VALUE */
       8 OCBBVAL2 FIXED(31),         /* BINARY SECOND VALUE */
       8 OCBCHVL1 CHAR(2),           /* FIRST VALUE AS ENTERED */
       8 OCBCHVL2 CHAR(2);           /* SECOND VALUE AS ENTERED */
 DCL 1 OCBTYPE BASED(ADDR(IEEMBOCB))BDY(WORD),/*  TYPE OCB       */
       8 * CHAR(LENGTH(IEEMBOCB)),
       8 OCBRECFL BIT(256),           /* RECORD FLAG BITS          */
       8 OCBLEN FIXED(31),            /* LENGTH OF CAHRACTER DATA    */
       8 OCBLDATA CHAR(*);            /* LIST OF DATA ITEMS          */
 DCL OCBRCDID(*) CHAR(4) DEFINED(OCBLDATA);/* RECORD ID'S            */

 DCL 1 OCBPOOLH BDY(WORD) BASED(ACTOCBPL), /* OCB BUFFER POOL+HEADER */
       2 OCBPLHDR,                      /* POOL HEADER               */
         3 OCBPLID CHAR(8),             /* POOL ID                   */
         3 OCBPLSPL FIXED(31),          /* SUBPOOL ID AND LENGTH     */
           5 OCBPLSPI FIXED(8),         /* SUBPOOL ID                */
           5 OCBPLSIZ FIXED(24),        /* OCB POOL LENGTH           */
         3 OCBPLAVL PTR(31),            /* NEXT AVAILABLE OCB ADDR   */
         3 OCBPLSPU FIXED(15),          /* SPACE USED IN BYTES       */
       2 OCBPOOL CHAR(*);               /* OCB BUFFER POOL BEGINS    */

