*/***  START OF SPECIFICATIONS  **************************************/
*/*                                                                  */
*/*  MODULE NAME = IEESMFID                                          */
*/*                                                                  */
*/*  DESCRIPTIVE NAME = MESSAGES INDEX TABLE CONSTANTS               */
*/*                                                                  */
*/*  FUNCTION = MAPPING MACRO FOR THE MESSAGES INDEX TABLE CONSTANTS */
*/*                                                                  */
*/*  NOTES = NONE                                                    */
*/*                                                                  */
*/*  MODULE TYPE = PLS MAPPING MACRO                                 */
*/*                                                                  */
*/*  METHOD OF INVOCATION                                            */
*/*    PLS - PERCENT INCLUDE(SYSLIB) IEESMFID                        */
*/*                                                                  */
*/*    BAL - NONE                                                    */
*/*                                                                  */
*/*  CHANGE ACTIVITY = SEE BELOW                                     */
*/*                                                                  */
*/*  A000000-999999                                          @G743PJK*/
*/*  JBB1226 - ADD MESSAGES FOR SSI CALLS                    @G383P26*/
*/*                                                                  */
*/****  END OF SPECIFICATIONS  ***************************************/
*/*                                                                  */
         DECLARE
           MID351I                  /* MSG ID - IEE351I             */
                 FIXED(31)          /* SYS1.MAN RECORDING NOT BEING */
                 CONSTANT(1),       /* USED                         */
           MID967I                  /* MSG ID - IEE967I             */
                 FIXED(31)          /* HH.MM.SS SMF PARAMETERS ID   */
                 CONSTANT(2),     /**/
           MID967I2                 /* MSG ID - IEE967I             */
                 FIXED(31)          /* XXXXXXXX -- XXXXXXXX         */
                 CONSTANT(3),       /*                              */
           MID967I3                 /* MSG ID - IEE967I             */
                 FIXED(31)          /* XXXXXXXX(XXXXX) -- XXXXXXXX  */
                 CONSTANT(4),       /*                              */
           MID967I4                 /* MSG ID - IEE967I             */
                 FIXED(31)          /*                              */
                 CONSTANT(5),       /*                              */
           MID357A                  /* MSG ID - IEE357A             */
                 FIXED(31)          /* REPLY WITH SMF VALUES OR U   */
                 CONSTANT(6),       /*                              */
           MID360I                  /* MSG ID - IEE360I             */
                 FIXED(31)          /* SMF NOW RECORDING ON SYS1.MAN*/
                 CONSTANT(7),       /* X ON AAAAAA TIME=XX:XX:XX    */
           MID361I                  /* MSG ID - IEE361I             */
                 FIXED(31)          /* SMF DATA LOST - NO DATA SETS */
                 CONSTANT(8),       /* AVAILABLE TIME=XX:XX:XX      */
           MID362A                  /* MSG ID - IEE362A             */
                 FIXED(31)          /* SMF ENTER DUMP FOR SYS1.MANX */
                 CONSTANT(9),       /* ON AAAAAA                    */
           MID364I                  /* MSG ID - IEE364I             */
                 FIXED(31)          /* SMF I/O ERROR ON AAAAAA      */
                 CONSTANT(10),      /*                              */
           MID480I                  /* MSG ID - IEE480I             */
                 FIXED(31)          /* SMF FAILED, TERMINATED       */
                 CONSTANT(11),      /*                              */
           MID480I2                 /* MSG ID - IEE480I             */
                 FIXED(31)          /* SMF ABEND XXX, DUMPED, TERM  */
                 CONSTANT(12),      /* INATED                       */
           MID940I                  /* MSG ID - IEE940I             */
                 FIXED(31)          /* SMF OPEN FAILED FOR XXXXXXXX */
                 CONSTANT(13),      /*                              */
           MID941I                  /* MSG ID - IEE3941             */
                 FIXED(31)          /* SMF MEMBER XXXXXXXX NOT      */
                 CONSTANT(14),      /* FOUND IN XXXXXXXXXX          */
           MID942I                  /* MSG ID - IEE942I             */
                 FIXED(31)          /* I/O ERROR ON SMFPRMXX READ - */
                 CONSTANT(15),      /* SYNAD TEXT FOLLOWS: XXXXXX   */
           MID943I                  /* MSG ID - IEE943I             */
                 FIXED(31)          /* SMF FIND ERROR CODE XXX ON   */
                 CONSTANT(16),      /* SMFPRMXX                     */
           MID944I                  /* MSG ID - IEE944I             */
                 FIXED(31)          /* SYNTAX ERROR IN OR FOLLOWING */
                 CONSTANT(17),      /* TEXT BEGINNING 'XXXX' IN     */
                                    /* XXXX INPUT                   */
           MID945I                  /* MSG ID - IEE945I             */
                 FIXED(31)          /* UNRECOGNIZABLE OPTION/SUB-   */
                 CONSTANT(18),      /* OPTION 'XXXX' IN XXXX INPUT  */
           MID946I                  /* MSG ID - IEE946I             */
                 FIXED(31)          /* UNEXPECTED END OF TEXT IN    */
                 CONSTANT(19),      /* XXXX INPUT                   */
           MID947I                  /* MSG ID - IEE947I             */
                 FIXED(31)          /* 'XXXX' SKIPPED DUE TO        */
                 CONSTANT(20),      /* PREVIOUS ERROR               */
           MID948I                  /* MSG ID - IEE948I             */
                 FIXED(31)          /* INVALID XXXX VALUE 'YYYY' IN */
                 CONSTANT(21),      /* ZZZZ INPUT                   */
           MID010I                  /* MSG ID - IFA010I             */
                 FIXED(31)          /* SMF DUMP PARAMETERS          */
                 CONSTANT(22),      /*                              */
           MID010I2                 /* MSG ID - IFA010I             */
                 FIXED(31)          /* XXXXXXXX -- XXXXXXXX         */
                 CONSTANT(23),      /*                              */
           MID010I3                 /* MSG ID - IFA010I             */
                 FIXED(31)          /* XXXXXXXX(XXXXX) -- XXXXXXXX  */
                 CONSTANT(24),      /*                              */
           MID011I                  /* MSG ID - IFA011I             */
                 FIXED(31)          /* SMF XXXXXXXX DATA SET        */
                 CONSTANT(25),      /* CANNOT BE XXXXXXXX.          */
           MID011I2                 /* MSG ID - IFA011I             */
                 FIXED(31)          /* JOB TERMINATED               */
                 CONSTANT(26),      /*                              */
           MID011I3                 /* MSG ID - IFA011I             */
                 FIXED(31)          /* NO FURTHER PROCESSING OF     */
                 CONSTANT(27),      /* THIS DATA SET                */
           MID011I4                 /* MSG ID - IFA011I             */
                 FIXED(31)          /* RETURN CODE=XX. FEEDBACK     */
                 CONSTANT(28),      /* CODE=XXXX.                   */
           MID012I                  /* MSG ID - IFA012I             */
                 FIXED(31)          /* DSORG OF XXXXXXXX CANNOT BE  */
                 CONSTANT(29),      /* DETERMINED                   */
           MID012I2                 /* MSG ID - IFA012I             */
                 FIXED(31)          /* JOB TERMINATED               */
                 CONSTANT(30),      /*                              */
           MID012I3                 /* MSG ID - IFA012I             */
                 FIXED(31)          /* NO FURTHER PROCESSING OF     */
                 CONSTANT(31),      /* THIS DATA SET                */
           MID013I                  /* MSG ID - IFA013I             */
                 FIXED(31)          /* 'CLEAR' OPTION IS VALID ONLY */
                 CONSTANT(32),      /* FOR VSAM DATA SETS. OPTION
                                       IGNORED FOR DDNAME XXXXXX    */
           MID014I                  /* MSG ID - IFA014I             */
                 FIXED(31)          /* SMF DUMP INITIALIZATION FAIL-*/
                 CONSTANT(33),      /* ED. JOB TERMINATED.          */
           MID015I                  /* MSG ID - IFA015I             */
                 FIXED(31)          /* SMF DUMP PROGRAM TERMINATED  */
                 CONSTANT(34),      /* ABNORMALLY. NO DATASETS WERE */
                                    /* CLEARED.                     */
           MID016I                  /* MSG ID - IFA016I             */
                 FIXED(31)          /* ERROR DETECTED IN USER EXIT  */
                 CONSTANT(35),      /* XXXXXXXX. EXIT BYPASSED.     */
           MID017I                  /* MSG ID - IFA017I             */
                 FIXED(31)          /* ERROR IN SMF DUMP SUMMARY    */
                 CONSTANT(36),      /* REPORT. REPORT TERMINATED.   */
           MID949I1                 /* MSG ID - IEE949I             */
                 FIXED(31)          /* HH.MM.SS SMF DATA SETS ID    */
                 CONSTANT(37),      /*                              */
           MID949I2                 /* MSG ID - IEE949I             */
                 FIXED(31)          /*     NAME    VOLSER SIZE(BLKS)*/
                 CONSTANT(38),      /*  %FULL STATUS                */
           MID949I3                 /* MSG ID - IEE949I             */
                 FIXED(31)          /*   XXXXXXXX  XXXXXX  XXXXXXX  */
                 CONSTANT(39),      /*   XXX    XXXXXXXXXX          */
           MID949I4                 /* MSG ID - IEE949I             */
                 FIXED(31)          /* NO TEXT (END OF MULTI-LINE)  */
                 CONSTANT(40),
           MID950I1                 /* MSG ID - IEE950I             */
                 FIXED(31)          /* SMF XXXXXXXX DATASET CANNOT  */
                 CONSTANT(41),      /* BE XXXXXXXXX                 */
           MID950I2                 /* MSG ID - IEE950I             */
                 FIXED(31)          /* RETURN CODE=XX. ERROR CODE=  */
                 CONSTANT(42),      /* XXXX. INFO. CODE=XXXXX       */
           MID951I                  /* MSG ID - IEE951I             */
                 FIXED(31)          /* DSORG OF XXXXXXXX DATASET IS */
                 CONSTANT(43),      /* NOT VSAM. DATASET CANNOT BE
                                       USED.                        */
           MID018I                  /* MSG ID - IFA018I             */
                 FIXED(31)          /* SMF DATA SET XXXXXXXX HAS    */
                 CONSTANT(44),      /* BEEN CLEARED.                */
           MID952I                  /* MSG ID - IEE952I             */
                 FIXED(31)          /* ERROR DETECTED IN USER EXIT  */
                 CONSTANT(45),      /* XXXXXXXX. EXIT BYPASSED.     */
           MID953I                  /* MSG ID - IEE953I             */
                 FIXED(31)          /* INVALID CONTROL INTERVAL     */
                 CONSTANT(46),      /* SIZE IN DATASET XXXXXXXX     */
           MID954I                  /* MSG ID - IEE954I             */
                 FIXED(31)          /* BUFNUM VALUE HAS BEEN        */
                 CONSTANT(47),      /* CHANGED TO XXXXXXX           */
           MID535I                  /* MSG ID - IEE535I             */
                 FIXED(31)          /* DISPLAY  INVALID PARAMETER   */
                 CONSTANT(48),
           MID955I                  /* MSG ID - IEE955I             */
                 FIXED(31)          /* SPECIFY IPL REASON           */
                 CONSTANT(49),
           MID956A                  /* MSG ID - IEE956I             */
                 FIXED(31)          /* REPLY - FTIME=HH.MM.SS,NAME= */
                 CONSTANT(50),      /* OPERATOR,REASON=(IPL REASON)
                                       OR U                         */
           MID957I                  /* MSG ID - IEE957I             */
                 FIXED(31)          /* SYNTAX ERROR IN IPL REASON   */
                 CONSTANT(51),      /* REPLY - RESPECIFY            */
           MID362I                  /* MSG ID - IEE362I             */
                 FIXED(31)          /* SMF ENTER DUMP FOR SYS1.MANX */
                 CONSTANT(52),      /* ON AAAAAA                    */
           MID961I                  /* MSG ID - IEE961I             */
                 FIXED(31)          /* SMF INITIALIZATION FAILED    */
                 CONSTANT(53),
           MID960I                  /* MSG ID - IEE960I             */
                 FIXED(31)          /* SMF1.MANX WILL NOT BE USED.  */
                 CONSTANT(54),      /* DATASET TOO SMALL            */
           MID958I                  /* MSG ID - IEE958I             */
                 FIXED(31)          /* MAXIMUM NUMBER OF SUBSYSTEMS */
                 CONSTANT(55),      /* EXCEEDED.                    */
           MID958I2                 /* MSG ID - IEE958I             */
                 FIXED(31)          /* SUBSYS XXXX IGNORED.         */
                 CONSTANT(56),
           MID958I3                 /* MSG ID - IEE958I             */
                 FIXED(31)          /* SET SMF COMMAND TERMINATED.  */
                 CONSTANT(57),      /* OLD OPTIONS REMAIN IN EFFECT */
           MID962E                  /* MSG ID - IEE962I             */
                 FIXED(31)          /* SMF TERMINATED.              */
                 CONSTANT(58),
           MID963I                  /* MSG ID - IEE963I             */
                 FIXED(31)          /* SMF RECOVERY ATTEMPTING      */
                 CONSTANT(59),      /* RETRY                        */
           MID964I                  /* MSG ID - IEE964I             */
                 FIXED(31)          /* SET SMF COMMAND ABENDED      */
                 CONSTANT(60),
           MID964I2                 /* MSG ID - IEE964I             */
                 FIXED(31)          /* OLD OPTIONS REMAIN IN EFFECT */
                 CONSTANT(61),
           MID964I3                 /* MSG ID - IEE964I             */
                 FIXED(31)          /* OPTIONS IN EFFECT            */
                 CONSTANT(62),      /* UNDETERMINABLE               */
           MID964I4                 /* MSG ID - IEE964I             */
                 FIXED(31)          /* NEW OPTIONS IN EFFECT        */
                 CONSTANT(63),
           MID965I                  /* MSG ID - IEE965I             */
                 FIXED(31)          /* SET SMF COMMAND INOPERATIVE  */
                 CONSTANT(64),      /* FOR REMAINDER OF IPL         */
           MID966I                  /* MSG ID - IEE966I             */
                 FIXED(31)          /* XXXXXXXXX IS BEING FORMATTED */
                 CONSTANT(65),      /* FOR REMAINDER OF IPL         */
           MID967I5                 /* MSG ID - IEE967I             */
                 FIXED(31)          /* MEMBER = SMFPRMXX            */
                 CONSTANT(66),      /*                              */
           MID962I                  /* MSG ID - IEE962              */
                 FIXED(31)          /* SMF TERMINATED               */
                 CONSTANT(67),
           MID019I                  /* MSG ID - IFA019I             */
                 FIXED(31)          /* CLEAR FUNCTION IS NOT AUTHOR */
                 CONSTANT(68),      /* IZED IN THIS ENVIRONMENT     */
           MID968I                  /* MSG ID - IEE968I     @G383P26*/
                 FIXED(31)          /* NOTIFICATION OF SUBSYS XXXX  */
                 CONSTANT(69),      /* REJECTED                     */
           MID968I2                 /* MSG ID - IEE968I     @G383P26*/
                 FIXED(31)          /* SUBSYSTEM DOES NOT SUPPORT   */
                 CONSTANT(70),      /* THIS FUNCTION                */
           MID968I3                 /* MSG ID - IEE968I     @G383P26*/
                 FIXED(31)          /* SUBSYSTEM IS NOT OPERATIONAL */
                 CONSTANT(71),
           MID968I4                 /* MSG ID - IEE968I     @G383P26*/
                 FIXED(31)          /* SUBSYSTEM DOES NOT EXIST     */
                 CONSTANT(72),
           MID968I5                 /* MSG ID - IEE968I     @G383P26*/
                 FIXED(31)          /* SYSTEM ERROR                 */
                 CONSTANT(73),      /*                              */
           MID969I                  /* MSG ID - IEE969I     @G383P26*/
                 FIXED(31)          /* SETSMF COMMAND ABENDED       */
                 CONSTANT(74),
           MID969I2                 /* MSG ID - IEE969I     @G383P26*/
                 FIXED(31)          /* OLD OPTIONS REMAIN IN EFFECT */
                 CONSTANT(75),
           MID969I3                 /* MSG ID - IEE969I     @G383P26*/
                 FIXED(31)          /* OPTIONS IN EFFECT            */
                 CONSTANT(76),      /* UNDETERMINABLE               */
           MID969I4                 /* MSG ID - IEE969I     @G383P26*/
                 FIXED(31)          /* NEW OPTIONS IN EFFECT        */
                 CONSTANT(77),
           MID970I                  /* MSG ID - IEE970I     @G383P26*/
                 FIXED(31)          /* SETSMF COMMAND NOT AUTHORIZED*/
                 CONSTANT(78),
           MID971I                  /* MSG ID - IEE971I     @G383P26*/
                 FIXED(31)          /* XXXX KEYWORDS IGNORED - ONLY */
                 CONSTANT(79),      /* ONE SUBSYSTEM CAN BE CHANGED */
           MID712I                  /* MSG ID - IEE712I     @G383P26*/
                 FIXED(31)          /* SETSMF PROCESSING COMPLETE   */
                 CONSTANT(80),
           MID972I                  /* MSG ID - IEE972I     @G383P26*/
                 FIXED(31)          /* SETSMF CANNOT BE USER TO     */
                 CONSTANT(81),      /* CHANGE XXXXX                 */
           MID973I                  /* MSG ID - IEE973I     @G385P26*/
                 FIXED(31)          /* DATA SET CHANGE REQUEST IS   */
                 CONSTANT(82)       /* IGNORED.                     */
         ;
