*        %GOTO AQEBSL;       /* BILINGUAL MAPPING            /*     /*
         MACRO
         IHAAQE   &TYPE
*
*        RELEASE 1 AOS, 11/3/71, LEVEL=1
*
         AIF   ('&TYPE' EQ 'INTERNAL').EQU
AQESECT  DSECT ,TCBAQE               ALLOCATED QUEUE ELEMENT
AQEPTR   DS    A                     ADDRESS OF PREVIOUS AQE
AQELEN   DS    F                     LENGTH OF ALLOCATED AREA
         MEXIT
.EQU     ANOP
AQEPTR   EQU   0                     ADDRESS OF PREVIOUS AQE
AQELEN   EQU   4                     LENGTH OF ALLOCATED AREA
         MEND  , */
*%AQEBSL:   ;
* DECLARE
*
*/*      RELEASE 1 AOS, 11/3/71, LEVEL=1                             */
*
*   1 AQESECT  BASED(TCBAQE),        /* ALLOCATED QUEUE ELEMENT      */
*   2 AQEPTR   PTR(31),              /* ADDRESS OF PREVIOUS AQE      */
*   2 AQELEN   FIXED(31);            /* LENGTH OF ALLOCATED AREA     */
