         MACRO
         IKJPARMA
IKJPARMA DSECT                DESCRIPTION OF ADDRESS PDE.
         SPACE
PDELDNAM DS    A              POINTER TO LOAD NAME.
PDELEN1  DS    H              LENGTH OF LOAD NAME.
PDEFLG1  DS    X              FLAGS FOR LOAD NAME.
LDNAMFLG EQU   B'10000000'    INDICATES PRESENCE OF LOAD NAME.
PDERSV1  DS    X              RESERVED.
PDECTNAM DS    A              POINTER TO ENTRY NAME.
PDELEN2  DS    H              LENGTH OF ENTRY NAME.
PDEFLG2  DS    X              FLAGS FOR ENTRY NAME.
CTNAMFLG EQU   B'10000000'    INDICATES PRESENCE OF ENTRY NAME.
PDERSV2  DS    X              RESERVED.
PDEADRPT DS    A              POINTER TO ADDRESS STRING.
PDELEN3  DS    H              LENGTH OF ADDRESS STRING.
PDEFLG3  DS    X              FLAGS FOR ADDRESS STRING.
AFLG     EQU   B'10000000'    INDICATES PRESENCE OF ADDRESS STRING.
PDERSV3  DS    X              RESERVED.
         SPACE
PDEFLG4  DS    X              ADDRESS TYPE FLAGS.
ABSADDR  EQU   B'00000000'    ABSOLUTE ADDRESS.
SYMADDR  EQU   B'10000000'    SYMBOLIC ADDRESS.
RELADDR  EQU   B'01000000'    RELATIVE ADDRESS.
GENR     EQU   B'00100000'    GENERAL REGISTER.
LFPR     EQU   B'00010000'    DOUBLE PREC. FLT. PT. REGISTER.
SFPR     EQU   B'00001000'    SINGLE PREC. FLT. PT. REGISTER.
CTONLY   EQU   B'00000100'    ENTRY NM NOT FOLLOWED BY SYM OR REL.
ABSCOMPL EQU   B'11111111'    COMPLEMENT FOR ABSOLUTE TEST.
         SPACE
PDESIGN  DS    C              EXPRESSION SIGN.
PDEINDCT DS    H              INDIRECT COUNT.
PDEEXPTR DS    A              PTR TO 1ST EXPRESSION PDE.
PDEFLG5  DS    0X             FLAG BYTE, PDE USER WORD.
PURESYM  EQU   B'10000000'    INDICATES PDE USER WORD POINTS TO SIB.
PDEUSER  DS    A              RESOLVED ADDR OR SIB POINTER.
PDESIB   EQU   X'80'          INDICATES USER WORD POINTS TO SIB.
PDECONVD EQU   X'40'          INDICATES ADDRESS IS CONVERTED.
PDEADLST EQU   X'20'          INDICATES PDE IS ONE OF A LIST.
PDEYECH  EQU   X'10'          INDICATES PDE IS USELESS.
PDEWRITE EQU   X'08'          INDICATES ADDRESS IS WRITABLE.
         SPACE
PDECHAIN DS    A              CHAIN PTR FIELD FOR ADDRESS LIST.
         SPACE
         ORG   PDECHAIN       IN ADDR RANGE, ADDR2 FOLLOWS ADDR1.
PDE2LDNA DS    A              POINTER TO LOAD NAME.
PDE2LEN1 DS    H              LENGTH OF LOAD NAME.
PDE2FLG1 DS    X              FLAGS FOR LOAD NAME.
PDE2RSV1 DS    X              RESERVED.
PDE2CTNA DS    A              POINTER TO ENTRY NAME.
PDE2LEN2 DS    H              LENGTH OF ENTRY NAME.
PDE2FLG2 DS    X              FLAGS FOR ENTRY NAME.
PDE2RSV2 DS    X              RESERVED.
PDE2ADRP DS    A              POINTER TO ADDRESS STRING.
PDE2LEN3 DS    H              LENGTH OF ADDRESS STRING.
PDE2FLG3 DS    X              FLAGS FOR ADDRESS STRING.
PDE2RSV3 DS    X              RESERVED.
         SPACE
PDE2FLG4 DS    X              ADDRESS TYPE FLAGS.
PDE2SIGN DS    C              EXPRESSION SIGN.
PDE2INDC DS    H              INDIRECT COUNT.
PDE2EXPT DS    A              PTR TO 1ST EXPRESSION PDE.
PDE2FLG5 DS    0X             FLAG BYTE, PDE USER WORD.
PDE2USER DS    A              RESOLVED ADDR OR SIB POINTER.
         SPACE
PDE2CHAI DS    A              CHAIN POINTER FOR ADDR LIST.
         MEND
