         MACRO
         TDRQD
* TDRQD MACRO UPDATED 7/2/71
IEDQDRQ  DSECT
*
*              THIS IS A DSECT OF THE CONCENTRATOR DATA READY QUEUE.
*
DRQFLAG1 DS    XL1 .                    DRQ FLAG BYTE
*                                       BITS 0,1,2 & 3 MUST BE 0
*                        BIT DEFINITIONS
DRQDRQQ  EQU   X'04' .                  FLAG INDICATING A DRQ
DRQFQCB  EQU   X'02' .                  FLAG INDICATING A QCB
DRQHELD  EQU   X'01' .                  STOP SENDING - REUSE
*
DRQELCHN DS    AL3 .                    ELEMENT CHAIN
DRQPRI   DS    CL1 .                    PRIORITY
DRQLINK  DS    AL3 .                    DRQ LINK FIELD
DRQSTVTO DS    XL1 .                    INDEX TO ENTRY IN SUBTASK
*                                       VECTOR TABLE
*                        BIT DEFINITIONS
DRQCSVTO EQU   X'20' .                  DRQ VTO
*
DRQSTCHN DS    AL3 .                    STCB CHAIN
DRQSTPRI DS    CL1 .                    PRIORITY OF THE STCB
DRQSLINK DS    AL3 .                    POINTER TO NEXT STCB IN CHAIN
DRQBUFCT DS    FL1 .                    TOTAL BUFFER COUNT
DRQERBCT DS    FL1 .                    ERB BUFFER COUNT
DRQTDO   DS    XL1 .                    TIME DELAY QUEUE OFFSET
DRQSTAT  DS    XL1 .                    STATUS OF THIS QCB
*                        BIT DEFINITIONS
DRQEOM   EQU   X'80' .                  END OF MSG SENT
DRQTRMHO EQU   X'40' .                  TERMINAL WAS HELD
DRQBUFRD EQU   X'20' .                  BUFFERED TERMINAL
DRQSEND  EQU   X'10' .                  SENDING TO BUFFERED TERM
DRQRECEV EQU   X'08' .                  RECEIVING FROM BUFFERED TERM
DRQSCHDL EQU   X'04' .                  PUT IN DELAY Q WHEN INACTIVE
DRQCLOCK EQU   X'02' .                  ON=CLOCK, OFF=INTERVAL
DRQTIME  EQU   X'01' .                  DELAY GREATER THEN 12 HOURS
*
DRQSCBOF DS    FL1 .                    X'00' - OFFSET TO PROPER SCB
DRQCURQ  DS    AL3 .                    POINTER TO CURRENT QCB
DRQFLAG3 DS    XL1 .                    DRQ FLAG BYTE
*                        BIT DEFINITIONS
DRQFSPCI EQU   X'80' .                  FIRST PCI FOR CONC MSG
DRQERBAV EQU   X'40' .                  INDICATES ENABLED CODE
*                                       REQUESTED ERB
*
DRQRESV  DS    XL1 .                    RESERVED
DRQCTBCT DS    FL1 .                    CTB COUNT
DRQCTBMX DS    FL1 .                    MAX CTBS PER CONC MSG
DRQPRLVL DS    XL1 .                    HIGHEST PRIORITY LEVEL MSG
DRQPRVLK DS    0AL3 .                   POINTER TO THE LINK FIELD
DRQTDLNK DS    AL3 .                    LINK FIELD FOR TIME DELAY Q
DRQRELLN DS    FL1 .                    RELATIVE LINE NO
DRQDCBAD DS    AL3 .                    DCB ADDRESS
DRQFLAG2 DS    XL1 .                    DRQ STATUS BITS
*                        BIT DEFINITIONS
DRQTSSES EQU   X'80' .                  TSO SESSION IN PROGRESS
DRQRSRV  EQU   X'10' .                  REUSE SERVICED BIT
DRQTERMQ EQU   X'08' .                  QUEUING BY TERMINAL
DRQSDFFO EQU   X'04' .                  CURRENTLY SENDING FEFO MSG
DRQPROC  EQU   X'02' .                  THIS QCB FOR A PROCESS ENTRY
DRQCKPT  EQU   X'01' .                  FLAG FOR CHECKPOINT
*
DRQQBACK DS    AL3 .                    QBACK CHAIN POINTER
*
*         *******************************************************
*     0   *   FLAG1   **                 ELCHN                  *
*         *******************************************************
*     4   *   PRI     **                 LINK                   *
*         *******************************************************
*     8   *   STVTO   **                 STCHN                  *
*         *******************************************************
*    12   *   STPRI   **                 SLINK                  *
*         *******************************************************
*    16   *   BUFCT   **   ERBCT    **   TD/      **   STAT     *
*         *******************************************************
*    20   *   SCBOF   **                 CURQ                   *
*         *******************************************************
*    24   *   FLAG3   **   RESV     **   CTBCT    **   CTBMX    *
*         *******************************************************
*    28   *   PRLVL   **                 TDLNK/PRVLK            *
*         *******************************************************
*    32   *   RELLN   **                 DCBAD                  *
*         *******************************************************
*    36   *   FLAG2   **                 QBACK                  *
*         *******************************************************
         MEND
