         MACRO
&NAME    IHBROCTL
.*2590872000                                                       MO17
         SPACE
*
* REGISTER ASSIGNMENTS - GLOBAL USAGE.
*
WKREG0   EQU   0                        WORK REGISTER
PMREG1   EQU   1                        PARAMETER REGISTER
PMREG2   EQU   2                        PARAMETER REGISTER
LKREG2   EQU   7                        LINK REGISTER TO SUBROUTINE
LKREG1   EQU   8                        LINK REGISTER TO SUBROUTINE
WKREG1   EQU   9                        WORK REGISTER
WKREG2   EQU   10                       WORK REGISTER
WKREG3   EQU   11                       WORK REGISTER
BASREG   EQU   12                       BASE REGISTER
SAVREG   EQU   13                       SAVE REGISTER
RETREG   EQU   14                       RETURN REGISTER
APGREG   EQU   15                       LINK REGISTER TO APPENDAGE
*
* FLAG DEFINITIONS - GLOBAL USAGE.
*
TCBFRA   EQU   X'20'                    STEP CAN CAUSE ROLLOUT
TCBFRI   EQU   X'40'                    STEP HAS INVOKED ROLLOUT
TCBWFC   EQU   X'20'                    TASK IS WAITING FOR CORE
TCBFRO   EQU   X'10'                    STEP HAS BEEN ROLLED OUT
PQEBOR   EQU   X'80'                    REGION IS NOT OWNED BY STEP
PQERO    EQU   X'40'                    REGION HAS BEEN ROLLED OUT
PQEUSE   EQU   X'20'                    REGION IS IN USE BY BORROWER
*
* PQE DESCRIPTION.
*
PQESECT  DSECT
PQEFFBQE DS    CL4                      FORWARD  FBQE POINTER
PQEBFBQE DS    CL4                      BACKWARD FBQE POINTER
PQEFPQE  DS    CL4                      FORWARD  PQE POINTER
PQEBPQE  DS    CL4                      BACKWARD PQE POINTER
PQETCB   DS    CL4                      ADDRESS OF OWNING TCB
PQESIZE  DS    CL4                      SIZE OF REGION DESCRIBED BY PQE
PQEREGN  DS    CL4                      ADDRESS OF FIRST BYTE OF REGION
PQERFLGS DS    CL1                      ROLLOUT FLAGS
PQEHRID  DS    CL1                      HIERARCHY IDENTIFICATION NUMBER
         DS    CL1                      RESERVED FOR LCS USE
         DS    CL1                      RESERVED FOR LCS USE
*
* IQE DESCRIPTION.
*
IQESECT  DSECT
IQELNK   DS    CL4                      ADDRESS OF NEXT IQE ON QUEUE
IQEPARAM DS    CL4                      ADDRESS OF PARAMETER LIST
IQEIRB   DS    CL4                      ADDRESS OF IRB TO BE SCHEDULED
IQETCB   DS    CL4                      ADDRESS OF TCB ON WHICH IRB IS
*                                       TO BE SCHEDULED.
*
* ROLLOUT PARAMETER LIST DESCRIPTION.
*
RPLSECT  DSECT
RPLTCB   DS    CL4                      ADDRESS OF REQUESTING TCB
RPLHRID  DS    CL1                      HIERARCHY IDENTIFICATION NUMBER
RPLSZPQE DS    CL3                      REQUESTED REGN. SIZE IF ROLLOUT
*                                       OR ADDRESS OF PQE IF ROLLIN
*
* IRB DESCRIPTION.
*
IRBSECT  DSECT
RBTMFLD  DS    CL1                      FLAGS FOR TIMER ROUTINES
RBPPSAV  DS    CL3                      ADDRESS OF REGISTER SAVE AREA
RBABOPSW DS    CL4                      ABNORMAL OLD PSW
RBWCSA   DS    CL1                      WAIT COUNT SAVE AREA
RBSIZE   DS    CL1                      SIZE OF RB IN DOUBLEWORDS
RBSTAB   DS    CL2                      STATUS AND ATTRIBUTE BITS
RBEP     DS    CL4                      ENTRY POINT ADDRESS
RBOPSW   DS    CL8                      OLD PSW
RBUSE    DS    CL1                      ATTACH USE COUNT
RBIQE    DS    CL3                      LIST ORIGIN FOR IQE'S ON RIB
RBWCF    DS    CL1                      WAIT COUNT
RBLINK   DS    CL3                      ADDRESS OF NEXT RB ON RB QUEUE
RBGRSAVE DS    CL64                     GENERAL REGISTER SAVE AREA
RBNEXAV  DS    CL4                      ADDRESS OF NEXT AVAILABLE IQE
         DS    CL4                      PADDING TO DOUBLEWORD BOUNDARY
*
* TCB DESCRIPTION.
*
TCBSECT  DSECT
TCBRBP   DS    CL4                      ADDRESS OF LAST RB ON RB QUEUE
TCBPIE   DS    CL4                      ADDRESS OF PIE
TCBDEB   DS    CL4                      ADDRESS OF LAST DEB ON DEB Q.
TCBTIO   DS    CL4                      ADDRESS OF TASK I/O TABLE
TCBCMP   DS    CL4                      TASK COMPLETION CODE
TCBTRN   DS    CL4                      ADDRESS OF TESTRAN CONTROL CORE
TCBNROC  DS    CL1                      NON-ROLLOUTABLE COUNT
TCBMSS   DS    CL3                      ADDRESS OF LAST SPQE ON SPQE Q.
TCBPKF   DS    CL1                      TCB PROTECT KEY
TCBFLGS  DS    CL5                      TCB CONTROL FLAGS
TCBLMP   DS    CL1                      LIMIT PRIORITY
TCBDSP   DS    CL1                      DISPATCHING PRIORITY
TCBLLS   DS    CL4                      ADDRESS OF LAST LLE
TCBJLB   DS    CL4                      ADDRESS OF JOB LIB. DCB
TCBJPQ   DS    CL4                      ADDRESS OF LAST CDE ON JPACQ
TCBGRS   DS    CL64                     GENERAL REGISTERS SAVE AREA
TCBFSA   DS    CL4                      ADDRESS OF FIRST P.P. SAVE AREA
TCBTCB   DS    CL4                      ADDRESS OF NEXT TCB ON TCB Q.
TCBTME   DS    CL4                      ADDRESS OF TIMER QUEUE ELEMENT
TCBJSTCB DS    CL4                      ADDRESS OF JOB STEP TCB
TCBNTC   DS    CL4                      ADDRESS OF NEXT SISTER TCB
TCBOTC   DS    CL4                      ADDRESS OF ORIGIN TCB
TCBLTC   DS    CL4                      ADDRESS OF LAST DAUGHTER TCB
TCBIQE   DS    CL4                      ADDRESS OF IQE FOR ETXR
TCBECB   DS    CL4                      ADDRESS OF ECB TO BE POSTED
TCBSTAE  DS    CL4                      RESERVED                   MO17
TCBPQE   DS    CL4                      ADDRESS OF PQE
TCBAQE   DS    CL4                      ADDRESS OF AQE
TCBNSTAE DS    CL4                      STAE CONTROL BLOCK ADDRESS MO17
TCBTCT   DS    CL4                      TIMING CONTROL TABLE ADDR  MO17
TCBUSER  DS    CL4                      RESERVED                   MO17
TCBDAR   DS    CL4                     DAMAGE ASSECMENT ROUTINE    MP2K
         DS    CL4                     RESERVED
         DS    CL1                     RESERVED
TCBJSCB  DS    CL3                     JSCB WRITE TO PROGRAMMER    I254
*
* FBQE DESCRIPTION.
*
FBQESECT DSECT
FBQEFWDP DS    CL4                      FORWARD  FBQE POINTER
FBQEBCKP DS    CL4                      BACKWARD FBQE POINTER
FBQESIZE DS    CL4                      SIZE IN BYTES OF 2K BLOCKS
         MEND
