         TITLE '*/* IRBMFALL - DYNAMIC ALLOCATION MODULE               *
                       '
IRBMFALL CSECT ,                                                   0001
@MAINENT DS    0H                                                  0001
         USING *,@15                                               0001
         B     @PROLOG                                             0001
         DC    AL1(16)                                             0001
         DC    C'IRBMFALL  74.087'                                 0001
         DROP  @15
@PROLOG  STM   @14,@12,12(@13)                                     0001
         BALR  @12,0                                               0001
@PSTART  DS    0H                                                  0001
         USING @PSTART,@12                                         0001
         L     @00,@SIZDATD                                        0001
         GETMAIN R,LV=(0)
         LR    @11,@01                                             0001
         USING @DATD,@11                                           0001
         ST    @13,@SA00001+4                                      0001
         LM    @00,@01,20(@13)                                     0001
         ST    @11,8(,@13)                                         0001
         LR    @13,@11                                             0001
         MVC   @PC00001(12),0(@01)                                 0001
*                                                                  0021
*/* BEGIN STATIC TO AUTOMATIC INITIALIZATION                         */
*                                                                  0021
*   /*****************************************************************/
*   /*                                                               */
*   /* STATIC TEXT UNITS TO AUTOMATIC STORAGE                        */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0021
*   DO ALLOOPV=1 TO DIM(ALTXTPTR);                                 0021
         LA    ALLOOPV,1                                           0021
@DL00021 DS    0H                                                  0022
*     ALATUNIT(ALLOOPV)=ALSTUNIT(ALLOOPV);                         0022
         LR    @10,ALLOOPV                                         0022
         MH    @10,@CH00364                                        0022
         LA    @03,ALATUNIT-14(@10)                                0022
         LA    @01,ALSTUNIT-14(@10)                                0022
         MVC   0(14,@03),0(@01)                                    0022
*   END;                                                           0023
         AH    ALLOOPV,@CH00058                                    0023
         CH    ALLOOPV,@CH00341                                    0023
         BNH   @DL00021                                            0023
*                                                                  0024
*/* BEGIN MAINLINE PROCESSING                                        */
*                                                                  0024
*   /*****************************************************************/
*   /*                                                               */
*   /* INITIALIZE DYNAMIC ALLOCATION CONTROL BLOCKS                  */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0024
*   S99RBPTR=ADDR(S99RB);           /* INITIALIZE POINTER TO REQUEST
*                                      BLOCK                         */
         LA    @10,S99RB                                           0024
         ST    @10,S99RBPTR                                        0024
*   S99RBPND='1'B;                  /* HIGH ORDER BIT MUST BE ONE    */
*                                                                  0025
         OI    S99RBPND,B'10000000'                                0025
*   /*****************************************************************/
*   /*                                                               */
*   /* INITIALIZE MAIN REQUEST BLOCK                                 */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0026
*   S99RB=S99RB&&S99RB;             /* ZERO REQUEST BLOCK            */
         XC    S99RB(20),S99RB                                     0026
*   S99RBLN=LENGTH(S99RB);          /* LENGTH                        */
         MVI   S99RBLN,X'14'                                       0027
*   S99VERB=S99VRBAL;               /* ALLOCATION VERB               */
         MVI   S99VERB,X'01'                                       0028
*   S99TXTPP=ADDR(ALTXTPTR);        /* POINTER TO TEXT UNIT POINTER
*                                      LIST                          */
*                                                                  0029
         LA    @10,ALTXTPTR                                        0029
         ST    @10,S99TXTPP                                        0029
*   /*****************************************************************/
*   /*                                                               */
*   /* INITIALIZE TEXT UNIT POINTER LIST                             */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0030
*   ALTXTPTR(DDNAME)=ADDR(ALATUNIT(DDNAME));                       0030
         LA    @10,ALATUNIT                                        0030
         ST    @10,ALTXTPTR                                        0030
*   ALTXTPTR(SYSOUT)=ADDR(ALATUNIT(SYSOUT));                       0031
         LA    @10,ALATUNIT+14                                     0031
         ST    @10,ALTXTPTR+4                                      0031
*   IF ALUNALLO='1'B THEN           /* IF UNALLOCATION AT CLOSE IS 0032
*                                      DESIRED                       */
         L     @10,@PC00001+8                                      0032
         TM    ALUNALLO(@10),B'10000000'                           0032
         BNO   @RF00032                                            0032
*     ALTXTPTR(UNACLOSE)=ADDR(ALATUNIT(UNACLOSE));                 0033
         LA    @10,ALATUNIT+28                                     0033
         ST    @10,ALTXTPTR+8                                      0033
*   ELSE                                                           0034
*     DO;                                                          0034
         B     @RC00032                                            0034
@RF00032 DS    0H                                                  0035
*       ALTXTPTR(UNACLOSE)=0;       /* DONT UNALLOCATE AT CLOSE      */
         SR    @10,@10                                             0035
         ST    @10,ALTXTPTR+8                                      0035
*       S99JBSYS='1'B;              /* SET BIT TO INDICATE WHOLE   0036
*                                      TRACK GROUP NOT TO BE ASSIGNED*/
         OI    S99JBSYS,B'00010000'                                0036
*     END;                                                         0037
*                                                                  0037
*   /*****************************************************************/
*   /*                                                               */
*   /* SET HIGH ORDER BIT IN LAST TEXT UNIT POINTER                  */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0038
*   ADDR(ALTXTPTR(UNACLOSE))->S99TUPND='1'B;                       0038
*                                                                  0038
@RC00032 LA    @10,ALTXTPTR+8                                      0038
         OI    S99TUPND(@10),B'10000000'                           0038
*   /*****************************************************************/
*   /*                                                               */
*   /* INITIALIZE TEXT UNITS ACCORDING TO INPUT PARAMETERS           */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0039
*   ALATEXT(DDNAME,1:8)=ALDDNAME;                                  0039
         L     @10,@PC00001                                        0039
         MVC   ALATEXT(8),ALDDNAME(@10)                            0039
*   ALATEXT(SYSOUT,1)=ALSYSOUT;                                    0040
*                                                                  0040
         L     @10,@PC00001+4                                      0040
         MVC   ALATEXT+14(1),ALSYSOUT(@10)                         0040
*   /*****************************************************************/
*   /*                                                               */
*   /* ISSUE DYNAMIC ALLOCATION REQUEST MACDATE Y-2 73018            */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0041
*   RESPECIFY                                                      0041
*    (GPR00P,                                                      0041
*     GPR01P,                                                      0041
*     GPR14P,                                                      0041
*     GPR15P)RESTRICTED;                                           0041
*   GPR01P=ADDR(S99RBPTR);                                         0042
*                                                                  0042
         LA    GPR01P,S99RBPTR                                     0042
*   /*****************************************************************/
*   /*                                                               */
*   /* MACDATE Y-2 73082                                             */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0043
*   SVC(99);                                                       0043
         SVC   99                                                  0043
*   ALRETCOD=GPR15F;                                               0044
*                                                                  0044
         LR    ALRETCOD,GPR15F                                     0044
*   /*****************************************************************/
*   /*                                                               */
*   /* MACDATE Y-2 73018                                             */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0045
*   RESPECIFY                                                      0045
*    (GPR00P,                                                      0045
*     GPR01P,                                                      0045
*     GPR14P,                                                      0045
*     GPR15P)UNRESTRICTED;                                         0045
*                                                                  0045
*   /*****************************************************************/
*   /*                                                               */
*   /* TEST FOR SUCCESSFUL COMPLETION                                */
*   /*                                                               */
*   /*****************************************************************/
*                                                                  0046
*   IF ALRETCOD^=0 THEN                                            0046
         LTR   ALRETCOD,ALRETCOD                                   0046
         BZ    @RF00046                                            0046
*     GENERATE(ABEND 1203,DUMP);                                   0047
         ABEND 1203,DUMP
*   RETURN;                         /* RETURN TO CALLER              */
@EL00001 L     @13,4(,@13)                                         0048
@EF00001 L     @00,@SIZDATD                                        0048
         LR    @01,@11                                             0048
         FREEMAIN R,LV=(0),A=(1)
@ER00001 LM    @14,@12,12(@13)                                     0048
         BR    @14                                                 0048
*   END                                                            0049
*                                                                  0049
*/* THE FOLLOWING INCLUDE STATEMENTS WERE FOUND IN THIS PROGRAM.     */
*/*%INCLUDE SYSLIB  (IEFZB4D0)                                       */
*/*%INCLUDE SYSLIB  (IEFZB4D2)                                       */
*                                                                  0049
*       ;                                                          0049
         B     @EL00001                                            0049
@DATA    DS    0H
@CH00058 DC    H'1'
@CH00341 DC    H'3'
@CH00364 DC    H'14'
@DATD    DSECT
         DS    0F
@SA00001 DS    18F
@PC00001 DS    3F
IRBMFALL CSECT
         DS    0F
@DATD    DSECT
         DS    0D
S99RBPTR DS    AL4
         ORG   S99RBPTR
S99RBPND DS    BL1
         ORG   S99RBPTR+4
S99TUFP  DS    A
S99RB    DS    CL20
         ORG   S99RB
S99RBLN  DS    CL1
S99VERB  DS    CL1
S99FLAG1 DS    CL2
         ORG   S99FLAG1
S99FLG11 DS    CL1
         ORG   S99FLG11
S99ONCNV DS    BL1
S99NOCNV EQU   S99FLG11+0
S99NOMNT EQU   S99FLG11+0
S99JBSYS EQU   S99FLG11+0
         ORG   S99FLAG1+1
S99FLG12 DS    CL1
         ORG   S99RB+4
S99RSC   DS    CL4
         ORG   S99RSC
S99ERROR DS    CL2
S99INFO  DS    CL2
         ORG   S99RB+8
S99TXTPP DS    AL4
S99RSV01 DS    FL4
S99FLAG2 DS    CL4
         ORG   S99FLAG2
S99FLG21 DS    CL1
         ORG   S99FLG21
S99WTVOL DS    BL1
S99WTDSN EQU   S99FLG21+0
S99NORES EQU   S99FLG21+0
S99WTUNT EQU   S99FLG21+0
S99OFFLN EQU   S99FLG21+0
S99TIONQ EQU   S99FLG21+0
S99CATLG EQU   S99FLG21+0
S99MOUNT EQU   S99FLG21+0
         ORG   S99FLAG2+1
S99FLG22 DS    CL1
S99FLG23 DS    CL1
S99FLG24 DS    CL1
         ORG   S99RB+20
ALTXTPTR DS    3A
ALATUNIT DS    CL14
         ORG   ALATUNIT+0
ALAKEY   DS    CL2
ALANUM   DS    FL2
ALALEN   DS    FL2
ALATEXT  DS    CL8
         ORG   ALATUNIT+42
         ORG   *+1-(*-@DATD)/(*-@DATD) INSURE DSECT DATA
@ENDDATD EQU   *
IRBMFALL CSECT
         DS    0F
@SIZDATD DC    AL1(0)
         DC    AL3(@ENDDATD-@DATD)
         DS    0D
ALPATCH  DS    CL100
ALSTUNIT DS    CL14
         ORG   ALSTUNIT+0
ALSKEY   DC    X'0001'
ALSNUM   DC    XL2'0001'
ALSLEN   DC    XL2'0008'
ALSTEXT  DC    CL8' '
         ORG   ALSTUNIT+14
         ORG   ALSTUNIT+14
         DC    X'0018'
         DC    XL2'0001'
         DC    XL2'0001'
         DC    CL8' '
         ORG   ALSTUNIT+28
         ORG   ALSTUNIT+28
         DC    X'001C'
         DC    XL2'0000'
         DC    XL2'0000'
         DC    CL8' '
         ORG   ALSTUNIT+42
@00      EQU   00                      EQUATES FOR REGISTERS 0-15
@01      EQU   01
@02      EQU   02
@03      EQU   03
@04      EQU   04
@05      EQU   05
@06      EQU   06
@07      EQU   07
@08      EQU   08
@09      EQU   09
@10      EQU   10
@11      EQU   11
@12      EQU   12
@13      EQU   13
@14      EQU   14
@15      EQU   15
ALRETCOD EQU   @02
ALLOOPV  EQU   @02
GPR15F   EQU   @15
GPR00P   EQU   @00
GPR01P   EQU   @01
GPR14P   EQU   @14
GPR15P   EQU   @15
GPR00F   EQU   @00
GPR01F   EQU   @01
GPR14F   EQU   @14
S99TUPL  EQU   0
S99TUPTR EQU   S99TUPL
S99TUP   EQU   0
S99TUPND EQU   S99TUP
S99TUNIT EQU   0
S99TUENT EQU   S99TUNIT+4
S99TUFLD EQU   0
IKEBC    EQU   0
IKEBF15  EQU   0
IKEBF31  EQU   0
IKEBP15  EQU   0
IKEBP31  EQU   0
IKEBP8   EQU   0
ALDDNAME EQU   0
ALSYSOUT EQU   0
ALUNALLO EQU   0
         AGO   .@UNREFD                START UNREFERENCED COMPONENTS
S99TUPRM EQU   S99TUFLD+2
S99TULEN EQU   S99TUFLD
S99TUPAR EQU   S99TUENT+2
S99TULNG EQU   S99TUENT
S99TUNUM EQU   S99TUNIT+2
S99TUKEY EQU   S99TUNIT
S99TUPLN EQU   S99TUPTR
.@UNREFD ANOP                          END UNREFERENCED COMPONENTS
@RF00046 EQU   @EL00001
@ENDDATA EQU   *
         END   IRBMFALL,(C'PL/S-II',0502,74087)
