          MACRO
          IEFSDDSB
*                                                                MAPMAC
*****************************************************************MAPMAC
*                                                                MAPMAC
*                THE FOLLOWING IS THE MACRO WHICH EXPANDS        MAPMAC
*                THE DATA SET BLOCK (DSB) IN THE SYSOUT          MAPMAC
*                WRITER MODULE IEFSD085.                         MAPMAC
*                                                                MAPMAC
*                ANY CHANGES TO THIS MACRO MUST BE VAILID        MAPMAC
*                FOR ALL MODULES CONTAINING THIS MACRO.          MAPMAC
*                                                                MAPMAC
*****************************************************************MAPMAC
DSB      DSECT
         DS    0F                                                MAPMAC
DSBDSKAD DS    XL3               TTR OF THIS DSB                 MAPMAC
DSBTABID DS    XL1               TABLE ID                        MAPMAC
DSBNXT   DS    XL3               TTR OF NEXT DSB                 MAPMAC
         DS    XL2               RESERVED                        MAPMAC
DSBPCCPY DS    XL1               NO. OF COPIES OF SYSOUT DS      MAPMAC
DSBPCPTN DS    H                 LAST TWO CHARS OF TEST          MAPMAC
*                                      PTRN.MEM.NAME             MAPMAC
         DS    XL1               RESERVED                        MAPMAC
DSBLGOUT DS    XL1               LOG OUT BITS                    MAPMAC
DSBFLAG  DC    X'FF'             STATUS BYTE TO DISTINGUISH      MAPMAC
*                                     FROM SMB                   MAPMAC
DSBWSMNT DS    XL1               WARM START INDICATIOR THAT      MAPMAC
*                                     VOLUME NOT MOUNTED         MAPMAC
DSBTIOLN DS    XL1               LNTH OF TIOT PORTION OF DSB     MAPMAC
DSBSTTA  DS    XL1               STATUS -A-                      MAPMAC
DSBRLOC  DS    H                 REL. LOCATION OF POOL           MAPMAC
DSBDDNAM DS    CL8               DDNAME OF SPOOLED OUTPUT DS     MAPMAC
DSBJFCB  DS    XL3               JFCB DISK ADDRESS               MAPMAC
DSBSTTC  DS    XL1               STATUS -C-                      MAPMAC
DSBSTTB  DS    XL1               STATUS -B-                      MAPMAC
DSBFSRT  DS    XL3               SRT ADDRESS                     MAPMAC
*                                                                MAPMAC
*  DISPLACEMENTS FROM THIS POINT ON MAY BE INCORRECT FOR TIOT    MAPMAC
*  ENTRIES LONGER THAN THE MINIMUM. DSBTIOLN SHOULD BE USED      MAPMAC
*  IN ESTABLISHING ADDRESSABILITY FOR THE REMAINDER OF THE DSB   MAPMAC
*                                                                MAPMAC
DSBBASE  EQU   DSBTIOLN-DSBDSKAD LENGTH OF DSB BASE              MAPMAC
DSBXXX   DS    XL1               RESERVED                        MAPMAC
DSBCLA   DS    CL1               OUTPUT CLASS                    MAPMAC
         DS    XL2                                               MAPMAC
DSBFOR   DS    F                 FORM TYPE TO BE USED            MAPMAC
*                                FROM SYSOUT DD                  MAPMAC
DSBPRG   DS    2F                NAME OF USER WRITER             MAPMAC
*                                FROM SYSOUT DD                  MAPMAC
DSBSMF   EQU   *                                                 MAPMAC
DSBCPUID DS    F                 SID AND MDL FROM SMCA           MAPMAC
DSBJOB   DS    2F                JOB NAME                        MAPMAC
DSBENTRY DS    F                 ENTRY TIME IN 1/100'S SEC       MAPMAC
DSBDATE  DS    F                 ENTRY DATE OOYYDDDF             MAPMAC
DSBUSEID DS    2F                USER ID - INIT BLK BY R/I       MAPMAC
*                                            EACH JOB            MAPMAC
DSBCLAS  DS    CL1               OUTPUT CLASS                    MAPMAC
         DS    0F                                                MAPMAC
DSBHOLD  DS    XL3               TTR IN INPUT DS AT POINT        MAPMAC
*                                    OF INTERRUPTION             MAPMAC
DSBVOL   DS    XL1               VOL AT PT OF INTERRUPTION       MAPMAC
DSBPAGE  DS    XL2               PAGE IN BLK AT PT OF INTERPT    MAPMAC
*                                                                MAPMAC
*****************************************************************MAPMAC
         MEND
