         MACRO
         IEFVMEWA &X
* L.01 R/I LEVEL NUMBER
*
*          ********************************************************
*          *                                                      *
*          *   THE INFORMATION MAPPED BY THIS MACRO IS USED ONLY  *
*          *      BY THE INTERPRETER EXEC ROUTINE AND IS NOT      *
*          *        PRESERVED BY OTHER INTERPRETER ROUTINES       *
*          *                                                      *
*          ********************************************************
*
EWA      DSECT
*                                                                A22206
*2362                                                              AACA
         USING EWA,RA
         AIF   ('&X' EQ 'NA').SKIP
         IEFVMAWA
.SKIP    ANOP
EATEMP1  DS    F                  TEMPORARY SAVE ONE.
EATEMP2  DS    F                  TEMPORARY SAVE TWO.
*
EASW1    DS    CL1           FLAGS (INTERNAL).
EAPGMSDF EQU   128                PGM EQUAL *. FLAG.
EAPGMEF  EQU   64                 PGM EQUAL FLAG.
EAACTORF EQU   32                 PREVIOUS ACT O'RIDE FLAG INDICATION.
EACONORF EQU   16                 PREVIOUS COND O'RIDE INDICATION.
EACNDF1  EQU   8                  COND HSKPNG BIT 1.
EACNDF2  EQU   4                  COND HSKPNG BIT 2.
EAPARMF1 EQU   2                  PARM FIELD HSKPNG FLAG.
EAERLYER EQU   1                  EARLY ERROR FLAG. -OFF- FAKE SCT.
EASW2    DS    CL1           FLAGS 2 (INTERNAL).
EAREGION EQU   128                REGION ON EXEC STMT.
EAROLL   EQU   64                 ROLL ON EXEC STMT.
EAFONSTF EQU   32                 FOUND RESTARTING STEP.           AACA
EACLCOND EQU   16                CLEAR COND. CODES DEFERRED C/R    AACA
EAEACCTE EQU   08  ACCT=  ON EXEC PROC STATEMENT                 A22206
*
EASNSVL  DS    C                  STEPNAME LENGTH.
EASNSV   DS    8C                 STEPNAME TEMPORARY SAVE.
EAPCSVL  DS    C                  PROCNAME LENGTH.
EAPCSV   DS    8C                 PROCNAME TEMPORARY SAVE.
EAPRSV   DS    8C                 OVERRIDDEN PROCSTEP TEMPORARY SAVE.
EAPRSVF  DS    C                  O'RIDE FLAG (USED BY EAORIDE).
EATTRSV  DS    F                  TEMPORARY TTR SAVE AREA.
*
EAREGSV  DS    10F                INTERNAL EXEC REG SAVE AND WORK AREA.
EAWKEND  EQU   *                  END OF EXECUTE WORK AREA.
***********************************************************************
         SPACE 2
*                                  TABLES
ACT      DS    CL176                     ACCOUNT CONTROL TABLE (ACT)
EAORTABL DS    CL176              O'RIDE TABLE WORK SPACE.
EAAUXWK  DS    CL176              AUXILIARY TABLE WORK SPACE.
ENDEWA   DS    0D
LEWA     EQU   ENDEWA-EWA          LENGTH OF EXEC ROUTINE WORK AREA
         MEND
