*        %GOTO COMBSL;        /* BILINGUAL MAPPING                   /*
         MACRO
         IEZCOM
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
*        COMMUNICATIONS PARAMETER LIST
*              MAPPING MACRO
*
*              RELEASE 20
*              02-16-70
*
         DS    0D
COMLIST  EQU   * COMPTR ->    COMMUNICATIONS PARAMETER LIST
*
COMECBPT DS    A -            PTR TO ECB FOR STOP OR MODIFY COMMAND
COMLAST  DS    0A -           LAST POINTER IN PARAMETER LIST
COMEND   EQU   X'80' -        HIGH ORDER BIT OF LAST PARAMETER POINTER
COMCIBPT DS    A -            PTR TO COMMAND INPUT BUFFER (CIB)
*                               MAPPED BY THE MACRO IEZCIB
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
         MEND  , */
* %COMBSL  :  ;
*
* /*  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  */
*
* /*     COMMUNICATIONS PARAMETER LIST                               */
* /*           MAPPING MACRO                                         */
*
* /*           RELEASE 20                                            */
* /*           02-16-70                                              */
*
* DECLARE
*   1 COMLIST  BASED(COMPTR),
*
*    2 COMECBPT PTR(31),             /* PTR TO ECB FOR STOP OR
*                                       MODIFY COMMAND               */
*    2 COMCIBPT PTR(31),             /* PTR TO COMMAND INPUT BUFFER
*                                       (CIB) MAPPED BY THE MACRO
*                                       IEZCIB                       */
*
* /*  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  */
*
*     3 COMLAST  PTR(31),            /* LAST POINTER IN PARAMETER
*                                       LIST                         */
*      4 COMEND   BIT(1),            /* HIGH ORDER BIT OF LAST
*                                       PARAMETER POINTER            */
*      4 *        BIT(1),            /* RESERVED                     */
*      4 *        BIT(1),            /* RESERVED                     */
*      4 *        BIT(1),            /* RESERVED                     */
*      4 *        BIT(1),            /* RESERVED                     */
*      4 *        BIT(1),            /* RESERVED                     */
*      4 *        BIT(1),            /* RESERVED                     */
*      4 *        BIT(1);            /* RESERVED                     */
