         TITLE 'IFDOLT03 DATA PROTECT TAPE'
         TITLE 'IFDOLT03  DATA PROTECT - TAPE AND UNIT RECORD' @ZA15468
         LCLA  &T,&SPN                                            0002
.@001    ANOP                                                     0002
IFDOLT03 CSECT ,                                                  0002
         BC    15,24(0,@F)
         DC    C'IFDOLT03 28 APR 78'                             0002
         STM   @E,@C,12(@D)                                       0002
         BALR  @B,0                                               0002
@PSTART  DS    0H                                                 0002
         USING @PSTART+00000,@B                                   0002
         ST    @D,@SAV001+4                                       0002
         LA    @F,@SAV001                                         0002
         ST    @F,8(0,@D)                                         0002
         LR    @D,@F                                              0002
*  GEN(USING CHASCT,2);                  /* COMMON AREA BASE REGISTER *
         USING CHASCT,2
         DS    0H
*  /*******************************************************************
*  /*                                                                 *
*  /*                CCW STRING FOR READING TAPE LABEL                *
*  /*                                                                 *
*  /*******************************************************************
*  GEN DATA;
*
*
*  GEN DATA;
*  GEN DATA;
*         GEN DATA;
*
* GENERATE DATA;
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                     DECLARED  REGISTERS                         *
*  /*                                                                 *
*  /*******************************************************************
*  DCL R0  REG(0)  PTR;
*  DCL R1  REG(1)  PTR;
*  DCL R2  REG(2)  PTR;
*  DCL R3  REG(3)  PTR;
*  DCL R4  REG(4)  PTR;
*  DCL R5  REG(5)  PTR;
*  DCL R6  REG(6)  PTR;
*  DCL R7  REG(7)  PTR;
*  DCL R8  REG(8)  PTR;
*  DCL R9  REG(9)  PTR;
*  DCL I REG(8);                         /* INDEX REGISTER      S21052*
*  DCL R10 REG(10) PTR;
*  DCL R11 REG(11) PTR;
*  DCL R12 REG(12) PTR;
*  DCL R13 REG(13) PTR;
*  DCL R14 REG(14) PTR;
*  DCL R15 REG(15) PTR;
*  RESTRICT(2,4,5,6,7,8);
*  DCL CESWT3 CHAR(1) GENERATED;         /* OLTEP SWITCHES       M4506*
*  DCL 1 * CHAR(1) BASED(ADDR(CESWT3)),  /* OLTEP SWITCHES       M4506*
*         2 * BIT(3),                    /* NA                   M4506*
*         2 GRBCTL BIT(1),               /* GRAB IN CONTROL      M4506*
*         2 SUSDEL BIT(1),               /* SUSPENDED DELETION   M4506*
*           3 * BIT(1);                  /* NA                   M4506*
*
*
*
*
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                   SECTION CONTROL TABLE                         *
*  /*                                                                 *
*  /*******************************************************************
*  DCL CHASCT GENERATED;            /* SECTION CONTROL TABLE          *
*  DCL 1 * CHAR(1) BASED(ADDR(CHASCT)+10),  /* SCT STRUCTURE          *
*        3 * BIT(1),                /* NA                             *
*        3 FPM BIT(1);              /* FILE PROTECT MODE BIT          *
*
*  DCL MSSSTAT CHAR(1) GENERATED;       /* MSS STATUS BYTE    @ZA15468*
*  DCL 1 * BASED(ADDR(MSSSTAT)),        /*                    @ZA15468*
*        3 FINITSW BIT(1),              /* FUNCTIONALLY INIT  @ZA15468*
*        3 DINITSW BIT(1),              /* DIAGNOSTICALLY INIT@ZA15468*
*        3 INITSW  BIT(1),              /* INITIALIZED BIT    @ZA15468*
*        3   *     BIT(5);              /* SPARE BITS         @ZA15468*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*           EXIO PARAMETER LIST                                   *
*  /*                                                                 *
*  /*******************************************************************
*
*                                       /* IO EFFECTOR CNTL BLK Y02906*
*                                       /* IN COMMON AREA       Y02906*
*  DCL EFCTRCB CHAR(20) GEND;           /* EFFECTOR CONTROL BLOCK     *
*  DCL CCWPTR PTR(31) GEND;             /* CCW LIST POINTER     Y02906*
*  DCL DVTPTR PTR(31) GEND;             /* DEVICE TABEL POINTER Y02906*
*  DCL FLGA   BIT(8)  GEND;             /* FLAG BYTE 1          Y02906*
*
*  DCL FLGB   BIT(8)  GEND;             /* FLAG BYTE 2          Y02906*
* DCL 1 FLG1A BIT(8) BASED(ADDR(FLGA)),
*       3 BYPASS BIT(1);                 /* BYPASS PREFIX       Y02906*
*
*
*  DCL 1 FLG2 BIT(8) BASED(ADDR(FLGB)),                       /*Y02906*
*        3 INTCALL BIT(1),              /* INTERNAL CALL FOR IO Y02906*
*        3 MODEREQ BIT(1);              /* IF ON MODE SET REQ   Y02906*
*  DCL FILEMSK CHAR(1) GEND;            /* FILE MSK FOR IOEFFEC Y02906*
* DCL SNSCNT CHAR(1) GEND;
* DCL TECBPTRX PTR(31) GEND;
*  DCL IORTNADR GEND;                   /* ADDR OF IO EFFECTOR  Y02906*
*         DCL 1 WAITLST CHAR(16) BDY(WORD), /* WAITIO LIST      Y02906*
*              3 XMGR CHAR(1) INIT('00'X), /* TRANS MGR STUFF   Y02906*
*              3 LVL CHAR(1) INIT('02'X),/* WAITIO LVL          Y02906*
*              3 MODID CHAR(2) INIT('36'), /* IFDOLT36 ID       Y02906*
*              3 TECBPTR PTR(31) INIT(ADDR(TECB)),/* TECB ADDR  Y02906*
*              3 CDSPTR PTR(31) INIT(0),  /*CDS = 0             Y02906*
*              3 FLG BIT(8) INIT('80'X), /* SET WAIT = YES      Y02906*
*               5 WAITYES BIT(1),        /* FLAG TO 1           Y02906*
*              3 TIME CHAR(2) INIT('001E'X); /* TIME IN SECONDS Y02906*
*
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                COMMUNICATION SWITCH STRUCTURE                   *
*  /*                                                                 *
*  /*******************************************************************
*
*  DCL CESWT CHAR(5) GENERATED;     /* COMMUNICATION SWITCHES         *
*  DCL 1 * BASED(ADDR(CESWT)),      /*                                *
*        3 * BIT(8),                /* CESWT                          *
*          5 * BIT(1),              /* NA                             *
*          5 PROTECT BIT(1),        /* DP FOR PRIMARY OR SEC DEVICE   *
*          5 * BIT(6),              /* NA                             *
*        3 * BIT(8),                /* CESWT1                         *
*          5 * BIT(1),              /* NA                             *
*          5 SEEK2321 BIT(1),       /* SEEK ONLY COMMANDS ON 2321     *
*          5 SECONLOK BIT(1),       /* SEC DEV ONLINE OK              *
*          5 * BIT(1),              /* NA                             *
*          5 FILMSK BIT(1),         /* ALLOWS FILE MASK CHANGES       *
*          5 T2321 BIT(1),          /* T2321 IS DEV BEING TESTED      *
*          5 ONLINEOK BIT(1),       /* DEV IS ONLINE PROCEED          *
*          5 * BIT(1),              /* NA                             *
*        3 * BIT(8),                /* CESWT2                         *
*          5 NDCFO BIT(1),          /* PREV OCCUR OF DYN COMM INTERVAL*
*          5 DPONDEV BIT(1),        /* DP HAS BEEN DONE ON THIS DEV   *
*          5 * BIT(1),              /* NA                             *
*          5 CHANTEST BIT(1),       /* DATA PROT TO BE DONE ON CHAN   *
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1),              /* NA                             *
*          5 TAPEHDR BIT(1),        /* TAPE HEADER IS TO BE WRITTEN   *
*         5 AMERLDV BIT(1),              /* ASPEN DEVICE        S21052*
*        3 * BIT(8),                /* CESWT3                         *
*          5 * BIT(1),              /* NA                             *
*          5 BYPALDEV BIT(1),       /* BYPASS ALL TESTS AND DEVICES   *
*          5 BYPDEV BIT(1),         /* BYPASS TESTS ON THIS DEVICE    *
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1);              /* NA                             *
*
*
* /********************************************************************
* /*                                                                  *
* /*                      DEVICE TABLE STRUCTURE                      *
* /*                                                                  *
* /********************************************************************
*
*         DCL  1 * BASED(R7),          /*                       S21050*
*         3 DEVADEB CHAR(8),             /* DEV ADDR IN EBCDIC        *
*                3 UCBAD POINTER(31),  /* UCB ADDR (2BYTES)     S21050*
*                3 DEVFLG1 CHAR(1),    /* FLAG BYTE #1          S21050*
*                 5 STATUS BIT(1),     /* ON LINE VS. OFF-LINE  S21050*
*                 5 PRIMARY BIT(1),    /* PRIMARY BIT           S21050*
*                 5 DPDONE  BIT(1),    /* D.P. COMPLETE         S21050*
*                 5 *       BIT(3),    /* FILL                  S21050*
*                 5 FILEPROT BIT(1),   /* F.P. MODE OPERATION   S21050*
*                 5 *       BIT(1),    /* FILL                  S21050*
*                3 DEVFLG2 CHAR(1),    /* FLAG BYTE # 2         S21050*
*           5 * BIT(2),                  /* N/A                 S21050*
*           5 CEVOL BIT(1),              /* CE VOL ON DEVICE    S21050*
*                 5   STDLABL BIT(1),  /* STANDARD TAPE LABEL   S21050*
*                 5 * BIT(4),          /* FILL                  S21050*
*                3 DEVFLG3 CHAR(1),    /* FLAG BYTE # 3         S21050*
*                 5 * BIT(3),          /* N/A                         *
*                 5   TAPEBIT BIT(1),  /* NOTREADY RESTORE BIT  Y01906*
*                 5 * BIT(1),              /*                 @ZA06048*
*                 5 SYSALLOC BIT(1),       /* DEV ALLOC IN SYS        *
*                 5 * BIT(2),              /*                 @ZA06048*
*                3 DEVFLG4 CHAR(1),    /* FLAG BYTE # 3         S21050*
*                3 TAPELABL CHAR(16),  /* TAPE LABEL SAVE AREA  S21050*
*                 5 VOL CHAR(10),      /* VOL NAME              S21050*
*                 5 HDR CHAR (4),      /* HDR NAME              S21050*
*                 5 MODESV CHAR(1),    /* MODE SAVE AREA        S21050*
*                 5 * CHAR(1),         /* FILL                  S21050*
*                3 ADRHEX CHAR (4),    /* 4 BYTE HEX ADDRESS    S21050*
*                 5 * CHAR(2),         /* FILL                  S21050*
*                 5 HEXAD CHAR(2),      /* HEX ADDR (2 BYTES)   X02906*
*                3 CDSINFOR CHAR(16),    /* CDS INFORMATION     X02906*
*                  5 MODEL CHAR(1),      /* MODEL #             X02906*
*                  5 FEATURES CHAR(1),   /* FEATURES            X02906*
*                    7 STRACK BIT(1),    /* SEVEN TRACK TAPE    X02906*
*                    7 * BIT(7),         /* N/A                 X02906*
*                  5 CLASS CHAR(1),      /* CLASS               X02906*
*                  5 TYPE CHAR(1),       /* TYPE                X02906*
*                  5 * CHAR(12);         /* N/A                 X02906*
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                  TEST EVENT CONTROL BLOCK FIELD                 *
*  /*                                                                 *
*  /*******************************************************************
*
*         DCL 1 TECB,                     /* EVENT BLOCK FOR IO Y02906*
*               2 FLDCNT CHAR(1) INIT('01'X),  /* NUMBER FDLS   Y02906*
*               2 FLDSIZE CHAR(1) INIT('0C'X), /* SIZE EACH FLD Y02906*
*               2 SOMETNG CHAR(1) INIT('00'X), /* N/A           Y02906*
*               2 SNSSIZE CHAR(1) INIT('18'X), /* SENSE EXPTD   Y02906*
*               2 FLG1 CHAR(1) INIT('00'X),    /* FLAGS         Y02906*
*               2 SNSCNTTB CHAR(1) INIT('01'X), /* XPECTED COUNTY02906*
*               2 CLRTECB CHAR(39),      /* LABEL TO CLEAR TECB YM3336*
*                 3 CNTSNS CHAR(1) INIT('00'X), /* NUMB OCCURED Y02906*
*                 3 CNTINT CHAR(1) INIT('00'X), /*NUMB INTERRUPTY02906*
*                 3 CCP CHAR(1),        /* SIO COND CODE        Y02906*
*                 3 * CHAR(3),          /* N/A                  YM3336*
*                 3 CSW1 CHAR(8),       /* CSW NO. ONE          Y02906*
*                   5 * CHAR(4),        /* N/A                  Y02906*
*                   5 STATUSX CHAR(2),  /* TWO STATUS BYTES     Y02906*
*                     7 EXIOK CHAR(1),  /* STATUS BYTE 1        Y02906*
*                       9 * BIT(6),     /* N/A                  Y02906*
*                       9 UNITCK BIT(1), /* UNIT CHECK          Y02906*
*                       9 UNITEXCP BIT(1), /* UNIT EXCEPTION BITY02906*
*                     7 BYTE2 CHAR(1),  /* STATUS BYTE 2        Y02906*
*                       9 * BIT(1),     /* N/A                  Y02906*
*                       9 INLENGTH  BIT(1), /* INCORR LNG IND   Y02906*
*                       9 * BIT(6),     /* N/A                  Y02906*
*                   5 * CHAR(2),        /* N/A                  Y02906*
*                 3 SENSE CHAR(24),     /* SENSE COUNT          Y02906*
*                   5 * CHAR(3),        /* N/A                  Y02906*
*                   5 SNS1 CHAR(7),     /* SENSE BYTES          Y02906*
*                     7 SNSFLD BIT(8),  /* BYTE0  SENSE         Y02906*
*                       9 * BIT(1),     /* N/A                  Y02906*
*                       9 SNS2 BIT(1),  /* BIT 1 SNS BYTE 0     Y02906*
*                     7 * CHAR(2),      /* SNS BYTES 1 & 2      Y02906*
*                     7 * BIT(8),       /* SNS BYTE 3           Y02906*
*                       9 * BIT(5),     /* FILL                 Y02906*
*                       9 PEIND BIT(1), /* BIT 5 BYTE3 OF SNS   Y02906*
*                     7 * CHAR(2),      /* SENCE BYTES 4 AND 5  Y02906*
*                     7 * CHAR(1),      /* SENCE BYTE 6         Y02906*
*                       9 * BIT(4),     /* NOT REFERENCED       Y02906*
*                       9 BIT4 BIT(1);  /* BIT FOUR FOR BIRTCH  Y03128*
*
*  DCL 1 LABEL1 CHAR(80),
*       2 TAPEVOL CHAR(10),
*        3 VOLAB CHAR(4),
*        3 VOLSERNO CHAR(6),
*       2 SECURE CHAR(1),              /* TAPE SECURITY BIT     Y01906*
*       2 * CHAR(69);                  /* N/A                   Y01906*
*  DCL 1 LABEL2 CHAR(80) BASED(ADDR(LABEL1)),
*       3 HDRLAB CHAR(4),
*        3 * CHAR(43),
*        3 * CHAR(7),
*           5 * CHAR(1),
*           5 DATE1 CHAR(5),
*          5 * CHAR(1),                /* N/A                   Y01906*
*        3 * CHAR(26);
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                    MESSAGE STRUCTURES                           *
*  /*                                                                 *
*  /*******************************************************************
*
*  DCL IFDMSG03 EXT ENTRY;          /* MESSAGE MODULE                 *
*  DCL MSGPTR PTR INIT(ADDR(IFDMSG03)); /* POINTER TO MESSAGE MODULE  *
*  DCL 1 * BASED(R4),               /* MESSAGE ADDRESS                *
*        3 MSG1 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG2 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG3 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG4 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG5 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG6 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG7 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG8 PTR,                     /* POINTER TO MESSAGE        *
*        3 MSG9 PTR,                     /* POINTER TO IFD130I  Y01906*
*        3 MSGA PTR,                     /* POINTER TO IFD138I  Y01906*
*        3 MSGB PTR,                     /* POINTER TO IFD139D  Y02008*
*        3 MSGC PTR,                    /* POINTER TO MSG C   @ZA15468*
*        3 MSGD PTR,                    /* POINTER TO MSG D   @ZA15468*
*        3 MSGE PTR,                    /* POINTER TO MSG E   @ZA15468*
*        3 MSGF PTR,                    /* POINTER TO MSG F   @ZA15468*
*'       3 MSGG PTR;                    /* POINTER TO MSG G   @ZA15468*
*'
*  DCL 1 MSG109 BASED(R1),                 /* FORMAT          @ZA06048*
*        3 * CHAR(12),                     /*                 @ZA06048*
*        3 MSGDVAD CHAR(8),                /* DEVICE ADDRESS  @ZA06048*
*        3 * CHAR(1),                      /*                 @ZA06048*
*        3 ONOROFF CHAR(8),                /* ON OR OFF LINE  @ZA06048*
*        3 ALORNOT CHAR(11);               /* ALLOCATED OR NOT        *
*  DCL MSGDVAD1 CHAR(8) BASED(R1+34);    /*DEV ADDR AREA IN MSG S21050*
*  DCL MSGDVAD2 CHAR(8) BASED(R1+36);    /*DEV ADDR AREA IN MSG S21050*
*  DCL MSGDVAD3 CHAR(8) BASED(R1+19);    /*DEV ADDR AREA IN MSG S21050*
*  DCL MSGDVAD4 CHAR(8) BASED(R1+19);    /*DEV ADDR AREA IN MSG S21050*
*  DCL MSGDVAD9 CHAR(8) BASED(R1+29);    /*DEV ADDR AREA IN MSG S21050*
*  DCL MSGDVADA CHAR(8) BASED(R1+16);    /*DEV ADDR AREA IN MSG S21050*
*  DCL MSGDVA39 CHAR(8) BASED(R1+39);    /*DEV ADDR AREA IN MSG Y02008*
*  DCL  MSGSNS CHAR(12) BASED (R1+37);   /* SENSE DATA IN 137I  Y01906*
*  DCL MSGCSW CHAR(14) BASED(R1+18);     /* CSW DATA AREA       S21050*
*  DCL MSGDVADD CHAR(8) BASED(R1+38);   /* DEVICE ADDRESS     @ZA15468*
*  DCL MSGDVADG CHAR(8) BASED(R1+22);   /* DEVICE ADDRESS     @ZA15468*
*  DCL MSGINIT CHAR(14) BASED(R1+43);   /* HOW INITIALIZED    @ZA15468*
*  DCL 1 MSGPARM BASED(R1),         /* NA                             *
*        3 LENGTH CHAR(1),          /* LENGTH OF RESPONSE             *
*        3 BUFAD PTR(24),           /* POINTER TO RESPONSE BUFFER     *
*        3 MSGECBAD FIXED;          /* ECB ADDRESS                    *
*  DCL DECB FIXED INIT(0);          /* EVENT CONTROL BLOCK            *
*   DCL INBUFR CHAR(72) GENERATED;
*    DCL BUFFER CHAR(1) BASED(ADDR(INBUFR));
*
*
*  DCL SECDVPTR PTR(31) GENERATED;  /* DEVICE  TABLE POINTER          *
*  DCL 1 INBUF  CHAR(62),                /* INPUT BUFFER        S21052*
*         3 CSWIN CHAR(14),              /* CONVERTED CSW DATA  S21052*
*        3 * CHAR(6),                  /* CONVERTED DEV ADDR   Y02906*/
*         3 SNSIN CHAR(48);              /* CONVERTED SNS DATA  S21052*
*  DCL AREA FIXED BDY(WORD) INIT(0);     /* AREA FOR PACKED DEC DATE  *
*  DCL AREA1 CHAR(6) INIT('000000000000'X); /* AREA FOR UNPACKED DATE *
*         DCL XAREA CHAR(5) BASED(ADDR(AREA1)+1);
*  DCL RDLAB LABEL GENERATED;       /* CCW LABEL                      *
*  DCL RDLAB1 LABEL GENERATED;      /* CCW LABEL                      *
*  DCL URSNS LABEL GENERATED;            /* LABEL FOR CCW       Y01906*
*  DCL TAB28 PTR(31) GENERATED;     /* NEW MACRO ENTRY POINT          *
*  DCL CNVRT CHAR(14) GENERATED;    /* CONVERT PARAMETER LIST         *
*  /*******************************************************************
*  /*                                                                 *
*  /*                         ONLINE STATUS CHECK                     *
*  /*                                                                 *
*  /*******************************************************************
*  DPTAPE00:
*         R4=MSGPTR;                     /*PUT PTR TO MESSAGE MODULE  *
DPTAPE00 L     @4,MSGPTR                                          0081
*  IF STATUS = '1'B THEN             /* IF DEVICE IS ONLINE   @ZA02796*
         TM    12(@7),B'10000000'                                 0082
         BC    12,@9FF                                            0082
*   DO;                              /*                       @ZA02796*
*    IF CLASS = '08'X &              /* IF DEVICE             @ZA02796*
*       TYPE = '42'X THEN            /* IS MSC                @ZA02796*
         CLI   38(@7),X'08'                                       0084
         BC    07,@9FE                                            0084
         CLI   39(@7),X'42'                                       0084
*       GOTO ONLINOK;                /* ONLINE IS OK          @ZA02796*
         BC    08,ONLINOK                                         0085
*     GOTO DPTAPE01;                 /* GO PRINT MESSAGE      @ZA02796*
         BC    15,DPTAPE01                                        0086
*   END;                                                    /*@ZA01047*
* ONLINOK:                           /*                       @ZA02796*
*         IF DPDONE='1'B THEN
@9FF     EQU   *                                                  0088
ONLINOK  TM    12(@7),B'00100000'                                 0088
*         RETURN;
         BC    03,@EL01                                           0089
*         STDLABL='0'B;                  /* ZERO STANDARD LABEL BIT   *
@9FC     NI    13(@7),B'11101111'                                 0090
*  /*******************************************************************
*  /*                                                                 *
*  /*                          SET UP FOR EXIO                        *
*  /*                                                                 *
*  /*******************************************************************
*   PROTECT = '1'B;                      /*                     Y01906*
         OI    A00007,B'01000000'                                 0091
*   IF CLASS = '08'X THEN              /* IS IT UNIT RECORD DEV,Y01906*
         CLI   38(@7),X'08'                                       0092
*      GOTO URXIO;                     /* YES,GO CHECK FOR READYY01906*
         BC    08,URXIO                                           0093
*
*   MODEREQ = '1'B;                      /* REQUEST MODE SET    Y01906*
         OI    FLG2,B'01000000'                                   0094
*         CCWPTR = ADDR(RDLAB);         /* SET CCW PTR          Y02906*
         LA    @F,RDLAB                                           0095
         ST    @F,CCWPTR                                          0095
*         IF STRACK ='1'B THEN
         TM    37(@7),B'10000000'                                 0096
         BC    12,@9FB                                            0096
*           FILEMSK='AB'X;                                    /*Y02906*
         MVI   FILEMSK,X'AB'                                      0097
         BC    15,@9FA                                            0098
*         ELSE FILEMSK='03'X;                                 /*Y02906*
@9FB     MVI   FILEMSK,X'03'                                      0098
*  GEN(BAL   R5,IORTN);                  /* I/O ROUTINES         M4506*
@9FA     EQU   *                                                  0099
         BAL   R5,IORTN
         DS    0H
*  IF EXIOK = '0D'X THEN                 /* IF CE + DE + UE THENY01906*
         CLI   TECB+16,X'0D'                                      0100
*    GOTO DPTAPE03;                      /*                      M4506*
         BC    08,DPTAPE03                                        0101
*  IF EXIOK ^= '0C'X THEN                /* IF NOT CE + DE THEN Y01906*
         CLI   TECB+16,X'0C'                                      0102
         BC    08,@9F9                                            0102
*   DO;                                  /* UC AND OTHER ERRORS Y01906*
*     IF  STRACK='0'B THEN               /* CHECK FOR 7-TRK     S21052*
         TM    37(@7),B'10000000'                                 0104
*       GOTO DPTAPE02;                   /* 9-TRK BRANCH        S21052*
         BC    08,DPTAPE02                                        0105
*     FILEMSK='2B'X;                     /* SET 7-TRK 200 BPI   Y02906*
         MVI   FILEMSK,X'2B'                                      0106
*     GEN(BAL   R5,IORTN);               /* EXECUTE I/O         S21052*
         BAL   R5,IORTN
         DS    0H
*     IF EXIOK='0D'X THEN                /* UNIT EXCEPTION      S21052*
         CLI   TECB+16,X'0D'                                      0108
*       GOTO DPTAPE03;                   /* NON-STD LABEL       S21052*
         BC    08,DPTAPE03                                        0109
*     IF EXIOK ^='0C'X THEN              /* NOT OKAY            S21052*
         CLI   TECB+16,X'0C'                                      0110
         BC    08,@9F8                                            0110
*       DO;                              /*                     S21052*
*         FILEMSK='6B'X;                /* SET 7-TRK 556 BPI    Y02906*
         MVI   FILEMSK,X'6B'                                      0112
*         GEN(BAL   R5,IORTN);           /* EXECUTE I/O         S21052*
         BAL   R5,IORTN
         DS    0H
*         IF EXIOK='0D'X THEN            /* UNIT EXCEPTION      S21052*
         CLI   TECB+16,X'0D'                                      0114
*           GOTO DPTAPE03;               /* NON-STD LABEL       S21052*
         BC    08,DPTAPE03                                        0115
*         IF EXIOK ^='0C'X THEN          /* NOT OKAY            S21052*
         CLI   TECB+16,X'0C'                                      0116
*           GOTO DPTAPE02;               /* UNREADABLE LABEL    S21052*
         BC    07,DPTAPE02                                        0117
*       END;                             /*                     S21052*
*   END;                                 /*                     S21052*
@9F8     EQU   *                                                  0119
*   TAPEBIT = '0'B;                      /* DRIVE IS READY      Y01906*
@9F9     NI    14(@7),B'11101111'                                 0120
*  /*******************************************************************
*  /*                                                                 *
*  /*                CHECK FOR CORRECT LENGTH & VOL1 IN LABEL         *
*  /*                                                                 *
*  /*******************************************************************
*  IF INLENGTH ='1'B ×              /* IF INCORRECT LENGTH IND OR     *
*     VOLAB ^= 'VOL1' THEN          /* IF VOL1 IS NOT IN THE LABEL    *
         TM    TECB+17,B'01000000'                                0121
         BC    01,@9F7                                            0121
         CLC   LABEL1(4),@C11                                     0121
         BC    08,@9F6                                            0121
*     GOTO DPTAPE03;                /* PRINT MESSAGE TO OPERATOR      *
         BC    07,DPTAPE03                                        0122
*  IF SECURE^='F0'X &                    /* CHECK FOR KNOWN NON-Y01906*
*     SECURE^='40'X &                    /* SECURITY CHARACTERS Y01906*
*     SECURE^='00'X THEN                 /* IF NOT SECURE       Y01906*
@9F6     CLI   LABEL1+10,X'F0'                                    0123
         BC    08,@9F5                                            0123
         CLI   LABEL1+10,X'40'                                    0123
         BC    08,@9F4                                            0123
         CLI   LABEL1+10,X'00'                                    0123
*     GO TO DPTAPE06;               /* GO PRINT MSG 122I        Y01906*
         BC    07,DPTAPE06                                        0124
*         VOL=TAPEVOL;                   /*SAVE VOL SER # IN DEVTAB */
@9F3     EQU   *                                                  0125
@9F4     EQU   *                                                  0125
@9F5     MVC   16(10,@7),LABEL1                                   0125
*         IF STRACK='0'B THEN
         TM    37(@7),B'10000000'                                 0126
         BC    05,@9F2                                            0126
*             DO;                                            /* Y02128*
*            IF PEIND='1'B THEN                             /* Y02128*/
         TM    TECB+26,B'00000100'                                0128
         BC    12,@9F1                                            0128
*              DO;                                          /* Y02128*/
*               FILEMSK = 'C3'X;                             /* YM3334*
         MVI   FILEMSK,X'C3'                                      0130
*               GOTO SETEXIO;                                /* Y02128*
         BC    15,SETEXIO                                         0131
*             END;                                           /* Y02128*
*             FILEMSK = 'CB'X;                               /* YM3334*
@9F1     MVI   FILEMSK,X'CB'                                      0133
*           IF BIT4 =  '1'B THEN       /* IS THIS A BIRCH       X03128*
         TM    TECB+29,B'00001000'                                0134
         BC    12,@9F0                                            0134
*              FILEMSK='D3'X;          /* IF YES SET FILE MSK   X03128*
         MVI   FILEMSK,X'D3'                                      0135
*               END;                                         /* Y02128*
@9F0     EQU   *                                                  0136
*  /*******************************************************************
*  /*                                                                 *
*  /*                          SET UP FOR EXIO                        *
*  /*                                                                 *
*  /*******************************************************************
* SETEXIO:                                                   /* Y02128*
*         CCWPTR = ADDR(RDLAB1);        /* SET CCW PTR          Y02906*
@9F2     EQU   *                                                  0137
SETEXIO  LA    @F,RDLAB1                                          0137
         ST    @F,CCWPTR                                          0137
*  GEN(BAL   R5,IORTN);                  /* I/O ROUTINES         M4506*
         BAL   R5,IORTN
         DS    0H
*  IF UNITEXCP='1'B THEN            /* INDICATES TAPE MARK            *
         TM    TECB+16,B'00000001'                                0139
         BC    12,@9EF                                            0139
*    DO;
*    HDR=' ';                       /*PUT BLANKS IN HDR AREA OF DEVTAB*
         MVI   26(@7),C' '                                        0141
         MVC   27(3,@7),26(@7)                                    0141
*    GOTO SETBITS;
         BC    15,SETBITS                                         0142
*    END;
*         IF EXIOK='0E'X THEN            /* WAS EXIO SUCESSFUL   M4505*
@9EF     CLI   TECB+16,X'0E'                                      0144
*           GOTO DPTAPE02;               /* YES, GO PRINT MSG    M4505*
         BC    08,DPTAPE02                                        0145
*  IF INLENGTH = '1'B ×             /* IF INCORRECT LENGTH BIT IS ON  *
*     HDRLAB ^= 'HDR1' THEN         /* OR HDR1 IS NOT ON TAPE         *
         TM    TECB+17,B'01000000'                                0146
         BC    01,@9EE                                            0146
         CLC   LABEL2(4),@C20                                     0146
         BC    08,@9ED                                            0146
*     GOTO DPTAPE03;                /* GO PRINT MESSAGE               *
         BC    07,DPTAPE03                                        0147
*  /*******************************************************************
*  /*                                                                 *
*  /*           HDR1, EXPIRATION DATE & DATA SECURITY CHECK           *
*  /*                                                                 *
*  /*******************************************************************
*                                        /* GET TODAY'S DATE    Y01906*
*  GEN;
@9ED     EQU   *                                                  0148
         TIME
         DS    0H
*  AREA = R1;                       /* PUT DATE TO BE UNPACKED IN AREA*
         ST    @1,AREA                                            0149
*  GEN;
         UNPK  AREA1(6),AREA+1(3)     UNPACK DATE
         OI    AREA1+5,X'F0'          CHANGE LAST BYTE
         DS    0H
*         IF DATE1 > XAREA THEN    /*IF THE EXPIRATION DATE EXCEEDS*/
         CLC   LABEL2+48(5),XAREA                                 0151
         BC    12,@9EC                                            0151
*           DO;
*           STDLABL='1'B;                /*SET STANDARD LABEL BIT     *
         OI    13(@7),B'00010000'                                 0153
*     GOTO DPTAPE08;                /* THE CURRENT DATE GO PRINT MSG. *
         BC    15,DPTAPE08                                        0154
*           END;
*         HDR=HDRLAB;                    /*SAVE HDR1 IN DEVTAB  */
@9EC     MVC   26(4,@7),LABEL2                                    0156
*  SETBITS:
*  STDLABL='1'B;                    /* SET STANDARD LABEL BIT         *
SETBITS  OI    13(@7),B'00010000'                                 0157
*       DPDONE='1'B;
         OI    12(@7),B'00100000'                                 0158
*  GOTO DPTAPE10;                   /* AND RETRN TO CALLING MODULE    *
         BC    15,DPTAPE10                                        0159
*  /*******************************************************************
*  /*                                                                 *
*  /*                     PRINT MESSAGE IFD109I                       *
*  /*     XXXXXXXX NOT OFFLINE                                        *
*  /*******************************************************************
*  DPTAPE01:
*  R1=MSG1;                         /* POINTER TO MESSAGE             *
DPTAPE01 L     @1,0(0,@4)                                         0160
*  MSGDVAD=DEVADEB;                 /* PUT DEVICE ADDRESS IN MSG1     *
         MVC   12(8,@1),0(@7)                                     0161
*  ONOROFF='ONLINE ,';                     /* SAY DEV ONLINE  @ZA06048*
         MVC   21(8,@1),@C21                                      0162
*  IF SYSALLOC='1'B                        /* CHECK ALLOCATION        *
*    THEN                                  /*                 @ZA06048*
         TM    14(@7),B'00000100'                                 0163
         BC    12,@9EB                                            0163
*      ALORNOT='ALLOCATED  ';              /* IF SO,SAY SO    @ZA06048*
         MVC   29(11,@1),@C22                                     0164
         BC    15,@9EA                                            0165
*    ELSE                                  /* IF NOT,         @ZA06048*
*      ALORNOT='UNALLOCATED';              /* AGAIN,SAY SO    @ZA06048*
@9EB     MVC   29(11,@1),@C23                                     0165
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
@9EA     EQU   *                                                  0166
         BAL   R5,DPTAPE13
         DS    0H
*  BYPDEV='1'B;                     /* SET BYPASS BIT                 *
         OI    A00007+3,B'00100000'                               0167
*         RETURN;
         BC    15,@EL01                                           0168
*  DPTAPE02:
*  IF CCP='F3'X THEN                /* IF CC=3                  YM3332*
DPTAPE02 CLI   TECB+8,X'F3'                                       0169
*    GOTO DPTAPE12;                      /*GO PRINT MESSAGE           *
         BC    08,DPTAPE12                                        0170
*         IF SNS2='1'B THEN
         TM    TECB+23,B'01000000'                                0171
*    GOTO DPTAPE11;               /*PRINT INTERVENTION REQUIRED MSG   *
         BC    01,DPTAPE11                                        0172
*    IF CLASS = '08'X THEN               /* IF UNIT RECORD      Y02008*
         CLI   38(@7),X'08'                                       0173
         BC    07,@9E9                                            0173
*      DO;                               /* YES                 Y02008*
*        R1=MSGC;                        /* SET POINTER IFD212I Y02008*
         L     @1,44(0,@4)                                        0175
*        MSGDVA39 = DEVADEB;             /* DEVICE ADDR IN MSG  Y02008*
         MVC   39(8,@1),0(@7)                                     0176
*        GEN(BAL   R5,DPTAPE13);         /* GO PRINT            Y02008*
         BAL   R5,DPTAPE13
         DS    0H
*        GOTO DPTAPE04;                  /* ISSUE NEXT          Y02008*
         BC    15,DPTAPE04                                        0178
*      END;                              /* NO                  Y02008*
*   TAPEBIT='0'B;                        /* NO RESTORE NTRDY BITY01906*
@9E9     NI    14(@7),B'11101111'                                 0180
*  /*******************************************************************
*  /*                                                                 *
*  /*                     PRINT MESSAGE IFD118I                       *
*  /*     UNREADABLE TAPE LABEL-XXXXXXXX                              *
*  /*******************************************************************
*  R1=MSG2;                         /* POINTER TO MESSAGE             *
         L     @1,4(0,@4)                                         0181
*  MSGDVAD1=DEVADEB;                /* PUT DEVICE ADDRESS IN MSG2     *
         MVC   34(8,@1),0(@7)                                     0182
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
         BAL   R5,DPTAPE13
         DS    0H
*  GOTO DPTAPE04;                   /* GO PRINT SENSE/CSW DATA        *
         BC    15,DPTAPE04                                        0184
*  /*******************************************************************
*  /*                     PRINT MESSAGE IFD119I                       *
*  /*     NON-STANDARD TAPE LABEL-XXXXXXXX                            *
*  /*                                                                 *
*  /*******************************************************************
*  DPTAPE03:
*  R1=MSG4;                         /* POINTER TO MESSAGE             *
DPTAPE03 L     @1,12(0,@4)                                        0185
*  MSGDVAD2=DEVADEB;                /* PUT DEVICE ADDRESS IN MSG4     *
         MVC   36(8,@1),0(@7)                                     0186
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
         BAL   R5,DPTAPE13
         DS    0H
*  GOTO DPTAPE05;                   /* GO PRINT OPTION MESSAGE        *
         BC    15,DPTAPE05                                        0188
*  /*******************************************************************
*  /*                                                                 *
*  /*                     CONVERT SENSE/CSW DATA                      *
*  /*                                                                 *
*  /*******************************************************************
*  DPTAPE04:
*  GEN(BAL   R14,NEWCONV);               /* CONVERT CALL         M4506*
DPTAPE04 BAL   R14,NEWCONV
         DS    0H
*  SUSDEL='1'B;                          /* SUSPEND DELETION     M4506*
         OI    A00000,B'00001000'                                 0190
*  GEN(BAL   R14,NEWCONV);               /* CONVERT CALL         M4506*
         BAL   R14,NEWCONV
         DS    0H
*  /*******************************************************************
*  /*                                                                 *
*  /*                     PRINT MESSAGE IFD137I                       *
*  /*           CSW-XXXXXXXXXXXXXXXX SNS-YYYYYYYYYYYY                 *
*  /*******************************************************************
*  R1=MSG3;                         /* POINTER TO MESSAGE             *
         L     @1,8(0,@4)                                         0192
*  MSGCSW=CSWIN;                    /* PUT CSW DATA IN MSG3           *
         MVC   18(14,@1),INBUF                                    0193
*         MSGSNS = SNSIN;                /* PUT SENSE IN MSG    X02906*
         MVC   37(12,@1),INBUF+20                                 0194
*         GEN(BAL  R5,DPTAPE13);         /* PRINT MSG           S21052*
         BAL  R5,DPTAPE13
         DS    0H
*  /*******************************************************************
*  /*                                                                 *
*  /*                     PRINT MESSAGE IFD139D                       *
*  /* TAPE: REPLY B TO BYPASS,R TO RETRY,P TO PROCEED(MAY DESTROY DATA*
*  /*     UNIT RECORD:   REPLY B TO BYPASS, R TO RETRY,P TO PROCEED   *
*  /*******************************************************************
*  DPTAPE05:
*  IF CLASS = '08'X THEN                 /* IF DEV IS UR,       Y01906*
DPTAPE05 CLI   38(@7),X'08'                                       0196
         BC    07,@9E8                                            0196
*    R1 = MSGB;                          /* PRINT SHORT FORM    Y01906*
         L     @1,40(0,@4)                                        0197
         BC    15,@9E7                                            0198
*    ELSE R1 = MSG6;                     /* PRT MAY DESTROY DATAX02906*
@9E8     L     @1,20(0,@4)                                        0198
*  BUFAD=ADDR(BUFFER);              /* SET UP BUFFER ADDRESS          *
@9E7     LA    @F,BUFFER                                          0199
         ST    @F,@TEMP4                                          0199
         MVC   1(3,@1),@TEMP4+1                                   0199
*  MSGECBAD=ADDR(DECB);             /* POINTER TO PWTO ECB            *
         LA    @F,DECB                                            0200
         ST    @F,4(0,@1)                                         0200
*     DECB=0;                       /* ZERO DECB                      *
         SR    @F,@F                                              0201
         ST    @F,DECB                                            0201
*  LENGTH='01'X;                    /* LENGTH OF RESPONSE             *
         MVI   0(@1),X'01'                                        0202
*  GEN(BAL   R5,DPTAPE14);               /* PRINT AND REPLY      M4506*
         BAL   R5,DPTAPE14
         DS    0H
*  IF BUFFER='P' THEN DO;           /* IF REPLY IS PROCEED            *
         CLI   BUFFER,C'P'                                        0204
         BC    07,@9E6                                            0204
*         DPDONE='1'B;
         OI    12(@7),B'00100000'                                 0206
*     GOTO DPTAPE10;                /* RETURN                         *
         BC    15,DPTAPE10                                        0207
*                    END;
*  IF BUFFER='B' THEN DO;           /* IF REPLY IS BYPASS             *
@9E6     CLI   BUFFER,C'B'                                        0209
         BC    07,@9E5                                            0209
*         IF PRIMARY ='1'B THEN
         TM    12(@7),B'01000000'                                 0211
         BC    12,@9E4                                            0211
*     BYPDEV='1'B;                  /* TURN ON BYPASS BIT             *
         OI    A00007+3,B'00100000'                               0212
*     GOTO DPTAPE10;                /* RETURN                         *
         BC    15,DPTAPE10                                        0213
*                    END;
*  IF BUFFER='R' THEN               /* IF REPLY IS RETRY              *
@9E5     CLI   BUFFER,C'R'                                        0215
*     GOTO DPTAPE00;                /* GOTO TO BEGINNING OF MODULE    *
         BC    08,DPTAPE00                                        0216
*  ELSE GOTO DPTAPE05;              /* TRY AGAIN REPLY NOT RECOGNIZED *
         BC    15,DPTAPE05                                        0217
*  /*******************************************************************
*  /*                                                                 *
*  /*        SET UP FOR SENSE FOR UNIT RECORD DEVICES                 *
*  /*                                                                 *
*  /*******************************************************************
*
* URXIO:
*  IF TYPE='42'X THEN                   /* IF THE DEVICE IS   @ZA15468*
URXIO    CLI   39(@7),X'42'                                       0218
         BC    07,@9E3                                            0218
*    DO;                                /* AN MSS, CHECK TO   @ZA15468*
*      IF INITSW='1'B THEN              /* SEE IF IT IS       @ZA15468*
         TM    A00005,B'00100000'                                 0220
         BC    12,@9E2                                            0220
*        DO;                            /* INITIALIZED AND IF @ZA15468*
*          R1=MSGG;                     /* IT IS, TELL HOW    @ZA15468*
         L     @1,60(0,@4)                                        0222
*          MSGDVADG=DEVADEB;            /* EITHER FUNCTIONALLY@ZA15468*
         MVC   22(8,@1),0(@7)                                     0223
*          IF FINITSW='1'B THEN         /* OR DIAGNOSTICALLY  @ZA15468*
         TM    A00005,B'10000000'                                 0224
         BC    12,@9E1                                            0224
*            MSGINIT='FUNCTIONALLY  ';  /* WRITE THE MESSAGE  @ZA15468*
         MVC   43(14,@1),@C29                                     0225
         BC    15,@9E0                                            0226
*          ELSE                         /* TO THE USER.       @ZA15468*
*            MSGINIT='DIAGNOSTICALLY';  /*                    @ZA15468*
@9E1     MVC   43(14,@1),@C30                                     0226
*          GEN(BAL R5,DPTAPE13);        /*                    @ZA15468*
@9E0     EQU   *                                                  0227
         BAL R5,DPTAPE13
         DS    0H
*          GO TO DPURMSC;               /* THEN CONTINUE WITH @ZA15468*
         BC    15,DPURMSC                                         0228
*        END;                           /* DATA PROTECTION.   @ZA15468*
*      R1=MSGD;                         /* IF THE INTERFACE   @ZA15468*
@9E2     L     @1,48(0,@4)                                        0230
*      MSGDVADD=DEVADEB;                /* IS NOT INITIALIZED @ZA15468*
         MVC   38(8,@1),0(@7)                                     0231
*      GEN(BAL R5,DPTAPE13);            /* TELL THE USER AND  @ZA15468*
         BAL R5,DPTAPE13
         DS    0H
*      R1=MSGE;                         /* AND GIVE THE OPTION@ZA15468*
         L     @1,52(0,@4)                                        0233
*      GEN(BAL R5,DPTAPE13);            /* OF BYPASSING THE   @ZA15468*
         BAL R5,DPTAPE13
         DS    0H
* DPMSGF:                               /* TEST OR TAKING A   @ZA15468*
*      R1=MSGF;                         /* CHANCE AND WIPING  @ZA15468*
DPMSGF   L     @1,56(0,@4)                                        0235
*      BUFAD=ADDR(BUFFER);              /* OUT A PACK.        @ZA15468*
         LA    @F,BUFFER                                          0236
         ST    @F,@TEMP4                                          0236
         MVC   1(3,@1),@TEMP4+1                                   0236
*      MSGECBAD=ADDR(DECB);             /* SET UP FOR A REPLY @ZA15468*
         LA    @F,DECB                                            0237
         ST    @F,4(0,@1)                                         0237
*      DECB=0;                          /* ZERO THE ECB       @ZA15468*
         SR    @F,@F                                              0238
         ST    @F,DECB                                            0238
*      LENGTH='01'X;                    /* SET MESSAGE LENGTH @ZA15468*
         MVI   0(@1),X'01'                                        0239
*      GEN(BAL R5,DPTAPE14);            /* GO WRITE MESSAGE   @ZA15468*
         BAL R5,DPTAPE14
         DS    0H
*      IF BUFFER='P' THEN               /* IF USER REPLIED P  @ZA15468*
         CLI   BUFFER,C'P'                                        0241
*        GO TO DPURMSC;                 /* CONTINUE           @ZA15468*
         BC    08,DPURMSC                                         0242
*      IF BUFFER='B' THEN               /* IF USER REPLIED B  @ZA15468*
         CLI   BUFFER,C'B'                                        0243
         BC    07,@9DF                                            0243
*        DO;                            /* SET SWITCHES TO    @ZA15468*
*          IF PRIMARY='1'B THEN         /* BYPASS THE TEST    @ZA15468*
         TM    12(@7),B'01000000'                                 0245
         BC    12,@9DE                                            0245
*            BYPDEV='1'B;               /*                    @ZA15468*
         OI    A00007+3,B'00100000'                               0246
*          GO TO DPTAPE10;              /* RETURN TO IFDOLT52 @ZA15468*
         BC    15,DPTAPE10                                        0247
*        END;                           /*                    @ZA15468*
*      GO TO DPMSGF;                    /* REWRITE THE MESSAGE        *
*    END;                               /*                    @ZA15468*
* DPURMSC:                              /*                    @ZA15468*
*   MODEREQ = '0'B;                      /* NO MODE SET NEEDED  Y01906*
@9E3     EQU   *                                                  0251
DPURMSC  NI    FLG2,B'10111111'                                   0251
*         CCWPTR = ADDR(URSNS);         /* SET CCW PTR          Y02906*
         LA    @F,URSNS                                           0252
         ST    @F,CCWPTR                                          0252
*  IF TYPE='4C'X THEN                   /* IF DEVICE IS 3838  @G29AFAA*
         CLI   39(@7),X'4C'                                       0253
         BC    07,@9DD                                            0253
*    DO;                                /* ARRAY PROCESSOR    @G29AFAA*
*      DPDONE='1'B;                     /* SET DPDONE FLAG ON @G29AFAA*
         OI    12(@7),B'00100000'                                 0255
*      GO TO DPTAPE10;                  /* EXIT MODULE        @G29AFAA*
         BC    15,DPTAPE10                                        0256
*    END;                                                   /*@G29AFAA*
*  GEN(BAL   R5,IORTN);                  /* GO DO IO OP         Y01906*
@9DD     EQU   *                                                  0258
         BAL   R5,IORTN
         DS    0H
*  IF EXIOK='0C' THEN                    /* IS IO OP SUCCESSFUL Y01906*
         CLC   TECB+16(1),@C32                                    0259
         BC    07,@9DC                                            0259
*         DO;                           /*                      YM3384*
*         DPDONE='1'B;                  /* SET DPDONE FLG ON    YM3384*
         OI    12(@7),B'00100000'                                 0261
*          GO TO DPTAPE10;         /* EXIT MODULE               YM2271*
         BC    15,DPTAPE10                                        0262
*         END;                          /*                      YM3384*
*  IF SNS2='1'B THEN                     /* NO,IS INT, REQUIRED Y01906*
@9DC     TM    TECB+23,B'01000000'                                0264
*    GOTO DPTAPE11;                      /* YES,GO PUT OUT MSG. Y01906*
         BC    01,DPTAPE11                                        0265
*         DPDONE='1'B;                  /* SET DPDONE FLG ON    YM3384*
         OI    12(@7),B'00100000'                                 0266
*          GO TO DPTAPE10;         /* EXIT MODULE               YM2271*
         BC    15,DPTAPE10                                        0267
*  /*******************************************************************
*  /*                                                                 *
*  /*                          PRINT MESSAGE IFD122I                  *
*  /*     VOL ON XXXXXXXX SECURITY PROTECTED                          *
*  /*******************************************************************
*  DPTAPE06:
*  R1=MSG5;                         /* POINTER TO MESSAGE             *
DPTAPE06 L     @1,16(0,@4)                                        0268
*  MSGDVAD3=DEVADEB;                /* PUT DEVICE ADDRESS IN MSG5     *
         MVC   19(8,@1),0(@7)                                     0269
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
         BAL   R5,DPTAPE13
         DS    0H
*  /*******************************************************************
*  /*                                                                 *
*  /*                          PRINT MESSAGE IFD139D                  *
*  /*     REPLY B TO BYPASS, R TO RETRY                               *
*  /*******************************************************************
*  DPTAPE07:
*  R1=MSG8;                         /* POINTER TO MESSAGE             *
DPTAPE07 L     @1,28(0,@4)                                        0271
*  BUFAD=ADDR(BUFFER);              /* SET UP BUFFER ADDRESS          *
         LA    @F,BUFFER                                          0272
         ST    @F,@TEMP4                                          0272
         MVC   1(3,@1),@TEMP4+1                                   0272
*  MSGECBAD=ADDR(DECB);             /* POINTER TO PWTOR ECB           *
         LA    @F,DECB                                            0273
         ST    @F,4(0,@1)                                         0273
*  LENGTH='01'X;                    /* LENGTH OF RESPONSE             *
         MVI   0(@1),X'01'                                        0274
*     DECB=0;                       /* ZERO DECB                      *
         SR    @F,@F                                              0275
         ST    @F,DECB                                            0275
*  GEN(BAL   R5,DPTAPE14);               /* PRINT AND REPLY      M4506*
         BAL   R5,DPTAPE14
         DS    0H
*  IF BUFFER= 'B' THEN DO;          /* IF REPLY IS BYPASS             *
         CLI   BUFFER,C'B'                                        0277
         BC    07,@9DB                                            0277
*         IF PRIMARY ='1'B THEN
         TM    12(@7),B'01000000'                                 0279
         BC    12,@9DA                                            0279
*     BYPDEV='1'B;                  /* SET BYPASS BIT                 *
         OI    A00007+3,B'00100000'                               0280
*     GOTO DPTAPE10;                /* RETURN                         *
         BC    15,DPTAPE10                                        0281
*                     END;
*  IF BUFFER= 'R' THEN              /* IF REPLY IS RETRY              *
@9DB     CLI   BUFFER,C'R'                                        0283
*     GOTO DPTAPE00;                /* GOTO BEGINNING OF MODULE       *
         BC    08,DPTAPE00                                        0284
*  ELSE GOTO DPTAPE07;              /* TRY AGAIN REPY NOT RECOGNIZED  *
         BC    15,DPTAPE07                                        0285
*  /*******************************************************************
*  /*                                                                 *
*  /*     PRINT IFD122I VOL ON XXXXXXXX UNEXPIRED DATE                *
*  /*                                                                 *
*  /*******************************************************************
*  DPTAPE08:
*  R1=MSG7;                         /* POINTER TO MESSAGE             *
DPTAPE08 L     @1,24(0,@4)                                        0286
*  MSGDVAD4=DEVADEB;                /* PUT DEVICE ADDRESS IN MSG7     *
         MVC   19(8,@1),0(@7)                                     0287
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
         BAL   R5,DPTAPE13
         DS    0H
*  GOTO DPTAPE05;                   /* GO PRINT OPTION MESSAGE        *
         BC    15,DPTAPE05                                        0289
*
*  /*******************************************************************
*  /*                                                                 *
*  /*           PRINT IFD130I MESSAGE                                 *
*  /*     INTERVENTION REQ XXXXXXXX                                   *
*  /*******************************************************************
*  DPTAPE11:
*         R1=MSG9;                       /* PUT PTR TO MSG IN R1      *
DPTAPE11 L     @1,32(0,@4)                                        0290
*         MSGDVAD9=DEVADEB;              /*PUT DEV ADDR IN MSG        *
         MVC   29(8,@1),0(@7)                                     0291
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
         BAL   R5,DPTAPE13
         DS    0H
*     GO TO DPTAPE05;               /* GO GIVE OPTIONS B, R, P  Y01906*
         BC    15,DPTAPE05                                        0293
*  /*******************************************************************
*  /*                                                                 *
*  /*                          PRINT MESSAGE IFD138I                  *
*  /*     DEV XXXXXXXX NOT OPERATIONAL,CC=3                           *
*  /*******************************************************************
*  DPTAPE12:
*         R1=MSGA;                       /* POINTER TO MESSAGE        *
DPTAPE12 L     @1,36(0,@4)                                        0294
*         MSGDVADA=DEVADEB;              /*PUT DEV ADDR IN MSG        *
         MVC   16(8,@1),0(@7)                                     0295
*  GEN(BAL   R5,DPTAPE13);               /* PRINT MESSAGE        M4506*
         BAL   R5,DPTAPE13
         DS    0H
*         GOTO DPTAPE05;                 /*GO PRINT MSG IFD139D       *
         BC    15,DPTAPE05                                        0297
* DPTAPE13:                              /*                      M4506*
*  GEN(PWTO  REG=(1));                   /* PRINT MESSAGE        M4506*
DPTAPE13 PWTO  REG=(1)
         DS    0H
*  GOTO R5;                              /* RESUME PROGRAM       M4506*
         BCR   15,@5                                              0299
* DPTAPE14:                              /*                      M4506*
*  GEN(PWTOR REG=(1));                   /* PRINT AND REPLY      M4506*
DPTAPE14 PWTOR REG=(1)
         DS    0H
*  GOTO R5;                              /* RESUME PROGRAM       M4506*
         BCR   15,@5                                              0301
*  DPTAPE10:
*         MODESV=FILEMSK;                                     /*Y02906*
DPTAPE10 MVC   30(1,@7),FILEMSK                                   0302
*         PROTECT='0'B;
         NI    A00007,B'10111111'                                 0303
*  RETURN;                          /* RETURN TO CALLING MODULE       *
         BC    15,@EL01                                           0304
* IORTN:
*         FLGB   = '00'X;               /* ZIP FLAGS            Y02906*
IORTN    MVI   FLGB,X'00'                                         0305
*         CLRTECB = CLRTECB && CLRTECB; /* CLEAR TECB           Y02906*
         XC    TECB+6(39),TECB+6                                  0306
*         DVTPTR = R7;                  /* SET DEVTAB ENTRY PTR Y02906*
         ST    @7,DVTPTR                                          0307
*         FLGA   = '00'X;               /* ZIP FLAGS            Y02906*
         MVI   FLGA,X'00'                                         0308
*         INTCALL = '1'B;               /* SET INTERNAL CALL SW Y02906*
         OI    FLG2,B'10000000'                                   0309
*         BYPASS = '1'B;                 /* SET BYPASS PREFIX SWY02906*
         OI    FLG1A,B'10000000'                                  0310
*         SNSCNT = '18'X;                /* SET SENSE COUNT     Y02906*
         MVI   SNSCNT,X'18'                                       0311
*         TECBPTRX = ADDR(TECB);         /* SET ADDR TECB       Y02906*
         LA    @F,TECB                                            0312
         ST    @F,TECBPTRX                                        0312
*         CDSPTR = ADDR(ADRHEX);        /* SET ADDR OF CDS DEV  Y02906*
         LA    @F,32(0,@7)                                        0313
         ST    @F,WAITLST+8                                       0313
*         R15  = IORTNADR;              /* GET EFFECTOR PTR     Y02906*
         L     @F,IORTNADR                                        0314
*         GEN(BALR R14,R15);            /* GO SIO               Y02906*
         BALR R14,R15
         DS    0H
*         R1 = ADDR(WAITLST);           /* GET POINTER FOR WAIT Y02906*
         LA    @1,WAITLST                                         0316
*         R15 = TAB28;                   /* GET TRANS MGR ENTRY Y02906*
         L     @F,TAB28                                           0317
*         GEN(BALR  14,15);             /* GO TO WAIT MODULE    Y02008*
         BALR  14,15
         DS    0H
*         GO TO R5;                     /* RETURN TO CALLER     Y02008*
         BCR   15,@5                                              0319
* NEWCONV:
*  R1=ADDR(CNVRT);                       /* CONVERT PARAMETER    M4506*
NEWCONV  LA    @1,CNVRT                                           0320
*  R15=TAB28;                            /* TRANSIENT MANAGER    M4506*
         L     @F,TAB28                                           0321
*  GOTO R15;                             /* CALL CONVERT         M4506*
         BCR   15,@F                                              0322
*         END;
@EL01    L     @D,4(0,@D)                                         0323
         LM    @E,@C,12(@D)                                       0323
         BCR   15,@E                                              0323
@DATA1   EQU   *
@0       EQU   00                  EQUATES FOR REGISTERS 0-15
@1       EQU   01
@2       EQU   02
@3       EQU   03
@4       EQU   04
@5       EQU   05
@6       EQU   06
@7       EQU   07
@8       EQU   08
@9       EQU   09
@A       EQU   10
@B       EQU   11
@C       EQU   12
@D       EQU   13
@E       EQU   14
@F       EQU   15
         DS    0F
@C11     DC    C'VOL1'
@C20     DC    C'HDR1'
@C21     DC    C'ONLINE ,'
@C29     DC    C'FUNCTIONALLY  '
@C30     DC    C'DIAGNOSTICALLY'
@C32     DC    C'0C'
@C22     DC    C'ALLOCATED  '
@C23     DC    C'UNALLOCATED'
         DS    0D
@DATA    EQU   *
@SAV001  EQU   @DATA+00000000      72 BYTE(S) ON WORD
X        EQU   00000000            FULLWORD INTEGER
R0       EQU   00000000            FULLWORD POINTER REGISTER
R1       EQU   00000001            FULLWORD POINTER REGISTER
R2       EQU   00000002            FULLWORD POINTER REGISTER
R3       EQU   00000003            FULLWORD POINTER REGISTER
R4       EQU   00000004            FULLWORD POINTER REGISTER
R5       EQU   00000005            FULLWORD POINTER REGISTER
R6       EQU   00000006            FULLWORD POINTER REGISTER
R7       EQU   00000007            FULLWORD POINTER REGISTER
R8       EQU   00000008            FULLWORD POINTER REGISTER
R9       EQU   00000009            FULLWORD POINTER REGISTER
I        EQU   00000008            FULLWORD INTEGER REGISTER
R10      EQU   00000010            FULLWORD POINTER REGISTER
R11      EQU   00000011            FULLWORD POINTER REGISTER
R12      EQU   00000012            FULLWORD POINTER REGISTER
R13      EQU   00000013            FULLWORD POINTER REGISTER
R14      EQU   00000014            FULLWORD POINTER REGISTER
R15      EQU   00000015            FULLWORD POINTER REGISTER
WAITLST  EQU   @DATA+00000072      16 BYTE(S) ON WORD
         ORG   WAITLST+00000000
XMGR     EQU   *                   1 BYTE(S)
         DC    X'00'
LVL      EQU   *                   1 BYTE(S)
         DC    X'02'
MODID    EQU   *                   2 BYTE(S)
         DC    C'36'
TECBPTR  EQU   *                   FULLWORD POINTER
         DC    AL4(TECB)
CDSPTR   EQU   *                   FULLWORD POINTER
         DC    AL4(0)
FLG      EQU   *                   8 BIT(S) ON BYTE
         DC    X'80'
WAITYES  EQU   WAITLST+00000012    1 BIT(S)
TIME     EQU   *                   2 BYTE(S)
         DC    X'001E'
A00026   EQU   00000000            52 BYTE(S) ON WORD
DEVADEB  EQU   A00026+00000000     8 BYTE(S)
UCBAD    EQU   A00026+00000008     FULLWORD POINTER
DEVFLG1  EQU   A00026+00000012     1 BYTE(S)
STATUS   EQU   A00026+00000012     1 BIT(S)
PRIMARY  EQU   A00026+00000012     1 BIT(S)
DPDONE   EQU   A00026+00000012     1 BIT(S)
A00027   EQU   A00026+00000012     3 BIT(S)
FILEPROT EQU   A00026+00000012     1 BIT(S)
A00028   EQU   A00026+00000012     1 BIT(S)
DEVFLG2  EQU   A00026+00000013     1 BYTE(S)
A00029   EQU   A00026+00000013     2 BIT(S)
CEVOL    EQU   A00026+00000013     1 BIT(S)
STDLABL  EQU   A00026+00000013     1 BIT(S)
A00030   EQU   A00026+00000013     4 BIT(S)
DEVFLG3  EQU   A00026+00000014     1 BYTE(S)
A00031   EQU   A00026+00000014     3 BIT(S)
TAPEBIT  EQU   A00026+00000014     1 BIT(S)
A00032   EQU   A00026+00000014     1 BIT(S)
SYSALLOC EQU   A00026+00000014     1 BIT(S)
A00033   EQU   A00026+00000014     2 BIT(S)
DEVFLG4  EQU   A00026+00000015     1 BYTE(S)
TAPELABL EQU   A00026+00000016     16 BYTE(S)
VOL      EQU   A00026+00000016     10 BYTE(S)
HDR      EQU   A00026+00000026     4 BYTE(S)
MODESV   EQU   A00026+00000030     1 BYTE(S)
A00034   EQU   A00026+00000031     1 BYTE(S)
ADRHEX   EQU   A00026+00000032     4 BYTE(S)
A00035   EQU   A00026+00000032     2 BYTE(S)
HEXAD    EQU   A00026+00000034     2 BYTE(S)
CDSINFOR EQU   A00026+00000036     16 BYTE(S)
MODEL    EQU   A00026+00000036     1 BYTE(S)
FEATURES EQU   A00026+00000037     1 BYTE(S)
STRACK   EQU   A00026+00000037     1 BIT(S)
A00036   EQU   A00026+00000037     7 BIT(S)
CLASS    EQU   A00026+00000038     1 BYTE(S)
TYPE     EQU   A00026+00000039     1 BYTE(S)
A00037   EQU   A00026+00000040     12 BYTE(S)
TECB     EQU   @DATA+00000088      45 BYTE(S) ON WORD
         ORG   TECB+00000000
FLDCNT   EQU   *                   1 BYTE(S)
         DC    X'01'
FLDSIZE  EQU   *                   1 BYTE(S)
         DC    X'0C'
SOMETNG  EQU   *                   1 BYTE(S)
         DC    X'00'
SNSSIZE  EQU   *                   1 BYTE(S)
         DC    X'18'
FLG1     EQU   *                   1 BYTE(S)
         DC    X'00'
SNSCNTTB EQU   *                   1 BYTE(S)
         DC    X'01'
CLRTECB  EQU   TECB+00000006       39 BYTE(S)
CNTSNS   EQU   *                   1 BYTE(S)
         DC    X'00'
CNTINT   EQU   *                   1 BYTE(S)
         DC    X'00'
CCP      EQU   TECB+00000008       1 BYTE(S)
A00038   EQU   TECB+00000009       3 BYTE(S)
CSW1     EQU   TECB+00000012       8 BYTE(S)
A00039   EQU   TECB+00000012       4 BYTE(S)
STATUSX  EQU   TECB+00000016       2 BYTE(S)
EXIOK    EQU   TECB+00000016       1 BYTE(S)
A00040   EQU   TECB+00000016       6 BIT(S)
UNITCK   EQU   TECB+00000016       1 BIT(S)
UNITEXCP EQU   TECB+00000016       1 BIT(S)
BYTE2    EQU   TECB+00000017       1 BYTE(S)
A00041   EQU   TECB+00000017       1 BIT(S)
INLENGTH EQU   TECB+00000017       1 BIT(S)
A00042   EQU   TECB+00000017       6 BIT(S)
A00043   EQU   TECB+00000018       2 BYTE(S)
SENSE    EQU   TECB+00000020       24 BYTE(S)
A00044   EQU   TECB+00000020       3 BYTE(S)
SNS1     EQU   TECB+00000023       7 BYTE(S)
SNSFLD   EQU   TECB+00000023       8 BIT(S)
A00045   EQU   TECB+00000023       1 BIT(S)
SNS2     EQU   TECB+00000023       1 BIT(S)
A00046   EQU   TECB+00000024       2 BYTE(S)
A00047   EQU   TECB+00000026       8 BIT(S)
A00048   EQU   TECB+00000026       5 BIT(S)
PEIND    EQU   TECB+00000026       1 BIT(S)
A00049   EQU   TECB+00000027       2 BYTE(S)
A00050   EQU   TECB+00000029       1 BYTE(S)
A00051   EQU   TECB+00000029       4 BIT(S)
BIT4     EQU   TECB+00000029       1 BIT(S)
LABEL1   EQU   @DATA+00000133      80 BYTE(S)
TAPEVOL  EQU   LABEL1+00000000     10 BYTE(S)
VOLAB    EQU   LABEL1+00000000     4 BYTE(S)
VOLSERNO EQU   LABEL1+00000004     6 BYTE(S)
SECURE   EQU   LABEL1+00000010     1 BYTE(S)
A00052   EQU   LABEL1+00000011     69 BYTE(S)
LABEL2   EQU   @DATA+00000133      80 BYTE(S)
HDRLAB   EQU   LABEL2+00000000     4 BYTE(S)
A00053   EQU   LABEL2+00000004     43 BYTE(S)
A00054   EQU   LABEL2+00000047     7 BYTE(S)
A00055   EQU   LABEL2+00000047     1 BYTE(S)
DATE1    EQU   LABEL2+00000048     5 BYTE(S)
A00056   EQU   LABEL2+00000053     1 BYTE(S)
A00057   EQU   LABEL2+00000054     26 BYTE(S)
         ORG   @DATA+00000216
MSGPTR   EQU   *                   FULLWORD POINTER
         DC    VL4(IFDMSG03)
A00058   EQU   00000000            64 BYTE(S) ON WORD
MSG1     EQU   A00058+00000000     FULLWORD POINTER
MSG2     EQU   A00058+00000004     FULLWORD POINTER
MSG3     EQU   A00058+00000008     FULLWORD POINTER
MSG4     EQU   A00058+00000012     FULLWORD POINTER
MSG5     EQU   A00058+00000016     FULLWORD POINTER
MSG6     EQU   A00058+00000020     FULLWORD POINTER
MSG7     EQU   A00058+00000024     FULLWORD POINTER
MSG8     EQU   A00058+00000028     FULLWORD POINTER
MSG9     EQU   A00058+00000032     FULLWORD POINTER
MSGA     EQU   A00058+00000036     FULLWORD POINTER
MSGB     EQU   A00058+00000040     FULLWORD POINTER
MSGC     EQU   A00058+00000044     FULLWORD POINTER
MSGD     EQU   A00058+00000048     FULLWORD POINTER
MSGE     EQU   A00058+00000052     FULLWORD POINTER
MSGF     EQU   A00058+00000056     FULLWORD POINTER
MSGG     EQU   A00058+00000060     FULLWORD POINTER
MSG109   EQU   00000000            40 BYTE(S) ON WORD
A00059   EQU   MSG109+00000000     12 BYTE(S)
MSGDVAD  EQU   MSG109+00000012     8 BYTE(S)
A00060   EQU   MSG109+00000020     1 BYTE(S)
ONOROFF  EQU   MSG109+00000021     8 BYTE(S)
ALORNOT  EQU   MSG109+00000029     11 BYTE(S)
MSGDVAD1 EQU   00000034            8 BYTE(S)
MSGDVAD2 EQU   00000036            8 BYTE(S)
MSGDVAD3 EQU   00000019            8 BYTE(S)
MSGDVAD4 EQU   00000019            8 BYTE(S)
MSGDVAD9 EQU   00000029            8 BYTE(S)
MSGDVADA EQU   00000016            8 BYTE(S)
MSGDVA39 EQU   00000039            8 BYTE(S)
MSGSNS   EQU   00000037            12 BYTE(S)
MSGCSW   EQU   00000018            14 BYTE(S)
MSGDVADD EQU   00000038            8 BYTE(S)
MSGDVADG EQU   00000022            8 BYTE(S)
MSGINIT  EQU   00000043            14 BYTE(S)
MSGPARM  EQU   00000000            8 BYTE(S) ON WORD
LENGTH   EQU   MSGPARM+00000000    1 BYTE(S)
BUFAD    EQU   MSGPARM+00000001    3  BYTE  POINTER ON WORD+1
MSGECBAD EQU   MSGPARM+00000004    FULLWORD INTEGER
DECB     EQU   *                   FULLWORD INTEGER
         DC    FL4'0'
INBUF    EQU   @DATA+00000224      62 BYTE(S)
CSWIN    EQU   INBUF+00000000      14 BYTE(S)
A00061   EQU   INBUF+00000014      6 BYTE(S)
SNSIN    EQU   INBUF+00000020      48 BYTE(S)
         ORG   @DATA+00000292
AREA     EQU   *                   FULLWORD INTEGER
         DC    FL4'0'
AREA1    EQU   *                   6 BYTE(S)
         DC    X'000000000000'
XAREA    EQU   @DATA+00000297      5 BYTE(S)
         ORG   @DATA
         DS    00000302C
@TEMPS   DS    0F
@TEMP4   DC    F'0'
RDLAB    CCW   7,*,X'60',1       REWIND
         CCW   4,SNS1,X'60',24          SENSE                    X02906
         CCW   2,LABEL1,X'40',80    READ VOL1 RECORD
         CCW   04,*,X'30',1       FORCE CHAN END DEV END, NO DATA TRANS
URSNS    CCW   3,*,X'60',1              NO-OP FOR UR RDY CHK   Y01906
         CCW   04,*,X'30',1       FORCE CHAN END DEV END, NO DATA TRANS
RDLAB1   CCW   2,LABEL1,X'40',80      READ HDR1 RECORD
         CCW   04,*,X'30',1       FORCE CHAN END DEV END, NO DATA TRANS
CNVRT    DC    B'00000000'         CONTROL PROGRAM FLAGS
         DC    AL1(2)              MACRO LEVEL
         DC    CL2'41'             MACRO ID
        DC    A(CSW1+1)
         DC    A(INBUF)
         DC    AL2(31+32768)            COUNT AND TYPE           S21052
DSECTAA  IFDCOM
A00000   EQU   CESWT3+00000000     1 BYTE(S)
A00001   EQU   A00000+00000000     3 BIT(S)
GRBCTL   EQU   A00000+00000000     1 BIT(S)
SUSDEL   EQU   A00000+00000000     1 BIT(S)
A00002   EQU   A00000+00000000     1 BIT(S)
A00003   EQU   CHASCT+00000010     1 BYTE(S)
A00004   EQU   A00003+00000000     1 BIT(S)
FPM      EQU   A00003+00000000     1 BIT(S)
A00005   EQU   MSSSTAT+00000000    1 BYTE(S) ON WORD
FINITSW  EQU   A00005+00000000     1 BIT(S)
DINITSW  EQU   A00005+00000000     1 BIT(S)
INITSW   EQU   A00005+00000000     1 BIT(S)
A00006   EQU   A00005+00000000     5 BIT(S)
FLG1A    EQU   FLGA+00000000       8 BIT(S) ON BYTE
BYPASS   EQU   FLG1A+00000000      1 BIT(S)
FLG2     EQU   FLGB+00000000       8 BIT(S) ON BYTE
INTCALL  EQU   FLG2+00000000       1 BIT(S)
MODEREQ  EQU   FLG2+00000000       1 BIT(S)
A00007   EQU   CESWT+00000000      4 BYTE(S) ON WORD
A00008   EQU   A00007+00000000     8 BIT(S)
A00009   EQU   A00007+00000000     1 BIT(S)
PROTECT  EQU   A00007+00000000     1 BIT(S)
A00010   EQU   A00007+00000000     6 BIT(S)
A00011   EQU   A00007+00000001     8 BIT(S)
A00012   EQU   A00007+00000001     1 BIT(S)
SEEK2321 EQU   A00007+00000001     1 BIT(S)
SECONLOK EQU   A00007+00000001     1 BIT(S)
A00013   EQU   A00007+00000001     1 BIT(S)
FILMSK   EQU   A00007+00000001     1 BIT(S)
T2321    EQU   A00007+00000001     1 BIT(S)
ONLINEOK EQU   A00007+00000001     1 BIT(S)
A00014   EQU   A00007+00000001     1 BIT(S)
A00015   EQU   A00007+00000002     8 BIT(S)
NDCFO    EQU   A00007+00000002     1 BIT(S)
DPONDEV  EQU   A00007+00000002     1 BIT(S)
A00016   EQU   A00007+00000002     1 BIT(S)
CHANTEST EQU   A00007+00000002     1 BIT(S)
A00017   EQU   A00007+00000002     1 BIT(S)
A00018   EQU   A00007+00000002     1 BIT(S)
TAPEHDR  EQU   A00007+00000002     1 BIT(S)
AMERLDV  EQU   A00007+00000002     1 BIT(S)
A00019   EQU   A00007+00000003     8 BIT(S)
A00020   EQU   A00007+00000003     1 BIT(S)
BYPALDEV EQU   A00007+00000003     1 BIT(S)
BYPDEV   EQU   A00007+00000003     1 BIT(S)
A00021   EQU   A00007+00000003     1 BIT(S)
A00022   EQU   A00007+00000003     1 BIT(S)
A00023   EQU   A00007+00000003     1 BIT(S)
A00024   EQU   A00007+00000003     1 BIT(S)
A00025   EQU   A00007+00000003     1 BIT(S)
BUFFER   EQU   INBUFR+00000000     1 BYTE(S)
@DATEND  EQU   *
@9FE     EQU   DPTAPE01
@9FD     EQU   DPTAPE01
@9F7     EQU   DPTAPE03
@9EE     EQU   DPTAPE03
@9E4     EQU   DPTAPE10
@9DE     EQU   DPTAPE10
@9DF     EQU   DPMSGF
@9DA     EQU   DPTAPE10
         END    ,(C'PL/S',1400,78118)
