         TITLE 'IFDOLT53 RESTORE TAPE LABELS'
         TITLE 'IFDOLT53 RESTORE TAPE LABELS,INDICATE MSS STATUS'
         LCLA  &T,&SPN                                            0002
.@001    ANOP                                                     0002
IFDOLT53 CSECT ,                                                  0002
         BC    15,24(0,@F)
         DC    C'IFDOLT53 26 APR 78'                             0002
         STM   @E,@C,12(@D)                                       0002
         BALR  @B,0                                               0002
@PSTART  DS    0H                                                 0002
         USING @PSTART+00000,@B                                   0002
         ST    @D,@SAV001+4                                       0002
         LA    @F,@SAV001                                         0002
         ST    @F,8(0,@D)                                         0002
         LR    @D,@F                                              0002
*  GEN(USING CHASCT,2);                  /* COMMON AREA BASE REGISTER *
         USING CHASCT,2
         DS    0H
* /********************************************************************
* /*                                                                  *
* /*                 CCW STRING FOR WRITING TAPE LABEL                *
* /*                                                                  *
* /********************************************************************
*         GENERATE DATA;
*         GEN DATA;
* GENERATE DATA;
*  /*******************************************************************
*  /*                                                                 *
*  /*                     DECLARED  REGISTERS                         *
*  /*                                                                 *
*  /*******************************************************************
*  DCL R0  REG(0)  PTR;
*  DCL R1  REG(1)  PTR;
*  DCL R2  REG(2)  PTR;
*  DCL R3  REG(3)  PTR;
*  DCL R4  REG(4)  PTR;
*  DCL R5  REG(5)  PTR;
*  DCL R6  REG(6)  PTR;
*  DCL R7  REG(7)  PTR;
*  DCL R8  REG(8)  PTR;
*  DCL R9  REG(9)  PTR;
*  DCL R10 REG(10) PTR;
*  DCL R11 REG(11) PTR;
*  DCL R12 REG(12) PTR;
*  DCL R13 REG(13) PTR;
*  DCL R14 REG(14) PTR;
*  DCL R15 REG(15) PTR;
*         RESTRICT(2,4,5,7,8);                              /*@ZA15468*
*  DCL ROPT GENERATED;                   /* SVC AREA            X02906*
*  DCL WKSVC GENERATED;                  /* SVC WORK AREA       X02906*
*  DCL MCT GENERATED;                    /* MODULE CONTROL TABLEX02906*
*  DCL VID CHAR(2) BASED(ADDR(WKSVC)+2); /* MODID IN SVC PLIST  X02906*
*  DCL MID1 CHAR(2) BASED(ADDR(MCT)+10); /* MY MODID            X02906*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*           EXIO PARAMETER LIST                                   *
*  /*                                                                 *
*  /*******************************************************************
*
*                                       /* IO EFFECTOR CNTL BLK Y02906*
*                                       /* IN COMMON AREA       Y02906*
*  DCL EFCTRCB CHAR(20) GEND;           /* IO EFFECTOR CONTROL BLOCK  *
*  DCL CCWPTR PTR(31) GEND;             /* CCW LIST POINTER     Y02906*
*  DCL DVTPTR PTR(31) GEND;             /* DEVICE TABEL POINTER Y02906*
*  DCL FLGA   BIT(8)  GEND;             /* FLAG BYTE 1          Y02906*
*
*  DCL FLGB   BIT(8)  GEND;             /* FLAG BYTE 2          Y02906*
*
* DCL 1 FLG1A BIT(8) BASED(ADDR(FLGA)),
*       3 BYPASS BIT(1);                 /* BYPASS PREFIX       Y02906*
*
*  DCL 1 FLG2 BIT(8) BASED(ADDR(FLGB)),                       /*Y02906*
*        3 INTCALL BIT(1),              /* INTERNAL CALL FOR IO Y02906*
*        3 MODEREQ BIT(1);              /* IF ON MODE SET REQ   Y02906*
*  DCL FILEMSK CHAR(1) GEND;            /* FILE MSK FOR IOEFFEC Y02906*
* DCL SNSCNT CHAR(1) GEND;
* DCL TECBPTRX PTR(31) GEND;
*  DCL IORTNADR GEND;                   /* ADDR OF IO EFFECTOR  Y02906*
*         DCL 1 WAITLST CHAR(16) BDY(WORD), /* WAITIO LIST      Y02906*
*              3 XMGR CHAR(1) INIT('00'X), /* TRANS MGR STUFF   Y02906*
*              3 LVL CHAR(1) INIT('02'X),/* WAITIO LVL          Y02906*
*              3 MODID CHAR(2) INIT('36'), /* IFDOLT36 ID       Y02906*
*              3 TECBPTR PTR(31) INIT(ADDR(TECB)),/* TECB ADDR  Y02906*
*              3 CDSPTR PTR(31) INIT(0),  /*CDS = 0             Y02906*
*              3 FLG BIT(8) INIT('80'X), /* SET WAIT = YES      Y02906*
*               5 WAITYES BIT(1),        /* FLAG TO 1           Y02906*
*              3 TIME CHAR(2) INIT('001E'X); /* TIME IN SECONDS Y02906*
*
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                COMMUNICATION SWITCH STRUCTURE                   *
*  /*                                                                 *
*  /*******************************************************************
*
*  DCL CESWT CHAR(5) GENERATED;     /* COMMUNICATION SWITCHES         *
*  DCL 1 * BASED(ADDR(CESWT)),      /*                                *
*        3 * BIT(8),                /* CESWT                          *
*          5 * BIT(1),              /* NA                             *
*          5 PROTECT BIT(1),        /* DP FOR PRIMARY OR SEC DEVICE   *
*          5 * BIT(6),              /* NA                             *
*        3 * BIT(8),                /* CESWT1                         *
*          5 * BIT(1),              /* NA                             *
*          5 SEEK2321 BIT(1),       /* SEEK ONLY COMMANDS ON 2321     *
*          5 SECONLOK BIT(1),       /* SEC DEV ONLINE OK              *
*          5 * BIT(1),              /* NA                             *
*          5 FILMSK BIT(1),         /* ALLOWS FILE MASK CHANGES       *
*          5 T2321 BIT(1),          /* T2321 IS DEV BEING TESTED      *
*          5 ONLINEOK BIT(1),       /* DEV IS ONLINE PROCEED          *
*          5 * BIT(1),              /* NA                             *
*        3 * BIT(8),                /* CESWT2                         *
*          5 NDCFO BIT(1),          /* PREV OCCUR OF DYN COMM INTERVAL*
*          5 DPONDEV BIT(1),        /* DP HAS BEEN DONE ON THIS DEV   *
*          5 * BIT(1),              /* NA                             *
*          5 CHANTEST BIT(1),       /* DATA PROT TO BE DONE ON CHAN   *
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1),              /* NA                             *
*          5 TAPEHDR BIT(1),        /* TAPE HEADER IS TO BE WRITTEN   *
*          5 DEVDPOK BIT(1),        /* DP ON DEVICE WAS SUCCESSFUL    *
*        3 * BIT(8),                /* CESWT3                         *
*          5 * BIT(1),              /* NA                             *
*          5 BYPALDEV BIT(1),       /* BYPASS ALL TESTS AND DEVICES   *
*          5 BYPDEV BIT(1),         /* BYPASS TESTS ON THIS DEVICE    *
*          5 * BIT(1),              /* NA                             *
*         5 SUSDEL BIT(1),               /* SUSPENDED DELETION   M4506*
*          5 * BIT(1),              /* NA                             *
*          5 * BIT(1),              /* NA                             *
*          5 STDLAB BIT(1);         /* STANDARD LABEL                 *
*
*         DCL   CESWT8 CHAR(1) GENERATED; /* ADDRESS OF SWITCH  X02906*
*         DCL   1 * BASED(ADDR(CESWT8)), /* SET ADDR FOR LETGO CHECK*/
*                 3 * BIT(2),            /* NOT USED BITS            */
*                 3  LETGO BIT(1);       /* LETGO REQUEST       X02906*
*
* /********************************************************************
* /*                                                                  *
* /*                      DEVICE TABLE STRUCTURE                      *
* /*                                                                  *
* /********************************************************************
*
*         DCL DEVTBPTR PTR GENERATED;      /* PTR TO DEVTAB      21050*
*         DCL TABLNGTH FIXED(15)         /* LENGTH OF DEVTAB    S21050*
*           GENERATED;                   /* ENTRY               S21050*
*         DCL  1 * BASED(R7),          /*                       S21050*
*         3 DEVADEB CHAR(8),             /* DEV ADDR IN EBCDIC        *
*                3 UCBAD POINTER(31),  /* UCB ADDR (2BYTES)     S21050*
*                3 DEVFLG1 CHAR(1),    /* FLAG BYTE #1          S21050*
*                 5 STATUS BIT(1),     /* ON LINE VS. OFF-LINE  S21050*
*                 5 PRIMARY BIT(1),    /* PRIMARY BIT           S21050*
*                 5 DPDONE  BIT(1),    /* D.P. COMPLETE         S21050*
*                 5 *       BIT(3),    /* FILL                  S21050*
*                 5 FILEPROT BIT(1),   /* F.P. MODE OPERATION   S21050*
*                 5 *       BIT(1),    /* FILL                  S21050*
*                3 DEVFLG2 CHAR(1),    /* FLAG BYTE # 2         S21050*
*                 5 * BIT(3),          /* FILL                  S21050*
*                 5   STDLABL BIT(1),  /* STANDARD TAPE LABEL   S21050*
*                 5 * BIT(4),          /* FILL                  S21050*
*                3 DEVFLG3 CHAR(1),    /* FLAG BYTE # 3         S21050*
*                 5 * BIT(3),            /* N/A                 X02906*
*                 5 TAPEBIT BIT (1),     /* RESET UCB NOTRDY FLGX02906*
*                 5 * BIT(4),            /* N/A                 X02906*
*                3 DEVFLG4 CHAR(1),    /* FLAG BYTE # 3         S21050*
*                3 TAPELABL CHAR(16),  /* TAPE LABEL SAVE AREA  S21050*
*                 5 VOL CHAR(10),      /* VOL NAME              S21050*
*                 5 HDR CHAR (4),      /* HDR NAME              S21050*
*                 5 MODESV CHAR(1),    /* MODE SAVE AREA        S21050*
*                 5 * CHAR(1),         /* FILL                  S21050*
*                3 ADRHEX CHAR (4),    /* 4 BYTE HEX ADDRESS    S21050*
*                 5 * CHAR(2),         /* FILL                  S21050*
*                 5 HEXAD CHAR(2);     /* 2 BYTE HEX ADDRESS    S21050*
*
*  /**********************************************************@ZA15468*
*  /*                                                         @ZA15468*
*  /*                     UCB DEVICE CLASS-TYPE STRUCTURE     @ZA15468*
*  /*                                                         @ZA15468*
*  /**********************************************************@ZA15468*
*
*  DCL 1 * BASED(R8),                    /*                   @ZA15468*
*        3 UCBOB CHAR(24),               /* UCB STRUCTURE     @ZA15468*
*          5 *        CHAR(16),          /* N/A               @ZA15468*
*          5 MODEL    CHAR(1),           /* MODEL OPTIONS     @ZA15468*
*          5 FEATURES CHAR(1),           /* DEVICE FEATURES   @ZA15468*
*          5 CLASS    CHAR(1),           /* DEVICE CLASS      @ZA15468*
*          5 TYPE     CHAR(1);           /* DEVICE TYPE       @ZA15468*
*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                  TEST EVENT CONTROL BLOCK FIELD                 *
*  /*                                                                 *
*  /*******************************************************************
*
*         DCL 1 TECB,                     /* EVENT BLOCK FOR IO Y02906*
*               2 FLDCNT CHAR(1) INIT('01'X),  /* NUMBER FDLS   Y02906*
*               2 FLDSIZE CHAR(1) INIT('0C'X), /* SIZE EACH FLD Y02906*
*               2 SOMETNG CHAR(1) INIT('00'X), /* N/A           Y02906*
*               2 SNSSIZE CHAR(1) INIT('18'X), /* SENSE EXPTD   Y02906*
*               2 FLG1 CHAR(1) INIT('00'X),    /* FLAGS         Y02906*
*               2 SNSCNTTB CHAR(1) INIT('01'X), /* XPECTED COUNTY02906*
*               2 CLRTECB  CHAR(39),     /* LABEL TO CLEAR TECB YM3336*
*                 3 CNTSNS CHAR(1) INIT('00'X), /* NUMB OCCURED Y02906*
*                 3 CNTINT CHAR(1) INIT('00'X), /*NUMB INTERRUPTY02906*
*                 3 CCP CHAR(1),        /* SIO COND CODE        Y02906*
*                 3 * CHAR(3),          /* N/A                  YM3336*
*                 3 CSW1 CHAR(8),       /* CSW NO. ONE          Y02906*
*                   5 * CHAR(4),        /* N/A                  Y02906*
*                   5 STATUSX CHAR(2),  /* TWO STATUS BYTES     Y02906*
*                     7 EXIOK CHAR(1),  /* STATUS BYTE 1        Y02906*
*                       9 * BIT(6),     /* N/A                  Y02906*
*                       9 UNITCK BIT(1), /* UNIT CHECK          Y02906*
*                       9 UNITEXCP BIT(1), /* UNIT EXCEPTION BITY02906*
*                     7 BYTE2 CHAR(1),  /* STATUS BYTE 2        Y02906*
*                       9 * BIT(1),     /* N/A                  Y02906*
*                       9 INLENGTH  BIT(1), /* INCORR LNG IND   Y02906*
*                       9 * BIT(6),     /* N/A                  Y02906*
*                   5 * CHAR(2),        /* N/A                  Y02906*
*                 3 SENSE CHAR(24),     /* SENSE COUNT          Y02906*
*                   5 * CHAR(3),        /* N/A                  Y02906*
*                   5 SNS1 CHAR(7),     /* SENSE BYTES          Y02906*
*                     7 SNSFLD BIT(8),  /* BYTE0  SENSE         Y02906*
*                       9 * BIT(1),     /* N/A                  Y02906*
*                       9 SNS2 BIT(1),  /* BIT 1 SNS BYTE 0     Y02906*
*                     7 * CHAR(2),      /* SNS BYTES 1 & 2      Y02906*
*                     7 * BIT(8),       /* SNS BYTE 3           Y02906*
*                       9 * BIT(5),     /* FILL                 Y02906*
*                       9 PEIND BIT(1), /* BIT 5 BYTE3 OF SNS   Y02906*
*                     7 * CHAR(2),      /* SENCE BYTES 4 AND 5  Y02906*
*                     7 * CHAR(1),      /* SENCE BYTE 6         Y02906*
*                       9 * BIT(4),     /* NOT REFERENCED       Y02906*
*                       9 BIT4 BIT(1);  /* BIT FOUR FOR BIRTCH  Y03128*
*  /**********************************************************@ZA15468*
*  /*                                                         @ZA15468*
*  /*                     MSS STATUS BYTE STRUCTURE           @ZA15468*
*  /*                                                         @ZA15468*
*  /**********************************************************@ZA15468*
*
*  DCL MSSSTAT CHAR(1) GENERATED;        /* MSS STATUS BYTE   @ZA15468*
*  DCL 1 * CHAR(1) BASED(ADDR(MSSSTAT)), /*                   @ZA15468*
*        3 FINITSW BIT(1),               /* FUNCT INIT BIT    @ZA15468*
*        3 DINITSW BIT(1),               /* DIAGN INIT BIT    @ZA15468*
*        3 INITSW  BIT(1),               /* INTERFACE STATUS  @ZA15468*
*        3 *       BIT(5);               /* N/A               @ZA15468*
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                    MESSAGE STRUCTURES                           *
*  /*                                                                 *
*  /*******************************************************************
*
*         DCL IFDMSG53 EXT ENTRY;        /*MESSAGE MODULE             *
*  DCL 1 * BASED(R4),               /* MESSAGE ADDRESS                *
*        3 MSG1 PTR,                /* POINTER TO MESSAGE             *
*        3 MSG2 PTR,                     /* PTR TO IFD137I    @ZA15468*
*        3 MSG3 PTR,                     /* PTR TO IFD139D    @ZA15468*
*        3 MSG4 PTR,                     /* PTR TO IFD476I    @ZA15468*
*        3 MSG5 PTR;                     /* PTR TO IFD477I    @ZA15468*
*  DCL MSGSNS CHAR(12) BASED(R1+37);     /* SENSE DATA AREA     S21050*
*  DCL MSGCSW CHAR(14) BASED(R1+18);     /* CSW DATA AREA       S21050*
*  DCL MSGDEVAD CHAR(8) BASED(R1+39);    /*DEV ADDR AREA IN MSG S21050*
*         DCL MECB FIXED;                /* ECB FOR PWTOR             *
*         DCL INBUF1 CHAR(1);            /*BUFFER FOR REPLY           *
*         DCL 1 * BASED(R1),             /* PARMLIST FOR WTOR         *
*           3 LENGTH CHAR(1),
*           3 REPLYAD PTR(24),
*           3 ECBAD PTR;
*
*  DCL MSG4DVAD CHAR(8) BASED(R1+22);    /* DEVICE ADDRESS IN @ZA15468*
*                                        /* MESSAGE IFD476I   @ZA15468*
*
*  DCL 1 OUTBUFRI CHAR(13),         /* OUTPUT BUFFER                  *
*        3 SNSOUT CHAR(6),          /* SENSE DATA TO BE CONVERTED     *
*        3 CSWOUT CHAR(7);          /* CSW DATA TO BE CONVERTED       *
*  DCL 1 INBUF CHAR(26),            /* INPUT BUFFER                   *
*        3 SNSIN CHAR(12),          /* CONVERTED SENSE DATA           *
*        3 CSWIN CHAR(14);          /* CONVERTED CSW DATA             *
*  DCL OLTTAB PTR GENERATED;             /* LINK TABLE           M4506*
*  DCL OLTTAB2 PTR BASED(ADDR(OLTTAB)+4); /* WAITIO INDICATOR    M4506*
*  DCL TAB28 PTR(31) GENERATED;     /* NEW MACRO ENTRY POINT          *
*  DCL CNVRT CHAR(14) GENERATED;    /* CONVERT PARAMETER LIST         *
*             DCL UNICTR CHAR(1) GENERATED;
*         DCL DEVTAB CHAR(576) GENERATED;    /*DEVICE TABLE           *
*         DCL TPSAVE CHAR(4) GENERATED;  /* ID OF OLT BEING RUNOX01386*
*         DCL WRTBOTH LABEL GENERATED;      /*CCW LABEL               *
*         DCL 1 VOL1BUF CHAR(80),        /*OUTPUT BUFFER FOR VOL1 REC *
*           3 VOLNAME CHAR(10),
*           3 *(70) CHAR(1) INIT((70)'0');
*         DCL 1 HDR1BUF CHAR(80),        /*OUTPUT BUFFER FOR HDR1 REC *
*           3 HDRNAME CHAR(4) INIT('HDR1'),
*           3 *(76) CHAR(1) INIT((76)'0');
*
*  /*******************************************************************
*  /*                                                                 *
*  /*     PARAMETER LIST FOR SVC59                                    *
*  /*                                                                 *
*  /*******************************************************************
*
*  DCL 1 * BASED(ADDR(ROPT)),            /*                     X02906*
*         3 UCBADDR CHAR(4),             /* UCB ADDR OF DEV     X02906*
*         3 FLAGS CHAR(4),               /*                     X02906*
*           5 SVCFLG CHAR(1),            /* FIRST FLAG BYTE     X02906*
*           5 * CHAR(3);                 /* N/A                 X02906*
*  DCL HCODE CHAR(1) BASED(84);          /* FUNC 21 SVC CODE #  X02906*
*
*          R4=ADDR(IFDMSG53);            /* GET ADD OF MSG53  @ZA15468*
         L     @3,@V1              ADDRESS OF IFDMSG53            0075
         LR    @4,@3                                              0075
*         R7  =  DEVTBPTR;         /* SET R 7 TO HEAD OF DEVTAB       *
         L     @7,DEVTBPTR                                        0076
*             DO R5=UNICTR TO 1 BY -1;
         SR    @5,@5                                              0077
         IC    @5,UNICTR                                          0077
         LTR   @5,@5                                              0077
         BC    12,@DO9FE                                          0077
*          R8=UCBAD;                     /* GET ADD OF UCB    @ZA15468*
@DO9FF   L     @8,8(0,@7)                                         0078
*          IF CLASS='08'X &              /* IF THE DEVICE IS  @ZA15468*
*             TYPE='42'X THEN            /* AN MSS, CHECK TO  @ZA15468*
         CLI   18(@8),X'08'                                       0079
         BC    07,@9FB                                            0079
         CLI   19(@8),X'42'                                       0079
         BC    07,@9FA                                            0079
*               DO;                      /* SEE HOW IT WAS    @ZA15468*
*                 IF INITSW='0'B ×       /* INITIALIZED. IF   @ZA15468*
*                    FINITSW='1'B THEN   /* FUNCTIONALLY OR   @ZA15468*
         TM    A00044,B'00100000'                                 0081
         BC    08,@9F9                                            0081
         TM    A00044,B'10000000'                                 0081
         BC    12,@9F8                                            0081
*                   GO TO INCRPTR;       /* NOT, GO           @ZA15468*
         BC    03,INCRPTR                                         0082
*                                        /* AHEAD NORMALLY.   @ZA15468*
*                 R1=MSG4;               /* ELSE,DIAGNOSTICALLY       *
@9F8     L     @1,12(0,@4)                                        0083
*                 MSG4DVAD=DEVADEB;      /* TELL THE CE.      @ZA15468*
         MVC   22(8,@1),0(@7)                                     0084
*                 GEN(PWTO REG=(1));     /*                   @ZA15468*
         PWTO REG=(1)
         DS    0H
*                 R1=MSG5;               /* TELL HOW TO CLEAR @ZA15468*
         L     @1,16(0,@4)                                        0086
*                 GEN(PWTO REG=(1));     /* IT.               @ZA15468*
         PWTO REG=(1)
         DS    0H
*                 GO TO INCRPTR;         /*                   @ZA15468*
         BC    15,INCRPTR                                         0088
*               END;                     /*                   @ZA15468*
*         IF TPSAVE='SOSP' THEN          /* IS THIS SOSP       OX01386*
@9FA     EQU   *                                                  0090
@9FB     CLC   TPSAVE(4),@C5                                      0090
*           GO TO RTRNWT;                /* YES, DONT RESTORE  OX01386*
         BC    08,RTRNWT                                          0091
*                                        /* TAPE LABEL.        OX01386*
*         IF STDLABL='1'B THEN
         TM    13(@7),B'00010000'                                 0092
*           GOTO WRLAB;                  /*GO WRITE LABEL             *
         BC    01,WRLAB                                           0093
*  RTRNWT:
*
*         IF TAPEBIT^='1'B THEN          /* SET UCB NOTRDY FLG? X02906*
RTRNWT   TM    14(@7),B'00010000'                                 0094
*           GOTO INCRPTR;                /* NO                  X02906*
         BC    12,INCRPTR                                         0095
*  ROPT= UCBAD;                          /*UCB ADDR             X02906*
         MVC   ROPT(4),8(@7)                                      0096
*  SVCFLG= '40'X;                        /* RESET NOTRDY FLG    X02906*
         MVI   A00050+4,X'40'                                     0097
*  VID= MID1;                            /* MY ID IN SVC PLIST  X02906*
         MVC   VID(2),MID1                                        0098
*  R0= ADDR(ROPT);                       /* SVC PLIST ADDRESS   X02906*
         LA    @0,ROPT                                            0099
*  R1= ADDR(HCODE);                      /* FUNC 21 SVC CODE #  X02906*
         LA    @1,HCODE                                           0100
*  GEN(SVC 59);                          /* ISSUE SVC 59        X02906*
         SVC 59
         DS    0H
*
*  INCRPTR:                              /*                     X02906*
*         R7=R7 + TABLNGTH;              /* INCREMENT DEVTAB PTR 21050*
INCRPTR  AH    @7,TABLNGTH                                        0102
*                                        /* TO NEXT ENTRY        21050*
*         END;
*         RETURN;
         BCT   @5,@DO9FF                                          0103
         BC    15,@EL01                                           0104
*
*  WRLAB:
*
*  /*******************************************************************
*  /*                                                                 *
*  /*                          SET UP FOR EXIO                        *
*  /*                                                                 *
*  /*******************************************************************
*         EFCTRCB = EFCTRCB&&EFCTRCB; /* CLEAR EFFECTOR CONTROL BLOCK *
WRLAB    XC    EFCTRCB(20),EFCTRCB                                0105
*         VOLNAME=VOL;             /*PUT VOL SER # IN OUTPUT BUFFER   *
         MVC   VOL1BUF(10),16(@7)                                 0106
*         FILEMSK = MODESV;          /* SET FILE MODE FOR DRIVE YM5401*
         MVC   FILEMSK(1),30(@7)                                  0107
*         CCWPTR = ADDR(WRTBOTH);       /* SET POINTER TO CCWS  Y02906*
         LA    @F,WRTBOTH                                         0108
         ST    @F,CCWPTR                                          0108
*         DVTPTR = R7;                  /* SET POINTER TO DEVTABY02906*
         ST    @7,DVTPTR                                          0109
*         FLGA = '00'X;                 /* SET FLG TO ZERO      Y02906*
         MVI   FLGA,X'00'                                         0110
*         INTCALL = '1'B;               /* SET INTERNAL CALL    Y02906*
         OI    FLG2,B'10000000'                                   0111
*         CLRTECB = CLRTECB &&CLRTECB;  /* CLEAR TECB FOR IO    Y02906*
         XC    TECB+6(39),TECB+6                                  0112
*         OUTBUFRI = OUTBUFRI &&OUTBUFRI;/* SET FEILD TO ZEROS  Y02906*
         XC    OUTBUFRI(13),OUTBUFRI                              0113
*         BYPASS = '1'B;                 /* SET BYPASS PREFIX SWY02906*
         OI    FLG1A,B'10000000'                                  0114
*         SNSCNT = '18'X;                /* SET SENSE COUNT     Y02906*
         MVI   SNSCNT,X'18'                                       0115
*         TECBPTRX = ADDR(TECB);         /* SET ADDR TECB       Y02906*
         LA    @F,TECB                                            0116
         ST    @F,TECBPTRX                                        0116
*         CDSPTR = ADDR(ADRHEX);        /* SET ADDR OF CDS DEV  Y02906*
         LA    @F,32(0,@7)                                        0117
         ST    @F,WAITLST+8                                       0117
*         R15 = IORTNADR;               /* GET PTR OF IO EFFECTRY02906*
         L     @F,IORTNADR                                        0118
*         GEN(BALR  14,15);             /* GO TO IO EFFECTOR    Y02906*
         BALR  14,15
         DS    0H
*         GEN(LTR   R15,R15);           /* IF EXIO FAILED       Y02906*
         LTR   R15,R15
         DS    0H
*         GEN(BNZ   RSTORE1);           /* GO PUT OUT MSG       Y02906*
         BNZ   RSTORE1
         DS    0H
*         R1 = ADDR(WAITLST);           /* GET POINTER FOR WAIT Y02906*
         LA    @1,WAITLST                                         0122
*         R14 = ADDR(STATS);            /* GET WAIT RETURNADDR  Y02906*
         LA    @E,STATS                                           0123
*         R15 = TAB28;                   /* GET TRANS MGR ENTRY Y02906*
         L     @F,TAB28                                           0124
*         GO TO R15;                    /* GO TO THE WAIT MOD   Y02906*
         BCR   15,@F                                              0125
*                                       /* GO TO WAITIO         Y02906*
*       STATS:                          /* WAIT RETURN POINT    Y02906*
*         GEN(LTR   R15,R15);           /* WAS HE SUCCESSFUL    Y02906*
STATS    LTR   R15,R15
         DS    0H
*         GEN(BNZ   RSTORE1);           /* IF NOT GO PUT MSG    Y02906*
         BNZ   RSTORE1
         DS    0H
*    FILMSK='1'B;
         OI    A00000+1,B'00001000'                               0128
*         PROTECT='0'B;                  /* CLEAR BIT           S21050*
         NI    A00000,B'10111111'                                 0129
*  IF EXIOK^='0C'X THEN                  /* CHECK EXIO RUN       M4506*
         CLI   TECB+16,X'0C'                                      0130
*    GOTO WRTAPE;                        /* UNSUCCESSFUL         M4506*
*         GOTO RTRNWT;                   /*CHECK NEXT DEVICE          *
         BC    08,RTRNWT                                          0132
*  WRTAPE:
*  R1=MSG1;                         /* POINTER TO MESSAGE             *
WRTAPE   L     @1,0(0,@4)                                         0133
*         MSGDEVAD=DEVADEB;              /*PUT UNIT ADDR IN MESSAGE   *
         MVC   39(8,@1),0(@7)                                     0134
*         GEN(PWTO REG=(1));             /*PRINT MESSAGE TO OPERATOR  *
         PWTO REG=(1)
         DS    0H
*  /*******************************************************************
*  /*                                                                 *
*  /*                     CONVERT SENSE/CSW DATA                      *
*  /*                                                                 *
*  /*******************************************************************
*  SNSOUT=SNS1;                     /* SENSE DATA TO BE CONVERTED     *
         MVC   OUTBUFRI(6),TECB+23                                0136
*  CSWOUT=CSW1;                     /* CSW DATA TO BE CONVERTED       *
         MVC   OUTBUFRI+6(7),TECB+12                              0137
*  R1=ADDR(CNVRT);                  /* GET ADDR OF CONVERT PARMLIST   *
         LA    @1,CNVRT                                           0138
*  R15=TAB28;                       /* GET ENTRY POINT ADDRESS        *
         L     @F,TAB28                                           0139
*  GEN(BALR R14,R15);               /* EXECUTE CONVERT MODULE         *
         BALR R14,R15
         DS    0H
*  /*******************************************************************
*  /*                                                                 *
*  /*                     PRINT MESSAGE IFD137I                       *
*  /*                                                                 *
*  /*******************************************************************
*  R1=MSG2;                         /* POINTER TO MESSAGE             *
         L     @1,4(0,@4)                                         0141
*  MSGSNS=SNSIN;                    /* PUT SENSE DATA IN MSG3         *
         MVC   37(12,@1),INBUF                                    0142
*  MSGCSW=CSWIN;                    /* PUT CSW DATA IN MSG3           *
         MVC   18(14,@1),INBUF+12                                 0143
*  GEN    (PWTO REG=(1));           /* PRINT MESSAGE                  *
         PWTO REG=(1)
         DS    0H
*         /************************************************************
*         /*                                                          *
*         /*        PRINT MESSAGE IFD139D                             *
*         /*                                                          *
*         /************************************************************
*  RSTORE1:
*         R4=ADDR(IFDMSG53);             /*ADDR OF MESSAGE MODULE     *
RSTORE1  L     @3,@V1              ADDRESS OF IFDMSG53            0145
         LR    @4,@3                                              0145
*         MECB=0;                        /* CLEAR ECB                 *
         SR    @F,@F                                              0146
         ST    @F,MECB                                            0146
*         R1=MSG3;                       /*POINTER TO MESSAGE         *
         L     @1,8(0,@4)                                         0147
*         LENGTH='01'X;                  /*LENGTH OF RESPONSE         *
         MVI   0(@1),X'01'                                        0148
*         INBUF1=' ';                    /*CLEAR INBUF1               *
         MVI   INBUF1,C' '                                        0149
*         REPLYAD=ADDR(INBUF1);
         LA    @F,INBUF1                                          0150
         ST    @F,@TEMP4                                          0150
         MVC   1(3,@1),@TEMP4+1                                   0150
*         ECBAD=ADDR(MECB);              /*ADDRESS OF ECB             *
         LA    @F,MECB                                            0151
         ST    @F,4(0,@1)                                         0151
*         GEN(PWTOR REG=(1));
         PWTOR REG=(1)
         DS    0H
*         IF INBUF1 = 'R' THEN
         CLI   INBUF1,C'R'                                        0153
*           GOTO WRLAB;                  /*RETRY                      *
         BC    08,WRLAB                                           0154
*         IF INBUF1^='P' THEN
         CLI   INBUF1,C'P'                                        0155
*           GOTO RSTORE1;                /* REPEAT MESSAGE            *
         BC    07,RSTORE1                                         0156
*         PROTECT='0'B;                  /* CLEAR BIT           A50386*
         NI    A00000,B'10111111'                                 0157
*         GOTO RTRNWT;                   /*CHECK NEXT DEVICE          *
         BC    15,RTRNWT                                          0158
*         END;
@EL01    L     @D,4(0,@D)                                         0159
         LM    @E,@C,12(@D)                                       0159
         BCR   15,@E                                              0159
@DATA1   EQU   *
@0       EQU   00                  EQUATES FOR REGISTERS 0-15
@1       EQU   01
@2       EQU   02
@3       EQU   03
@4       EQU   04
@5       EQU   05
@6       EQU   06
@7       EQU   07
@8       EQU   08
@9       EQU   09
@A       EQU   10
@B       EQU   11
@C       EQU   12
@D       EQU   13
@E       EQU   14
@F       EQU   15
@V1      DC    V(IFDMSG53)
         DS    0F
@C5      DC    C'SOSP'
         DS    0D
@DATA    EQU   *
@SAV001  EQU   @DATA+00000000      72 BYTE(S) ON WORD
Y        EQU   00000000            FULLWORD INTEGER
R0       EQU   00000000            FULLWORD POINTER REGISTER
R1       EQU   00000001            FULLWORD POINTER REGISTER
R2       EQU   00000002            FULLWORD POINTER REGISTER
R3       EQU   00000003            FULLWORD POINTER REGISTER
R4       EQU   00000004            FULLWORD POINTER REGISTER
R5       EQU   00000005            FULLWORD POINTER REGISTER
R6       EQU   00000006            FULLWORD POINTER REGISTER
R7       EQU   00000007            FULLWORD POINTER REGISTER
R8       EQU   00000008            FULLWORD POINTER REGISTER
R9       EQU   00000009            FULLWORD POINTER REGISTER
R10      EQU   00000010            FULLWORD POINTER REGISTER
R11      EQU   00000011            FULLWORD POINTER REGISTER
R12      EQU   00000012            FULLWORD POINTER REGISTER
R13      EQU   00000013            FULLWORD POINTER REGISTER
R14      EQU   00000014            FULLWORD POINTER REGISTER
R15      EQU   00000015            FULLWORD POINTER REGISTER
WAITLST  EQU   @DATA+00000072      16 BYTE(S) ON WORD
         ORG   WAITLST+00000000
XMGR     EQU   *                   1 BYTE(S)
         DC    X'00'
LVL      EQU   *                   1 BYTE(S)
         DC    X'02'
MODID    EQU   *                   2 BYTE(S)
         DC    C'36'
TECBPTR  EQU   *                   FULLWORD POINTER
         DC    AL4(TECB)
CDSPTR   EQU   *                   FULLWORD POINTER
         DC    AL4(0)
FLG      EQU   *                   8 BIT(S) ON BYTE
         DC    X'80'
WAITYES  EQU   WAITLST+00000012    1 BIT(S)
TIME     EQU   *                   2 BYTE(S)
         DC    X'001E'
A00019   EQU   00000000            36 BYTE(S) ON WORD
DEVADEB  EQU   A00019+00000000     8 BYTE(S)
UCBAD    EQU   A00019+00000008     FULLWORD POINTER
DEVFLG1  EQU   A00019+00000012     1 BYTE(S)
STATUS   EQU   A00019+00000012     1 BIT(S)
PRIMARY  EQU   A00019+00000012     1 BIT(S)
DPDONE   EQU   A00019+00000012     1 BIT(S)
A00020   EQU   A00019+00000012     3 BIT(S)
FILEPROT EQU   A00019+00000012     1 BIT(S)
A00021   EQU   A00019+00000012     1 BIT(S)
DEVFLG2  EQU   A00019+00000013     1 BYTE(S)
A00022   EQU   A00019+00000013     3 BIT(S)
STDLABL  EQU   A00019+00000013     1 BIT(S)
A00023   EQU   A00019+00000013     4 BIT(S)
DEVFLG3  EQU   A00019+00000014     1 BYTE(S)
A00024   EQU   A00019+00000014     3 BIT(S)
TAPEBIT  EQU   A00019+00000014     1 BIT(S)
A00025   EQU   A00019+00000014     4 BIT(S)
DEVFLG4  EQU   A00019+00000015     1 BYTE(S)
TAPELABL EQU   A00019+00000016     16 BYTE(S)
VOL      EQU   A00019+00000016     10 BYTE(S)
HDR      EQU   A00019+00000026     4 BYTE(S)
MODESV   EQU   A00019+00000030     1 BYTE(S)
A00026   EQU   A00019+00000031     1 BYTE(S)
ADRHEX   EQU   A00019+00000032     4 BYTE(S)
A00027   EQU   A00019+00000032     2 BYTE(S)
HEXAD    EQU   A00019+00000034     2 BYTE(S)
A00028   EQU   00000000            24 BYTE(S) ON WORD
UCBOB    EQU   A00028+00000000     24 BYTE(S)
A00029   EQU   A00028+00000000     16 BYTE(S)
MODEL    EQU   A00028+00000016     1 BYTE(S)
FEATURES EQU   A00028+00000017     1 BYTE(S)
CLASS    EQU   A00028+00000018     1 BYTE(S)
TYPE     EQU   A00028+00000019     1 BYTE(S)
TECB     EQU   @DATA+00000088      45 BYTE(S) ON WORD
         ORG   TECB+00000000
FLDCNT   EQU   *                   1 BYTE(S)
         DC    X'01'
FLDSIZE  EQU   *                   1 BYTE(S)
         DC    X'0C'
SOMETNG  EQU   *                   1 BYTE(S)
         DC    X'00'
SNSSIZE  EQU   *                   1 BYTE(S)
         DC    X'18'
FLG1     EQU   *                   1 BYTE(S)
         DC    X'00'
SNSCNTTB EQU   *                   1 BYTE(S)
         DC    X'01'
CLRTECB  EQU   TECB+00000006       39 BYTE(S)
CNTSNS   EQU   *                   1 BYTE(S)
         DC    X'00'
CNTINT   EQU   *                   1 BYTE(S)
         DC    X'00'
CCP      EQU   TECB+00000008       1 BYTE(S)
A00030   EQU   TECB+00000009       3 BYTE(S)
CSW1     EQU   TECB+00000012       8 BYTE(S)
A00031   EQU   TECB+00000012       4 BYTE(S)
STATUSX  EQU   TECB+00000016       2 BYTE(S)
EXIOK    EQU   TECB+00000016       1 BYTE(S)
A00032   EQU   TECB+00000016       6 BIT(S)
UNITCK   EQU   TECB+00000016       1 BIT(S)
UNITEXCP EQU   TECB+00000016       1 BIT(S)
BYTE2    EQU   TECB+00000017       1 BYTE(S)
A00033   EQU   TECB+00000017       1 BIT(S)
INLENGTH EQU   TECB+00000017       1 BIT(S)
A00034   EQU   TECB+00000017       6 BIT(S)
A00035   EQU   TECB+00000018       2 BYTE(S)
SENSE    EQU   TECB+00000020       24 BYTE(S)
A00036   EQU   TECB+00000020       3 BYTE(S)
SNS1     EQU   TECB+00000023       7 BYTE(S)
SNSFLD   EQU   TECB+00000023       8 BIT(S)
A00037   EQU   TECB+00000023       1 BIT(S)
SNS2     EQU   TECB+00000023       1 BIT(S)
A00038   EQU   TECB+00000024       2 BYTE(S)
A00039   EQU   TECB+00000026       8 BIT(S)
A00040   EQU   TECB+00000026       5 BIT(S)
PEIND    EQU   TECB+00000026       1 BIT(S)
A00041   EQU   TECB+00000027       2 BYTE(S)
A00042   EQU   TECB+00000029       1 BYTE(S)
A00043   EQU   TECB+00000029       4 BIT(S)
BIT4     EQU   TECB+00000029       1 BIT(S)
A00046   EQU   00000000            20 BYTE(S) ON WORD
MSG1     EQU   A00046+00000000     FULLWORD POINTER
MSG2     EQU   A00046+00000004     FULLWORD POINTER
MSG3     EQU   A00046+00000008     FULLWORD POINTER
MSG4     EQU   A00046+00000012     FULLWORD POINTER
MSG5     EQU   A00046+00000016     FULLWORD POINTER
MSGSNS   EQU   00000037            12 BYTE(S)
MSGCSW   EQU   00000018            14 BYTE(S)
MSGDEVAD EQU   00000039            8 BYTE(S)
MECB     EQU   @DATA+00000136      FULLWORD INTEGER
INBUF1   EQU   @DATA+00000140      1 BYTE(S)
A00047   EQU   00000000            8 BYTE(S) ON WORD
LENGTH   EQU   A00047+00000000     1 BYTE(S)
REPLYAD  EQU   A00047+00000001     3  BYTE  POINTER ON WORD+1
ECBAD    EQU   A00047+00000004     FULLWORD POINTER
MSG4DVAD EQU   00000022            8 BYTE(S)
OUTBUFRI EQU   @DATA+00000141      13 BYTE(S)
SNSOUT   EQU   OUTBUFRI+00000000   6 BYTE(S)
CSWOUT   EQU   OUTBUFRI+00000006   7 BYTE(S)
INBUF    EQU   @DATA+00000154      26 BYTE(S)
SNSIN    EQU   INBUF+00000000      12 BYTE(S)
CSWIN    EQU   INBUF+00000012      14 BYTE(S)
VOL1BUF  EQU   @DATA+00000180      80 BYTE(S)
VOLNAME  EQU   VOL1BUF+00000000    10 BYTE(S)
         ORG   VOL1BUF+00000010
A00048   EQU   *                   70*1 BYTE(S)
         DC    00070C'0'
HDR1BUF  EQU   @DATA+00000260      80 BYTE(S)
HDRNAME  EQU   *                   4 BYTE(S)
         DC    C'HDR1'
A00049   EQU   *                   76*1 BYTE(S)
         DC    00076C'0'
HCODE    EQU   00000084            1 BYTE(S)
         ORG   @DATA
         DS    00000344C
@TEMPS   DS    0F
@TEMP4   DC    F'0'
WRTBOTH  CCW   7,*,X'60',1              REWIND
         CCW   1,VOL1BUF,X'60',80       WRITE VOL1 RECORD
         CCW   1,HDR1BUF,X'60',80       WRITE HDR1 RECORD
         CCW   04,*,X'30',1  FORCE CHAN END AND DEV END, NO DATA TRANS
CNVRT    DC    B'00000000'         CONTROL PROGRAM FLAGS
         DC    AL1(2)              MACRO LEVEL
         DC    CL2'41'             MACRO ID
         DC    A(OUTBUFRI)
         DC    A(INBUF)
         DC    AL2(13+32768)       COUNT AND TYPE INFORMATION
DSECT53  IFDCOM
VID      EQU   WKSVC+00000002      2 BYTE(S)
MID1     EQU   MCT+00000010        2 BYTE(S)
FLG1A    EQU   FLGA+00000000       8 BIT(S) ON BYTE
BYPASS   EQU   FLG1A+00000000      1 BIT(S)
FLG2     EQU   FLGB+00000000       8 BIT(S) ON BYTE
INTCALL  EQU   FLG2+00000000       1 BIT(S)
MODEREQ  EQU   FLG2+00000000       1 BIT(S)
A00000   EQU   CESWT+00000000      4 BYTE(S) ON WORD
A00001   EQU   A00000+00000000     8 BIT(S)
A00002   EQU   A00000+00000000     1 BIT(S)
PROTECT  EQU   A00000+00000000     1 BIT(S)
A00003   EQU   A00000+00000000     6 BIT(S)
A00004   EQU   A00000+00000001     8 BIT(S)
A00005   EQU   A00000+00000001     1 BIT(S)
SEEK2321 EQU   A00000+00000001     1 BIT(S)
SECONLOK EQU   A00000+00000001     1 BIT(S)
A00006   EQU   A00000+00000001     1 BIT(S)
FILMSK   EQU   A00000+00000001     1 BIT(S)
T2321    EQU   A00000+00000001     1 BIT(S)
ONLINEOK EQU   A00000+00000001     1 BIT(S)
A00007   EQU   A00000+00000001     1 BIT(S)
A00008   EQU   A00000+00000002     8 BIT(S)
NDCFO    EQU   A00000+00000002     1 BIT(S)
DPONDEV  EQU   A00000+00000002     1 BIT(S)
A00009   EQU   A00000+00000002     1 BIT(S)
CHANTEST EQU   A00000+00000002     1 BIT(S)
A00010   EQU   A00000+00000002     1 BIT(S)
A00011   EQU   A00000+00000002     1 BIT(S)
TAPEHDR  EQU   A00000+00000002     1 BIT(S)
DEVDPOK  EQU   A00000+00000002     1 BIT(S)
A00012   EQU   A00000+00000003     8 BIT(S)
A00013   EQU   A00000+00000003     1 BIT(S)
BYPALDEV EQU   A00000+00000003     1 BIT(S)
BYPDEV   EQU   A00000+00000003     1 BIT(S)
A00014   EQU   A00000+00000003     1 BIT(S)
SUSDEL   EQU   A00000+00000003     1 BIT(S)
A00015   EQU   A00000+00000003     1 BIT(S)
A00016   EQU   A00000+00000003     1 BIT(S)
STDLAB   EQU   A00000+00000003     1 BIT(S)
A00017   EQU   CESWT8+00000000     1 BYTE(S) ON WORD
A00018   EQU   A00017+00000000     2 BIT(S)
LETGO    EQU   A00017+00000000     1 BIT(S)
A00044   EQU   MSSSTAT+00000000    1 BYTE(S)
FINITSW  EQU   A00044+00000000     1 BIT(S)
DINITSW  EQU   A00044+00000000     1 BIT(S)
INITSW   EQU   A00044+00000000     1 BIT(S)
A00045   EQU   A00044+00000000     5 BIT(S)
OLTTAB2  EQU   OLTTAB+00000004     FULLWORD POINTER
A00050   EQU   ROPT+00000000       8 BYTE(S) ON WORD
UCBADDR  EQU   A00050+00000000     4 BYTE(S)
FLAGS    EQU   A00050+00000004     4 BYTE(S)
SVCFLG   EQU   A00050+00000004     1 BYTE(S)
A00051   EQU   A00050+00000005     3 BYTE(S)
@DATEND  EQU   *
@9F9     EQU   INCRPTR
@DO9FE   EQU   @EL01
         END    ,(C'PL/S',1400,78116)
