         TITLE 'IFDOLT73 LINE CONNECTION MODULE'
         LCLA  &T,&SPN                                            0001
.@001    ANOP                                                     0001
IFDOLT73 CSECT ,                                                  0001
         BC    15,24(0,@F)
         DC    C'IFDOLT73 12 FEB 74'                             0001
         ST    @E,12(0,@D)                                        0001
         STM   @0,@C,20(@D)                                       0001
         BALR  @B,0                                               0001
@PSTART  DS    0H                                                 0001
         USING @PSTART+00000,@B                                   0001
         ST    @D,@SAV001+4                                       0001
         LA    @F,@SAV001                                         0001
         ST    @F,8(0,@D)                                         0001
         LR    @D,@F                                              0001
         TITLE 'OS OLTEP LINE CONNECTION MODULE IFDOLT73'
         DS    0H
* GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* /*                 IFDOLT73 REGISTER DEFINITIONS BELOW
* /********************************************************************
*         /* START
*         DCL   R0 REG(0);               /*REG FOR POSTING TIMEOUT
*         DCL   R1 REG(1) PTR;           /*REG FOR MSG PTR
*         DCL   R2 REG(2) PTR;           /*REG PTR TO OLTEP COMMON AREA
*         DCL   R6 REG(6);               /*LINK REG FOR EXCP ROUTINE
*         DCL   R7 REG(7);               /*LINK REG FOR OUTPUT MESSAGE
*         DCL   R9 PTR REG(9);           /*MESSAGE MODULE POINTER
*         DCL   R14 REG(14) PTR;         /*LINK REG FOR CONVERT MODULE
*         DCL   R15 REG(15) PTR;         /*RETURN CODE REGISTER
*         DCL   DEVPT1 PTR(24) REG(3);   /*DEVTAB ENTRY
*         DCL   DEVPT2 PTR(24) REG(4);   /*PTR TO DEVTAB SEARCH FOUND
*         DCL   CCWADR PTR(24) REG(4);   /*PTR TO NEXT CCW AREA
*         DCL   CDSPTR PTR(31) REG(5);   /*PTR TO OLT'S CDS
*         DCL   VARFLDPT PTR(24) REG(7); /*PTR TO EXTENDED FIELD IN CDS
*         DCL   IOSBPTR PTR(31) REG(8);   /*PTR TO IOSB          Y02008
*         GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* /*  DEFINITIONS OF INTERNAL FLAGS
* /********************************************************************
*         /* START
*         DCL   1 LCRFLAG CHAR(1),       /*INTERNAL FLAGS
*                3 TELNO BIT(1),         /*DIAL DIGITS IN CDS FLAG
*                3 OPERCALL BIT(1),      /*OPERATOR CALL FLAG
*                3 RETRY BIT(1),         /*RETRY FLAG
*                3 UNSUCCES BIT(1),      /*EXCP UNSUCCESSFUL FLAG
*                3 HDRMSG BIT(1);       /* FLAG FOR HEADER MSG  X02008*
*
*         DCL R1SAVE FIXED;             /* REG 1 SAVE AREA      X02008*
*
* /********************************************************************
* /*  DEFINITION OF INTERNAL WORK AREAS
* /********************************************************************
*         /* START
*         DCL   CAWPTR PTR(31);          /*PTR TO CHANNEL PROGRAM
*         /* FAILED CCW
*         DCL   FAIL CHAR(8) BASED(CCWADR);
*         /*
*         DCL   1 DEC CHAR(40) BDY(WORD),/*EBCDIC SAVE AREA
*                3 DECCSW CHAR(14),      /*EBCDIC CSW
*                3 DECCCW CHAR(16),      /*EBCDIC CCW
*                3 DECSENSE CHAR(4);     /*EBCDIC SENSE
*         /*
*         DCL   1 HEX CHAR(17) BDY(WORD),/*SAVE AREA FOR HEX NUMBERS
*                3 HEXCSW CHAR(7),       /*HEX CSW
*                 5 * CHAR(3),           /*NOT USED
*                 5 * BIT(6),            /*NOT USED
*                 5 SAVUNITCHK BIT(1),   /*UNIT CHECK FLAG
*                 5 * BIT(1),            /*NOT USED
*                 5 * CHAR(1),           /*NOT USED
*                3 HEXCCW CHAR(8),       /*FAILED CCW SAVE AREA
*                3 HEXSENSE CHAR(2);     /*SENSE BYTES
*         /* CONVERT PARAMETER LIST
*         DCL   1 CONVERT CHAR(14) BDY(WORD),
*                /* CONSTANT
*                3 * CHAR(2) INIT('0002'X),
*                /* CONSTANT
*                3 * CHAR(2) INIT('41'),
*                /* FROM ADDRESS
*                3 * PTR(31) INIT(ADDR(HEX)),
*                /* TO ADDRESS
*                3 * PTR(31) INIT(ADDR(DEC)),
*                /* FLAG AND COUNT
*                3 * CHAR(2) INIT('8011'X);
*         /*
*         DCL 1 ONES CHAR(80),           /*80 BYTES OF ONES FOR WRITE
*                3 *(80) CHAR(1) INIT((80)'FF'X);
*         DCL 1 X20F0 CHAR(20),          /*20 BYTES OF F0 FOR DIAL DGTS
*              3 *(20) CHAR(1) INIT((20)'F0'X);
*         /* SEARCH TABLE FOR CCW COMMAND CODE
*         DCL 1 CODE CHAR(7),            /*COMMAND CODE
*                3 * CHAR(1),            /*NOT USED
*                /* SET MODE
*                3 SETMODE(2) CHAR(1) INIT((2)'23'X),
*                /* SADXX
*                3 SADXX(4) CHAR(1) INIT('13'X,'17'X,'1B'X,'1F'X);
*         /************************************************************
*         GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* /*                           COMMON CORE MAP
* /********************************************************************
*         /* START
*         DCL   UNICTR CHAR(1) GEND;     /*NUMBER OF ENTRIES IN DEVTAB
*         DCL   TAB28 GEND;              /* COMMON AREA TABLE
*         DCL   DEVTBPTR PTR(31) GEND;   /*PTR TO DEVTAB
*         /* LENGTH OF DEVTAB ENTRY
*         DCL   TABLNGTH FIXED(15) BDY(WORD) GEND;
*
*         DCL CESWT7 CHAR(1) GEND;       /* DIAGNOSTIC SWITCH    Y02008
*
*         DCL 1 * BASED(ADDR(CESWT7)),   /* FORMAT OF SWITCH     Y02008
*           3 * BIT(6),                  /* N A                  Y02008
*           3 VIRTUAL BIT(1);            /* OLTEP IS IN VIRTUAL  Y02008
*
*         /************************************************************
*         GEN(USING CHASCT,2);
         USING CHASCT,2
         DS    0H
*         GENERATE DATA;                 /* COMMON AREA
* /********************************************************************
* /*                      MESSAGE MODULE MAP
* /********************************************************************
*         /* MESSAGE MODULE LABEL
*         DCL   IFDMSG73 LABEL NONLOCAL EXTERNAL;
*         /* MESSAGES
*         DCL   1 MSGPTR BASED(R9),
*                3 IFDXX1 PTR,           /* IFD413I
*                3 IFDXX2 PTR,           /* IFD400I
*                3 IFDXX3 PTR,           /* IFD415I
*                3 IFDXX7 PTR,           /* IFD405I
*                3 IFDXX8 PTR,           /* IFD406I
*                3 IFDXX9 PTR,           /* IFD412I
*                3 IFDXXA PTR,           /* IFD407I
*                3 IFDXXB PTR,           /* IFD137I
*                3 IFD408I PTR;          /* IFD408I MSG          Y02008
*         /* IFD400I
*         DCL   1 MSG2 BASED(R1),
*                3 * CHAR(12),           /*NOT USED
*                3 * CHAR(25),           /*NOT USED
*                3 LINE CHAR(8),         /*LINE ADDRESS
*                3 * CHAR(11),           /*NOT USED
*                3 NAME CHAR(8);         /*TERMINAL SYMBOLIC NAME
*         /* IFD406I
*         DCL   1 MSG8 BASED(R1),
*                3 * CHAR(4),            /* NOT USED
*                3 * CHAR(41),           /* NOT USED
*                3 DDGT CHAR(20);        /*DIAL DIGITS
*         /* IFD412I
*         DCL   1 MSG9 BASED(R1),
*                3 * CHAR(4),            /* NOT USED
*                3 * CHAR(32),           /* NOT USED
*                3 CCWFAIL CHAR(16);     /* CCW
*         /* IFD137I
*         DCL 1 MSG11 BASED(R1),
*                3 * CHAR(4),            /* NOT USED
*                3 * CHAR(14),           /* NOT USED
*                3 STATUS CHAR(14),      /* CSW
*                3 * CHAR(5),            /* NOT USED
*                3 SENSE CHAR(4);        /* SENSE
*
*         DCL 1 MSG408 BASED(R1),        /* MESSAGE IFD408I      Y02008
*           3 * CHAR(12),                /* N A                  Y02008
*           3 ERRORLIN CHAR(8),          /* LINE IN ERROR        Y02008
*           3 * CHAR(50);                /* MSG TEXT             Y02008
*         GEN(EJECT);                    /* EJECT
         EJECT
         DS    0H
* /********************************************************************
* /*  THE FOLLOWING MAPS DEFINE THE IOSB-TECB-WAITLIST          Y02008*
* /********************************************************************
*
*         DCL IORTNADR PTR GEND;         /* I/0 EFFECTOR ADDRESS Y02008
*
*
*         DCL EFCTRCB CHAR(20) GEND;    /* I O EFFECTOR PLIST   Y02008*
*
*         /* PTR TO CCWS FOR ENBL Y02008*/
*         DCL IOCCWADR PTR BASED(ADDR(EFCTRCB));
*
*         DCL DVTPTR PTR GEND;           /* PTR TO DEV TABLE     Y02008
*         DCL FLGA CHAR(1) GEND;         /* FLAG BYTE            Y02008
*         DCL GDP CHAR(1) GEND;          /* GUARANTEE DEV PATH   Y02008
*         DCL FLGB CHAR(1) GEND;         /* FLAG BYTE            Y02008
*         DCL INTERNAL CHAR(1) GEND;     /* INTERNAL IOSB CALL   Y02008
*         DCL ATTNIN CHAR(1) GEND;       /* ATTENTION INTERUPT   Y02008
*         DCL VIRTCCWS CHAR(1) GEND;     /* CCW STRING IN VIRTUALY02008
*         DCL FILEMSK CHAR(1) GEND;      /* DEV FILE MASK        Y02008
*         DCL OLDTECBX CHAR(1) GEND;     /* USE OLD TECB FORMAT  Y02008
*         DCL SNSCNT CHAR(1) GEND;          /* SNS BYTES EXPCTED Y02008
*         DCL TECBPTRX PTR GEND;         /* PTR TO ACTV TECB     Y02008
*
*         /************************************************************
*         /* THE FOLLOWING MAPS THE WAIT I/O LIST                Y02008
*         /************************************************************
*
*         DCL 1 WAITLIST CHAR BDY(WORD), /* WAIT LIST FOR WAITIO Y02008
*           3 XMGR CHAR(1) INIT('00'X),  /* OLTEP TRANSMNGR FLGS Y02008
*           3 LVL CHAR(1) INIT('02'X),   /* LEVEL 02 OF MACRO    Y02008
*           3 MODID CHAR(2) INIT('36'),  /* ID OF WAIT I/O MOD   Y02008
*           3 TECBPTR PTR INIT(ADDR(TECB)),  /* ADDR OF OLT TECB Y02008
*           3 CDSDATA PTR INIT('00'X),   /* ADDR OF CDS TO USE   Y02008
*           3 FLG CHAR(1) INIT('80'X),   /* FLAG BYTE            Y02008
*             5 WAITYES BIT(1),          /* WAIT REQ FOR EVENT   Y02008
*           3 TIME CHAR(2);              /* TIME PARM FOR WAIT   Y02008
*
*         DCL WAITRC FIXED;              /* WAIT IO RETURN CODE  Y02008
*         /************************************************************
*         /* THE FOLLOWING MAPS THE NEW TECB FORMAT USED IN IO   Y02008
*         /************************************************************
*
*         DCL 1 TECB CHAR,               /* NEW TECB FORMAT      Y02008
*           3 FLDCNT CHAR(1)  INIT('01'X),  /* EVENT FIELDS USED Y02008
*           3 FLDSIZE CHAR(1) INIT('0C'X),  /* SIZE OF EVENT FLD Y02008
*           3 *  CHAR(1) INIT('00'X),    /* NOT APPLICABLE       Y02008
*           3 SNSIZE CHAR(1) INIT('05'X),/* NUM OF SENS BYTES    Y02008
*           3 FLG1 CHAR(1) INIT('00'X),  /* FLAG BYTE            Y02008
*           3 SNSFIELD CHAR(1) INIT('01'X),/* NUM SENSE FIELDS   Y02008
*           3 CNTSNS CHAR(1) INIT('00'X),/* NUM SNS FIELDS FILLEDY02008
*           3 CNTINT CHAR(1) INIT('00'X),/* NUM INT FIELDS FILLEDY02008
*           3 SIOCC CHAR(1) INIT('00'X), /* START I/O COND CODE  Y02008
*           3 *  CHAR(1) INIT('00'X),    /* N A                  Y02008
*           3 DEVAD CHAR(2) INIT('0000'X),  /* DEVADR IN TECB    Y02008
*           3 *   CHAR(1) INIT('00'X),   /* N A                  Y02008
*           3 OUTBUFR(12) CHAR(1) INIT((12)'00'X),   /* DATA BUF Y02008
*             5 CSW1 CHAR(7),            /* EVENT CSW            Y02008
*               7 CCWPLUS8 CHAR(3),      /* NEXT CCW TO BE ISSUEDY02008
*               7 TECBFLGA CHAR(1),      /* CSW FLAG BYTE        Y02008
*                 9 * BIT(4),            /* N A                  Y02008
*                 9 CHANEND BIT(1),      /* CHANNEL END INDICATORY02008
*                 9 DEVICEND BIT(1),     /* DEVICE END INDICATOR Y02008
*                 9 UNITCHCK BIT(1),     /* UNIT CHECK INDICATOR Y02008
*               7 TECBFLGB CHAR(1),      /* FLAG BYTE            Y02008
*             5 * CHAR(3),               /* I/O DEV ADDR         Y02008
*             5 TSNS1 CHAR(2);           /* TECB EVENT SENSE     Y02008
*
*         GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* /*  THE FOLLOWING MAPS DEFINE DEVTAB ENTRIES
* /********************************************************************
*         /* START
*         DCL   1 * BASED(DEVPT1),
*                3 DEVADDR1 CHAR(8),     /*LINE ADDR
*                3 UCBADDR1 PTR(31),     /*UCB ADDR
*                3 * CHAR(1),
*                 5 * BIT(1),            /*NOT USED
*                 5 PRIMARY BIT(1),      /*PRIMARY DEVICE FLAG
*                 5 * BIT(6),            /*NOT USED
*                3 * CHAR(2),            /*NOT USED
*                3 * CHAR(1),            /*LINE STATUS FLAGS
*                 5 LNDSBL1 BIT(1),      /*LINE DISABLED BY OLTED FLAG
*                 5 LNENBL1 BIT(1),      /*LINE ENABLED FLAG
*                 5 * BIT(6),            /*NOT USED
*                3 * CHAR(25),           /*NOT USED
*                3 * CHAR(1),            /*CDS FLAG
*                 5 * BIT(4),            /*NOT USED
*                 5   NMPRSNT1 BIT(1),   /*SYMBOLICALLY NAMED TERMINAL
*                 5 * BIT(3),            /*NOT USED
*                3 * CHAR(2),            /*NOT USED
*                3 SYMBNM1 CHAR(8),      /*SYMBOLIC NAME
*                3 * CHAR(4);            /*NOT USED
*         /* 2ND DEVICE POINTER
*         DCL   1 * BASED(DEVPT2),
*                3 DEVADDR2 CHAR(8),     /*LINE ADDR
*                3 * CHAR(7),            /*NOT USED
*                3 * CHAR(1),            /*LINE STATUS FLAGS
*                 5 LNDSBL2 BIT(1),      /*LINE DISABLED BY OLTEP FLAG
*                 5 LNENBL2 BIT(1),      /*LINE ENABLED FLAG
*                 5 * BIT(6),
*                 5 CHAR(40);            /* NOT USED            Y02008*
*         GEN(EJECT);
         EJECT
         DS    0H
*         /************************************************************
*         /*    THE FOLLOWING MAP DEFINES A CDS ENTRY           Y02008*
*         /************************************************************
*
*         DCL   1 * BASED(CDSPTR),
*                3 * CHAR(9),            /*NOT USED
*                3 * CHAR(1),            /*NOT USED
*                 5 * BIT(4),            /* NOT USED
*                 5 SYMNMFLG BIT(1),     /* SYMBOLIC NAME FLAG
*                 5 * BIT(2),            /* NOT USED
*                 5 LCRFLG BIT(1),       /* LCR FLAG
*                3 * CHAR(11),           /*NOT USED
*                3 * CHAR(1),            /*NOT USED
*                 5 SMPRSNT BIT(1),      /*SET MODE BYTES IN CDS FLAG
*                 5 AUTOCALL BIT(1),     /*AUTOCALL FEATURE FLAG
*                 5 SWITCHLN BIT(1),     /*SWITCHED LINE FLAG
*                 5 NSWTCHLN BIT(1),     /*NON SWITCHED LINE FLAG
*                 5 WORLDTRD BIT(1),     /*WORLD TRADE FLAG
*                 5 * BIT(3),            /*NOT USED
*                3 * CHAR(1),            /*NOT USED
*                3 CMDSEQ CHAR(1),       /* COMMAND SEQUENCE CODE
*                3 VARIABLE CHAR(23);    /*EXTENDED FIELD IN CDS
*         /* COMMON AREA POINTER
*         DCL   1 * BASED(VARFLDPT),
*                3 DIALCNT CHAR(1),      /*DIAL DIGIT COUNT IN CDS
*                3 DIALDGT CHAR(20);     /*DIAL DIGITS IN CDS
* /********************************************************************
* /*  THE FOLLOWING MAP DEFINES THE PARAMETER LIST
* /********************************************************************
*         /* START
*         DCL   1 * BASED(R1),
*                3 * CHAR(4),            /*NOT USED
*                3 EXIOPTR PTR(31);      /*PTR TO PARAMETER LIST
*         /* PARAMETER LIST
*         DCL   1 * BASED(EXIOPTR),      /*PARAMETER LIST
*                3 DEVICE PTR(31),       /*PTR TO DEVTAB ENTRY
*                3 CDSADR PTR(31);       /*PTR TO OLT'S CDS
*         GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* /*  THE FOLLOWING DEFINES THE CHANNEL PROGRAM AREA
* /********************************************************************
*         /* LCR CCW AREA
*         DCL   1 CCWAREA CHAR(64) BDY(DWORD),
*                /* DISABLE CCW
*                3 DISABLE CHAR(8) INIT('2F00000020000001'X),
*                3 TWOCCW CHAR(16),      /*SADXX, SET MODE, DIAL OR
*                /*                          ENABLE CCW AREA
*                3 WRITECCW(6) CHAR(8),  /*6 DATA-CHAINED WRITE CCW'S
*                 /* WRITE COMMAND CODE
*                 5 * CHAR(1) INIT((6)'01'X),
*                 /* PTR TO 80 BYTES OF ONES
*                 5 * PTR(24) INIT((6)ADDR(ONES)),
*                 /* DC AND BYTE COUNT
*                 5 * CHAR(4) INIT((6)'E0000050'X),
*                3 * CHAR(8),
*                 /* WRITE COMMAND CODE
*                 5 * CHAR(1) INIT('01'X),
*                 /* PTR TO ONES
*                 5 * PTR(24) INIT(ADDR(ONES)),
*                 /* NOT DC AND BYTE COUNT
*                 5 * CHAR(4) INIT('20000050'X);
* /********************************************************************
* /*  THE FOLLOWING MAP DEFINES THE CCW
* /********************************************************************
*         /* CCW BREAK DOWN
*         DCL   1 CCW CHAR(8) BASED(CCWADR),
*                3 * CHAR(1),
*                3 DATAADDR PTR(24),     /*CCW PTR TO DATA AREA
*                3 * CHAR(4);
*         GEN(EJECT);                    /*EJECT PAGE
         EJECT
         DS    0H
*         /* SAVE
*
*
*         /************************************************************
*         /*          RETAIN SWITCH FORMATS                           *
*         /************************************************************
*
*         DCL CESWTR CHAR(1) GEND;      /* RETAIN SWITCH              *
*
*         DCL 1 * BASED(ADDR(CESWTR)),  /*    SWITCH STRUCTURE        *
*           3 RETAINAC BIT(1);          /* RETAIN ACTIVE              *
*
*
*         DCL CESWTR2 CHAR(1) GEND;     /* THIRD RETAIN FLAG          *
*
*         DCL 1 * BASED(ADDR(CESWTR2)), /* SWITCH STRUCTURE           *
*           3 * BIT(7),
*           3 DPMSGREI BIT(1);          /* DATA PROT MSG TO REMOY00427*
*         RESTRICT(DEVPT1,IOSBPTR,CDSPTR,R2);     /*             Y02008
* /********************************************************************
* /*                           INITIALIZATION
* /********************************************************************
*         /* START
*         EFCTRCB=EFCTRCB&&EFCTRCB;     /* CLEAR EFFECTOR PLIST Y02008*
         XC    EFCTRCB(20),EFCTRCB                                0080
*         IF RETAINAC='1'B THEN         /* IF RETAIN ACTIVE           *
         TM    A00070,B'10000000'                                 0081
         BC    12,@9FF                                            0081
*         HDRMSG='0'B;                  /* DONT OUTPUT HDR MSG  X02008*
         NI    LCRFLAG,B'11110111'                                0082
*         DPMSGREI='1'B;                /* REM SITE GETS MSG   OY00427*
@9FF     OI    A00071,B'00000001'                                 0083
*         RESTRICT(R1);
*         DEVPT1=DEVICE;                 /*SET DEVTAB SEARCH PARAMETER
         L     @4,4(0,@1)          
         L     @3,0(0,@4)                                         0085
*         CDSPTR=CDSADR;                 /*SET PTR TO CDS IN OLT
         L     @5,4(0,@4)                                         0086
*         RELEASE(R1);                   /* N/A
*         R9=ADDR(IFDMSG73);             /*SET MESSAGE MODULE POINTER
         L     @1,@V1              ADDRESS OF IFDMSG73            0088
         LR    @9,@1                                              0088
*         /* SAVE IT
*         RESTRICT(R9);
*         R1=IFDXX1;                     /*SET MSG PTR
         L     @1,0(0,@9)                                         0090
*         /* CHECK CDS PTR
*         IF CDSPTR=0 THEN               /*CDS ADDR SPECIFIED BY OLT
         LTR   @5,@5                                              0091
*           GOTO LCR4;                   /*NO - BRANCH TO ERROR RETURN
         BC    08,LCR4                                            0092
*         /* SAVE IT
*         RESTRICT(R1);
*         R1=IFDXX2;                     /*SET MSG PTR
         L     @1,4(0,@9)                                         0094
*         LINE=DEVADDR1;                 /*MOVE LINE ADDR FROM DEVTAB
         MVC   37(8,@1),0(@3)                                     0095
*         /* CHECK DEVTAB
*         IF SYMNMFLG='0'B THEN          /*SYMBOLICALLY NAMED TERMINAL?
         TM    9(@5),B'00001000'                                  0096
*           GOTO LCR2A;                  /*NO - BRANCH TO ERROR RETURN
         BC    08,LCR2A                                           0097
*         NAME=NAME&&NAME;               /* CLEAR NAME BUFFR   AS13319*
         XC    56(8,@1),56(@1)                                    0098
*         NAME=SYMBNM1;                  /*MOVE SYMBOLIC NAME FROM
         MVC   56(8,@1),44(@3)                                    0099
*         HDRMSG='1'B;                  /* OUTPUT HDR MSG       X02008*
         OI    LCRFLAG,B'00001000'                                0100
*         /* RELEASE
*         RELEASE(R1);
*         /* CHECK FOR LINE ALREADY DISABLED
*         IF LNENBL1='1'B THEN           /* YES
         TM    15(@3),B'01000000'                                 0102
         BC    12,@9FE                                            0102
*           DO;
*              LCRFLG='0'B;              /* RESET LCR FLAG IN CSWY02008
         NI    9(@5),B'11111110'                                  0104
*              GOTO LCR6;                /* RETURN
         BC    15,LCR6                                            0105
*           END;
*         /* CHECK SEQ CODE IN CDS
*         IF CMDSEQ='00'X THEN           /*BYPASS LINE CONNECTION ?
@9FE     CLI   23(@5),X'00'                                       0107
*           GOTO LCR6;                   /*YES - BRANCH TO RETURN
         BC    08,LCR6                                            0108
*         /* CHECK COMMAND SEQ IN CDS
*         IF CMDSEQ>='08'X THEN          /*VALID LINE CONNECTION ?
         CLI   23(@5),X'08'                                       0109
*           GOTO LCR3;                   /*BRANCH TO ERROR RETURN
         BC    10,LCR3                                            0110
*         RESTRICT(CCWADR);
*         LCRFLAG='00'X;                 /*CLEAR INTERNAL FLAGS
         MVI   LCRFLAG,X'00'                                      0112
*         TWOCCW=TWOCCW&&TWOCCW;         /*CLEAR CCW AREA
         XC    CCWAREA+8(16),CCWAREA+8                            0113
*         CAWPTR=ADDR(CCWAREA);          /*SET CHANNEL PROGRAM PTR
         LA    @F,CCWAREA                                         0114
         ST    @F,CAWPTR                                          0114
*         CCWADR=CAWPTR;                 /*SET PTR TO CHANNEL PROGRAM
         LR    @4,@F                                              0115
*         DISABLE(5)='60'X;              /*MAKE DISABLE CCW CHAINED
         MVI   CCWAREA+4,X'60'                                    0116
* /********************************************************************
*         /* END
*         GEN(EJECT);
         EJECT
         DS    0H
*         /* CHECK SEQ CODE IN CDS
*         IF CMDSEQ='01'X THEN           /*/*COMMAND SEQUENCE CODE=01
         CLI   23(@5),X'01'                                       0118
*           GOTO LCR1;                   /*YES - BRANCH
         BC    08,LCR1                                            0119
* /********************************************************************
* /*  SET MODE OR SADXX COMMAND ?
* /********************************************************************
*         /* START
*         CCWADR=CCWADR+8;               /*SET POINTER TO NEXT CCW
         LA    @4,8(0,@4)                                         0120
*         CCW(1)=CODE(CMDSEQ);           /*SET COMMAND CODE BY SEQ CODE
         SR    @1,@1                                              0121
         IC    @1,23(0,@5)                                        0121
         LA    @E,CODE-1(@1)                                      0121
         MVC   0(1,@4),0(@E)                                      0121
*         CCW(5)='60'X;                  /*MAKE CCW COMMAND CHAINED
         MVI   4(@4),X'60'                                        0122
*         CCW(8)='01'X;                  /*SET BYTE COUNT TO 1
         MVI   7(@4),X'01'                                        0123
*         /* CHECK SEQ CODE IN CDS
*         IF CMDSEQ='02'X THEN           /*SET MODE CCW FOR SDA-I ?
         CLI   23(@5),X'02'                                       0124
         BC    07,@9FD                                            0124
*           DO;                          /* YES-
*             CCW(5)='20'X;              /*NO COMMAND CHAINING
         MVI   4(@4),X'20'                                        0126
*             CCW(8)='02'X;              /*BYTE COUNT=2
         MVI   7(@4),X'02'                                        0127
*           END;                         /*
*         /* CHECK SEQ CODE IN CDS
*         IF CMDSEQ='02'X × CMDSEQ='03'X THEN/*
*                                          SET MODE CCW ?
@9FD     CLI   23(@5),X'02'                                       0129
         BC    08,@9FC                                            0129
         CLI   23(@5),X'03'                                       0129
         BC    07,@9FB                                            0129
*           DO;                          /* YES
*             /* CHECK CDS
*             IF SMPRSNT='0'B THEN       /*SET MODE BYTES IN CDS
@9FC     TM    21(@5),B'10000000'                                 0131
*               GOTO LCR3;               /*BRANCH TO ERROR RETURN
         BC    08,LCR3                                            0132
*             DATAADDR=ADDR(VARIABLE);   /*SET CCW PTR TO SET MODE BYTE
         LA    @F,24(0,@5)                                        0133
         ST    @F,@TEMP4                                          0133
         MVC   1(3,@4),@TEMP4+1                                   0133
*             /* CHECK CDS
*             IF CMDSEQ='02'X THEN       /*SET MODE CCW FOR SDA-I ?
         CLI   23(@5),X'02'                                       0134
         BC    07,@9FA                                            0134
*               DO;                      /*YES -
*                 RESTRICT(R6);
*                 GEN(BAL   R6,IOSBRTN); /*BRANCH TO IOSB ROUTINEY02008
         BAL   R6,IOSBRTN
         DS    0H
*                 /* RELEASE
*                 RELEASE(R6);
*                 /* CHECK ECB
*                 IF UNSUCCES='1'B THEN  /*EXCP SUCCESSFUL ?
         TM    LCRFLAG,B'00010000'                                0139
*                   GOTO LCR5;           /*NO - BRANCH TO RETURN
         BC    01,LCR5                                            0140
*                 CAWPTR=CCWADR+8;       /*RESET CHANNEL PROGRAM PTR
         LA    @F,8                                               0141
         AR    @F,@4                                              0141
         ST    @F,CAWPTR                                          0141
*               END;
*           END;
@9FA     EQU   *                                                  0143
*         /* EJECT PAGE
*         GEN(EJECT);
@9FB     EQU   *                                                  0144
         EJECT
         DS    0H
* /********************************************************************
* /*  ENABLE OR DIAL COMMAND ?
* /********************************************************************
* LCR1:                                  /* BUILD CCWS
*         CCWADR=CCWADR+8;               /*POINT TO NEXT CCW
LCR1     LA    @4,8(0,@4)                                         0145
*         CCW(1)='27'X;                  /*ENABLE COMMAND CODE
         MVI   0(@4),X'27'                                        0146
*         CCW(5)='20'X;                  /*NO COMMAND CHAINING
         MVI   4(@4),X'20'                                        0147
*         CCW(8)='01'X;                  /* BYTE COUNT
         MVI   7(@4),X'01'                                        0148
*         /* CHECK CDS
*         IF SWITCHLN='0'B THEN          /*SWITCHED LINE ?
         TM    21(@5),B'00100000'                                 0149
*           GOTO LCR2;                   /* NO
         BC    08,LCR2                                            0150
*         /* CHECK CDS
*         IF AUTOCALL='0'B THEN          /*SWITCHED LINE W/AUTOCALL
         TM    21(@5),B'01000000'                                 0151
         BC    05,@9F9                                            0151
*           /* NO -  SDA-II AND WORLD TRADE ?
*           IF CMDSEQ='03'X & WORLDTRD='1'B
*             THEN                       /* YES
         CLI   23(@5),X'03'                                       0152
         BC    07,@9F8                                            0152
         TM    21(@5),B'00001000'                                 0152
         BC    12,@9F7                                            0152
*               CCW(5)='60'X;            /*MAKE ENABLE COMMAND CHAUNED
         MVI   4(@4),X'60'                                        0153
*         /* RESTRICT
*         RESTRICT(VARFLDPT);
@9F7     EQU   *                                                  0154
@9F8     EQU   *                                                  0154
*         VARFLDPT=ADDR(VARIABLE);       /*SET POINTER TO VARIABLE
@9F9     LA    @7,24(0,@5)                                        0155
*         /* FIELD IN OLTS CDS
*         /* CHECK CDS
*         IF SMPRSNT='1'B THEN           /*SET MODE BYTES IN CDS ?
         TM    21(@5),B'10000000'                                 0156
         BC    12,@9F6                                            0156
*           VARFLDPT=VARFLDPT+2;         /*YES-RESET PTR TO DIAL
         LA    @7,2(0,@7)                                         0157
*         /* CHECK CDS
*         IF DIALCNT>'14'X THEN          /*DIGIT COUNT 20  ?
@9F6     CLI   0(@7),X'14'                                        0158
*           GOTO LCR3;                   /*BRANCH TO ERROR RETURN
         BC    02,LCR3                                            0159
* /********************************************************************
*         /* CHECK CDS
*         IF AUTOCALL='0'B THEN          /*AUTOCALL ON SWITCHED LINE?
         TM    21(@5),B'01000000'                                 0160
         BC    05,@9F5                                            0160
*           DO;                          /*NO-
*             OPERCALL='1'B;             /*SET OPERATOR CALL FLAG ON
         OI    LCRFLAG,B'01000000'                                0162
*             /* CHECK CDS
*             IF DIALCNT^='00'X THEN     /*DIAL DIGITS IN CDS ?
         CLI   0(@7),X'00'                                        0163
         BC    08,@9F4                                            0163
*               DO;                      /*YES-
*                 TELNO='1'B;            /* SET FLAG
         OI    LCRFLAG,B'10000000'                                0165
*                 /* RESTRICT
*                 RESTRICT(R1);
*                 R1=IFDXX8;             /*SET MSG PTR
         L     @1,16(0,@9)                                        0167
*                 /*MOVE DIAL DIGITS INTO MESSAGE
*                 DDGT=DIALDGT(1:DIALCNT);
         SR    @6,@6                                              0168
         IC    @6,0(0,@7)                                         0168
         BCTR  @6,0                                               0168
         LA    @E,1(0,@7)                                         0168
         LA    @A,45(0,@1)                                        0168
         MVI   0(@A),C' '                                         0168
         MVC   1(019,@A),0(@A)                                    0168
         EX    @6,@MVC                                            0168
*                 DDGT(1:DIALCNT)=       /* OR IN F0'S
*                 DDGT(1:DIALCNT) ×      /* IN CASE NUMBER
*                 X20F0(1:DIALCNT);      /* NOT IN EBCDIC
         LA    @E,X20F0                                           0169
         SR    @6,@6                                              0169
         IC    @6,0(0,@7)                                         0169
         BCTR  @6,0                                               0169
         LA    @A,45(0,@1)                                        0169
         EX    @6,@OC                                             0169
*                 /* RELEASE
*                 RELEASE(R1);
*               END;
*           END;
         BC    15,@9F3                                            0173
*         ELSE                           /*YES - AUTOCALL ON SWITCHED
*           /*                             LINE
*           DO;
*             /* CHECK CDS
*             IF DIALCNT='00'X THEN      /*DIAL DIGITS IN CDS ?
@9F5     CLI   0(@7),X'00'                                        0174
*               GOTO LCR3;               /* ERROR
         BC    08,LCR3                                            0175
*             CCW(1)='29'X;              /*CHANGE ENABLE TO DIAL
         MVI   0(@4),X'29'                                        0176
*             DATAADDR=ADDR(DIALDGT);    /*POINT TO DUAL DIGITS IN CDS
         LA    @F,1(0,@7)                                         0177
         ST    @F,@TEMP4                                          0177
         MVC   1(3,@4),@TEMP4+1                                   0177
*             CCW(5)='20'X;              /*NO CHAINING
         MVI   4(@4),X'20'                                        0178
*             CCW(8)=DIALCNT;            /*BYTE COUNT
         MVC   7(1,@4),0(@7)                                      0179
*           END;
* /********************************************************************
*         /* RELEASE
*         RELEASE(VARFLDPT);
@9F3     EQU   *                                                  0181
*         /* RELEASE
*         RELEASE(CCWADR);
* /********************************************************************
*         /* EJECT
*         GEN(EJECT);
         EJECT
         DS    0H
* LCR2:                                  /*SET UP TO GO TO IOSB RTN
*         /* SAVE REG 6
*         RESTRICT(R6);
LCR2     EQU   *                                                  0184
*         GEN(BAL   R6,IOSBRTN);         /*BRANCH TO EXCP ROUTINE TO
         BAL   R6,IOSBRTN
         DS    0H
*         RELEASE(R6);                   /*  ENABLE LINE
*         /* CHECK ECB
*         IF UNSUCCES='1'B THEN          /* I/O SUCCESSFUL ?
         TM    LCRFLAG,B'00010000'                                0187
*           GOTO LCR5;                   /*NO - BRANCH TO RETURN
         BC    01,LCR5                                            0188
*         /* RELEASE REG 8
*         RELEASE(IOSBPTR);
* /********************************************************************
*         LCRFLG='0'B;                   /*RESET LCR FLAG IN CDS
         NI    9(@5),B'11111110'                                  0190
*         LNENBL1='1'B;                  /*SET ENABLE FLAG ON IN DEVTAB
         OI    15(@3),B'01000000'                                 0191
*         LNDSBL1='0'B;                  /*SET DISABLE FLAG OFF
         NI    15(@3),B'01111111'                                 0192
*         /* EJECT
*         GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* LCR6:                                  /* NORMAL RETURN
*         DPMSGREI='0'B;                /* TURN OFF REM MSG FLGOY00427*
LCR6     NI    A00071,B'11111110'                                 0194
*         R15=0;                         /*SET RETURN CODE=00
         SR    @F,@F                                              0195
*         RETURN;                        /*YES - RETURN TO EXIO MODULE
         BC    15,@EL01                                           0196
* /********************************************************************
* LCR2A:                                 /*SET UP TO GO TO MESSAGE RTN
*         GEN(BAL   R7,MSGRTN);          /*BRANCH TO OUTPUT MESSAGE
LCR2A    BAL   R7,MSGRTN
         DS    0H
* /********************************************************************
* LCR3:                                  /* ERROR
*         R1=IFDXX3;                     /*SET ERROR MSG PTR
LCR3     L     @1,8(0,@9)                                         0198
* /********************************************************************
* LCR4:                                  /*SET UP TO GO TO MESSAGE RTN
*         GEN(BAL   R7,MSGRTN);          /*BRANCH TO OUTPUT MESSAGE
LCR4     BAL   R7,MSGRTN
         DS    0H
* /********************************************************************
* LCR5:                                  /* ERROR RETURN
*         DPMSGREI='0'B;                /* REM SITE GETS MSG   OY00427*
LCR5     NI    A00071,B'11111110'                                 0200
*         R15=20;                        /*SET RETURN CODE=14
         LA    @F,20                                              0201
*         RETURN;                        /*RETURN TO EXIO MODULE
         BC    15,@EL01                                           0202
*         RELEASE(DEVPT1,CDSPTR);
* /********************************************************************
* /*  OUTPUT OPERATOR MESSAGE ROUTINE
* /********************************************************************
* MSGRTN:                                /* MESSAGE ROUTINE
*
*         /* OUTPUT HEADER MESSAGE FOR IFDOLT73, LINE ADDR AND SYMNAM *
*         IF HDRMSG='1'B THEN           /* IF HDR MSG FLAG IS ONX02008*
MSGRTN   TM    LCRFLAG,B'00001000'                                0204
         BC    12,@9F2                                            0204
*          DO;                          /* SET UP FOR MSG OUTPUTX02008*
*           R1SAVE=R1;                  /* SAVE ERROR MSG PTR   X02008*
         ST    @1,R1SAVE                                          0206
*           R1=IFDXX2;                  /* ADDRESS HEADER MSG   X02008*
         L     @1,4(0,@9)                                         0207
*           GEN(PWTO REG=(1));          /* OUTPUT MESSAGE       X02008*
         PWTO REG=(1)
         DS    0H
*           R1=R1SAVE;                  /* RESTORE REG 1 VALUE  X02008*
         L     @1,R1SAVE                                          0209
*           HDRMSG='0'B;                /* DONT OUTPUT MSG AGAINX02008*
         NI    LCRFLAG,B'11110111'                                0210
*          END;                         /* END MSG LOOP         X02008*
*
*         GEN(PWTO  REG=(1));            /*WRITE OUTPUT MESSAGE
@9F2     EQU   *                                                  0212
         PWTO  REG=(1)
         DS    0H
*         GEN(BR    R7);                 /*BRANCH BACK
         BR    R7
         DS    0H
*         /************************************************************
*         GEN(EJECT);
         EJECT
         DS    0H
* /********************************************************************
* /*  EXECUTE CHANNEL PROGRAM TO CONDITION LINE
* /********************************************************************
* IOSBRTN:                               /* EXCP ROUTINE
*         RESTRICT(R6);
*         /* SAVE REGS
*         RESTRICT(IOSBPTR,DEVPT1,CCWADR,CDSPTR);
*         FLGA='00'X;                    /* INIT FLAG BYTE TO 0  Y02008
IOSBRTN  MVI   FLGA,X'00'                                         0217
*         FLGB='00'X;                    /* INIT FLAG BYTE TO 0  Y02008
         MVI   FLGB,X'00'                                         0218
*         FILEMSK='00'X;                 /* INIT FILE MASK TO 0  Y02008
         MVI   FILEMSK,X'00'                                      0219
*         SNSCNT='02'X;                  /* INIT SENSE COUNT=02  Y02008
         MVI   SNSCNT,X'02'                                       0220
*         CNTSNS='00'X;                 /* CLEAR TECB SNS CNT   Y02008*
         MVI   TECB+6,X'00'                                       0221
*         CNTINT='00'X;                 /* CLEAR TECB INT CNT   Y02008*
         MVI   TECB+7,X'00'                                       0222
*         SIOCC='00'X;                  /* ZERO I/O CC IN TECB  Y02008*
         MVI   TECB+8,X'00'                                       0223
*         OUTBUFR=OUTBUFR&&OUTBUFR;     /* ZERO CSW,SNS IN TECB Y02008*
         XC    TECB+13(1),TECB+13                                 0224
*         TECBPTRX=ADDR(TECB);           /* PTR TO TECB FOR EVENTY02008
         LA    @F,TECB                                            0225
         ST    @F,TECBPTRX                                        0225
*         IOCCWADR=CAWPTR;               /* ADDRESS OF CCWS,ENABLY02008
         MVC   IOCCWADR(4),CAWPTR                                 0226
*         DVTPTR=DEVPT1;                 /* ADDRESS OF DEVICE TABY02008
         ST    @3,DVTPTR                                          0227
*         FLGA=FLGA×'20'X;              /* INVOKE GDP IO FCTN   Y02008*
         OI    FLGA,X'20'                                         0228
*         FLGB=FLGB×'80'X;              /* INTERNAL CALL FLAG   Y02008*
         OI    FLGB,X'80'                                         0229
*
*         IF VIRTUAL='1'B                /* IS OLTEP IN VIRTUAL? Y02008
*          THEN                          /* YES, SET BIT TELLING Y02008
         TM    A00012,B'00000010'                                 0230
         BC    12,@9F1                                            0230
*         FLGB=FLGB×'20'X;              /* VIRTUAL CCWS         Y02008*
         OI    FLGB,X'20'                                         0231
*
*         R15=IORTNADR;                  /* ADDRESS IO EFFECTOR  Y02008
@9F1     L     @F,IORTNADR                                        0232
*         GEN(BALR R14,R15);             /* GO PERFORM ENABLE    Y02008
         BALR R14,R15
         DS    0H
*
*         TIME=0120;                     /*SET TIMER FOR 2 MIN   Y02008
         MVC   WAITLIST+13(2),@D1                                 0234
*         /*     CHECK CDS
*         IF OPERCALL='1'B THEN          /*OPERATOR CALL ?
         TM    LCRFLAG,B'01000000'                                0235
         BC    12,@9F0                                            0235
*           DO;                          /*YES
*             TIME=0240;                 /*SET TIMER FOR 4 MIN   Y02008
         MVC   WAITLIST+13(2),@D2                                 0237
*             /* SAVE REG
*             RESTRICT(R1);
*             R1=IFDXX7;                 /*SET MSG PTR
         L     @1,12(0,@9)                                        0239
*             /* CHECK CDS
*             IF TELNO='1'B THEN         /*DIAL DIGITS IN CDS
         TM    LCRFLAG,B'10000000'                                0240
         BC    12,@9EF                                            0240
*               R1=IFDXX8;               /*YES - SET MSG PTR
         L     @1,16(0,@9)                                        0241
*             GEN(BAL   R7,MSGRTN);      /*BRANCH TO OUTPUT MESSAGE
@9EF     EQU   *                                                  0242
         BAL   R7,MSGRTN
         DS    0H
*             /* FREE REG
*             RELEASE(R1);
*           END;
*
*         R1=ADDR(WAITLIST);             /* ADDRESS WAIT LIST    Y02008
@9F0     LA    @1,WAITLIST                                        0245
*         R14=ADDR(CHKENABL);            /* ADDR OF RETURN POINT Y02008
         LA    @E,CHKENABL                                        0246
*         R15=TAB28;                     /* ADDRESS TRANS MNGR   Y02008
         L     @F,TAB28                                           0247
*         GO TO R15;                     /* PERFORM WAIT I/O     Y02008
         BCR   15,@F                                              0248
*
* CHKENABL:
*         WAITRC=R15;                    /* SAVE WAITIO RET CODE Y02008
CHKENABL ST    @F,WAITRC                                          0249
*         IF WAITRC='08'X                /* DID EVENT TIMEOUT?   Y02008
*          THEN                          /* YES, MUST PRINT MSG  Y02008
         LA    @F,X'08'                                           0250
         C     @F,WAITRC                                          0250
         BC    07,@9EE                                            0250
*           DO;                          /* AND RE ISSUE EVENT   Y02008
*           IF OPERCALL='1'B THEN        /* OPERATOR CALL ?      Y02008
         TM    LCRFLAG,B'01000000'                                0252
         BC    12,@9ED                                            0252
*             DO;                        /*YES -
*               R1=IFDXXA;               /*SET MSG PTR
         L     @1,24(0,@9)                                        0254
*               GEN(BAL   R7,MSGRTN);    /*BRANCH TO OUTPUT MESSAGE
         BAL   R7,MSGRTN
         DS    0H
*             END;
*             UNSUCCES='1'B;             /*SET ENABLE FAILED FLAG ON
@9ED     OI    LCRFLAG,B'00010000'                                0257
*             GEN(BR    R6);             /*BRANCH BACK
         BR    R6
         DS    0H
*           END;
*         GEN(EJECT);
@9EE     EQU   *                                                  0260
         EJECT
         DS    0H
* /********************************************************************
* /*  LINE CONNECTION CHANNEL PROGRAM ERROR RECOVERY AND OUTPUT
* /********************************************************************
*
*         IF SIOCC='F3'X                 /* IF SIO RESULTED IN   Y02008
*          THEN                          /* CC==3 THEN DEV IS NOTY02008
         CLI   TECB+8,X'F3'                                       0261
         BC    07,@9EC                                            0261
*           DO;                          /* MUST PRINT MESSAGE   Y02008
*            R1=IFD408I;                 /* ADDRESS ERROR MESSAGEY02008
         L     @1,32(0,@9)                                        0263
*            ERRORLINE=DEVADDR1;         /* PUT LINE ADDR IN MSG Y02008
         MVC   12(8,@1),0(@3)                                     0264
*            GEN (BAL  R7,MSGRTN);       /* PRINT MESSAGE        Y02008
         BAL  R7,MSGRTN
         DS    0H
*            UNSUCCES='1'B;              /* UNSUCCESSFUL ENABLE  Y02008
         OI    LCRFLAG,B'00010000'                                0266
*            GEN( BR R6);                /* RETURN TO MAINLINE   Y02008
          BR R6
         DS    0H
*           END;                         /* END MSG OUTPUT       Y02008
*
*         IF UNITCHCK='1'B ×             /* IF UNIT CHECK OCCURD Y02008
*            TECBFLGB>'00'X &            /* OR STATUS SHOWS OTHR Y02008
*            TECBFLGB<'80'X              /* EXCEPTIONAL CONDITIONY02008
*          THEN                          /* MUST OUTPUT CSW AND  Y02008
@9EC     TM    TECB+16,B'00000010'                                0269
         BC    01,@9EB                                            0269
         CLI   TECB+17,X'00'                                      0269
         BC    12,@9EA                                            0269
         CLI   TECB+17,X'80'                                      0269
         BC    10,@9E9                                            0269
*           DO;                          /* POSSIBLE SENSE INFO. Y02008
*             HEX=HEX&&HEX;              /*CLEAR HEX SAVE AREA
@9EB     XC    HEX(17),HEX                                        0271
*             HEXCSW=CSW1;               /* SAVE CSW
         MVC   HEX(7),TECB+13                                     0272
*             /* CHECK CSW
*             IF UNITCHCK='1'B THEN      /*UNIT CHECJ FLAG ON
         TM    TECB+16,B'00000010'                                0273
         BC    12,@9E8                                            0273
*               DO;                      /*YES -
*                 HEXSENSE=TSNS1;        /*SAVE IOB SENSE BYTES  Y02008
         MVC   HEX+15(2),TECB+23                                  0275
*                 /* CHECK CDS
*                 IF OPERCALL='0'B & RETRY='0'B
*                   THEN                 /* YES
         TM    LCRFLAG,B'01000000'                                0276
         BC    05,@9E7                                            0276
         TM    LCRFLAG,B'00100000'                                0276
         BC    05,@9E6                                            0276
*
*                    DO;                 /*
*                     RETRY='1'B;        /*SET RETRY FLAG ON
         OI    LCRFLAG,B'00100000'                                0278
*                     GOTO IOSBRTN;      /*BRANCH BACK TO RETRY  Y02008
         BC    15,IOSBRTN                                         0279
*                    END;
*
*               END;                     /* END UNIT CHECK DO-ENDY02008
@9E6     EQU   *                                                  0281
@9E7     EQU   *                                                  0281
*
*             CCWADR=CCWPLUS8;           /*PTR TO COMMAND ADDR INY02008
@9E8     MVC   @TEMP3+1(3),TECB+13                                0282
         L     @4,@TEMP3                                          0282
*             /* DECREMENT CCW PTR
*             CCWADR=CCWADR-8;           /*POINT TO FAILING CCW
         SH    @4,@D3                                             0283
*             HEXCCW=FAIL;               /*SAVE FAILED CCW
         MVC   HEX+7(8),0(@4)                                     0284
*             RESTRICT(R1);
*             R1=ADDR(CONVERT);          /*SET PTR TO CONVERT LIST
         LA    @1,CONVERT                                         0286
*             R15=TAB28;                 /*SET PTR TO CONVERT MODULE
         L     @F,TAB28                                           0287
*             GEN(BALR  R14,R15);        /*BRANCH TO CONVERT MODULE
         BALR  R14,R15
         DS    0H
*             R1=IFDXX9;                 /*SET MSG PTR
         L     @1,20(0,@9)                                        0289
*             CCWFAIL=DECCCW;            /*MOVE FAILED CCW INTO MSG
         MVC   36(16,@1),DEC+14                                   0290
*             GEN(BAL   R7,MSGRTN);      /*BRANCH TO OUTPUT MESSAGE
         BAL   R7,MSGRTN
         DS    0H
*             /* PTR TO ERROR MSG
*             R1=IFDXXB;
         L     @1,28(0,@9)                                        0292
*             STATUS=DECCSW;             /*MOVE STATUS INTO ERROR MSG
         MVC   18(14,@1),DEC                                      0293
*             /* CHECK CSW
*             IF UNITCHCK='1'B THEN      /*UNIT CHECK ?
         TM    TECB+16,B'00000010'                                0294
         BC    12,@9E5                                            0294
*               SENSE=DECSENSE;          /*YES - MOVE SENSE BYTES INTO
         MVC   37(4,@1),DEC+30                                    0295
*             /* BRANCH TO MESSAGE ROUTINE
*             GEN( BAL   R7,MSGRTN);
@9E5     EQU   *                                                  0296
          BAL   R7,MSGRTN
         DS    0H
*             /* FREE REG
*             RELEASE(R1);
*           END;
*
*         /* IHIS POINT REACHED IF LINE ENABLED OK               Y02008
*
*         IF TECBFLGA='0C'X &            /* IF CHAN/DEV END ARE  Y02008
*            TECBFLGB='00'X              /* ONLY STATUS INDICATRSY02008
*          THEN                          /* LINE IS ENABLED      Y02008
@9E9     EQU   *                                                  0299
@9EA     CLI   TECB+16,X'0C'                                      0299
         BC    07,@9E4                                            0299
         CLI   TECB+17,X'00'                                      0299
         BC    07,@9E3                                            0299
*           GEN(BR R6);                  /* RETURN TO MAINLINE   Y02008
         BR R6
         DS    0H
*
*         UNSUCCES='1'B;                /* UNSUCCESSFUL ENABLE  Y02008*
@9E3     EQU   *                                                  0301
@9E4     OI    LCRFLAG,B'00010000'                                0301
*         GEN( BR R6);                  /* BRANCH BACK TO MAINLINE    *
          BR R6
         DS    0H
*         END IFDOLT73;
@EL01    L     @D,4(0,@D)                                         0303
         L     @E,12(0,@D)                                        0303
         LM    @0,@C,20(@D)                                       0303
         BCR   15,@E                                              0303
@DATA1   EQU   *
@0       EQU   00                  EQUATES FOR REGISTERS 0-15
@1       EQU   01
@2       EQU   02
@3       EQU   03
@4       EQU   04
@5       EQU   05
@6       EQU   06
@7       EQU   07
@8       EQU   08
@9       EQU   09
@A       EQU   10
@B       EQU   11
@C       EQU   12
@D       EQU   13
@E       EQU   14
@F       EQU   15
@D1      DC    H'120'
@D2      DC    H'240'
@D3      DC    H'8'
@MVC     MVC   0(1,@A),0(@E)
@OC      OC    0(1,@A),0(@E)
@V1      DC    V(IFDMSG73)
         DS    0F
         DS    0D
@DATA    EQU   *
@SAV001  EQU   @DATA+00000000      72 BYTE(S) ON WORD
R0       EQU   00000000            FULLWORD INTEGER REGISTER
R1       EQU   00000001            FULLWORD POINTER REGISTER
R2       EQU   00000002            FULLWORD POINTER REGISTER
R6       EQU   00000006            FULLWORD INTEGER REGISTER
R7       EQU   00000007            FULLWORD INTEGER REGISTER
R9       EQU   00000009            FULLWORD POINTER REGISTER
R14      EQU   00000014            FULLWORD POINTER REGISTER
R15      EQU   00000015            FULLWORD POINTER REGISTER
DEVPT1   EQU   00000003            3  BYTE  POINTER REGISTER
DEVPT2   EQU   00000004            3  BYTE  POINTER REGISTER
CCWADR   EQU   00000004            3  BYTE  POINTER REGISTER
CDSPTR   EQU   00000005            FULLWORD POINTER REGISTER
VARFLDPT EQU   00000007            3  BYTE  POINTER REGISTER
IOSBPTR  EQU   00000008            FULLWORD POINTER REGISTER
LCRFLAG  EQU   @DATA+00000072      1 BYTE(S)
TELNO    EQU   LCRFLAG+00000000    1 BIT(S)
OPERCALL EQU   LCRFLAG+00000000    1 BIT(S)
RETRY    EQU   LCRFLAG+00000000    1 BIT(S)
UNSUCCES EQU   LCRFLAG+00000000    1 BIT(S)
HDRMSG   EQU   LCRFLAG+00000000    1 BIT(S)
R1SAVE   EQU   @DATA+00000076      FULLWORD INTEGER
CAWPTR   EQU   @DATA+00000080      FULLWORD POINTER
FAIL     EQU   00000000            8 BYTE(S)
DEC      EQU   @DATA+00000084      40 BYTE(S) ON WORD
DECCSW   EQU   DEC+00000000        14 BYTE(S)
DECCCW   EQU   DEC+00000014        16 BYTE(S)
DECSENSE EQU   DEC+00000030        4 BYTE(S)
HEX      EQU   @DATA+00000124      17 BYTE(S) ON WORD
HEXCSW   EQU   HEX+00000000        7 BYTE(S)
A00000   EQU   HEX+00000000        3 BYTE(S)
A00001   EQU   HEX+00000003        6 BIT(S)
SAVUNITC EQU   HEX+00000003        1 BIT(S)
A00002   EQU   HEX+00000003        1 BIT(S)
A00003   EQU   HEX+00000004        1 BYTE(S)
HEXCCW   EQU   HEX+00000007        8 BYTE(S)
HEXSENSE EQU   HEX+00000015        2 BYTE(S)
CONVERT  EQU   @DATA+00000144      14 BYTE(S) ON WORD
         ORG   CONVERT+00000000
A00004   EQU   *                   2 BYTE(S)
         DC    X'0002'
A00005   EQU   *                   2 BYTE(S)
         DC    C'41'
A00006   EQU   *                   FULLWORD POINTER
         DC    AL4(HEX)
A00007   EQU   *                   FULLWORD POINTER
         DC    AL4(DEC)
A00008   EQU   *                   2 BYTE(S)
         DC    X'8011'
ONES     EQU   @DATA+00000158      80 BYTE(S)
A00009   EQU   *                   80*1 BYTE(S)
         DC    00080X'FF'
X20F0    EQU   @DATA+00000238      20 BYTE(S)
A00010   EQU   *                   20*1 BYTE(S)
         DC    00020X'F0'
CODE     EQU   @DATA+00000258      7 BYTE(S)
A00011   EQU   CODE+00000000       1 BYTE(S)
         ORG   CODE+00000001
SETMODE  EQU   *                   2*1 BYTE(S)
         DC    00002X'23'
SADXX    EQU   *                   4*1 BYTE(S)
         DC    X'13'
         DC    X'17'
         DC    X'1B'
         DC    X'1F'
MSGPTR   EQU   00000000            36 BYTE(S) ON WORD
IFDXX1   EQU   MSGPTR+00000000     FULLWORD POINTER
IFDXX2   EQU   MSGPTR+00000004     FULLWORD POINTER
IFDXX3   EQU   MSGPTR+00000008     FULLWORD POINTER
IFDXX7   EQU   MSGPTR+00000012     FULLWORD POINTER
IFDXX8   EQU   MSGPTR+00000016     FULLWORD POINTER
IFDXX9   EQU   MSGPTR+00000020     FULLWORD POINTER
IFDXXA   EQU   MSGPTR+00000024     FULLWORD POINTER
IFDXXB   EQU   MSGPTR+00000028     FULLWORD POINTER
IFD408I  EQU   MSGPTR+00000032     FULLWORD POINTER
MSG2     EQU   00000000            64 BYTE(S) ON WORD
A00014   EQU   MSG2+00000000       12 BYTE(S)
A00015   EQU   MSG2+00000012       25 BYTE(S)
LINE     EQU   MSG2+00000037       8 BYTE(S)
A00016   EQU   MSG2+00000045       11 BYTE(S)
NAME     EQU   MSG2+00000056       8 BYTE(S)
MSG8     EQU   00000000            65 BYTE(S) ON WORD
A00017   EQU   MSG8+00000000       4 BYTE(S)
A00018   EQU   MSG8+00000004       41 BYTE(S)
DDGT     EQU   MSG8+00000045       20 BYTE(S)
MSG9     EQU   00000000            52 BYTE(S) ON WORD
A00019   EQU   MSG9+00000000       4 BYTE(S)
A00020   EQU   MSG9+00000004       32 BYTE(S)
CCWFAIL  EQU   MSG9+00000036       16 BYTE(S)
MSG11    EQU   00000000            41 BYTE(S) ON WORD
A00021   EQU   MSG11+00000000      4 BYTE(S)
A00022   EQU   MSG11+00000004      14 BYTE(S)
STATUS   EQU   MSG11+00000018      14 BYTE(S)
A00023   EQU   MSG11+00000032      5 BYTE(S)
SENSE    EQU   MSG11+00000037      4 BYTE(S)
MSG408   EQU   00000000            70 BYTE(S) ON WORD
A00024   EQU   MSG408+00000000     12 BYTE(S)
ERRORLIN EQU   MSG408+00000012     8 BYTE(S)
A00025   EQU   MSG408+00000020     50 BYTE(S)
WAITLIST EQU   @DATA+00000268      1 BYTE(S) ON WORD
         ORG   WAITLIST+00000000
XMGR     EQU   *                   1 BYTE(S)
         DC    X'00'
LVL      EQU   *                   1 BYTE(S)
         DC    X'02'
MODID    EQU   *                   2 BYTE(S)
         DC    C'36'
TECBPTR  EQU   *                   FULLWORD POINTER
         DC    AL4(TECB)
CDSDATA  EQU   *                   FULLWORD POINTER
         DC    XL4'00'
FLG      EQU   *                   1 BYTE(S)
         DC    X'80'
WAITYES  EQU   WAITLIST+00000012   1 BIT(S)
TIME     EQU   WAITLIST+00000013   2 BYTE(S)
WAITRC   EQU   @DATA+00000284      FULLWORD INTEGER
TECB     EQU   @DATA+00000288      1 BYTE(S)
         ORG   TECB+00000000
FLDCNT   EQU   *                   1 BYTE(S)
         DC    X'01'
FLDSIZE  EQU   *                   1 BYTE(S)
         DC    X'0C'
A00026   EQU   *                   1 BYTE(S)
         DC    X'00'
SNSIZE   EQU   *                   1 BYTE(S)
         DC    X'05'
FLG1     EQU   *                   1 BYTE(S)
         DC    X'00'
SNSFIELD EQU   *                   1 BYTE(S)
         DC    X'01'
CNTSNS   EQU   *                   1 BYTE(S)
         DC    X'00'
CNTINT   EQU   *                   1 BYTE(S)
         DC    X'00'
SIOCC    EQU   *                   1 BYTE(S)
         DC    X'00'
A00027   EQU   *                   1 BYTE(S)
         DC    X'00'
DEVAD    EQU   *                   2 BYTE(S)
         DC    X'0000'
A00028   EQU   *                   1 BYTE(S)
         DC    X'00'
OUTBUFR  EQU   *                   12*1 BYTE(S)
         DC    00012X'00'
CSW1     EQU   TECB+00000013       7 BYTE(S)
CCWPLUS8 EQU   TECB+00000013       3 BYTE(S)
TECBFLGA EQU   TECB+00000016       1 BYTE(S)
A00029   EQU   TECB+00000016       4 BIT(S)
CHANEND  EQU   TECB+00000016       1 BIT(S)
DEVICEND EQU   TECB+00000016       1 BIT(S)
UNITCHCK EQU   TECB+00000016       1 BIT(S)
TECBFLGB EQU   TECB+00000017       1 BYTE(S)
A00030   EQU   TECB+00000020       3 BYTE(S)
TSNS1    EQU   TECB+00000023       2 BYTE(S)
A00031   EQU   00000000            56 BYTE(S) ON WORD
DEVADDR1 EQU   A00031+00000000     8 BYTE(S)
UCBADDR1 EQU   A00031+00000008     FULLWORD POINTER
A00032   EQU   A00031+00000012     1 BYTE(S)
A00033   EQU   A00031+00000012     1 BIT(S)
PRIMARY  EQU   A00031+00000012     1 BIT(S)
A00034   EQU   A00031+00000012     6 BIT(S)
A00035   EQU   A00031+00000013     2 BYTE(S)
A00036   EQU   A00031+00000015     1 BYTE(S)
LNDSBL1  EQU   A00031+00000015     1 BIT(S)
LNENBL1  EQU   A00031+00000015     1 BIT(S)
A00037   EQU   A00031+00000015     6 BIT(S)
A00038   EQU   A00031+00000016     25 BYTE(S)
A00039   EQU   A00031+00000041     1 BYTE(S)
A00040   EQU   A00031+00000041     4 BIT(S)
NMPRSNT1 EQU   A00031+00000041     1 BIT(S)
A00041   EQU   A00031+00000041     3 BIT(S)
A00042   EQU   A00031+00000042     2 BYTE(S)
SYMBNM1  EQU   A00031+00000044     8 BYTE(S)
A00043   EQU   A00031+00000052     4 BYTE(S)
A00044   EQU   00000000            176 BYTE(S) ON WORD
DEVADDR2 EQU   A00044+00000000     8 BYTE(S)
A00045   EQU   A00044+00000008     7 BYTE(S)
A00046   EQU   A00044+00000015     1 BYTE(S)
LNDSBL2  EQU   A00044+00000015     1 BIT(S)
LNENBL2  EQU   A00044+00000015     1 BIT(S)
A00047   EQU   A00044+00000015     6 BIT(S)
CHAR     EQU   A00044+00000016     40*4  BYTE  INTEGER
A00048   EQU   00000000            47 BYTE(S) ON WORD
A00049   EQU   A00048+00000000     9 BYTE(S)
A00050   EQU   A00048+00000009     1 BYTE(S)
A00051   EQU   A00048+00000009     4 BIT(S)
SYMNMFLG EQU   A00048+00000009     1 BIT(S)
A00052   EQU   A00048+00000009     2 BIT(S)
LCRFLG   EQU   A00048+00000009     1 BIT(S)
A00053   EQU   A00048+00000010     11 BYTE(S)
A00054   EQU   A00048+00000021     1 BYTE(S)
SMPRSNT  EQU   A00048+00000021     1 BIT(S)
AUTOCALL EQU   A00048+00000021     1 BIT(S)
SWITCHLN EQU   A00048+00000021     1 BIT(S)
NSWTCHLN EQU   A00048+00000021     1 BIT(S)
WORLDTRD EQU   A00048+00000021     1 BIT(S)
A00055   EQU   A00048+00000021     3 BIT(S)
A00056   EQU   A00048+00000022     1 BYTE(S)
CMDSEQ   EQU   A00048+00000023     1 BYTE(S)
VARIABLE EQU   A00048+00000024     23 BYTE(S)
A00057   EQU   00000000            21 BYTE(S) ON WORD
DIALCNT  EQU   A00057+00000000     1 BYTE(S)
DIALDGT  EQU   A00057+00000001     20 BYTE(S)
A00058   EQU   00000000            8 BYTE(S) ON WORD
A00059   EQU   A00058+00000000     4 BYTE(S)
EXIOPTR  EQU   A00058+00000004     FULLWORD POINTER
A00060   EQU   00000000            8 BYTE(S) ON WORD
DEVICE   EQU   A00060+00000000     FULLWORD POINTER
CDSADR   EQU   A00060+00000004     FULLWORD POINTER
CCWAREA  EQU   @DATA+00000328      64 BYTE(S) ON DWORD
         ORG   CCWAREA+00000000
DISABLE  EQU   *                   8 BYTE(S)
         DC    X'2F00000020000001'
TWOCCW   EQU   CCWAREA+00000008    16 BYTE(S)
WRITECCW EQU   CCWAREA+00000024    6*8 BYTE(S)
         ORG   CCWAREA+00000024
A00061   EQU   *                   1 BYTE(S)
&T       SETA  00006
.L099995 ANOP
         DC    X'01'
         DS    00007C
&T       SETA  &T-1
         AIF   (&T NE 0).L099995
         ORG   CCWAREA+00000025
A00062   EQU   *                   3  BYTE  POINTER
&T       SETA  00006
.L099994 ANOP
         DC    AL3(ONES)
         DS    00005C
&T       SETA  &T-1
         AIF   (&T NE 0).L099994
         ORG   CCWAREA+00000028
A00063   EQU   *                   4 BYTE(S)
&T       SETA  00006
.L099993 ANOP
         DC    X'E0000050'
         DS    00004C
&T       SETA  &T-1
         AIF   (&T NE 0).L099993
A00064   EQU   CCWAREA+00000072    8 BYTE(S)
         ORG   CCWAREA+00000072
A00065   EQU   *                   1 BYTE(S)
         DC    X'01'
A00066   EQU   *                   3  BYTE  POINTER
         DC    AL3(ONES)
A00067   EQU   *                   4 BYTE(S)
         DC    X'20000050'
CCW      EQU   00000000            8 BYTE(S)
A00068   EQU   CCW+00000000        1 BYTE(S)
DATAADDR EQU   CCW+00000001        3  BYTE  POINTER
A00069   EQU   CCW+00000004        4 BYTE(S)
         ORG   @DATA
         DS    00000412C
@TEMPS   DS    0F
@TEMP3   DC    F'0'
@TEMP4   DC    F'0'
LCRO     IFDCOM
A00012   EQU   CESWT7+00000000     1 BYTE(S) ON WORD
A00013   EQU   A00012+00000000     6 BIT(S)
VIRTUAL  EQU   A00012+00000000     1 BIT(S)
IOCCWADR EQU   EFCTRCB+00000000    FULLWORD POINTER
A00070   EQU   CESWTR+00000000     1 BYTE(S) ON WORD
RETAINAC EQU   A00070+00000000     1 BIT(S)
A00071   EQU   CESWTR2+00000000    1 BYTE(S) ON WORD
A00072   EQU   A00071+00000000     7 BIT(S)
DPMSGREI EQU   A00071+00000000     1 BIT(S)
@DATEND  EQU   *
@9F4     EQU   @9F3
         END   IFDOLT73
