//************************************************************
//*   INSTALL OF  TSO COMMAND PROCESSOR TO DECONCATENTATE    *
//*   (DECONCAT) DYNAMICALLY A LIST OF PREVIOUSLY DEFINED    *
//*    DATASETS.                                             *
//*----------------------------------------------------------*
//DECONCAT  EXEC ASMHCL,PARM.ASM='NOXREF,RENT',
//     PARM.LKED='MAP,RENT,XREF,LIST'
//SYSIN   DD DSN=ASFI00U.FI100.TSOSRC(DECONCAT),DISP=SHR
//LKED.SYSLMOD DD DSN=SYS1.LINKLOAD,DISP=SHR
//LKED.SYSIN  DD *
 ENTRY DECONCAT
 ALIAS DECAT
 NAME DECONCAT(R)
/*
