*        %GOTO UPTBSL ;  /*
         MACRO
         IKJUPT
.* A 0-999999                                                    S20031
***********************************************************************
*    THE USER PROFILE TABLE (UPT) IS BUILT BY THE LOGON/LOGOFF        *
*    SCHEDULER FROM INFORMATION STORED IN THE UADS AND FROM THE       *
*    LOGON COMMAND.  IT IS IN CORE SHARED BY THE TMP AND THE          *
*    LOGON/LOGOFF SCHEDULER.  CP'S AND SERVICE ROUTINES CAN MODIFY    *
*    THE UPT, BUT THEY CANNOT FREE IT.                                *
***********************************************************************
UPT      DSECT
         DS    0F
         DS    CL2      RESERVED
UPTUSER  DS    CL10     RESERVED FOR INSTALLATION USE
UPTSWS   DS    X        USERS ENVIRONMENT SWITCHES
UPTRCVR  EQU   X'80'    EDIT RECOVER OPTION IS REQUESTED DEFLT @Z40NQKG
UPTNPRM  EQU   X'40'    NO PROMPTING IS TO BE DONE
UPTMID   EQU   X'20'    PRINT MESSAGE IDENTIFIERS
UPTNCOM  EQU   X'10'    NO USER COMMUNICATION ALLOWED VIA SEND COMMAND
UPTPAUS  EQU   X'08'    PAUSE FOR '?' WHEN IN NON-INTERACTIVE MODE
UPTALD   EQU   X'04'    ATTN HAS BEEN SPECIFIED AS LINE DELETE CHAR
UPTMODE  EQU   X'02'    MODE MESSAGES DESIRED                    Y01676
UPTWTP   EQU   X'01'    WRITE TO PROGRAMMER MESSAGES DESIRED     Y02669
UPTCDEL  DS    CL1      CHAR DELETE CHARACTER
UPTLDEL  DS    CL1      LINE DELETE CHARACTER
         DS    CL1      RESERVED
UPTPREFX DS    CL7      DSNAME PREFIX                            Y02669
UPTPREFL DS    BL1      LENGTH OF DSNAME PREFIX                  Y02669
**/
         MEND
* %UPTBSL: ;
* %IF UPTSTORAGE='' %THEN              /*                   @ZA29467 */
*   %UPTSTORAGE='BASED(UPTPTR)';       /*                   @ZA29467 */
* /* *************************************************************** */
* /* THE USER PROFILE TABLE (UPT) IS BUILT BY THE LOGON/LOGOFF       */
* /* SCHEDULER FROM INFORMATION STORED IN THE UADS AND FROM THE      */
* /* LOGON COMMAND.  IT IS IN CORE SHARED BY THE TMP AND THE         */
* /* LOGON/LOGOFF SCHEDULER.  CP'S AND SERVICE ROUTINES CAN MODIFY   */
* /* THE UPT, BUT THEY CANNOT FREE IT.                               */
* /* *************************************************************** */
* DECLARE
*   1 UPT UPTSTORAGE,                /*                     @ZA29467 */
*    2 *        CHAR(2) BDY(WORD),   /* RESERVED                     */
*    2 UPTUSER  CHAR(10),            /* RESERVED FOR INSTALLATION    */
*    2 UPTSWS   CHAR(1),             /* USERS ENVIRONMENT SWITCHES   */
*     3 UPTRCVR  BIT(1),             /* EDIT RECOVER OPTION IS
*                                       REQUESTED DEFAULT    @Z40NQKG*/
*     3 UPTNPRM  BIT(1),             /* NO PROMPTING TO BE DONE      */
*     3 UPTMID   BIT(1),             /* PRINT MESSAGE IDENTIFIERS    */
*     3 UPTNCOM  BIT(1),             /* NO USER COMMUNICATION
*                                       ALLOWED VIA SEND COMMAND     */
*     3 UPTPAUS  BIT(1),             /* PAUSE FOR '?' WHEN IN NON-
*                                       INTERACTIVE MODE             */
*     3 UPTALD   BIT(1),             /* ATTN HAS BEEN SPECIFIED AS
*                                       THE LINE DELETE CHARACTER    */
*     3 UPTMODE  BIT(1),             /* MODE MESSAGES DESIRED  Y01676*/
*     3 UPTWTP   BIT(1),             /* WRITE TO PROGRAMMER    Y02669*/
*                                    /* MSGS ARE TO BE PUT OUT Y02669*/
*    2 UPTCDEL  CHAR(1),             /* CHAR DELETE CHARACTER        */
*    2 UPTLDEL  CHAR(1),             /* LINE DELETE CHARACTER        */
*    2 *        CHAR(1),             /* RESERVED                     */
*    2 UPTPREFX CHAR(7),             /* DSNAME PREFIX          Y02669*/
*    2 UPTPREFL PTR(8);              /* DSNAME PREFIX LENGTH   Y02669*/
