//LKEDSHOW  JOB SHOW38J,CLASS=A,MSGCLASS=A,COND=(0,NE)
//*
//LKED     EXEC PGM=IEWL,
//             REGION=1024K,
//             PARM='LET,MAP,XREF,LIST,TEST'
//SYSPRINT  DD SYSOUT=*
//SYSLMOD   DD DSN=JMM.PDS.LOAD,DISP=SHR
//SYSLIN    DD DSN=CBT.CBTxxx.FILE052.PDS,DISP=SHR
//          DD *
 NAME SHOWMVS(R)
//*
//SHOWMVS  EXEC PGM=SHOWMVS
//STEPLIB   DD DSN=JMM.PDS.LOAD,DISP=SHR
//SYSPRINT  DD SYSOUT=*
//
