
                             F L S M F C A T


         This utility is intended to list catalog activity at the
         dataset level for batch jobs, started tasks, and TSO users
         on the MVS system.  It provides a flexible selection and
         sort mechanism to tailor the report.  The following
         information can be provided for each selected catalog
         update event:

         JOBNAME   - The name of the batch job, task, or TSO user.

         DATE      - The Julian date that the catalog update occurred.

         TIME      - The time of day that the catalog update occurred.

         SYSID     - The name of the MVS system which processed the
                     catalog update request.

         OPERATION - The type of catalog update event which was
                     recorded.

         DSTYPE    - The type of dataset catalog entry which was
                     being updated.

         DSNAME    - The name of the dataset catalog entry which was
                     being updated.

         TYPE      - The job type T (test) or P (production) for the
                     job which updated the catalog.

         CATNAME   - The name of the catalog which was updated.

         DAYOFWEEK - The day of the week, SUN - SAT, that the catalog
                     update occurred.  It is based upon the DATE.



                                    J C L


          //stepname EXEC PGM=FLSMFCAT
          //SYSPRINT DD  SYSOUT=*
          //SMFIN    DD  DSN=input.SMF.dataset.name,DISP=SHR
          //SYSIN    DD  *                optional control dataset
          control statements


          SMF Dataset Names

            SYS2.SYS0X010.SMFDALY         disk - todays SMF
            SYS2.SYS0X120.SMFDAYY         disk - yesterdays SMF
            TCAT.SF.SYS0X120.SMFDAILY     tape - daily SMF
            TCAT.SYS1X010.FILE1           tape - weekly SMF


         The SYSIN file and any control statements are optional.  If
         neither is present, then all catalog activity for all jobs
         is included in the report.  Note that this can be a huge
         report since all datasets which are being created, updated
         and deleted for every batch job, started task, and TSO user
         will be listed.  It is anticipated that this report will
         usually be limited by specific control statements which
         will specify which of the activity will be included on the
         report.  Following is a list of the input control
         statements.  A detailed description of each entry will
         follow this list.

         An asterisk in front of an option denotes that up to 1000
         of these statements may be entered as selection criteria.



                                O P T I O N S


           * JOBName/JOBNm=jjjjjjjj(nn)
           * EXJobname/XJobname/EXJobnm/XJobnm=jjjjjjjj(nn)
           * DATE=yy.ddd:yy.ddd
           * TIme=hh.mm:hh.mm
           * SYstem/SYsid=ssss
           * EXSystem/XSystem/EXSysid/XSysid=ssss
           * DSName/DATAset=dddddddddddddddd
           * EXDSname/XDSname/EXDAtaset/XDAtaset=dddddddddddddddd
           * Catname/Catalog=dddddddddddddddd
           * EXCatname/XCatname/EXCatalog/XCatalog=dddddddddddddddd
             Operation=oooooooo
             DSType=tttttttt
             JOBType/JType/TYpe=T/P
             STopafter/STopcount/STopcnt=nnnnnnnnn
             SUnday
             Monday
             TUesday
             WEDnesday
             THursday
             FRiday
             SAturday
             WEEKDay
             WEEKEnd
             ALldays/EVeryday
             NOSUnday
             NOMonday
             NOTUesday
             NOWEDnesday
             NOTHursday
             NOFriday
             NOSAturday
             NOWEEKDay
             NOWEEKEnd
             SOrt=OPT1,OPT2,OPT3,OPT4,OPT5
                 JOBName/JOBNm
                 DATE
                 TIme
                 SYstem/SYsid
                 DSName/DATAset
                 Catname/Catalog
                 Operation
                 DType/DSType
                 JOBType/JType/TYpe
                 DAYoftheweek

             Note that each sort option can be suffixed by "(A)" or
             "(D)" for ascending or descending sort sequence.  The
             default is "(A)" for ascending

             Print=FIELD1,FIELD1,FIELD3, ... FIELD.

                 JOBName/JOBNm
                 DATE
                 TIme
                 SYstem/SYsid
                 DSName/DATAset
                 Catname/Catalog
                 Operation
                 DType/DSType
                 JOBType/JType/TYpe
                 DAYoftheweek

             The field names listed on the PRINT statement will be
             printed in the order given.

             More than one PRINT statement can be used if needed
             because of the number of fields desired.

             Some of the options have more than one spelling.  Also
             many of the options are allowed to be abbreviated to
             a shorted name as long as it remains unique.  That it,
             as long as another option could not also be abbreviated
             to the same name.



                    D E T A I L E D    D E S C R I P T I O N


         1)  JOBNAME=jjjjjjjj(nn)
             WHERE jjjjjjjj is a 1 to 8 character jobname
                   nn is the starting position within the full jobname
                   to be used for selection

             ALIASES JOBNM

             Up to 1000 JOBNAME control statements may be entered.

             Select only catalog activity for jobs whose name
             matches the specified name.  An optional index value
             can be specified to indicate that the specified name
             starts other than in position 1 of the job name.  A
             name of less than 8 characers is assumed to be generic.
             That is, any job which starts with the specified
             characters will be selected.  Note that jobs selected
             by this statement may be excluded by an EXJOBNAME
             statement.

         2)  EXJOBNAME=jjjjjjjj(nn)
             WHERE jjjjjjjj is a 1 to 8 character jobname
                   nn is the starting position within the full jobname
                   to be excluded from selection

             ALIASES EXJOBNM, XJOBNAME, XJOBNM

             Up to 1000 EXJOBNAME control statements may be entered.

             Exclude all catalog activity for jobs whose name
             matches the specified name.  This will exclude even
             those jobs which may have been selected by a JOBNAME
             statement.  An optional index value can be specified to
             indicate that the specified name starts other than in
             position 1 of the job name.  A name of less than 8
             characers is assumed to be generic.  That is, any job
             which starts with the specified characters will be
             excluded.

         3)  DATE=yy.ddd:yy.ddd
             WHERE yy.ddd is the Julian start date
                   yy.ddd:yy.ddd is the Julian start:end date to be
                                 used for selection

             ALIASES *NONE*

             Up to 1000 DATE range control statements may be entered.

             Select only catalog activity which occurred on or after
             the specified date if one date is specified or occurred
             within the date range if two dates are specified.

         4)  TIME=hh.mm:hh.mm
             WHERE hh.mm is the start time
                   hh.mm:hh.mm is the start:end time to be used for
                               selection

             ALIASES *NONE*

             Up to 1000 TIME range control statements may be entered.

             Select only catalog activity which occurred on or after
             the specified time of day if one time is specified or
             occurred within the time range if two times are
             specified.

         5)  SYSTEM=ssss
             WHERE ssss is the 4 character SMF system ID to be
                   used for selection.

             ALIASES SYSID

             Up to 1000 SYSID control statements may be entered.

             Select only catalog activity for jobs which executed on
             the specified system.  If specified, this must be an
             exact match on the assigned SMF system name.  This only
             has value when the input data was created on multiple
             MVS systems.

         6)  EXSYSTEM=ssss
             WHERE ssss is the 4 character SMF system ID to be
                   excluded from selection.

             ALIASES EXSYSID, XSYSTEM, XSYSID

             Up to 1000 EXSYSID control statements may be entered.

             Exclude catalog activity for jobs which executed on the
             specified system.  This will exclude even those entries
             which may have been selected by a SYSID statement.  If
             specified, this must be an exact match on the assigned
             SMF system name.  This only has value when the input
             data was created on multiple MVS systems.

         7)  DSNAME=dddddddddddddddd
             WHERE dddddddddddddddd is the 1 to 44 character dataset
                   name to be used for selection.

             ALIASES DATASET

             Up to 1000 DSNAME control statements may be entered.

             Select only catalog activity affecting datasets with
             the specified name.  This name is assumed to be
             generic.  That is, any dataset name which starts with
             the specified characters will be selected.

         8)  EXDSNAME=dddddddddddddddd
             WHERE dddddddddddddddd is the 1 to 44 character dataset
                   name to be excluded from selection.

             ALIASES EXDATASET, XDSNAME, XDATASET

             Up to 1000 EXDSNAME control statements may be entered.

             Exclude catalog activity affecting datasets with the
             specified name.  This name is assumed to be generic.
             That is, any dataset name which starts with the
             specified characters will be excluded even if the entry
             has been selected by a DSNAME statement.

         9)  CATNAME=dddddddddddddddd
             WHERE dddddddddddddddd is the 1 to 44 character name of
                   the catalog being updated to be used for selection.

             ALIASES DATASET

             Up to 1000 CATNAME control statements may be entered.

             Select only catalog activity affecting catalogs with
             the specified name.  This name is assumed to be
             generic.  That is, any catalog update for a catalog
             which starts with the specified characters will be
             selected.

         10) EXCATNAME=dddddddddddddddd
             WHERE dddddddddddddddd is the 1 to 44 character name of
                   the catalog being updated to be excluded from
                   selection.

             ALIASES XCATNAME, EXCATALOG, XCATALOG

             Up to 1000 EXCATNAME control statements may be entered.

             Exclude only catalog activity affecting catalogs with
             the specified name.  This name is assumed to be
             generic.  That is, any catalog update for a catalog
             which starts with the specified characters will be
             excluded.

         11) OPERATION=oooooooo
             WHERE oooooooo is the 1 to 8 character name of catalog
                   update operation.  These include the following:

             A)  DEFine
             B)  DELete / Uncatalog
             C)  Scratch
             D)  Rename
             E)  Alter

             ALIASES *NONE*

             As many OPERATION statements can be entered as needed.

             Delete and uncatalog activity is different from scratch
             activity in that tapes get uncataloged but not scratched.
             Two OPERATION statements may be entered to include both
             Uncatalog and Scratch activity.

         12) DSTYPE=dddddddd
             WHERE dddddddd is the type of dataset affected by the
                   catalog activity.  They include the following:

             A)  Nonvsam / Nvsam
             B)  Gdg
             C)  Cluster
             D)  Dataset
             E)  AIx
             F)  Index
             G)  Mcat / Mastercat
             H)  PAGespc
             I)  PATh
             J)  UCat / USercat
             K)  Volume
             L)  ALias
             M)  UPgrage
             N)  UNknown

             ALIASES DTYPE, DATASETTYPE

             As many DSTYPE statements can be entered as needed.

             Select only catalog activity for the specified type of
             dataset.

         13) JOBTYPE=T/P
             WHERE T or P is the job type.  It will be a "T" for test
                   jobs or "P" for production jobs.

             ALIASES JTYPE/TYPE

             Select only catalog activity which was performed by
             jobs of one of the specified type.  This will be either
             T for test jobs or P for production jobs.  Note that
             all started tasks and TSO users are considered
             production.  All batch jobs with a numeric second
             position will be considered test jobs.

         14) STOPAFTER=nnnnnnnnn
             WHERE nnnnnnnnn is the number of items to include
                   on the report.  It will be the first nnnnnn
                   input type 61, 65, or 66 records if the SORT option
                   is not taken or the first nnnnnn records of the
                   requested sort sequence.

             ALIASES STOPCOUNT/STOPCNT

             This option limits the report to only printing the first
             nnnnnnnnn selected entries.  This is after any other
             optional control statements may have eliminated any
             entries.  This will be the first nnnnn selectable type 61
             65, or 66 records if the SORT option is not taken or the
             first nnnnn records in the sort sequence if the SORT
             option is taken.  The value must not exceed 9 digits.

         25) SUNDAY/NOSUNDAY
             MONDAY/NOMONDAY
             TUESDAY/NOTUESDAY
             WEDNESDAY/NOWEDNESDAY
             THURSDAY/NOTHURSDAY
             FRIDAY/NOFRIDAY
             SATURDAY/NOSATURDAY
             WEEKDAY/NOWEEKDAY
             WEEKEND/NOWEEKEND
             ALLDAYS/EVERYDAY

             These control statements, when used in combination, will
             select data based upon the day of the week.  They are
             processed in the order received.  No data is automatically
             included.  At least one "including" statement must be
             entered if any of these statements are entered.  If none
             of these statements are used, all days are selected.

             Day of the week selection involves turning on and off
             the specified or implied days of the week.  The resulting
             list of days of the week are used for selection.  The
             control statements are processed in the order received.
             A control statement can specify or imply a day or group
             of days and a later one can negate it.  It is the final
             list of days that is used.  If the final list does not
             include any days, an error message is issued.

         26) SORT=OPT1,OPT2,OPT3,OPT4,OPT5
             Where sorting of the input data is requested in the
             order in which the following options are listed:

             A)  CATNAME/CATALOG
             B)  DATE
             C)  DAYOFTHEWEEK
             D)  DSNAME/DATASET
             E)  DSTYPE/DTYPE/DATASETTYPE
             F)  JOBNAME/JOBNM
             G)  JOBTYPE/JTYPE/TYPE
             H)  OPERATION
             I)  SYSTEM/SYSID
             J)  TIME

             Note that each keyword can be suffixed by "(A)" or
             "(D)" for ascending or descending sort sequence.
             The default is "(A)" for ascending

             A maximum of five of the above options may be made
             on a given run.

             If an option is not specified, no sorting on that
             field will be made.

             Sorting on DAYOFTHEWEEK will sort Sunday first through
             Saturday which will be last.

         27) PRINT=FIELD1,FIELD2,FIELD3, ... FIELD.
             WHERE the default fields to be printed are being
             overridden to include only the specified field
             names.

             A)  CATNAME/CATALOG
             B)  DATE
             C)  DAYOFTHEWEEK
             D)  DSNAME/DATASET
             E)  DSTYPE/DTYPE/DATASETTYPE
             F)  JOBNAME/JOBNM
             G)  JOBTYPE/JTYPE/TYPE
             H)  OPERATION
             I)  SYSTEM/SYSID
             J)  TIME

             Only as many field names can be entered whose values
             will fit on a 133 character print line.

             More than one PRINT statement can be used if a large
             number of field names is being specified.

             If a PRINT statement is not included, the following
             fields will be printed:

             JOBNAME,DATE,TIME,SYSID,OPERATION,DSTYPE,DSNAME,
             JOBTYPE

        Many of the error messages refer to errors on optional control
        statements.  The control statement is always written to the
        SYSPRINT report file prior to performing syntax checking.  The
        last control statement printed will be the one containing the
        specified error.




                E R R O R    M E S S A G E S   I S S U E D


    1)  SMF3000 - OPTIONAL SYSIN DD STATEMENT NOT SPECIFIED, NO
                  OPTIONS SPECIFIED

        The SYSIN file is used to enter optional control statements.
        Since the file was not defined, the report will include all
        job steps in the input sequence.

    2)  SMF3001 - INVALID KEYWORD ON INPUT SYSIN CARD

        ABEND U001

        An invalid keyword was entered on an optional control
        statement.

    3)  SMF3002 - INVALID JOBNAME VALUE ON SYSIN CARD - MUST 1 TO 8
                  ALPHANUMERIC CHARACTERS

        ABEND U002

        The specified jobname must be 1 to 8 characters long.

    4)  SMF3003 - INVALID JOBNAME VALUE ON SYSIN CARD - INDEX FIELD
                  WAS NOT PRECEDED BY THE JOBNAME

        ABEND U003

        The offset index specification on thejobname must be preceded
        by a jobname value.

    5)  SMF3004 - INVALID JOBNAME VALUE ON SYSIN CARD - JOBNAME
                  EXCEEDS 8 CHARACTERS

        ABEND U004

        The specified jobname must be 1 to 8 characters long.

    6)  SMF3005 - INVALID JOBNAME VALUE ON SYSIN CARD - INDEX LENGTH
                  EXCEEDS 2 CHARACTERS

        ABEND U005

        The specified jobname offset index was more than 2 digits long.
        The index value must be 1 to 2 numeric digits.

    7)  SMF3006 - INVALID JOBNAME VALUE ON SYSIN CARD - INDEX VALUE
                  IS NOT NUMERIC

        ABEND U006

        The specified jobname offset index was not numeric.  The index
        value must be 1 to 2 numeric digits.

    8)  SMF3007 - INVALID DATE VALUE ON SYSIN CARD - BEGIN DATE NOT IN
                  THE FORM YY.DDD

        ABEND U007

        The specified beginning JULIAN date is syntactically invalid.
        It was not a 2 digit year followed by a 3 digit day value
        separated by a ".".

    9)  SMF3008 - INVALID DATE VALUE ON SYSIN CARD - BEGIN YEAR NOT
                  NUMERIC

        ABEND U008

        The specified beginning JULIAN date is syntactically invalid.
        The first 2 digits must be a numeric year value.

    10) SMF3009 - INVALID DATE VALUE ON SYSIN CARD - BEGIN DAY NOT
                  NUMERIC

        ABEND U009

        The specified beginning JULIAN date is syntactically invalid.
        Digits 4 - 6 must be a numeric day value.

    11) SMF3010 - INVALID DATE VALUE ON SYSIN CARD - BEGIN DATE NOT
                  SEPARATED FROM END DATE BY ":"

        ABEND U010

        A date ramge was apparently being specified.  The beginning
        date must be separated from the ending date by a ":".

    12) SMF3011 - INVALID DATE VALUE ON SYSIN CARD - END DATE NOT IN
                  THE FORM YY.DDD

        ABEND U011

        The specified ending JULIAN date is syntactically invalid.  It
        was not a 2 digit year followed by a 3 digit day value
        separated by a ".".

    13) SMF3012 - INVALID DATE VALUE ON SYSIN CARD - END YEAR NOT
                  NUMERIC

        ABEND U012

        The specified ending JULIAN date is syntactically invalid.
        The first 2 digits must be a numeric year value.

    14) SMF3013 - INVALID DATE VALUE ON SYSIN CARD - END DAY NOT
                  NUMERIC

        ABEND U013

        The specified ending JULIAN date is syntactically invalid.
        Digits 4 - 6 must be a numeric day value.

    15) SMF3014 - INVALID TIME VALUE ON SYSIN CARD - BEGIN TIME NOT IN
                  THE FORM HH.MM

        ABEND U014

        The specified beginning time is syntactically invalid.  It was
        not a 2 digit hour followed by a 2 digit minutes value
        separated by a ".".

    16) SMF3015 - INVALID TIME VALUE ON SYSIN CARD - BEGIN HOUR NOT
                  NUMERIC

        ABEND U015

        The specified beginning time is syntactically invalid.
        The first 2 digits must be a numeric hour of the day.

    17) SMF3016 - INVALID TIME VALUE ON SYSIN CARD - BEGIN MINUTES NOT
                  NUMERIC

        ABEND U016

        The specified beginning time is syntactically invalid.  Digits
        3 - 5 must be a numeric minutes value.

    18) SMF3017 - INVALID TIME VALUE ON SYSIN CARD - BEGIN TIME NOT
                  SEPARATED FROM END TIME BY ":"

        ABEND U017

        A time ramge os apparently being specified.  The beginning
        time must be separated from the ending time by a ":".

    19) SMF3018 - INVALID TIME VALUE ON SYSIN CARD - END TIME NOT IN
                  THE FORM HH.MM

        ABEND U018

        The specified ending time is syntactically invalid.  It was
        not a 2 digit hour followed by a 2 digit minutes value
        separated by a ".".

    20) SMF3019 - INVALID TIME VALUE ON SYSIN CARD - END HOUR NOT
                  NUMERIC

        ABEND U019

        The specified ending time is syntactically invalid.  The first
        2 digits must be a numeric hour of the day.

    21) SMF3020 - INVALID TIME VALUE ON SYSIN CARD - END MINUTE NOT
                  NUMERIC

        ABEND U020

        The specified ending time is syntactically invalid.  Digits 3
        - 5 must be a numeric minutes value.

    22) SMF3021 - INVALID SYSTEM VALUE ON SYSIN CARD - MUST BE 1 TO 4
                  ALPHANUMERIC CHARACTERS

        ABEND U021

        A blank system name was entered.  It must be a 1 to 4
        character alpahanumeric name.

    23) SMF3022 - INVALID SORT SUBPARAMETER ON SYSIN CARD - NO
                  SUBPARAMETERS ENTERED

        ABEND U022

        The SORT option was specified without subparameters.  No sorting
        can be performed.

    24) SMF3023 - INVALID SORT SUBPARAMETER ON SYSIN CARD - MORE THAN
                  5 SUBPARAMETERS ENTERED

        ABEND U023

        More than 5 sort options were specified.  Five is the limit
        on concurrent sort options.

    25) SMF3024 - INVALID SORT SUBPARAMETER ON SYSIN CARD - UNKNOWN
                  SUBPARAMETER ENTERED

        ABEND U024

        An invalid sort option was specified.  Refer to the
        documentation for valid values.

    26) SMF3025 - INVALID SORT SUBPARAMETER ON SYSIN CARD -
                  SUBPARAMETERS NOT SEPARATED BY ","

        ABEND U025

        A list of sort options was entered.  Each option must be
        separated by a comma.

    27) SMF3026 - INVALID SORT SUBPARAMETER ON SYSIN CARD - NULL
                  PARAMETER ENTERED

        ABEND U026

        A null sort option was entered.  Invalid syntax.

    28) SMF3027 - INVALID DATASET TYPE ON SYSIN CARD

        ABEND U027

        The specified DSTYPE is invalid.  Only one of the following
        values may be entered:

        NONVSAM, GDG, CLUSTER, DATA, AIX, INDEX, MCAT, PAGESPC,
        PATH, UCAT, VOLUME, ALIAS, or UPGRADE

    29) SMF3028 - INVALID EXJOBNAME VALUE ON SYSIN CARD - INDEX LENGTH
                  EXCEEDS 2 CHARACTERS

        ABEND U028

        The specified excluded jobname offset index was more than 2
        digits long.  The index value must be 1 to 2 numeric digits.

    30) SMF3029 - SYSPRINT DD STATEMENT MISSING - JOB ABORTED

        ABEND U029

        The SYSPRINT DD statement is required for processing.

    31) SMF3030 - SMFIN DD STATEMENT MISSING - JOB ABORTED

        ABEND U030

        The SMFIN DD statement pointing to the input SMF data is
        required for processing.

    32) SMF3031 - INVALID KEYWORD OPERATOR ON SYSIN INPUT CARD - NOT
                  VALID FOR THIS KEYWORD

        ABEND U031

        The keyword operator is invalid.  It is either " ", "=", "<"
        or ">" and is not valid for this option.  Refer to the
        documentation for that option for allowable values.

    33) SMF3032 - NULL KEYWORD ON SYSIN INPUT CARD

        ABEND U032

        Each control statement must start in column 1.  Either the
        statement started with a blank or a keyword operator was
        entered without a preceding keyword.  Refer to the
        documentation to determine the valid syntax for the control
        statements.

    34) SMF3033 - INVALID CATALOG NAME ON SYSIN CARD - MUST BE 1 to
                  44 ALPHANUMERIC DIGITS

        ABEND U033

        The catalog name must be from 1 to 44 characters long.

    35) SMF3034 - INVALID CATALOG OPERATION NAME ON SYSIN CARD -
                  MUST BE DEFINE, DELETE, SCRATCH, RENAME, OR
                  ALTER

        ABEND U034

        The catalog operation name must be one of the specified
        values.

    36) SMF3035 - INVALID EXCATALOG NAME ON SYSIN CARD - MUST BE 1 to
                  44 ALPHANUMERIC DIGITS

        ABEND U035

        The excatalog name must be from 1 to 44 characters long.

    37) SMF3036 - INVALID EXJOBNAME VALUE ON SYSIN CARD - JOBNAME
                  EXCEEDS 8 CHARACTERS

        ABEND U036

        The specified excluded jobname must be 1 to 8 characters
        long.

    38) SMF3037 - INVALID EXJOBNAME VALUE ON SYSIN CARD - INDEX LENGTH
                  EXCEEDS 2 CHARACTERS

        ABEND U037

        The specified excluded jobname offset index was more than 2
        digits long.  The index value must be 1 to 2 numeric digits.

    39) SMF3038 - INVALID JOB TYPE VALUE ON SYSIN CARD - MUST BE "T"
                  OR "P" TO INDICATE TEST OR PRODUCTION

        ABEND U038

        The specified job type value must be a "T" or "P" to indicate
        test or production.

    40) SMF3039 - INVALID STOP COUNT VALUE ENTERED ON SYSIN CARD -
                  MUST BE 1 TO 9 NUMERIC DIGITS

        ABEND U039

        The specified stop count value must contain 1 to 9 numeric
        digits.

    41) SMF3040 - INVALID DATASET NAME ON SYSIN CARD - MUST BE 1 TO
                  44 ALPHANUMERIC CHARACTERS

        ABEND U040

        The specified dataset name must be 1 to 44 characters in
        length.

    42) SMF3041 - INTERNAL ERROR - NO FIELDS SELECTED FOR PRINTING

        ABEND U041

        Print preparation processing determined that no fields were
        selected for printing.  This situation should never happen.

    43) SMF3042 - INTERNAL ERROR - PRINT SELECTED FOR NON-PRINTABLE
                  OPTION

        ABEND U042

        Print generation processing attempted to select an option
        instead of a field name for printing.  This situation should
        never happen.

    44) SMF3043 - PRINT SPECIFICATION ERROR - THE GENERATED PRINT LINE
                  EXCEEDS 133 CHARACTERS

        ABEND U043

        Too many fields were specified on one or more PRINT
        statements.  The total display length of all fields cannot
        exceed 133 characters.  Remove one or more PRINT options.

    45) SMF3044 - INVALID PRINT SUBPARAMETER ON SYSIN CARD - NULL
                  PARAMETER ENTERED

        ABEND U044

        A syntax error such as two commas in a row or a comma after
        the PRINT statement can create this situation.  Correct the
        syntax problem.

    46) SMF3045 - INVALID PRINT SUBPARAMETER ON SYSIN CARD - UNKNOWN
                  SUBPARAMETER ENTERED

        ABEND U045

        One or more of the subparameters on the PRINT statement
        was incorrect.  Check the spelling of all field names.

    47) SMF3046 - INVALID PRINT SUBPARAMETER ON SYSIN CARD - MORE
                  THAN 30 SUBPARAMETERS ENTERED

        ABEND U046

        A limit of 30 print field selections has been set.  The line
        limit of 133 characters will normally be reached before this
        condition.

    48) SMF3047 - INVALID PRINT SUBPARAMETER ON SYSIN CARD -
                  SUBPARAMETERS NOT SEPARATED BY ","

        ABEND U047

        A syntax error has been detected in the PRINT statement.
        Check for appropriate field names separated by commas.

    49) SMF3048 - INVALID PRINT SUBPARAMETER ON SYSIN CARD - NO
                  SUBPARAMETERS ENTERED

        ABEND U048

        A PRINT statement was entered without any field names
        specified.  One or more field names must be specified.

    50) SMF3049 - MORE THAN 1000 JOBNAME SELECT STATEMENTS ENTERED

        ABEND U049

        A maximum of 1000 JOBNAME statements may be entered.

    51) SMF3050 - MORE THAN 1000 DATE RANGE SELECT STATEMENTS ENTERED

        ABEND U050

        A maximum of 1000 DATE range statements may be entered.

    52) SMF3051 - MORE THAN 1000 TIME RANGE SELECT STATEMENTS ENTERED

        ABEND U051

        A maximum of 1000 TIME range statements may be entered.

    53) SMF3052 - MORE THAN 1000 SYSTEM ID NAME SELECT STATEMENTS
                  ENTERED

        ABEND U052

        A maximum of 1000 SYSID statements may be entered.

    54) SMF3053 - MORE THAN 1000 DATASET NAME SELECT STATEMENTS
                  ENTERED

        ABEND U053

        A maximum of 1000 DATASET name statements may be entered.

    55) SMF3054 - MORE THAN 1000 CATALOG NAME SELECT STATEMENTS
                  ENTERED

        ABEND U054

        A maximum of 1000 CATNAME statements may be entered.

    56) SMF3055 - MORE THAN 1000 EXCATALOG NAME SELECT STATEMENTS
                  ENTERED

        ABEND U055

        A maximum of 1000 EXCATNAME statements may be entered.

    57) SMF3056 - INVALID EXJOBNAME VALUE ON SYSIN CARD - INDEX VALUE
                  IS NOT NUMERIC

        ABEND U056

        The specified excluded jobname offset index was not numeric.
        The index value must be 1 to 2 numeric digits.

    58) SMF3057 - MORE THAN 1000 EXJOBNAME SELECT STATEMENTS ENTERED

        ABEND U057

        A maximum of 1000 EXJOBNAME statements may be entered.

    59) SMF3058 - INVALID EXJOBNAME VALUE ON SYSIN CARD - MUST 1 TO 8
                  ALPHANUMERIC CHARACTERS

        ABEND U058

        The specified excluded jobname must be 1 to 8 characters long.

    60) SMF3059 - INVALID EXSYSTEM VALUE ON SYSIN CARD - MUST BE 1 TO 4
                  ALPHANUMERIC CHARACTERS

        ABEND U059

        A blank excluded system name was entered.  It must be a 1 to 4
        character alpahanumeric name.

    61) SMF3060 - MORE THAN 1000 EXSYSTEM ID NAME SELECT STATEMENTS
                  ENTERED

        ABEND U060

        A maximum of 1000 EXSYSID statements may be entered.

    62) SMF3061 - INVALID EXDATASET NAME ON SYSIN CARD - MUST BE 1 TO
                  44 ALPHANUMERIC CHARACTERS

        ABEND U061

        The specified excluded dataset name must be 1 to 44
        characters in length.

    63) SMF3062 - MORE THAN 1000 EXDATASET NAME SELECT STATEMENTS
                  ENTERED

        ABEND U062

        A maximum of 1000 EXDATASET name statements may be entered.

    64) SMF3063 - INVALID COMBINATION OF DAY-OF-WEEK SELECT
                  STATEMENTS RESULTING IN NO ELIGIBLE DAYS

        ABEND U063

        Either no "including" day of week statements such as SUNDAY,
        MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY,
        WEEKDAY, WEEKEND, ALLDAYS, or EVERYDAY was entered or one of
        them was specified and later logically negated by the use of
        other "excluding" parameters starting with "NO...".

