
    /*****************************************************************/
    /*                                                       @Y30LB55*/
    /* ISDAMSC5 - 28 BYTE FORMAT 5 DCL ---- BASE ISDAMSC5 ON SENSEPTR*/
    /* POS(5) IF MSC RECORD. BASE ISDAMSC5 ON SENSEPTR IF DASD OBR   */
    /* RECORD                                                @Y30LB55*/
    /*                                                       @Y30LB55*/
    /*****************************************************************/

    DCL                             /* FORMAT5 DASD          @Y30LB55*/
      1 ISDAMSC5 CHAR(28) BASED,
       2 STATUS15 BIT(8),           /* 0                     @Y30LB55*/
       2 STATUS25 BIT(8),           /* 1                     @Y30LB55*/
       2 STATUS35 BIT(8),           /* 2                     @Y30LB55*/
       2 RESTART5 BIT(8),           /* 3 RESTART             @Y30LB55*/
       2 DRIVEID4 BIT(8),           /* 5 CHAN/DRIVE ID       @Y30LB55*/
       2 LOWCYL5 BIT(8),            /* 5                     @Y30LB55*/
       2 HIGHCYL5 BIT(8),           /* 6                     @Y30LB55*/
       2 FMTMSG5 BIT(8),            /* 7 FORMAT NO. (0-3), MESSAGE
                                       (4-7)                 @Y30LB55*/
        3 SUBFMTN5 BIT(4),          /* SUBFORMAT NUMBER      @Y30LB55*/
        3 MSGCODE5 BIT(4),          /* MESSAGE CODE          @Y30LB55*/
       2 DASDSENS CHAR(20),         /* 8-27 SUBFORMATS 0 - 6 @Y30LB55*/
        3 BYTE8F5 BIT(8),           /* 8                     @Y30LB55*/
        3 BYTE9F5 BIT(8),           /* 9                     @Y30LB55*/
        3 BYTE10F5 BIT(8),          /* 10                    @Y30LB55*/
        3 BYTE11F5 BIT(8),          /* 11                    @Y30LB55*/
        3 BYTE12F5 BIT(8),          /* 12                    @Y30LB55*/
        3 BYTE13F5 BIT(8),          /* 13                    @Y30LB55*/
        3 BYTE14F5 BIT(8),          /* 14                    @Y30LB55*/
        3 BYTE15F5 BIT(8),          /* 15                    @Y30LB55*/
        3 BYTE16F5 BIT(8),          /* 16                    @Y30LB55*/
        3 BYTE17F5 BIT(8),          /* 17                    @Y30LB55*/
        3 BYTE18F5 BIT(8),          /* 18                    @Y30LB55*/
        3 BYTE19F5 BIT(8),          /* 19                    @Y30LB55*/
        3 BYTE20F5 BIT(8),          /* 20                    @Y30LB55*/
        3 BYTE21F5 BIT(8),          /* 21                    @Y30LB55*/
        3 FSCFMT5 BIT(16),          /* 22,23 FAULT SYMPTOM CODE
                                                             @Y30LB55*/
        3 RUAFMT5 BIT(8),           /* 24                    @Y30LB55*/
        3 REALCYL5 BIT(16),         /* 25,26                 @Y30LB55*/
        3 BYTE27F5 BIT(8);          /* 27                    @Y30LB55*/
