)ATTR
 | TYPE(INPUT) INTENS(HIGH) CAPS(OFF)
)BODY
%--------------------------  O.H     Help     Subcommand  --------------
%OPTION ===>|ZCMD
+
+Enter the PDS subcommand name and any operands for%HELP:   +
%===>|LOPER

+Operands:  subcommandname - specifies the subcommand to be explained
+           FUNCTION - provide subcommand function information
+           SYNTAX   - provide subcommand syntax information
+           OPERAND  - provide subcommand operand information
+           OPERAND(opername) - provide information on the named operand
+
+Note:  to obtain an explanation of PDS message PDS998E, enter:  msg msg
+
+Subcommands:    ATTRIB   ALIAS    BROWSE   CHANGE   COMPARE  COMPRESS C
+                DISPLAY  DIRENTRY DELETE   DSNAME   DSPRINT  EDIT     E
+                EXEC     FIND     FIXPDS   FSE      HELP     HISTORY  I
+                ISPF     ISPMODE  LIST     MAP      MEMBERS  MEMLIST  O
+                OUTCOPY  PATTERN  PRINTOFF RECALL   RENAME   REPLACE  R
+                REVIEW   SUBMIT   SUBLIST  TSO      TSOEDIT  TSOLIST  U
+                VERIFY   VPSPRINT
+
+Default:  All subcommand information
)INIT

  &LOPER = '&OPERS'
  .CURSOR = LOPER
  .HELP   = P71OPHE1
)PROC
  &PDSZSEL='Help  &LOPER'
)END
