)ATTR
 | TYPE(INPUT) INTENS(HIGH) CAPS(OFF)
)BODY
%--------------------------  O.DSP   Dsprint  Subcommand  --------------
%OPTION  ===>|ZCMD
%
+Enter the member group name, the printer name and operands for%DSPRINT:
%===>|LOPER

+Operands:  memgroup    (for example, *; start:end; start:; part1/part2;
+           printername
            DDNAME(ddname)  DIRECT(KEEP/DELETE)
            LINES(linenum1:linenum2)
            NUM(loc,length)/SNUM(loc,length)/NONUM
            FCB(fcbname)  FORMS(formname)
            CLASS(c)  HOLD/NOHOLD  COL(col1:col2, ...)  COPIES(number)
            PAGELEN(num)  TMARGIN(num)  BMARGIN(num)
            SINGLE/DOUBLE/CCHAR
            FOLD(width)/TRUNCATE(width)
            EJECT/NOEJECT  NOEJMESS  NOHEADER
            TERMINAL  TRACE  WTR(wtrname)
+
+Required:  printername
+Defaults:  NUM, CLASS(A), COPIES(1), NOHOLD, SINGLE, HEADER, NOEJECT, M
+
+Note:      The above parameters are actually for the VPSPRINT product.
)INIT
  &LOPER  = '&OPERS'
  .CURSOR = LOPER
  .HELP   = P71OPHH
)PROC
 &PDSZSEL='Dsprint  &LOPER'
)END
