//HERC01SL JOB (SMPLIST),'SMPLIST ',CLASS=A,MSGCLASS=X
//* USER=HERC01,PASSWORD=xxxxxxxx
//*
//*-+----1----+----2----+----3----+----4----+----5----+----6----+----7-
//*
//SMPLIST  EXEC SMPAPP,COND=(5,LT)
//SMPCNTL  DD  *
  LIST CDS    MOD(IEECVUCM IEEDUCM)
             LMOD(IEECVUCM IEEDUCM)
                                      .
//*
//* other examples:
//*
//SMPCNTL  DD  *
  LIST CDS    LMOD(HASJES20)
            MOD(HASPNUC
                                HASPRDR
                                HASPRDRO
                                HASPRSCN
                                HASPXEQ
                                HASPPRPU
                                HASPACCT
                                HASPMISC
                                HASPCON
                                HASPRTAM
                                HASPCOMM
                                HASPCOMA
                                HASPINIT)
                 SYSMOD(EJE1103,ZP60015,WM00017,TJES801,ZUM0018)
                                .
//SMPCNTL  DD  *
  LIST CDS    MOD(IEFJESNM,HASJES20).
//SMPCNTL  DD  *
LIST CDS SYSMOD .
//*
