//HERC01  JOB  (SETUP),
//             'Assemble everything',
//             CLASS=A,
//             MSGCLASS=X,
//             MSGLEVEL=(1,1),
//             NOTIFY=HERC01
//********************************************************************
//*
//* Name:CBT.MVS38J.ASM($ASMALL)
//*
//* Desc: Assemble Everything
//*
//********************************************************************
//COMP1   EXEC COMPRESS,LIB='SYS2.LINKLIB'
//COMP2   EXEC COMPRESS,LIB='SYS2.CMDLIB'
//TSO     EXEC PGM=IKJEFT01
//SYSPRINT DD  SYSOUT=*
//SYSTSPRT DD  SYSOUT=*
//SYSTSIN  DD  *
 SUBMIT 'CBT.MVS38J.CNTL(APFCK$)'
 SUBMIT 'CBT.MVS38J.CNTL(APFLS$)'
 SUBMIT 'CBT.MVS38J.CNTL(BRODSCN$)'
 SUBMIT 'CBT.MVS38J.CNTL(CVXIT$)'
 SUBMIT 'CBT.MVS38J.CNTL(DELAY$)'
 SUBMIT 'CBT.MVS38J.CNTL(DISKM$)'
 SUBMIT 'CBT.MVS38J.CNTL(FCOOK$)'
 SUBMIT 'CBT.MVS38J.CNTL(MOVELOD$)'
 SUBMIT 'CBT.MVS38J.CNTL(OSCMD$)'
 SUBMIT 'CBT.MVS38J.CNTL(PA2SI$)'
 SUBMIT 'CBT.MVS38J.CNTL(REQUEUE$)'
 SUBMIT 'CBT.MVS38J.CNTL(RUNSC$)'
 SUBMIT 'CBT.MVS38J.CNTL(SETPF$)'
 SUBMIT 'CBT.MVS38J.CNTL(SMPSL$)'
 SUBMIT 'CBT.MVS38J.CNTL(TAPEHDR$)'
 SUBMIT 'CBT.MVS38J.CNTL(VTAMWT$)'
