//HERC01  JOB  (MVS),
//             'INSTALL # SUBSYS',
//             CLASS=A,
//             MSGCLASS=X,
//             MSGLEVEL=(1,1),
//             NOTIFY=HERC01
//********************************************************************
//*                                                                  *
//* NAME: SYS1.SETUP.CNTL(CMDSB4)                                    *
//*                                                                  *
//* TYPE: JCL to assemble modules for the CMDSBSYS                   *
//*                                                                  *
//********************************************************************
//DMASM   PROC MEMBER=,
//             ASMLIB='CBT249.FILE266',
//             LINKLIB='CBT.CMDSBSYS.LINKLIB',
//             LNCT=55
//ASM     EXEC PGM=IEUASM,PARM=(LOAD,NODECK,'LINECNT=&LNCT.')
//SYSLIB   DD  DISP=SHR,DSN=&ASMLIB,DCB=BLKSIZE=32720
//         DD  DISP=SHR,DSN=SYS1.HASPSRC
//         DD  DISP=SHR,DSN=SYS1.MACLIB
//         DD  DISP=SHR,DSN=SYS1.AMODGEN
//SYSUT1   DD  UNIT=SYSDA,SPACE=(TRK,(90,50))
//SYSUT2   DD  UNIT=SYSDA,SPACE=(TRK,(90,50))
//SYSUT3   DD  UNIT=SYSDA,SPACE=(TRK,(90,50))
//SYSPRINT DD  SYSOUT=*
//SYSGO    DD  UNIT=VIO,SPACE=(TRK,(90,50)),
//             DISP=(,PASS)
//SYSIN    DD  DSN=&ASMLIB.(&MEMBER.),DISP=SHR
//DMLINK  EXEC PGM=IEWL,
//             PARM='XREF,LET,LIST,AC=1,SIZE=(140K,6400)'
//SYSLIN   DD  DSN=*.ASM.SYSGO,DISP=(OLD,DELETE)
//         DD  DDNAME=SYSIN
//SYSLIB   DD  DISP=SHR,DSN=&LINKLIB.
//SYSLMOD  DD  DISP=SHR,DSN=&LINKLIB.(&MEMBER.)
//SYSUT1   DD  UNIT=VIO,SPACE=(TRK,(50,20))
//SYSPRINT DD  SYSOUT=*
//        PEND
//ASMPR   EXEC DMASM,MEMBER=CMDPRINT
//ASM00   EXEC DMASM,MEMBER=CMDDUMMY,
//             PARM.DMLINK='RENT,REUS,LET,LIST,SIZE=(140K,6400)'
//ASM01   EXEC DMASM,MEMBER=CMDSBCSC
//ASM02   EXEC DMASM,MEMBER=CMDSBINT
//ASM03   EXEC DMASM,MEMBER=CMDSBSYS,
//             PARM.DMLINK='RENT,REUS,LET,AC=1,LIST,SIZE=(140K,6400)'
//ASM04   EXEC DMASM,MEMBER=CMDTSO
//ASM05   EXEC DMASM,MEMBER=CMDSBTSO
//ASM05A  EXEC DMASM,MEMBER=CMDSBMON
//ASM06   EXEC DMASM,MEMBER=CSCSB03D
//ASM07   EXEC DMASM,MEMBER=CSCSA03D
//DMLINK.SYSIN DD *
 INCLUDE SYSLIB(CSCSB03D)
 ENTRY IEESA03D
/*
//ASM08   EXEC DMASM,MEMBER=CSCSC03D
//ASM09   EXEC DMASM,MEMBER=CSCSD03D
//ASM10   EXEC DMASM,MEMBER=CSCSE03D
//ASM11   EXEC DMASM,MEMBER=CSCSF03D
//ASM12   EXEC DMASM,MEMBER=CSCSG03D
//ASM13   EXEC DMASM,MEMBER=CSCSH03D
//ASM14   EXEC DMASM,MEMBER=CSCSI03D
//ASM15   EXEC DMASM,MEMBER=CSCSJ03D
//ASM16   EXEC DMASM,MEMBER=CSCSK03D
//ASM17   EXEC DMASM,MEMBER=CSCSL03D
//ASM17A  EXEC DMASM,MEMBER=CSCSZ03D
//ASM18   EXEC DMASM,MEMBER=CSCSM03D
//ASM19   EXEC DMASM,MEMBER=CSCSN03D
//ASM20   EXEC DMASM,MEMBER=CSCSO03D
//ASM21   EXEC DMASM,MEMBER=CSCSP03D
//ASM22   EXEC DMASM,MEMBER=CSCSQ03D
//ASM23   EXEC DMASM,MEMBER=CSCSR03D
//ASM24   EXEC DMASM,MEMBER=CSCSS03D
//ASM25   EXEC DMASM,MEMBER=CSCZB03D
//ASM26   EXEC DMASM,MEMBER=CSCZC03D
//ASM27   EXEC DMASM,MEMBER=CSCZJ03D
//ASM28   EXEC DMASM,MEMBER=CSCZP03D
//ASM29   EXEC DMASM,MEMBER=CSCZS03D
//ASM30   EXEC DMASM,MEMBER=CSCGA03D
//ASM31   EXEC DMASM,MEMBER=CSCGE03D
//ASM32   EXEC DMASM,MEMBER=CSCGF03D
//ASM33   EXEC DMASM,MEMBER=CSCGH03D
//ASM34   EXEC DMASM,MEMBER=CSCGJ03D
//ASM35   EXEC DMASM,MEMBER=CSCGO03D
//ASM36   EXEC DMASM,MEMBER=CSCGS03D
//ASM61   EXEC DMASM,MEMBER=CSCZA03D
//ASM62   EXEC DMASM,MEMBER=CSCGI03D
//ASM63   EXEC DMASM,MEMBER=CSCGU03D
