         MACRO
&PHASEID CONTAINS  &DUMMY
.*
.*             CHANGES TO RELEASE 3
.*             CHANGES TO RELEASE 2
.*             CHANGES TO RELEASE 1
.* INNER MACRO TO ICOMMON USED TO CREATE AN EXTERNAL
.* ROUTINE NAME ARRAY
         GBLC  &X0(26)
         GBLC  &X1(26)
         GBLC  &X2(26)
         GBLC  &X3(26)
         GBLC  &X4(26)
         GBLC  &X5(26)
         GBLC  &X6(26)
         GBLC  &X7(26)
         GBLC  &X8(26)
         GBLC  &X9(26)
         GBLC  &XA(26)
         GBLC  &XB(26)
         GBLC  &XC(26)
         GBLC  &XD(26)
         GBLC  &XE(26)
         GBLC  &XF(26)
.*
         LCLA  &I,&J                    INDEX
.*
         AIF   (K'&PHASEID EQ 0).ERR1
.*
         AIF   ('&X0(1)' EQ '').X0
         AIF   ('&X0(1)' EQ '&PHASEID').ERR5
         AIF   ('&X1(1)' EQ '').X1
         AIF   ('&X1(1)' EQ '&PHASEID').ERR5
         AIF   ('&X2(1)' EQ '').X2
         AIF   ('&X2(1)' EQ '&PHASEID').ERR5
         AIF   ('&X3(1)' EQ '').X3
         AIF   ('&X3(1)' EQ '&PHASEID').ERR5
         AIF   ('&X4(1)' EQ '').X4
         AIF   ('&X4(1)' EQ '&PHASEID').ERR5
         AIF   ('&X5(1)' EQ '').X5
         AIF   ('&X5(1)' EQ '&PHASEID').ERR5
         AIF   ('&X6(1)' EQ '').X6
         AIF   ('&X6(1)' EQ '&PHASEID').ERR5
         AIF   ('&X7(1)' EQ '').X7
         AIF   ('&X7(1)' EQ '&PHASEID').ERR5
         AIF   ('&X8(1)' EQ '').X8
         AIF   ('&X8(1)' EQ '&PHASEID').ERR5
         AIF   ('&X9(1)' EQ '').X9
         AIF   ('&X9(1)' EQ '&PHASEID').ERR5
         AIF   ('&XA(1)' EQ '').XA
         AIF   ('&XA(1)' EQ '&PHASEID').ERR5
         AIF   ('&XB(1)' EQ '').XB
         AIF   ('&XB(1)' EQ '&PHASEID').ERR5
         AIF   ('&XC(1)' EQ '').XC
         AIF   ('&XC(1)' EQ '&PHASEID').ERR5
         AIF   ('&XD(1)' EQ '').XD
         AIF   ('&XD(1)' EQ '&PHASEID').ERR5
         AIF   ('&XE(1)' EQ '').XE
         AIF   ('&XE(1)' EQ '&PHASEID').ERR5
         AIF   ('&XF(1)' EQ '').XF
         AIF   ('&XF(1)' EQ '&PHASEID').ERR5
.*
         AGO   .ERR4
.*
.X0      ANOP
&X0(1)   SETC  '&PHASEID'
.X01     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X01
         AIF   (&J GT 24).ERR6
&X0(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X01
.*
.X1      ANOP
&X1(1)   SETC  '&PHASEID'
.X11     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X11
         AIF   (&J GT 24).ERR6
&X1(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X11
.*
.X2      ANOP
&X2(1)   SETC  '&PHASEID'
.X21     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X21
         AIF   (&J GT 24).ERR6
&X2(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X21
.*
.X3      ANOP
&X3(1)   SETC  '&PHASEID'
.X31     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X31
         AIF   (&J GT 24).ERR6
&X3(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X31
.*
.X4      ANOP
&X4(1)   SETC  '&PHASEID'
.X41     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X41
         AIF   (&J GT 24).ERR6
&X4(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X41
.*
.X5      ANOP
&X5(1)   SETC  '&PHASEID'
.X51     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X51
         AIF   (&J GT 24).ERR6
&X5(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X51
.*
.X6      ANOP
&X6(1)   SETC  '&PHASEID'
.X61     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X61
         AIF   (&J GT 24).ERR6
&X6(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X61
.*
.X7      ANOP
&X7(1)   SETC  '&PHASEID'
.X71     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X71
         AIF   (&J GT 24).ERR6
&X7(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X71
.*
.X8      ANOP
&X8(1)   SETC  '&PHASEID'
.X81     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X81
         AIF   (&J GT 24).ERR6
&X8(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X81
.*
.X9      ANOP
&X9(1)   SETC  '&PHASEID'
.X91     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').X91
         AIF   (&J GT 24).ERR6
&X9(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .X91
.*
.XA      ANOP
&XA(1)   SETC  '&PHASEID'
.XA1     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').XA1
         AIF   (&J GT 24).ERR6
&XA(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .XA1
.*
.XB      ANOP
&XB(1)   SETC  '&PHASEID'
.XB1     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').XB1
         AIF   (&J GT 24).ERR6
&XB(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .XB1
.*
.XC      ANOP
&XC(1)   SETC  '&PHASEID'
.XC1     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').XC1
         AIF   (&J GT 24).ERR6
&XC(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .XC1
.*
.XD      ANOP
&XD(1)   SETC  '&PHASEID'
.XD1     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').XD1
         AIF   (&J GT 24).ERR6
&XD(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .XD1
.*
.XE      ANOP
&XE(1)   SETC  '&PHASEID'
.XE1     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').XE1
         AIF   (&J GT 24).ERR6
&XE(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .XE1
.*
.XF      ANOP
&XF(1)   SETC  '&PHASEID'
.XF1     AIF   (&I+1 GT N'&SYSLIST).END
&I       SETA  &I+1
         AIF   ('&SYSLIST(&I)' EQ '').XF1
         AIF   (&J GT 24).ERR6
&XF(&J+2) SETC '&SYSLIST(&I)'
&J       SETA  &J+1
         AGO   .XF1
.*
.ERR1    MNOTE 8,'INVALID OR NO PHASEID FURNISHED.'
         MEXIT
.ERR4    MNOTE 8,'EXTERNAL ROUTINE NAME ARRAYS FULL.'
         MEXIT
.ERR5    MNOTE 8,'DUPLICATE PHASEID.'
         MEXIT
.ERR6    MNOTE 8,'TOO MANY NAMES.'
         MEXIT
.END     AIF   (&J GT 0).MEND
         MNOTE 0,'NO ROUTINE NAMES FURNISHED.'
.MEND    MEND
