//RCTST2   JOB (CBT),
//             'Run BSPRCTST',
//             CLASS=A,
//             MSGCLASS=A,
//             MSGLEVEL=(1,1),
//             NOTIFY=HERC02
//********************************************************************
//*                                                                  *
//*  Name: SYS1.SETUP.CNTL(RCTST#)                                   *
//*                                                                  *
//*  Desc: Testrun BSPRCTST  or SYSIN                                *
//*                                                                  *
//********************************************************************
//HERC    EXEC PGM=BSPHRCMD,PARM='devinit 00e prt/$$rctst#.lst crlf'
//STEP1   EXEC PGM=IDCAMS
//SYSPRINT DD  SYSOUT=*
//SYSIN    DD  *
 SET MAXCC=4
 SET LASTCC=0
//STEP2   EXEC PGM=IDCAMS
//SYSPRINT DD  SYSOUT=*
//SYSIN    DD  *
 SET MAXCC=8
 SET LASTCC=0
//STEP3   EXEC PGM=IDCAMS,COND=(0,NE)
//SYSPRINT DD  SYSOUT=*
//SYSIN    DD  *
 SET MAXCC=8
 SET LASTCC=0
//STEP4   EXEC PGM=NOTHERE
//STEP5   EXEC PGM=IDCAMS,COND=EVEN
//SYSPRINT DD  SYSOUT=*
//SYSIN    DD  *
 SET MAXCC=0
 SET LASTCC=0
//RCTST2  EXEC PGM=BSPRCTST,PARM=12,COND=EVEN
//SYSPRINT DD  SYSOUT=*
//RCTST3A EXEC PGM=BSPRCTST,PARM=8,COND=EVEN
//RCTST3B EXEC PGM=BSPRCTST,PARM=8,COND=EVEN
//STEP2    DD  DUMMY
//RCTST4  EXEC PGM=BSPRCTST,PARM=4,COND=EVEN
//RCTST5  EXEC PGM=BSPRCTST,PARM=0,COND=EVEN
//RCTST6  EXEC PGM=BSPRCTST,COND=EVEN
//SYSPRINT DD  SYSOUT=*
