         MACRO
         FC    &X
         LCLC  &C
         GBLA  &COUNT
&COUNT   SETA  &COUNT+1
         AIF   (&COUNT GT 9000).SETB
&C       SETC  'A&SYSNDX'
         AGO   .TESTIT
.SETB    ANOP
         AIF   (&COUNT GT 18000).SETC
&C       SETC  'B&SYSNDX'
         AGO   .TESTIT
.SETC    ANOP
&C       SETC  'C&SYSNDX'
.TESTIT  ANOP
         DC    AL1(L'&C)              , LENGTH OF FORTUNE COOKIE
&C       DC    C&X                    , FORTUNE COOKIE TEXT
         MEND
