.section 'FIXUPDSN'
.ix FIXUPDSN
.ix 'ISPF Programs' FIXUPDSN
.sp 2
.subsection 'Description'
.sp
FIXUPDSN is an ISPF program designed to simplify CLIST processing under
ISPF by determining if a DSN passed from an ISPF panel is fully
qualified in quotes or not.

If it is fully qualified in quotes then the quotes are removed and it is
put back into the ISPF variable pool.

If it is not in quotes then the TSO prefix (ZPREFIX) is appended in
front and it is put back into the ISPF variable pool.

To invoke via CLIST:
      ISPEXEC SELECT PGM(FIXUPDSN) PARM(DSN-VARIABLE-NAME)

To retrieve the updated DSN via CLIST:
      ISPEXEC VGET DSN-VARIABLE-NAME

