.section 'FTL -  File Copy Utility'
.ix 'FTL - Copy Utility'
.ix 'Faster Than Light Utility'
.ix Programs FTL
.sp 2
.subsection 'Description'
.sp 2
     FTL may be used under OS/MVS for transfer of multiple sequential
  files in one step. This saves initiation/termination time.And is
     FTL will run in 4k (not including file buffers)

     FTL can reblock files or change physical record length or format
  by specifying appropiate DCB parameters on the output data definition
  (DD) statement.

     The DD statements are paired using names in and out as prefixes
  followed by a two-character number from 01 to 99. These pairs must be
  sequential starting with IN01 and OUT01 and increasing without break
  for as many files as desired.
     Any sequentially organized file may be input or output. It may
  have any record format, record length, and blocksize consistent with
  OS/MVS. Exceptions are indexed sequential(ISAM) data set organization,
  variable spanned record format, and partitioned data sets. The latter
  may be processed as individual members.

     When expanding   the record length, the additional field will have
  unpredictable contents. Other changes of length, format, or blocksize
  do not affect file content.

     For each transfer pair, a message is written to an output data set
  (DD name is messages) giving a record count and volume serial number
  of input and output data sets if on direct access or tape.

  FTL is an old science fiction term meaning "faster than light".

.cp 20
.subsection 'Example'

   Sample JCL
 //SAVE EXEC PGM=FTL
 //STEPLIB DD DSN=AOST.LOAD,DISP=SHR
 //SYSUDUMP DD SYSOUT=A
 //MESSAGES DD SYSOUT=A
 //IN01     DD DSN=Y01PR195,DISP=SHR,DCB=BUFNO=1,VOL=(,RETAIN)
 //OUT01    DD DSN=T011PR195,DISP=(NEW,KEEP),UNIT=TAPE16,VOL=(,RETAIN),
 //  DCB=(LRECL=1560,BLKSIZE=1560,BUFNO=1,RECFM=FB)
 //IN02     DD DSN=Y02PR195,DISP=SHR,DCB=(BUFNO=4,OPTCD=C)
 //OUT02    DD DSN=T02PR195,DISP=(NEW,KEEP),UNIT=TAPE16,LABEL=2,
 //  VOL=C,RETAIN,REF=*,OUT01,
 // DCB=(LRECL=492,BLKSIZE=19188,RECFM=FB,BUFNO=3,OPTCD=C)
 //IN03     DD  .  .  .
 //OUT03    DD  .  .  .
      .
      .
      .
     This example shows a DCB given for every DD statement, this is
  not necessary when no change of record length, record format, or
  blocksize is being made, because the program will copy these DCB
  parameters from the input file.

