.pa
.chapter 'VM COMMANDS'
.ix 'VM Testing' 'VM Commands'

     All VM commands should be preceded by a #CP to indicate that you
     are entering a VM command and not a CMS or MVS command.

     Some of the more common VM commands are:

     #CP Q N  - display who is logged onto VM

     #CP IND  - display current CPU utilization

     #CP IND USER - display the current CPU usage for your session

     #CP D P   - display the current PSW

     #CP D G   - display the current general register contents

     #CP SET PFxx IMM command - set a PFK with a VM or MVS command to
                                be executed immediately

     #CP Q PF                 - displays current PFK settings

     #CP SET PFxx command     - set a PFK with a VM or MVS command to
                                be executed after allowing modification

     #CP SPOOL CONSOLE START - to spool all VM, MVS and JES3 console
                               messages to hardcopy

     #CP SPOOL 00B cmsid     - to spool all sysout to your cms id

     #CP SPOOL 00B TO SYSTEM - to spool all sysout to back to hardcopy

     #CP SET CPUid 012345    - change cpu serial number

     #CP Q CPUid             - query current cpu serial number

     #CP DEF CTC xxx         - define a virtual CTC

     #CP Q V xxx             - find what is on virtual address xxx

     #CP Q DASD vvvvvv       - find out where vol vvvvvv is mounted

     #CP COUPLE xxx userid yyy - connects CTC xxx on current userid
                                 to other userid's CTC yyy

     #CP TRace (SVC,I/O,PROgram,EXTernal,PRIV,SIO,CCW,BRanch,INSTruct,
                ALL,CSW) (OFf/RUN)  - to trace to console any or all
                                      of these events


     If you want to use the same MVS system on your next VM session and
     do not need to change any IPL parameters you can save the current
     MVS system intact.  You will want to reserve your VM logonid to
     insure that the paging and spool packs will not be altered.
     To do this :

     1) issue QUIESCE  - then wait for a wait state message

     2) issue #CP SAVESYS MVSx  - where x = your VM id (1-4)

     3) issue #CP LOGOFF when the savesys is completed

     To recover from a SAVESYS:

     1) Logon to VM

     2) issue IPL MVSx - where x = your VM id

     3) you are now exactly where you were when you did the SAVESYS.
