.pa
.ix 'VM Testing' JES3
.chapter 'JES3'

     You are now ready to start JES3.

     To do so enter:
     S JES3,Q=VM

     Check with the JES3 group if you wish any changes to the standard
     JES3 system.

     You will recieve 3 prompts for JES3 initialization.

     The first prompt is:
     IAT3011 SPECIFY JES3 START TYPE
     01 IAT3011 (L H HA W WA OR C)

     You should normally respond with C for cold start as this is the
     cleanest.
     ex.  R 01,C

     The second prompt is:
     02 IAT3033 CONFIRM JES3 COLDSTART REQUEST (U)

     Reply with R 02,U

     The third prompt is for the init deck and is:
     03 IAT3012 SELECT JES3 INISH ORIGIN (N M= U=), ...

     The normal response is R 03,M=VM

     JES3 is now on its way to initialization

     After some time you will receive message:
     IAT3100 JES3 x.x.x SYSTEM COLDSTART ON yy.ddd AS L

     This indicates that the coldstart has been successfully completed.

     You should now enter:
     *S JSS

     This will complete the initialization of JES3.

     Message IAT2645 ****** L    CONNECT COMPLETE ******
     indicates that you are ready to begin processing.

     If you have any sysout be sure that all output has a DEST of LOCAL.
.pa
     You may receive message:
     IAT7030 jobname (job#) on WCC1#00B (00B), SETUP F=STANDARD, ..

     This indicates that JES3 wants to start writer 00B, you should
     enter:
     *S 00B to start the output writer.


.sp 3
.section 'JES3 Commands'

     Some common JES3 commands are:

     *I J/jobname   - inquire about a job

     *I J/job#      - inquire about a job

     *F J/job#,C    - cancel a job

     *F J/job#,p=xx - change a jobs JES3 priority

     NOTE:  All JES3 commands are prefixed by an * or 8.

            For a complete list of JES3 commands see SX23-0007
.pa
.section 'Global-Local JES3'
.sp 2
     1)  Preparation
         a) Insure that AUJSQ0 is mounted and available to VM.
         b) Check the JES3 initdeck JES3.PARMLIB(JES3IN00) to determine
            the CTC addresses for your test.
         c) Do ISPF browse F DEVICE 1
         d) Find JNAME= cpu you desire and then
         e) Determine the CTC address that connects to the local
            you are bringing up.  NOTE: It is the same in both
            directions today but might change.
         f) Signup for 2 MVS VM id's.
         g) Determine the CPUid for your global and for your local
            so that you can set the cpuid prior to ipl'ing MVS.

     2)  Logon to 1 MVS VM system.

     3)  Insure that AUJSQ0 is available to your VM MVS system
         as read/write (RW).
         a) If not then issue #CP ATT xxx SYSTEM AUJSQ0
            where xxx is the address of AUJSQ0.  The address is
            determined by issuing a #CP Q DASD AUJSQ0.
         b) Issue #CP LINK FULLPROD 120 320 MW WT for the first link
            or #CP LINK FULLPROD 120 320 MW MULT if another id
            has linked to AUJSQ0.

     4)  Logon to 2nd MVS VM system.
         a) Issue #CP SET CPUID xxxxxx
            where xxxxxx is the CPUID of planned local.
         b) Issue #CP LINK FULLPROD 120 320 MW MULT for access to
            AUJSQ0.

     5)  Issue #CP DEF xxx CTC for both MVS systems
         a) From 1 of the systems issue:
            #CP COUPLE xxx MVSy zzz
            where xxx = the CTC address of the MVS system you are on
                  y   = the MVS id of the other MVS system
            and   zzz = the CTC address of the other MVS system

     6)  IPL normally as documented under MVS VM TESTING.

     7)  Issue S JES3,Q=TEST and bring up your global processor first.
         Do a COLD start (reply C).

     8)  Issue *S JSS after the system is up.

     9)  Issue *V x,ON where x = the cpuname of the global.

    10)  When the global processor is up, then IPL the local on the
         other MVS VM system.

    11)  Issue S JES3,Q=TEST and reply L to bring it up as a local.

    12)  Issue *S JSS after the system is up.

    13)  On the global processor: *V x,ON where x is the cpuname of
         the local.

    14)  Verify that the JES3 classes you need are turned on for both
         the global and local.

    15)  Contact someone in the JES3 group if you have any questions
         or problems.
.pa
.section 'Viewing the INITDECK Listing on VM'
.sp 2
When JES3 comes up it places the initdeck listing into a disk
dataset on a minidisk.  To view the listing you need to log onto a
CMS id and execute the OSLIST CMS EXEC.
.sp 2
.subsection 'OSLIST'
.sp
This EXEC will prompt the user thru a process to view the
INITDECK.
.sp
     To execute OSLIST enter:
.sp
     OSLIST
