//SBGOLOBM  JOB (ACCT#),S-GOLOB,
// NOTIFY=&SYSUID,
// CLASS=B,MSGCLASS=X
//******************************************************************//
//*     COPY 2 TAPES - EVERYTHING - 4 COPIES ILLUSTRATED           *//
//******************************************************************//
//* ---------------------------------------------------------------
//* -- USE PARM=LTMSKIP ONLY IF YOU WANT TO STRIP LEADING TAPEMARKS
//* -- THIS IS A RARE OCCURRENCE - USUALLY DEALING WITH VSE TAPES.
//* ---------------------------------------------------------------
//*
//COPY   EXEC  PGM=COPYMODS,REGION=4096K PARM='HDR1'
//STEPLIB  DD  DISP=SHR,DSN=SBGOLOB.LOAD
//SYSPRINT DD  SYSOUT=*
//IN    DD VOL=SER=CBT423,DISP=OLD,UNIT=3480,LABEL=(,BLP)
//OUT1  DD VOL=SER=CBT42A,DISP=OLD,UNIT=3480,LABEL=(,BLP)
//OUT2  DD VOL=SER=CBT42B,DISP=OLD,UNIT=3480,LABEL=(,BLP)
//OUT3  DD VOL=SER=CBT42C,DISP=OLD,UNIT=3480,LABEL=(,BLP)
//OUT4  DD VOL=SER=CBT42D,DISP=OLD,UNIT=3480,LABEL=(,BLP)
