         TITLE 'PGM TO COMPRESS/COPY A DISK VOLUME-MVS (ALCDS)'
         MACRO
&LABEL   CRASH
&LABEL   BAL   14,CRASH        GO TO CRASH ROUTINE
         MEND
         SPACE
         MACRO
&LABEL   WRTVTOC &LOC,&ADR,&IND
&LABEL   MVI   OUTER,0        CLEAR ERROR BYTE
         WRITE VTCOUTDB,DI,,&LOC+44,,&LOC,MF=E
         CHECK VTCOUTDB       WAIT TILL FINISHED
         AIF   (T'&IND NE 'O').OUT
         CLI   OUTER,0        SEE IF GOOD WRITE
         BE    *+8             GOODIE
         BAL   14,CRASH        GO CRASH
.OUT     ANOP
         AIF   (T'&ADR EQ 'O').OUT2
         L     14,VTCOUTDB+16  GET IOB ADDRESS
         IHBINNRA &ADR         GET PARM IN REG 1
         MVC   0(5,1),CCHHR(14) MOVE CCHHR OF ADDRESS
.OUT2    ANOP
         L     14,BLOCKAD      GET BLOCK #
         LA    14,1(14)        INCR
         ST    14,BLOCKAD      SAVE
         MEND
         SPACE
         MACRO
&LABEL   TTRABS &DCB,&ABSAD    CONVERT FROM TTR TO ABSOLUTE ADDRESS
&LABEL   L     1,&DCB+44       GET DEB ADDRESS
         LA    2,&ABSAD        GET ADDRESS OF ABSOULTE ADDRESS
         L     14,16           GET CVT ADDRESS
         L     15,X'1C'(14)    GET CONVERT ROUTINE ADDRESS
         LA    3,RGSAV         POINT TO SAVE AREA
         STM   9,13,0(3)       SAVE THEM
         BALR  14,15           GO TO IT
         LM    9,13,0(3)       RESTORE REGS.
         MEND
         SPACE 2
         MACRO
&LABEL   ABSTTR &DCB,&ABSAD    CONVERT FROM ABSOLUTE ADDRESS TO TTR
&LABEL   L     1,&DCB+44       GET DEB ADDRESS
         LA    2,&ABSAD        GET ADDRESS OF ABSOLUTE ADDRESS
         L     14,16           GET CVT ADDRESS
         L     15,X'20'(14)    GET CONVERT ROUTINE ADDRESS
         LA    3,RGSAV         GET ADDRESS OF SAVEA AREA
         STM   9,13,0(3)       SAVE REGS
         BALR  14,15           GO TO ROUTINE
         LM    9,13,0(3)       RESTORE REGS.
         MEND
         SPACE
         MACRO
&LABEL   READVTOC &LOC
&LABEL   POINT DISKIN,FULL     POINT AT RECORD
         MVI   OUTER,0        CLEAR ERROR
         READ  VTOCINDB,SF,,&LOC,MF=E
         CHECK VTOCINDB        WAIT TO STOP
         CLI   OUTER,0        MAKE SURE NO ERROR
         BE    *+8            IF NOT, GOODIE
         BAL   14,CRASH       OTHERWISE, GO CRASH
         MEND
         EJECT
ALCDS    CSECT                                                WMT 04/76
*        BAL   R14,ALCDS                                      WMT 04/76
         USING ALCDS,RF           SET UP TEMP BASE.           WMT 04/76
         ST    RC,X5              SAVE OLD BASE ADDR.         WMT 04/76
         ST    RE,XXX000          SAVE RETURN ADDR.           WMT 06/76
         DROP RF                  DROP OLD BASE.              WMT 04/76
         LR    RC,RF              SET UP START ADDR.          WMT 04/76
         USING ALCDS,RC           SET UP ADDRESSING.          WMT 04/76
         USING SAVE,RD            SET UP COMMON ADDRESSING.   WMT 04/76
         L     RF,RGSAV           RESTORE RF                  WMT 04/76
         XC    SULFLAG,SULFLAG    CLEAR FLAG.                 WMT 04/76
         TM    FMT1+105,X'40'     TEST FOR SUL.               WMT 04/76
         BZ    NOTSUL             BR IF NOT SUL.              WMT 04/76
         MVI   SULFLAG,X'FF'      TURN ON SUL FLAG.           WMT 04/76
NOTSUL   DS    0H                                             WMT 04/76
*                                                             WMT 12/75
*        EQUATE REGISTERS.                                    WMT 12/75
*                                                             WMT 12/75
R0       EQU   0                                              WMT 12/75
R1       EQU   1                                              WMT 12/75
R2       EQU   2                                              WMT 12/75
R3       EQU   3                                              WMT 12/75
R4       EQU   4                                              WMT 12/75
R5       EQU   5                                              WMT 12/75
R6       EQU   6                                              WMT 12/75
R7       EQU   7                                              WMT 12/75
R8       EQU   8                                              WMT 12/75
R9       EQU   9                                              WMT 12/75
RA       EQU   10                                             WMT 12/75
RB       EQU   11                                             WMT 12/75
RC       EQU   12                                             WMT 12/75
RD       EQU   13                                             WMT 12/75
RE       EQU   14                                             WMT 12/75
RF       EQU   15                                             WMT 12/75
         STM   15,2,RGSAV      SAVE 15-2
         LH    10,TRKPCYL      GET TRACKS PER CYLINDER IN 10
         L     11,=F'-1'
         AR    11,10           11 HAS LAST TRACK ADDR. ON CYL
         LH    3,INEXT+4(1)    GET ENDING CYL
         MR    2,10            GET REL CYL START
         CLI   SULFLAG,X'FF'      TEST FLAG.                  WMT 04/76
         BE    JUSTAD             BR IF SUL.                  WMT 04/76
         TM    3(4),X'28'      NOT CYLINDER?
         BNZ   JUSTAD          IF NOT, ADD IN TRACKS
         AR    3,11            GET UP TO LAST TRK
         B     ALCOMM
JUSTAD   AH    3,INEXT+6(1)    ADD IN LAST TRACK
ALCOMM   LA    3,1(3)          NOW HAVE # OF LAST TRACK
         LH    7,INEXT(1)      GET STARTING CYL
         MR    6,10            GET REL CYL START
         CLI   SULFLAG,X'FF'      TEST FOR SUL.               WMT 04/76
         BE    X10                BR IF SUL.                  WMT 04/76
         TM    3(4),X'28'      CYLINDER?
         BZ    ALNOAD1         IF SO, BRANCH
X10      DS    0H                                             WMT 04/76
         AH    7,INEXT+2(1)    ADD IN FIRST TRK
ALNOAD1  SR    3,7             3 HAS # OF TRKS TO ALLOCATE
         STH   3,TRKALC        SAVE TRACKS ALLOCATED
         L     6,PFMT5AD       GET START OF FREE EXTENT LIST
         LA    15,PFMT5AD      GET ADDRESS OF FORMAT 5 ADDRESS
SPCLOK1  EQU   *
         TM    3(4),X'20'      SYSCTLG DATA SET?
         BZ    NTCTLG02        IF NOT, NORMAL ALLOC
         CLC   OTVTCEND,4(6)   SEE IF EXTENT PAST VTOC
         BNL   LKNXTFRE        IF NOT, LOOK AT NEXT FREE EXTENT
NTCTLG02 EQU   *
         LH    5,8(6)          GET TRKS ON CYL
         AH    5,10(6)         ADD LEFT OVER TRKS O END
         CLI   SULFLAG,X'FF'      TEST FOR SUL.               WMT 04/76
         BE    X11                BR IF SUL.                  WMT 04/76
         TM    3(4),X'10'      IS THIS FOR CYLINDER
         BO    ALNOAD2
X11      DS    0H                                             WMT 04/76
         AH    5,6(6)          ADD IN TRKS BEFORE CYL
ALNOAD2  CR    3,5             SEE IF ENOUGH SPACE
         BNH   SPCFND1         IF SO, WE'RE IN
LKNXTFRE EQU   *
         LR    15,6           SAVE REG. 6
         L     6,0(15)         POINT TO NEXT  FREE EXTENT
         LTR   6,6             MAKE SURE SOME LEFT
         BNZ   SPCLOK1         OH GOODIE
         CRASH , IF NOT, THEN KILL THYSELF
SPCFND1  LH    9,4(6)          GET EXTENT START
         CLI   SULFLAG,X'FF'      TEST FOR SUL.               WMT 04/76
         BE    ALNOAD3            BR IF SUL.                  WMT 04/76
         TM    3(4),X'10'      IS IT CYLINDER
         BNO   ALNOAD3
         AH    9,6(6)          ADD TRKS BEFORE CYL
ALNOAD3  LR    0,9             SAVE #
         SR    8,8             CLEAR 8 FOR DIVIDE
         DR    8,10            GET STARTING EXTENT ADDRESS
         STH   9,OUTEXT(1)     SAVE CYL START
         STH   8,OUTEXT+2(1)   & TRK START
         LR    9,0             GET START BACK
         AR    9,3             ADD IN # OF TRKS
         BCTR  9,0             REDUCE TO LAST TRACK ADDRESS
         SR    8,8             CLEAR 8 AGAIN
         DR    8,10            GET ENDING TRACK ADDRESS
         STH   9,OUTEXT+4(1)   SAVE ENDING CYL
         STH   8,OUTEXT+6(1)   SAVE    ENDING TRACK
         L     7,FPFMT5AD      GET START OF FERE AREA
         CLI   SULFLAG,X'FF'      TEST FOR SUL.               WMT 04/76
         BE    NOHDTRKS                                       WMT 04/76
         TM    3(4),X'10'      SEE IF CYLINDER ALLOCATION
         BNO   NOHDTRKS        IF NOT,AT BEGINNING
         SR    8,8             CLEAR 8 FOR COMPARE
         CH    8,6(6)          SEE IF TRKS BEFORE CYL IS ZERO
         BE    NOHDTRKS        IF NOT, THEN GET OUT
         LH    2,4(6)          GET EXTENT START
         AH    2,6(6)          ADD TRKS BEFORE CYL
         AR    2,3             ADD TRACKS ALLOCATED
         STH   2,4(7)          SAVE START OF NEW EXTENT
         LH    2,8(6)          GET # OF CYLS BEFORE ALLOC
         SR    2,3             SUBTRACT THOSE ALLOC
         STH   2,8(7)          SAVE THEM IN NEW EXTENT
         AH    2,10(6)         ADD IN EXTRA TRACKS
         BZ    FXTHSEXT        IF ZERO, NO NEW EXTENT
         MVC   10(2,7),10(6)   MOVE EXTRA TRACKS OVER
         MVC   FPFMT5AD,0(7)   MOVE FREE POINTER
         MVC   0(4,7),0(6)     MOVE EXT POINTER
         ST    7,0(6)          KEEP LINKING
         XC    6(2,7),6(7)     WIPE OUT TRKS BEFORE CYL
FXTHSEXT XC    8(4,6),8(6)     WIPE OUT CYLS & EXT TRKS
         B     BLASTOUT        GO BACK
NOHDTRKS EQU   *
         LH    2,4(6)          GE T EXTENT START
         AR    2,3             UP TO WHERE EXTENT WOULD END
         STH   2,4(6)          SAVE NEW EXTENT START
         LH    2,8(6)          GET # OF ORIG TRKS
         AH    2,6(6)          ADD IN TRKS BEFORE CYL
         SR    2,3             SUBTRACT THOSE ALLOCATEDC
         BP    HITIT1          IF A GOOD NUMBER, USE IT
         AH    2,10(6)         ADD IN TRKS AFTER CYL
         MVC   8(4,6),ZEROES   CLEAR IT AND ONE BEFORE
         BP    HITIT2          GO STORE TRLS
         BZ    GIVEBACK        GIVE BACK EXTENT IF ZERO
         CRASH ,               IF HERE - A REAL GOOF
HITIT1   EQU   *
         LR    3,2             LOAD 3 WITH LEFT OVER TRACKS
         SR    2,2             CLEAR 2 FOR DIVIDE
         DR    2,10            GET CYLS AND LEFT OVER TRACKS
         MH    3,TRKPCYL       GET BACK TRACKS ON CYL BOUNDARY
         STH   3,8(6)          STORE TRACKS ON CYL BOUNDARY
HITIT2   EQU   *
         STH   2,6(6)          STORE TRACKS BEFORE CYL
         B     BLASTOUT        GET OUT
GIVEBACK EQU   *
*        IF ZERO WE JUST USED UP AN EXTENT & HAVE TO GIVE IT BACK
         XC    4(8,6),4(6)     WIPE OUT EXTENT INFO
         L     2,0(6)          GET NEXT ENTRY POINTER
         ST    2,0(15)         STORE IT IN LAST ENTRY
         ST    7,0(6)          SAVE IN MINE
         ST    6,FPFMT5AD      MAKE NEW START
BLASTOUT EQU   *
         LM    15,2,RGSAV      RESTORE 15-2
         L     RE,XXX000          RESTORE RETURN ADDR.        WMT 06/76
         L     RC,X5              RESTORE OLD BASE.           WMT 04/76
         BR    14              &RETURN
X5       DC    F'0'               RC SAVE AREA.               WMT 04/76
XXX000   DC    F'0'               RETURN ADDR.                WMT 06/76
SULFLAG  DC    XL1'00'            SUL FLAG.                   WMT 04/76
         LTORG
         EJECT
SAVE     DSECT                                                WMT 04/76
         DC    9D'0'              SAVE AREA.                  WMT 04/76
IOER     EQU   *              I/O ERROR ROUTINE
         USING *,15           15 IS BASE FOR A WHILE
         MVI   OUTER,255      INDICATE ERROR
         BR    14             AND RETURN
         DROP  15                                             WMT 12/75
CRASH    DS    0H                                             WMT 12/75
EX       EX    0,EX               BLOW WITH C03.              WMT 12/75
VTOC     DC    CL8'SYSVTOC'    MAJOR QUEUE NAME
HEADER   DC    CL121'1DISK SQUISHER'
         ORG   *-8
         DC    C'PAGE '
PAGE#UP  DS    CL3
         ORG
         DC    CL121' '
         ORG   *-120
DSNAME   DS    CL44
         DC    C'  COPIED SUCCESSFULLY'
         ORG
         DC    CL121' '                 *SDS*
         ORG   *-120                    *SDS*
BADCPY   DS    CL44                     *SDS*
         DC    C'  COPY FAILED  I/O ERROR ************'   *SDS*
         ORG
PAGE#    DC    PL3'0'
LINE#    DC    P'60'
ENDMES   DC    CL121'0DISK SQUISHER COMPLETE'
OLDVOL   DS    CL6                      *SDS*
TAGVOL   DS    CL6                      *SDS*
REPL     DS    CL6                      *SDS*
ENQL     ENQ   (VTOC,OLDVOL,E,6,SYSTEMS,VTOC,TAGVOL,E,6,SYSTEMS),      +
               MF=L                     *SDS*
WTOR     WTOR  'COPYVOL VERIFY ENTER TARGET VOL FOR XXXXXX',REPL,6,    +
               INECB,MF=L               *SDS*
BDOPMES  DC    CL121' OPERATOR DENIED YOUR REQUEST TO SQUISH VOLUME.'
R5R6     DS    2F
ALLTRKS  DC    F'16650'           TOTAL TRACKS ON A PACK.     GJG8/76
MRGSW    DC    X'00'              NOT A MERGE INITIALLY.      WMT 12/75
SAV14    DS    F                  R14 SAVE AREA.              WMT 12/75
RG6TO15  DS    10F                TEMP SAVE AREA.             WMT 12/75
CTLG     DC    CL44'SYSCTLG'   NAME OF CATALOG DATA SET
BIGGIE   DC    H'10000'
OTVTCEND DS    H               LAST TRACK NUMBER IN OUTPUT VTOC
OUTER    DS    X              IOERROR BYTE
R0FLAG   DS    X
         DS    0D
ABSHD    DC    AL3(0)
ABSAD    DS    XL5
LSTFM1   DS    F
THIRD    DC    AL3(3),AL1(0)
ZEROES   DC    XL8'0'
OVSW     DC    X'0'            OVERFLOW SWITCH
FKEOF    DS    X
#TRKS    DS    H
FULL     DS    F
STAD     DS    F
ENDAD    DS    F
R11      DS    F
INDKAD   DS    F
OTDKAD   DS    F
DSLSTAD  DS    A
RGSAVE   DS    18F
PFMT5AD  DC    A(PFMT5)
FPFMT5AD DS    A
PFMT5    DC    (60*3)F'0'                                      DART4/78
HFLG     DS    X                        *SDS*
UHL1     DC    C'UHL1UHL2UHL3UHL4UHL5UHL6UHL7'        *SDS*
UHL8     DC    C'UHL8UTL0UTL1UTL2UTL3UTL4UTL5UTL6UTL7UTL8' *SDS*
VSAMSW   DC    X'0'                                               *BAR*
VSAMSAVE DS    XL22                                               *BAR*
INDISK   DCB   MACRF=E,DDNAME=SYSUT1,EXLST=INJFCBAD,                   +
               IOBAD=INIOB
OUTDISK  DCB   MACRF=E,DDNAME=SYSUT2,EXLST=OTJFCBAD,                   +
               IOBAD=OUTIOB
BLOCKAD  DC    F'0'
REC#     EQU   BLOCKAD+2
CCHHR    EQU   X'23'           OFFSET OF CCHHR IN IOB
FMT1     DS    140C
FMT2     DS    140C
FMT3     DS    140C
FMT5     DS    140C
VTOCOUT  DS    140C
FMT4     EQU   VTOCOUT
VTOCIN   DS    140C
DACYLS   DC    H'0,200,25,80,246,980,48,96,200,404,0,555,0,808' GJG8/76
#EXTS    DS    H
TCYL     DS    H
TRKALC   DS    H
TRKUSD   DS    H
INEXTS   DC    16D'0'
OUTEXTS  DC    16D'0'
OUTEXT   EQU   OUTEXTS
INEXT    EQU   INEXTS
DISKIN   DCB   DSORG=PS,MACRF=RP,DDNAME=SYSUT1,RECFM=F,KEYLEN=44,      +
               LRECL=96,BLKSIZE=96,EXLST=INJFCBAD
INJFCBAD DS    0F
         DC    X'87'
         DC    AL3(INJFCB)
INJFCB   DS    44F
         READ  VTOCINCB,SF,DISKIN,MF=L
DISKOUT  DCB   DSORG=DA,MACRF=(RIC,WIC),DDNAME=SYSUT2,OPTCD=R,         +
               RECFM=F,KEYLEN=44,BLKSIZE=96,EXLST=OTJFCBAD,SYNAD=IOER
OTJFCBAD DS    0F
         DC    X'87'
         DC    AL3(OUTJFCB)
OUTJFCB  DS    44F
         READ  VTCOUTDB,DI,DISKOUT,,'S',,BLOCKAD+1,MF=L
         EJECT
INIOB    DS    0D
         DC    X'42'           CC AND UNRELATED
         DS    XL3
         DC    A(INECB)
INCSW    DC    2A(0)
INCCWAD  DS    A
         DC    A(INDISK)
         DC    2A(0)
         DC    XL3'0'
INCCHH   DC    XL4'0'
         DC    X'0'
         DC    C'SQUV'
         DC    A(VTOCIN)
INCYLS   DS    H
INECB    DC    F'0'
OUTIOB   DS    0D
         DC    X'42'
         DS    XL3
         DC    A(OUTECB)
OUTCSW   DC    2A(0)
         DC    A(OUTCCW)       ADDRESS OF OUTPUT CCW
         DC    A(OUTDISK)
         DC    2A(0)
         DC    XL3'0'
OUTCCHH  DC    XL4'0'
         DC    X'0'
         DC    C'SQUV'
         DC    A(FMT4)
OUTCYLS  DS    H
OUTECB   DC    F'0'
NOREC    EQU   X'20'
OUTCCW   CCW   X'31',OUTCCHH,X'40',5   SEARCH FOR RECORD 0
         CCW   X'08',OUTCCW,0,0        KEEP LOOKING
DACCWADO CCW   X'08',0,0,0     THIS TIC WILL BE MODIFIED BY PROG
RDDACCW  CCW   X'31',INCCHH,X'40',5    LOOK FOR RECORD 0
         CCW   X'08',RDDACCW,0,0       TIC *-8
DACCWADI CCW   X'08',0,0,0     TIC TO GOTMAIN CCW
RDCNTCCW CCW   X'31',INCCHH,X'40',5    SEARCH FOR RECORD 0
         CCW   X'08',RDCNTCCW,0,0
RDCNTAD  CCW   X'80',0,0,0     WILL BE FILLED IN BY INIT ROUTINE
DATADI   DS    F               ADDRESS OF INPUT DATA
DATADO   DS    F               ADDRESS OF OUTPUT DATA
FRSTSW   DS    CL2
LSTSW    EQU   FRSTSW+1
SVR5R6   DS    2F              OTHER SAVE AREA FOR REGS 5 & 6
INR0DATA DS    CL8
         EJECT
SYSPRINT DCB   DSORG=PS,MACRF=PM,DDNAME=SYSPRINT,RECFM=FBA,LRECL=121,  +
               BLKSIZE=968
         LTORG
FREESPAC DC    16650X'00'         EVERYTHING UNALLOCATED FIRSTGJG8/76
         DC    X'FF'           TO INSURE THE END
VTOCINDB EQU   VTOCINCB
RGSAV    EQU   RGSAVE
#FREXTS  EQU   #EXTS
TRKPCYL  EQU   VTOCIN+64
#CYL     EQU   VTOCIN+62
         END ALCDS                                            WMT 04/76
