         MACRO
&NAME    #HFRAME &DIR,&N,&IMAGE
&NAME    DS   0H .
         AIF    ('&DIR' EQ 'FORWARD').FOR
         AIF    ('&DIR' EQ 'F').FOR
         AIF    ('&DIR' EQ 'BACKWARD').BAK
         AIF    ('&DIR' EQ 'B').BAK
         MNOTE 9,'DIRECTION SPECIFICATION MISSING OR INVALID'
         MEXIT
.FOR     ANOP
.*       L     R15,#SCR&N .    TO LENGTH
.*       LR    R1,R15 .        FROM LENGTH
.*       LA    R14,&IMAGE .    TRMIO IMAGE ADDRESS (TO)
.*       L     R0,#NOW&N  .    CURRENT STACK FRAME (FROM)
.**      MVCL  R14,R0
         L     R2,#LPF&N .     LINES PER FRAME
         L     R1,#MVC&N .     BYTES TO MOVE
         LA    R14,&IMAGE .    TO ADDRESS
         L     R15,#NOW&N .    FROM ADDRESS
#HFM&SYSNDX DS 0H .
         MVC   0(0,R14),0(R15) EXECUTED ZERO LENGTH MOVE
#HFL&SYSNDX DS 0H .
         EX    R1,#HFM&SYSNDX .
         LA    R14,79(R14) .    NEXT LINE
         LA    R15,79(R15) .         NEXT LINE
         BCT   R2,#HFL&SYSNDX
         L     R0,#TOP&N .     POINT TO TOP
         LR    R1,R15 .        POINT TO CURRENT
         ST    R1,#NOW&N .                         AND LIMIT IT
         C     R1,#END&N .     -RESETTING
         BNH   *+8 .                      IF
         ST    R0,#NOW&N .                   AT END
         MEXIT
.BAK     ANOP
         MEND
