         MACRO
&NAME    PFKEY  &BLOCK=IOCB,&TYPE=IOCB,&KEYGEN=NO,                     X
               &CLEAR=,&ENTER=,&ATTN=,&CNCL=,&DEF=,&SYSREQ=,           X
               &K1=,&K2=,&K3=,&K4=,&K5=,&K6=,                          X
               &K7=,&K8=,&K9=,&K10=,&K11=,&K12=,                       X
               &K13=,&K14=,&K15=,&K16=,&K17=,&K18=,                    X
               &K19=,&K20=,&K21=,&K22=,&K23=,&K24=
         COPY  DCMSGBLS
         SPACE
*                                                                     *
*        I N P U T    A N A L Y S I S                                **
*                                                                   ***
*                                            AID / PF KEY SELECTOR ****
*                                                                   ***
*                                                                    **
*                                                                     *
         SPACE
         CLI   &TYPE.AID,X'00'
         BH    PFT&SYSNDX
         CLI   &TYPE.AID,X'60'
         BH    PFT&SYSNDX
         CLI   &TYPE.AID,X'7C'
         BNH   PFT&SYSNDX
         B     PFK&SYSNDX .
PFT&SYSNDX  DS   0H .
.PKEYS   ANOP
         AIF   ('&KEYGEN' EQ '').KDFLT
.KK1     ANOP
         AIF   ('&K1' EQ '').KK2
         CLI   &TYPE.AID,AIDPF1
         BE    &K1 .                             <=====   P F K 1
.KK2     ANOP
         AIF   ('&K2' EQ '').KK3
         CLI   &TYPE.AID,AIDPF2
         BE    &K2 .                             <=====   P F K 2
.KK3     ANOP
         AIF   ('&K3' EQ '').KK4
         CLI   &TYPE.AID,AIDPF3
         BE    &K3 .                             <=====   P F K 3
.KK4     ANOP
         AIF   ('&K4' EQ '').KK5
         CLI   &TYPE.AID,AIDPF4
         BE    &K4 .                             <=====   P F K 4
.KK5     ANOP
         AIF   ('&K5' EQ '').KK6
         CLI   &TYPE.AID,AIDPF5
         BE    &K5.                              <=====   P F K 5
.KK6     ANOP
         AIF   ('&K6' EQ '').KK7
         CLI   &TYPE.AID,AIDPF6
         BE    &K6 .                             <=====   P F K 6
.KK7     ANOP
         AIF   ('&K7' EQ '').KK8
         CLI   &TYPE.AID,AIDPF7
         BE    &K7 .                             <=====   P F K 7
.KK8     ANOP
         AIF   ('&K8' EQ '').KK9
         CLI   &TYPE.AID,AIDPF8
         BE    &K8 .                             <=====   P F K 8
.KK9     ANOP
         AIF   ('&K9' EQ '').KK10
         CLI   &TYPE.AID,AIDPF9
         BE    &K9 .                             <=====   P F K 9
.KK10    ANOP
         AIF   ('&K10' EQ '').KK11
         CLI   &TYPE.AID,AIDPF10
         BE    &K10 .                            <=====   P F K 1 0
.KK11    ANOP
         AIF   ('&K11' EQ '').KK12
         CLI   &TYPE.AID,AIDPF11
         BE    &K11 .                            <=====   P F K 1 1
.KK12    ANOP
         AIF   ('&K12' EQ '').KK13
         CLI   &TYPE.AID,AIDPF12
         BE    &K12 .                            <=====   P F K 1 2
.KK13    ANOP
         AIF   ('&K13' EQ '').KK14
         CLI   &TYPE.AID,AIDPF13
         BE    &K13 .                            <=====   P F K 1 3
.KK14    ANOP
         AIF   ('&K14' EQ '').KK15
         CLI   &TYPE.AID,AIDPF14
         BE    &K14 .                            <=====   P F K 1 4
.KK15     ANOP
         AIF   ('&K15' EQ '').KK16
         CLI   &TYPE.AID,AIDPF15
         BE    &K15 .                             <=====   P F K 1 5
.KK16     ANOP
         AIF   ('&K16' EQ '').KK17
         CLI   &TYPE.AID,AIDPF16
         BE    &K16 .                             <=====   P F K 1 6
.KK17     ANOP
         AIF   ('&K17' EQ '').KK18
         CLI   &TYPE.AID,AIDPF17
         BE    &K17.                              <=====   P F K 1 7
.KK18     ANOP
         AIF   ('&K18' EQ '').KK19
         CLI   &TYPE.AID,AIDPF18
         BE    &K18 .                             <=====   P F K 1 8
.KK19     ANOP
         AIF   ('&K19' EQ '').KK20
         CLI   &TYPE.AID,AIDPF19
         BE    &K19 .                             <=====   P F K 1 9
.KK20     ANOP
         AIF   ('&K20' EQ '').KK21
         CLI   &TYPE.AID,AIDPF20
         BE    &K20 .                             <=====   P F K 2 0
.KK21     ANOP
         AIF   ('&K21' EQ '').KK22
         CLI   &TYPE.AID,AIDPF21
         BE    &K21 .                             <=====   P F K 2 1
.KK22    ANOP
         AIF   ('&K22' EQ '').KK23
         CLI   &TYPE.AID,AIDPF22
         BE    &K22 .                            <=====   P F K 2 2
.KK23    ANOP
         AIF   ('&K23' EQ '').KK24
         CLI   &TYPE.AID,AIDPF23
         BE    &K23 .                            <=====   P F K 2 3
.KK24    ANOP
         AIF   ('&K24' EQ '').KEND
         CLI   &TYPE.AID,AIDPF24
         BE    &K24 .                            <=====   P F K 2 4
         AGO   .KEND
.KDFLT   ANOP
         SPACE
*
*        DEFAULT PFK KEYNAMES / FUNCTIONS USED
*
         SPACE
         MEXIT
.KEND    ANOP
PFK&SYSNDX  EQU   *
         SPACE
.CLR     ANOP
         AIF   ('&CLEAR' EQ '').CNCLR
         CLI   &TYPE.AID,AIDCLR
         BE    &CLEAR .                          <=====   C L E A R
.CNCLR   ANOP
         AIF   ('&CNCL' EQ '').ATN
         CLI   &TYPE.AID,AIDCAN
         BE    &CNCL .                           <=====   C A N C L
.ATN     ANOP
         AIF   ('&ATTN' EQ '').ENTR
         CLI   &TYPE.AID,AIDPA1
         BE    &ATTN .                           <=====   A T T E N
.ENTR    ANOP
         AIF   ('&DEF' EQ 'YES').ENTBR
         AIF   ('&DEF' EQ 'ENTER').ENTBR
         AIF   ('&ENTER' EQ '').NER
         CLI   &TYPE.AID,AIDENT
         BE    &ENTER .                          <=====   E N T E R
.NER     ANOP
         AIF   ('&DEF' EQ 'NO').NODEF
         AIF   ('&DEF' EQ '').NODEF
         B     &DEF
.NODEF   ANOP
         AGO   .OUT
.ENTBR   ANOP
         AIF   ('&ENTER' EQ '').NOENTR
*
*        NOTE: ALL OTHER AID VALUES TREATED AS ENTER  <====   E N T E R
*
         B     &ENTER .
         AGO   .OUT
.NOENTR  MNOTE 9,'*** DEFAULT/ENTER/TYPE OPERANDS REQUIRED ***'
         MEXIT
.OUT     ANOP
         SPACE
*                                                                     *
**                                                                    *
***                                     END OF PFK SELECTION CODE     *
**                                                                    *
*                                                                     *
         SPACE
         MEND
