$cmd clearsc
$ start
Print a banner - you specify the text size and lines per page.

  1 - Introductory explanation.
  2 - Print the text.
  3 - Information on how to print banners from TSO READY mode.

Enter the number of the category you want assistance for,
or a null line to terminate this menu:
$cmd setl answer &INPUT
$cmd setl halt ''
$select
  $when answer=''
    $goto eoj
  $when answer='1'
    $cmd assist bannerd
  $when answer='2'
    $cmd assist bannere
  $when answer='3'
    $cmd assist bannerh
  $otherwise
    Only 1, 2, 3 or a null line are acceptable responses.
    $cmd setl halt 1
$* comment to delimit select.

$cmd clearsc &HALT
$goto start
