Suppose you have a report consisting of a column of equal length groups
of lines, as in the following:

A1
A2
A3
B1
B2
B3
C1
C2
C3
D1
D2
D3
E1
E2
E3

And you would like the report to appear as follows:

A1 B1 C1
A2 B2 C2
A3 B3 C3
D1 E1
D2 E2
D3 E3

This aid text will help you build a subcommand to do the above.

$cmd lo
$until answer^=''
  Enter the total number of groups in the report, e.g. in the sample
  above, the number of groups is 5:
  $input
$cmd setl g &ANSWER

$until answer^=''
  Enter the number of lines in each group, e.g. in the sample above,
  the number of lines in each group is 3:
  $input
$cmd setl h &ANSWER

$until answer^=''
  Enter the length of each group line, e.g. in the sample above,
  the length of each group line is 3:
  $input
$cmd setl l &ANSWER

$until answer^=''
  Enter the symbolic name of the report data set.  This would be the
  name you might enter on the NAME subcommand:
  $input
$cmd setl n &ANSWER

$until answer^=''
  Enter the number of groups to go in each row, e.g. in the sample
  above, the number of groups in each row is 3:
  $input
$cmd setl r &ANSWER

$cmd calc s#h*r
$cmd calc t#ceil(g/r)*r*h

Normally, at this point in AID, the generated command would be displayed
at the terminal.  But, because of a bug in TSO, this is not possible
here.

Do you want the command executed?  Enter a null line for yes.
$input
$if answer=''
  $cmd +
  apl (&T Y(&L `R &N)){((&T%&R),&R)R(&S XD(_1+I&T)%&S)+&T R,T&R &H RI&S}
Note that in order for this aid subcommand to work, it had to issue the
lo subcommand.  Would you like it to issue the hi subcommand for you?
Enter a null line for yes.
$input
$if answer=''
  $cmd hi
