Use the OL subcommand to overlay a data matrix specified by a to-LSU
with nonblank data from a data matrix specified by a from-LSU.

First you will be prompted for the to-LSU.
$cmd aid lsu
$cmd setquot tolsu lsu
$cmd setl tolsu &TOLSU
Now you will be prompted for the from-LSU.
$cmd aid lsu

The generated command is as follows:

$write &TOLSU ol &LSU

Do you want it executed?  Enter a null line for yes.
$input
$if answer=''
  $cmd &TOLSU ol &LSU
