)Attr
   ! type( text) intens(high)   SKIP(on)
   ^ type( input) intens(high) caps(off) just(asis ) pad(' ')
)Body
+---------------------% AOST Systems Flash Creation      +--------------
%Command ===>_ZCMD
+
+Enter/Verify:
+
+        Subject%===>^AOSTSUBJ                         +****
+         Number%===>_AOSTNO  +
+         Author%===>^AOSTAUTH            +****
+
+   Enter%Y+to enter/review/update text%===>_CONT+
)INIT
 &CONT = &Z
 IF (&AOSTDATE = &Z)
   &AOSTDATE = '&ZMONTH/&ZDAY/&ZYEAR'
   &AOSTNO   = TRUNC(&ZJDATE,'.')
   &AOSTNO   = .TRAIL
   &AOSTNO = F&ZYEAR&AOSTNO.A
)PROC
 VER (&AOSTSUBJ,NONBLANK)
 VER (&AOSTNO,NONBLANK,PICT,ANNNNNC)
 VER (&AOSTAUTH,NONBLANK)
 VER (&CONT,NONBLANK,LIST,Y)
 Vput (AOSTAUTH) PROFILE
)END
