%------------------------ Create USERMOD Option Menu -------------------
%COMMAND ===>_ZCMD
+
+Modified source input data set:
+    PROJECT              %===>_PROJECT
+    LIBRARY              %===>_LIBRARY
+    TYPE                 %===>_TYPE
+    MEMBER NAME          %===>_CUMEMBER+
_DEBUG
+Original source library  %===>_SMPSRC
+         macro  library  %===>_SMPMAC
+
+Element Type             %===>_SRCMAC+SRC or MAC for SMP control cards
+Allow Deletions ?        %===>_ADEL+    (Y or N)
+    Autonum Required     %===>_ANUM+    (Y or N)
+
+SMP DECK GENERATION:     %===>_SMP+     (Y OR N FOR CONTROL CARDS)
+    USERMOD id           %===>_MODID  + (aabbbcd)
+    Description          %===>_COMMENT
+
+Report Disposition:      %===>_RDISP
+
)INIT
 .HELP   = TCUMOD
 .CURSOR = CUMEMBER
 &RDISP   = TRANS(&RDISP   ' ',NEW  *,*)
 &SMP     = TRANS(&SMP     ' ',YES *,*)
 IF (&ANUMDEF = N)
      &ANUM    = N
 IF (&ANUMDEF = Y)
      &ANUM    = TRANS(&ANUM    ' ',Y *,*)
 &ADEL = N
 &AUTONUM = CUMOD
 &SRCMAC  = TRANS (&SRCMAC ' ',&Z *,*)
)PROC
 &SMP = TRUNC(&SMP,1)
 VER (&SMPMAC,NONBLANK)    VER (&SMPMAC,DSNAME)
 VER (&SMPSRC,NONBLANK)    VER (&SMPSRC,DSNAME)
 &SRCMAC = TRANS(TRUNC(&SRCMAC,1) S,SRC M,MAC *,*)
 VER (&SRCMAC,NONBLANK)     VER (&SRCMAC,LIST,SRC,MAC)
 IF (&SRCMAC = SRC)
    &OSMPSRC = &SMPSRC
 IF (&SRCMAC = MAC)
    &OSMPSRC = &SMPMAC
 VER (&MODID,NONBLANK)     VER(&MODID,PICT,AANNNCC)
 VER (&CUMEMBER,NONBLANK)  VER (&CUMEMBER,NAME)
 &MEMBER = &CUMEMBER
 VER (&ADEL,NONBLANK)      VER (&ADEL,LIST,Y,N)
 VER (&SMP,LIST,YES,NO,Y,N)
 &CUOPT = TRUNC(&SMP,1)
 IF (&ANUM = Y)
   &CUOPT = A
 &SEL = TRANS(&CUOPT
              Y      ,'PANEL(CUMODS)'
              N      ,'CMD(%CUMOD &DEBUG)'
              A      ,'PANEL(AUTONUM)'
              ' '   ,' '
              *     ,?)
)END
