)ATTR DEFAULT(%+_)
       %   TYPE(TEXT)  INTENS(HIGH)                      COLOR(TURQ)
       +   TYPE(TEXT)  INTENS(LOW)  SKIP(ON)             COLOR(GREEN)
       _   TYPE(INPUT) INTENS(HIGH) CAPS(ON)  JUST(LEFT) COLOR(WHITE)
       ~   TYPE(INPUT) INTENS(HIGH) CAPS(OFF) JUST(LEFT) COLOR(WHITE)
/** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **
/** LISTSP ISPF Command: Full-Screen Browse/Action of LISTSP Output
/** By: Mike Theys       Rockwell International
/** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **
)BODY EXPAND(||)
%-|-|-  EZ LISTSP   SAVE  DATASET LIST  -|-|
%Command ===>_ZCMD
+
+
+Data Set List: %&EZLSPIDX

+SAVE NAME:  _EZLSPSTN+
+DESCRIPTION:~EZLSPSTD                                     +
+
+Saved by:   &ZUSER
+Saved on:   &ZDATE &ZTIME
+
+
+
+Press%ENTER+to save current data set list into your EZLISTSP.TABLES dat
+Press%END+PF Key to abort the save.
+
)INIT
  &ZCMD = &Z
  .CURSOR   = EZLSPSTN
)PROC
  VER(&EZLSPSTN,NB,NAME)
)END
