%TUTORIAL -------------  MVS Bulk Data Transfer Tutorial  ------------ T
+  Command%===>_ZCMD
%
%                    ---------------------------------------
%                    ×            DTC Networks             ×
%                    ×            Introduction             ×
%                    ×             (continued)             ×
%                    ---------------------------------------
+
    %NETCOND(cond1(,cond2))+
       The NETCOND command indicates (1) what will happen to this transa
       when each predecessor completes in a successful fashion, and,
       optionally, (2) what will happen when any predecessor fails. The
       actions are indicated by one of the following:

       D - Decrement this transaction's Hold Count by 1.
       R - Do nothing to this transaction ("Retain" the Hold Count).
       F - Flush (cancel) this transaction and all of its successors.

       If NETCOND does not appear on a Network transaction, the default
       (D,D).
)PROC
 &ZUP = RBDT0000
)END
