+-------------% Rockwell Technical Proposal Creation Dialog +-----------
%Command ===>_ZCMD
+
+
+    Technical Proposal Table Dataset%===>_RTPDSN
+
+    Xerox 3700 Printer%===>_RTPDEST +
+
+  This dialog will guide the user through the creation of a Rockwell IS
+  Tehcnical Proposal Form.  If updates are required the user will be
+  allowed to update and reprint the form.  All Technical Proposals%MUST
+  printed on a Xerox DEST printer with the correct fonts.
)INIT
 .CURSOR = RTPDSN
)PROC
 VER (&RTPDSN,NONBLANK,DSNAME)
 VER (&RTPDEST,NONBLANK,NAME)
 VPUT (RTPDSN,RTPDEST) PROFILE
)END
