+-----------% Data Set and Free Space Manager 5796-PNN Tutorial +-------
%Command ===>_ZCMD
%
+Report Processing
+
+    The REPORT option provides the ability to generate a data set level
+    volume level, and volume group level report that details any
+    misutilization of DASD space.  Unutilized tracks in all defined
+    catagories are presented in the report by data set and are summariz
+    volume and volume group.
+
+    AGE and JULIANAGE select datasets by age (days or older than x date
+
+    OPTBLOCK is used to cause the 'optimum' blocksize to be reported on
+    when the Detail report is requested.
+
+    GASCHECK is used to determine the amount of 'gas' in PDS datasets.
+
+    CATCHECK is used to determine if the dataset is cataloged.
+
+    INCLUDE is used to mask datasets to be processed: ALL, INCLUDE or E
+
)PROC
)END
