PROC < member × mask > ª ,nth ³
MACRO < member × mask > ª ,nth ³
PARM < member × mask > ª ,nth ³
SRC < member × mask > ª ,nth ³

This program performs a member lookup in one or more
Partitioned Data Sets, and displays the requested member (if
found) with UPD.

PROC performs the lookup in SYS1.PROCLIB and any libraries
explicitly added by your installation (to the options data
set). If the member cannot be found, a message similar to
that produced by the PDS function is displayed.
MACRO performs similar lookup, but in SYS1.MACLIB and its
concatenations (if any)
PARM searches SYS1.PARMLIB and concatenations in OPTions data set.
SRC searches the libraries specified in ªSRCLIB³.

Instead of a member name, a mask may be specified. The first
member name matching the mask will be processed. Refer to the
PDS description for mask processing.

The "nth" parameter will continue the search until it finds the
nth match.
