TCB <jobname × job.step × .joborstep × A=hexadd><,n><,BUMP><,LOOP>

This function is deprecated, but has been kept for debugging. Under
MVS, only TCBs in the current Exhibit address space are viewable.

The TCB program formats the contents of a Task Control Block in a
fashion similar to Abend. Under MVT/VS2 the top RBs are also
formatted.
Input options are:
TCB                retrieve first TCB from the chain
TCB ,n             retrieve the "nth" TCB
Both of the above search and continue via TCBTCB
TCB jobname <,n>   retrieve the TCB containing "jobname" in the
TIOT. If "n" is used, retrieve the (n-1)Th TCB from the
first retrieved one using TCBLTC/TCBNTC/TCBOTC. If the
form "job.step" is used, both the Job and Stepname will be
tested. If the form ".joborstep" is used, the supplied
name will be used if it matches a task's job or step name
field.
TCB A=hexadd <,n> retrieve TCB at address "hexadd", if "n" is
used, descend (n-1) TCBs along TCBLTC.
Both of the above, when TCBLTC is zero, will use TCBNTC.
The search continues using TCBLTC of this task. Eventually all
TCBs in the "tree" of a task are displayed. No indication is
made of the current TCB level.
If the TCB chain is exhausted, or the requested TCB does not
exist, or if an invalid "hexadd" was used, the message
"BAD REQUEST" or "END OF TCB CHAIN" is issued. Otherwise a
reply of ENTER will repeat the previous logical request for the
next "n", except if TCB A= was used. In this case, ENTER will
refresh the current display. To use ENTER to descend from the
current TCB, set BUMP mode. The LOOP operand functions the
same as would a LOOP command.
After a display, additional input may be given :
& or + display next TCB
* or PA1 key hold display on this TCB
- or BACK display previous TCB
LOOP/NOLOOP set/reset LOOP mode
BUMP/NOBUMP set/reset BUMP mode (next TCB on ENTER)
LTC display subtask of this TCB
NTC display sister task
OTC display originating TCB
JSTCB display Jobstep TCB of current task
TOP display highest TCB (since start of request or since
last JSTCB request)
TCB if followed by text, taken as a TCB command; if last
request on input, displays TCBTCB.
