%TUTORIAL------------------------ LIST CATALOG -------------------------
%OPTION  ===>_ZCMD
%                          --------------------------
                           ×  General Introduction  ×
                           --------------------------

+FSLISTC stands for  Full-Screen List  Catalog.  It builds and displays
 information for  datasets  beginning  with  a specified  catalog  prefi

+Information displayed  for each dataset includes  allocation informatio
 in Tracks  (i.e., number of  tracks allocated,  percentage of space  us
 the number of  extents used), and  dataset attribute  information (i.e.
 RECFM, LRECL, and BLKSIZE).

+From the LIST  CATALOG display,  numerous  functions can  be performed
 datasets listed.  These include invoking Enhanced Edit/Browse for the d
 obtaining  a PDS Member  List for a parititioned dataset, renaming or d
 datasets, or compressing/releasing datasets.
)PROC
   &ZUP = DST@FC00
)END
