%TUTORIAL------------------  SCAN PDS / MEMBER LIST  -------------------
%OPTION  ===>_ZCMD
%                            -----------------------
                             ×  Rename and Delete  ×
                             -----------------------

+The%R+Select Code is used to rename a member. Give the new name for the
 in the "RENAME" column of  the display.  (Recall that all member functi
 be invoked from the COMMAND  line by entering  the Select code followed
 member name;  for Rename,  enter the Select Code, the member name, and
 member name.)

+To delete a PDS member  from the Member List, enter the three-character
 Code%DEL+ ("D" was  not chosen as the  Select Code  for Delete  because
 proximity to  "E" on the  keyboard).  Note  that the Equals sign (=) is
 valid Select Code; it means to use the Select Code from the previous me
 the Member List that had a Select Code. You can use this Select Code to
 many members  at a time by  using the "DEL"  Select Code for the first
 and then the "="  Select Code  for the other  members (i.e., it saves y
 having to type "DEL" for each one).
)PROC
  &ZUP = DST@SC40
)END
