         MACRO
         IECDXFRR
FRREXCP  DSECT                                                 @ZA12704
************************************************************** @ZA12704
*        IECVEXCP/IECVEXPR FRR PARM AREA DSECT.              * @ZA12704
*        DSECT DESCRIBES USAGE OF THE 6 WORD FRR PARM AREA   * @ZA12704
*                                                            * @ZA12704
************************************************************** @ZA12704
FRRCRQE  DS    A         CURRENT  RQE POINTER                  @ZA12704
FRRPRQE  DS    A         PREVIOUS RQE POINTER                  @ZA12704
FRRSTRG  DS    A         FREE 160B BLOCK POINTER               @ZA12704
         SPACE 1                                               @ZA12704
FRRFLAG  DS    X         EXCP PROCESSING FLAGS                 @ZA12704
FRRFTE   EQU   X'80'     FRONT END ENTRANCE                    @ZA12704
FRRBKE   EQU   X'40'     BACK END ENTRANCE                     @ZA12704
FRRPCI   EQU   X'20'     PCI APPENDAGE PROCESSING              @ZA12704
FRRCHE   EQU   X'10'     CHANNEL END APPENDAGE PROCESSING      @ZA12704
FRRABE   EQU   X'08'     ABNORMAL END APPENDAGE PROCESSING     @ZA12704
FRREOE   EQU   X'04'     END OF EXTEND APPENDAGE PROCESSING    @ZA12704
FRRPGFX  EQU   X'02'     PAGE FIX APPENDAGE PROCESSING         @ZA12704
FRRAACT  EQU   X'01'     APPENDAGE IS ACTIVE                   @ZA12704
FRRSIO   EQU   X'00'     START I/O APPENDAGE PROCESSING        @ZA12704
*                                                              @ZA12704
FRREXPR  EQU   X'3E'     EXPR ENTRY FOR PURGING OR FRR TERM    @ZA12704
         SPACE 1                                               @ZA12704
FRRTCNT  DS    X         RQE XLATE CTR AND SMGR INTF FLAGS     @ZA12704
*        EQU   X'80'     RESERVED                              @ZA12704
FRRXLTA  EQU   X'40'     RQE TRANSLATION ACTIVE                @ZA12704
FRRXLT   EQU   X'30'     2 BIT RQE XLATE COUNTER (0-3)         @ZA12704
FRRGETR  EQU   X'08'     STORAGE MANAGER GET REQUEST           @ZA12704
*        EQU   X'04'     STORAGE MANAGER RESERVED BIT          @ZA12704
FRR40    EQU   X'02'     STORAGE MANAGER 40B (MED) REQUEST     @ZA12704
FRR160   EQU   X'01'     STORAGE MANAGER 160B (LGE) REQUEST    @ZA12704
*                                                              @ZA12704
FRRG40   EQU   X'0A'     40 BYTE GET REQUEST                   @ZA12704
FRRF40   EQU   X'02'     40 BYTE FREE REQUEST                  @ZA12704
FRRG160  EQU   X'09'     160 BYTE GET REQUEST                  @ZA12704
FRRF160  EQU   X'01'     160 BYTE FREE REQUEST                 @ZA12704
         SPACE 1                                               @ZA12704
FRRFCNT  DS    X         COUNT OF CHAINED 160 B BLOCKS TO FREE @ZA12704
FRRWORK  DS    X         WORK BYTE AND FLAG DEFINITIONS        @ZA12704
*        EQU   X'F0'     WORK BITS                             @ZA12704
FRRPTERM EQU   X'08'     POST STATUS TERMINATION ENTRY         @ZA12704
FRRRRP   EQU   X'04'     PURGE REL REQ RQES TO CURRENT RQE     @ZA12704
FRRUNREL EQU   X'02'     IOBUNREL BIT                          @ZA12704
*        EQU   X'01'     RESERVED                              @ZA12704
         SPACE 1                                               @ZA12704
FRRRETR  DS    A         CALLERS RETURN ADDRESS                @ZA12704
FRRLLSA  DS    A         LOCAL LOCK SAVE AREA POINTER          @ZA12704
         SPACE 1                                               @ZA12704
FRRXLEN  EQU   *-FRREXCP      FRR PARM AREA LENGTH             @ZA12704
         MEND
