.cm SCRIPT REFERENCE OF
.SUBT Purpose
The OFFSET control word causes all but the first line of a section to
be indented.
.SUBT Format
×
×  .OF           <0_×n×+n×-n>
×
.SUBT Usage
The .OF control word is used to indent the left side of the printout
"n" spaces _a_f_t_e_r printing the next output line.
The extra indentation remains in effect until another .HI, .IN
or .OF control word is encountered.
An operand of the form "+n" adds
the value n to the current offset setting.  An operand of the
form "-n" subtracts the value n from the current offset setting.
.sp 1
The .OF control word may be used within a section which is also
indented with the .IN control.  Any subsequent .IN
control word causes the indentation set by .OF to be cleared.
.sp 1
If it is desired to start a new section with the same offset as the
previous section, it is necessary to repeat
the .OF request.
.SUBT Defaults
This command does create a break when encountered.  If
no argument is supplied then _n = 0 will be assumed.
.SUBT Notes
.of 4
(1) If the following sequence is input:
.sp 1
     .of _m
     <text>
     .of _n
     <text>
.sp 1
The second offset will be added to the first if n_ is a signed
integer.  If n_ is unsigned,
this addition will not occur.  Phrased differently: if n_ is signed,
all but the first line of the first section
together with the first line of the second section will be indented
_m spaces and all
but the first line of the second section will be indented
m_
.sp 1
.of 4
(2) If HANGING INDENT is in effect, an OFFSET control word
will override the next time the HANGING INDENT is to be used.
.cp 16
.SUBT Examples
.FNADD
.of 4
.ur (1) Many of the sections of this manual&LP
.fn begin
.in
.ur .of &OFN
.ur (&NFN.) Including the example text.
.fn end
are produced by a sequence like this:
.sp 1
.in 15
.nf
 <section header>
 .in 5
 .of 4
 (1) <text>
 .of 4
 (2) <text>
    .
    .
    .
 .in
.cm End of OF
