***********************************************************************
*
*        MODULENAME  : IPLDATE
*
*        DESCRIBTION : IPLDATE VERIFIES THE DATE ENTERED BY THE
*                      OPERATOR DURING IPL. IT INFORMS THE OPERATOR
*                      ABOUT THE STATUS OF THE DATE.
*
*        FUNCTION    : IPLDATE IS CALLED DURING NIP AFTER THE OPERATOR
*                      REPLIED WITH 'U' IN RESPONSE TO MESSAGE IEA888A.
*                      FIRST  > IT CHECKS THAT NO DIFFERENCE EXISTS
*                      BETWEEN THE LOCAL- AND GMT- TIME/DATE.
*                      SECOND > IT READS IN THE DATE FROM LAST IPL AND
*                      CALCULATES THE DIFFERENCE BETWEEN THIS DATE AND
*                      THE DATE FROM THE CURRENT IPL.
*                      THIRD  > IT INFORMS THE OPERATOR ABOUT THE
*                      STATUS OF THE DATE AND LET HIM DECIDE IF HIS
*                      ENTERED DATE IS GOOD OR BAD.
*                      FORTH  > IF THE DATE IS GOOD, IT IS WRITTEN TO
*                      DISK AND THE IPL CAN CONTINUE. IF THE DATE IS IN
*                      ERROR, THE SYSTEM IS SET IN THE WAIT STATE AND
*                      THE OPERATOR SHOULD RE-IPL THE SYSTEM.
*
*        INSTALLATION: THE ID FOR THIS USERMOD IS OBRIPF0. ALL
*                      NECESSARY INFORMATION FOR A SUCCESSFULL IN-
*                      STALLATION CAN BE FOUND IN THE SYS4.LIB.___
*                      LIBRARIES.
*                      usermod obripf0:
*                       LINK IPLDATE  INTO SYS1.NUCLEUS(IEANUC01)
*                       LINK IPLDATED INTO SYS1.LINKLIB(IPLDATED)
*                      usermod obrip00:
*                       ZAP MODULE SYS1.LPALIB(IEAVRTOD)
*                      usermod obrcvt0:
*                       add user-cvt at the end of system-cvt
*
*                      IPL THE SYSTEM WITH OPTION 'CLPA'
*
***********************************************************************
