*        %GOTO PLSSBT;                  /* BILINGUAL HEADER
         MACRO
         TSBTD
IEDQSBTD DSECT
.* A000000-999999                                              @YM07020
SBTFLAGS DS    X                        FUNCTION FLAGS
SBTECBN  EQU   X'80'                    REQUEST ECB POST WHEN COMPLETE
SBTBFRTN EQU   X'40'                    RETURN BFR CONTAINING PARM
*                                        LIST TO BFR RETURN WHEN
*                                        COMPLETE
SBTOI    EQU   X'20'                    PERFORM OR FUNCTION
SBTNI    EQU   X'10'                    PERFORM AND FUNCTION
*              X'08'-X'01'              RESERVED
SBTQCBA  DS    AL3                      QCB ADDRESS
SBTPRI   DS    X                        PRIORITY
SBTLINK  DS    AL3                      LINK FIELD
         DS    A                        BUFFER TIC FIELD
SBTDATA  DS    X                        BIT CONFIGURATION FOR OR/AND
*                                        FUNCTION
SBTADDR  DS    AL3                      ADDRESS OF BYTE FOR OR/AND
*                                        FUNCTION
SBTECB   DS    A                        OPTIONAL ECB FOR POST
         MEND  ,   */
*%PLSSBT:  ;
*DECLARE                                /* IEDQSBT PARAMETER LIST    */
*  1 IEDQSBTD  BASED(IEDQSBTR),         /* PARM LIST                 */
*   2 SBTFLAGS     BIT(8),              /* FUNCTION FLAGS            */
*    3 SBTECBN      BIT(1),             /* REQUEST ECB POST WHEN
*                                          COMPLETE                  */
*    3 SBTBFRTN     BIT(1),             /* RETURN BFR CONTAINING PARM
*                                          LIST TO BFR RETURN WHEN
*                                          COMPLETE                  */
*    3 SBTOI        BIT(1),             /* PERFORM OR FUNCTION       */
*    3 SBTNI        BIT(1),             /* PERFORM AND FUNCTION      */
*    3 *            BIT(4),             /* RESERVED                  */
*
*   2 SBTQCBA      PTR(24),             /* QCB ADDRESS               */
*
*   2 SBTPRI       CHAR(1),             /* PRIORITY                  */
*   2 SBTLINK      PTR(24),             /* LINK FIELD                */
*
*   2 *            PTR(31),             /* BUFFER TIC FIELD          */
*
*   2 SBTDATA      BIT(8),              /* BIT CONFIGURATION FOR
*                                          OR/AND FUNCTION           */
*   2 SBTADDR      PTR(24),             /* ADDRESS OF BYTE FOR
*                                          OR/AND FUNCTION           */
*   2 SBTECB       PTR(31);             /* OPTIONAL ECB FOR POST     */
*
*
