                         THE SAD SYSTEM
THE SAD (SYSTEM FOR ANALYSING DATA) SUITE CONSISTS OF TWO DATA SETS: A
DIRECT ORGANISATION DATA SET TO HOLD DATA TO BE ANALYSED AND A
PARTITIONED DATA SET TO HOLD THE LOAD MODULES OF PROGRAMS AND ROUTINES.
THE DIRECT DATA SET - FOR USER'S DATA - MAY CONTAIN UP TO 10**6 FLOATING
POINT NUMBERS IN THE FORM OF MATRICES. THERE IS AN UPPER LIMIT OF 100
MATRICES ON THE SYSTEM. LIBERAL USE SHOULD THUS BE MADE OF THE DELETE
AND DUMP/RESTORE FEATURES*.
THE PROGRAMS ARE CALLED BY A SET OF USER CODES AND PROVIDE FACILITIES
TO CARRY OUT OPERATIONS OF A STATISTICAL, MANIPULATORY, OR I/O NATURE
ON THESE MATRICES. THE SYSTEM IS WRITTEN IN FORTRAN. A LIST OF THE
OPERATION CODES WITH COMMENTS ON THEIR FUNCTIONS IS PROVIDED.
* DELETES IN SAD UNFORTUNATELY HAVE A BUILT-IN 'TIDY' OF THE DIRECT
ACCESS DATA SET. FILES SHOULD THUS BE DELETED FROM THE END. DELETES
SHOULD NEVER BE CANCELLED WHILE IN OPERATION.
1.0 SET-UP OF SYSTEM
         THIS REQUIRES:
    1.1  RESTORING THE SADLIB PROGRAM LIBRARY FROM DISK
    1.2  RUNNING THE SAD INITIALISATION DECK WHICH SETS UP A
         DIRECT ACCESS DATA SET CAPABLE OF HOLDING 10**6 FLOATING
         POINT NUMBERS ON A 2314 DISK PACK (ABOUT 30 CYLS.).
         THIS JOB TAKES ABOUT 15 MINS. TO RUN.
    1.3  OBTAINING A PASSWORD FOR FUTURE USE. TO DO THIS,
         ANY JOBUSING SAMPLE RUN DECK PROVIDED, MAY BE
         RUN WITH THE SECOND CARD AFTER THE SYSIN BLANK,
         EXCEPT FOR 1 IN COL. 1, (SAY WITH OPCODE 003).
         NOTE THAT VOLUME NAMES MUST BE CHANGED FIRST TO
         SUIT THE INSTALLATION. THE 8 CHR. PASSWORD MUST
         BE PUNCHED IN COLS 7-14 OF THE BLANK CARD AND
USED FOR ALL FUTURE RUNS WITH THE SYSTEM.
3.0 INSTRUCTIONS FOR OP-CODE USAGE
    3.1  OPCODE 004
         THIS OPCODE IS FOR DUMPING TO DISK/TAPE FROM SAD.
         LAYOUT:  1ST CARD   004 IN COLS. 1-3
                  2ND CARD   MATRIX NAME IN COLS. 1-10
                             1 IN COL. 14
         THIS OPCODE IS ASSOCIATED WITH A UNIQUE 'FT' CARD - FT12F001.
         THUS 1 MATRIX ONLY CAN BE DUMPED PER SET OF J.C.L., UNLESS
         USE IS MADE OF THE LAST DIGIT IN THE FT SEQUENCE, BUT THIS
         TECHNIQUE HAS NOT BEEN TESTED.
         THE DCB PARAMETER USED WITH FT12 IS AS FOLLOWS:
         DCB = (RECFM = VS, LRECL = N X 4 + 4, BLKSIZE = N X 4 + 8)
             WHERE N = NO. OF COLS. IN THE MATRIX.
         THIS GIVES UNBLOCKED DATA, COMPATIBLE WITH THE 117 OPCODE FOR
         READING THE MATRIX BACK INTO SAD AGAIN.
3.2 OPCODE 117
         THIS OPCODE IS FOR READING DISK R TAPE FILES INTO SAD, IN
         PARTICULAR 004 OPCODE OUTPUT.
         LAYOUT:  1ST CARD   117 COLS. 1-3
                  2ND CARD   MATRIX NAME COLS. 1-10
                             1 COL. 14
                  FT NUMBER (E.G. 20) COLS. 16, 17.
                  NO. OF COLS. IN MATRIX COLS. 19-21
         DCB PARAMETER ON THE FT IS AS FOR 004.
4.0 CONTROL DECKS
    4 SAMPLE CONTROL DECKS ARE SUPPLIED:
    4.1  SYSTEM INITIALISE
    4.2  DICTIONARY PRINT
    4.3  SAMPLE JOB J.C.L.
    4.4  SAMPLE TIDY
5.0 OPERATIONAL RESTRICTIONS
         THERE ARE 2 INPORTANT OPERATIONAL RESTRICTIONS ON THE SYSTEM:
    5.1  007 OPCODE
         USE OF THE OPCODE HAS BEEN DISCONTINUED. ITS FUNCTION WAS TO
         DELETE ALL TEMPORARY FILES. ALWAYS MAKE FILES PERMANENT WHEN
         WORKING WITH SAD (1 IN COL. 19 WITH OPCODE 002 AND
                           1 IN COL. 14 WITH OPCODE 117), AND USE
         006 TO DELETE FILES AS REQUIRED.
    5.2  006 OPCODE
         IT WAS FOUND NECESSARY TO DO ALL DELETES AS SPECIAL JOBS -
         TIDY JOBS. DELETES COMPRESS THE FILE SO THEY SHOULD BE DONE
         FROM END UPWARDS, AS DEPICTED IN DICTIONARY PRINT OUTPUT.
         ATTEMPTS TO DELETE AMBEDDED FILES CAN BE TIME CONSUMING.
         IF A DELETE EXCEEDS ITS TIME AND IS CANCELLED, THE WHOLE DIRECT
         DATA SET IS LOST. THIS WAS THE REASON FOR DOING DELETES AS
         SPECIAL JOBS - 'TIDY' JOBS - WITH INSTRUCTIONS THAT THEY NEVER
         BE CANCELLED.
    5.3  KEEP NUMBER OF MATRICES IN THE SYSTEM     100.
    5.4  KEEP NO. OF COLUMNS IN ANY ONE MATRIX     100.
    5.5  USE DICTIONARY PRINT REGULARLY.
2.0  LIST OF OPCODES
       001
       002              READ A MATRIX FROM CARDS INTO SAD
       03               PRINT A MATRIX FROM SAD
       004              OUTPUT A MATRIX TO PUNCH, DISK OR TAPE, DEPENDIN
                        ON INPUT PARAMETERS
       05               GRAPHS A MATRIX
       006              DELETE A FILE
       007              TERMINATION CODES - DELETES TEMPORARY FILES OUT
                        THE SYSTEM
       008              LISTS NAMES AND DIMENSIONS OF ALL FILES IN THE
                        SYSTEM
       009              CHANGE FILE MODE
       110              COLUMN/ROW MANIPULATION OF MATRIX. DOES ARITHMET
                        OPERATIONS ON A ROW OR COLUMN OVERWRITING THE OR
       111              EXTRACT COLUMNS/ ROWS FROM A MATRIX TO FORM A NE
                        MATRIX
       112              ROW OR COLUMN MERGE OF TWO MATRICES
       114              DISCRIMINANT ANALYSIS
       115              REGRESSION ANALYSIS
       116              STEPWISE MULTIPLE REGRESSION
       117              READ FILE FROM DISK OR TAPE INTO SAD
       119              CROSS CLASSIFICATION OF RANGES IN TWO VARIABLES
       120              INVERTS A MATRIX     30 WIDE
       121              FORMS I - S GIVEN S
       112              TO MULTIPLY A MATRIX BY A VECTOR TO FORM A NEW
                        OUTPUT VECTOR
       123              SUBTRACTS 2 COLUMN VECTORS
       124              TO PERFORM ELEMENT BY ELEMENT MULTIPLICATION OF
                        PERFORM 3ROWS OF A MATRIX BY A VECTOR
SECTION A.10
                               SAD21
PURPOSE: TO FORM FROM A MATRIX S A MATRIX OF THE FORM (I-S)
SUBROUTINE CALL: CALL SAD21
TASK CARD
CARD COLUMN              FIELD DESCRIPTION               NOTES
   1 - 10            NAME = DATA FILE NAME         MAX. 10 COLS. ALPHAME
SECTION A.10
                             SAD21
PURPOSE: TO FORM FROM A MATRIX S A MATRIX OF THE FORM (I-S)
SUBROUTINE CALL: CALL SAD21
TASK CARD
CARD COLUMN          FIELD DESCRIPTION             NOTES
   1 - 10            NAME = DATA FILE NAME         MAX. 10 COLS.
                                                   ALPHAMERIC
SECTION A.11
                             SAD22
PURPOSE: TO MULTIPLY A MATRIX BY A VECTOR
SUBROUTINE CALL: CALL SAD22
TASK CARD
CARD COLUMN          FIELD DESCRIPTION                    NOTES
   1 - 10            NAME = INPUT MATRIX           MAX. 10 COLS ALPHAMER
  11 - 20            NAME1 = INPUT VECTOR          MAX. 10 COLS ALPHAMER
  21 - 30            NAME2 = OUTPUT VECTOR         MAX. 10 COLS ALPHAMER
SECTION A.12
                             SAD23
PURPOSE: TO SUBTRACT TWO COLUMN VECTORS
SUBROUTINE CALL: CALL SAD23
TASK CARD
CARD COLUMN            FIELD DESCRIPTION                   NOTES
   1 - 10            NAME1 = SECOND VECTOR         MAX. 10 COLS ALPHAMER
  11 - 20            NAME2 = FIRST VECTOR          MAX. 10 COLS ALPHAMER
SECTION A.13
                             SAD24
PURPOSE: TO PERFORM ELEMENT BY ELEMENT MULTIPLICATION
SUBROUTINE CALL: CALL SAD24
TASK CARD
CARD COLUMN            FIELD DESCRIPTION              NOTES
   1 - 10            NAME = INPUT MATRIX           MAX. 10 COLS ALPHAMER
  11 - 20            NAME2 = INPUT VECTOR          MAX. 10 COLS ALPHAMER
    21               N = NUMBER OF ROWS TO BE      MAX. VALUE N CAN TAKE
                         USED IN MULTIPLICATION    PRESENT IS 3
  22 - 27            M SPECIFIES ROW NUMBERS FOR   NUMBER OF ROWS TO BE
                      MULTIPLICATION               DEPENDS ON N
                 PROGRAMME SPECIFICATION FOR "SAD"SYSTEM - JUNE 1970
OPERATION  CODE   C.C.        CARD OF OP.          FIELD DESCRIPTION
CARD-READ  002    1-3     1         READ A DATA FILE FROM CARDS TO DISK
                  1-10    2         DATA FILE NAME
                 12-15              NO. OF ROWS OF DATA (RECORDS)
                   17               1 = READ ONLY FILE
                   18               1 = PRIVATE FILE
                   19               1 = PERMANENT FILE
                 21-23              NO. OF COLUMNS OF DATA (ELEMENTS/REC
                          3 AND SUBSEQUENT CARDS = DATA WITH SINGLE
                            SPACE AT LEAST OF 'END OF CARD' BETWEEN
                            EACH ELEMENT.
PRINT      003    1-3     1         PRINT A DATA FILE
                  1-10    2         DATA FILE NAME
                   11               1 = REPEAT FLAG
GRAPH      005    1-3     1         DRAW A GRAPH
                    1     2         NO. OF COLUMNS TO BE GRAPHED (MAX =3
                    3               0 = CURVES SUPERIMPOSED
                                    1 =   "   SEPARATE
                                    2 =   "   SUPERIMPOSED
                  1-10    3         DATA FILE NAME
                 12-14              COLUMN NO. OF DATA FILE
                 16-19              = NUMBER OF POINTS TO BE PLOTTED
                                    -1 = ALL POINTS
      NOTE:  THE THIRD CARD IS REPEATED UP TO 3 TIMES
             I.E. FOR EACH COLUMN REQUIRED IN C.C.1 CARD 2.
OPERATION  CODE  C.C.     CARD OF OP.                 FIELD DESCRIPTION
DELETE     006   1-3      1         DELETE A DATA FILE
                 1-10     2         DATA FILE NAME
                  11                1 = REPEAT FLAG
JOB-END    007   1-3      1         TERMINATE SESSION
LIST-FILES 008   1-3      1         LIST NAME, DIMENSIONS OF ALL FILES
MODE       009   1-3      1         CHANGE FILE MODE
                 1-10     2         DATA FILE NAME
                  11                1 = REPEAT FLAG
                  12                1 = READ ONLY
                  13                1 = PRIVATE
                  14                1 = PERMANENT
OPERATION CODE  C.C.       CARD OF OP.                   FIELD DESCRIPTI
ARITHMETIC 110   1-3           1        COLUMNS/ROWS ARITHMETHICAL MANIP
                  1-10         2        DATA FILE NAME
                   11                   1 = COLUMN'S OPERATION
                                        2 = ROWS       "
                  12-13                 = NO. OF OPERATIONS
                                          4 PER CARD
OPERATION  A     B     C     D
   C1     1- 3 = 21-23 = 41-43 = 61-63
  C2      4- 6 = 24-26 = 44-46 = 64-66  C1 = C2 OP C3
  OP      (-8 = 27-28 = 47-48 = 67-68   C3 MAY CONTAIN DECIMAL POINT
  C3      9-20 = 29-40 = 49-60 = 69-70
OP.CODE   COLUMN'S OPERATION        OP.CODE         ROWS OPERATION
   11     ADD TWO COLUMNS               51          ADD TWO ROWS
   12     SUBTRACT TWO COLUMNS          52          SUBTRACT TWO ROWS
  13      MULTIPLY TWO COLUMNS          53          MULTIPLY TWO ROWS
  14      DIVIDE TWO COLUMNS            54          DIVIDE TWO ROWS
  21      ADD COLUMN TO CONSTANT        61          ADD ROW TO CONSTANT
  22      SUBTRACT CONSTANT FROM COLUMN 62          SUBTRACT CONSTANT FR
  23      MULTIPLY COLUMN BY CONSTANT   63          MULTIPLY ROW BY CONS
  24      DIVIDE COLUMN BY CONSTANT     64          DIVIDE ROW BY CONSTA
  93      RECIPROCAL OF COLUMN          NOTE:
  94      SQUARE-ROOT OF COLUMN         ABOVE OPERATIONS CAN ONLY BE APP
  95      LOGARITHM OF COLUMN           TO MATRIX AS IT IS - I.E. IT CAN
  96      ARCSINE OF COLUMN             BE USED TO GENERATE A NEW COLUMN
  97      EXPONENTIAL OF COLUMN         THEREBY INCREASING MATRIX SIZE.
  25      BLOCK COLUMN ADDITION    C2 = START COLUMN NO.  C3 = FINISH CO
  55      BLOCK ROW ADDITION        C2 = START ROW NO.    C3 = FINISH RO

EXTRACT   111   1-3        1            EXTRACT COLUMNS/ROWS FROM A FILE
                1-10        2           OUTPUT DATA FILR NAME
                 11                     1 = COLUMNS
                                        2 = ROWS
               12-13                    NUMBER OF SI TO BE EXTRACTED.  S
                                        MAY BE ROWS/COLUMNS BUT IS NOT
                                        NECESSARILY THE NUMBER OF ROWS/
                                        COLUMNS. SEE INCLUSIVE RANGE OF
                                        ABILITY ABOVE.
               14-23                    INPUT DATA FILE NAME.
          24-26, 27-29, 30-32, 33-35,   SI = USUALLY ROW OR COLUMN
          36-38, 39-41, 42-44, 45-47,       NUMBER. WHEN = -1 NEXT
          48-50, 51-53, 54-56, 57-59,       TWO SI ARE AN INCLUSIVE RANG
          60-62, 63-65, 66-68, 69-71.
                 24-71          3       SI IF I IS GREATER THAN 16.
                   11           3       3 = END EXTRACT SESSION IF I LES
                                        16, OTHERWISE ON 4TH/5TH CARDS
                                        DEPENDING ON I.
NOTES:
SAME FILE NAME CAN BE USED FOR OUTPUT/INPUT THE INPUT FILE BEING OVER-WR
SI - I CANNOT EXCEED 99; NUMBER OF ROWS OR COLUMNS MUST NOT EXCEED 500.
OPERATION      CODE   C.C.        CARD OF OP.                FIELD DESCR
MERGE          112    1-3               1         MERGE TWO FILES
                      1-10              2         FIRST DATA FILE NAME
                     11-20                        SECOND DATA FILE NAME
                       21                         1 = MERGE COLUMN-WISE
                                                  2 = MERGE ROW-WISE
                     22-24                        OUTPUT DATA FILE NAME
                       21               3         3 = END OF MERGE SESSI
NOTE: THE SECOND CARD IS REPEATED FOR EACH MERGE IN ANY ONE SESSION.
      IF THERE IS MORE THAN ONE MERGE CARD 3 IS LAST CARD OF SESSION.
      SAME FILE CAN BE USED FOR INPUT/OUTPUT THE INPUT FILE BEING
      OVER WRITTEN.
DISCRIMINANT   114    1-3               1         DISCRIMINANT ANALYSIS
                      1-10              2         DATA FILE NAME
                     11-13                        NO. OF ANALYSES
                     14-70                        TITLE
                      1-3               3         FIRST ROW OF FIRST GRO
                      4-6                         NUMBER OF ROWS IN FIRS
                      7-9                         FIRST ROW OF SECOND GR
                     10-12                        NUMBER OF ROWS IN SECO
                      ETC. UP TO 10 GROUPS MAY BE DEFINED.
                      1-3               4         COLUMN NO. OF FIRST VA
                      4-6                         COLUMN NO. OF SECOND V
                       ETC. UP TO 20 VARIABLES MAY BE SELECTED.
NOTE:  CARD 4 IS REPEATED FOR EACH ANALYSIS.
OPERATION CODE   C.C.          CARD OF OP.                FIELD DESCRIPT
REGRESSION 115 1-3             1       REGRESSION ANALYSES
               1-10            2       INPUT DATA FILE NAME
               11-12                   NO. OF ANALYSES
               13-80                   TITLE
                 2             3       1 = RESIDUALS REQUIRED
                3-4                    COLUMN NO. OF DEPENDENT VARIABLES
                5-6                    NUMBER OF INDEPENDENT VARIABLES
                7-8                    COLUMN NO. OF 1ST INDEPENDENT VAR
                9-10                   COLUMN NO. OF 2ND INDEPENDENT VAR
NOTE:           ETC.
      CARD 3 IS REPEATED FOR EACH ANALYSIS. PROGRAM WILL TAPE 40 VARIABL
STEP-WISE  116 1-3             1       STEPWISE MULTIPLE REGRESSION.
               1-10            2       DATA FILE NAME.
               11-12                   NO. OF SELECTIONS.
               13-18                   0.0 IF ALL VARIABLES ARE TO BE
                                       INCLUDED IN REGRESSION.
                 19                    1 = RESIDUALS REQUIRED.
               20-80                   TITLE.
                 1             3       SP. = INDEPENDENT VARIABLE TO BE
                                           CHOSEN BY PROGRAM.
                                       1 = INDEPENDENT VARIABLE FORCED B
                                          THE USER TO ENTER REGRESSION.
                                       2 = VARIABLE TO BE DELETED.
                                       3 = DEPENDENT VARIABLE.
                 2                     AS FOR C.C. 1
                 3                     AS FOR C.C. 1
                ETC. 1 C.C. FOR EACH COLUMN OF FILE UP TO 35 COLUMNS.
DISK-READ  117  1-3            1       EXTRACT FILE FROM DISC.
                1-10           2       DATA FILE NAME (INPUT).
                 12                    1 = READ ONLY
                 13                    1 = PRIVATE
                 14                    1 = PERMANENT
               16-17                   FILE NO. JCL
               19-21                   NO. OF COLUMNS.
NOTES:
THIS OPERATION CAN ONLY BE USED WITH JV
THIS OPERATION CAN ONLY BE USED WITH JCL REFERENCE CARD. TO DATE:TRAIN =
BUS = 13; 14 = RAIL SURVEY; 15 = MRBI HH FILE; 16 = MRBI TRIPS FILE.
OPERATION CODE C.C.           CARD OF OP.             FILE DESCRIPTION
CLASSIFY  119  1-3             1       CLASSIFICATION + HISTOGRAM
                1-10           2       DATA FILE NAME
                 11                    1 = REPEAT FLAG
                 12                    0 = HISTOGRAM OF 1 COLUMN
                                       1 = CLASSIFY 1 COLUMN
                                       2 = TWO-WAY TABLE
               13-13                   NO. OF LOGICAL TESTS
                 15                    1 = FREQUENCY TABLE REQUIRED
                 16                    1 = EXPECTED FREQUENCY
                 17                    1 = SUMMATION OF COLUMN WITHIN EA
                 18                    1 = MEAN OF COLUMN WITHIN EACH CE
                 19                    1 = STANDARD DEVIATION WITHIN EAC
               20,22                   VARIABLE NUMBER TO BE ANALYSED BY
                                       OPERATION IN C.C. 17-19. MUST BE
                                       NON-ZERO OPTIONS 17-19 REQUESTED
                                       OR NOT.
               23-80                   TITLE
                1-3            3       COLUMN NO.
                5-6                    N = NO. OF INTERVALS
                7-12                   UP TO 10 INTERVAL POSTS = N - 1
                 .
                 :
                 :
               61-66
                7-12           4       REQUIRED ONLY OF N IS GREATER THA
                 :
                 :
               55-60
1-3=17-19=33-35=49-51=65-67    5       COLUMN NO.
 4 = 20 = 36 = 52 = 68                 TYPE 0 = SUP. VALUE
                                           1 = INC. VALUE
                                           2 = SUP. RANGE
                                           3 = SUP. VALUE
5-10=21-26=37-42=53-58=69-74           VALUE/LOWER LIMIT OF RANGE
11-16=27-32=43-48=59-64=75-80          VALUE/UPPER LIMIT OF RANGE
NOTES: CARD 3 (AND 4 IF NECESSARY) MAY OCCUR TWICE IN A SINGLE ANALYSIS
C.C. 12
       IN CARD 2 = 2. CARD 5 ONLY OCCURS IF C.C. 13,14 IN CARD 2 IS POSI
MAXIMUM
       LOGICAL TESTS = 10.
       IF REPEAT FLAG IS USED NO NEED TO RE-CODE DATA FILE NAME.
         FOUR SAMPLE JOBS ARE PROVIDED
  U11000BJ  DICTIONARY PRINT
  U11000CJ  SAMPLE JOB
