* PROCESS  A,X,AG,LIST,MAP,OPT(TIME),STG;
 /*      ZAJL2 - FORM NODE TABLE FROM PARAMETER CARDS                */
0ZAJL2:  PROC REORDER;
-        DCL   SYSIN     FILE INPUT;
0/*      VOLUME SET TABLE FOR FREE SPACE LISTING     */
         DCL 1 ZAJLVOL BASED(ZAJLPTR),
               2 NSETS   FIXED BIN,
               2 NINSET  FIXED BIN,
               2 SET(J REFER(NSETS)),   /* J IS A DUMMY */
                 3 SETNAME CHAR(6),
                 3 SETVOL(K REFER(NINSET)) CHAR(6); /* K IS A DUMMY */
         DCL ZAJLPTR PTR EXT;
-/* STRUCTURE TO HOLD TABLE OF NODES  */
         DCL   1    NODES(200) EXTERNAL,
 /*                   NODE NAME       */
                    2 NDN     CHAR(44),
 /*                   LENGTH OF NAME  */
                    2 NDNLN   FIXED BIN(15),
 /*                   VOLUME SERIAL   */
                    2 NDVOL   CHAR(6),
 /*                   INDEX ADDRESS   */
                    2 NDTTR   CHAR(3),
 /*                   FLAGS           */
                    2 NDFLG   BIT(8) ALIGNED;
-/* TABLE OF VOLUMES FOR WHICH FREE SPACE LISTING IS REQUIRED  */
         DCL   SPVOL(20) EXT CHAR(6) INIT((20)(6)' ');
-/* STRUCTURE TO HOLD COMMON COUNTERS */
         DCL   1    CTRS EXTERNAL,
 /*                   LAST ENTRY IN NODE TABLE       */
                    2 NND     FIXED BIN(15),
 /*                   LAST ENTRY IN DATASET TABLE    */
                    2 NDS     FIXED BIN(15),
 /*                   CURRENT NODE                   */
                    2 JND     FIXED BIN(15),
 /*                   FIRST DATASET ENTRY IN ALPHAMERIC SEQUENCE  */
                    2 ALPHA   FIXED BIN(15);
-/* OTHER DECLARATIONS */
         DCL   VOL  CHAR(6),
               NVOL FIXED BIN STATIC INIT(1),
               NAME CHAR(45);
         DCL FIRSTTIME BIT(1) STATIC ALIGNED INIT('1'B);
-/*      INITIALISATION     */
0        ON ENDFILE(SYSIN) GO TO BACK;
-/*      READ A PARAMETER CARD   */
0READ:
         GET EDIT(VOL,NAME)   (A(6),X(3),A(71));
         IF NAME='FREE SPACE'
           THEN DO;
                  DO J=1 TO NSETS;
                    IF VOL=SETNAME(J)
                      THEN DO;
                             DO K=1 TO NINSET;
                               IF SETVOL(J,K) = '      '
                                       THEN GO TO LABEL;
                        /* IGNORE BLANK DISK SERIAL NUMBERS IN LIST */
                               SPVOL(NVOL) = SETVOL(J,K);
                               NVOL = NVOL + 1; /* ADD 1 TO SUBSCRPT*/
 LABEL:                      END;  /* K LOOP */
                             GO TO READ;
                           END;
                  END; /* J */
                  SPVOL(NVOL)=VOL;
                  NVOL=NVOL+1;
                  GO TO READ;
                END;
         NND=NND+1;
         J=VERIFY(NAME,'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-#@$');
         NDN(NND)=NAME;
         NDNLN(NND)=J-1;
         NDTTR(NND)='   ';
         NDFLG(NND)='00000000'B;
0BACK:
         IF FIRSTTIME & (NND+NVOL)=1
           THEN PUT SKIP EDIT('NO VALID PARAMETER CARDS') (A);
         FIRSTTIME='0'B;
         RETURN;
0        END;
