*                                       THIS SUBROUTINE OBTAINS THE
*        DSNAME                         DSNAME OF A FILE FROM ITS JFCB
*                                       AND RETURNS IT TO THE CALLING
*                                       MODULE
*        /* PROG TO SHOW USE OF DSNAME FUNCTION                      */
*DSNTEST:PROC    OPTIONS (MAIN) ;
*DECLARE CAA11   CHAR (8),
*        CAA12   CHAR (44) ,
*        DSNAME  RETURNS (CHAR(44)) ;
*        CAA11 = 'FRED' ;
*        CAA12 = DSNAME  (CAA11) ;
*        DISPLAY (CAA12) ;
*        END     DSNTEST ;
*
DSNAME   ENTER   SAVE=(14,11)
         LM    5,6,0(1)                 LOAD PARAMETER ADDRESSES
         L     5,0(5)
         L     6,0(6)                   LOAD STRING ADDRESSES FROM SDVS
         MVC   DCBA+40(8),0(5)          MOVE DDNAME TO DCB
         RDJFCB (DCBA)                  READ JFCB FOR FILE
         MVC   0(44,6),JFCBAREA         RETIRN DSNAME
         EXIT    RESTORE=(14,11)
*
DCBA     DCB   DSORG=PS,MACRF=GM,DDNAME=DUMMY,EXLST=JFCBAD
JFCBAD   DS    0F
         DC    X'87'
         DC    AL3(JFCBAREA)
JFCBAREA DS    0F
         DS    CL176
*
         END
