OVERLAY FMAP SIZE 8 IN 10 IN OFFSET .5 IN .5 IN ;
ORIENT 00 ;

   FONT FONT06 g1756i DDNAME FONTDD ;
   FONT FONT08 g0758i DDNAME FONTDD ;
   FONT FONT10 g0750i DDNAME FONTDD ;
   FONT FONT12 g075bi DDNAME FONTDD ;
   FONT FONT14 g075di DDNAME FONTDD ;
   FONT FONTs1 p0750p DDNAME FONTDD ;

   position absolute .0 in absolute .0 in ;
   drawbox 4.2 in 8.8 in bold solid;

   position absolute 0 in absolute 0 in;
    drawbox 4.2 in 1.7 in
     shade all screen light
     withtext box 1 0 modern top left
      line font08 char '  EMERGENCY (Security) 2222'
     withtext box 1 0 modern top right
      line font08 char 'OPERATOR  3311  '
     withtext box 1 0 modern center center
      line font10 char
          'Do not unplug this digital telephone from its assigned'
      line font10 char
          'wall jack.  Unauthorized connection of modems or other'
      line font10 char
          'equipment on this phone line will cause damage to the'
      line font10 char
          'switching system.  Contact the Telecommunications'
      line font10 char
          'Services department if you need to relocate or connect'
      line font10 char
          'special equipment to the system'
     withtext box 1 0 modern right bottom
      line font14 char 'PhoneMail'
           font06 char 'TM';

   position absolute 0  in absolute 1.7 in;
    drawbox 4.2 in .3 in bold
      withtext box 1 0 modern center left
          line fonts1 hex 'fc'
      withtext box 1 0 modern center right
          line fonts1 hex 'fc'
      withtext box 1 0 modern center center
        line font12 char '(213) 797-&RLEXT  COMNET 374-&RLEXT';

   position absolute 0 in absolute 2 in;
    drawbox 4.2 in .15 in bold
      shade all light;

   position absolute 0  in absolute 2.15 in;
    drawbox 2.1 in 2 in 0
      withtext box 1 0 modern center left
        line font10 char '   F=Flash'
        line font10 char '   ACCT #'
        line font10 char '   SET '
        line font10 char '   CAMP-ON '
        line font10 char '   CANCEL FWD'
        line font10 char '   CONFERENCE'
        line font10 char '   FORWARD  '
        line font10 char '   INTERCOM'
        line font10 char '   PARK  '
      withtext box 1 0 modern center right
        line font10 char '   '
        line font10 char 'F *2  '
        line font10 char '*566  '
        line font10 char 'F #1  '
        line font10 char '##9  '
        line font10 char 'F *4  '
        line font10 char '#9  '
        line font10 char 'F**6  '
        line font10 char 'F *6  ';

   position absolute 2.1 in absolute 2.15 in;
    drawbox 2.1 in 2 in 0
      withtext box 1 0 modern center left
        line font10 char '          '
        line font10 char '  PICK-UP (EXT)'
        line font10 char '  PICK-UP (GRP)'
        line font10 char '  PRIVACY (EXT)'
        line font10 char '  REPEAT'
        line font10 char '  SAVE '
        line font10 char '  SET STA SPD'
        line font10 char '  STA SPD '
        line font10 char '  SYS SPD'
      withtext box 1 0 modern center right
        line font10 char '          '
        line font10 char '*3  '
        line font10 char '**3  '
        line font10 char 'F #2  '
        line font10 char '#7  '
        line font10 char 'F #4  '
        line font10 char '##3  '
        line font10 char '#3  '
        line font10 char '#6  ';

   position absolute 0 in absolute 4.15 in;
    drawbox 4.2 in .15 in 0
     shade all light;

   position absolute .95 in 4.45 in;
     drawbox .6  in .3 in
       repeat down 6 spaced .2 in;

   position absolute 1.6 in absolute 4.30 in;
    drawbox 2.6 in 3.5 in  0
      shade all light;

   position absolute 2.4 in absolute 4.45 in;
      drawbox .45 in .3 in bold
        repeat across 1 spaced .1 in;

   position absolute 2.15 in absolute 4.5 in;
      drawbox .2 in .3 in 0
        withtext box 1 180 modern center center
          line fonts1 hex 'ed';

   position absolute 3.5 in absolute 4.5 in;
      drawbox .2 in .3 in 0
        withtext box 1 0 modern center center
          line fonts1 hex 'ed';

   position absolute 2.0 in absolute 4.9 in;
       drawbox .5 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'RECORD';

   position absolute 2.7 in absolute 4.9 in;
       drawbox .5 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'SKIP';

   position absolute 3.35 in absolute 4.9 in;
       drawbox .5 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'LISTEN';

   position absolute 2.0 in absolute 7.7 in;
       drawbox .5 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'STOP';

   position absolute 2.7 in absolute 7.7 in;
       drawbox .5 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'HELP';

   position absolute 3.35 in absolute 7.7 in;
       drawbox .5 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'ENTER';

   position absolute 1.65 in absolute 6 in;
       drawbox .3 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char ' SAV';

   position absolute 3.9 in absolute 6 in;
       drawbox .3 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'DEL ';

   position absolute 1.65 in absolute 6.7 in;
       drawbox .3 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char ' REV';

   position absolute 3.9 in absolute 6.7 in;
       drawbox .3 in .2 in 0
        withtext box 1 0 modern center center
          line font10 char 'FWD ';

   position absolute 2.05 in absolute 5.2 in;
      drawbox .45 in .45 in bold
        repeat across 2 spaced .2 in;

   position absolute 2.05 in absolute 5.87 in;
      drawbox .45 in .45 in bold
        repeat across 2 spaced .2 in;

   position absolute 2.05 in absolute 6.52 in;
      drawbox .45 in .45 in bold
        repeat across 2 spaced .2 in;

   position absolute 2.05 in absolute 7.2  in;
      drawbox .45 in .45 in bold
        repeat across 2 spaced .2 in;

   position absolute 0 in absolute 4.30 in;
    drawbox 1.6 in .5 in bold
      repeat down 6
      withtext box 1 0 modern center left
        line font10 char '   MSG'
        line font10 char '   WTG'
      withtext box 2 0 modern center left
        line font08 char '   &R1A '
        line font08 char '   &R1B '
      withtext box 3 0 modern center left
        line font10 char '   STA'
        line font10 char '   SPD'
      withtext box 4 0 modern center left
        line font10 char '   FWD'
        line font08 char '    '
      withtext box 5 0 modern center left
        line font10 char '   CAMP'
        line font10 char '  '
      withtext box 6 0 modern center left
        line font10 char '   FLASH'
        line font10 char '  '
      withtext box 7 0 modern center left
        line font10 char ' '
        line font10 char '   &RLEXT';

   position absolute 0 in absolute 7.8 in;
    drawbox 4.2 in .65 in 0
     shade all light;

   position absolute .4 in absolute 8.2 in;
    drawbox .13 in .13 in;

   position absolute .88 in 8.1 in;
     drawbox .68 in .3 in bold
      repeat across 2 spaced 11 mm ;

   position absolute 0 in absolute 8.45 in;
    drawbox 1 in .25 in 0
     withtext box 1 0 modern center center
       line font08 char 'CALL WTG' ;

   position absolute .9 in absolute 8.45 in;
    drawbox 1 in .25 in 0
     withtext box 1 0 modern center left
       line font10 char 'HOLD' ;

   position absolute 2 in absolute 8.45 in;
    drawbox 1 in .25 in 0
     withtext box 1 0 modern center left
       line font10 char 'CONNECT' ;

   position absolute 3.1 in absolute 8.45 in;
    drawbox 1 in .25 in 0
     withtext box 1 0 modern center left
       line font10 char 'TRANSFER' ;
