GRPTEST  $PROLOG
         LA    R1,=C'AUTH'
         SVC   231
L1       ICHEINTY LOCATE,TYPE='GRP',ACTIONS=ACT1,WKAREA=WK1,           X
               ENTRY=GRP1
PT1      EQU   *
L2       ICHEINTY LOCATE,TYPE='CON',WKAREA=WK2,ENTRY=CON1,             X
               ACTIONS=(ACT2,ACT3,ACT4,ACT5,ACT6)
PT2      EQU   *
         DC    H'0'
ACT1     ICHEACTN FIELD=ACL,MF=L
ACT2     ICHEACTN FIELD=FLAG2,MF=L
ACT3     ICHEACTN FIELD=FLAG3,MF=L
ACT4     ICHEACTN FIELD=FLAG4,MF=L
ACT5     ICHEACTN FIELD=FLAG5,MF=L
ACT6     ICHEACTN FIELD=FLAG6,MF=L
GRP1     DC    X'04'
         DC    CL8'TS00'
CON1     DC    X'11'
         DC    CL8'TS52'
         DC    X'00'
         DC    CL8'TSE1'
WK1      DC    F'512'
         DC    CL256' '
         DC    CL256' '
WK2      DC    F'256'
         DC    CL256' '
         END
