USERS    CSECT
         REGS
         SAVE  (14,12),T,USERS_TSO_COMMAND
         USING USERS,R15
         LA    R11,SAVEARE3
         ST    R13,SAVEARE3+4
         ST    R11,8(,R13)
         LR    R13,R11
         B     STAR3
         DROP  R15
         SPACE 2
SAVEARE3 DC    18F'0'
         SPACE 2
STAR3    DS    0H
         USING SAVEARE3,R13
         SPACE 2
         LM    R6,R9,CLEARREG
         MVCL  R6,R8                    CLEAR TABLE
         SPACE
         L     R1,16                    FIND CVT
         L     R2,X'94'(,R1)            FIND BASEA (M.S.RES.DATA)
         LA    R3,TABLE                 NAME TABLE
         LA    R4,10                    BXLE INCREMENT
         L     R5,=A(TABLE+LENTABLE)    BXLE END
         SR    R6,R6                    COUNT OF USERS
CSC8LOOP ICM   R2,15,0(R2)
         BZ    CSC8END                  WHEN DONE
         CLI   28(R2),1                 TSO USER ID?
         BNE   CSC8LOOP
         LA    R6,1(,R6)                BUMP USER COUNT
         MVC   0(8,R3),8(R2)            MOVE USERID TO TABLE
         BXLE  R3,R4,CSC8LOOP
         TPUT  MSG0V,L'MSG0V
         SPACE 2
CSC8END  CVD   R6,D0UBLE                NUM USERS MSG
         MVC   NUMUSERS(4),=X'40202020'
         ED    NUMUSERS(4),D0UBLE+6
         TPUT  NUMUSERS,LNSG
         SPACE 2
         LR    R5,R3                    SET END OF TABLE
         LA    R2,TABLE                 SET START OF TABLE
         LR    R6,R4                    FOR SORT
         LR    R7,R5
         SH    R7,=H'20'                BACK UP ONE ENTRY
         LR    R8,R2                    SAVE FIRST ADDRESS
SORTLOOP CLC   0(8,R2),10(R2)           COMPAIR TWO
         BNH   SORTBXLE
         LR    R8,R2                    LAST SWAP
         XC    0(8,R2),10(R2)
         XC    10(8,R2),0(R2)
         XC    0(8,R2),10(R2)
SORTBXLE BXLE  R2,R6,SORTLOOP
         LR    R7,R8                    SAVE LAST SWAP
         LA    R2,TABLE                 REINIT
         LR    R8,R2                    REINIT LAST SWAP
COMPAIR  CR    R2,R7                    DONE?
         BL    SORTLOOP
         SPACE 2
* SKIP FOR NON BLANK NAME
         SPACE 1
BLNKL00P CLI   0(R2),C' '
         BNE   PRNTLOOP
         BXLE  R2,R4,BLNKL00P
         SPACE 1
* OUTPUT NAMES
         SPACE 1
PRNTLOOP LR    R3,R5                    COMPUTE LENGTH
         SR    R3,R2
         BP    *+6                      IF ANSWER IS ZERO
         LR    R3,R4                    ONLY 1 USER IS ON
         TPUT  (2),(3),R
         SPACE 1
         L     R13,SAVEARE3+4
         RETURN (14,12),RC=0
         SPACE 1
NUMUSERS DC    X'40202020',C' USERS LOGGED ON'
LNSG     EQU   *-NUMUSERS
MSG0V    DC    C'* TABLE OVERFLOW *'
D0UBLE   DC    D'0'
         SPACE 2
         SPACE 1
         LTORG
         SPACE 1
CLEARREG DC    A(TABLE,2000),A(0),X'40000000'
TABLE    DS    200CL10' '
LENTABLE EQU   *-TABLE
         END   USERS
