 TITLE 'RXVSAMSG - Error Messages for RXVSAM'
         PUSH PRINT
         PRINT OFF
         MACRO
&LABEL   GENMSGS &GEN=DSECT
         AIF   ('&GEN' EQ 'DSECT').OK
         AIF   ('&GEN' EQ 'CSECT').OK
         MNOTE 8,'GENMSGS MACRO STATEMENT HAD AN INVALID VALUE'
         AGO   .ENDMAC
.OK      ANOP
&LABEL   &GEN
M$ALLOK  DS      0CL38
         DC      CL4'0000'
         DC      CL4'I'
         DC      CL30'Request successfully processed'
M$BADARG DS      0CL31
         DC      CL4'0001'
         DC      CL4'E'
         DC      CL23'Invalid argument passed'
M$BADOPN DS      0CL19
         DC      CL4'0002'
         DC      CL4'E'
         DC      CL11'Open failed'
M$BADCLO DS      0CL20
         DC      CL4'0003'
         DC      CL4'E'
         DC      CL12'Close failed'
M$EOF    DS      0CL19
         DC      CL4'0004'
         DC      CL4'W'
         DC      CL11'End of File'
M$PREVOP DS      0CL28
         DC      CL4'0005'
         DC      CL4'E'
         DC      CL20'File is already open'
M$NOBLK  DS      0CL46
         DC      CL4'0006'
         DC      CL4'E'
         DC      CL38'Unable to access RXVSAM BLOCK variable'
M$NORECV DS      0CL67
         DC      CL4'0007'
         DC      CL4'E'
         DC      CL46'REXX record variable could not be accessed or '
         DC      CL13'was undefined'
M$DUPL   DS      0CL24
         DC      CL4'0008'
         DC      CL4'E'
         DC      CL16'Duplicate record'
M$VMSG   DS      0CL38
         DC      CL4'0010'
         DC      CL4'E'
         DC      CL30'Unable to save VSAM error data'
M$RMSG   DS      0CL41
         DC      CL4'0011'
         DC      CL4'E'
         DC      CL33'Unable to set return message text'
M$CLOSAC DS      0CL77
         DC      CL4'0012'
         DC      CL4'E'
         DC      CL46'ACB was not available to perform CLOSE request'
         DC      CL23' - file may not be open'
M$NOACB  DS      0CL71
         DC      CL4'0014'
         DC      CL4'E'
         DC      CL41'ACB was not available to perform request '
         DC      CL22'- file may not be open'
M$BADSCB DS      0CL56
         DC      CL4'0015'
         DC      CL4'E'
         DC      CL48'Unable to obtain max record length for this file'
M$NOTFND DS      0CL24
         DC      CL4'0016'
         DC      CL4'W'
         DC      CL16'Record not found'
M$BWDNF  DS      0CL87
         DC      CL4'0016'
         DC      CL4'W'
         DC      CL47'Record not found - a FULL KEY must be specified'
         DC      CL32' when issuing a STARTBWD request'
M$NORLEN DS      0CL41
         DC      CL4'0017'
         DC      CL4'E'
         DC      CL33'Cannot determine length of record'
M$BADUPD DS      0CL41
         DC      CL4'0018'
         DC      CL4'E'
         DC      CL33'Unable to modify RPL for "UPDate"'
M$BADFUN DS      0CL23
         DC      CL4'0019'
         DC      CL4'E'
         DC      CL15'Function failed'
M$NOREC  DS      0CL40
         DC      CL4'0020'
         DC      CL4'E'
         DC      CL32'Unable to update RECORD variable'
M$NOIN   DS      0CL34
         DC      CL4'0021'
         DC      CL4'E'
         DC      CL26'File is not open for INPUT'
M$NOOUT  DS      0CL35
         DC      CL4'0022'
         DC      CL4'E'
         DC      CL26'File is not open for OUTPUT'
M$BADDSW DS      0CL42
         DC      CL4'0023'
         DC      CL4'E'
         DC      CL34'Unable to switch to DIR processing'
M$NOGEN  DS      0CL41
         DC      CL4'0024'
         DC      CL4'E'
         DC      CL33'READGENERIC only allowed for KSDS'
M$NONNUM DS      0CL45
         DC      CL4'0025'
         DC      CL4'E'
         DC      CL37'Non-numeric key specified for an RRDS'
M$NOESDS DS      0CL48
         DC      CL4'0026'
         DC      CL4'E'
         DC      CL40'This function is not allowed for an ESDS'
M$NORRN  DS      0CL33
         DC      CL4'0027'
         DC      CL4'E'
         DC      CL25'Unable to set RXVSAM_RRN#'
M$NOPOS  DS      0CL55
         DC      CL4'0088'
         DC      CL4'E'
         DC      CL47'READPREV attempted without a previous STARTBWD '
M$NOGET  DS      0CL59
         DC      CL4'0092'
         DC      CL4'E'
         DC      CL47'REWRITE or DELETE attempted without a previous '
         DC      CL4'READ'
M$BADRL  DS      0CL99
         DC      CL4'0108'
         DC      CL4'E'
         DC      CL48'Record length = 0, > max, < key length (KSDS) or'
         DC      CL43' not equal to slot size (fixed length RRDS)'
.ENDMAC  ANOP
         MEND
         POP PRINT
         PRINT GEN
RXVSAMSG CSECT
RXVSAMSG AMODE 31
RXVSAMSG RMODE ANY
RXVSAMSG GENMSGS GEN=CSECT
         END   RXVSAMSG
