         MACRO
         SGIEC3TP
         COPY  SGGBLPAK
         AIF   (NOT &SGDMGTB(4)).END2
         PUNCH ' INCLUDE CQ513(IGC058) '
         AIF   (NOT &SGDCLSB(80)).END2                            M0470
         PUNCH ' INCLUDE CQ513(IECTATEN)'                         M0470
.END2    AIF   (NOT &SGDMGTB(3)).END1
         PUNCH ' INCLUDE CQ519(IECKQQ01) '
.END1    AIF   (NOT &SGDMGTB(5)).END0
         PUNCH ' INCLUDE CQ548(IEDQEB) '
         PUNCH ' INCLUDE CQ548(IEDQATTN) '
.END0    MEND
