)BODY
%------INTERACTIVE VS FORTRAN COMPILE AND LINK EDIT---------------------
%
%
%      This facility will compile a VS FORTRAN program for you and link
%      a load library if RC < 8. Output is directed to USERID.FORT.LIST
%      Do not change NODECK option. other options may be changed.
%
%      Unquoted dataset names will be prefixed by your user-id. Enter YE
%      if you want the output printed . Enter PFK3/15 to exit.
%
%      YOU WILL GET ABEND S0C4 IF YOUR LOGON SIZE IS LESS THAN 2048K.
%
%      You can specify an additional search library for link edit. The F
%      libraries are automatically included.
%
+ HEWL OPT :%====>_LDT
+ FORT OPT :%====>_OPT
                                         +
+   PRINT WANTED      :%====>_PRTOPT
+   SOURCE DSN        :%====>_SOURCE
+   TARGET LIBRARY    :%====>_LOAD
+   INCLUDE LIBRARY   :%====>_LOAD1
+   LOAD MODULE NAME  :%====>_LNAME   +
)INIT
 .CURSOR=SOURCE
 &PRTOPT='NO'
 &OPT='NODECK,OBJECT,XREF,OPT(0)'
 &LDT='MAP,XREF,LET'
 &LNAME=&Z
 &SOURCE='SOURCE.PGMS(XXXXXXXX)'
 &LOAD='LOADLIB'
 &LOAD1=&Z
)END
