         MACRO
&LABEL   PKA   &BD1,&BD2
.*
.*       Generate PKA instruction in IFOX00
.*
         DS    0H
&LABEL   DC    0XL6'00'                Set Instruction Length of 6
.*
.*       Use MVC opcode to generate Base and Displacement fields
.*
         MVC   &BD1,&BD2               OpCode overwritten to E9
.*
.*       Org back to reset the Opcode to E9
.*
         ORG   *-6
         DC    X'E9'                   Opcode set to E9
         DC    AL1(L'&BD2-1)           Set 2nd operand length
.*
.*       Get back to where we were
.*
         ORG
         MEND
