//JCCCG   PROC SOUT='*',JCC='JCC',
//        INFILE='',JOPTS='-o'
//********************************************************************
//*
//* Name: SYS2.PROCLIB(JCCCG)
//*
//* Desc: Compile and execute C program using JCC, PRELINK and LOADER
//*
//********************************************************************
//COMPILE  EXEC PGM=JCC,
//         PARM='-I//DDN:JCCINCL //DDN:SYSIN &JOPTS'
//STEPLIB  DD   DSN=&JCC..LINKLIB,DISP=SHR
//JCCINCL  DD   DSN=&JCC..INCLUDE,DISP=SHR
//JCCINCS  DD   DSN=&JCC..INCLUDE,DISP=SHR
//JCCOUTPT DD   UNIT=SYSDA,SPACE=(TRK,(50,20)),DISP=(,PASS),DSN=&&OUTPT
//STDOUT   DD   SYSOUT=&SOUT
//JCCOASM  DD   UNIT=VIO,SPACE=(3200,(200,100),RLSE),DSN=&&OBJ,
//         DCB=(RECFM=FB,LRECL=80,BLKSIZE=3200),DISP=(,PASS)
//SYSIN    DD   DSN=&INFILE,DISP=SHR
//*
//PRELINK  EXEC PGM=PRELINK,
//         PARM='-r //DDN:L //DDN:O //DDN:I'
//STEPLIB  DD   DSN=&JCC..LINKLIB,DISP=SHR
//STDOUT   DD   DUMMY
//L        DD   DSN=&JCC..OBJ,DISP=SHR
//I        DD   DSN=&&OBJ,DISP=(OLD,DELETE)
//O        DD   UNIT=VIO,SPACE=(3200,(200,100),RLSE),DSN=&&OBJMOD,
//         DCB=(RECFM=FB,LRECL=80,BLKSIZE=3200),DISP=(,PASS)
//*
//GO       EXEC PGM=LOADER,PARM='NCAL,NOPRINT,EP=ST000000'
//SYSLIN   DD DSN=&&OBJMOD,DISP=(OLD,DELETE)
//SYSLOUT  DD SYSOUT=&SOUT
//SYSPRINT DD SYSOUT=&SOUT
//STDOUT   DD SYSOUT=&SOUT
//STDERR   DD SYSOUT=&SOUT
//STDIN    DD DDNAME=SYSIN
