//JCCCL   PROC SOUT='*',JCC='JCC',
//        OUTFILE='',INFILE='',JOPTS='-o -list=//DDN:SYSPRINT'
//********************************************************************
//*
//* Name: SYS2.PROCLIB(JCCCL)
//*
//* Desc: Compile and link C program using JCC, PRELINK and IEWL
//*
//********************************************************************
//COMPILE  EXEC PGM=JCC,
//         PARM='-I//DDN:JCCINCL //DDN:SYSIN &JOPTS'
//STEPLIB  DD   DSN=&JCC..LINKLIB,DISP=SHR
//JCCINCL  DD   DSN=&JCC..INCLUDE,DISP=SHR
//JCCINCS  DD   DSN=&JCC..INCLUDE,DISP=SHR
//JCCOUTPT DD   UNIT=SYSDA,SPACE=(TRK,(50,20)),DISP=(,PASS),DSN=&&OUTPT
//STDOUT   DD   SYSOUT=&SOUT
//SYSPRINT DD   SYSOUT=&SOUT
//JCCOASM  DD   UNIT=VIO,SPACE=(3200,(200,100),RLSE),DSN=&&OBJ,
//         DCB=(RECFM=FB,LRECL=80,BLKSIZE=3200),DISP=(,PASS)
//SYSIN    DD   DSN=&INFILE,DISP=SHR
//*
//PRELINK  EXEC PGM=PRELINK,
//         PARM='-r //DDN:L //DDN:O //DDN:I'
//STEPLIB  DD   DSN=&JCC..LINKLIB,DISP=SHR
//STDOUT   DD   SYSOUT=&SOUT
//L        DD   DSN=&JCC..OBJ,DISP=SHR
//I        DD   DSN=&&OBJ,DISP=(OLD,DELETE)
//O        DD   UNIT=VIO,SPACE=(3200,(200,100),RLSE),DSN=&&OBJMOD,
//         DCB=(RECFM=FB,LRECL=80,BLKSIZE=3200),DISP=(,PASS)
//*
//LKED     EXEC PGM=IEWL,PARM='NCAL,MAP,LIST,XREF,NORENT'
//SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(5,2))
//SYSPRINT DD SYSOUT=&SOUT
//SYSLIN   DD DSN=&&OBJMOD,DISP=(OLD,DELETE)
//SYSLMOD  DD DSN=&OUTFILE,DISP=SHR
