%TUTORIAL ---------------------- QUEUE COMMAND ------------------------
%OPTION ===>_ZCMD
+
+                            Job Related Commands
+
+   The job related commands allow veiwing of job related datasets (both
+   SYSIN and SYSOUT), and allows those sysouts in hold classes to be
+   canceled or requeued.  Only jobs begining with your userid can have
+   their datasets viewed.
+
+   The operand%jobname+in the following commands can be either the actu
+   jobname, or the JES2 job number, or an asterisk (indicating use the
+   one previously requested).
+
+  %DJ jobname+
+        This displays the queue, class, position, job name, job number,
+        JES2 priority, number of lines, execution system id, and output
+        destination.
+
+                          (continued on next page)
)PROC
   &ZUP = BFTQU000
   &ZCONT = BFTQU021
)END
