//SG0080  JOB  (SYSGEN),
//             'ACCEPT TIOCS et al',
//             CLASS=A,
//             MSGCLASS=A,
//             MSGLEVEL=(1,1),
//             REGION=8000K
//*********************************************************************
//*
//*                       MVS 3.8 SYSGEN
//*                       ==============
//*
//* DESC: ACCEPT various MVS related FMIDs
//*
//*
//*********************************************************************
//JOBCAT   DD  DISP=SHR,DSN=SYS1.VMASTCAT
//MVSACC  EXEC SMP4
//SMPCNTL  DD  *
 ACCEPT G(
          EML1102                            /* Multi-Leaving WS    */
          EMS1102                            /* MSS                 */
          FDZ1610                            /* DSF                 */
          ETI1106                            /* TIOC                */
          ETC0108                            /* TCAM                */
         )
     DIS(WRITE)
     NOAPPLY
.
//OOOPS EXEC PGM=OOOOPS,COND=(0,EQ)
//
