//SG0400   JOB (SMP4),
//             'Cleanup',
//             CLASS=S,
//             TIME=1439,
//             REGION=8000K,
//             MSGCLASS=A,
//             MSGLEVEL=(1,1),
//             NOTIFY=HERC01
//********************************************************************
//*
//* Name: SYS1.SYSGEN.CNTL(SG0400)
//*
//* Desc: Remove all ACCEPTED and SUPERCEEDED SYSMODS from SMPPTS
//*       Remove all SMPTLIB files
//*
//********************************************************************
//ACCEPT  EXEC SMPACC
//SMPWRK3  DD  UNIT=3350,SPACE=(CYL,(50,10,1000)),DCB=(BLKSIZE=3120,
//             LRECL=80)
//SMPCNTL  DD  *
 REJECT PURGE
 .
//
