./ CHANGE      SEQFLD=736,NAME=DSSSIM
    /*FIX026:EXPAND THE NUMBER OF DIGITS PRINTED FROM 5 TO 7  /*FIX026*/
           (HDSR,HSQN) FIXED BIN(15) INIT(0),   /* DSR PTR */ /*FIX026*/
            #HST       FIXED BIN(31) INIT(0), /*HIST REC CT*/ /*FIX026*/
            (#CND,#DSK)      FIXED BIN(31) INIT(0), /* NEW ×*//*FIX026*/
       PUT EDIT('TOTAL SEEKS = ',DSR_DSREF(NDSP),             /*FIX026*/
                '  SEEK RATE = ',                             /*FIX026*/
                 TSPA,' SEEKS/SEC.')                          /*FIX026*/
                (SKIP(2),COL(15),A,F(09),A,F(6,1),A);         /*FIX026*/
          (SKIP(2),COL(15),A,F(5),X(4),A,F(09),A,F(6,1),A);   /*FIX026*/
          DTEC8) (SKIP(2),COL(49),A,SKIP(2),                  /*FIX026*/
                    COL(12),A,F(7),A,                         /*FIX026*/
          A,F(7),A,COL(60),A,COL(91),A,A,                     /*FIX026*/
                    COL(12),A,F(7),COL(60),                   /*FIX026*/
          A,COL(91),A,F(4),A,                                 /*FIX026*/
                    COL(12),A,F(7,1),A,COL(91),A,F(4),A);     /*FIX026*/
            2 F(5),A,F(7),F(5),A,F(8),X(5),F(3),F(8),         /*FIX026*/
                     X(4),P'ZZZZZZZ',                         /*FIX026*/
            2 F(5),A,F(7),F(5),A,2 F(8),                      /*FIX026*/
                     X(4),P'ZZZZZZZ',P'ZZZZV.Z',X(3),         /*FIX026*/
           PUT EDIT(PVC(I),M,' -',PLNE)                       /*FIX026*/
                   (SKIP,COL(2),A,COL(3),F(7),A,COL(12),A);   /*FIX026*/
          ELSE PUT EDIT(PVC(I),PLNE)                          /*FIX026*/
                       (SKIP,COL(2),A,COL(12),A);             /*FIX026*/
          #CND,' RECORDS PROCESSED')                          /*FIX026*/
                (SKIP(2),COL(CIM),A,A,F(10),A);               /*FIX026*/
          #CND,' RECORDS PROCESSED')                          /*FIX026*/
                (SKIP(2),COL(CIM),A,A,F(10),A);               /*FIX026*/
